### ISSUE TITLE
Get working inside FreeNAS Jail

### ISSUE THREAD

**Issue by Arcanemagus** [Tautulli/Tautulli#1]
I'll try to put some time into figuring this out later tonight, on attempting to launch this in the same jail plexWatch runs inside I get the following error.

```
Traceback (most recent call last):
  File "PlexPy.py", line 23, in <module>
    from plexpy import webstart, logger
  File "/usr/local/bin/plexpy/plexpy/__init__.py", line 24, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

Looks like a missing required module to me.

**Comment by drzoidberg33** [comment]
Thanks, I'll look into this. May be possible to package the library with the app.

**Comment by Arcanemagus** [comment]
Looks like in FreeBSD they decided to package the SQLite3 module separately, it can be installed on the system with the following command:

```
pkg install py27-sqlite3
```

So either that should be included in the setup instructions, or possibly the module included in the project :wink:.

**Comment by Arcanemagus** [comment]
Looks like another missing module:

```
pkg install py27-openssl
```

```
New packages to be INSTALLED:
        py27-openssl: 0.15.1
        py27-cryptography: 0.8.2
        py27-six: 1.8.0
        py27-cffi: 1.1.1
        py27-pycparser: 2.10
        py27-asn1: 0.1.7,1
```

---

Also since I forgot it for sqlite3:

```
New packages to be INSTALLED:
        py27-sqlite3: 2.7.9_6
        py27-setuptools27: 17.0
```

**Comment by drzoidberg33** [comment]
Thanks for looking into this. As FreeBSD is not an officially supported platform I won't be dedicating too much to this at the moment. Once I have release version 1 then maybe somebody will be willing to create a freeNAS plugin ::

**Comment by Arcanemagus** [comment]
I'll just put some installation instructions in the Wiki tonight then, looks great so far btw ;)

**Comment by Arcanemagus** [comment]
Oh btw, if by "officially supported platform" you meant Plex, it's is supported by them...

**Comment by Arcanemagus** [comment]
Gotta love package managers, the instructions on the wiki will get you from this:

```
root@plexpy:/ # pkg info
pkg-1.5.4                      Package manager
root@plexpy:/ #
```

To a working PlexPy installation :wink:.

**Comment by drzoidberg33** [comment]
Awesome! Thank you for this, really appreciate it.
