### ISSUE TITLE
multiple viewings are not merged into one

### ISSUE THREAD

**Issue by desimaniac** [Tautulli/Tautulli#1001]
**Version:**
1.4.17 
**Branch:**
master
**Commit hash:**
e85cdd5609c3f5795baaf2d45c484eb652497ec2
**Operating system:**
Docker via Synology DSM 6.1 (Linux 3.10.102)
**Python version:**
2.7.13 

**What happened?**
Plexpy doesnt merge multiple viewings into one single viewing for certain items. 

![image](https://cloud.githubusercontent.com/assets/5501908/24226036/1c978dd0-0f32-11e7-8855-35df0f76f761.png)

![image](https://cloud.githubusercontent.com/assets/5501908/24226041/2598a50e-0f32-11e7-83be-10aa1be2c43c.png)

**Link to logs:**
https://gist.github.com/desimaniac/fa9520c0a5f6cba33effb623a4bde80c

**Comment by JonnyWong16** [comment]
Are they all increasing progress? i.e. the user didn't rewind the movie.

**Comment by desimaniac** [comment]
Im quite sure they dont rewind. 

is there a way i can get the details of what position of the movie they start and stop at?

**Comment by JonnyWong16** [comment]
Hover your mouse over the dot on the right,

**Comment by desimaniac** [comment]
I mean like exact timestamps for the movie... (ie 2:13 or 44:33)... but the percentages are (for "OK Jaanu"): 4, 12, 27, 50, 88, 88, 100.

**Comment by JonnyWong16** [comment]
Take the percent * duration of the movie.

It looks like the progress is increasing. I have no idea.

**Comment by desimaniac** [comment]
Yeah, it's odd.

**Comment by desimaniac** [comment]
Can we get an option to merge multiple viewings together and add up the percentage? Like we can click edit, select all the viewings manually and then click merge.

**Comment by tgaguy** [comment]
I have the same issue. From a smart tv but not using the Plex ap. I access Plex on a local network via the DLNA server. I did pause this movie a couple times and did a slight rewind. but nothing like the entries here. 41 log entires in total for one movie. first 7 entries were a continuous play untill i fell asleep and the tv off timer turned the tv off.

Panasonic Viera 50" LED. TH-50CX610Z

![plexpy multiple history entries](https://user-images.githubusercontent.com/29828530/32420415-d018912c-c2ee-11e7-951f-a481ec60198a.jpg)

**Comment by abb0r** [comment]
I have the same issue. If I stop a movie and finish the rest of the movie e.g. an hour later, I get two play entries. It would be nice if we could merge two views into one.
