### ISSUE TITLE
Everything Randomly Reset?

### ISSUE THREAD

**Issue by tejasgadhia** [Tautulli/Tautulli#1002]
I've had PlexPy running perfectly for a long time now. I restarted my computer and now it seems to have lost its configuration. I had changed the port it was operating on, but when I go to that port Chrome says the page cannot be displayed. 

I opened the log file to see the service was running on the default 8181 port. So I went to localhost:8181 and now its asking me to set up PlexPy as if I've never used it. I havent done anything so far because I really dont want to lose all my historical data. Any idea how I can restore my history & configuration?

**Version:**
v1.4.17
**Branch:**
master
**Commit hash:**
e85cdd5609c3f5795baaf2d45c484eb652497ec2
**Operating system:**
Windows 10
**Python version:**
2.7
**What you did?**
Restarted Computer
**What happened?**
PlexPy launched as if it was a fresh install
**What you expected?**
PlexPy application start like normal on my custom port with previous historical data.
**How can we reproduce your issue?**
No idea.
**What are your (relevant) settings?**
N/A
**Link to logs:**
https://gist.githubusercontent.com/anonymous/9c3abc58db71ec9e26792d7d5dcdcb87/raw/6d88d3020e2d5fa1a3d958f2cab6de3b4588242c/logs

**Comment by JonnyWong16** [comment]
Database is probably fine. Probably just the config file messed up. You can also check the backups folder for backup files.

**Comment by tejasgadhia** [comment]
Thanks @JonnyWong16 - So what should I do to get PlexPy restored back to its previous state?

**Comment by JonnyWong16** [comment]
Restore backups from the backup folder.

**Comment by tejasgadhia** [comment]
Restoring from backup worked temporarily, but every computer restart it seems like the config.ini file keeps getting reset to blank values.

**Comment by JonnyWong16** [comment]
Try installing it somewhere else other than C:\PlexPy. Something like Documents where you have full permissions.
