### ISSUE TITLE
PlexPi slow to load

### ISSUE THREAD

**Issue by Rouzax** [Tautulli/Tautulli#1004]
**Version:**
VERSION 1.4.17

**Branch:**
Git Branch:	master

**Commit hash:**
Git Commit Hash:	e85cdd5609c3f5795baaf2d45c484eb652497ec2

**Operating system:**
Platform:	Server 2016

**Python version:**
Python Version:	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]

**What you did?**
Open the webconsole. PlexPy and Plex are located on 2 virtual Windows server both with 8 GB RAM and 6 CPU cores.

**What happened?**
Is is slow loading the images and page, it appears that `script.js` and `moment-with-locale.js` take 10 seconds to load.
After those are done it will seem that the homepage is loaded but in the background it is still gathering `pms_image_proxy?img=/library/metadata/85631/thumb/1490090409&width=300&height=450&fallback=poster` files and those range from 10 to 49 seconds

**What you expected?**
Faster load times 😄

**Link to logs:**
It does not seem like that there is anything in the Plex or PlexPy logs

![image](https://cloud.githubusercontent.com/assets/4103090/24322038/33d93ddc-115c-11e7-96b0-4b03fecc93ec.png)
![image](https://cloud.githubusercontent.com/assets/4103090/24322041/4901777e-115c-11e7-800a-e33f8eac9d03.png)

**Comment by JonnyWong16** [comment]
#720

**Comment by Rouzax** [comment]
I saw that issue but my PMS communication is http and not https.

**Comment by Rouzax** [comment]
@JonnyWong16 
So did some more testing.
Loading the page from the server running: `http://localhost:8182/home` it is fast. When I open it using the hostname `http://download:8182/home` it is slow.
Opening it with the IP address it is fast again, `http://192.168.2.11:8182/home`
One other weird thing I'm noting is that when I open it from the hostname it shows me the mobile login on my desktop browser, while opening the localhost or IP it is fine.
![image](https://cloud.githubusercontent.com/assets/4103090/24330090/bd7fcf7c-1217-11e7-81b7-a1d5060b50e4.png)
![image](https://cloud.githubusercontent.com/assets/4103090/24330095/ce4e25d8-1217-11e7-9109-c629df3b0e05.png)

**Comment by Rouzax** [comment]
@JonnyWong16, could you please reopen this issue. It is not the same as #720

**Comment by JonnyWong16** [comment]
It looks like a network issue on your end.

**Comment by Rouzax** [comment]
After further digging it seems it might be related to IIS ARR reverse proxy.
With my previous Windows 2012 R2 install it worked Ok but since my migration to Windows 2016 it is really slow.
Please let me know what you need to debug this.

Complete IIS log from one page opening

| date | time | s-ip | cs-method | cs-uri-stem | cs-uri-query | s-port | cs-username | c-ip | cs(Referer) | sc-status | sc-substatus | sc-win32-status | time-taken
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /users | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=4042e759-3ff1-4e31-9dca-3d2204c794c9&SERVER-STATUS=200 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/home | 200 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /css/bootstrap3/bootstrap.css | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=b9c7a680-6ac0-4d93-801f-2d1e3e4391af&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 93
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /css/opensans.min.css | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=d2c6a6e0-9009-42b7-b978-38a202c768da&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 93
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /css/plexpy.css | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=49da7159-6776-4388-a153-ee86698f732f&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 93
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /css/pnotify.custom.min.css | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=a783149e-1e58-4a04-8341-a9272dad82d2&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 93
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /css/font-awesome.min.css | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=161a509e-818a-45cb-a61a-761089880e24&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 93
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /css/dataTables.bootstrap.css | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=9a99afce-297f-4b82-8c2b-fa327c19ba09&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 93
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /css/dataTables.colVis.css | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=a327185f-fbf6-405f-b219-7fb2bc1219ad&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 93
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /css/plexpy-dataTables.css | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=662aeb5a-65e7-4648-93aa-62ec84761d15&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /js/script.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=ae5e99f0-d734-437b-b6e5-aeb78026ac8a&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /js/bootstrap.min.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=a2b9a657-29f1-4f51-b012-60171d551253&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /js/jquery.dataTables.min.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=7b375d38-0be6-4994-ad03-41d61893e7af&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /js/dataTables.colVis.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=06e4647f-ac79-4ef5-a72f-77df1554f88d&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /js/pnotify.custom.min.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=2125f204-dde7-4afd-8f20-3e1952ff6027&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /js/dataTables.bootstrap.min.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=b84bb825-1264-44ca-abb7-754077df1832&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /js/dataTables.bootstrap.pagination.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=4d71ae0b-9fe7-42da-852a-a0168e81ca0c&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /images/logo-plexpy@2x.png | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=a0ce50ad-bf95-4e7e-a772-163076941909&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /fonts/Open-Sans-regular/Open-Sans-regular.woff2 | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=83426be7-8bba-468e-a88b-4ccbb0f92a20&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/css/opensans.min.css | 304 | 0 | 0 | 31
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /fonts/fontawesome-webfont.woff2 | v=4.4.0&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=c420dd76-b3f1-428f-881d-a65a687539b8&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/css/font-awesome.min.css | 304 | 0 | 0 | 31
| 2017-04-03 | 08:38:50 | 192.168.2.12 | GET | /fonts/Open-Sans-600/Open-Sans-600.woff2 | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=cba92d84-b37b-4900-804e-12b8e270e20d&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/css/opensans.min.css | 304 | 0 | 0 | 78
| 2017-04-03 | 08:38:59 | 192.168.2.12 | GET | /js/jquery-2.1.4.min.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=e3d40283-e280-4516-8938-e2d3fb0e271e&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 9370
| 2017-04-03 | 08:38:59 | 192.168.2.12 | GET | /js/bootstrap-hover-dropdown.min.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=520486b5-98ce-4120-a5e3-7d31339391d9&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 9386
| 2017-04-03 | 08:39:00 | 192.168.2.12 | GET | /js/moment-with-locale.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=4233b8d3-4f25-4255-8665-17dea3cad986&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 10302
| 2017-04-03 | 08:39:00 | 192.168.2.12 | GET | /js/tables/users.js | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=9baed2c2-0d64-4963-ba77-9f8cd7cde887&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 10302
| 2017-04-03 | 08:39:00 | 192.168.2.12 | GET | /fonts/bootstrap3/glyphicons-halflings-regular.woff2 | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=fa6032cd-4d03-496e-9b41-75ead092be46&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/css/bootstrap3/bootstrap.css | 304 | 0 | 0 | 31
| 2017-04-03 | 08:39:00 | 192.168.2.12 | POST | /get_user_list | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=cb125555-07a6-4a31-a7bd-6715aeb47410&SERVER-STATUS=200 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 200 | 0 | 0 | 140
| 2017-04-03 | 08:39:00 | 192.168.2.12 | GET | /interfaces/default/images/gravatar-default-80x80.png | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=ca90f269-d258-4d70-9877-3ae4c23a85c7&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 62
| 2017-04-03 | 08:39:00 | 192.168.2.12 | GET | /images/res/ios/icon-60@3x.png | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=4515285e-c9ce-410d-9ed7-571ab4133349&SERVER-STATUS=304 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 304 | 0 | 0 | 62
| 2017-04-03 | 08:39:00 | 192.168.2.12 | GET | /images/favicon.png | X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=f363e7cd-3b2f-4b69-8299-ab891154448b&SERVER-STATUS=200 | 443 | - | 89.200.1.54 | https://plexlogs.xxx.yyy/users | 200 | 0 | 0 | 93



My other reverse proxy sites like SickRage, CouchPotato, Plex, qBittorrent, etc work as fast as expected.
HeadPhones has also become slow like PlexPy but since you share the same codebase that is not surprising.

**Comment by JonnyWong16** [comment]
I have no idea. I've never used IIS and I have no idea how it works.
