### ISSUE TITLE
Can't delete library

### ISSUE THREAD

**Issue by chrisvandergeld** [Tautulli/Tautulli#1005]
Hi, I've added music to my Plex. However, when I deleted a library - PlexPy didn't delete it.

**Version:**
1.4.17

**Branch:**
Master

**Commit hash:**
e85cdd5609c3f5795baaf2d45c484eb652497ec2

**Operating system:**
Ubuntu 16.04

**Python version:**
Python 2.7.12

**What you did?**
Delete library from Plex
Clean up database
Empty trash
Start PlexPy
https://foo.bar/plexpy/delete_duplicate_libraries
Restart PlexPy service

**What happened?**
Nothing

**What you expected?**
The library to dissapear

**How can we reproduce your issue?**
Delete library from Plex
Clean up database
Empty trash
Start PlexPy
https://foo.bar/plexpy/delete_duplicate_libraries
Restart PlexPy service

**Comment by JonnyWong16** [comment]
Libraries > Edit mode.
