### ISSUE TITLE
[Feature] Possible to add TV series & episode to history?

### ISSUE THREAD

**Issue by tylordurton** [Tautulli/Tautulli#101]
Hi,

Not sure if this has already been requested (apologies if so), would it be possible to add the above detail rather than just the show title to the history screen?

Also (just for confirmation as this has been raised a few times on the forum) are there any plans to include the now playing item in the history screen whilst it's playing similar to Plex Watch?

Kind Regards
Tylor

**Comment by JonnyWong16** [comment]
What do you mean by TV series and episode?

Right now it displays as "Series Name - Episode Title".

**Comment by drzoidberg33** [comment]
@JonnyWong16 I think it means the numbering. Like:

> Show Name - Episode Name - S0xE0x

I think.

**Comment by drzoidberg33** [comment]
Added in 1.1.3.

**Comment by tylordurton** [comment]
Thanks Guys, apologies for the late reply
