### ISSUE TITLE
Getting concurrent streams alert even under configured threshold

### ISSUE THREAD

**Issue by domibarton** [Tautulli/Tautulli#1010]
**Version:**   
1.4.17

**Git Tag:**  
v1.4.17 (e85cdd5)

**Operating system:**  
Linux (Debian)

**Python version:**  
2.7.9

**What you did?**  
Configured `User Concurrent Stream Threshold` to `2`

**What happened?**  
Getting e-mails with the content `<Friend> has 1 concurrent streams.`

**What you expected?**  
Mails should only be sent when the concurrent streams are `>=2`

**How can we reproduce your issue?**  
* Run PlexPy v1.4.17 (I'm using my [Docker Image](https://hub.docker.com/r/dbarton/plexpy/))
* Configure e-mail notifications
* Configure `User Concurrent Stream Threshold` to `2`
* Invite some Plex friends 
* Let them play something

You should now receive an email with the content `<Friend> has 1 concurrent streams.`

**Workaround**  
Stay on v1.4.16 as this didn't happen with it.

**What are your (relevant) settings?**  
* `Configured E-mail notification agent`
* `User Concurrent Stream Threshold: 2`

**Link to logs:**

n/a

**Comment by Adanufgail** [comment]
Can confirm this also occurs on 1.4.25 Docker on unRAID, but only to my user (Server Admin).

**Comment by dohlin** [comment]
Can confirm I'm also seeing this, but only with 1 user.  Very odd.
