### ISSUE TITLE
Library list not showing

### ISSUE THREAD

**Issue by matmuilwijk** [Tautulli/Tautulli#1011]
**Version:**
1.4.17
**Branch:**
master
**Commit hash:**
e85cdd5609c3f5795baaf2d45c484eb652497ec2
**Operating system:**
Ubuntu 16.04 LTS Server 32-bit
**Python version:**
2.7.12
**What you did?**
Reboot server after kernel upgrades. 
**What happened?**
Library list shows up empty, and refreshing manually doesn't help. (Plex is running)
**What you expected?**
To see my libraries listed as usual.
**How can we reproduce your issue?**

Run PlexPy as a Daemon, with the init script provided from the repo;
Upgrade to the latest available kernel for Ubuntu 16.04 32 bit; 
Reboot
**What are your (relevant) settings?**
Plex connects with WebSocket for events. Server runs on the same machine as PMS. (Doesn't work with WebSocket turned off either)
**Link to logs:**

[plexpylog.txt](https://github.com/JonnyWong16/plexpy/files/889641/plexpylog.txt)

**Comment by JonnyWong16** [comment]
Ctrl + F5?

**Comment by matmuilwijk** [comment]
Already tried that one... (And it didn't work)

Libraries also don't show up in the app btw

**Comment by JonnyWong16** [comment]
Database corrupted? It's really hard to tell when you only provide 17 lines of your log file.

**Comment by matmuilwijk** [comment]
Here you go, the full log since 30-1-2017... ;) 

It seems like Plex doesn't show the Libraries to PlexPy to me, but no idea how to fix it

[plexpylog.txt](https://github.com/JonnyWong16/plexpy/files/890652/plexpylog.txt)

**Comment by JonnyWong16** [comment]
Can you visit `http://localhost:8181/js/tables/libraries.js`?

**Comment by matmuilwijk** [comment]
Is it ok to visit over IP? Server is headless, so will be a bit hard... ;)

**Comment by JonnyWong16** [comment]
Yes

**Comment by matmuilwijk** [comment]
Do you need the output?

**Comment by JonnyWong16** [comment]
Does the page load?

**Comment by matmuilwijk** [comment]
Yes, it loads a raw script

**Comment by JonnyWong16** [comment]
You're not using a proxy or anything?

Reinstall PlexPy.

**Comment by matmuilwijk** [comment]
Good point, I do use Apache as a proxy, and loading over IP fixes it...

**Comment by matmuilwijk** [comment]
Just not on the proxy, and the app

**Comment by JonnyWong16** [comment]
Then it's a problem with your proxy and not a problem with PlexPy.

**Comment by matmuilwijk** [comment]
My app however doesn't run over the proxy, and doesn't show the libraries either.

**Comment by wcomartin** [comment]
Can you open your Developer Console (F12) in Chrome or Firefox and see when you hit Refresh if there is any Network request failing?

**Comment by matmuilwijk** [comment]
Yeah, error 500 on both the proxy as the direct IP access. 

IP: GET http://192.168.2.6:8181/refresh_libraries_list?_=1491236339080 500 (Internal Server Error)

Proxy: GET http://ppp.matthijsmuilwijk.nl/refresh_libraries_list?_=1491253915393 500 (Internal Server Error)

Weird part is that they do show with IP access, but not through the proxy. (Proxy is just a basic proxypass within Apache, and routed through cloudflare)

**Comment by matmuilwijk** [comment]
If I refresh the entire page with the console on, it gives me the following errors with a load of warnings about fonts:

GET http://ppp.matthijsmuilwijk.nl/js/tables/libraries.js net::ERR_CONTENT_DECODING_FAILED
libraries:330 

Uncaught ReferenceError: libraries_list_table_options is not defined
    at HTMLDocument.<anonymous> (libraries:330)
    at j (jquery-2.1.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.4.min.js:2)
    at Function.ready (jquery-2.1.4.min.js:2)
    at HTMLDocument.I (jquery-2.1.4.min.js:2)

**Comment by JonnyWong16** [comment]
Clear browser cache?

**Comment by matmuilwijk** [comment]
Done, and doesn't change anything... 

The app still doesn't show the libraries either, so I'm pretty sure the issue is within PlexPy. I had hoped that the update of Plex would fix it, but it doesn't.

**Comment by matmuilwijk** [comment]
And this rule keeps popping up in the log:

WebUI :: /libraries : Uncaught ReferenceError: libraries_list_table_options is not defined. (libraries:330)

**Comment by JonnyWong16** [comment]
Have you tried a different browser?

That error is basically saying that it can't find this file http://ppp.matthijsmuilwijk.nl/js/tables/libraries.js

**Comment by whiltseymour** [comment]
I have a similar issue too.
when I access plexpy through a domain like py.mydomain.com, the font crash.
It looks ok from a desktop browser but unreadable from a phone.

`home:1 Failed to decode downloaded font: http://py.mydomain.com/fonts/Open-Sans-600/Open-Sans-600.woff2`
`home:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT`
`home:1 Failed to decode downloaded font: http://py.mydomain.com/fonts/Open-Sans-regular/Open-Sans-regular.woff2`
`home:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT`
`home:1 Failed to decode downloaded font: http://py.mydomain.com/fonts/Open-Sans-600/Open-Sans-600.woff`
`home:1 OTS parsing error: uncompressed sfnt size mismatch`
`home:1 Failed to decode downloaded font: http://py.mydomain.com/fonts/Open-Sans-regular/Open-Sans-regular.woff`
`home:1 OTS parsing error: uncompressed sfnt size mismatch`
`home:1 Failed to decode downloaded font: http://py.mydomain.com/fonts/Open-Sans-600/Open-Sans-600.ttf`
`home:1 OTS parsing error: overlapping tables`
`home:1 Failed to decode downloaded font: http://py.mydomain.com/fonts/fontawesome-webfont.woff2?v=4.4.0`
`home:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT`
`home:1 Failed to decode downloaded font: http://py.mydomain.com/fonts/Open-Sans-regular/Open-Sans-regular.ttf`
`home:1 OTS parsing error: GSUB: table overruns end of file`

![1493260518841](https://cloud.githubusercontent.com/assets/4934341/25465751/b6ff531a-2b36-11e7-9a63-b9b489b07ac1.jpg)


any idea?

**Comment by JonnyWong16** [comment]
@whiltseymour See #1034
