### ISSUE TITLE
Several notifications not sent to slack(discord) when adding a lot of episodes at once

### ISSUE THREAD

**Issue by jsebt** [Tautulli/Tautulli#1012]
**Version:**
1.4.17
**Branch:**
master
**Commit hash:**
e85cdd5609c3f5795baaf2d45c484eb652497ec2
**Operating system:**
Windows 10 v1607
**Python version:**
2.7.13
**What you did?**
Added several episodes, at least 10 (or a whole show or season) all at once or in a short period of time (within the 1 minute of the "check recently added" task)
**What happened?**
Got 4-5 notifications in my discord channel (using slack notifications). For a show of 22 episodes. Notifications are random episodes from the show and are not in order. No real paterns.
Logs show "Slack notification failed: [429] TOO MANY REQUESTS" for the number of notifications that should have showed up but didn't. They also show that PlexPy sent the notifications request all in one second
**What you expected?**
Get 22 notifications for 22 episodes, in order.
**How can we reproduce your issue?**
Have notifications enabled for recently added
Setup discord(slack) notifications to have recently added shows send a notification.
Add several episodes of TV in a short period or all at once
_Can also be reproduced by spamming the "test slack" in slack notifications settings._
**What are your (relevant) settings?**
Options for grouping notifications for Tv Shows is disabled
Notification Delay for recently added : 180 seconds
Don't know if issue is present with movies. Never added enough in a short period of time for the issue to be present. Never had a movie or slowly added episodes have this isssue.
**Link to logs:**
[plexpy.txt](https://github.com/JonnyWong16/plexpy/files/894144/plexpy.txt)

**Comment by JonnyWong16** [comment]
I think that's pretty clear

"TOO MANY REQUESTS"

**Comment by jsebt** [comment]
This was more a feature request/bugfix request to add a delay of a second or two between notification sent to slack/discord (or any other solution that would work). Sorry, It wasn't clear in my OP.

As for the out of order episodes its not that critical but I wonder if it can be fixed

I'll do the request on feathub if you think its more of a feature request than a bugfix.

**Comment by jsebt** [comment]
Is there a fix planned for this? Could be a delay between each command plexpy sends to slack.

**Comment by JonnyWong16** [comment]
Not really.
