### ISSUE TITLE
Monitor Multiple Plex Servers - New Feature Request

### ISSUE THREAD

**Issue by bcorbet** [Tautulli/Tautulli#1013]
I have 2 Plex Media server running in my house.  One is mostly for my immediate family and the other is the one I share with extended family and friends.  It would be nice to be able to monitor both server from 1 PlexPy server.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests

http://feathub.com/JonnyWong16/plexpy/+14

#113
