### ISSUE TITLE
Unable to search for anything with certain special characters ' or &

### ISSUE THREAD

**Issue by gold007eye** [Tautulli/Tautulli#1014]
**Version:**
1.4.17

**Branch:**
master

**Commit hash:**
e85cdd5609c3f5795baaf2d45c484eb652497ec2

**Operating system:**
Linux 3.12.6

**Python version:**
2.7.11

**What you did?**
Tried to search for "Law & Order"
Tried to search for "fast n' loud"
Tried to search for "dc's legends of tomorrow"
Tried to search for "gold rush: parker's"

**What happened?**
No results found because the special characters change in the search field once you hit search.

Hyphen ' becomes "&#39;"
Ampersand becomes "&amp;"

**What you expected?**
To return search results based on the actual search phrase or to allow for partial match or wildcard searches.  I know you could search for "legends of tomorrow" and get it to show up but on something like Law & Order or Fast N' Loud I don't want to have to search for "Law" or "Fast" and have everything in my library with those single words show up.

**How can we reproduce your issue?**
Use the shows above as an example and try to search for them.  They won't return unless you have an exact match.  

Search entered:
![image](https://cloud.githubusercontent.com/assets/4365462/24807604/78859d5a-1b7e-11e7-98fe-af8e430581a2.png)

Search results:
![image](https://cloud.githubusercontent.com/assets/4365462/24807680/c60a4b5c-1b7e-11e7-9331-cccd324a855b.png)

To prove this show DOES exist (using the search of "law"):
![image](https://cloud.githubusercontent.com/assets/4365462/24807736/08a6c594-1b7f-11e7-83d2-dcfb2c77813f.png)

**Comment by JonnyWong16** [comment]
Note that it also doesn't work in Plex (if you type fast enough before the list populates).
![image](https://cloud.githubusercontent.com/assets/9099342/24807968/1c0f22bc-1b6f-11e7-90d8-f738e71a7edc.png)

**Comment by gold007eye** [comment]
I got the same result for that, but Law & Order & Fast N' Loud both come up in plex also typing fast.

![image](https://cloud.githubusercontent.com/assets/4365462/24813896/6609ce1e-1b95-11e7-8568-b8ddb2ec8f21.png)

![image](https://cloud.githubusercontent.com/assets/4365462/24813948/93499e72-1b95-11e7-8f2e-c365da056a11.png)

Looks like the special characters charset is changing in the search box for the other cases in plexpy which I'm betting then sends the search incorrectly to Plex

I'm thinking that Plex is getting "Law &amp; Order" as the search query string.  

**Dashes and Periods** seem to be fine for searching other than this scenario below which I'm not sure is related to the same bug.

Mr. Robot (notice the period)  In Plex you don't need to put the period for it to show results:
![image](https://cloud.githubusercontent.com/assets/4365462/24814177/39f6a396-1b96-11e7-9ae8-b568d5a6bfb9.png)

But in PlexPy it requires the period in order to be found:
No Period after Mr
![image](https://cloud.githubusercontent.com/assets/4365462/24814201/584386de-1b96-11e7-94a8-c808e9ea5e88.png)

Period after Mr:
![image](https://cloud.githubusercontent.com/assets/4365462/24814288/af4d5cac-1b96-11e7-82af-fa411695eb6e.png)

Hope this helps

**Comment by JonnyWong16** [comment]
Thanks for the info.

**Comment by gold007eye** [comment]
Any update on this issue?

**Comment by JonnyWong16** [comment]
No, I haven't looked into it since. This is low priority.

**Comment by gold007eye** [comment]
Ok thanks for the update 👍

**Comment by JonnyWong16** [comment]
Fixed in v2-beta.
