### ISSUE TITLE
IFTTT Notifications

### ISSUE THREAD

**Issue by BadBadger76** [Tautulli/Tautulli#1015]
As of this afternoon, the IFTTT notifications are all coming through as "The event named "plexpy" occurred on the Maker service". The event is being triggered correctly but it seems the information is not being sent. Even the test send shows up as "The event named "plexpy" occurred on the Maker service" in IFTTT and the IOS notification.

Git Branch:	master
Git Commit Hash:	e85cdd5609c3f5795baaf2d45c484eb652497ec2
Python Version:	2.7.12

Log of IFTTT Test Send
2017-04-10 21:43:03	INFO	PlexPy Config :: Writing configuration to file
2017-04-10 21:43:02	INFO	PlexPy Config :: Writing configuration to file
2017-04-10 21:43:00	INFO	PlexPy Notifiers :: Ifttt notification sent.
2017-04-10 21:42:59	DEBUG	Sending test IFTTT notification.
2017-04-10 21:42:59	INFO	PlexPy Config :: Writing configuration to file

**Comment by JonnyWong16** [comment]
Have you checked your IFTTT maker applet?

I just tested this myself.

IFTTT maker applet:
![image](https://cloud.githubusercontent.com/assets/9099342/24889536/5b0caa7c-1e1f-11e7-82fe-44c5a2938f37.png)

PlexPy settings:
![image](https://cloud.githubusercontent.com/assets/9099342/24889558/72cbd80e-1e1f-11e7-9a52-0801c5a70d7b.png)

Notification in Slack:
![image](https://cloud.githubusercontent.com/assets/9099342/24889561/797c1e70-1e1f-11e7-88b9-8aca1ff34128.png)

**Comment by Viper007Bond** [comment]
I'm getting the exact same thing as @BadBadger76. I receive notifications via the IFTTT app on my iPhone. It's previously worked as expected but started doing this within the last 24 hours I believe.

Perhaps this is an issue on IFTTT's end?

My notification body in IFTTT is set to `{{Value1}}: {{Value2}}`.

Git Branch: 	master
Git Commit Hash: 	e85cdd5609c3f5795baaf2d45c484eb652497ec2
Python Version: 	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

**Comment by JonnyWong16** [comment]
It's clearly not a PlexPy issue as I proved above.

**Comment by Viper007Bond** [comment]
Yep, that seems to be the case, but it's also not a configuration issue on @BadBadger76's end as you originally suggested. I just wanted to comment to say the issue was more widespread. 😃

**Comment by BadBadger76** [comment]
It seems like it could be an issue for established notifications. I will try resetting both PlexPy and IFTTT to see if that fixes it.

**Comment by StPatty33** [comment]
Same issue here.  I've had it working for 6 mos and suddenly in the last day or two it started sending the same generic notification instead.

**Comment by StPatty33** [comment]
I deleted my IFTTT recipe and created another one and it's still sending the generic'd info.

I have one recipe set up, just for the event "plexpy", no specific action modifier after it.  That's how it's always been and worked previously.

**Comment by Banthaf0dder** [comment]
Just throwing another log on the fire, I'm getting the exact same thing as of sometime yesterday afternoon/evening.

**Comment by JonnyWong16** [comment]
There is literally nothing I can do about it.

**Comment by Banthaf0dder** [comment]
It might not be a fix on PlexPy's end but have you engaged IFTTT about it?

**Comment by BadBadger76** [comment]
I do agree with @JonnyWong16, the log is showing the correct notification Subject and Body Text is being generated. So I wonder if something has changed on the IFTTT end

**Comment by StPatty33** [comment]
I tried adding a custom modifier with an underscore and word after plexpy through both IFTTT and Plexpy, and it just sent the same message only with the modifier there.  For some reason value1 and value2 aren't being recognized by IFTTT is what it looks like.

**Comment by BadBadger76** [comment]
I have opened a ticket with IFTTT but have yet to get a response

**Comment by Banthaf0dder** [comment]
So it won't send variables?

**Comment by StPatty33** [comment]
I know 0 about programming, but I think that's where the breakdown is.  I believe it was sending the same generic notification many months ago when I first set up the IFTTT recipe before I changed the notification ingredients in IFTTT to {{Value1}} and {{Value2}}, as they don't default to that.

**Comment by StPatty33** [comment]
It looks like this is a new issue with IFTTT's app notifications, as recipes sending to SMS and slack channel work fine.

**Comment by Banthaf0dder** [comment]
Anyone using IFTTT notifications to pass custom data with any other services?

**Comment by BadBadger76** [comment]
@JonnyWong16 So it does seem that this is a PlexPy issue. I added a new notification agent, in this case Slack. I turned on one of the triggers and now the IFTTT agent is working fine. If I remove the Slack notification trigger then the "The event named "plexpy" occurred on the Maker service" notification returns.

**Comment by JonnyWong16** [comment]
I am still unable to reproduce the issue.

**Comment by BadBadger76** [comment]
Is there any more log data that I can send when I reproduce to help?

**Comment by Viper007Bond** [comment]
It looks like IFTTT fixed this 2-3 hours ago. I'm getting normal notifications via the app on iOS again.

**Comment by BadBadger76** [comment]
I can confirm that it seems to be fixed. Returned my notification agent to just IFTTT and it sends fine.

**Comment by Homan13** [comment]
Shakes fist at IFTTT
