### ISSUE TITLE
Copy settings from old server to new doesn't work as expected.

### ISSUE THREAD

**Issue by shadycuz** [Tautulli/Tautulli#1018]
**Version:**
1.4.17
**Branch:**
master
**Commit hash:**
e85cdd5609c3f5795baaf2d45c484eb652497ec2
**Operating system:**
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie

**Python version:**
2.7
**What you did?**
Spun up a new server and copied config.ini and plexpy.db to it
**What happened?**
I still had to go through the welcome screen and none of my settings seemed to be present. 
I had to reauth to plex.tv using the welcome screen and none of my notification settings were present
**What you expected?**
It to wook exactly like the old server, well at least I expected most of my settings to copy over.
**How can we reproduce your issue?**
Copy the ini and db from a server that is set up to a fresh install on a different server.

**What are your (relevant) settings?**

**Link to logs:**

Let me know if you need more detail.

Thanks,
Levi

**Comment by JonnyWong16** [comment]
My guess is you didn't put the config and database file in the correct place or your startup script is pointing to the wrong place.

**Comment by shadycuz** [comment]
I'll double check but I put them in /opt/plexpy . The database worked and
copied over, but my settings didn't. Like my slack notification settings.

**Comment by shadycuz** [comment]
For some reason, sudo cp would not overwrite the existing file =/. Similar to these issues https://apple.stackexchange.com/questions/112890/how-do-i-use-cp-to-overwrite-files

I had to rm the file and then the copy would work.
