### ISSUE TITLE
Transcoding quality

### ISSUE THREAD

**Issue by zobe123** [Tautulli/Tautulli#102]
is it possible to log transcoding Quality (2mbit, 4mbit, etc...) and show on hover the Server Symbol at history (started column)

and/or on activity 1 stream(s) - next to Video: direct play (h264) (720x404) 

thx

**Comment by drzoidberg33** [comment]
It's not currently possible to get the quality setting the user selected (at least in none of the Plex api's I'm aware of) only the resolution (sometimes the resolution isn't returned either though).

We can add the icon on hover, I think that'd be useful too.

Not quite sure what you mean with this though:

> and/or on activity 1 stream(s) - next to Video: direct play (h264) (720x404)

Could you elaborate?

**Comment by JonnyWong16** [comment]
I can work on adding the tooltips, but what info should be included? It should be minimal since clicking on the Platform shows all the details.

**Comment by drzoidberg33** [comment]
@JonnyWong16 I can understand the server icon, which would give you an indication of transcodes at a glance, not sure what the other request means.

**Comment by zobe123** [comment]
I'm sorry. i meant the home view (see attached picture)
![img_9034](https://cloud.githubusercontent.com/assets/13840542/9406189/883687e6-47fe-11e5-8ad6-8ff964d7e7f8.jpg)

...but if it's not possible to get it from api, then it tooks care of itself. btw, could not conclude from the resolution..?

**Comment by zobe123** [comment]
great Addition. RESPECT!

**Comment by zobe123** [comment]
i am just randomly came across it that it appears in the logfile: (average Bitrate)

![untitled-1](https://cloud.githubusercontent.com/assets/13840542/9425421/2f5ef9e2-4910-11e5-9362-4179a63295be.jpg)

**Comment by drzoidberg33** [comment]
@zobe123 Yes, the transcoder will report this in the logs but no Plex API reports this neither will it report it anywhere when there is no transcode session.

**Comment by drzoidberg33** [comment]
Closing for now as this parameter isn't available to us.

**Comment by Hellowlol** [comment]
Bitrate is in session. Or this that the bitrate of the video? :P

```
 <Video addedAt="1447993190" art="/library/metadata/3812/art/1448379649" chapterSource="" contentRating="TV-14" duration="1292584" grandparentArt="/library/metadata/3812/art/1448379649" grandparentKey="/library/metadata/3812" grandparentRatingKey="3812" grandparentTheme="/library/metadata/3812/theme/1448379649" grandparentThumb="/library/metadata/3812/thumb/1448379649" grandparentTitle="2 Broke Girls" guid="com.plexapp.agents.thetvdb://248741/5/2?lang=en" index="2" key="/library/metadata/60645" librarySectionID="2" originallyAvailableAt="2015-11-19" parentIndex="5" parentKey="/library/metadata/60556" parentRatingKey="60556" parentThumb="/library/metadata/60556/thumb/1448379648" rating="8.0" ratingKey="60645" sessionKey="114" summary="When the shower at Max and Caroline’s apartment breaks, they get part-time jobs at a fancy gym’s juice bar and enjoy free use of the locker room. However, their jobs and free showers are jeopardized when Caroline has a run-in with a group of rich moms who are jealous of the attention she’s getting from a sexy trainer." thumb="/library/metadata/60645/thumb/1448601714" title="And The Gym and Juice" type="episode" updatedAt="1448601714" viewOffset="1281410" year="2015">
        <Media aspectRatio="1.78" audioChannels="6" audioCodec="ac3" bitrate="3547" container="mkv" duration="1292584" height="720" id="72112" videoCodec="h264" videoFrameRate="24p" videoResolution="720" width="1280">
            <Part container="mkv" duration="1292584" file="X:\2 Broke Girls\Season 05\2.Broke.Girls.S05E02.720p.HDTV-DIMENSION.mkv" id="72400" indexes="sd" key="/library/parts/72400/file.mkv" size="573132830">
                <Stream bitDepth="8" bitrate="3093" cabac="1" chromaSubsampling="4:2:0" codec="h264" codecID="V_MPEG4/ISO/AVC" colorSpace="yuv" duration="1292584" frameRate="23.976" frameRateMode="cfr" hasScalingMatrix="0" height="720" id="199497" index="0" language="English" languageCode="eng" level="41" profile="high" refFrames="8" scanType="progressive" streamType="1" width="1280" />
                <Stream audioChannelLayout="5.1(side)" bitDepth="16" bitrate="384" bitrateMode="cbr" channels="6" codec="ac3" codecID="A_AC3" dialogNorm="-31" duration="1292576" id="199498" index="1" samplingRate="48000" selected="1" streamType="2" />
            </Part>
        </Media>
        <Writer id="15333" tag="Liz Astrof" />
        <Director id="21871" tag="Michael Patrick King" />
        <User id="xxx" title="xxx" />
        <Player machineIdentifier="yyyy" platform="Chrome" product="Plex Web" state="paused" title="Plex Web (Chrome)" />
        <TranscodeSession key="sgt975awb1g1ra4i" throttled="0" progress="100" speed="6.0999999046325684" duration="1292000" remaining="0" context="streaming" videoDecision="transcode" audioDecision="transcode" protocol="http" container="mkv" videoCodec="h264" audioCodec="aac" audioChannels="2" width="569" height="320" />
    </Video>
```

**Comment by JonnyWong16** [comment]
It's the video's bitrate.

**Comment by palak314** [comment]
I added the bitrate to the live activity session for my personal use. http://i.imgur.com/hDzGFWU.jpg Could clean up code and display formatting then make a pr, unsure if this is something you want.

**Comment by JonnyWong16** [comment]
Is it the bitrate of the video file? or the bitrate of the stream? Did you just scrape it from the Plex logs?

**Comment by palak314** [comment]
Bitrate of the stream. Yes scrapes the logs for maxVideoBitrate of the session key. Was also going to add displaying the video bitrate for direct plays and in the case where the video bitrate is below the maxVideoBitrate of the transcode.
