### ISSUE TITLE
Invalid PMS Server IP Causes PlexPy Pages to Slow Down or Time Out with "Connection Refused" Errors

### ISSUE THREAD

**Issue by jacobspayne** [Tautulli/Tautulli#1022]
**Version:** 1.4.18

**Branch:** Master

**Commit hash:** ed2d34e97945525a5f83f6b9edc3350df54057b8

**Operating system:** Windows 10

**Python version:** 2.7.12

**What you did?** Changed the IP address of the Plex Media Server (got a new router that did this automatically), causing the PMS IP address stored in PlexPy settings to become invalid (unresolvable), restarted the laptop running PlexPy, logged into PlexPy successfully, then attempted to navigate to the Settings page of PlexPy.

**What happened?** Page load times increase dramatically (from ~1 second to ~40 seconds), and sometimes page loads time out completely with the error "Connection refused". The Settings page would partially load after 15-30 seconds, but then sit there for another 10 seconds with "Loading configuration table" messages. PlexPy logs showed lots of messages like this:
'Failed to access uri endpoint /status/sessions with error timed out'
`PlexPy Pmsconnect :: Unable to parse XML for get_current_activity: 'NoneType' object has no attribute 'getElementsByTagName'.`
`PlexPy Monitor :: Unable to read session list.`
`PlexPy Monitor :: Unable to get an internal response from the server, ping attempt 5.`

**What you expected?** The settings page to work normally (i.e. no slowdowns or timeouts), even though the IP address that PlexPy was attempting to use for the PMS was no longer valid.

**How can we reproduce your issue?**

1. Shut down PlexPy.
2. In PlexPy's config.ini, set the PMS IP address to an IP that does not resolve (it will not let you set an invalid IP in the GUI).
3. Start PlexPy and log in
4. Attempt to navigate to the Settings page in PlexPy.
_Note: You cannot replicate this issue simply by shutting down PMS; PlexPy will behave normally in that case. Only if the PMS IP is unresolvable will the symptoms occur_

**What are your (relevant) settings?** Changing the `pms_ip` and `pms_url` parameters in `config.ini` to the new/correct IP address and restarting PlexPy caused everything worked as expected. Ideally, at least the Settings page would continue to work normally so this setting could be corrected in the GUI instead of in the config file.

**Link to logs:**
Issue started at: `2017-04-22 21:01:10` (this is when I swapped routers, causing the old IP to be invalid)
Issue resolved at: `2017-04-22 23:46:02` (this is when I made the settings change to a valid IP in `config.ini`)
[plexpy.log](https://gist.github.com/jacobspayne/563a279eeb509f544d97421d0596299a)

**Comment by jacobspayne** [comment]
I imagine that this issue will be low-priority since this situation is probably pretty rare for most people, but I just wanted to let you know about it since it did cause me some headaches when swapping my router out. Thank you so much for the work you put in for PlexPy, it is an amazing application!

**Comment by deed02392** [comment]
You can avoid this in future by using a hostname that automatically updates to point to your Plex server either with a dynamic or static IP address.

**Comment by jacobspayne** [comment]
@deed02392 I did that for a while. Wasn’t perfect because my dynamic DNS provider only updated once every 5 minutes so there was occasionally some downtime after IPs changed. Eventually I just moved PlexPy and PMS to the same server and used the local looback address instead.

**Comment by deed02392** [comment]
@jacobspayne How come you can't get a static IP for your Plex server? £££?
