### ISSUE TITLE
Library double - FAQ steps don´t work

### ISSUE THREAD

**Issue by Massaguana** [Tautulli/Tautulli#1024]
**Version:** 1.4.18

**Branch:** Master

**Commit hash:** ed2d34e97945525a5f83f6b9edc3350df54057b8

**Operating system:** Thecus NAS (Linux 3.14.66)

**Python version:** 2.7.8 (default, Nov 20 2016, 22:44:57) [GCC 4.7.2]

**What happened?**
After the last Update the Library are double
![bildschirmfoto 2017-04-25 um 14 47 32](https://cloud.githubusercontent.com/assets/15521791/25386013/24106498-29c6-11e7-902a-1e9b4a4ecf4c.PNG)

What i do to fix this is to the steps from FAQ. nothing happens.

**Link to logs:**
[plexpy.log.zip](https://github.com/JonnyWong16/plexpy/files/955051/plexpy.log.zip)

regards
Massaguana

**Comment by JonnyWong16** [comment]
Toggle the cards in the Settings > Homepage.

**Comment by Massaguana** [comment]
Works. Thank you.
