### ISSUE TITLE
PlexPy 1.418 Mac OS Sending unwanted notifications

### ISSUE THREAD

**Issue by Jashun44** [Tautulli/Tautulli#1026]
**Version: **
1.418

**Branch:**
master

**Commit hash:**
ed2d34e97945525a5f83f6b9edc3350df54057b8

**Operating system:**
Mac OS El Capitan

**Python version:**
2.7.10

**What you did?**
Turned off notifications for Music; Setup Facebook post notifications

**What happened?**
PlexPy is posting Facebook notifications for newly added music, even though Music notifications is unchecked

**What you expected?**
No notifications to be sent/posted for Music Libraries

**How can we reproduce your issue?**

- Enable Facebook post notifications
- Enable "Newly Added" notifications
- Uncheck "Music Notifcations"

**What are your (relevant) settings?**
- "Newly Added" notifications enabled
- "Music Notifications" unchecked

**Link to logs:**

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#q-can-i-disable-recently-added-notifications-for-tv-showsmovies

**Comment by Jashun44** [comment]
Hi,

Sorry, I should have added that this was the first thing I tried. It still is sending notifications for newly added music. The toggle button in Library->Edit Mode is the bell icon, correct? That is unchecked/toggled off for all music libraries. I just wasn't sure if I was missing something else. This only just started happening after I recently updated PlexPy. P.S. I love PlexPy!! :)

Thanks!

**Comment by JonnyWong16** [comment]
![image](https://cloud.githubusercontent.com/assets/9099342/25558785/dd638ea6-2ce2-11e7-92d2-e15856549e95.png)

**Comment by Jashun44** [comment]
??? Right. Got it. Thanks. Does that refer to the Bell icon? If so, that is toggled off for all music libraries. There is nothing in the Libraries > Edit mode that says "Toggle Recently Added".

Thanks again

**Comment by Jashun44** [comment]
Ugh nevermind. It's the other icon. Thanks
