### ISSUE TITLE
'Refresh media info' does not update file size

### ISSUE THREAD

**Issue by ksarnelli** [Tautulli/Tautulli#1027]
VERSION 1.4.1
Git Branch:	master
Git Commit Hash:	ed2d34e97945525a5f83f6b9edc3350df54057b8
Platform:	Linux 4.9.19-unRAID
Python Version:	2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]

**What you did?**
Replaced movie files and refreshed library in Plex.  Then, in PlexPy, I browsed to the library and clicked 'Refresh media info'

**What happened?**
All columns update except 'File Size', the value of the old file is still showing.

**What you expected?**
The file size of the new file should show.

**How can we reproduce your issue?**
See 'What happened' ^^^^

**What are your (relevant) settings?**
n/a

**Link to logs:**
n/a

**Comment by JonnyWong16** [comment]
Clear the PlexPy cache. (or just the .json files in the cache folder)

**Comment by ksarnelli** [comment]
That did the trick, thanks!
