### ISSUE TITLE
Notifications to Buffer.com or HootSuite

### ISSUE THREAD

**Issue by notlimahrelyt** [Tautulli/Tautulli#1029]
I would love the ability to push Recently Added and Server Up/Down notifications to either my Buffer or HootSuite account.

I have my Plex users registered to a twitter, Facebook group and Instagram. Currently I'm using a workaround through IFTTT to get the notifications to Buffer, but a native integration would be awesome!

Thanks

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests
