### ISSUE TITLE
[REQ] Add transcode reason to stream information 

### ISSUE THREAD

**Issue by brimur** [Tautulli/Tautulli#1030]
Thanks for the great piece of software. I see a few devices in the History section that transcode for various reasons and right now I have to go into the logs to see why. Could you add the transcode reason to the stream info in the History tab? Thanks

**Comment by Deepcuts** [comment]
Feature Requests:
  * Feature requests are handled on FeatHub: http://feathub.com/JonnyWong16/plexpy
  * Do not post them on the GitHub issues tracker.
