### ISSUE TITLE
Activity Thumb Refresh Rate

### ISSUE THREAD

**Issue by jscottelblein** [Tautulli/Tautulli#1031]
VERSION 1.4.17

Just wondering if there's a setting / way to increase the auto-refresh rate of the thumbnail of an active user? When for example, a user is watching a movie and I view it within the PMS web app itself, the thumb refreshes pretty fast; watching the thumb via PlexPy though, it's a lot slower. I'd like to match PMS's refresh rate in PlexPy, but only if it means refreshing *just* that thumb, and not the entire PlexPy db.

**Comment by JonnyWong16** [comment]
No, it's set to 15 seconds. I don't want to make it ping every second.
