### ISSUE TITLE
[Request] Limit concurrent streams per user

### ISSUE THREAD

**Issue by fash202** [Tautulli/Tautulli#1033]
You can now close streams through the Plex web app and even give a reason, wondering if it was possible to make something that limits the amount of streams a user is allowed to have at once, maybe even send a message when the stream is closed (though the above mentioned feature or email)

**Comment by fash202** [comment]
I know you can limit the amount of remote streams allowed per user, but was hoping to have different amounts for different users

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests
