### ISSUE TITLE
PlexPy via IOS font rendering issues

### ISSUE THREAD

**Issue by zenjabba** [Tautulli/Tautulli#1034]
Version: 1.4.18

When accessing PlexPy via IOS Safari the fonts are broken. Picture Added for reference

![db7250e7-f670-4619-a4e6-33836885b277](https://cloud.githubusercontent.com/assets/679864/26020009/ef978a90-3747-11e7-9869-7afa82674da6.PNG)

**Comment by JonnyWong16** [comment]
I think this is an issue with your reverse proxy not allowing fonts.

This might help: https://serverfault.com/questions/186965/how-can-i-make-nginx-support-font-face-formats-and-allow-access-control-allow-o

**Comment by zenjabba** [comment]
Thanks, will take a look.

That fixed it.
