### ISSUE TITLE
Duplicate resolutions in Graphs

### ISSUE THREAD

**Issue by sander1** [Tautulli/Tautulli#1036]
**Version:**
1.4.18

**Branch:**
master

**Operating system:**
Ubuntu 16.04.2

**Python version:**
2.7.12

**What you did?**
Click Graphs and check "Play count by source resolution" or "Play count by stream resolution".

**What happened?**
Certain resolutions are duplicates, e.g. "720" and "720p", or "sd" and "SD".

![screen shot 2017-04-29 at 18 00 34](https://cloud.githubusercontent.com/assets/104684/26180226/89507006-3b68-11e7-8d06-8ebac9620143.jpg)

**Comment by JonnyWong16** [comment]
#993
