### ISSUE TITLE
File size not updating

### ISSUE THREAD

**Issue by Deepcuts** [Tautulli/Tautulli#1037]
**Version:**
1.4.18
**Branch:**
master
**Commit hash:**
ed2d34e97945525a5f83f6b9edc3350df54057b8
**Operating system:**
Ubuntu Server 14.04
**Python version:**
2.7.6
**What you did?**
Changed a 8.1 GB movie with a 2 GB movie. Same name.
**What happened?**
Size reported by PlexPy remained 8.1 GB
**What you expected?**
Size to be reported as the new value of 2 GB after clicking on Refresh media info
**Link to logs:**
Nothing reported in logs

Similar to #1027 but that one has been closed.

**Comment by Deepcuts** [comment]
Deleting /opt/plexpy/cache/*.json files and a restart fixed the wrong/old size displayed.
Not a nice fix, but it does the trick.

**Comment by Deepcuts** [comment]
Happened again.
Changed two large files with smaller versions. Same name, same location.
PlePy still reports the old size after a media refresh.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.20.
