### ISSUE TITLE
History no longer loads

### ISSUE THREAD

**Issue by kingwoftam** [Tautulli/Tautulli#1040]
**Version:**
1.4.18

**Branch:**
master

**Commit hash:**
ed2d34e97945525a5f83f6b9edc3350df54057b8

**Operating system:**
QNAP NAS - Linux 3.12.6

**Python version:**
2.7.11 (default, Jan 30 2016, 18:32:06) [GCC 4.3.6]

**What you did?**
Clicked on the History button

**What happened?**
Page loads but table is empty. Sits spinning on the fetch but never displays anything

**What you expected?**
The history loads in a reasonable time

**How can we reproduce your issue?**
Click on the History button - ensure it loads

**What are your (relevant) settings?**
Nothing applicable to this worth mentioning

**Link to logs:**
[plexpy.log.zip](https://github.com/JonnyWong16/plexpy/files/1027916/plexpy.log.zip)

**Comment by JonnyWong16** [comment]
Did you read your own logs before posting? **`database or disk is full`**

```
2017-05-25 15:45:42 - WARNING :: CP Server Thread-9 : PlexPy DataFactory :: Unable to execute database query for get_history: database or disk is full.
```
