### ISSUE TITLE
Updater not working - Windows Server 2016

### ISSUE THREAD

**Issue by daveywave** [Tautulli/Tautulli#1041]
**Version:** 1.4.18

**Branch:** master

**Commit hash:**

**Operating system:** windows server 2016

**Python version:** 2.7.12

**What you did?** 

**What happened?**  Updated does not retrieve latest commit. I was stuck on an old commit from 11/2016. The update notification in the lower right of the app window reads _You're running an unknown version of PlexPy. Update or Close_
 
**What you expected?** I ran without this issue in Server 2012 R2. The disk used for PlexPy was taken out of the 2012 R2 install and runs exactly the same (through task scheduler) in this new 2016 box.

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
![image](https://cloud.githubusercontent.com/assets/5883347/26468216/3bbdd010-415b-11e7-8d4d-5ea5cd8691c5.png)

**Comment by JonnyWong16** [comment]
Please read the FAQ.
