### ISSUE TITLE
Notifications: air_date and release_date are the same for TV shows

### ISSUE THREAD

**Issue by harrisonlingren** [Tautulli/Tautulli#1043]
**Version:**
1.4.18
**Branch:**
master
**Commit hash:**
ed2d34e97945525a5f83f6b9edc3350df54057b8
**Operating system:**
Ubuntu 16.04 (Linux 4.4.0-28-generic)
**Python version:**
2.7.11+
**What you did?**
Set up an email notification that includes the date the episode aired for recently added items.
**What happened?**
I tried using both {air_date} and {release_date}, but both give the date when the show originally aired.
**What you expected?**
I am looking to include the metadata for when the specific _episode_ aired, not the whole show.
**How can we reproduce your issue?**

**Comment by JonnyWong16** [comment]
`{air_date}` and `{release_date}` are the exact same value. There is no difference between them.

If the date is wrong, then your Plex metadata is wrong. PlexPy does not retrieve metadata from any external sources, only from your Plex server. Also, if you have "Group notifications for recently added TV Shows or Music" checked in your PlexPy settings, then it won't have episode metadata as specified in the note:

```
[ ] Group notifications for recently added TV Shows or Music
Enable to only get one TV Show or Artist notification for a batch of recently added Episodes or Tracks. Movies are unaffected.
Note: No Season/Episode or Album/Track metadata will be available.
```
