### ISSUE TITLE
Transcode resolution not showing

### ISSUE THREAD

**Issue by tijmenvn** [Tautulli/Tautulli#1045]
**Version:**
1.4.18

**Branch:**
Master

**Commit hash:**
ed2d34e97945525a5f83f6b9edc3350df54057b8

**Operating system:**
Ubuntu 16.04

**Python version:**
2.7.12

**What you did?**
Watch the activity on homepage and in history

**What happened?**
Resolution not showing and double p at the resolution (1080pp)

**What you expected?**
The transcode resolution to show

**How can we reproduce your issue?**
Watch something on Plex using transcode and watch the activity

**What are your (relevant) settings?**
-

**Link to logs:**
Logs to be added ASAP

![capture](https://cloud.githubusercontent.com/assets/9320891/26573693/00de7b30-451f-11e7-8e54-a4a7e11a71c1.PNG)

![capture1](https://cloud.githubusercontent.com/assets/9320891/26573600/bae87c20-451e-11e7-97b4-c688458c2004.PNG)

**Comment by ghost** [comment]
I know the double p thing has been reported before. IIRC it's fixed in PlexPy v2 which has no ETA.

As for the `(x)` thing, I've been having that lately from one person's device only. No one else's device does it, so I'm not sure where the actual problem is.

**Comment by tijmenvn** [comment]
For me the (x) is consistent with all transcodes, have already tried restarting everything to fix it, to no avail

**Comment by Cimplex** [comment]
Same thing is happening to me, but only since I updated to the latest Plex Pass server version (1.7.1.3856).

**Comment by Magikarplvl4** [comment]
I see this problem too after updating to plex server 1.7.1

**Comment by JonnyWong16** [comment]
(Temporarily) Fixed on v1.4.19.

**Comment by seanvree** [comment]
I'm on PMS Version 1.7.2.3878 on windows. Have the issue.  

Temp fix on MASTER ea41d06023969d938bd3b690e72cd3de56b18370 fixed it. 

THX

**Comment by tijmenvn** [comment]
Video resolution is indeed fixed. However. The source still states 1080pp whenever you transcode. While it says 1080p for the source if you direct play

**Comment by JonnyWong16** [comment]
#993
