### ISSUE TITLE
While Plexpy can see current activity but it hasn't reported any activity since 2017-05-03.

### ISSUE THREAD

**Issue by edasque** [Tautulli/Tautulli#1046]
Plexpy **v1.4.18**

Git Branch:	master
Git Commit Hash:	ed2d34e97945525a5f83f6b9edc3350df54057b8
Configuration File:	/config/config.ini
Database File:	/config/plexpy.db
Log File:	/config/logs/plexpy.log
Backup Directory:	/config/backups
Cache Directory:	/config/cache
GeoLite2 Database:	Click here to install the GeoLite2 database.
Arguments:	['--datadir', '/config']
Platform:	Linux 3.10.102
Python Version:	2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]**What you did?**

Plex: **v1.7.1.3856** on Synology

Running on docker via:
```
sudo docker create --name="plexpy" -v /etc/localtime:/etc/localtime:ro -v /volume1/docker/plexpy:/config -v "/volume1/Plex/Library/Application Support/Plex Media Server/Logs/":/logs:ro -e PGID=100 -e PUID=1024 -p 8901:8181 linuxserver/plexpy
```
While Plexpy can see current activity, it hasn't reported any activity since 2017-05-03.

I expect recent activity, not sure why it stopped then.

**How can we reproduce your issue?**
Not sure, frankly but help me diagnose it.

Plexpy logs show no error or warning level items but recent infos & debug. Plexpy shows recent Plex logs, no errors but this warning:

May 31, 2017 21:23:44.113	WARN	LongPoll: Got error, closing.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#history-q3
