### ISSUE TITLE
Notification Agent Scripts Not Firing

### ISSUE THREAD

**Issue by Brenex** [Tautulli/Tautulli#1047]
**Version:**
VERSION 1.4.19

**Branch:**
master

**Commit hash:**
ea41d06023969d938bd3b690e72cd3de56b18370

**Operating system:**
Win 8.1

**Python version:**
2.7.11

**
I have two scripts in the scripts folder that I use to limit by bandwidth depending on if stream is started/resumed or stopped/paused. The scripts are no longer firing. I am not sure exactly when they stopped working but here are some screenshots of my settings and logs. I'm not sure if this is the same issue as the following so I thought I would post it: https://github.com/JonnyWong16/plexpy/issues/923

![screen shot 2017-06-03 at 3 09 08 pm](https://cloud.githubusercontent.com/assets/3178983/26756418/ec25f408-486f-11e7-9885-31f3270b3ad8.png)
![screen shot 2017-06-03 at 3 09 30 pm](https://cloud.githubusercontent.com/assets/3178983/26756417/ec254f76-486f-11e7-9ed1-8085290a5d3e.png)
![screen shot 2017-06-03 at 3 09 51 pm](https://cloud.githubusercontent.com/assets/3178983/26756420/ec2dcc50-486f-11e7-8e1c-f6599d5efc0e.png)
![screen shot 2017-06-03 at 3 12 12 pm](https://cloud.githubusercontent.com/assets/3178983/26756419/ec281de6-486f-11e7-897d-5b1396bc7246.png)

**Comment by irodimus** [comment]
I'm getting the exact thing using PlexPy 1.4.19 running on a Mac Mini using macOS 10.12.5 with Python 2.7.13. There is no notification logged in PlexPy Logs, not even a Trying to run the script message. I'm trying to run blacktwin's "Kill transcode if paused for more than X time" script.

My PlexPy Log view looks like the one above with the session showing paused, then writing configuration file message. I should add I also followed the steps outlined in the top of the script to set it and enable it.

**Comment by JonnyWong16** [comment]
Restart PlexPy, test it again, and post your entire logs.

**Comment by Brenex** [comment]
[Plex Media Server.txt](https://github.com/JonnyWong16/plexpy/files/1112775/Plex.Media.Server.txt)
[plexpy.txt](https://github.com/JonnyWong16/plexpy/files/1112774/plexpy.txt)

**Comment by JonnyWong16** [comment]
Do you have all the notification toggles enabled?

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q1

**Comment by Brenex** [comment]
[plexpy.txt](https://github.com/JonnyWong16/plexpy/files/1112798/plexpy.txt)

That seemed to have fixed it.
