### ISSUE TITLE
KeyError: 'week_start_monday'

### ISSUE THREAD

**Issue by BSOD2600** [Tautulli/Tautulli#1049]
**Version:**
 v1.4.18 

**Branch:**
main

**Operating system:**
Win7

**Python version:**
2.7.13

**What you did?**
Manually updated the files from github (since automatic was not working) and then this issue started. 

**What happened?**
Visiting http://localhost:8181/settings  results in the following error stack:
```
KeyError: 'week_start_monday'

</div> <div class="checkbox"> <label> <input type="checkbox" id="week_start_monday" name="week_start_monday" value="1" ${config['week_start_monday']}> Week Starting on Monday </label> <p class="help-block">Change the "<em>Play by day of week</em>" graph to start on Monday. Default is start on Sunday.</p> </div> <div class="checkbox"> <label>
C:\Program Files (x86)\PlexPy\data/interfaces/default/settings.html, line 122:
<input type="checkbox" id="week_start_monday" name="week_start_monday" value="1" ${config['week_start_monday']}> Week Starting on Monday
C:\Program Files (x86)\PlexPy\data/interfaces/default/base.html, line 312:
${next.body()}
C:\Program Files (x86)\PlexPy\lib/mako\runtime.py, line 860:
callable_(context, *args, **kwargs)
C:\Program Files (x86)\PlexPy\lib/mako\runtime.py, line 835:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
C:\Program Files (x86)\PlexPy\lib/mako\runtime.py, line 803:
**_kwargs_for_callable(callable_, data))
C:\Program Files (x86)\PlexPy\lib/mako\template.py, line 443:
return runtime._render(self, self.callable_, args, data)
C:\Program Files (x86)\PlexPy\plexpy\webserve.py, line 70:
_session=_session, **kwargs)
```

**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
n.a.  
C:\Program Files (x86)\PlexPy\logs\plexpy.log  hasnt updated itself since 5/28, even though I reproed this issue today.

**Comment by JonnyWong16** [comment]
Sounds like you botched the manual update.

Backup and reinstall.

**Comment by BSOD2600** [comment]
Ok, 
   * fresh download of master.zip from https://github.com/JonnyWong16/plexpy/archive/master.zip
   * replace all/overwrite existing files
   * Issue still occurs. 

Possibly something wrong with the db?

**Comment by JonnyWong16** [comment]
Did you shut down PlexPy first?

**Comment by BSOD2600** [comment]
Yes, I did.

**Comment by JonnyWong16** [comment]
Backup the database and delete everything else, then reinstall again.

**Comment by BSOD2600** [comment]
db deletion was the only way I could make this error go away.
