### ISSUE TITLE
Double registration in history when using Kodi/OSMC and PlexBMC

### ISSUE THREAD

**Issue by LarsErikP** [Tautulli/Tautulli#1053]
**Version:** 1.4.19

**Branch:** master

**Commit hash:** ea41d06023969d938bd3b690e72cd3de56b18370

**Operating system:** Ubuntu Server 16.04 LTS

**Python version:** 2.7.12

In my setup, I watch Plex from OSMC with the PlexBMC plugin. When I do that, PlexPy registers all my history twice. One line with "Platform Kodi / Player "My PlexBMC Client" and one line with "Platform XBMC / Player osmc"

**Comment by JonnyWong16** [comment]
Post some recent screenshots, recent logs, and PM me your database on Discord please.

**Comment by timmyk0** [comment]
I am having this same issue except it's across all players, Samsung TV, Chromecast, Chrome browser, Apple TV, iPhone, etc. It looks like it started about 5 days ago. 

I tried restarting PlexPy, but wasn't sure what else to do, that didn't seem to make any difference. See attached screenshot for the history page view showing duplicates of everything watched or played.

![image](https://user-images.githubusercontent.com/19522008/27667853-913c6960-5c4b-11e7-8936-e3eb6a3c8d0c.png)

**Comment by timmyk0** [comment]
I may be wrong about the reboot of PlexPy, looks like that may have fixed it. I just had a user finish a show and it only shows once on the history page. I will have to give it a day or so and see how it goes.
