### ISSUE TITLE
Most Watched Movie ins't acurate

### ISSUE THREAD

**Issue by SirWintour** [Tautulli/Tautulli#1057]
On the front page of PlexPy, it shows what movie is the most watched. But it only looks for how many times it's been started, not how many times it's been completed aka "Watched".
I have provided a screenshot, which is set as "Most watched movie", but as you can see, only 1 use has seen it, and only 1 time, just over multiple parts.

![plexpyedited](https://user-images.githubusercontent.com/15029818/27509623-8942d7d2-5901-11e7-86c4-c94967848ecd.jpg)

**Comment by JonnyWong16** [comment]
Enable "Group Table and Watch Statistics History" in the settings.

**Comment by SirWintour** [comment]
Thanks :)
