### ISSUE TITLE
[Request] export metrics to influxdb

### ISSUE THREAD

**Issue by evanrich** [Tautulli/Tautulli#1058]
Feel free to close this if you don't think it's valid, but I was wondering what the chance would be of exporting stats to something like influxdb?  I know it's better to have plex itself do this, but that's probably never going to happen, so I wonder if plexpy could?  I currently use InfluxDB + Grafana to display stats on my home lab + whole house power consumption, and while the graphs in PlexPy are super useful, I'd like to have the expanded ability to monitor/manipulate data to look at trends over time, plus the graphs are a lot nicer.

![image](https://user-images.githubusercontent.com/518320/27514128-f3696444-5935-11e7-9683-7ffc217b0191.png)

Due to the nature of how InfluxDB works, I'm not sure how this would exactly work (would probably need to write out something in grahite format, or newer influx format), I'm willing to help figuure out how to maybe do it, just floating the idea.

Thanks!

**Comment by JonnyWong16** [comment]
People have already done this: https://www.google.com/search?q=plexpy+influxdb
