### ISSUE TITLE
Install as daemon file not found

### ISSUE THREAD

**Issue by dhldh07** [Tautulli/Tautulli#1059]
<!when following the guide the first part goes fine then when entering 

"~/Library/LaunchAgents/com.JonnyWong16.plexpy.plist"

It says file not found. Yet everything is up and working. Can anyone advise?

Thanks
Reporting Issues:
  * To ensure that a developer has enough information to work with please include all of the information below.
    Please provide as much detail as possible. Screenshots can be very useful to see the problem.
  * Use proper markdown syntax to structure your post (i.e. code/log in code blocks).
    See: https://help.github.com/articles/basic-writing-and-formatting-syntax/
  * Include a link to your **FULL** log file that has the error(not just a few lines!).
    Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Feature Requests:
  * Feature requests are handled on FeatHub: http://feathub.com/JonnyWong16/plexpy
  * Do not post them on the GitHub issues tracker.
-->

**Version:**

**Branch:**

**Commit hash:**

**Operating system:**

**Python version:**

**What you did?**

**What happened?**

**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
That command is all one line.

```
cp /Applications/PlexPy/init-scripts/init.osx ~/Library/LaunchAgents/com.JonnyWong16.plexpy.plist
```
