### ISSUE TITLE
Add last 5 watched items on the Homepage

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#106]
It would be good to have the last 5 or 10 watched items (configurable if possible) on the homepage with following details as a small table: user - date/hour - movie/show title 

Instead of going to the history page to find out recently watched items.

**Comment by kylerw** [comment]
+1

**Comment by majora2007** [comment]
I personally don't see the need to clutter the home screen any further as this functionality is already in the history tab.

**Comment by kylerw** [comment]
What I think might make the most sense is to have the ability to pick and choose which widgets appear on the home screen. I personally don't care for all of the current stats widgets and would like some of others to take their place. The option to control which appear would resolve both concerns (clutter and new widgets).

**Comment by JonnyWong16** [comment]
I'm looking into selective hiding of homepage statistics.

**Comment by nomadore** [comment]
Could you add progress in the Last Watch Widget?  85% 100% etc.  That would make it so much useful.

**Comment by JonnyWong16** [comment]
@nomadore The next update will only show an Item in the "Last Watched" statistic if it exceeds the "Watched Percent" in the settings.

**Comment by drzoidberg33** [comment]
This is released.
