### ISSUE TITLE
Wrong coinbase address

### ISSUE THREAD

**Issue by janabimustafa** [Tautulli/Tautulli#1061]
**Version:1.4.19**

**Branch:master**

**Commit hash:ea41d06023969d938bd3b690e72cd3de56b18370**

**Operating system:Unraid**

**Python version:	2.7.13**

**What you did?** clicked on donate bitcoin button

**What happened?** 404 page not found on coinbase

**What you expected?** A bitcoin address to donate to

**How can we reproduce your issue?**

Click on the bitcoin donate button in the menu
**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
I'm aware. Coinbase ended payment pages.

**Comment by JonnyWong16** [comment]
Updated in v1.4.21.
