### ISSUE TITLE
Duplicate libraries after changing server IP

### ISSUE THREAD

**Issue by jacobwgillespie** [Tautulli/Tautulli#1062]
My Plex server just changed IP addresses and I had to re-register it with Plex.tv, however now in PlexPy, each library shows up twice.  Each link links to the same URL (since the duplicate libraries share the same ID), and each duplicate is fetching updates from the same single server.  Is there a way to merge them or otherwise resolve?  I don't think deleting will work since the duplicates share the same library ID.  If there's something that needs to be done manually to the database I can do that too.

Here's a screenshot:

<img width="452" alt="screenshot 2017-06-29 13 22 40" src="https://user-images.githubusercontent.com/130874/27703963-9f78732e-5cce-11e7-8add-3c7a53520ed6.png">

**Version:** 1.4.20

**Branch:** master

**Commit hash:** 	29c7853380ea255cd017a77647d4485ab41c5382

**Operating system:** Debian (Linux 3.16.0-4-amd64)

**Python version:** 2.7.13

**What you did?** was forced to re-register my server with Plex.tv

**What happened?** each library was duplicated in PlexPy

**What you expected?** not sure, but some way for it to detect that those libraries are duplicated

**How can we reproduce your issue?** that'll be tricky because I'm not sure why I needed to re-associate the server with Plex.tv.  Probably by disconnecting a server from Plex.tv and re-connecting it again that _might_ do it, but I'm not sure.

**Comment by JonnyWong16** [comment]
FAQ.

**Comment by jacobwgillespie** [comment]
Okay, my bad, I read over the FAQ before posting and thought I checked it thoroughly but somehow totally missed the entry about duplicated libraries.  Sorry about that!

In case anybody else needs a fix for this and finds this issue from searching issues, it's the following FAQ entry:

> **[My libraries are duplicated! How do I remove them?](https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q8)**
> 
> This usually happens when you try to reinstall or switch your Plex Media Server. You can visit the following url to remove all libraries not associated with the current Plex server connected to PlexPy.
>
> ```
> http://localhost:8181/delete_duplicate_libraries
> ```
>
> If the libraries are duplicated on the homepage, toggle the Library Statistic cards under Settings > Homepage and click Save.

Thanks again!
