### ISSUE TITLE
PlexPy only works while Python window is open

### ISSUE THREAD

**Issue by JLACKER** [Tautulli/Tautulli#1068]
I had an issue with my computer and had to reinstall PlexPy.  I was able to install it and it works but only while my Python window is open. As soon as I close it the PlexPy page gets an error. It didnt used to be this way.

Is there a way to fix this, like have the Python window run in the background? I am sure its a setting I need to change but I cannot find it. Thanks in advance.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Install-as-a-daemon
