### ISSUE TITLE
Bug: Please verify your Server.

### ISSUE THREAD

**Issue by zobe123** [Tautulli/Tautulli#107]
what does it mean and where can i find the 'verify Button' - i don't have 'Server Details' in my plexpy
![untitled-1](https://cloud.githubusercontent.com/assets/13840542/9425228/3df473c6-4909-11e5-9d5f-e2e10a9f4e38.jpg)

Thank you very much

**Comment by drzoidberg33** [comment]
It means PlexPy cannot reach the Plex Media Server with the details you've entered into the settings.

**Comment by zobe123** [comment]
...eehm. but plex&plexpy runs fine. only if i try to edit some Settings it Response this error and nothing happens. what could it else be?

**Comment by drzoidberg33** [comment]
Just try and reverify your Plex Media Server settings first then save again. Here:

<img width="586" alt="screenshot 2015-08-22 20 27 26" src="https://cloud.githubusercontent.com/assets/1313205/9425328/bdb1e604-490c-11e5-8c2a-1fc96d4e4fdb.png">

**Comment by zobe123** [comment]
that worked for me! i cleared out Hostname and port - saved and then typed all new, now it works like it should. thank you man!

**Comment by drzoidberg33** [comment]
Cool. Closing this issue.
