### ISSUE TITLE
TV/Movie Tags for Notifications not working

### ISSUE THREAD

**Issue by soulvoid86** [Tautulli/Tautulli#1070]
**Issue:**
When attempting to post notifications of Recently Added Media to a Secret Facebook group, the <tv> and <movie> tags do not appear to be working correctly when I use the below code:

See "New" code section
https://gist.github.com/soulvoid86/6e25e86df77d199663e051abd4d2600b

It acts as if the code isn't even there and posts with the default template code listed below:

See "Default" code section
https://gist.github.com/soulvoid86/6e25e86df77d199663e051abd4d2600b

However, if I remove the <tv> and <movie> tags, like this below code, it works just fine as it should:

See "Old" code section
https://gist.github.com/soulvoid86/6e25e86df77d199663e051abd4d2600b

Another note, the {plex_url} parameter doesn't appear to be formatting the URL. It just posts it as plain text instead of a hyperlink.

**Version:**
1.4.21

**Branch:**
Master? Not sure what is needed here.

**Commit hash:**
af77e5130761850fd79038fef9b623269c02f04f

**Operating system:**
Windows 10 Pro 64-bit

**Python version:**
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

**How can we reproduce your issue?**
Listed above.

**What are your (relevant) settings?**
I have notifications turned on and they do work, it just simply ignores the script when the <tv> and <movie> tags are used.

**Link to logs:**
https://gist.github.com/soulvoid86/b107b83157239fd3115ccebbaa79be97

Thanks!

**Comment by JonnyWong16** [comment]
```
2017-07-10 12:02:27 - ERROR   :: Thread-77 : PlexPy NotificationHandler :: Unable to parse field u'showname' in notification body. Using fallback.
```

`{show_name}` not `{showname}`

Also, you can't use HTML tags for Facebook notifications. PlexPy will strip out all HTML tags before sending the notification.

**Comment by soulvoid86** [comment]
Ah, always something stupid xD

Thanks!
