### ISSUE TITLE
Unable to access web interface due to error

### ISSUE THREAD

**Issue by Nozavi** [Tautulli/Tautulli#1071]
**Version:**
Latest
(unable to access web interface, but when attempting to run from command line I do see: "INFO :: MainThread : PlexPy is up to date")
**Operating system:**
Ubuntu 17.04
**Python version:**
2.7.13
**What you did?**
I don't know for sure what triggered this problem. The only major change I've recently made was to upgrade Ubuntu to 17.04
**What happened?**
I'm unable to access the web interface. Each time I attempt to do so I see an error instead:

> 400 Bad Request
> 
> Illegal cookie name _ga
> 
> Traceback (most recent call last):
>   File "/opt/plexpy/lib/cherrypy/_cprequest.py", line 635, in respond
>     self.process_headers()
>   File "/opt/plexpy/lib/cherrypy/_cprequest.py", line 737, in process_headers
>     raise cherrypy.HTTPError(400, msg)
> HTTPError: (400, 'Illegal cookie name _ga')

**Comment by JonnyWong16** [comment]
Clear your browser cache.

**Comment by Nozavi** [comment]
Just did using CCleaner and the error is still there.

**Comment by Nozavi** [comment]
I actually had to delete the cookies associated with plexpy, thanks
