### ISSUE TITLE
No numbers showing in the home page

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#1072]
**Version:**
1.4.21

**Branch:**
master

**Commit hash:**
af77e5130761850fd79038fef9b623269c02f04f

**Operating system:**
Debian 8

**Python version:**
2.7.9

**What you did?**
Just launched plexpy

**What happened?**
There is no numbers (numbers of plays, numbers of items in library )
an other example is top users they appear in order but there is no how many plays they have so it's like plexpy knows how many plays they have but he doesn't want to show me.

**What you expected?**
Numbers on the homepage as they appear in the library tab it's weird 

**How can we reproduce your issue?**
I just got a fresh debian install and a fresh plexpy install.

**What are your (relevant) settings?**
I don't think we need to set things it's already connected to my plex server with no issues.

**Link to logs:**
https://zerobin.net/?d29497660fab980a#QprYoaYdGCM//YPRu6pQwhVd/2NLjn00SD2XwcKyI6M=

**Some screenshots**
https://vgy.me/igdfXD.png
https://vgy.me/SKvpmd.png

**Comment by JonnyWong16** [comment]
I honestly have no idea. Completely new install with a blank database?

**Comment by ghost** [comment]
Yes it's really weird I installed multiple times plexpy and it's the first time I get this bug

**Comment by ghost** [comment]
Oh nevermind I think it comes from my browser as it works flawlessly on mobile. I'll try to figure this out tomorrow (maybe just a cache and cookies cleaning would do the trick)

**Comment by ghost** [comment]
It's fixed !
I had a custom extension on Chrome who was messing with plexpy I edited the code to add a domain exception and it works now. 👍
