### ISSUE TITLE
Unable to start PlexPy on Ubuntu 16.04

### ISSUE THREAD

**Issue by fatalglitch** [Tautulli/Tautulli#1075]
Unable to start PlexPy due to error about dom.minidom missing. Error received is "ImportError: No module named dom.minidom". Logs are below.

Ubuntu Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Python Version:
Python 2.7.12

Logs:
-- Unit plexpy.service has begun starting up.
Jul 22 08:55:26 atreyu plexpy[8470]:  * Starting PlexPy
Jul 22 08:55:26 atreyu plexpy[8470]: Traceback (most recent call last):
Jul 22 08:55:26 atreyu plexpy[8470]:   File "PlexPy.py", line 35, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     import plexpy
Jul 22 08:55:26 atreyu plexpy[8470]:   File "/opt/plexpy/plexpy/__init__.py", line 34, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     import activity_pinger
Jul 22 08:55:26 atreyu plexpy[8470]:   File "/opt/plexpy/plexpy/activity_pinger.py", line 20, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     import activity_processor
Jul 22 08:55:26 atreyu plexpy[8470]:   File "/opt/plexpy/plexpy/activity_processor.py", line 21, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     import database
Jul 22 08:55:26 atreyu plexpy[8470]:   File "/opt/plexpy/plexpy/database.py", line 24, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     import logger
Jul 22 08:55:26 atreyu plexpy[8470]:   File "/opt/plexpy/plexpy/logger.py", line 30, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     import helpers
Jul 22 08:55:26 atreyu plexpy[8470]:   File "/opt/plexpy/plexpy/helpers.py", line 23, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     import ipwhois, ipwhois.exceptions, ipwhois.utils
Jul 22 08:55:26 atreyu plexpy[8470]:   File "lib/ipwhois/__init__.py", line 28, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     from .net import Net
Jul 22 08:55:26 atreyu plexpy[8470]:   File "lib/ipwhois/net.py", line 38, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     from .whois import RIR_WHOIS
Jul 22 08:55:26 atreyu plexpy[8470]:   File "lib/ipwhois/whois.py", line 30, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     from .utils import unique_everseen
Jul 22 08:55:26 atreyu plexpy[8470]:   File "lib/ipwhois/utils.py", line 26, in <module>
Jul 22 08:55:26 atreyu plexpy[8470]:     from xml.dom.minidom import parseString
Jul 22 08:55:26 atreyu plexpy[8470]: ImportError: No module named dom.minidom
Jul 22 08:55:26 atreyu plexpy[8470]:    ...fail!
Jul 22 08:55:26 atreyu systemd[1]: plexpy.service: Control process exited, code=exited status=1
Jul 22 08:55:26 atreyu systemd[1]: Failed to start LSB: starts instance of PlexPy.
-- Subject: Unit plexpy.service has failed

**Comment by JonnyWong16** [comment]
Can you post property logs please?
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q14
