### ISSUE TITLE
Recently Added Notifications will not work

### ISSUE THREAD

**Issue by masterkaj** [Tautulli/Tautulli#1077]
**Version:** 1.4.21

**Branch:** master

**Commit hash:** af77e5130761850fd79038fef9b623269c02f04f

**Operating system:** Windows Server 2012 R2

**Python version:** 2.7.9

**What you did?** Checked "Enable Recently Added Notifications"

**What happened?** No notifications are sent to Slack for recently added files, but still sends notifications for play/stop/pms down/etc...

**What you expected?** New notification for each file that is recently added

**How can we reproduce your issue?** 

-Check "Enable Recently Added Notifications"
-Test, doesn't work
-Uncheck/Recheck "Enable Recently Added Notifications"
-Test, doesn't work
-Confirm that Libraries -> Edit Mode -> "Toggle Recently Added" is enabled
-Still doesn't work
-Check the PlexPy Logs, see no notification trying to be sent for recently added items
-I do see the recently added files on the PlexPy homepage...

**What are your (relevant) settings?**

**Link to logs:**
Plexpy Logs (last 50): https://pastebin.com/uxwiwUCF

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q1
