### ISSUE TITLE
Monitor Plex Updates

### ISSUE THREAD

**Issue by MikeDawg** [Tautulli/Tautulli#1078]
**Version:** 
VERSION 1.4.21

**Branch:**
master

**Commit hash:**
af77e5130761850fd79038fef9b623269c02f04f

**Operating system:**
Linux 4.11.10-200.fc25.x86_64

**Python version:**
2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

**What you did?**
Went to the PlexPy Interface, Settings --> Plex Media Server (side-tab).

**What happened?**
After enabling "Monitor Plex Updates", and setting my version (specific to my OS/Distribution, etc. :   Linux Fedora 64-bit) 
After applying and saving (from the save button, at the bottom of the page), the selection box, where I had selected my distribution info, resets back to CentOS 64-bit.
I think it would be more valuable to users, if that selection had stayed to the value I had selected, Fedora 64-bit, as opposed to swapping back with CentOS

**What you expected?**
I think it would be more valuable to users, if that selection had stayed to the value I had selected, Fedora 64-bit, as opposed to swapping back with CentOS

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

This is me selecting my version of Plex:

![screenshot from 2017-07-23 12-00-40](https://user-images.githubusercontent.com/1027610/28501714-f851fc44-6f9e-11e7-828d-eb52c56c5410.png)

This is post-save:

![screenshot from 2017-07-23 12-00-47](https://user-images.githubusercontent.com/1027610/28501717-13d6dcdc-6f9f-11e7-970e-975f4ff2b40d.png)

**Comment by JonnyWong16** [comment]
Because there is no difference between the Fedora and CentOS builds.

You can view them here: https://plex.tv/api/downloads/1.json
