### ISSUE TITLE
Slow page loadings

### ISSUE THREAD

**Issue by blurb2m** [Tautulli/Tautulli#1079]
**Version:**
1.4.21
**Branch:**
master
**Commit hash:**
No idea?
**Operating system:**
Windows 10
**Python version:**
2.7.10
**What you did?**
Opened webpage. Same result pre and post reboot of machine.
**What happened?**
Extremely slow loading of homepage *POST* login.
**What you expected?**
Faster loading?
**How can we reproduce your issue?**

plexpy.db is 15,573 KB. Is there a "max size" where things should be archived off?
**What are your (relevant) settings?**
Plex and PlexPy both running on same machine. 
**Link to logs:**

**Comment by JonnyWong16** [comment]
Link to logs?

**Comment by blurb2m** [comment]
Is it ok to just send a portion?
Also, side question: would moving db to a SSD help?

**Comment by JonnyWong16** [comment]
At least since the last restart.

**Comment by blurb2m** [comment]
I apologize! Figured out my issue. Wife kept trying to watch a 40mbps HEVC 4k movie and it I didn't see it crushing the server!
2 weeks until 2 year anniversary with PlexPy. Thank you so much for all your amazing work.
