### ISSUE TITLE
Wrong Informations in "Activity" when there are 2 files for one Movie available

### ISSUE THREAD

**Issue by Massaguana** [Tautulli/Tautulli#1080]
**Version:** 1.4.21

**Branch:** master

**Commit hash:** af77e5130761850fd79038fef9b623269c02f04f

**Operating system:** Thecus OS "Linux 3.14.79"

**Python version:** 2.7.8 (default, Nov 20 2016, 22:44:57) [GCC 4.7.2]

**What you did?** Playing HEVC "x265" files

**What happened?** The Activity told me the playback is x264

**What you expected?** that PlexPy told me HEVC is Playing

**Link to logs:** 
[plexpy.log.zip](https://github.com/JonnyWong16/plexpy/files/1185531/plexpy.log.zip)

I have the Movie in 2 files, one x264 one x265 (HEVC) in mkv. Start Playing Plex ask me witch version i wood like to use. i say HEVC. But PlexPy told me there is x264 Playing. When i delete the x264 file and start Playing PlexPy told me HEVC ist Playing. 
I test this with an x264 1080p file and and HEVC UHD file... In PlexPy i see this:
![img_0002](https://user-images.githubusercontent.com/15521791/28751810-4ff6d0e2-7511-11e7-874b-09b0601e07db.jpg)

x264 and UHD... that must be wrong... mayby Plexpy put the wrong Information when there are 2 version available.

Regrads
Massaguana

**Comment by JonnyWong16** [comment]
PlexPy can only grab the info for the first file listed.

**Comment by Massaguana** [comment]
are there plans to change this?

**Comment by JonnyWong16** [comment]
I have looked into this for v2.
