### ISSUE TITLE
PlexPy Daemon from Scheduler does not start

### ISSUE THREAD

**Issue by loibi** [Tautulli/Tautulli#1081]
Hi,

Did setup PlexPy on my Win 10 PMS - works perfect.
Then I tried to setup the Daemon as described in the Wiki
Interactive Mode works.
But running the same .cmd File from Scheduler starts the pythonw.exe in Taskmanager but I cant reach the Webinterface.
Also no Logs in the PlexPy Folders are written
Any Ideas?

**Comment by JonnyWong16** [comment]
What cmd file? None of the daemon instructions in the wiki have a cmd file.

**Comment by loibi** [comment]
Followed this Instruction (non interactive is the one I want to use)
https://github.com/JonnyWong16/plexpy/wiki/Install-as-a-daemon

> Create a new text file and enter the following line: Start C:\Python27\pythonw.exe C:\PlexPy\PlexPy.py
> Save the file in your PlexPy folder as PlexPy.cmd (e.g. C:\PlexPy\PlexPy.cmd)

**Comment by JonnyWong16** [comment]
I don't know. Double check all your settings.

If nothing works, delete the `config.ini` file to reset all your settings.

**Comment by cameronrbrown** [comment]
Same problem. Is it a windows 10 thing?

**Comment by ghost** [comment]
same issue as well
