### ISSUE TITLE
Facebook artwork issue

### ISSUE THREAD

**Issue by trackermb** [Tautulli/Tautulli#1082]
Hi have setup facebook group and notifications are working a dream but having issue with a lot of TV shows not showing artwork example below.  Movies work 100% but it only seems to TV shows that have the issue. Any Ideas? Using Master branch up to date version.

Most TV Shows look like this
![image](https://user-images.githubusercontent.com/7849892/28890398-e3605eb6-77be-11e7-9d55-8f085e5e1072.png)

Movies are fine
![image](https://user-images.githubusercontent.com/7849892/28890517-400a41a4-77bf-11e7-8d72-d9718ecf5283.png)

Sometimes get this 
![image](https://user-images.githubusercontent.com/7849892/28890563-65a48b54-77bf-11e7-97e5-b5bd4bb36707.png)

One a few shows look correct 
![image](https://user-images.githubusercontent.com/7849892/28890626-8f6e4b1e-77bf-11e7-93c8-5a787ae06426.png)
![image](https://user-images.githubusercontent.com/7849892/28890652-aae778e8-77bf-11e7-99a2-9dd5d1f255ec.png)

**Comment by JonnyWong16** [comment]
#1063
