### ISSUE TITLE
Multiple Telegram Notifications 

### ISSUE THREAD

**Issue by badgerhome** [Tautulli/Tautulli#1086]
Version: 1.4.21

Branch: master

Commit hash: af77e5130761850fd79038fef9b623269c02f04f

Operating system: Debian Linux 3.16.0-4-amd64

**

Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

**What you did?**
Enabled Telegram notifications, stop, start, recently added

**What happened?**
Getting x2 of the same notification to Telegram at the same time.

**What you expected?**
One notification 

**How can we reproduce your issue?**

**What are your (relevant) settings?**

Also have Facebook group notifications enabled, seems to only be ending them once (only recently added for FB) 

Will add logs when not on mobile device

**Comment by badgerhome** [comment]
I've noticed that I'm getting one of the actual username of the person when they start playing and also one of the friendly name I've set for them too.

**Comment by JonnyWong16** [comment]
Need logs.
