### ISSUE TITLE
increase check event 

### ISSUE THREAD

**Issue by killpilot80** [Tautulli/Tautulli#1087]
hi team,

i develop a custom script for my domotic network, i try interface plex media server with my domotic box with plexpy.

my script works fine, my defined action are correctly launch in my domotic box, but there is a problem...

latency... the time between i make a action, for exemple Pause, and the time when plexpy catch the event and launch the notification script there is sometime more than 30-50s, is slow....

Is there a way to reduce this latency ?

thank for your help.

**Comment by JonnyWong16** [comment]
Enable websockets.

**Comment by killpilot80** [comment]
thank,
Put in the mile, thanks for help,

and thank for your time for the community :D
