### ISSUE TITLE
Information in History -> Source Details incorrect for Audio

### ISSUE THREAD

**Issue by brimur** [Tautulli/Tautulli#1088]
VERSION 1.4.21

I kept seeing streams were being partially transcoded for some devices in History so I looked at the details. This is an example of what I am seeing... http://i.imgur.com/5v4qEBi.png

You can see the audio is transcoded but both source and stream details are the same. When I check the source file itself however I see the audio is AC3 5.1 which would require trancoding. So it looks like the Source detail is just using the same variables as the Stream Details for Audio.

**Comment by JonnyWong16** [comment]
Temporarily fixed in v1.4.22.
