### ISSUE TITLE
After an update issue showing history page

### ISSUE THREAD

**Issue by msh100** [Tautulli/Tautulli#109]
I had a notice in the bottom right for an update, I ran that. 

Then I started getting errors on the "history" page.

Log

```
2015-08-22 17:03:23 WARNING Unable to execute database query.
2015-08-22 17:03:23 ERROR   Database error: ambiguous column name: id
2015-08-22 17:02:57 WARNING Unable to execute database query.
2015-08-22 17:02:57 ERROR   Database error: ambiguous column name: id
```

Javascript `alert()` text

```
DataTables warning: table id=history_table - Requested unknown parameter 'date' for row 0.
```

I tried restarting PlexPy, this did not help.

**Comment by JonnyWong16** [comment]
Try force refreshing the page.

**Comment by msh100** [comment]
Already did

**Comment by msh100** [comment]
That said, I just tried another browser. I will close this for now and reopen if I can't find the solution.

**Comment by JonnyWong16** [comment]
https://forums.plex.tv/discussion/comment/1001385/#Comment_1001385

**Comment by msh100** [comment]
Ah perfect, that has done it. Thanks @JonnyWong16
