### ISSUE TITLE
TV Shows - Notifications & Episode Information

### ISSUE THREAD

**Issue by herbi3** [Tautulli/Tautulli#1090]
All notification agents are only sending the TV Show name. Instead of The season number, episode number, summary etc. also. Is this a bug, or would it be a feature request? I am genuinely unsure.

**Comment by ghost** [comment]
There's a whole section with nice, bright text in the settings if you use your eyes a little harder. 😉 

![img](https://i.imgur.com/crmruYH.png)

**Comment by herbi3** [comment]
It's easy to presume this is only relevant to the season metadata itself for season only notifications - I wouldn't expect the feature to affect the individual notifications of episodes. mate.
