### ISSUE TITLE
::REQUEST:: Concurrent Users Alert - Stop Playback

### ISSUE THREAD

**Issue by Foebik** [Tautulli/Tautulli#1091]
Is there a chance that if you have the "Concurrent Playback" alert set to X number,  and API call can be made to kill (stop playback) the most recent stream that started? 
Would also be nice if you can use the custom message option for that is already included in the manual "stop playback" to explain why.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests
