### ISSUE TITLE
GeoLite2 database won't install ... this is not the cache refresh issue

### ISSUE THREAD

**Issue by adx442** [Tautulli/Tautulli#1092]
My version information:
OS: Ubuntu 16.04.3 Server 
PlexPy:  Most current version
Info from the Settings page:
Git Branch: | master
-- | --
Git Commit Hash: | ec685407bbd4924b7c94c2dab2f1754089e77322
Configuration File: | /opt/plexpy/config.ini
Database File: | /home/jack/plexpy/plexpy.db
Log File: | /home/jack/plexpy/logs/plexpy.log
Backup Directory: | /home/jack/plexpy/backups
Cache Directory: | /home/jack/plexpy/cache
GeoLite2 Database: | Click here to install the GeoLite2 database.
Arguments: | ['--quiet', '--daemon', '--nolaunch', '--config', '/opt/plexpy/config.ini', '--datadir', '/home/jack/plexpy']
Platform: | Linux 4.4.0-92-generic
Python Version: | 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

I'm unable to install the MaxMind database through the settings page.  Here's what I've tried:
 
1) Emptied the browser cache completely
2) Used a brand new browser in a VM
3) Manually downloading and extracting the MM2 database to the folder and adding that location to the config.ini and restarting (no effect)
3a) With the database manually extracted to the main PlexPy directory, clicking the install link from the settings page ... this results in the mmdb file being overwritten with a 0 byte file (and failing).
4) Checked permissions on all files and ownership ... everything else works perfectly, including making other settings changes.  
5) The config.ini file section about the maxmind database gets overwritten on restart even when I specify the extracted database location.  
6) Erased the mmdb file, cleared the cache, tried again, still getting a 0 byte mmdb file created.

Here's the relevant section of the logs:

2017-08-20 10:34:57 - DEBUG   :: CP Server Thread-2 : PlexPy Helpers :: Downloading GeoLite2 gzip file from MaxMind...
2017-08-20 10:35:03 - DEBUG   :: CP Server Thread-2 : PlexPy Helpers :: Extracting GeoLite2 database...
2017-08-20 10:35:03 - ERROR   :: CP Server Thread-2 : PlexPy Helpers :: Failed to extract the GeoLite2 database: Error -3 while decompressing: invalid literal/length code

Thank you!

**Comment by JonnyWong16** [comment]
I honestly have no idea.

If you are manually downloading it, you can't edit the config file while PlexPy is still running. Make sure PlexPy is shutdown first.

You should be downloading and extracting this file to the folder below:
http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz

```
geoip_db = /home/jack/plexpy/GeoLite2-City.mmdb
```

If everything is correct, then it should just list the GeoLite2 database on the settings page. It won't ask you to install it.

**Comment by adx442** [comment]
Okay, I had not been updating the config.ini while it was shutdown (I assumed it was only read on startup).  I'll give that a try this evening.  Your note about the location is what I was using, so this should work.

Thank you very much for the quick response, and thanks very much for Plexpy, it's amazing!

**Comment by adx442** [comment]
Stopping Plexpy and editing the configuration file with the manual location for the Maxmind database worked, thank you! Closing the issue.
