### ISSUE TITLE
Latest update has broken Facebook updates and Prowl

### ISSUE THREAD

**Issue by kevmasonk1** [Tautulli/Tautulli#1093]
Hi

Since latest update facebook updates now no longer work (Automated when something added to the library) Only test notification works.
Also Prowl doesn't work even on test, instead just get an error message advising 500 internal server error.

Tried full reinstall but same issue.

No error in logs at all it appears to have sent, please advise

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#if-nothing-has-worked
