### ISSUE TITLE
Duration watched very high

### ISSUE THREAD

**Issue by toomuchio** [Tautulli/Tautulli#1095]
Latest version just upgraded today, it's been an issue for a few weeks though. Latest Plex Pass Server version as well.

http://i.imgur.com/9HdnnFv.png

Been happening at random on random shows, not entirely sure why, haven't changed a thing on my server or plexpy on months except for applying updates.

**Comment by JonnyWong16** [comment]
Search the GItHub issues. It's been answered many times before.

**Comment by toomuchio** [comment]
My mistake I should have searched...... Thought it was a new issue since I've been using sockets for months now on v1 and didn't encounter it until now, very odd...

#925 if anybody else is wondering.
