### ISSUE TITLE
NMA notifications not firing off

### ISSUE THREAD

**Issue by docwho76** [Tautulli/Tautulli#1097]
Version: 1.4.22
Branch: master
Commit hash: ec685407bbd4924b7c94c2dab2f1754089e77322
Operating system: Ubuntu Linux 14.04 Linux 4.4.0-78-generic
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

What you did? Setup notifications via NotifyMyAndroid, test notifications worked.

What happened? Never got notifications for anything but the test notifications

What you expected? Notifications to show up when users played items

How can we reproduce your issue? Setup NMA provider with my NMA hash. Ran test. Checked user settings showed that all users had notifications turned on. Also tried unsetting this and resetting it. No change.

What are your (relevant) settings? 
http://imgur.com/khe6ytv
http://imgur.com/uOUC1Xv
http://imgur.com/vjqDnwR

Link to logs: It would appear there are no notification logs? http://imgur.com/ltXNvs1

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q1

Also, you need to post the PlexPy logs.

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q14
