### ISSUE TITLE
Required Secure Connections causes "There was an error communicating with your Plex Server"

### ISSUE THREAD

**Issue by masterkaj** [Tautulli/Tautulli#1098]
I read through the FAQ at first and saw that it may be a DNS rebind issue (I use a version of Open-WRT / Gargoyle firmware on my router).  However, I have since fixed that issue and am now able to access https://LOCAL-IP-ADDRESS.SERVER-HASH.plex.direct:32400/web and everything matches my config file as well.  

Now that I fixed the DNS rebind issue, I tried changing my plex setting from Preferred to Required Secure Connection and I got the same error, "There was an error communicating with your Plex Server."  Note: Use SSL is selected in PlexPy options throughout all my testing.

PlexPy and the PMS are on the same machine running Windows 2012 R2.  I think it may have to do with me manually entering the IP's inside my PlexPy settings (using 192.168.1.6 instead of localhost).  The reason I manually entered my server IP is because I was having issues accessing it externally.

- Settings -> PMS -> Plex IP or Hostname = 192.168.1.6, Plex set to Preferred Secure connections:  PlexPy works outside my server and the "verify server" works.

- Settings -> PMS -> Plex IP or Hostname = 192.168.1.6, Plex set to Required Secure connections:  PlexPy can't connect to the Plex server at all and "verify server" fails.

- Settings -> PMS -> Plex IP or Hostname = localhost, Plex set to Preferred Secure connections:  PlexPy can't connect to the Plex server at all, but "verify server" works.

- Settings -> PMS -> Plex IP or Hostname = localhost, Plex set to Required Secure connections:  PlexPy can't connect to the Plex server at all, but "verify server" works.

It seems it has something to do with this?  I never figured out why I can't use "localhost" when both Plex and PlexPy are on 192.168.1.6.  I've been trying to solve this all day and have no idea what to do next.

Here is the latest log with me manually entering the Plex IP and Required Secure connections: https://pastebin.com/DmmWs707

**Comment by JonnyWong16** [comment]
From your logs it looks like PlexPy is failing to retrieve your `*.plex.direct` address because your Plex token is invalid. Try fetching a new token in the settings.

**Comment by masterkaj** [comment]
I think all the issues I had over the past year or so has stemmed from the fact that I manually installed the PlexPy folder to Program Files (x86) on Windows Server 2012 R2.  You need special permissions to edit that folder and it made networking permissions a nightmare as well.  I have since moved the folder to the C:\ and all my issues disappeared immediately.  

I confirmed it worked on the same server as my PMS and then moved PlexPy to it's own VM where I am installing all my miscellaneous programs and scripts that I run for various other guest machines.

Edit: I did notice that the PlexPy CLI on my new server is constantly outputting the following warning: 
C:\PlexPy\lib/cherrypy\wgiserver\ssl_pyopenssl.py:247: DepractionWarning: ConnectionType has been deprecated, use Connection instead if SSL and isinstance(sock, SSL.ConnectionType):

I do use SSL with my own certificates to access PlexPy remotely, but I am unsure what that warning means and if I should ignore it because everything seems to be working just fine.

**Comment by JonnyWong16** [comment]
I think you can ignore that warning.
