### ISSUE TITLE
internal 500 server error displaying current activity on main page

### ISSUE THREAD

**Issue by tbae2** [Tautulli/Tautulli#11]
Hello 

feat06 from the forums, seem to be getting this error after updating to the last commit 

![image](https://cloud.githubusercontent.com/assets/7338550/8586243/7d8bab2a-25ba-11e5-8547-72d936844be6.png)

Please let me know how I can help 

Thanks!

**Comment by drzoidberg33** [comment]
Hey,

That shouldn't be happening. Can you restart PlexPy, check the PlexPy logs and see if you're getting any errors regarding the database being read-only or any errors after start up.

**Comment by tbae2** [comment]
Hello, 

I loaded it up again this morning (no restart) just to start troubleshooting and it randomly works? I'll keep an eye on it and post the issue again if it occurs. So strange!
