### ISSUE TITLE
Plexivity import fails

### ISSUE THREAD

**Issue by grahams** [Tautulli/Tautulli#1101]
I'm trying to import my Plexivity data to no avail.  I get a python stacktrace in the logs:

```py
Uncaught exception: Traceback (most recent call last):
    File "/app/plexpy/plexpy/logger.py", line 270, in new_run 
        old_run(*args, **kwargs) 
    File "/usr/lib/python2.7/threading.py", line 754, in run 
        self.__target(*self.__args, **self.__kwargs) 
    File "/app/plexpy/plexpy/plexivity_import.py", line 426, in import_from_plexivity 
        import_ignore_interval=import_ignore_interval) 
    File "/app/plexpy/plexpy/activity_processor.py", line 296, in write_session_history 
        metadata['duration'], metadata['width'], metadata['height'], metadata['container'], 
KeyError: 'width' 
```

I'm using the PlexPy docker image, which is v1.4.22
I'm using the latest github version of Plexivity (which hasn't been updated in some time afaict, and from which I struggle to find a version number): https://github.com/mutschler/plexivity

I noticed the importer says to ensure my Plexivity database is 0.9.8 or higher, but the changelogs on Github (and the old bitbucket repo) for Plexivity stop at 0.9.7.  Is there some other fork/version of Plexivity somewhere with a higher release #?

Import settings:
<img width="637" alt="jtedun" src="https://user-images.githubusercontent.com/49202/29756436-088b8f1e-8b72-11e7-97ac-593c07f20549.png">

**Comment by JonnyWong16** [comment]
Fixed in v1.4.23.
