### ISSUE TITLE
No userdata or history after a new install.

### ISSUE THREAD

**Issue by Diquito** [Tautulli/Tautulli#1102]
**Version:1.4.22

**Branch: master

**Commit hash: ec685407bbd4924b7c94c2dab2f1754089e77322

**Operating system: Mac OSX 10.12.6

**Python version: 3.6.2

**What you did? New install.

**What happened? No Userdata, user list is there and correct, But no userdata or history data.

**What you expected? History and user data.

**How can we reproduce your issue? 
I just installed according instructions and started the program, have not done anything extra.

**What are your (relevant) settings? Default, Only settings that are required in the setup process.

**Link to logs: https://pastebin.com/mQKvYnCh

Screenshots:
[Empty Graphs
](https://www.dropbox.com/s/z1zkk9g0imb55mx/Graphs.png?dl=0)

[Empty History](https://www.dropbox.com/s/96c43q5avhftzl7/History.png?dl=0)

[Empty User Data](https://www.dropbox.com/s/cgk7948el0z0rhj/Userdata.png?dl=0)

**Comment by JonnyWong16** [comment]
Please read the FAQ.

**Comment by Diquito** [comment]
I have read the faq and even googled before posting.. so what did I miss.. Better with a hint on what to read in the FAQ...

**Comment by Diquito** [comment]
Sorry forget my previlous post.. I just saw now that the history is not from Plex but is saved in PlexPy.. didn't look for that earlier.
Thanks
