### ISSUE TITLE
PlexPy does not correcly detect source IPv6 in X-Forwarded-For header

### ISSUE THREAD

**Issue by vistalba** [Tautulli/Tautulli#1103]
**Version:**
VERSION 1.4.22

**Branch:**
master

**Commit hash:**
ec685407bbd4924b7c94c2dab2f1754089e77322

**Operating system:**
Ubuntu 16.04 LTS

**Python version:**
2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]

**What you did?**
My PlexPy runs behind a traefik rproxy. The PlexPy backend has a internal ipv4 address.

Client (Internet, ipv6) -> traefik (frontend, ipv6) -> traefik (backend, ipv4 10.x.x.x) -> plexpy (ipv4 10.x.x.y).

**What happened?**
Configuration is working without any functional issue. If a client connects over ipv6 under "ACTIVITY" it shows the internal ipv4 address (10.x.x.x) and does not show the ipv6 address that is delivered in the x-forwarded-for header.

**What you expected?**
Show ipv6 address in ACTIVITY section.

**Comment by JonnyWong16** [comment]
PlexPy does not read any IP addresses, it only displays what the Plex server is reporting through the API. 

There is nothing I can do. It had to be resolved by Plex.

https://forums.plex.tv/discussion/254026/plex-api-sessions-status-not-honoring-x-forwarded-for-x-real-ip-with-ipv6-clients
