### ISSUE TITLE
Plexpy showing wrong images (and yes I cleared the cache)

### ISSUE THREAD

**Issue by stve-a** [Tautulli/Tautulli#1105]
**Version:** VERSION 1.4.22

**Branch:** master

**Operating system:** Raspbian Linux 4.9.35-v7+

**Python version:** 2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]

**What you did?** Nothing, until one day watch statistics started showing wrong images, even the refresh icon on the images does not resolve the issue

I cleared both "image cache" and "all cache" in the general settings for Plexpy and rebooted.
Plex showing the correct images/art.

**Comment by JonnyWong16** [comment]
Have you cleared your browser cache?

**Comment by stve-a** [comment]
Hey jonnyWong16, 

I actually forgot to try that, but I did after you mentioned it and did not resolve the issue.
I also tried a couple of other browsers I never use like IE and Opera and same issue there.

**Comment by stve-a** [comment]
I did some extra checking, and it appears to be only for 1 movie now.
When I click through, it goes to the TV shows where the image is from rather then the movie.

**Comment by JonnyWong16** [comment]
You moved the movie after the history was recorded in PlexPy and the ID number for the movie changed in Plex. You can try fixing it with the "Fix Metadata" button.
