### ISSUE TITLE
streaming from a new device: Plex for LG (NetCast) keeps getting added as new

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#1108]
streaming from a new device: Plex for LG (NetCast) even if this user already played with this device.

Everytime it gets added as e new device, no problem with other users/devices.

**Comment by dotsam** [comment]
I’m seeing this in the last few weeks as well, getting notifications for users streaming from “new” devices that they’ve been streaming from for a while. This is with a pretty large database now, so I’m wondering if an index has overflowed somewhere?

**Comment by dannyzumwalt** [comment]
Been seeing this as well for several months actually. Friend accounts as well as local. All types of devices (roku, chrome cast, Apple TV, etc)

**Comment by tj1816** [comment]
Yep, same issue here

**Comment by dotsam** [comment]
Running the `SELECT machine_id FROM session_history WHERE user_id = ? GROUP BY machine_id` query from `get_user_devices` for one of the users that frequently causes this seems to return a sane list of machine ID's. I've added `{machine_id}` to my new device notification to try and troubleshoot further.
