### ISSUE TITLE
PlexPy not detecting installed version

### ISSUE THREAD

**Issue by phhowe17** [Tautulli/Tautulli#1109]
**Version:**  v1.4.22
**Branch:**
**Commit hash:**
**Operating system:** Windows 10, CU
**Python version:** Python 2.7.13
**What you did?**

Installed PlexPy using the GitGUI method. PlexPy is running and correctly monitoring Plex

**What happened?**
PlexPy reports: You're running an unknown version of PlexPy. Update or Close

Logs show:

2017-09-12 13:38:13 - INFO :: Thread-12 : PlexPy Config :: Writing configuration to file
xi2017-09-12 13:38:14 - DEBUG :: Thread-18 : Latest version is ec685407bbd4924b7c94c2dab2f1754089e77322
2017-09-12 13:38:14 - INFO :: Thread-18 : You are running an unknown version of PlexPy. Run the updater to identify your version
t2017-09-12 13:38:14 - INFO :: Thread-21 : PlexPy Config :: Writing configuration to file
2017-09-12 13:38:14 - INFO :: Thread-21 : PlexPy Pmsconnect :: Libraries list refreshed.

**What you expected?**
Correct version detection and update.

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
https://pastebin.com/J4wHxu8x
Logs start just before pressing Update in the GUI.

Config file: https://pastebin.com/nkxGZvvW

**Comment by MikeDawg** [comment]
Did you already refer to the FAQ?   https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#windows-q2

**Comment by phhowe17** [comment]
Well, I thought I did.  Uninstalled every thing, started over. Stared at the "Use Git from the Windows command prompt" for a long time. click.  Now it works.  Sigh.  PEBKAC.
