### ISSUE TITLE
No IP for failed logins

### ISSUE THREAD

**Issue by briped** [Tautulli/Tautulli#1111]
**Version:**
VERSION 1.4.22

**Branch:**
Git Branch: master

**Commit hash:**
Git Commit Hash: ec685407bbd4924b7c94c2dab2f1754089e77322

**Operating system:**
Platform: Linux 4.10.0-33-generic (Lubuntu 17.04 x64)

**Python version:**
Python Version: 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

**What you did?**
Attempted to find IP of failed logins in "/opt/plexpy/logs/plexpy.log" and the logs interface of the PlexPy UI.

I've tried to see a setting somewhere, or a FAQ somewhere, where I can enable this feature, but I have not been able to find it.

**What happened?**
No IPs logged for failed logins in either place. Only IP of successful logins shown in the logs interface of the PlexPy UI.

I know it says to link to the full log. If you still require more information I'll of course provide that.

I can't decide if it's a bug that this is missing, or if it's a feature request to add it. So I'll go for a bug for now.

`2017-09-15 00:02:56	DEBUG	PlexPy WebAuth :: Invalid login attempt from 'adminuser'.
2017-09-15 00:02:56	WARNING	PlexPy WebAuth :: Unable to retrieve Plex.tv user token for user 'adminuser'.
2017-09-15 00:02:56	WARNING	Failed to access uri endpoint /users/sign_in.xml. Status code 401
2017-09-14 23:59:14	DEBUG	PlexPy WebAuth :: Invalid login attempt from 'wronguser'.
2017-09-14 23:59:14	WARNING	PlexPy WebAuth :: Unable to retrieve Plex.tv user token for user 'wronguser'.
2017-09-14 23:59:14	WARNING	Failed to access uri endpoint /users/sign_in.xml. Status code 401
2017-09-14 23:52:00	DEBUG	PlexPy WebAuth :: Admin user 'adminuser' logged into PlexPy.
2017-09-14 23:39:00	DEBUG	PlexPy WebAuth :: Guest user 'plexuser' logged into PlexPy.`

**What you expected?**
To see the IP address of a failed login, for use in blocking mechanisms such as Fail2Ban.

**How can we reproduce your issue?**
Simply login to PlexPy using a wrong user and/or wrong password and check the logs.

**Comment by JonnyWong16** [comment]
PlexPy does not log invalid logins.

**Comment by briped** [comment]
I'm not sure I understand your comment?

In the "/opt/plexpy/logs/plexpy.log" it clearly shows "Invalid login attempt" when I type in an incorrect username and/or password, as can also be seen in the 7 lines I pasted from the very same log. Hence, PlexPy (at least how I see it) does in fact log invalid logins. It just does not show the source IP of the failed login.

Since the "adminuser" isn't a plex user, that user, and its associated login attempt, can't come from Plex and therefore must come from PlexPy. Or have I completely misunderstood when it is Plex that is handling the login and when it's PlexPy that is handling the login?

**Comment by JonnyWong16** [comment]
I mean there is no data saved anywhere about the invalid logins. The line in the logs is the only thing.

**Comment by briped** [comment]
Is it possible to add source/X-Forwarded-Fo IP to that log entry for the failed attempt?

**Comment by JonnyWong16** [comment]
Maybe.

**Comment by JonnyWong16** [comment]
Added in v2.
