### ISSUE TITLE
Plex watched sync

### ISSUE THREAD

**Issue by Troubadoure** [Tautulli/Tautulli#1113]
Would it be possible to sync watched status back to my Plex server? I've lost my watched data so many times and this would allow for a perfect solution as a kind of back up. I know trakt.tv can do this however, I'm not really sure how much I like keeping all my user data on a third party site. This could be the perfect solution, especially as PlexPy seems like the most advanced and polished Plex notifier out there!

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests

**Comment by Troubadoure** [comment]
My bad - Updated https://feathub.com/JonnyWong16/plexpy/+226

**Comment by JonnyWong16** [comment]
Duplicate https://feathub.com/JonnyWong16/plexpy/+215
