### ISSUE TITLE
Two type of notification

### ISSUE THREAD

**Issue by Cylae** [Tautulli/Tautulli#1114]
Hello,

I just would like to know if there is a way to set two types of notifications : one type for movies and one type for show because when an episode is added, I have a notification like this : 

> Hell's Kitchen (US) - Aerial Manuevers - S16E11 aired on 2017-01-05 was recently added to Cylae's Plex server.

but when a movie is added, I have a notification like this : 

> Man on Wire - S00E00 aired on 2008-07-25 was recently added to Cylae's Plex server.

Thank you for your help !

**Comment by SgtBatten** [comment]
This already exists. Use tv and movie tags to specify bits you only want to use In a notification for that type of media. All the instructions are in plexpy on the notification page.

`<tv>your tv specific info here </tv>`

**Comment by Cylae** [comment]
Thanks men !
