### ISSUE TITLE
Duration is sometimes corrupted

### ISSUE THREAD

**Issue by redfellow** [Tautulli/Tautulli#1116]
Screenshot from History page, sorted by the Duration column: https://vgy.me/1NjMrN.png

**Version:** 1.4.22 

**Branch:** master

**Commit hash:** ec685407bbd4924b7c94c2dab2f1754089e77322

**Operating system:** Windows 10 Pro N

**Python version:** 2.7.11

**What you did?** Used Plex normally

**What happened?** Sometimes Duration info is out of whack

**What you expected?** For PlexPy to detect that an item that was played for 8 minutes and then paused for 6180 minutes should in fact have a duration of 8 minutes and not 6188.

**How can we reproduce your issue?** Not sure

**What are your (relevant) settings?** Happens on Browser play, Samsung TV and with Chromecasting

**Comment by JonnyWong16** [comment]
#992
