### ISSUE TITLE
Problem to restore a deleted user !

### ISSUE THREAD

**Issue by vincegre** [Tautulli/Tautulli#1117]
Hi

I tried to restore a deleted user using indications in FAQ but it's not working :(

```
http://localhost:8181/undelete_user?user_id=<user_id>
http://localhost:8181/undelete_user?username=<username>
```
It lists an URL to get list of user_id but it doesn't work, it always complains that I have to be looged but I'm already well logged with my Plex account !
I tried with the username but not much effect also ! I just get returned to main page of Plexpy when I try the URL (username of user has a dot in it, maybe a problem ?

Plexpass 1.9.2.4285
Ubuntu 16.04.2
Plexpy 
Thanks

Vincèn

**Comment by JonnyWong16** [comment]
Logout of plex.tv and log back in, then go to the URL.

**Comment by vincegre** [comment]
Thanks it made it and I got confirmation when using the special url by a text message ;)

`{"message": "Re-added user with username xxxxxxxxx."}`
