### ISSUE TITLE
PlexPy Logs stopped 17 days ago

### ISSUE THREAD

**Issue by tronyx** [Tautulli/Tautulli#1118]
**Version:**
1.4.22

**Branch:**
Master

**Commit hash:**

ec685407bbd4924b7c94c2dab2f1754089e77322

**Operating system:**
Windows Server 2012

**Python version:**
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

**What you did?**
Tried to view PlexPy Logs tab within Logs

**What happened?**
Logs stop 17 days ago

**What you expected?**
To see logs for missing days

**How can we reproduce your issue?**

Try to view PlexPy logs

**What are your (relevant) settings?**

**Link to logs:**

So when I go to the PlexPy Logs tab within Settings -> View Logs, the PlexPy logs are 17 days old. Last time stamp is 2017-09-11 23:26:04. All other log tabs are populating as I'd expect. I've tried restarting PlexPy and then even the Server itself, but the result is the same. I want to add that my Slack notifications are still working so it's obviously logging data, but it's maybe just not viewable or something.

**Comment by tronyx** [comment]
So is there a limit on PlexPy logs? I cleared the logs and now it's working as expected.

**Comment by JonnyWong16** [comment]
It cycles 5 files at 5MB max each.

**Comment by tronyx** [comment]
Right, but shouldn't it be rotating and not just get choked up?

**Comment by JonnyWong16** [comment]
I don't know. Check your permissions. Make sure there is enough disk space. Not much more I can tell you.

**Comment by tronyx** [comment]
Nothing has changed on this system other than updating Plex and PlexPy. I cleared Notification Logs too and now that's not logging anything. Is there anything else I can provide you to help troubleshoot?

**Comment by JonnyWong16** [comment]
Notification logs are stored in the database, not a log file, so that's an unrelated issue. I'd notifications are still working, then I don't know. 

Normally I'd ask for the logs to diagnose the issue, but that won't work in this case, so I really don't know. But to me it sounds like an OS level issue.

**Comment by notlimahrelyt** [comment]
I'm having a similar issue, if I go to PlexPy logs, nothing shows and "fetching rows" rotates infinitely in the bottom right. 

If I clear logs I receive the log entry "Cleared the plexpy.log file." and all is back to normal again, play/pause logs start coming through, etc.

If I leave the Logs page and return back to Logs, the issue returns.. I'm forced to clear logs to begin viewing them again.

In an attempt to resolve it I have done the following:

1) Removed the "PlexPy Logs" Log file manually and allowed PlexPy to create a new one.
2) I have Flushed Temporary Sessions from the "Extra Settings" tab. 
3) Removed PlexPy completely including config files, reinstalled latest version and reconfigured from scratch. (This seemed to resolve it for about a day or so, but the issue returned.)

Has anyone seem/heard of this happening and found the trigger?

Thanks.

**Comment by JonnyWong16** [comment]
Possibly related to #1146.

**Comment by tronyx** [comment]
I noticed that this seemed to happen in conjunction with a paused stream and one of Blacktwins kill stream scripts (which may or may not be a coincidence), but the logging stopped until I killed the stream.

**Comment by tronyx** [comment]
Closing per #1446.
