### ISSUE TITLE
Get 500 internal server error after last update

### ISSUE THREAD

**Issue by Magikarplvl4** [Tautulli/Tautulli#112]
When i click on the picture the gambler on the home page by most i get a 500 error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\drzoidberg33-plexpy-bca1032\lib/cherrypy_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\drzoidberg33-plexpy-bca1032\lib/cherrypy\lib\encoding.py", line 217, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\drzoidberg33-plexpy-bca1032\lib/cherrypy_cpdispatch.py", line 61, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\drzoidberg33-plexpy-bca1032\plexpy\webserve.py", line 740, in info
    result = pms_connect.get_metadata_details(rating_key=item_id)['metadata']
TypeError: list indices must be integers, not str

**Comment by drzoidberg33** [comment]
Where are you clicking through from, which page?

Is the media item still in your Plex library?

**Comment by Magikarplvl4** [comment]
![klik](https://cloud.githubusercontent.com/assets/2944704/9428804/f376af64-49ba-11e5-88d1-766fe1f6be7e.png)

Yes its still in my library

**Comment by drzoidberg33** [comment]
I've addressed this "ugly" error page in my latest commit however I'm not yet exactly sure why you would be getting this error if it's still in your Plex Library.

Please can you click that link get the error and then post the PlexPy log.

**Comment by Magikarplvl4** [comment]
Maybe Couchpotato update the movie to a better quality and change the movie file name that plexpy didn't understand?

Error in plexpy log after i click on the link:
01-sep-2015 22:19:21 - WARNING :: CP Server Thread-11 : Failed to access uri endpoint /library/metadata/4500. Status code 404

**Comment by drzoidberg33** [comment]
Status code 404 means the page cannot be found. If the file did change then it is possible it was re-added with a different rating key into your Plex library.

Unfortunately nothing much you can do about that other than manually going to change the rating key value in the PlexPy db.

**Comment by Magikarplvl4** [comment]
pitty :(

Is it possible to update the rating key automatic?
Sonarr, CP and SB are all made to download better quality when its available.
I and many other users can more often get this error .

**Comment by drzoidberg33** [comment]
I'm closing this as it's not really an issue in PlexPy, it's the id in the Plex library itself which has changed.

**Comment by JonnyWong16** [comment]
Is it worth using the PMS /search API to try to match the item? It doesn't have to update the database (although it would be nice if it did), just return the metadata so it can generate the info page.
