### ISSUE TITLE
Since latest plexserver update plexpy partly shows wrong numbers

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#1122]
I am running latest stable branch plexpy on Debian, since latest plexmediaserver update statistics changed a lot.
For example most active user has 299 hours instead of 90.
Some movies has been watched by a single user for 3200 minutes etc etc.
There seems to be something wrong.

**Comment by drachul** [comment]
I've noticed the same issue with my setup as well.
Haven't spent a whole bunch of time trying to debug/troubleshoot it, but it seems to be an issue with the stop time of play sessions.  In my case the ones that have an issue have a stop time of "10:04" when the start time was something like "20:40", or "17:47", this leads to very large durations.

**Comment by ghost** [comment]
Different start/stop times for me

**Comment by drachul** [comment]
In your case are the stop times the same (in the error case)?

**Comment by JonnyWong16** [comment]
#992
