### ISSUE TITLE
incomplete metadata info in notification agent

### ISSUE THREAD

**Issue by makkawy** [Tautulli/Tautulli#1126]
**i use custom attribute on Recently Added 
تم اضافة 
{title},{episode_name},{season_num},{episode_num},{year}
نوع المحتوى
{genres}
تصنيفه
{content_rating}
تقيمه
{rating}
/settings#notify-text-sub-modal
i used twitter agent for notification 

but i have problem for incomplete metadata info in notification agent
when i add some movies everything will be ok 
but when i add some episode there is some data missing of custom attribute
![image](https://user-images.githubusercontent.com/6168711/31732779-5c111660-b442-11e7-9910-b184408d1704.png)

you can see in image there missing {episode_name},{season_num},{episode_num}
and put for {episode_name} = nothing 
and {season_num} = 0
and {episode_num}= 1
no problem with {year} its ok :D**

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q4
