### ISSUE TITLE
OSX Notify (macOS 10.13) Python Issue

### ISSUE THREAD

**Issue by TechJedi51** [Tautulli/Tautulli#1127]
Version 1.4.25
macOS 10.13

When a OSX Notification is triggered, the Notification is not displayed and the follow message in the Python log is displayed:
`Connection to notification center invalid. ServerConnectionFailure: 1 invalidated: 0`

**Comment by mguterl** [comment]
How are you running PlexPy? Are you running PlexPy as the same user you are signed in as?

**Comment by TechJedi51** [comment]
PlexPy is running on a separate Mac mini. I am accessing it via URL in Firefox.

**Comment by mguterl** [comment]
@TechJedi51 I'm not positive, but I don't think you can do notification center notifications from a remote source.
