### ISSUE TITLE
Sending multiple album notifications to discord even with Global Music Notifications disabled in settings.

### ISSUE THREAD

**Issue by MrsAngelD** [Tautulli/Tautulli#1128]
**Version:**
Version 1.4.25
**Branch:**
master
**Commit hash:**
cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:**
Ubuntu Linux
**Python version:**
2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

**What you did?**
Enabled notifications via slack to post to discord. I disabled the Global music notifications.

**What happened?**
I'm receiving multiple notifications about each album added in discord. Something like 5 notifications per new album.

**What you expected?**
To only receive new movie & tv show notifications in discord.

**How can we reproduce your issue?**
Setup notifications for discord via slack.

**What are your (relevant) settings?**
I disabled Global Music Notifications

**Link to logs:**
https://pastebin.aquilenet.fr/?71202ad7342158d5#u/UMl2z8RyC4N8og4rdq6vs01slaNq3vekzb4h855DE=

**Comment by JonnyWong16** [comment]
Global toggles are only for stream notifications.

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q3

**Comment by MrsAngelD** [comment]
@JonnyWong16 Sorry about that, I don't know how I missed the information. Thank you.
