### ISSUE TITLE
Plex libraries missing

### ISSUE THREAD

**Issue by aporzio1** [Tautulli/Tautulli#1129]
**Version: 1.4.25

**Branch: Master

**Commit hash: cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system: MacOS 10.11

**Python version: 2.7.10

**What you did? Went to look at the history

**What happened? It only shows the history of my movies and the TV show library is mossing from the libraries tab

**What you expected? expected to see history of movies & TV Shows. Refreshing libraries does not make TV Show library show up, also some libraries are duplicated. 

**How can we reproduce your issue?

Unknown

**What are your (relevant) settings?

**Link to logs:
 https://pastebin.com/6m89t9E8

**Comment by JonnyWong16** [comment]
Please read the FAQ.

**Comment by aporzio1** [comment]
I did the delete_duplicate_libraries in the URL, but it did not change anything. I restored a back up to get my TV Show library back, but I still have the issue of duplicate libraries. 

I think that manually deleting them is what caused my issue before.
