### ISSUE TITLE
Support for Multiple Plex Servers / Instances

### ISSUE THREAD

**Issue by zero888** [Tautulli/Tautulli#113]
Is it possible to add support for multiple Plex media servers?

**Comment by drzoidberg33** [comment]
Yes, it's possible I just haven't looked into it with much detail yet.

**Comment by rickcab1** [comment]
+1 this would be awesome as I run 3 right now!

**Comment by Kaylen878** [comment]
First of all, drzoidberg33 - its an amazing app you have made, just what i have looked for!
But when do you expect the support of multiple plex servers will be implemented?

i have 6 plex servers :)

**Comment by TheBlackDrake** [comment]
+1 on this. Would be perfect.
Finally an app that works :D 
I have been using plexdb and the web frontend. But had problems with multiple views on same items.
(like one episode get 50 views from 1 real view)
So great job :D thanks :dancer:

**Comment by cbjerg** [comment]
+1 for this. I have a server for my own family and one I share with friends

**Comment by elRadix** [comment]
I need this as well

I'm running now 2 instances of Plexpy to manage my plex servers.

**Comment by Hellowlol** [comment]
Why does ppl use 2 servers? How many concurrent stream are you guys serving?

**Comment by cbjerg** [comment]
Actually I just setup PlexPy on both servers - no big hassle

**Comment by Vorlonze** [comment]
+1 for me too! 2 servers here as well.

**Comment by BoilerAC** [comment]
+1 YES!!!! That would be amazing!

**Comment by Qosmo** [comment]
This would be awesome!

**Comment by YipYup** [comment]
Adding my vote. Would be a great feature to have.

**Comment by parzival84** [comment]
This would be an amazing feature, I currently have 2 Plex servers: a rented dedicated server and a local server. I am using 2 PlexPy installs currently to get around this which isn't the most convenient.

**Comment by jm-hill** [comment]
+1 from me as well

**Comment by pickthenimp** [comment]
+2 for my 2 severs

**Comment by trendless** [comment]
+vote

Also, thanks for the great app!

**Comment by antoinesylvia** [comment]
+1

**Comment by imperativeoz** [comment]
+1

**Comment by didyouexpectthat** [comment]
This would be highly requested from me (and then the ability to merge two plexpy's together once multiserver support is enabled). have lots of streams and large libraries, thus, multiple servers. One server refreshing just takes too long.

**Comment by Noktam** [comment]
I would like that too.

**Comment by tj1816** [comment]
+1

**Comment by steetiehj** [comment]
+1

**Comment by fliiiix** [comment]
:+1: this would be super awesome

**Comment by lhawkins** [comment]
I'd like this too... I've got a Supermicro server running FreeNAS with one PMS, but the FreeNAS version of Plex doesn't currently support the new music features so I have a separate server dedicated to music. Currently running two instances of PlexPy, but ditching one of them would be nice!

**Comment by SirGigantor** [comment]
+1

**Comment by Keelan** [comment]
Got 3 servers but would settle for monitoring 2 with plexpy.

+1 :)

**Comment by seitzbg** [comment]
+1 for this as well!

**Comment by nicdal** [comment]
+1

**Comment by didyouexpectthat** [comment]
If possible, how long do you think it would take to implement? Anyone tried to do anything related to this? Now the second most commented and opened issue/enhancement on this github :P  Any incentives to get started on this?

**Comment by JonnyWong16** [comment]
Many months. I don't think anyone's looked at it yet. It's definitely not a simple task as this would likely require rewriting _a lot_ of the code.

**Comment by flipdee** [comment]
+1 Yes please

**Comment by Arcanemagus** [comment]
Saying "+1" does nothing but spam notifications and annoy developers. GitHub added reactions _specifically_ for that purpose, so please just give the initial post a :+1: if you are not going to contribute to the discussion.

**Comment by Keelan** [comment]
@arcanemagus actually the developer says to vote over at http://feathub.com/drzoidberg33/plexpy/+14

**Comment by flipdee** [comment]
Apologies, I misunderstood the initial few comments on this thread to be "voting" or I suppose expressing interest in this feature.

**Comment by Arcanemagus** [comment]
@flipdee I wasn't specifically meaning you, this thread just keeps getting spammed with those comments :wink:.

**Comment by flipdee** [comment]
Agreed, I think it stemmed from the plex forum and the horrendous +1 threads on there, but thanks for the heads up on githubs reactions, feathub looks interesting, I suppose if a thread is labelled an enhancement, a little note at the top of the thread explaining how best to express your interest would be useful. It's awful though it seems like everywhere we turn it's becoming more and more like facebook.

**Comment by Keelan** [comment]
I don't even see reactions on mobile so might be a reason. Anyways nice features etc have. I have been wanting this since plexwatcb became a thing. It's great having multiple servers and multiple plexpy buy its a lot nice to have all that data in one place

**Comment by JonnyWong16** [comment]
As mentioned above, please go over and vote on [FeatHub](http://feathub.com/drzoidberg33/plexpy/+14). I'm trying to move everything over there since it has a proper voting system.

**Comment by tcheronneau** [comment]
Hi there,
Just discovered this tool and I find it quite handy !
So thanks for that. 
I've managed to make a "work around" in order to supervise multiple server. 
I use docker container for each server (simple to manage and easy to deploy). 
You just have to download the github project for each instance and I made this simple line to launch an instance : 
docker run -d --name instance1 -v /opt/plexpy1:/plexpy -p 8080:8181 python:2.7 python plexpy/PlexPy.py
and for example another one : 
docker run -d --name instance2 -v /opt/plexpy2:/plexpy -p 8081:8181 python:2.7 python plexpy/PlexPy.py

And a little proxy in front of those containers. 
Hope it will help some !

**Comment by krsandvik** [comment]
+1 on this

**Comment by yoyostile** [comment]
+1 

that'd be great!

**Comment by jemus42** [comment]
I'd just like to chime in and support this request! +1

**Comment by bbashy** [comment]
Just looking into this and thought I'd be able to monitor all my servers but was saddened when I found out I couldn't (apart from installing on each server).

Hope this gets started on soon!

**Comment by Mearman** [comment]
I'd be all over this

**Comment by bbashy** [comment]
Pretty much made me not use it.

**Comment by saitoh183** [comment]
I would like to see this also instead of having to run 3 Plexpy  instances

**Comment by PremiumizeNZB** [comment]
With the introduction of Plex Cloud (and finding out that Plexpy is actually compatible with Plex Cloud) I ran into this exact issue. A VM with only Plexpy on it would be overkill.
So +1 from me as well.

Btw. the FeatHub link shows a "The page you were looking for doesn't exist." error.

Has anyone found a way to run two separate instances of PlexPy on Windows?

**Comment by Hellowlol** [comment]
There are nothing special things to it. Just download the source code edit the config, change to port and python plexpy.py and you good to go.

**Comment by saitoh183** [comment]
@PremiumizeNZB 

How do you currently run it on windows? Is it running as a service? Because the simple way is to duplicate the entire Plexpy folder, Run it, modify the port, and API key and Plex server info. If your running it via nssm, then you can create another one point to the second instance. I have this setup with PlexRequest.Net and it runs great. I also have 2 instances on Nix.

**Comment by JonnyWong16** [comment]
@Hellowlol Any ideas for #853?

Also: 

```
python PlexPy.py -p PORT_NUMBER
```

**Comment by Hellowlol** [comment]
^^

**Comment by PremiumizeNZB** [comment]
@saitoh183 
LMAO. I thought you were joking, I simply duplicated the Plexpy folder, changed the port in the config.ini, put the shortcut of the new PlexPy.py in the Windows Startup folder, ran it, changed the Backup/Cache/Log Directory under Settings/General and it worked.

How to get Plex Cloud working with Plexpy:
- ~~Go under https://plex.tv/users/cpms, look under PMS Links and copy your Plex Instance Link~~
- ~~Go to Plexpy/Settings/Plex Media Server and paste the link to the Hostname (remove the https:// part), choose Port 80, check Remote Server and Use SSL.~~

Worked for me.

**Comment by JonnyWong16** [comment]
Please don't do this. I am working with the Plex people to do this properly. Plex Cloud servers turn off when not in use in order to save resources. If not done correctly it will keep your Plex Cloud server awake because PlexPy is constantly pinging the server.

**Comment by filoor** [comment]
+1

**Comment by TheMNSTR** [comment]
The support for multiple servers is one feature I'm eagerly awaiting :) .
But, to be honest, I think most of PlexPy functionality should've been folder into Plex Server or offered through Plex.tv somehow. It would be much easier and cleaner.

@JonnyWong16 have you thought about that or even tried to bring it up with plex inc?

@PremiumizeNZB - just out of curiosity - did you get get Plex Cloud Server logs to work? If so, how? I'm trying to poke around and test it, but can't figure that part out.

**Comment by tcouture** [comment]
+1

**Comment by YodaSpow** [comment]
+1

**Comment by carlosrovira** [comment]
+1

**Comment by andrewjeffree** [comment]
If people could stop commenting with "+1" to this and instead use the "Thumbs Up" or any of the other relevant reaction icons on the original request it would be much appreciated by many people I'm sure. It reduces the amount of useless notifications anyone who's watching this thread has to get.

**Comment by btmndkh** [comment]
+1

**Comment by n1nj4888** [comment]
+1 and added a thumbs up to the original post...

Given that the user details are shared per Plex.TV login, wouldn't this just be the case of adding the option to add multiple servers in the GUI settings, adding filters for servers for history etc in the GUI and running the same inspection routine for each configured plex server? 

PS: PlexPy is awesome!

**Comment by BermudaLamb** [comment]
Please, please, please ... enable this feature. I would like to know if maintaining my cloud server is worth the effort.

**Comment by jeff15110168** [comment]
Same, would really like to know how my cloud server is being used

**Comment by adambirds** [comment]
@JonnyWong16 how is that 6 years on, this still hasn't been implemented when as far as I can see its the most asked for addition.

**Comment by TheMeanCanEHdian** [comment]
> @JonnyWong16 how is that 6 years on, this still hasn't been implemented when as far as I can see its the most asked for addition.

This software is built entirely for free using personal time outside of normal work. Additionally, this feature requires extensive backend changes and time to do it right.

Please mind your tone.
