### ISSUE TITLE
Set PMS log

### ISSUE THREAD

**Issue by edflips** [Tautulli/Tautulli#1130]
**Version:**
VERSION 1.4.25

**Commit hash:**
`cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca`

**Operating system:**
CONTOS 7

**Python version:**
2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]

**What you did?**
Sorry to open another log location issue, but I can't get PlexPy to recognise the path to the Plex log directory. I'm running both PlexPy and PMS in Docker containers, but my paths are correct, so I'm not sure whats going on.

I have tried both escaped and non-escaped paths, but neither work.

*Setting an unescaped path:*
`/home/docker/plex/library/Library/Application Support/Plex Media Server/Logs/`

PlexPy log reports:
`Unable to open Plex Log file. [Errno 2] No such file or directory: '/home/docker/plex/library/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log'`

*Setting an escaped path:*
`/home/docker/plex/library/Library/Application\ Support/Plex\ Media\ Server/Logs/`

PlexPy log reports:
`Unable to open Plex Log file. [Errno 2] No such file or directory: '/home/docker/plex/library/Library/Application\\ Support/Plex\\ Media\\ Server/Logs/Plex Media Server.log'`

It looks like PlexPy is escaping the escape characters in the latter example, which leads me to believe the non-escaped path is what its after. Am I doing anything specifically wrong here?

Just to confirm that doing `cat /home/docker/plex/library/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Media\ Server.log` displays the log, so it is at this location.

**Link to logs:**
https://pastebin.com/mPt2F5ba

Thanks!

**Comment by JonnyWong16** [comment]
A docker container does not have access to files outside the container (that's the whole point of docker).

You need to mount/share the paths between containers.

You don't need to escape the path.

**Comment by edflips** [comment]
Gah, yes, of course. Thanks for taking the time to set me straight!
