### ISSUE TITLE
Recently Added history length !> 100

### ISSUE THREAD

**Issue by c01000100** [Tautulli/Tautulli#1131]
This is not an error, but rather a programming/coding choice I'm sure.  I recently added more than 100 titles to a single Plex library.  The recently added content list only seems to be returning 100 results via the API method get_recently_added.  Is there a way to get more than 100 entries?  Are they trimmed from the PlexPy DB at length 100?  Can I bump that to 500?  If so, where?  I understand that was probably limited for performance reasons, but I'm willing to take the risk.

**Comment by JonnyWong16** [comment]
It's limited to 100 on the Plex API. This is not a PlexPy limitation.

**Comment by c01000100** [comment]
Thanks for the speedy response.  Love the PlexPy product!

**Comment by c01000100** [comment]
I'm looking now at the PlexPy user interface, and see that the 9 seasons of "night court" added 5 days ago is collapsed down to seasons.  If listed individually the total for night court alone would be 192 episodes.  Is PlexPy keeping a separate database for recently added?  If not, is it possible to return a similar result from Plex using the PlexPy API?

**Comment by JonnyWong16** [comment]
It's collapsed down because that's how the Plex API returns the data. It's the same as your Plex dashboard. PlexPy does not grab one item at a time and then collapse them down.

**Comment by c01000100** [comment]
Not for the sake of being contrary, but there is a difference. I'm just
having troubles identifying what exactly it is. Now that recently added for
that series is 6 days old and some new content is added, PlexPy shows just
season 9 collapsed and nothing after it while Plex  shows the whole series
collapsed with a couple other shows after it.  The API is returning some of
season 8 and 9. I need to debug to see if the script performing the api
call is doing the expanding for me. I prefer collapsed down to series every
time.

**Comment by JonnyWong16** [comment]
PlexPy is using the old API call from Plex Web 2.0.

**Comment by c01000100** [comment]
Ah.  Makes sense.  Any chance for an update in the near future?  Also, any plans for Trakt and IMDb lookup support?
