### ISSUE TITLE
recently added notifications being sent twice. 

### ISSUE THREAD

**Issue by dejected1** [Tautulli/Tautulli#1132]
**Version:**
VERSION 1.4.25

**Branch:**
Master

**Commit hash:**
cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
--

**Operating system:**
windows 10 x64

**Python version:**
2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]

**What you did?**
Restarted server and services. No change. 

**What happened?**
When the recently added notification is triggered and sent through pushbullet, two notifications are sent. this started happening at 10-27. Confirmed test message from pushbullet settings only sends one notification. This happens on tv and movies. was not happening prior to 10-27. 

**What you expected?**
for it to send 1 notification

**How can we reproduce your issue?**
setup pushbullet, have it notify on recently added. I get two as of 10-27. All pushbullet notifications prior to 10-27 worked fine. no settings were changed. Haven't touched notifications settings in weeks. 

**What are your (relevant) settings?**

**Link to logs:**

[plexpy.log](https://github.com/JonnyWong16/plexpy/files/1427984/plexpy.log)
![image](https://user-images.githubusercontent.com/26720061/32183717-48704216-bd57-11e7-96e0-9ed7e3e17f03.JPG)

**Comment by JonnyWong16** [comment]
You somehow have two instances of PlexPy running on top of each other.

**Comment by dejected1** [comment]
hmmm. i setup email notifications along side pushbullet, i only got one email notify. i restarted server again and I manually ended all python instances and started plexpy manually. This time it only sent one alert. So you were right, im just not sure why its starting two instances on server reboot. Well thats my problem not yours. thanks.
