### ISSUE TITLE
Unable to Update - No Version info

### ISSUE THREAD

**Issue by phoniclynx** [Tautulli/Tautulli#1134]
I am unable to update the version of PlexPy because it's reporting that it doesn't know what current version it is running. Every time I restart the app it reports the same issue. I have given it a GitHub API key and asked it to update a few times and each time get the same result.

It is running on a Synology DSM 6.x system which is the same system that is running Plex 

LOGS: https://pastebin.com/Wr9LjnBm

**Comment by MikeDawg** [comment]
Is https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#windows-q2 pertinent?

**Comment by phoniclynx** [comment]
I'm using this on a Synology.. not on a Windows Environment... It was installed using the SonoCommunity repo's

**Comment by JonnyWong16** [comment]
Looks like an issue with the Synology package. It doesn't have git included. You will have to go to the package maintainer to get them to fix it.

**Comment by phoniclynx** [comment]
Why close it straight away without giving me a chance to respond?? lol

Yes, it DOES have GIT and yes GIT DOES work for other applications.. just
not this one.

**Comment by JonnyWong16** [comment]
```
2017-10-31 13:35:56 - DEBUG   :: MainThread : Git output: /bin/sh: git: command not found
```

Git in other packages doesn't mean git is inside the PlexPy package.

**Comment by phoniclynx** [comment]
Git is installed on the Synology and is accessible to any other applications on the Synology. it's still in /volume1/@appstore/git/bin  and any program should be able to execute it and read data from it.

**Comment by JonnyWong16** [comment]
Set the `git_path` inside the config.ini file.

**Comment by phoniclynx** [comment]
Yeah.. I changed that and it made no difference

**Comment by JonnyWong16** [comment]
PlexPy must be shut down when changing the config file.

**Comment by phoniclynx** [comment]
I see this in the logs:

```
> 2017-11-30 22:45:52 | ERROR | Could not retrieve branch name from git. Falling back to master
> -- | -- | --
> 2017-11-30 22:45:52 | DEBUG | Unable to find git with command git rev-parse --abbrev-ref HEAD
> 2017-11-30 22:45:52 | DEBUG | Git output: /bin/sh: git: command not found
> 2017-11-30 22:45:52 | DEBUG | Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /volume1/@appstore/plexpy-custom/var/plexpy
```

I have also put this in the /root/,profile file:
```
PATH=$PATH:/volume1/@appstore/git/bin
export PATH
```

**Comment by phoniclynx** [comment]
Ahh.. fixed it... the config needed to be the path to the actual executable... not just the path
