### ISSUE TITLE
Script is not activating by itself

### ISSUE THREAD

**Issue by markisoke** [Tautulli/Tautulli#1137]
**Reporting Issues:**
I try to setup to kill the paused transcoding streams via a script that works when I test the script, but won't fire automaticly.

**Version:** 1.4.25

**Branch:** master

**Commit hash:** cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:** Ubuntu 16.04

**Python version:** 2.7.12

**What you did?** Tried to setup the following script: https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_trans_pause.py

**What happened?** When I test the script everything works as shown below:

![screenshot-plexpy xena link-2017-11-01-15-06-53-247](https://user-images.githubusercontent.com/12715660/32278819-2ac5a082-bf17-11e7-98d7-6388d3aae855.png)
![screenshot-plexpy xena link-2017-11-01-15-07-45-709](https://user-images.githubusercontent.com/12715660/32278823-2c2a3370-bf17-11e7-9276-7818bdd4ee5f.png)

**What you expected?** For it to work automatically when someone pauses a stream, it doesn't do that at the moment.

**How can we reproduce your issue?**
I have no clue

**What are your (relevant) settings?**

**Link to logs:**
[plexpy.log](https://github.com/JonnyWong16/plexpy/files/1434382/plexpy.log)
[Plex Media Server.log](https://github.com/JonnyWong16/plexpy/files/1434383/Plex.Media.Server.log)

**Comment by blacktwin** [comment]
Do you have these settings set?

```
PlexPy > Settings > Notification Agents > Scripts > Bell icon:
        [X] Notify on playback start
PlexPy > Settings > Notification Agents > Scripts > Gear icon:
        Playback Start: kill_trans_pause.py
PlexPy > Settings > Notifications > Script > Script Arguments:
        {session_key}
```

**Comment by markisoke** [comment]
I didn't have these 3, for the first 2 I only had playback pause since I thought that was the only one necessary. I now have those 3 enabled, but still nothing.

![screenshot-plexpy xena link-2017-11-01-15-31-15-142](https://user-images.githubusercontent.com/12715660/32279664-b834e106-bf19-11e7-8a31-2cb0a061a831.png)
![screenshot-plexpy xena link-2017-11-01-15-31-42-411](https://user-images.githubusercontent.com/12715660/32279689-c7e9ca12-bf19-11e7-954b-8dc598fb1f7c.png)
![screenshot-plexpy xena link-2017-11-01-15-32-13-862](https://user-images.githubusercontent.com/12715660/32279717-d806e7b8-bf19-11e7-93d6-281480820ad8.png)
![screenshot-plexpy xena link-2017-11-01-15-32-42-957](https://user-images.githubusercontent.com/12715660/32279759-e979cede-bf19-11e7-88e9-79d27357271b.png)
![screenshot-plexpy xena link-2017-11-01-15-34-52-520](https://user-images.githubusercontent.com/12715660/32279883-37cc3c98-bf1a-11e7-9c6b-a5fed81793a1.png)

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q1

**Comment by markisoke** [comment]
I've done all of that, as seen in the screenshots.

**Comment by JonnyWong16** [comment]
No you haven't. I can see it in your first screenshot.

**Comment by markisoke** [comment]
Stupid me, I know see what you mean :(
