### ISSUE TITLE
When selecting a Movie, the following error is shown on the screen.

### ISSUE THREAD

**Issue by zenjabba** [Tautulli/Tautulli#114]
Clicking OK lets it continue, but it looks like an AJAX error is occuring.

<img width="1807" alt="screenshot 2015-08-22 21 54 53" src="https://cloud.githubusercontent.com/assets/679864/9426550/a2036bd8-4918-11e5-8430-b183b3104e57.png">

**Comment by JonnyWong16** [comment]
Try clearing your browser cache / force refresh, and also clicking on one of the table headers.

**Comment by zenjabba** [comment]
Fixed
