### ISSUE TITLE
get_recently_added returns null

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#1140]
**Version:** 1.4.25

**Branch:** master

**Commit hash:** cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:** Debian 8 amd64

**Python version:** 2.7.9

**What you did?** Called the API using php to get the recently added media.

**What happened?** API returns null

**What you expected?** Getting the recently added media, not null ^^

**How can we reproduce your issue?**

Issue happens when trying to get the response. Well, actually you get a response, but it doesn't provide the requested content. `get_activity`, for example, returns the expected response. `get_recently_added` doesn't.

PHP code:
```
<?php
$apikey = '*********';
$apicmd = 'get_recently_added';
$apiurl = 'http://***********************.*****:****/api/v2?apikey=' . $apikey . '&cmd=' . $apicmd;
$response = file_get_contents($apiurl);
echo $response;
?>
```

response:
```
{"response": {"message": null, "data": {"recently_added": []}, "result": "success"}}
```

**What are your (relevant) settings?**

API is enabled
PlexPy is running on a public domain
PlexPy is running on the same machine as Plex, but not on the machine im running the above PHP file from

**Link to logs:**
Only 2 lines in the log:
```
2017-11-08 14:32:45 - DEBUG   :: CP Server Thread-7 : PlexPy APIv2 :: API called with kwargs: {'cmd': u'get_recently_added', 'apikey': u'********8b'}
2017-11-08 14:32:45 - DEBUG   :: CP Server Thread-7 : PlexPy APIv2 :: Cleaned kwargs: {}
```

**Comment by JonnyWong16** [comment]
`count` is a required parameter. 

https://github.com/JonnyWong16/plexpy/blob/master/API.md#get_recently_added

**Comment by ghost** [comment]
Now I feel dumb. Thanks, its working.
