### ISSUE TITLE
pyOpenSSL "ConnectionType" deprecation warning

### ISSUE THREAD

**Issue by westerterp** [Tautulli/Tautulli#1142]
**Version:**
1.4.25

**Branch:**
master

**Commit hash:**
cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:**
Windows Server 2016

**Python version:**
Python 2.7.14

**Problem:**
I wanted to enable SSL, so I did and got an error (can't recall the exact error) about not having OpenSSL available.
So I installed pyOpenSSL with pip. This worked fine.

But now my console window of PlexPy is getting the following warning:
`C:\Program Files (x86)\plexpy-1.4.22\lib/cherrypy\wsgiserver\ssl_pyopenssl.py:247: DeprecationWarning: ConnectionType has been deprecated, use Connection instead  if SSL and isinstance(sock, SSL.ConnectionType):`

Is that someting you can fix?
Thanks in advance!

**Comment by JonnyWong16** [comment]
Note to self: cherrypy requires an update.

**Comment by sido86** [comment]
hi Jonny, 

can you please remove me from youre email list. 

Sirwan Palani

________________________________________
Fra: JonnyWong16 <notifications@github.com>
Sendt: 16. november 2017 20:31
Til: JonnyWong16/plexpy
Cc: Subscribed
Emne: Re: [JonnyWong16/plexpy] pyOpenSSL "ConnectionType" deprecation warning (#1142)

Note to self: cherrypy requires an update.

**Comment by JonnyWong16** [comment]
Fixed with #1181.
