### ISSUE TITLE
[Feature Request] New 'weekday' Tag for the notifications.

### ISSUE THREAD

**Issue by prinzpi** [Tautulli/Tautulli#1143]
I would love to have a "weekday" Tag inside the PlexPy Notifications.

For example, when a new movie was added it looks like this at the moment:
```

NEW Stuff ♥
<movie>🎥 {title} ({year}) was added!

🕑 Dauer: {duration} min.

💯 Note: {rating}/10

📹 Studio: {studio}

🎯 Genre: {genres}
```

I would like to use it like this:

```
New Stuff for Saturday ♥
<movie>🎥 {title} ({year}) was added!

🕑 Dauer: {duration} min.

💯 Note: {rating}/10

📹 Studio: {studio}

🎯 Genre: {genres}
```

Saturday ofc perhaps which weekday is today. 
Thanks.

**Comment by JonnyWong16** [comment]
You can add the weekday to your Date Format, then use the `{datestamp}` option.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests
