### ISSUE TITLE
There was an error communicating with your Plex Server.

### ISSUE THREAD

**Issue by fazools** [Tautulli/Tautulli#1144]
**Version:**1.4.25

**Branch:**Master

**Commit hash:**cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:**Windows 10 Pro 64bit

**Python version:**2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]

**What you did?**Started PlexPy

**What happened?**It showed me an error on the homepage.

**What you expected?** For it to connect to Plex

**How can we reproduce your issue?** Wish I knew! 

**What are your (relevant) settings?**All default

**Link to logs:**
[plexpy.log](https://github.com/JonnyWong16/plexpy/files/1464747/plexpy.log)

Everything was working one day, the next it stopped. At this point it's been down for a few months due to my work travel and lack of time to sit and troubleshoot. I am sure there have been some windows updates and Plex updates since and maybe before but not sure where to begin. I have read other posts here with the same issue but have not been able to get mine going.

**Comment by NewAccountWhoDis** [comment]
I had a similar issue and have been going through different threads. What worked for me I stumbled on, basically having PlexPy re-authenticate to my server. 

SETTINGS > PLEX.TV ACCOUNT > PMS TOKEN >FETCH TOKEN

I confirmed my admin user id and password, restarted PlexPy and all is good. 

Hope that helps.

**Comment by fazools** [comment]
That fixed it! Thanks!!

**Comment by JonnyWong16** [comment]
I just saw this. This is answered in the FAQ.

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q16
