### ISSUE TITLE
Watched Notifications no longer working.

### ISSUE THREAD

**Issue by sbcrumb** [Tautulli/Tautulli#1145]
**Version:**
VERSION 1.4.25
**Branch:**
Master
**Commit hash:**

**Operating system:**
Ubuntu 16.04
**Python version:**
2.7.12
**What you did?**
Nothing but update
**What happened?**
Notifications for Watched no longer work
**What you expected?**
it to work like it did.
![capture](https://user-images.githubusercontent.com/5639759/32859767-7196f00e-ca1d-11e7-9648-90a4d2a957f2.JPG)

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
You're going to have to provide a lot more info than that. Have you checked the FAQ for notifications?

**Comment by sbcrumb** [comment]
What else do you need? This worked then stopped on an update.  I don't even have the option to tell it to notify me after x %.
Uncaught exception: Traceback (most recent call last):
    File "/opt/plexpy/plexpy/logger.py", line 270, in new_run 
        old_run(*args, **kwargs) 
    File "/usr/lib/python2.7/threading.py", line 754, in run 
        self.__target(*self.__args, **self.__kwargs) 
    File "/opt/plexpy/plexpy/notification_handler.py", line 75, in notify 
        metadata=metadata) 
    File "/opt/plexpy/plexpy/notification_handler.py", line 534, in set_notify_state 
        monitor_db.upsert(table_name='notify_log', key_dict=keys, value_dict=values) 
    File "/opt/plexpy/plexpy/database.py", line 191, in upsert 
        self.action(update_query, value_dict.values() + key_dict.values()) 
    File "/opt/plexpy/plexpy/database.py", line 144, in action 
        sql_result = c.execute(query, args) 
DatabaseError: database disk image is malformed 

I noticed this in the logs just now. I also have not been getting watched notifications since Nov 7th.

I ran a database repair after seeing this and now notifications are coming in. So I will call it fixed. I don't have the option to change the percent like I used to but in the .ini file only.

**Comment by JonnyWong16** [comment]
Watched percentage is under "General".

**Comment by sbcrumb** [comment]
Your right my bad. Sorry about that. And the confusion.
