### ISSUE TITLE
Log entries are not escaped/sanitized (Token visible/Page Redirects)

### ISSUE THREAD

**Issue by Nostang3** [Tautulli/Tautulli#1146]
**Plex API Version:** 3.0.3
**Operating system:** FreeNAS | FreeNAS-9.10.2-U6 (561f0d7a1)
**Python version:** 2.7.13

**What you did?:** Attempted to run ip_whitelist.py when playback starts via scripts. 

**What happened?:** The script erred out most likely because my Plex Token had changed since I last attempted to use the script. This caused an error to post to the PlexPy logs that was not properly escaped and would cause redirects anytime the error was visible on the log page. You'd have to wait till enough entries pushed it off to a following page before you could access the log page again. Also, the Plex Token was visible in this error code. 

**How can we reproduce your issue?:** I believe you would just need to run the script with a bad plex token value. 

**Link to logs:** https://pastebin.com/xm3Z1825
The error will be at the bottom.

**Comment by Hellowlol** [comment]
I meant on the plexapi repo :)

**Comment by JonnyWong16** [comment]
This should still be filed here as it is a security bug in PlexPy.

**Comment by Hellowlol** [comment]
It will be impossible to cover all the edge cases in plexpy. Anything can go wrong in the script leaking info. :(

**Comment by Nostang3** [comment]
Posted in plexapi.

**Comment by JonnyWong16** [comment]
Script output sanitized in 79581fb
