### ISSUE TITLE
Reverse Proxy Issues in PlexPy V2

### ISSUE THREAD

**Issue by MaartenMol** [Tautulli/Tautulli#1147]
**Version:**
Commit:  1235f73
**Branch:**
V2
**Commit hash:**
1235f73
**Operating system:**
Windows Server 2016 Latest Updates
**Python version:**
2.7
**What you did?**
When I have setup reverse proxy on IIS it normally worked when on the master branch. No issues. However now I have V2 installed and i came accross an issue. Only when accessing by the reverse proxy not when access by direct ip + port.
**What happened?**
When PlexPy wants to show the current stream, it shows continues error from IIS that the resource is not available. (No issues when accessing by local ip + port without reverse proxy) See the following image:
![](https://img.familie-mol.nl/2b0f00cf.png)
**What you expected?**
That it worked like the master branch or by accessing local ip. However it doesn't work like it supposed to be.
**How can we reproduce your issue?**
I can make screenshots of my setup if needed.

**What are your (relevant) settings?**
All settings are the same as an installation from the master branch.
**Link to logs:**

**Comment by JonnyWong16** [comment]
Noted, but v2 is unsupported right now.

**Comment by MaartenMol** [comment]
@JonnyWong16 I know I just wanted to let you know ;)

However, is this something you will fix in the near future?
