### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by AcidRain999** [Tautulli/Tautulli#1148]
using v2, whenever i start it, it gives me 500 internal server error right after loading. although it does seem to running and giving feedback in the console window i cant browse to the website it is running

it is running on debian, brand new download from this website and it still fails
tried it on python 2 and python 3

**Comment by JonnyWong16** [comment]
Noted, but v2 is unsupported right now.

**Comment by vertigo235** [comment]
Install git and v2 will be able to identify the branch you are on. The issue is due to a string join on a variable with a None value due to not knowing what version you are running.
