### ISSUE TITLE
PlexPy no more avalaible on Web interface !

### ISSUE THREAD

**Issue by vincegre** [Tautulli/Tautulli#1154]
**Version:** updated to github latest version but problem appeared with previous version I guess

**Operating system:** Ubuntu 16.04.2

**Python version:** 3.5

**What you did?** nothing I noticed one day that I could no more access web interface of PlexPy but could not ! I restarted Plexpy service but not better ! I then updated PlexPy from github (as I did multiple times in past but not much result !
I include logs that show Plexpy unable to retrieve lists of libs from my PMS :(

**Link to logs:**

> root@serveur:/opt/plexpy/logs# more plexpy.log 
> 2017-11-22 13:56:16 - INFO    :: MainThread : Checking to see if the database has all tables....
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Git output: cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/plexpy
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Git output: master
> 2017-11-22 13:56:16 - INFO    :: MainThread : Retrieving latest version information from GitHub
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
> 2017-11-22 13:56:21 - DEBUG   :: MainThread : Latest version is cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
> 2017-11-22 13:56:21 - INFO    :: MainThread : PlexPy is up to date
> 2017-11-22 13:56:21 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
> 2017-11-22 13:56:21 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
> 2017-11-22 13:56:22 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
> 2017-11-22 13:56:22 - INFO    :: MainThread : PlexPy PlexTV :: Server URL retrieved.
> 2017-11-22 13:56:22 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
> 2017-11-22 13:56:23 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
> 2017-11-22 13:56:24 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
> 2017-11-22 13:56:24 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
> root@serveur:/opt/plexpy/logs# more plexpy.log 
> 2017-11-22 13:56:16 - INFO    :: MainThread : Checking to see if the database has all tables....
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Git output: cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/plexpy
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Git output: master
> 2017-11-22 13:56:16 - INFO    :: MainThread : Retrieving latest version information from GitHub
> 2017-11-22 13:56:16 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
> 2017-11-22 13:56:21 - DEBUG   :: MainThread : Latest version is cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
> 2017-11-22 13:56:21 - INFO    :: MainThread : PlexPy is up to date
> 2017-11-22 13:56:21 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
> 2017-11-22 13:56:21 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
> 2017-11-22 13:56:22 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
> 2017-11-22 13:56:22 - INFO    :: MainThread : PlexPy PlexTV :: Server URL retrieved.
> 2017-11-22 13:56:22 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
> 2017-11-22 13:56:23 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
> 2017-11-22 13:56:24 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
> 2017-11-22 13:56:24 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
> 2017-11-22 13:56:33 - DEBUG   :: MainThread : PlexPy Pmsconnect :: No library data.
> 2017-11-22 13:56:34 - DEBUG   :: MainThread : PlexPy Pmsconnect :: No library data.
> 2017-11-22 13:56:35 - DEBUG   :: MainThread : PlexPy Pmsconnect :: No library data.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q1

**Comment by JonnyWong16** [comment]
No response.
