### ISSUE TITLE
PlexPy Facebook Notifications

### ISSUE THREAD

**Issue by Comfubar** [Tautulli/Tautulli#1158]
**Version:**
Version 1.4.25
**Branch:**
master
**Commit hash:**
 	cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
**Operating system:**
Windows 10
**Python version:**
2.7
**What you did?**

**What happened?**
Upon setting Up Facebook integration with PLEXPY. Plexpy puts movie and tv show update photos as the TVDB screen shot or no screen shot at all  
**What you expected?**
PLEXPY to put in FB group the TVshow screenshot or Movie screenshot
**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
https://nofile.io/f/cNJ3F5vgnEP/PLEXPYLOG

**ScreenShot of Issue**
https://imgur.com/a/W6NXx

**Comment by JonnyWong16** [comment]
Duplicate #1063.
