### ISSUE TITLE
Plexpy  Links to incorrect metadata after rebuilding media.

### ISSUE THREAD

**Issue by Madbeefer** [Tautulli/Tautulli#1161]
**Version:**
1.4.25
**Branch:**
master
**Commit hash:**

**Operating system:**
QNAP
**Python version:**

**What you did?**
I had to rebuild all my data on my NAS, I was able to safe the majority of the data and put it back and reformat.
**What happened?**
Plexpy links the mostly the correct files, there are some that its not even close on. 
**What you expected?**
Someway to rebuild the links between what was watched and the correct media.
**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
![capture](https://user-images.githubusercontent.com/34440759/33826261-3ce4efae-de19-11e7-836c-13c05839ae7b.JPG)

**Comment by blacktwin** [comment]
You can try this [script](https://gist.github.com/JonnyWong16/f554f407832076919dc6864a78432db2). `Updates all metadata in the PlexPy database after moving Plex libraries.`

**Comment by Madbeefer** [comment]
I tried that, and I am sure I am doing something incorrectly, but I got "ImportError: No module named plexapi.server" and nothing happened.

**Comment by JonnyWong16** [comment]
The script requires `requests` and the `python-plexapi` (as stated at the top of the script).

Run
```
pip install requests
pip install git+https://github.com/pkkid/python-plexapi.git
```

**Comment by Madbeefer** [comment]
I have installed python on my QNAP but I am not able to get the pip command to function, I am fairly new to doing much in this environment.

**Comment by JonnyWong16** [comment]
That I don't know. Google is probably your friend here.

**Comment by Hellowlol** [comment]
I’ll update the script a bit later .guid requires a reload of objects so this should happen in a thread pool
