### ISSUE TITLE
Daemon setup on Mac OS X 10.13.2

### ISSUE THREAD

**Issue by alfgut** [Tautulli/Tautulli#1163]
Hi there,

I was smoothly running PlexPy as a daemon until I updated to High Sierra. Since then, I am struggling to get it again loading up with the system.

Here the content of my .plist file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>plexpy</string>
  <key>ProgramArguments</key>
  <array>
       <!-- Modify these two lines if you need to to reflect your python location and PlexPy install location -->
       <string>/usr/bin/python</string>
       <string>/Applications/PlexPy/PlexPy.py</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
```

All the commands to copy the list and loading and unloading seem to work fine:

> cp /Applications/PlexPy/init-scripts/init.osx ~/Library/LaunchAgents/com.JonnyWong16.plexpy.plist

> launchctl load ~/Library/LaunchAgents/com.JonnyWong16.plexpy.plist

Then I try to load localhost:8181 in Safari with no success (in fact normally it opens automatically when I use "python PlexPy.py &"). If I repeat the same command the system states that the service is already running, but it does not work so, can you help me?

I don't know if this may be important, but whenever I try to update PlexPy I am getting this message in the terminal:

> 2017-12-14 10:15:46 - ERROR :: CP Server Thread-6 : Request raise HTTP error with status code 403 (local client error).
> 2017-12-14 10:15:46 - DEBUG :: CP Server Thread-6 : Server responded with message: {"message":"API rate limit exceeded for 88.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docume...
> 2017-12-14 10:15:46 - WARNING :: CP Server Thread-6 : Could not get the latest version from GitHub. Are you running a local development version?

Please request any information you may need.

**Version:** 1.4.25

**Branch:** master

**Commit hash:** cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:** Mac OS X 10.13.2

**Python version:** 2.7.10

**What you did?**

**What happened?**

**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
Have you tried deleting the .plist file and following the steps again?

**Comment by alfgut** [comment]
Yes, several times, with no success.

**Comment by alfgut** [comment]
Update, I have checked in /var/log/system.log and I find several:

com.apple.xpc.launchd[1] (plexpy[74193]): Service exited with abnormal code: 1
com.apple.xpc.launchd[1] (plexpy): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.

Any ideas?

**Comment by JonnyWong16** [comment]
No idea. I don't use a Mac.

**Comment by mguterl** [comment]
You can modify the plist file to log more information from PlexPy.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>plexpy</string>
  <key>ProgramArguments</key>
  <array>
       <!-- Modify these two lines if you need to to reflect your python location and PlexPy install location -->
       <string>/usr/bin/python</string>
       <string>/Applications/PlexPy/PlexPy.py</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <!-- LOGGING BELOW -->
  <key>StandardOutPath</key>
  <string>/usr/local/var/log/plexpy.log</string>
  <key>StandardErrorPath</key>
  <string>/usr/local/var/log/plexpy.error.log</string>
</dict>
</plist>
```

Note the StandardOutPath and StandardErrorPath need to be in a location that is writable by your user account. `sudo chown -R $(whoami) /usr/local/*` and make sure that /usr/local/var/log exists: `mkdir -p /usr/local/var/log`.

You should then be able to get more information from PlexPy as it tries to startup by running: 
`tail -f /usr/local/var/log/plexpy.log /usr/local/var/log/plexpy.error.log`
