### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by majorpdd** [Tautulli/Tautulli#1168]
**Version:**
v2.0.0-beta
**Branch:**
v2 Tautulli
**Commit hash:**
Not Sure
**Operating system:**
Windows 10
**Python version:**
2.7.14
**What you did?**
Started a new server
**What happened?**
Redirected to http://localhost:8181/welcome, then error occurred.
**What you expected?**
Welcome config page like with master branch.
**How can we reproduce your issue?**

Fetch new Branch, and run.
**What are your (relevant) settings?**
New Config
**Link to logs:**
No Availavble

**Comment by JonnyWong16** [comment]
Beta requires git.

**Comment by ofurpesi** [comment]
All fixed :) git it running using GIT.
