### ISSUE TITLE
Stream info popup in History->Player doesn't reflect the right file when more than 1 version exists for the same movie

### ISSUE THREAD

**Issue by Macie73** [Tautulli/Tautulli#1169]
**Version:**
1.4.25
**Branch:**
master
**Commit hash:**
cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
**Operating system:**
Darwin 16.7.0 (MacOS 10.12.6)
**Python version:**
2.7.10
**What you did?**
i have been collecting uncompressed versions of all the movies i own in MKV format. i started out with DVDs now i've added all the Bluray discs as well. For those for which i have both a DVD (720x576 PAL) and a BD (1920x1080) version, i collapse them into one library item in Plex, to keep the library nice and tidy.
when i play such a movie for which i have multiple versions i notice that the 'Activity' section on the homescreen displays the proper version (video and audio streams) but the History and movie- and user-stats do not.
**What happened?**
the History, Movie stats and users stats, don't show the correct version of the movie (so basically which file) that was actually played. it's as if the PlexPy sticks the activity in history to the first version (file) of the library item (in this case a movie) that was added to the library.
i've seen this happen with 1080p MKV, which i had transcoded to 720p MP4, but both files still in the library stacked as 1 library item. When the later file was streamed the current activity showed that the mp4 version was streamed, while the history shows asif the 1080p MKV was transcoded.
**What you expected?**
i would like to be able to see in the History and everything that is built on that, the streaming/direct play that actually happened.
This only applies when you stack different versions (resolution, containers) of the same movie into 1 library item.
**How can we reproduce your issue?**

see above
**What are your (relevant) settings?**
don't think there are any relevant settings to reproduce this, you just need to stack the versions of the same movie into 1 library item and then play the last version you added. Compare the actual activity when watching with the history item after the activity stopped.
**Link to logs:**

thanks.

**Comment by JonnyWong16** [comment]
PlexPy v1 only grabs the details for the first file it finds. This was limitation of the old Plex server API. Tautulli v2 will show the correct file.
