### ISSUE TITLE
History : Database error: ambiguous column name: id

### ISSUE THREAD

**Issue by novakin** [Tautulli/Tautulli#117]
Hi,

Since last update to Version 1.1.3, history is broken

Following error in log Database error: ambiguous column name: id

**Comment by elRadix** [comment]
I also got this error in the log file for the same version 1.1.3

Uncaught exception: Traceback (most recent call last):
File "/opt/plexpy/plexpy/logger.py", line 210, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/plexpy/plexpy/notification_handler.py", line 101, in notify
notify_strings = build_notify_text(session=stream_data, state=notify_action)
File "/opt/plexpy/plexpy/notification_handler.py", line 303, in build_notify_text
stream_duration = 0 if state == 'play' else int((time.time() - helpers.cast_to_float(session['started']) - helpers.cast_to_float(session['paused_counter'])) / 60)
File "/opt/plexpy/plexpy/helpers.py", line 338, in cast_to_float
return float(s)
TypeError: float() argument must be a string or a number

**Comment by drzoidberg33** [comment]
@novakin See here: https://github.com/drzoidberg33/plexpy/issues/109

@elRadix This issue is unrelated, there is a fix for this in the dev branch already - will be pushed live soon.

**Comment by novakin** [comment]
@drzoidberg33 Thank you !
