### ISSUE TITLE
Websocket errors on tautulli

### ISSUE THREAD

**Issue by Comfubar** [Tautulli/Tautulli#1170]
After installing Tautulli I have everything set up i went to try the https feature for using it with myip and the app

I activated https then I got this issue

2017-12-19 14:50:59 - INFO :: Thread-15 : Tautulli Monitor :: Attempting to reconnect Plex server...
2017-12-19 14:50:59 - DEBUG :: Thread-15 : Tautulli Monitor :: Checking for active streams.
2017-12-19 14:50:59 - WARNING :: Thread-15 : Websocket :: Unable to open connection.

Then I could not reconnect to Tautulli what so ever so I stopped it went into the configuration file zeroed put https so it would turn off and I'm still getting those errors what might be causing it??

Other than that error it seems to run fine but I don't want the error to keep building

Thanks for all you do with this :)

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/blob/master/README.md#issues

**Comment by Comfubar** [comment]
Sorry Jonny was doing this from mobile I'll fix it tonight after work and edit my post

**Comment by Comfubar** [comment]
Version Newest 
Branch master
Commit hash cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
Operating system Windows 10 
Python version 2.7
What you did? enabled https
What happened? couldnt connect / stopped Tautulli and disabled https through config
What you expected? HTTPs to allow me connect and work
How can we reproduce your issue? enabling HTTPS on Tautulli 
What are your (relevant) settings?

https://pastebin.com/Sny8PST3

**Comment by JonnyWong16** [comment]
That is not a valid version number, branch, and commit hash. Tautulli is only available on the beta branch. Please provide correct info.

**Comment by Comfubar** [comment]
here is a screenshot of what is states on my help & info page 
https://i.imgur.com/Y7DohUI.png

if i need to reinstall entirely what can i transfer from my plexpy to Tautulli for easier installation

**Comment by JonnyWong16** [comment]
It's definitely not installed correctly. Check the FAQ for instructions.

**Comment by Comfubar** [comment]
and if i reinstall entirely it gets up to starting Tautulli web server and i get a 500 Internal Server Error if i try to do so 

I unblock like I had to with plexpy and all as well same does occur im gonna restart my servewr now to see if same happens

**Comment by JonnyWong16** [comment]
The beta requires git.

**Comment by Comfubar** [comment]
im using https://github.com/JonnyWong16/plexpy to git correct

**Comment by JonnyWong16** [comment]
The point of the beta is to spend my time fixing bugs. I'm spending too much time providing support to install the beta. I'm closing this issue.
