### ISSUE TITLE
Tautulli keep rolling error in console

### ISSUE THREAD

**Issue by halali** [Tautulli/Tautulli#1172]
Hi

my isse is that in console keep rolling this error
```
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file web_socket.py, line 179
```
**Version:**
V2.0.1-BETA

**Branch:**
Beta

**Commit hash:**
38ad9c9893f3c1720777aae7727f0ec6ec54e0c5

**Operating system:**
Windows 10

**Python version:**
2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]

**What you did?**
Just run Tautulli and after few hours or days it start rolling error in console, in logs there is no error

**What happened?**

**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
[plexpy.log](https://github.com/JonnyWong16/plexpy/files/1574533/plexpy.log)

**Comment by JonnyWong16** [comment]
I'm not downloading a log file.

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q14

But if sounds like you installed Tautulli in a folder where it doesn't have permissions to create/move the log files.
