### ISSUE TITLE
Retrieving latest version not working

### ISSUE THREAD

**Issue by majorpdd** [Tautulli/Tautulli#1173]
**Version:**
V2.0.0-BETA
**Branch:**
Beta
**Commit hash:**
bd07cf5a042187b1170a9a55e0e6ffe0e3e0a599
**Operating system:**
Ubuntu 16.04.3 LTS
**Python version:**
2.7.12
**What you did?**
Upon loading its not picking up latest version
**What happened?**
Requesting URL via GET method: https://api.github.com/repos/tautulli/plexpy/commits/beta

Request raise HTTP error with status code 404 (local client error).

Server responded with message: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

Could not get the latest version from GitHub. Are you running a local development version?
**What you expected?**
New version found
**How can we reproduce your issue?**

On initial start

**Comment by JonnyWong16** [comment]
You have the wrong repository name in your config file. I don't know how you did that unless you installed from a different/wrong branch before the beta. Either edit the correct repository in the config file or reinstall.

**Comment by majorpdd** [comment]
I used git on ubuntu and changed the Branch as shown [here](https://www.reddit.com/r/PleX/comments/7kmhl3/its_finally_here_tautulli_v2_beta_formerly_plexpy/).

Where should i change in the config?

**Comment by JonnyWong16** [comment]
You should just delete the config file and reinstall.

**Comment by majorpdd** [comment]
Removed Config and restarted the setup, new config created.
Now my git is showing beta but my config is showing git_branch = master.

I am probably missing newbies stuff here, could you send me info how how to install from beta from start as it seems I keep getting reference to master.

Thanks

**Comment by majorpdd** [comment]
Resolved, backed up DB, removed folder.
Following install instruction but before running setup, changed branch.
Ran config, restored DB.
Resolved.

Thanks Jonny
