### ISSUE TITLE
400 Bad Request,  Illegal cookie name

### ISSUE THREAD

**Issue by cyberb0b** [Tautulli/Tautulli#1174]
**Version:**
latest

**Branch:**
master

**Commit hash:**
cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:**
Ubuntu

**Python version:**
2.7.12

**What happened?**

400 Bad Request

Illegal cookie name SM#/#smFieldsetVisibleSMPagesSettings

Traceback (most recent call last):
  File "/opt/plexpy/lib/cherrypy/_cprequest.py", line 635, in respond
    self.process_headers()
  File "/opt/plexpy/lib/cherrypy/_cprequest.py", line 737, in process_headers
    raise cherrypy.HTTPError(400, msg)
HTTPError: (400, 'Illegal cookie name SM#/#smFieldsetVisibleSMPagesSettings')

**What you expected?**
That it loaded the page.

**How can we reproduce your issue?**
This i can continuously reproduce.
examples explain easiest. Cache clear does not seem to work on chrome and safari,  firefox seems to have no problem with this.

http://ip:8181/plexpy/ - works
http://server:8181/plexpy/  - works
http://server.local:8181/plexpy/   - error 400 as above.

***notes***
- mdns is resolving, service is installed, apache does respond on it.
-The /plexpy/ is for a proxypass, but not the cause of the issue.. 
  Enabled or disabled does not make any change.
- Cookie clearing helps only for a day or 2. The issue re-occures.

**Comment by JonnyWong16** [comment]
Do you have another service or app running on the same ip/domain which uses cherrypy? They might be conflicting with each other.

**Comment by JonnyWong16** [comment]
#523

**Comment by cyberb0b** [comment]
No plex request,

however
- radarr
- sonarr
- deluge
- plex
- cups
- webmin
and a few other things but they go through apache.

(Sorry for the late response but these holidays mess up my schedule.
