### ISSUE TITLE
Existing sessions in v1 db cause v2 WebSockets to fail

### ISSUE THREAD

**Issue by davidlohle** [Tautulli/Tautulli#1175]
**Version:** v2.0.1-beta

**Branch:** beta 

**Commit hash:** 	38ad9c9893f3c1720777aae7727f0ec6ec54e0c5

**Operating system:** Windows Server 2016

**Python version:** 2.7

**What you did?** 
Upgraded to v2 with a v1 database that had existing stream activity during shutdown.

**What happened?**
Websocket connections fail to Plex Server

**What you expected?**
Functioning websockets

**How can we reproduce your issue?**
While Tautulli is running on 1.4 and someone is streaming, shut down the server and migrate to v2 with existing DB. Future websocket connections will fail.

```
2017-12-22 01:30:51 - WARNING :: MainThread : Websocket :: Unable to open connection.
2017-12-22 01:30:51 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "plexpy.py", line 267, in <module>
    main()
  File "plexpy.py", line 199, in main
    web_socket.start_thread()
  File "C:\Users\Administrator\Documents\Tautulli\plexpy\web_socket.py", line 38, in start_thread
    activity_pinger.check_active_sessions(ws_request=True)
  File "C:\Users\Administrator\Documents\Tautulli\plexpy\activity_pinger.py", line 163, in check_active_sessions
    success = monitor_process.write_session_history(session=stream)
  File "C:\Users\Administrator\Documents\Tautulli\plexpy\activity_processor.py", line 158, in write_session_history
    session.update(json.loads(session['raw_stream_info']))
  File "C:\python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```
Was the error I got when I threw a 'raise' into the websocket thread. `check_active_sessions` is digging through the DB for cached sessions and since the JSON/dict schema has changed, the json load will fail because `session['raw_stream_info']` is None.

I'm not too familiar with the code, but if possible v2 should clear that table when first booting from a v1 state. Clearing out any entries under sessions in plexpy.db solves this issue.

**Comment by JonnyWong16** [comment]
I tried multiple times and I cannot reproduce this.

1. Git clone a completely new v1.4.25.
2. Start and run through the setup.
3. Play a movie on my server. Stream shows up in the database.
4. Shutdown PlexPy while stream is still playing.
5. Switch the git branch to beta (Tautulli v2.0.1-beta).
6. Start up Tautulli. Stream is still playing and database entry is correct upgraded.
7. Everything is working as expected.

Edit: Got it. If the stream is stopped after v1 is shut down and before v2 is started.

**Comment by davidlohle** [comment]
Just checked and repeated my steps with my old v1 db. b2157df solves this issue. Thank you!
