### ISSUE TITLE
Discord not working in V2

### ISSUE THREAD

**Issue by matmuilwijk** [Tautulli/Tautulli#1176]
Issue: Discord notifications don't get triggered. In V1, I used the Slack channel for discord, and this worked great, but with the new Discord channel not so much. Test notification get's delivered, but when something is added, or someone starts playing, it doesn't. It also doesn't show up in the notification log. (The test does)
**Version:**
2.0.0 beta
**Branch:**
v2
**Commit hash:**
??
**Operating system:**
Ubuntu 16.04 LTS Server
**Python version:**
2.7.12
**What you did?**
Set up new Discord notification trigger.
**What happened?**
After a successful test: nothing except succesful tests
**What you expected?**
My notifications to trigger, like before.
**How can we reproduce your issue?**
Add discord as a notification trigger, set it up with 'Include subject line', 'Include Rich Metadata', ''Include Plot Summaries', 'Include Plex Link' and 'Poster Thumbnail'. Movie and TV: IMDB, music: Last.FM. No discord Username/color.
![2017-12-22 09_23_01-greenshot](https://user-images.githubusercontent.com/20720945/34290833-c06efe44-e6f9-11e7-99dd-291ab72bb898.jpg)

**What are your (relevant) settings?**

**Link to logs:**

![2017-12-22 09_23_01-greenshot](https://user-images.githubusercontent.com/20720945/34290848-ca290592-e6f9-11e7-8868-1de45fdc85d8.jpg)

**Comment by matmuilwijk** [comment]
Addition: Restarting the old Slackchannel doesn't notify either.

**Comment by JonnyWong16** [comment]
Proper branch and commit hash please. 

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q14

**Comment by kudos** [comment]
@JonnyWong16 This is from missing columns on the `notify_log` table. I got errors for missing `body_text` and `parent_rating_key` before I dropped the table and recreated.

**Comment by JonnyWong16** [comment]
This should not happen if you switched from master (or dev) to beta. If you switched from other v2 branches (or switched to any of them), I cannot guarantee a clean database upgrade.
