### ISSUE TITLE
"Watched Percent" will not set

### ISSUE THREAD

**Issue by majorpdd** [Tautulli/Tautulli#1177]
**Version:**
v2.0.1-beta (2017-12-19)
**Branch:**
beta
**Commit hash:**
38ad9c9893f3c1720777aae7727f0ec6ec54e0c5
**Operating system:**
Ubuntu 16.04.3 LTS
**Python version:**
2.7.12
**What you did?**
Tried to change the percentage watched on Movie and TV.
**What happened?**
After restart they reset back to 85
**What you expected?**
Setting was saved
**How can we reproduce your issue?**
As Above.
**What are your (relevant) settings?**
MOVIE @ 95%
TV @ 95%
**Link to logs:**
Logs are showing "Tautulli Config :: Writing configuration to file" then "Received signal: restart"

**Comment by majorpdd** [comment]
To add, if I manually set the config file then setting saves.

**Comment by majorpdd** [comment]
Actually, it did once, but now it will not!

**Comment by majorpdd** [comment]
Ok, so chrome restarts after every setting change, tried another browser (Firefox), saves settings without  restart.  But when I restart, settings go back to 85.

**Comment by JonnyWong16** [comment]
Fixed in v2.0.2-beta.
