### ISSUE TITLE
Stop times are "n/a" in History

### ISSUE THREAD

**Issue by coneslayer** [Tautulli/Tautulli#1178]
**Version:** VERSION V2.0.2-BETA

**Branch:** beta

**Commit hash:** e60241ca734b230470349ecdbeca8a65dddd8797

**Operating system:** Windows 10

**Python version:** Python 2.7.13 |Anaconda, Inc.| (default, Sep 19 2017, 08:25:59) [MSC v.1500 64 bit (AMD64)] on win32

**What you did?** Viewed the watch history

**What happened?** Stopped times are "n/a" even though viewing sessions have ended. Date column is misaligned. [Screenshot](https://imgur.com/Es8WUK1)

**What you expected?** Stop time to be correct. Date column to be aligned with other rows.

**How can we reproduce your issue?** View history tab.

**What are your (relevant) settings?** The problem may be related to Tautulli updating at 2017-12-24 23:16:56. The problem started with the first viewing session after that.

**Link to logs:**
[plexpy.log](https://gist.github.com/coneslayer/832e70a0e31f08a9436a3dd9d7f1ca8a)
[plex_websocket.log](https://gist.github.com/coneslayer/b62f4c541d0028dc4ab530ae66401069)
plexpy_api.log is empty

**Comment by JonnyWong16** [comment]
It's n/a because that stream is currently in session.

It should look like this (this stream is currently paused)
![image](https://user-images.githubusercontent.com/9099342/34342116-7f9b9f44-e95b-11e7-842c-1b19c11a3968.png)

Try clearing your browser cache. v2.0.2-beta also had some history logging bugs. Try v2.0.3-beta.

**Comment by coneslayer** [comment]
Thanks, updating to 2.0.3-beta fixed the issue.

Not that it matters now, but the streams in question weren't paused--they had stopped. Their stop times are now shown properly in 2.0.3-beta.

![image](https://user-images.githubusercontent.com/4835005/34342170-c100bfd6-e975-11e7-8733-76525a91a265.png)
