### ISSUE TITLE
IPv6 addresses don't format properly

### ISSUE THREAD

**Issue by psaab** [Tautulli/Tautulli#1179]
When displaying an IPv6 address, it causes the overall formatting of the status box to be off since the wraps to another like..  See the attached screenshot.

<img width="342" alt="screenshot 2017-12-25 13 03 52" src="https://user-images.githubusercontent.com/196946/34342914-39c389b4-e974-11e7-8b09-922efdb2e613.png">

**Comment by JonnyWong16** [comment]
Added overflow for IPv6 addresses in 5a14c229a14f9a93825abacfeeb7eef98e4b57be.
