### ISSUE TITLE
v2 Issue :: Join notifications are not sending the API Key correctly

### ISSUE THREAD

**Issue by heymoe** [Tautulli/Tautulli#1183]
TAUTULLI: V2.0.4-BETA
Git Branch: beta
Git Commit Hash: e908c45cf27097de79e7fef9b539e405822e2c34
OS: Linux / Docker
Python: 2.7.14

Setup Join notification and hit the test button and got a notification that say you need to send the api key when sending to groups / multiple devices (or something to that effect).

Looking at the code (notifiers.py) it looks like you're sending the the api key using this format in the URL:

api_key=[api key]

but it needs to be:

apikey=[api key]

I made the below change locally and notifications now work.

```
--- notifiers.py.org
+++ notifiers.py
@@ -1963,7 +1963,7 @@
 
         deviceid_key = 'deviceId%s' % ('s' if len(self.config['device_id'].split(',')) > 1 else '')
 
-        data = {'api_key': self.config['api_key'],
+        data = {'apikey': self.config['api_key'],
                 deviceid_key: self.config['device_id'],
                 'text': body.encode("utf-8")}
```

**Comment by JonnyWong16** [comment]
Thanks. I guess I forgot that line in 6b2bc0108b6f90daabe3c04bae9ec112ac1458b4.

**Comment by JonnyWong16** [comment]
Fixed in 645ef86c75fc877196cce6cf41ef9994c35cf1d4

**Comment by heymoe** [comment]
Hey, quick question.. 

I'm running Tautulli from the beta channel. Is that the correct channel I should be running for Tautulli?

It looks like your commit for this fix was to the master channel which is Plexpy (pre v2?). The beta channel did not get this fix.

**Comment by JonnyWong16** [comment]
It's not pushed to beta yet.

**Comment by heymoe** [comment]
Ahh.. gotcha.. Thanks again!
