### ISSUE TITLE
Session reset after server restart

### ISSUE THREAD

**Issue by felixbuenemann** [Tautulli/Tautulli#1184]
I'm running the v2 of tautulli/plexpy and my login session resets every time the server is restarted and I have to log in again even though I have the "remember me" checkbox checked during login.

I would expect the session to still be valid after a server restart.

**Version:** v2

**Branch:** nightly

**Commit hash:** a8c5f48b6042d30f7a2689928989b1d1740f808e

**Operating system:** Ubuntu Xenial x86_64

**Python version:** 2.7.12

**Comment by felixbuenemann** [comment]
I think the reason for this is that the `tools.sessions.storage_type` setting in cherrypy default to "ram". For sessions to be remembered the `tools.sessions.storage_type`would have to be set to "file" and `tools.sessions.storage_path` to a directory to store sessions.

I'm not sure how this ties in with the "remember me" feature.

**Comment by JonnyWong16** [comment]
Changed in b2b728a.

"Remember me" still works.

**Comment by felixbuenemann** [comment]
Thanks.
