### ISSUE TITLE
Statistics information doesn't flow across the page correctly

### ISSUE THREAD

**Issue by zenjabba** [Tautulli/Tautulli#119]
When the browser is put into full screen, the statistics information doesn't go across the page as the other two section do correctly (now playing and recently added)

<img width="2464" alt="screenshot 2015-08-23 08 47 26" src="https://cloud.githubusercontent.com/assets/679864/9428240/ca621222-4973-11e5-8550-dd13da17ae68.png">

**Comment by drzoidberg33** [comment]
I just pushed a fix for this in https://github.com/drzoidberg33/plexpy/commit/7eac5213692db57071705396ee90cf60909d42e3

Will be pushed to master in next release.
