### ISSUE TITLE
Trying to load Media Info for library gets error

### ISSUE THREAD

**Issue by hotleadsingerguy** [Tautulli/Tautulli#1190]
I realize I'm only including the single line in the log, but my logs are enormous and the rest is just library refreshes.

Version:
2.0.7 BETA

Branch:
BETA

Operating system:
Ubuntu latest

Python version:
2.7.12

What you did?
Select Libraries, select a library (Movies, in this case), and nothing loads when attempting to fetch rows. Viewing the log presents the message below.

What happened?
The rows don't load in the datagrid and the log has an error: 
`WebUI :: /library?section_id=1#tab_tabs-mediainfo : Uncaught TypeError: Illegal invocation. (jquery-2.1.4.min.js:4)`

What are your (relevant) settings?
I'm not sure if I have any relevant settings, but my libraries are all hosted in a Windows environment and shared to the Linux VM. Plex itself has perfect access to all, as does the user running Tautulli.

**Comment by JonnyWong16** [comment]
Try deleting the `media_info_X.json` cache files inside the cache directory.

**Comment by hotleadsingerguy** [comment]
That did the trick! Thanks. Was this a relic from PlexPy, or another issue? It worked to load the info on the phone app, just not in the webapp.
