### ISSUE TITLE
Notifications without Message Body fail

### ISSUE THREAD

**Issue by redfellow** [Tautulli/Tautulli#1191]
**Version:** 
V2.0.7-BETA

**Branch:** 
beta

**Commit hash:** 
04d4ffb63d48056d80e63d9a91b59b0f00791bb2

**Operating system:**
Windows 10

**Python version:**
2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]

**What you did?**
I attempted to truncate Tautulli Discord notifications a bit:
![Image 1]( https://vgy.me/MTmuvT.png)
.. so that they would appear similar to Sonarr and Radarr notifications: ![Image 2]( https://vgy.me/mjxFBg.png)

**What happened?**
Notification fails if `Message Body`is not set.

**Link to logs:** 
Logs: ![Image 3]( https://vgy.me/Z4yNIN.png)

**Comment by JonnyWong16** [comment]
You cannot send blank notifications.

I know some notification agents allow a blank body, but others do not. I don't want to go through and manually specify different settings for each agent.

**Comment by redfellow** [comment]
I figure either 1) the UI shouldn't allow setting the inputs to empty, or 2) the notification handler could just attempt to dispatch the notification regardless - either the recipient can or can't handle it - but I don't see why making said attempt would require making separate settings for each agent?

I went ahead and tested 2) for Discord, Slack & Facebook and tested all 3 - it worked as expected. I'll open a PR so you can see the dirty little change I did, but in any case, if it's too much a hassle, I can live with having the two liners np.

**Comment by JonnyWong16** [comment]
I meant making a setting like "Include Body Text" similar to the one for "Include Subject Line".

**Comment by redfellow** [comment]
Don't know how I managed to miss that setting, but I suppose for my usecase unchecking it and putting everything in the body works just as well. Thanks!
