### ISSUE TITLE
Since installing PlexPy there is now no option to stop playback or send user a message in plex 'Now Playing'.

### ISSUE THREAD

**Issue by MRFU510N88** [Tautulli/Tautulli#1197]
As per title.

Example before Installation of Plexpy with stop playback admin option:
![image](https://user-images.githubusercontent.com/35142900/34614801-909c744e-f22a-11e7-950a-1fabe505a21c.png)

Screenshot after installation:

![image](https://user-images.githubusercontent.com/35142900/34615080-76c4febe-f22b-11e7-8c30-535372aa4c16.png)

Option has now disappeared?? any help with this would be greatly appreciated as I used it quite often.

Cheers,

Jay

**Comment by JonnyWong16** [comment]
1. That's not PlexPy, that's Plex Web.
2. Terminating streams is a Plex Pass feature. Based on your second screenshot (before you edited it), you don't have Plex Pass.

**Comment by alneven** [comment]
#fail

**Comment by MRFU510N88** [comment]
Thank you @JonnyWong16  

It happens to be coincidence that my plex subscription was set to expire  a day ago and I hadn't noticed. 

I think PlexPy is Brilliant and I cant believe you got back to me so fast. 

I do have one more question however I will create a new post encase another user needs to search for a similar answer. 

Thanks again

Jay.
