### ISSUE TITLE
Plex Server views and behaves differently since the install of PlexPy. 

### ISSUE THREAD

**Issue by MRFU510N88** [Tautulli/Tautulli#1198]
Since I installed PlexPy I noticed that Plex server views differently when i was messing about with settings for PlexPy to get it set up properly, I have a feeling it has something to do with me toggling ssl.

Visually:

Correct me if I just didn't notice before, but I'm sure there was not a (default theme)scroll bar on the left hand side see picture:
![image](https://user-images.githubusercontent.com/35142900/34625805-03949efa-f252-11e7-9196-b7d5ce299831.png)

as it used to look like:
![image](https://user-images.githubusercontent.com/35142900/34625837-2a25e7ae-f252-11e7-9cf3-ca8d7d462602.png)

Whenever I open:

I get this message that I didn't before.

'Invalid credentials
 Your credentials have expired. Please sign in again.'

I cant remember why but I have a feeling it has something to do with tokens. 

Honestly I'm not mental but thanks for your help @JonnyWong16 PlexPy is a masterpiece i just want to make sure ive got it running correctly and perhaps help others in the process.

Cheers!

Jay.

**Comment by JonnyWong16** [comment]
Also not a PlexPy issue.

https://www.reddit.com/r/PleX/comments/7lgj6z/web_player_differences_between_chrome_and_firefox/

**Comment by MRFU510N88** [comment]
I visited your link, I am using Microsoft edge for both before and after pictures?

**Comment by Arcanemagus** [comment]
@Jaysurf88 The Plex web interface has _nothing_ to do with PlexPy / Tautulli (the repository you filed this issue on). The link is showing that this is likely a recent change on Plex's side that broke the scroll bar hiding for non-Chrome browsers.
