### ISSUE TITLE
Notification Conditions not being evaluated 

### ISSUE THREAD

**Issue by ridizy** [Tautulli/Tautulli#1199]
**Version:** 2.0.10-BETA
**Branch:** beta
**Commit hash:** 74a68f3c7de290772e070a0b68a0d491d23085ba
**Operating system:** macOS 10.13.2
**Python version:** 2.7.13 
**PMS version:** 1.11.0.4666

**What I did/what happened:**
Updated today which removes notification filtering from libraries.  I want to keep history for my audio libraries but not send notifications for them.  After this commit, I started receiving notifications for "watched" for each track that is played.

I went to my e-mail notification and added a condition: "Media Type | is not | track".  I still received an e-mail.

I also replaced that condition with: "Library Name | is not | Music".  I still received an e-mail.  

*Side note*...just to make sure I was using the correct text, I added {media_type} and {library_name} to the text of my notification.  {media_type} reports "track" but {library_name} is blank.  Other libraries are also not displaying a {library_name} in the notification.

**What I expected:**
History would be kept for media that was "watched" from the library "Music" but no notifications would be sent

**How to reproduce:**
Create an e-mail notification with a condition that library_name is not <something>.  Watch something from library <something> and see if a notification e-mail is still sent.

Please let me know which logs, if any,  you'd like to see.

**Comment by JonnyWong16** [comment]
Did you fill in the "Condition Logic"?

**Comment by ridizy** [comment]
Yes and no.  Originally I had 2 conditions for 2 library_name (I wasn't sure if I could list them both in a single condition) and I used `{1} and {2}`, but that didn't work.*

Since I changed it to media_type I only had one condition and didn't realize that I still needed to add logic.  Setting it to `{1}` does indeed work - thank you!

*Going back to the library_name issue.  Should I open a separate one for that or can we use this one?

**Comment by JonnyWong16** [comment]
`{library_name}` shows up fine for me.

![image](https://user-images.githubusercontent.com/9099342/34629262-63fd39ae-f21c-11e7-8cef-d19d13de8177.png)

![image](https://user-images.githubusercontent.com/9099342/34629300-7df83f84-f21c-11e7-8780-13359b132f9d.png)

Yes, you can do more than one value per condition. (There is an implicit `or` in between values. i.e. `Library Name` `is not` `Music OR Podcasts`)

![image](https://user-images.githubusercontent.com/9099342/34629316-8cde6bf4-f21c-11e7-809c-d1f0834296a0.png)

Another note, if you're using `Media Type`, you'll probably want to include `album` and `artist` as values too.

**Comment by ridizy** [comment]
Thanks for clarifying how Conditions work!

As for `{library_name}`, it appears to work for certain actions, but not for `on_watched`:

![image](https://user-images.githubusercontent.com/33641/34630422-04e33874-f23a-11e7-89ed-b5a067386ef8.png)


![image](https://user-images.githubusercontent.com/33641/34630389-e9296554-f239-11e7-8d7c-b01cd62d4062.png)

**Comment by JonnyWong16** [comment]
Thanks, I found the bug.

**Comment by JonnyWong16** [comment]
Fixed in v2.0.11-beta.
