### ISSUE TITLE
Tautulli Security issue

### ISSUE THREAD

**Issue by xxwiredxx** [Tautulli/Tautulli#1200]
**Version:**
V2.0.4-BETA

**Branch:**
Beta

**Commit hash:**
e908c45cf27097de79e7fef9b539e405822e2c34

**Operating system:**
Linux 4.9.20-hardened-whatbox-r1

**Python version:**
2.7.14 (default, Jan 4 2018, 17:02:38) [GCC 5.4.0]

**What you did?**
Took the hashed password from the config.ini and pasted it in the web login with the username and the hash password was accepted, allowing to pass the hash.

**What happened?**
Hashed passwords are accepted in the web login.

**What you expected?**
Hashed passwords should not be accepted in the weblogin.

**How can we reproduce your issue?**
Repeat the above steps

**What are your (relevant) settings?**
Password is hashed
HTML login form

**Link to logs:**
N/A

**Comment by JonnyWong16** [comment]
Fixed in v2.0.11-beta.
