### ISSUE TITLE
Fails to start on boot with systemd unit file

### ISSUE THREAD

**Issue by Do-while-Bacon** [Tautulli/Tautulli#1201]
**Version:** 2.0.11-BETA but problem existed in 1.X

**Operating system:** CentOS 7.4.1708

**Python version:** 2.7.5

**What you did?** Enabled plexpy as a service using the provided systemd script.

**What happened?** The service fails to start on boot and must be manually started by an administrator after the machine has full booted.

**What you expected?** The service would start on boot with the rest of my daemons.

**How can we reproduce your issue?**
Install the latest build of CentOS 7.4
Enable the application as a daemon via systemd
Reboot

**What are your (relevant) settings?**
[Unit]
Description=PlexPy - Stats for Plex Media Server usage
[Service]
ExecStart=/apps/plexpy_system/PlexPy.py --quiet --daemon --nolaunch --config /apps/plexpy/config.ini --datadir /apps/plexpy
GuessMainPID=no
Type=forking
User=plexpy
Group=plexpy
[Install]
WantedBy=multi-user.target

**Logs:**
Jan  7 14:31:12 www systemd: Starting plexpy.service...
Jan  7 14:31:12 www systemd: Failed at step USER spawning /apps/plexpy_system/PlexPy.py: No such process
Jan  7 14:31:12 www systemd: plexpy.service: control process exited, code=exited status=217
Jan  7 14:31:12 www systemd: Failed to start plexpy.service.
Jan  7 14:31:12 www systemd: Unit plexpy.service entered failed state.
Jan  7 14:31:12 www systemd: plexpy.service failed.

Thanks. Love the app by the way.

**Comment by MikeDawg** [comment]
Do the user plexpy and group plexpy exist?

egrep -i plexpy /etc/passwd
egrep -i plexpy /etc/group

**Comment by Do-while-Bacon** [comment]
I see what the issue is. I'm using LDAP for user and group information and the app is starting before a network connection is available. I resolved the problem by adding "After=network-online.target" to the unit file.

Might not be a bad idea to add that to the bundled unit file? A lot of other apps have it (ombi, radarr, sabnzbd, deluge...etc).

**Comment by jaydee99** [comment]
Thanx, had the same problem, solved it !
