### ISSUE TITLE
Play History will not be fetched through PlexPy

### ISSUE THREAD

**Issue by daeks** [Tautulli/Tautulli#1202]
Version: PlexPy 1.4.25 / PMS 1.11.0.4666
 Branch:  master 
 Commit hash: cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
 Operating system: Windows 2008R2
 Python version: 2.7.14
 What you did? Updated PMS to 1.11.0.4666
 What happened? History will not be actualised. I can see activity on the homepage, but not in the history tab. Use Websocket is enabled and ignore intervall is set to 60. 
 What you expected? Played a movie around 5 minutes but nothing appears on history tab.
 How can we reproduce your issue? same happens with v2 beta
 What are your (relevant) settings? Use Websocket is enabled and ignore intervall is set to 60. 

Log:
2018-01-08 14:13:19 - DEBUG   :: MainThread : PlexPy Monitor :: Session 3 has stopped.
2018-01-08 14:13:19 - DEBUG   :: MainThread : PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'
2018-01-08 14:13:19 - WARNING :: MainThread : Websocket :: Unable to open connection.

**Comment by JonnyWong16** [comment]
Have you read the FAQ?

**Comment by daeks** [comment]
Which point of the FAQ do you mean? I had it running for a couple of months already and tried without websocket as well.

**Comment by JonnyWong16** [comment]
How about the one that is the exact question you asked...

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#history-q3
