### ISSUE TITLE
Tautulli/V2 Reverse Proxy issues with Nginx

### ISSUE THREAD

**Issue by SlothCroissant** [Tautulli/Tautulli#1204]
**Version:** V2.0.11-BETA

**Branch:** beta

**Commit hash:** cf14fbc3f05ec4ced5891f7a2d80d54bedeccef6

**Operating system:** Docker on UnRAID [shiggins8/tautulli](https://hub.docker.com/r/shiggins8/tautulli/)

**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]

**Explanation of the Problem**
Before V2 beta (running PlexPy and Tautulli in parallel while in Beta), I could access `plexpy.url.com` using the Nginx reverse proxy configuration below. In Tautulli, this same config throws some strange behavior using `tautulli.url.com`.

Observations:
* When navigating to `tautulli.url.com` when not logged in, it redirects me to `https://tautulli.url.com:8181/auth/logout` and throws an `ERR_SSL_PROTOCOL_ERROR` in Chrome. 
* If I manually change the URL to go to `https://tautully.url.com/auth/login`, I can successfully login and cache my token/cookie. However, instead of redirecting me to `http://tautulli.url.com/home`, it takes me to `https://tautulli.url.com:8181/`, with another `ERR_SSL_PROTOCOL_ERROR`.
* At this point, I can manually go to `https://tautulli.url.com/home` and Tautulli works as expected. 

Nginx configuration:
```
server {
  listen 80;
  server_name tautulli.url.com;
  return 302 https://tautulli.url.com$request_uri;
}

server {
  listen 443 ssl;
  server_name tautulli.url.com;

	ssl_certificate /etc/nginx/keys/mycert.pem;
    ssl_certificate_key /etc/nginx/keys/mycert.key;

  ssl on;
  ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC4-SHA';
  ssl_prefer_server_ciphers on;
  ssl_dhparam /etc/nginx/keys/dhparams.pem;

  proxy_hide_header X-Frame-Options;
  add_header X-XSS-Protection "1; mode=block";
  add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

  location / {
    	proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_pass http://10.0.1.4:8182; ### I used 8182 forwarded in Docker to 8181, FYI ###
  }
}
```

Let me know if I can provide you with any further details or logs. Thanks!

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q10

**Comment by SlothCroissant** [comment]
You're the man, never saw that Wiki since I never had an issue with PlexPy on the same config.

Thanks and keep up the great work!
