### ISSUE TITLE
Feature Request: Additional variables in IFTTT Notification Agent

### ISSUE THREAD

**Issue by hoobio** [Tautulli/Tautulli#1205]
When adding the `{machine_id}` variable to the IFTTT Notification Agent the following error is thrown when any IFTTT notification is triggered and nothing is posted to the webhook:

```
Uncaught exception: Traceback (most recent call last):
    File "C:\plexpy\plexpy\logger.py", line 270, in new_run 
        old_run(*args, **kwargs) 
    File "C:\Python27\lib\threading.py", line 761, in run 
        self.__target(*self.__args, **self.__kwargs) 
    File "C:\plexpy\plexpy\notification_handler.py", line 68, in notify 
        metadata=metadata) 
    File "C:\plexpy\plexpy\notifiers.py", line 593, in send_notification 
        return iftttClient.notify(subject=subject, message=body, action=notify_action) 
    File "C:\plexpy\plexpy\notifiers.py", line 1813, in notify 
        event = unicode(self.event).format(action=action) 
KeyError: u'machine_id' 
```

Can confirm IFTTT **is** working without the variable.

 - **PlexPy Version:** 1.4.25
 - **Git Branch:** master
 - **Git Commit Hash:** cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
 - **Python Version:** 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

**Comment by hoobio** [comment]
Tested on newer Python version: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]` with no luck. 😭

**Comment by hoobio** [comment]
Never mind I've just realised you cannot use any variable other than `{action}`.

Please consider this now a feature request to use additional variables in the IFTTT Notification Agents in the `Ifttt event` field.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests
