### ISSUE TITLE
Join Notification - Stop Using DeviceID

### ISSUE THREAD

**Issue by zhdenny** [Tautulli/Tautulli#1206]
Join app developer has recommended all devs no longer use DeviceID...it is not a reliable / stable value. Instead, use Device Name.

Reference post from Join developer
http://forum.joaoapps.com/index.php?threads/10228/

**Comment by zhdenny** [comment]
Join app developer has recommended all devs no longer use DeviceID...it is not a reliable / stable value. Instead, use Device Name.

Reference post from Join developer
http://forum.joaoapps.com/index.php?threads/10228/

**Comment by Arcanemagus** [comment]
For reference, this is already fixed in Tautulli:
https://github.com/JonnyWong16/plexpy/blob/45c2ccdffe309eaf734631da1fd1d722f6e6f875/plexpy/notifiers.py#L1950
