### ISSUE TITLE
Wiki Addition: Nginx Reverse Proxy with HTTP>HTTPS Redirection (V2/Tautulli)

### ISSUE THREAD

**Issue by SlothCroissant** [Tautulli/Tautulli#1207]
Hey there @JonnyWong16 , wanted to provide some content for the Wiki, and can't for the life of me figure out how to do a PR for Wiki content. 

Below is an Nginx reverse proxy example that will allow users to access Tautulli via tautulli.url.com, and redirects HTTP requests to HTTPS. This configuration passes [SSL Labs'](https://www.ssllabs.com) test with an "A" grade. 

DH Params creation via `openssl`:
`openssl dhparam 2048 -out /etc/nginx/keys/dhparams.pem`

[How to use LetsEncrypt certs (free!) with Nginx if you don't have a cert](https://www.nginx.com/blog/free-certificates-lets-encrypt-and-nginx/). This is *highly* recommended if you expose Tautulli to the internet. It also provides that coveted green padlock in Chrome and bypasses SSL warnings in browsers.

Change the following:
* All instances of `tautulli.url.com` to your preferred domain
* your `ssl_certificate`, `ssl_certificate_key`, and `ssl_dhparam` locations, as they may well differ from mine
* `127.0.0.1:8181` if your Tautulli instance lives at another IP/port combo.  

```
server {
  listen 80;
  server_name tautulli.url.com;
  return 302 https://tautulli.url.com$request_uri;
}

server {
  listen 443 ssl;
  server_name tautulli.url.com;

  ssl_certificate /etc/nginx/keys/cert.pem;
  ssl_certificate_key /etc/nginx/keys/cert.key;

  ssl on;
  ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC4-SHA';
  ssl_prefer_server_ciphers on;
  ssl_dhparam /etc/nginx/keys/dhparams.pem;

  proxy_hide_header X-Frame-Options;
  add_header X-XSS-Protection "1; mode=block";
  add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

  # Standard proxying headers
  proxy_set_header    Host                $host;
  proxy_set_header    X-Real-IP           $remote_addr;
  proxy_set_header    X-Forwarded-Host    $server_name;
  proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

  # SSL proxying headers
  proxy_set_header    X-Forwarded-Proto   $scheme;
  proxy_set_header    X-Forwarded-Ssl     on;

  location / {
	proxy_pass http://127.0.0.1:8181;
  }
}
```

**Comment by Hellowlol** [comment]
Just edit the wiki directly?

**Comment by JonnyWong16** [comment]
I locked the wiki. I felt Tautulli is getting too big to have an open wiki.
