### ISSUE TITLE
SSL error when trying to send notification to Mattermost (slack)

### ISSUE THREAD

**Issue by seanvree** [Tautulli/Tautulli#1208]
**Version:**
VERSION V2.0.12-BETA

**Branch:**
BETA

**Commit hash:**
644fea666538c101d2a7f6876ca98a7e25a4bbee

**Operating system:**
Windows 10E x64 1709 FCU

**Python version:**
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32

**What you did?**
- Installed new/parallel version of PlexPY (installed to new DIR, diff port)
- Sending notification to Mattermost (Slack)
- This worked great on V1, didn't change anything as far as settings in Mattermost or Plexpy.
- Can send a notification to Gmail  fine.
- Sonarr/radarr all other apps work fine sending notifications

**What happened?**

```
Tautulli Notifiers :: Unable to connect to remote host because of a SSL error
```

**What you expected?**
receive notification

**How can we reproduce your issue?**
1 - create notification agent - mattermost (slack)
2 - use self-hosted slack webhook URL
3 - send notification

**What are your (relevant) settings?**

Slackwebhook URL: https://mydomain.com:8065/hooks/k8n3aoxmhjyk5jiu86axxxxxx
slack channel: blank
Slack UN: Plexpy
slack icon: blank
Slack color: blank
all options unchecked

**Link to logs:**
https://gist.github.com/seanvree/bf04c830af9c8d9d02a825d4eb0beda3

![plexpy_notification](https://user-images.githubusercontent.com/8906637/34809569-a7638900-f64a-11e7-8f50-d8fefd63300a.PNG)

**Comment by JonnyWong16** [comment]
I just tested Slack and it works fine. I think it's something wrong with your mattermost.

![image](https://user-images.githubusercontent.com/9099342/34810431-22b2e20e-f650-11e7-9d74-072ce439edd7.png)

**Comment by seanvree** [comment]
@JonnyWong16  Hummm...Have any idea what to check for?  I mean, it still works in V1, and all my other apps can send fine.  Certs are good, as you can see here:  https://seanvree.com:8065


![image](https://user-images.githubusercontent.com/8906637/34810618-58efdf1a-f651-11e7-942e-0c631fb9b5f5.png)

**Comment by seanvree** [comment]
@JonnyWong16 

Setting the following to 0 fixed this:

```
verify_ssl_cert = 0

```
It's set to 1 on V1, and that works great. still not sure why this doesn't work as all the other applications do.

I think it has something to do with Python backports / SSL_match_hostname ?


Cheers mate.

**Comment by JonnyWong16** [comment]
There is definitely something wrong with the cert on your domain.

This is what I tested. (Not even in Tautulli.)
```
>>> import requests
>>> requests.get("https://seanvree.com")  # This works fine without issues.
<Response[200]>

>>> requests.get("https://seanvree.com:8065")  # This returns a SSLError.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='seanvree.com', port=8065): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
```

And here is the method that v1 used.
```
>>> from httplib import HTTPSConnection
>>> http_handler = HTTPSConnection("seanvree.com")
>>> http_handler.request("GET", "/")
>>> http_handler.getresponse().status
301

>>> http_handler = HTTPSConnection("seanvree.com", "8065")
>>> http_handler.request("GET", "/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 859, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 353, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 601, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by seanvree** [comment]
humm. interesting. V1 works great. Like I said, not trying to argue here, but I have like 20 apps (internal and external) all sending to mattermost just great...weird. Never had any issues with my certs...ever.

https://www.ssllabs.com/ssltest/analyze.html?d=seanvree.com
