### ISSUE TITLE
Deleted library still showing in PlexPy

### ISSUE THREAD

**Issue by AnthonyBe** [Tautulli/Tautulli#1209]
3 days ago I upgraded my free version of Plex to a Plex Pass, and consequently, created a new Premium Music library and deleted the original 'basic' music library.

PlexPy is still showing the deleted library, i.e. I have 2 Music libraries listed.

Should PlexPy have stopped showing the library that no longer exists by now?

Version: 1.4.25
Branch: Release
Operating system: Windows Server 2012 R2
Python version: 2.7.14

**Comment by JonnyWong16** [comment]
#682
