### ISSUE TITLE
Error when loading history table [Safari]

### ISSUE THREAD

**Issue by brentrahn** [Tautulli/Tautulli#121]
Browser: Safari Version 8.0.8 (10600.8.9)
Server: Ubuntu 14.04.3

When loading the history table (either main history table or table on user profile) the following error message is displayed in a popup.

`DataTables warning: table id=history_table - Requested unknown parameter '10' for row 0. For more information about this error, please see http://datatables.net/tn/4`

I have not experienced this issue in any other browser. This started occurring after the latest update.

Logs did not contain any data pertaining to this issue so they were not included.

**Comment by JonnyWong16** [comment]
https://forums.plex.tv/discussion/comment/1001385/#Comment_1001385

**Comment by brentrahn** [comment]
Thank you. I should have checked those forums too - I only checked github issues for similar tickets.

**Comment by JonnyWong16** [comment]
It was also on github #109.
