### ISSUE TITLE
Add a history event manually

### ISSUE THREAD

**Issue by TrialMaster** [Tautulli/Tautulli#1210]
I only discovered PlexPy after a remote user had watched two episodes of a series. I'm just being anal I know, but is it possible to manually create the two episodes that were missed? Can I create the entries under my username then edit them to the proper user maybe?

Thank you, I love this program, I even went out and purchased a Raspberry Pi just to log my Nvidia Shield.

**Comment by SgtBatten** [comment]
database editor and enter the lines yourself I guess.

**Comment by TrialMaster** [comment]
ok, thanks :)
