### ISSUE TITLE
Libraries with Recently Added disabled, sending Slack notification

### ISSUE THREAD

**Issue by daymanbpi** [Tautulli/Tautulli#1212]
**Version:**
2.0.13-BETA
**Branch:**
BETA
**Commit hash:**
e9725a00819cd103b1fd34141c581b65b340eed7
**Operating system:**
Docker
**Python version:**

**What you did?**
Enabled slack notifications for recently added items on plex.
**What happened?**
All new additions send notification on slack. Items in libraries not showing up in recently added on plex, still send out notifications on slack.
**What you expected?**
Should just be libraries with dashboard enabled, to show up in recently added items on plex.
**How can we reproduce your issue?**

Added move/show in library that does not  have dashboard box ticked, under library settings. Slack notification still sends out.
**What are your (relevant) settings?**
Usual tautulli settings with slack webhook.
**Link to logs:**

**Comment by JonnyWong16** [comment]
Dashboard has nothing to do with notifications.  Never has.

https://github.com/JonnyWong16/plexpy/releases/tag/v2.0.10-beta
