### ISSUE TITLE
Facebook Notifications

### ISSUE THREAD

**Issue by wellingssimon** [Tautulli/Tautulli#1216]
Probably a question more than an issue. I'm trying to get facebook notifications working with TV episode information. In Facebook settings I have tried with The Movie Database which gives series info rather than episode, Plex Web which doesn't give any details and TheTVDB which used to work but I gather no longer does due to Facebook API changes.

Anybody out there managed to get this working in the way I would like? I will carry on experimenting in the meantime.

**Comment by JonnyWong16** [comment]
GitHub Issues are for bug reports. Use the Discord Server for help.

**Comment by wellingssimon** [comment]
Apologies. Thanks for all the great work!
