### ISSUE TITLE
Delete button does not work [Safari]

### ISSUE THREAD

**Issue by brentrahn** [Tautulli/Tautulli#122]
Browser: Safari Version 8.0.8 (10600.8.9)
Server: Ubuntu 14.04.3

Clicking the "Delete Mode" button in Safari does nothing.

**Comment by drzoidberg33** [comment]
Please refresh your page and try again. F5 or the refresh button.

**Comment by brentrahn** [comment]
Once I fixed the history tables issue the button started working. Thanks.
