### ISSUE TITLE
ImportError: No module named 'activity_pinger'

### ISSUE THREAD

**Issue by dannyhanes** [Tautulli/Tautulli#1220]
**Operating system:**
Ubuntu 16.04.3

**Python version:**
Python3

**What you did?**
Tried to run `python3 PlexPy.py`

**What happened?**
```
Traceback (most recent call last):
  File "PlexPy.py", line 35, in <module>
    import plexpy
  File "/opt/plexpy/plexpy/__init__.py", line 34, in <module>
    import activity_pinger
ImportError: No module named 'activity_pinger'
```

**What you expected?**
PlexPy to start

**How can we reproduce your issue?**
gitclone the repo
tried to run

**What are your (relevant) settings?**
No settings, fresh install. 

<img width="738" alt="screen shot 2018-01-20 at 10 34 00 am" src="https://user-images.githubusercontent.com/3778687/35185151-a2be4c70-fdcd-11e7-8aba-3fd800165c7a.png">

**Comment by JonnyWong16** [comment]
You didn't read the instructions. 

https://github.com/JonnyWong16/plexpy/wiki/Installation

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q1

**Comment by dannyhanes** [comment]
Ah my bad. I read that as "If running Ubuntu, specify which version of Python you have" not "If you have Ubuntu, make sure you're running Python2.7"
