### ISSUE TITLE
Tautulli Remote does not support HTTP Auth - bug or by design?

### ISSUE THREAD

**Issue by mescon** [Tautulli/Tautulli#1223]
I have all of my services behind a reverse proxy with HTTP Auth.

For example:
``https://user:password@example.com/tautulli``

In the Android Tautulli Remote, there is nowhere to enter user/pass for HTTP Auth which is fine. In some applications such as NZB360 I can just enter ``user:password@example.com`` as hostname and all is well.

In Tautulli Remote, it throws an error.

I don't want to call this a bug report or a feature request as I'm not sure if this is by design (because HTTP Auth isn't considered fully secure and is being deprecated over time), or if this is indeed a bug.

I'll let you decide.

Thanks a bunch for a great piece of software - I couldn't live without it!
Cheers!

**Comment by JonnyWong16** [comment]
For anything related to the app:

https://github.com/wcomartin/PlexPy-Remote

I believe there is already a request for this on the PlexPy-Remote FeatHub page.

**Comment by mescon** [comment]
Ah, didn't even know that was a separate repository. Thanks @JonnyWong16 !
