### ISSUE TITLE
Tautulli Remote doesn't receive notifications

### ISSUE THREAD

**Issue by Mssol94** [Tautulli/Tautulli#1224]
**Version:** V2.0.14-BETA

**Branch:** beta

**Commit hash:** 45c2ccdffe309eaf734631da1fd1d722f6e6f875

**Operating system:** Windows 10

**Python version:** 2.7.14

**Problem description:** 
Tautulli Remote doesn't receive notifications, the notifications are in the notification log and marked as successful, but they aren't received by the Android app.

**How can we reproduce your issue?**

The problem started after I reinstalled my phone. I removed the phone from the settings and set it up again.

**Link to logs:**
![screenshot_9](https://user-images.githubusercontent.com/7490531/35195887-712dfc52-feca-11e7-9b59-8d41d40d1f1d.png)

**Comment by wcomartin** [comment]
Do you get any or none of the notifications?

**Comment by Mssol94** [comment]
None of the notifications.

**Comment by wcomartin** [comment]
Try clearing the app cache and data and setting the app up again using QR code

**Comment by Mssol94** [comment]
That solved the problem.
