### ISSUE TITLE
Duplicate Of Functioning Libraries 

### ISSUE THREAD

**Issue by mmenanno** [Tautulli/Tautulli#1225]
**Version:**
VERSION 1.4.25

**Branch:**
master

**Commit hash:**
cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:**
Linux 4.14.13-unRAID

**Python version:**
2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]

**What you did?**
Migrated PlexPy from iMac to new unRaid server.

**What happened?**
Almost everything migrated perfectly, except I new have 2 copies of all my libraries, but of which seem to be updating when I watch things, but have slightly different total stats.

![](https://api.monosnap.com/rpc/file/download?id=1Dl512e0nLWpkWnI2bN6RFKHI19Kud)

**What you expected?**
To just have one copy of my libraries.

**How can we reproduce your issue?**
Not sure if it would reproduce doing the same steps. I started PlexPy once on the unRAID sever after setting up the docker.
Stopped the docker.
Copied over all the data and settings from the old iMac for PlexPy
Started PlexPy docker
Been using it for a couple weeks now and both copies of the libraries seem to track new things watched yet have different total counts.

**What are your (relevant) settings?**
Not sure

**Link to logs:**
https://gist.github.com/halorrr/765e294ba1ab3f86b662a01f343456a0
^Noticed when I grabbed this I have a lot of warnings in my logs, don't know if those are related.

**Comment by JonnyWong16** [comment]
You didn't read the FAQ.
