### ISSUE TITLE
Option to disable notifications for Music playback

### ISSUE THREAD

**Issue by MatYRiCs** [Tautulli/Tautulli#1227]
After upgrading to newest tautulli beta I don't have the option to exclude music from push notifications. I don't wan't to get push notifications each time a user plays a song.

**Comment by JonnyWong16** [comment]
Changelog from v2.0.10-beta
https://github.com/JonnyWong16/plexpy/releases/tag/v2.0.10-beta

* Notifications:
  * Remove: Notification toggles from library and user settings. Use custom conditions to filter out notifications instead.
