### ISSUE TITLE
[Feature Request] Pushover Poster Attachment

### ISSUE THREAD

**Issue by Nixon506E** [Tautulli/Tautulli#1228]
Pushover 3.0 recently added support for pushing out local image attachments (i.e. not image links) and I was hoping to add support. I took a look and currently all the notification agents use urls and not images directly.

[Pushover 3.0](https://updates.pushover.net/post/170043375237/pushing-images-with-pushover-30)

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests
