### ISSUE TITLE
[BETA] Python fatal error, crashed

### ISSUE THREAD

**Issue by samip5** [Tautulli/Tautulli#1229]
**Version:**
v2.0.14-beta

**Branch:**
beta

**Commit hash:**
45c2ccdffe309eaf734631da1fd1d722f6e6f875

**Operating system:**
Debian 8.10 (Jessie)

**Python version:**
2.7.9

**What you did?**
Tried to execute a another python script to kill a stream based on notification.

**What happened?**
Full application crashed on Python Fatal error, which can't be reproduced.
It's also giving I/O errors.

**What you expected?**
The script to get executed and killed the stream.

**How can we reproduce your issue?**

Use the script from https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_device.py
Set it up as detailed and try to use Plex Web.
This happens

**What are your (relevant) settings?**
PlexPy > Settings > Notification Agents > Scripts > Bell icon:
        [X] Notify on playback start
PlexPy > Settings > Notification Agents > Scripts > Gear icon:
        Playback Start: kill_device.py

**Link to logs:**
http://termbin.com/oioz

**Comment by JonnyWong16** [comment]
What is your thread limit?

```
cat /proc/sys/kernel/threads-max
```

**Comment by samip5** [comment]
@JonnyWong16 
```
cat /proc/sys/kernel/threads-max:

128013
```
