### ISSUE TITLE
[enhancement request] Support (Required) Secure Connections from PMS

### ISSUE THREAD

**Issue by vulcanjedi** [Tautulli/Tautulli#123]
Finally most clients have Secure support with SSL Secure connections on PMS.  Would like to enable however this makes PlexPy fail. Can this be supported?

**Comment by drzoidberg33** [comment]
Is PlexPy running on the same machine as your Plex Server? 

I need to figure out why this is an issue, just on vacation at the moment - finding it tough to get some quiet time to sit down and work so will get to this stuff when I'm back home in 2 weeks.

**Comment by vulcanjedi** [comment]
Enjoy your vacation!
Yeah it took like 6-9 months for IOS update but that was the main holdover so would like to enable.
Sorry no, PMS is ubuntu VM and PlexPy running on its own RasPi at the moment. Same network but different machines. Everything else works great.

**Comment by drzoidberg33** [comment]
It should work, though it's sometimes slow when enabled on the local network.

Could you enable the Force SSL option, then open the home page and then grab your PlexPy log and post it here. Just FYI, Remote Server should not be checked.

**Comment by vulcanjedi** [comment]
Odd. I swear I tried this when I first was playing with PlexPy and migrating over and it didnt work. But it seems to now. Apologies.

**Comment by drzoidberg33** [comment]
It is still however a bit buggy. It is on my to-do list.
