### ISSUE TITLE
[API-Bug] Issues with German characters ä,ü,ö, ...

### ISSUE THREAD

**Issue by memmex** [Tautulli/Tautulli#1231]
Hi,
I am having some problems with the API. I programmed a simple currently watched and recently added 
script for my homepage using Javascript and the API.
At first I was trying to use the provided JSON-objects, but that was not possible due to the Access-Control-Allow-Origin CORS-header. I then switched to JSONP, which is more or less working.

I am using this API-call:
`https://SOMEURL/api/v2?callback=?&apikey=OBFUSCATED&cmd=get_activity`

The call is working sometimes, but in some cases I get the following error:
`500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Powered by CherryPy 5.1.0`

I did some research, what the problem could be. The Tautulli logs printed the following:
`Tautulli APIv2 :: API called with kwargs: {'cmd': u'get_activity', 'callback': u'?', 'apikey': u'********47'}`

`Tautulli APIv2 :: Cleaned kwargs: {}`

`Tautulli APIv2 :: Traceback (most recent call last):
    File "/app/plexpy/plexpy/api2.py", line 563, in _api_out_as
        out = self._api_callback + '(' + out + ');'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1183: ordinal not in range(128)
Traceback (most recent call last):
    File "/app/plexpy/plexpy/api2.py", line 563, in _api_out_as
        out = self._api_callback + '(' + out + ');'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1183: ordinal not in range(128) `

I found some more info using the following API-call, that gives back a xml-object:
`https://SOMEURL/api/v2?callback=?&apikey=OBFUSCATED&out_type=xml&cmd=get_activity`

`XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: https://SOMEURL/api/v2?callback=?&apikey=OBFUSCATED&out_type=xml&cmd=get_activity
Zeile Nr. 40, Spalte 186:			<summary>Jess zieht zu Nick ins Zimmer. Schon die erste Nacht bringt geheime Angewohnheiten ans Licht und erweist sich als echte Belastungsprobe: Sind der Anblick von Nicks nackten F￿`

The mysterious ￿ is the German character "ü".
So the API gives back an error, whenever a "ä,ü,ö, ...." occurs in the JSON. Regarding my media is in German, this happens quit often and sadly makes the API unusable.

**Version:** v2.0.14-beta

**Branch:** beta

**Commit hash:** 45c2ccdffe309eaf734631da1fd1d722f6e6f875

**Operating system:** Docker shiggins8/tautulli, Linux 4.9.0-5-amd64

**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29)  [GCC 6.4.0]

**Comment by JonnyWong16** [comment]
You should be using json instead of jsonp.

**Comment by memmex** [comment]
I am using JSONP because of the missing CORS-header 'Access-Control-Allow-Origin'. Otherwise I can not load the JSON.

The JSONP only is function{JSON}; So it should work as well.

**Comment by JonnyWong16** [comment]
Then you should be changing your API command to the same origin, or allowing the command from a different origin.
