### ISSUE TITLE
PlexPy issues notifications for available updates from the Plex beta channel, even when Plex is configured to use the Public channel

### ISSUE THREAD

**Issue by jtrosper** [Tautulli/Tautulli#1232]
**Version:** 1.4.25

**Branch:** master

**Commit hash:** cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:** Ubuntu Server 16.04 64-bit

**Python version:** 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]

**What you did?** Enabled notifications for available updates for Plex Media Server

**What happened?** PlexPy issues notifications for available updates from the beta channel, even when Plex is configured to update from the Public channel.

**What you expected?** Update notifications from the Public channel only, in accordance with the selected update channel in Plex.

**How can we reproduce your issue?**

1. Install Plex Media Server.
2. Leave Plex set to only receive updates from the Public channel.
3. Configure notifications in PlexPy for updates to Plex.

**What are your (relevant) settings?**

- In Plex - Settings>Server>Update Channel>Public
- In PlexPy - Settings>Notification Agents>Pushover>Notify on Plex update available

**Link to logs:**
- 2018-01-26 21:03:58 - INFO    :: Thread-20 : PlexPy Monitor :: Checking for PMS updates...
- 2018-01-26 21:03:58 - INFO    :: Thread-20 : PlexPy Monitor :: Current PMS version: 1.10.1.4602-f54242b6b
- 2018-01-26 21:03:58 - INFO    :: Thread-20 : PlexPy Monitor :: PMS update available version: 1.11.1.4730-6967ec0b1

**Comment by JonnyWong16** [comment]
The PlexPy notifications have nothing to do with the update channel setting in Plex. It has its own update channel setting.

![image](https://user-images.githubusercontent.com/9099342/35534978-0095eada-04f7-11e8-852c-854a82ecd1ea.png)
