### ISSUE TITLE
[Beta] Crashing and wierd behavior

### ISSUE THREAD

**Issue by samip5** [Tautulli/Tautulli#1233]
**Version:**
v2.0.15-BETA
**Branch:**
Beta
**Commit hash:**
e1e5a050c239543b9edb885518f68efe4550c7fe
**Operating system:**
Debian GNU/Linux 8.10 (jessie)
**Python version:**
2.7.9
**What you did?**
Executed python PlexPy.py and left it running.
**What happened?**
It worked for some time and then started yelling DISK I/O errors.
**What you expected?**
It working without any hickups.
**How can we reproduce your issue?**
Execute it and leave it running simply
**What are your (relevant) settings?**
N/A
**Link to logs:**
https://gist.github.com/samip5/9b4511be0590d095ff9d4dc0c8df9433
http://termbin.com/vuzi

**Thread Limit:**
> cat /proc/sys/kernel/threads-max:
>128013

**Comment by JonnyWong16** [comment]
Duplicate #1229
