### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by Kedryn** [Tautulli/Tautulli#1235]
As reported from others, Telegram agent post 2 messages for every notigification. One is for the image, one for the text. They get messed up when there are multiple notifications at the same time.
Please, use only one post for every poster+text. We know of the missing formatting, but if there is an image, is way worse having those messed than not having bold or italic.

I think the best solution is that if the image option is active, you can tell the user that he will lose formatting. Or you can add an optional checkbox to let have joined or split post for every notification.

But please, as it is now, it is a mess.

**Comment by JonnyWong16** [comment]
And posting multiple times just makes me annoyed and less likely to do anything about it.

#1230

**Comment by Kedryn** [comment]
Sorry, but i thought that adding to a closed issue wont get you updated.
My fault
