### ISSUE TITLE
get_synced_items api is broken since v2.0.16-beta

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli#1236]
**Version:** v2.0.16-beta
**Branch:** beta
**Commit hash:** d15223fb1af4e86297fbfed355f537822ec82f3e
**Operating system:** Linux 4.4.0-112-generic
**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?** Called get_synced_items as described in the [docs](https://github.com/JonnyWong16/plexpy/blob/beta/API.md)
**What happened?** Error occurred
**What you expected?** Api to work as before
**How can we reproduce your issue?**

Seems that the latest beta release broke the get_synced_items api, if I call it like before:
`https://<host>/api/v2?apikey=<apikey>&cmd=get_synced_items&machine_id=<machineid>`
I get an error message:
`{"response": {"message": null, "data": {}, "result": "error"}}`

Logfile shows a warning when calling the api, Tautulli web works as expected.
`WARNING | Unable to retrieve data for get_synced_items.`

**Comment by JonnyWong16** [comment]
Fixed in v2.0.17-beta.

**Comment by tfonfara** [comment]
Confirmed.
