### ISSUE TITLE
API: get_activity does provide wrong media info when transcoding

### ISSUE THREAD

**Issue by AndreasWurm** [Tautulli/Tautulli#1237]
all the media specific attributes of the file that is transcoded:
width, height, audio_codec, container, video_codec..
are not the real values but just identical with their transcode_* counterparts.
My expectation was that its like in the history where you see what the source and the target was.

**Comment by JonnyWong16** [comment]
Issue not filled out properly.

https://github.com/JonnyWong16/plexpy#issues
