### ISSUE TITLE
Discord notifications do not push special symbols properly to api

### ISSUE THREAD

**Issue by Ghent** [Tautulli/Tautulli#1239]
**Version:**
v2.0.16-beta

**Branch:**
beta

**Commit hash:**
d15223fb v2.0.16-beta

**Operating system:**
Linux 4.19 Funtoo

**Python version:**
Python 2.7.13

**What you did?**
Tested via test notification, which worked.
Then tested actual notification and it didn't work.  Greater than/less than symbols were converted to html and thus not parsed by Discord properly.

**What happened?**
https://i.imgur.com/qOEt9Ui.png

**What you expected?**

**How can we reproduce your issue?**

Obtain a Discord ID, you can obtain this by enabling developer options in Discord, right clicking a role or user and copy ID.  Insert this as <@id>.

In test notification, insert ID:
`<@98487282410995712> Test notification`
Test will pass:
Discord output: `@Ghent Test notification`

In text area of actual notification, duplicate entry:
`<@98487282410995712> The Plex Media Server is down.`
Notification will fail:
Discord output: `&lt;@98487282410995712&gt; The Plex Media Server is down.`

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
Fixed in v2.0.17-beta.
