### ISSUE TITLE
Notifier ID increases/is saved even when not saved, or is deleted or closed

### ISSUE THREAD

**Issue by JamminR** [Tautulli/Tautulli#1241]
**Version:**
v2.0.17-beta (has occurred for several weeks since I started testing however)
**Branch:**
nightly
**Commit hash:**
3ca1bd5d78cc9b6c2048ddc9ebac8bf83bda5a40
**Operating system:**
Win10 Pro v1709
**Python version:**
2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
**What you did?**
Cancelled several new notification agent setups
**What happened?**
Noticed that, though I close window or click the delete button before ever saving a notification agent setup, the notifier ID continues to climb, even after a restart of Tautulli
**What you expected?**
The ID not to climb, as the notifier was never setup/saved.
**How can we reproduce your issue?**
Go into Tautulli settings 
1)  Notification Agents 
2)  Add New Notification agent
3) Select Email (I've not tried others)
4) Make note of the Notifier ID
5) Click Delete for that that instance, or Close by clicking X
 5a If X was clicked, it's added anyway, with no details. Go back in and delete.
 5b If Delete is clicked, Confirm.
6) Go to Step 2. 
At step 3 on 2nd go-through, the notifier ID is increased even though no agent was ever intended to be saved.

I attempt to help in the forums. I often go to start a new agent so I can see what other people are seeing.
Though I don't use notifications for anything other than Plex connectivity checking (up/down), I now have about a 10 count on ID, but only have one actual notification agent listed.

Restarting Tautulli has not adjusted - it's still the same number.

**Comment by Arcanemagus** [comment]
That's how database sequences work, you can safely ignore the ID number.

**Comment by JonnyWong16** [comment]
This is the way database IDs are incremented. You can't reuse ID numbers.

**Comment by JamminR** [comment]
Understood, but why should there even be a database count if the original creation is cancelled/not saved.
That is, if I start to create an agent, and click the X at the top right of the window, I'm of the belief and opinion I'm cancelling. No save is ever pressed.
If I start one, leave it incomplete, save, then go back and delete immediately, with no ID numbers/agents created after that one, I believe it should be re-used. I understand if it were in the middle of other IDS, but, again, I repeatedly cancel when viewing.

**Comment by JonnyWong16** [comment]
Because it is created and added to the database as soon as you click a new agent. At that point the number has been "used". 

In the end, it's just a number. There is no difference if it's number 1 or number 1000.
