### ISSUE TITLE
How to clear all images uploaded to imgur.

### ISSUE THREAD

**Issue by nkj2001** [Tautulli/Tautulli#1243]
First of all, thank you for using a great program.

There is one important question.
PlexPy did not write the deletehash value to db when PlexPy uploaded it using the imgur API.
How do I delete that image?
This problem is sensitive.
Of course I did not use the shared Imgur client id.

**Comment by JonnyWong16** [comment]
Unfortunately there is no way to delete the image. You will have to contact Imgur support to have it removed.

I will look into including the `deletehash` in the future.
