### ISSUE TITLE
No discord notification and no watched history

### ISSUE THREAD

**Issue by winbergoscar0** [Tautulli/Tautulli#1244]
**Version:**
 v2.0.17-beta 
**Branch:**
beta
**Commit hash:**
5d2219f2f8bdc249f6489e85319b569f3188d84d
**Operating system:**
Windows Server 2016
**Python version:**
 2.7.13
**What you did?**
Nothing, not done any changes since I installed the new beta
**What happened?**
Tautulli doesn't send notifications to discord when new media has been added, and save watched history
**What you expected?**
Tautulli to send the notification, (Sending a test notification works). And save watched history
**What I've tried?**
Change the notification from slack (using /slack in the discord webhook) to "real" discord webhook
Restart server, restart computer etc
**How can we reproduce your issue?**

**What are your (relevant) settings?**
Notify on Recently Added is checked, it has been working properly since I installed the beta
**Link to logs:**

There is no error when sending the notfication, it never triggers.
Got an error with attempting to reconnect with Plex server, but I can still see who is watching stuffs and the items that gets added in the library is properly seen on the homepage
https://www.dropbox.com/s/6e3ww2q8yt6u4i1/plexpy.log?dl=0
https://gist.github.com/anderssonoscar0/a2245bafbbad91081c5fc281ea2539b3
Also just noticed that, however I can see what users are watching, it never shows up on the history page.
Seems to have broke at 2018-02-03 (Last watched history & last discord notification) 
Can see in the log that `"Failed to process session data: database disk image is malformed."` the 2018-02-02 but even after that I got watched history and discord notifications for another day

**Comment by Arcanemagus** [comment]
> `2018-02-02 00:38:57 - ERROR   :: Thread-3 : Tautulli WebSocket :: Failed to process session data: database disk image is malformed.`

Your log has quite a bit of these entries, I wouldn't be surprised if your database is corrupt. Can you try with an empty database temporarily to see if that clears up the connection issue?

> Got an error with attempting to reconnect with Plex server, but I can still see who is watching stuffs and the items that gets added in the library is properly seen on the homepage

The websocket connection needs to be working for most of the functionality to work.

> Change the notification from slack (using /slack in the discord webhook) to "real" discord webhook
Restart server, restart computer etc

Please use the actual Discord notification agent. Although from this it looks like you _are_ and it is working... ?
```
2018-02-08 17:24:28 - INFO    :: CP Server Thread-8 : Tautulli Notifiers :: Updated notification agent: Discord (notifier_id 4).
2018-02-08 17:24:28 - DEBUG   :: CP Server Thread-8 : Sending test discord notification.
2018-02-08 17:24:28 - INFO    :: CP Server Thread-8 : Tautulli NotificationHandler :: Preparing notifications for notifier_id 4.
2018-02-08 17:24:29 - INFO    :: CP Server Thread-8 : Tautulli Notifiers :: Discord notification sent.
```

**Comment by winbergoscar0** [comment]
Seems to be working with a clean database, actually didn't think (almost) all of these problems would be connected to that. But that seems to be the case.
yeah, tried swapping from the slack notifier to discord (The once you see are the test notifications I tried today)
Should've probably tried a backup of it after finding all the `Disk image is malformed` messages

Everything seems to be working now (Getting history & got notification after adding something)
However the warnings with re-connection to Plex server still exists
[Picture of logs](https://gyazo.com/f1b7573b0f1aa3bc6593af7fdf50a7be) 4x logs every minute

**Comment by JonnyWong16** [comment]
Settings > Extra Settings > Flush temporary sessions.

**Comment by winbergoscar0** [comment]
Thank you @JonnyWong16 @Arcanemagus, Everything works now. Luckily I do backup on backup and got a DB file from a day before it got corrupt! 👍
