### ISSUE TITLE
Tautulli does not keep live tv history

### ISSUE THREAD

**Issue by samwiseg0** [Tautulli/Tautulli#1245]
**Version:**
V2.0.17-BETA

**Branch:**
Beta
**Commit hash:**
5d2219f2f8bdc249f6489e85319b569f3188d84d

**Operating system:**

Linux 3.10.0-693.2.2.el7.x86_64

**Python version:**
2.7.5 

**What you did?**
Played a Live session for X time. Stopped the session. Played a live stream again hours later

**What happened?**
The history of the user does not show the previous live session

**What you expected?**
I expect Tauttilli to keep track of live TV usage. It seems there is only one history item for Live TV.

**How can we reproduce your issue?**
Play a Live session for X time. 
Stop the session.
Played a live stream again hours later

**Comment by JonnyWong16** [comment]
Live TV is not logged.

**Comment by samwiseg0** [comment]
Could it be? Can I request a feature enhancement?
 
 
 
>  
>  
>  
>    
>    
>  
>
