### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Grimshad** [Tautulli/Tautulli#1247]
**Version:**
Tautulli v2.0.17-beta
**Operating system:**
Windows 10
**Python version:**
2.7.14
**What you did?**
Unzipped Tautulli into a folder and ran plexpy.py
**What happened?**
it opened localhost:8181/welcome in my browser which returned a 500 Internal Server error
**What you expected?**
Tautullito load the welcome page to setup Tautulli
**How can we reproduce your issue?**
As described above

**What are your (relevant) settings?**
Default settings

**Link to logs:**
https://pastebin.com/E0pLzmBy

**Comment by JonnyWong16** [comment]
Not searching before posting annoys me.

#1148
#1168
#1203

**Comment by Grimshad** [comment]
Apologies, i did search and i only saw issues for pre v2.
