### ISSUE TITLE
Discord Notifications Missing Poster Artwork

### ISSUE THREAD

**Issue by Fiala06** [Tautulli/Tautulli#1248]
**Version:**
 V2.0.18-BETA
**Branch:**
beta
**Commit hash:**

3a5d5918deb5ce63720a9d47f89e029644f0ef0c

**Operating system:**
Win 10 x64

**Python version:**
2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**What you did?**
Setup Discord Notifications

**What happened?**
Posters don't show up: https://i.imgur.com/8NGd02S.png

**What you expected?**
Posters to show

**How can we reproduce your issue?**

My settings for the Discord Agent are: https://imgur.com/a/pL2ik

**What are your (relevant) settings?**
Above

**Link to logs:**

https://pastebin.com/Q58Z2if3

**Comment by Arcanemagus** [comment]
In the notification settings you have "Upload Posters to Imgur for Notifications" disabled. Since you haven't allowed it to upload any images, you don't have any images showing. 😆

Enable that option, add your Imgur API key, and you should be good to go.

**Comment by Fiala06** [comment]
I’ll try that I suppose. I was under the assumption it would pull from imdb since that was my souce😊 seems wasteful esp since my upload sucks to have to upload images to redownload them for notifications.. they all exist out there already, why reupload them?

**Comment by JonnyWong16** [comment]
Discord cannot access your server.

**Comment by Arcanemagus** [comment]
Because you could have _any_ source for the images, you could even hand draw images for every single episode and set those as the image in Plex if you really wanted. Tautulli has no way of knowing what you have done for the images, so it just asks your Plex server and uses that.

**Comment by Fiala06** [comment]
I understand it’s using the local media profiles now. But why not just link the media from other sources. Like Ombi, sonarr radarr etc does from tmdb or any of the other site. You already have movie link source for descriptions. Just tell it to pull the poster also? 

Just a suggestion. Other than that everythingS been working great! Thanks
