### ISSUE TITLE
Library media info isn't updated properly

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli#1250]
**Version:** v2.0.18-beta
**Branch:** beta
**Commit hash:** 3a5d5918deb5ce63720a9d47f89e029644f0ef0c
**Operating system:** Linux 4.4.0-112-generic
**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?** Configured library refresh as scheduled task. Added new media to library. Waited for next scheduled refresh.
**What happened?** New media was listed in recently added list but not in library media info (neither in the web interface nor in get_library_media_info api call). If I go to library media info in the web interface and trigger the refresh manually using the "refresh media info" button everything works as expected.
**What you expected?** New media to be listed in library media info after the scheduled refresh.
**How can we reproduce your issue?** See description above.

**Comment by JonnyWong16** [comment]
No, the media info tables do not refresh automatically because the API calls to Plex in order to update them are very expensive.

If you are using the `get_library_media_info` API command, then you can add `refresh=true` to the query parameters to update it through the API.

**Comment by tfonfara** [comment]
Got it.

What will be updated in the scheduled task then? The list of libraries itself?

Wouldn't it make sense to offer this option as scheduled task as well (like once a week for example)?

**Comment by JonnyWong16** [comment]
> What will be updated in the scheduled task then? The list of libraries itself?

Yes, and item counts.

> Wouldn't it make sense to offer this option as scheduled task as well (like once a week for example)?

Use a cron task.
