### ISSUE TITLE
Graph Tab | Plays by Period -> over state play count by not grouping plays according to History Tab

### ISSUE THREAD

**Issue by apollolabsai** [Tautulli/Tautulli#1252]
Cross Posting this here as I do not think the Tautulli-Issues is being looked at (this is where all the action is)

Reporting Issues:
 The History tab has an elegant way of grouping successive user's plays into a single entry by enabling the following setting:
"Group successive play history by the same user as a single entry in the tables and **watch statistics**."

This SHOULD carry through to all "watch statistics", but it does not carry through to the the Graph Tab / Plays by Period resulting in significant over stating of the number of plays for a given day / category. 

This is one of the most important features of Tautulli, and I would love for it to be more accurate.

Example:
The below image is from the History Table and groups all these plays into 1:
![image](https://user-images.githubusercontent.com/5577598/36354457-b950a91a-1489-11e8-95c3-e6e871531769.png)

This image is from the Graphs Tab / Plays by Period where each play is counted individually:
![image](https://user-images.githubusercontent.com/5577598/36354474-f68eacd2-1489-11e8-8dce-ad4782bef528.png)

A simple comparison between the History Tab and the Plays by Period tab will allow one to reproduce the issue. I think this is a bug because the setting specifically mentions "watch statistics" which would imply that the setting covers the graphing features. Happy to answer any questions to help solve this.

VERSION V2.0.19-BETA
Git Branch: | beta
Git Commit Hash: | 066a95d2096bbb046ce5e3c3f5a4ab2874394e9c
Platform: | Windows 10
Python Version: | 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]

**Comment by apollolabsai** [comment]
Looks like the latest release has fixed the issue:
Change: Graphs now respect the "Group History" setting.

Have not verified it yet, but THANKS!!!

**Comment by Arcanemagus** [comment]
Yep, this should be fixed in the latest release 😉.
