### ISSUE TITLE
Plexpy Stops Recording User History/Data

### ISSUE THREAD

**Issue by jamesonp** [Tautulli/Tautulli#1253]
I just wanted to document this for anybody having a similar issue and has been unable to solve it.  I am running Ubuntu 17.10 so your mileage may vary with other distros.

Plexpy was working up until a few days ago for me.  Suddenly it stopped recording all user history, logins, etc..  

I would see the following errors in my logs:

`2018-02-18 17:59:55 | DEBUG | PlexPy Pmsconnect :: No library data.`

I spent a few days on this issue and couldn't figure out what was causing until tonight.  Oh a whim I decided to check dmesg, which showed the following logs at about the time I restarted Plexpy each time:

> `[1225395.981049] TCP: request_sock_TCP: Possible SYN flooding on port 8181. Sending cookies.  Check SNMP counters.`
> `[1226084.054167] TCP: request_sock_TCP: Possible SYN flooding on port 8181. Sending cookies.  Check SNMP counters.`
> `[1226782.112719] TCP: request_sock_TCP: Possible SYN flooding on port 8181. Sending cookies.  Check SNMP counters.`

From my understanding, this message caused Plexpy to be unable to connect with Plex and would cause the Pmsconnect issues.  Here's how I solved it:

1) Edit /etc/sysctl.conf

2) Add the following to the bottom of sysctl.conf:

> `net.core.somaxconn = 4096`
> `net.ipv4.tcp_max_syn_backlog = 32765`
> `net.ipv4.tcp_fin_timeout = 30`

3) Issue `sudo sysctl --system` to apply the changes.

4) Restart Plexpy

**Comment by JonnyWong16** [comment]
GitHub issues are for bug reports.

**Comment by jamesonp** [comment]
Wasn't sure where else to document this for others. My apologies.
