### ISSUE TITLE
Cards for Live TV scroll

### ISSUE THREAD

**Issue by psaab** [Tautulli/Tautulli#1254]
See the attached screen shot.  You have to scroll to see the bandwidth

<img width="543" alt="screenshot 2018-02-19 17 12 53" src="https://user-images.githubusercontent.com/196946/36403218-4865c5ae-1598-11e8-9fca-9ae24492a6f0.png">

**Comment by TheMeanCanEHdian** [comment]
This is expected behavior when the stream details force a new line.
