### ISSUE TITLE
NameError: Undefined

### ISSUE THREAD

**Issue by cm86** [Tautulli/Tautulli#1258]
![18-02-24 21-49-47 9010](https://user-images.githubusercontent.com/14919688/36635085-743d4470-19af-11e8-956c-e7378ab945a6.png)

**Branch:**
nightly
**Commit hash:**
cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
**Operating system:**
ubuntuserver 16.04
**Python version:**
2.7.12
**What you did?**
updated to latest version
**What happened?**
can't access the guy anymore

**Link to logs:**
[plexpy.log](plexpy.log)

**Comment by JamminR** [comment]
I was formerly on Nightly and had same. Switched back to beta and now works.
SEEMS that behind the scenes, Tautulli was still recording data properly.
Some collaborating info.

Platform: | Windows 10
Python Version: | 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Title of HTML page states "Mako Runtime Error"

**Comment by JonnyWong16** [comment]
Fixed
