### ISSUE TITLE
Wiki: git repo URL and instructions are out of date

### ISSUE THREAD

**Issue by mobyte0** [Tautulli/Tautulli#1259]
https://github.com/Tautulli/Tautulli/wiki/Installation

Commands call for `https://github.com/JonnyWong16/plexpy.git` when it should be `https://github.com/Tautulli/Tautulli.git`.

Additionally, subsequential instructions should follow this.

**Comment by JonnyWong16** [comment]
The wiki will move to https://github.com/Tautulli/Tautulli-Wiki/wiki/Installation once it is out of beta.

Both git URL will still continue to work because GitHub automatically redirects.

**Comment by mobyte0** [comment]
Ah, didn't realize this. I was inquiring because it prompted me for a login using the old URL when it shouldn't have.

Thanks for your work on the project, cheers.
