### ISSUE TITLE
FreeNAS Jail FreeBSD

### ISSUE THREAD

**Issue by BioRunner** [Tautulli/Tautulli#1260]
Have the latest FreeNAS server OS installed. Have Plex running under a jail. Followed the install instructions found here https://github.com/Tautulli/Tautulli/wiki/Installation for FreeNAS install. When I run the command python2 PlexPy.py I get this error...

Traceback (most recent call last):
	File "PlexPy.py", line 35, in <module>
	  import plexpy
	
	File "/usr/local/share/plexpy/plexpy/__init__.py", line 17, in <module>
	  import sqlite3
	File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
	  from dbapi2 import *

	File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
	  from _sqlite3 import *

ImportError: /usr/local/lib/libsqlite3.so.0: Undefined symbol "fdatasync"

The first time I ran python2 PlexPy.py I did not get the error. I tried to configure PlexPy.py to run on startup, but I was reading the wrong instructions. Anyhow I thought I had messed things up. So I tried to run python2 PlexPy.py again and started getting the above error. I used pkg remove to uninstall all the packages I installed so I could just start over. But I still get the error above. Even after rebooting my jail (after removing all the packages and plexpy folders).

I tried to Google the error but it is such a long error. I could not really find anything.

Thank you for any help on this.

**Comment by BioRunner** [comment]
I should move this to the forums.

**Comment by UnR34L** [comment]
FreeNAS jails seem to be falling behind in versions, I don't know why but here's how you can fix it.

```
portsnap fetch
portsnap extract
cd /usr/ports/databases/sqlite3
make deinstall
make install clean ALLOW_UNSUPPORTED_SYSTEM=true
#Smash the enter button
service plexpy start
```
