### ISSUE TITLE
Email Notifications not working

### ISSUE THREAD

**Issue by mrblack7** [Tautulli/Tautulli#1262]
**Version:**
1.4.25

**Branch:**
master

**Commit hash:**
 cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**Operating system:**
Windows 10

**Python version:**
Python 2.7.13

**What you did?**
Added movies to Plex

**What happened?**
Movies were added in Plex

**What you expected?**
Email notification to be sent out.

**How can we reproduce your issue?**
Add media to Plex

**What are your (relevant) settings?**
smtp.gmail.com
SMTP Port 587

Note: Test Email sends successfully

**Link to logs:**
https://gist.github.com/mrblack7/ef62af145757373cd1c71d63e5f6263b

**Comment by Arcanemagus** [comment]
The issue tracker is for bug reports, support should be done through one of the [support options](http://tautulli.com/#support), thanks! I'd recommend hopping in the `#support` channel on Discord so we can work through this with you.

**Comment by TheMeanCanEHdian** [comment]
Please use the Support channel in [Discord](https://discord.gg/tQcWEUp) for things that are not bug reports.
