### ISSUE TITLE
No 'Toggle Recently Added' button in Tautulli

### ISSUE THREAD

**Issue by emreuenal** [Tautulli/Tautulli#1265]
**Version:** V2.0.20-BETA

Hi,

is that changed [how to disable recently added notifications](https://github.com/Tautulli/Tautulli/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q3) for certain users and libraries?

v1:
![image](https://user-images.githubusercontent.com/6360198/37040442-21f4a9ee-215a-11e8-96e0-93b7c91f6d41.png)

V2:
![image](https://user-images.githubusercontent.com/6360198/37040461-301f8566-215a-11e8-8c43-05b287f96577.png)

**Comment by TheMeanCanEHdian** [comment]
Use the conditions tab under the notification agent you want to restrict.
