### ISSUE TITLE
Pushover Priority 2 Fails

### ISSUE THREAD

**Issue by deed02392** [Tautulli/Tautulli#1266]
Configure a pushover notifier. Confirm the settings work with priority set to 0 or 1. They fail with bad request if you try 2.

**Comment by TheMeanCanEHdian** [comment]
Please provide your logs corresponding to the failed test.

**Comment by Arcanemagus** [comment]
From [the documentation](https://pushover.net/api#priority) it looks like priority 2 is only meant to be an emergency priority and has additional requirements when sending messages with this priority.

**Comment by JonnyWong16** [comment]
Fixed in v2.0.22-beta.
