### ISSUE TITLE
No poster image in email notifications

### ISSUE THREAD

**Issue by jjbmetal** [Tautulli/Tautulli#1269]
For an email notification, I have "Enable HTML Support" checked and all the HTML seems to be working fine, except the poster image.

I have used the line suggested from the FAQ and saw listed in another issue, but all I get is a blank box with no image.
`<img src="{poster_url}" height="225" width="150">`

I also saw the below in the FAQ, and so I do not have this option checked as I am using email notifications.

> Posters are only available for notification agents which have the "Include Poster Image" option in the settings, with the exception of Email.

**Comment by Arcanemagus** [comment]
It sounds like you haven't enabled Imgur upload of the images in the settings.

Issues aren't the place for support requests, if the above isn't enough to get it working please use one of the support options available on [the website](http://tautulli.com/#support), I'd recommend Discord as it's the easiest to troubleshoot things on 😉.
