### ISSUE TITLE
Notification tags not working

### ISSUE THREAD

**Issue by psitem** [Tautulli/Tautulli#1272]
**Version:** 2.0.22

**Branch:** master

**Commit hash:** a08bce2073b1847762a22a843b13acc5f996d9cb

**Operating system:** Windows Server 2016

**Python version:** 2.7.11

**What you did?** Set recently added notification for Discord with tv / movie tags.

`<tv>**{show_name} S{season_num00}E{episode_num00} {episode_name}**</tv><movie>**{title}**</movie>`

**What happened?** Notification was posted as `<tv> S00E00 Star Wars: The Last Jedi</tv>Star Wars: The Last Jedi`

**What you expected?** A notification like `Star Wars: The Last Jedi`

This was working as expected under my very old version of PlexPy using the Slack agent.

**Comment by JonnyWong16** [comment]
There is no `<tv>` tag anymore. Please read the changelogs and the new help window in the UI.
