### ISSUE TITLE
Tautulli Database :: Database error: no such column: notifier_id

### ISSUE THREAD

**Issue by dhcrees** [Tautulli/Tautulli#1273]
Just updated my version (was PlexPy) and now I get the following error every 4 seconds in the logs.

Tautulli Database :: Database error: no such column: notifier_id

Tried the standard stuff, like a restart, but nothings worked..

Any ideas/help would be much appreciated.

**Comment by JonnyWong16** [comment]
GitHub issues are not for bug reports, not support. Please use our [Discord Server](https://discord.gg/tQcWEUp) for support.

Try restoring a backup of your database.
