### ISSUE TITLE
Bandwidth Totals Include Paused Streams

### ISSUE THREAD

**Issue by kyse** [Tautulli/Tautulli#1274]
**Version:**
V2.0.22
**Branch:**
master
**Commit hash:**
a08bce2073b1847762a22a843b13acc5f996d9cb
**Operating system:**
Ubuntu 17.10
**Python version:**
2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
**What you did?**
Open main webpage and review activity header regarding bandwidth.
**What happened?**
Compared bandwidth to actual stream's.
**What you expected?**
Bandwidth from a paused stream shouldn't be included in total bandwidth in summary header.
**How can we reproduce your issue?**
Start a stream in plex, pause it.
Start another stream in plex against same server on different client.
View Tautulli main page.
**What are your (relevant) settings?**
N/A
**Link to logs:**
N/A

**Comment by TheMeanCanEHdian** [comment]
We are using the [Plex Streaming Brain](https://support.plex.tv/articles/227715247-server-settings-bandwidth-and-transcoding-limits/) for this information. 

It considers the bandwidth of paused streams when calculating upload limits, etc.
