### ISSUE TITLE
I Pressed Update on old Plexpy and Now Tautulli is Stuck on Signing In

### ISSUE THREAD

**Issue by jeff15110168** [Tautulli/Tautulli#1275]
**Version:**
Tautulli (latest update?)

**Branch:**
unsure

**Operating system:**
Windows 10

**Python version:**

**What you did?**
Plexpy had a notification inside the website that I was ~700 commits behind. I updated Plexpy and it seemed to have updated the whole platform to Tautulli.

**What happened?**
At first, localhost:8181 and my port forwarded server wasn't working at all. I went into plexpy folder and manually clicked the PlexPy.py (I notice there's also "tautulli.py" in the folder too now?)

**What you expected?**
The tautulli login page shows up at localhost:8181 but the sign in page is stuck when I use my old credentials.

**Comment by Arcanemagus** [comment]
You can try [resetting the password](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q3), if that doesn't work can you please [post your logs](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#q-where-can-i-find-my-tautulli-logs)? Thanks!

**Comment by jeff15110168** [comment]
I restarted and ended the python exe and re-launched the tautulli.py and was able to login.

I noticed that I lost all my user data in the history and graphs section - is this an issue? this was one of the more valuable things i had in my old plexpy setup which is why I didn't want to use the beta.

How can I make tautulli launch at startup now hidden? I had a plexpy.pyw file setup previously that I believe let plexpy launch in the background. I need to make sure both are not trying to launch now.

**Comment by JonnyWong16** [comment]
Using a `PlexPy.pyw` file was never a supported method of launching PlexPy. I'm not surprised that that would be causing you issues. Please use the correct methods outlined in the wiki page. https://github.com/Tautulli/Tautulli-Wiki/wiki/Install-as-a-daemon

Tautulli probably doesn't have correct permissions to rename the `plexpy.db` file to `tautulli.db`. You can manually rename it (or restore one of the backup databases to `tautulli.db`).

**Comment by jeff15110168** [comment]
awesome. fixed it by using an old backup from plexpy backup folder and renaming it to "tautulli". May want to quickly note in the FAQ that to restore backups / configs from old plexpy installation, all you need to do is go into backup folder and rename the latest plexpy backup into "tautulli.db" and "config.ini" if something has gone wrong.

Last question - what can i cleanup in the hierarchy of files in the installation folder so that I don't have redundancy from old plexpy legacy files?

![image](https://user-images.githubusercontent.com/9892738/37249589-93feb87a-24b8-11e8-90be-0cd98628d2d6.png)

**Comment by JonnyWong16** [comment]
Don't touch the files. Leave everything where it is.

**Comment by jeff15110168** [comment]
okay thanks. so i just leave the "plexpy.py" and "plexpy.pyw" there and it shouldn't interfere with what I assume to be tautulli.py as the master executable? Just want to make sure no issues come up again in terms of legacy compatibility if it does make any sense to delete the old plexpy.py.

**Comment by JonnyWong16** [comment]
Don't use the `.pyw` file like I mentioned above.

**Comment by jeff15110168** [comment]
thanks jonny, appreciate the tremendous effort that went into this. really incredible software.
