### ISSUE TITLE
MEDIA_CAPTION_TOO_LONG error for Telegram when poster is enabled

### ISSUE THREAD

**Issue by enchained** [Tautulli/Tautulli#1276]
**Version:**
v2.0.22

**What you did?**
Added summary and genres to the notification template.

**What happened?**
Notifications fail with this error in the logs:
`Tautulli Notifiers :: Request response: {"ok":false,"error_code":400,"description":"Bad Request: MEDIA_CAPTION_TOO_LONG"}`

One solution that comes to mind is to sent it as a separate message when total text length > 200 chars.

**Comment by JonnyWong16** [comment]
Please use the proper repository for bug reports.

https://github.com/Tautulli/Tautulli-Issues
