### ISSUE TITLE
Search is case sensitive for cyrillic symbols/russian language

### ISSUE THREAD

**Issue by enchained** [Tautulli/Tautulli#1277]
**Version:**
v2.0.22

**Operating system:**
linuxserver docker container

**What you did?**
Entered `сделано` (lowercase с) into the history search filter or global filter etc

**What happened?**
No results

**What you expected?**
`Сделано в Америке` movie history entry should appear, just as it correctly happens when I enter `Сделано` (uppercase С).

**Comment by JonnyWong16** [comment]
Please use the proper repository for bug reports.

https://github.com/Tautulli/Tautulli-Issues
