### ISSUE TITLE
Systemd daemon script for Ubuntu 15.04

### ISSUE THREAD

**Issue by artbird309** [Tautulli/Tautulli#128]
I was trying to set PlexPy up on my Ubuntu 15.04 server that now uses Systemd not upstart anymore and there was not a daemon script so I mashed together the init.fedora.centos.systemd (which is also set up weird) and the init.ubuntu.

This is the process I used to create the daemon it might not be the best but seems to be working for me and if correct it can be included in the wiki and files.
- Add user

```
cd /opt/plexpy/scripts/
sudo adduser --system --no-create-home plexpy
sudo chown plexpy:nogroup -R /opt/plexpy
```
- plexpy.service file for Systemd

```
sudo nano plexpy.service
**Paste plexpy.service file below into editor and exit and save
```

```
# PlexPy
#
# Service Unit file for systemd system manager
#
# INSTALLATION NOTES
#
#   1. Rename this file as you want, ensuring that it ends in .service
#       e.g. 'plexpy.service'
#
#   2. Adjust configuration settings as required.  More details in the
#      "CONFIGURATION NOTES" section shown below.
#
#   3. Copy this file into your systemd service unit directory, which is
#      often '/lib/systemd/system'.
#
#   4. Create any files/directories that you specified back in step #2.
#       e.g. '/etc/plexpy/plexpy.ini'
#            '/home/sabnzbd/.plexpy'
#
#   5. Enable boot-time autostart with the following commands:
#       systemctl daemon-reload
#       systemctl enable plexpy.service
#
#   6. Start now with the following command:
#       systemctl start plexpy.service
#
#   7. If troubleshooting startup-errors, start by checking permissions
#      and ownership on the files/directories that you created in step #4.
#
#
# CONFIGURATION NOTES
#
#    - The example settings in this file assume that:
#       1. You will run PlexPy as user/group: sabnzbd.sabnzbd
#       2. You will either have PlexPy installed as a subdirectory
#          under '~sabnzbd', or that you will have a symlink under
#          '~/sabnzbd' pointing to your PlexPy install dir.
#       3. Your PlexPy data directory and configuration file will be
#          in separate locations from your PlexPy install dir, to
#          simplify updates.
#           
#    - Option names (e.g. ExecStart=, Type=) appear to be case-sensitive)
#
#    - Adjust ExecStart= to point to:
#       1. Your PlexPy executable,
#       2. Your config file (recommended is to put it somewhere in /etc)
#       3. Your datadir (recommended is to NOT put it in your PlexPy exec dir)
#
#    - Adjust User= and Group= to the user/group you want PlexPy to run as.
#
#    - WantedBy= specifies which target (i.e. runlevel) to start PlexPy for.
#        multi-user.target equates to runlevel 3 (multi-user text mode)
#        graphical.target  equates to runlevel 5 (multi-user X11 graphical mode)

[Unit]
Description=PlexPy

[Service]
ExecStart=/opt/plexpy/PlexPy.py --quiet --daemon --nolaunch --config /opt/plexpy/config.ini --datadir /opt/plexpy
GuessMainPID=no
Type=forking
User=plexpy
Group=nogroup

[Install]
WantedBy=multi-user.target
```

**Comment by drzoidberg33** [comment]
I'll have to look into this when I get back home. These have been cloned from the Headphones repo, so I just assumed they worked.

**Comment by drzoidberg33** [comment]
Added into latest commit.

**Comment by crediblebytes** [comment]
Just a heads up in the documentation it recommends: 

>  2. Your config file (recommended is to put it somewhere in /etc)

But if you do this after following the directions your plexpy user will not have permissions to write to that config file in that location (/etc). So just put the config file inside the opt/plexpy folder as it is later configured to do so anyways inside the systemd service file:

> ExecStart=/opt/plexpy/PlexPy.py --quiet --daemon --nolaunch --config /opt/plexpy/config.ini --datadir /opt/plexpy

 Will save someone an hour of debugging if we can update the documentation and remove this suggestion.

**Comment by JonnyWong16** [comment]
The recommendation is there so that you can easily delete the PlexPy install folder (`/opt/plexpy`) and reinstall without losing your settings.

**Comment by crediblebytes** [comment]
@JonnyWong16 I understand the reason behind putting it into another folder but we are lacking some proper instruction in the documentation for it to work properly if someone does place it elsewhere. (i.e. the systemd service file needs to be updated to proper location)
