### ISSUE TITLE
Database error: ambiguous column name: id // Unable to execute database query.

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#129]
Hi, I updated an hour ago and since then I get database errors. I though okay maybe something went wrong while updating so I "reinstalled" plexpy but the problems are still there.
The overall History view is working fine.

**User History**
The user profil overview shows the latest watched episodes but under history I get _No matching records found_.

**Episode History**
Example Rick and Morty S02E05 (still on the server), if I click on the episode I get a popup saying:

_DataTables warning: table id=history_table - Unable to execute database query._ 

and a second one

_DataTables warning: table id=history_table - Requested unknown parameter 'date' for row 0. For more information about this error, please see http://datatables.net/tn/4_

**Putty output for the episode overvie**
_24-Aug-2015 09:32:42 - ERROR :: CP Server Thread-9 : Database error: ambiguous column name: id
24-Aug-2015 09:32:42 - WARNING :: CP Server Thread-9 : Unable to execute database query._

Tried it on another server with the same outcome.

Debian 8.1
Python 2.7.9
Plex Server 0.9.12.9

**Comment by JonnyWong16** [comment]
@lewsidaniel See #109.

**Comment by ghost** [comment]
Thanks.
