### ISSUE TITLE
Missing platform icon

### ISSUE THREAD

**Issue by parzival84** [Tautulli/Tautulli#13]
Just a heads up, the server seems to be missing the platform icon for Xbox. PlexPy just shows a broken image icon. The Plex Server does have an icon for it. Thanks!

**Comment by drzoidberg33** [comment]
Thanks! Will add it in a coming commit.

**Comment by drzoidberg33** [comment]
Fixed in https://github.com/drzoidberg33/plexpy/commit/dd90f2e37595d33b527622207e9e2e50da54913b

Please check and re-open the issue if it's not fixed, I can't test as I don't know what the X-box device name is exactly.
