### ISSUE TITLE
Feature request: start day of week

### ISSUE THREAD

**Issue by malle-pietje** [Tautulli/Tautulli#130]
Thanks for all the great work on PlexPy: love it!
One small request: would it be possible to add an option to select the start day of the week? Here in the Netherlands for example we consider Monday to be the start instead of Sunday. Afaik this only reflects in the " Play count by day of week" graph.

**Comment by elRadix** [comment]
- 1

maybe could be added in the extra setting tab to change the start day to Monday

**Comment by drzoidberg33** [comment]
It's actually just using the default for Sqlite. Monday is also the 1st day of the week for me, but not for Sqlite:

As per https://www.sqlite.org/lang_datefunc.html:

> > The "weekday" modifier advances the date forward to the next date where the weekday number is N. Sunday is 0, Monday is 1, and so forth.

I can change the function to swap the days, just didn't think most people would care about this.

**Comment by malle-pietje** [comment]
indeed not a big deal, but it's nice if the weekend show ups on the right. Just what I'm used to ;-)

**Comment by swordh** [comment]
This would be a nice little feature

**Comment by JonnyWong16** [comment]
Added in v1.4.17.
