### ISSUE TITLE
HDPi posters on the history page.

### ISSUE THREAD

**Issue by Swiftnesses** [Tautulli/Tautulli#131]
Please increase the quality of the poster pop-ups.

Thank you for a great tool!

**Comment by Swiftnesses** [comment]
Also the star ratings...

**Comment by JonnyWong16** [comment]
HDPI thumbnails added in #126.

I cam currently updating all the info pages. The star ratings will be fixed in that update.

**Comment by drzoidberg33** [comment]
Closing. Added in 1.1.5.

**Comment by Swiftnesses** [comment]
The stars still look @1x?

**Comment by JonnyWong16** [comment]
Stars should be updated when #140 is merged.
