### ISSUE TITLE
[Feature] Transcode speed & throttled status listed in activity pane.

### ISSUE THREAD

**Issue by Absentee23** [Tautulli/Tautulli#133]
It'd be great to see the transcode speed and whether the transcode is throttled or not in the activity panel, whenever a file is being transcoded. 

You can get this info from _/transcode/sessions_. A speed of 1 means it is transcoding in real time, lower and it is not transcoding fast enough.

It's be _amazing_ to have these things logged and graphed, possibly relative/linked to the type of files being transcoded.

Thanks! :)

**Comment by zobe123** [comment]
love this +1

**Comment by majora2007** [comment]
I think this would also be a great feature. +1

**Comment by Swiftnesses** [comment]
+1

**Comment by zenjabba** [comment]
+1

**Comment by rickcab1** [comment]
+1

**Comment by drzoidberg33** [comment]
This is now available on the activity pane. Logging this kind of thing is not really practical though.
