### ISSUE TITLE
PlexPy Pushover API Token over limit.

### ISSUE THREAD

**Issue by jgsawyers** [Tautulli/Tautulli#135]
I noticed that i recently stopped reciving alerts from PlexPy via Pushover. Running a call to the Pushover API manually (using the default PlexPy token) returns:

`{"token":"invalid","errors":["application has exceeded current limit of 7500 messages"],"status":0,"request":"da6f716af8ff80212fa82444993b412e"}`

Using a self-generated token does work without issue. Just a heads up that it looks like the default token is hitting the 7500 message limit. 

Thanks!

**Comment by HitsvilleUK** [comment]
Yeah I mentioned it yesterday on the Plex Forums without realising it was actually brought up there a few days ago that it is indeed hitting the limit and to use a self generated token.

**Comment by drzoidberg33** [comment]
It's not really a bug, Pushover only allows 7500 notifications per month on a free account. Additional capacity is crazy expensive.

You can create your own app token, and I will attempt to get the PlexPy app clonable for ease of use. Here was my original post on this: https://forums.plex.tv/discussion/comment/1001166/#Comment_1001166
