### ISSUE TITLE
[Request] Uptime Feature

### ISSUE THREAD

**Issue by majora2007** [Tautulli/Tautulli#137]
I think it would be really awesome to have uptime shown through stats. Something like, Server has been up for last X days, Y hours. Thoughts?

**Comment by rickcab1** [comment]
+1

**Comment by JamminR** [comment]
This might be a good request to combine with #175

**Comment by Magikarplvl4** [comment]
+1

**Comment by Arcanemagus** [comment]
Duplicate of http://feathub.com/drzoidberg33/plexpy/+16.

(From the looks of it @JonnyWong16 just copied this over there, but regardless that is where feature requests are handled for this project.)
