### ISSUE TITLE
Support auto update when running as a service

### ISSUE THREAD

**Issue by Eds1989** [Tautulli/Tautulli#1390]
**Is your feature request related to a problem? Please describe.**
When auto update is enabled, and Tautulli is running as a service, the updater does not currently stop the running service, so cannot proceed to update

**Describe the solution you'd like**
I'd like to see the updater stop the service before running the update

**Describe alternatives you've considered**
Simply stopping the service after the update starts and actioning the warning message. Not ideal, require manual intervention

**Additional context**
N/A

**Comment by JonnyWong16** [comment]
What operating system?

* All Linux installs (Snap or git) can auto-update without issues when running as a service.
* Docker container don't have auto-updating features since updates are handled by Docker and not the container.
* The MacOS package doesn't have auto-updating features.
* The Windows exe auto-updater was removed in v2.6.7 and won't be added back due to it being flagged by antivirus software.

**Comment by Eds1989** [comment]
Sorry, it would be on Windows.
Can the auto updater not be left as an option, and admins can just add exceptions for the updater executable? I'd rather do that than have to stop the service, run an update and start the service again.

**Comment by JonnyWong16** [comment]
No, just including the updater in the exe triggers antivirus software. It's not dependent on whether or not you enable the feature or not.

It is not worth leaving it in for the few people that can add exceptions vs the 10s of thousands of people that use the installer. I do not have the time to spend on submitting every update to every antivirus software as a false positive, nor the time to spend answering the numerous support issues that arise from it.

Sorry, but I am marking this issue as `wont-fix`.

**Comment by Eds1989** [comment]
No problem.
Would an alternative be for the main installer to check for a Tautulli service, and stop it as part of the install? That would at least make updates a one click affair?

**Comment by JonnyWong16** [comment]
There is no official Tautulli service. Tautulli doesn't run as a service on Windows so any service you are using must be managed on your own.

Your best option of probably writing a script to download and run the installer when there is an update. You can trigger the script using the notification agents.

**Comment by Eds1989** [comment]
Might be beyond my capabilities, but I'll take a crack at it ta!

**Comment by reloxx13** [comment]
the missing auto update sucks so hard since there r so many updates, almost daily/weekly. thank you idiots who cannot add an exception.

**Comment by reloxx13** [comment]
@Eds1989 add it as a scheduled task, create a .CMD file which stats tutulli and create a scheduled task for it.   
    
`Start C:\Python36\pythonw36.exe "S:\Program Files\Tautulli\Tautulli.py"`

And use the pyton installation method for auto updates.

**Comment by vanowm** [comment]
I'm using Windows 10 built-in antivirus and I've never seen it's complaining about Tau...if it's other antivirus software that complaining, than your estimates of "10s of thousands" is way out of proportion, since majority of people don't install additional antiviruses...

**Comment by samwiseg0** [comment]
> I'm using Windows 10 built-in antivirus and I've never seen it's complaining about Tau...if it's other antivirus software that complaining, than your estimates of "10s of thousands" is way out of proportion, since majority of people don't install additional antiviruses...

We had many many many reports. Unfortunately, the decision stands for now. If you have any further questions please use discord
 
 
Thanks
