### ISSUE TITLE
Recently added websocket attempts to retrieve metadata before it is available on the Plex server

### ISSUE THREAD

**Issue by rg9400** [Tautulli/Tautulli#1392]
**Describe the Bug**
Using the new TV agent on PMS version 1.22.0.4163, Recently Added notifications from Tautulli are only being sent intermittently. It seems to only pick up around 20% of the items. Movie notifications work perfectly as before. Tautulli logs indicate they cannot find the metadata for the RatingKey when these notifications fail. The Recently Added section on Tautulli seems to be accurate.

Per Swift,  it might be related to Tautulli being too fast and trying to grab data before the new agent has fully set up the new episode.

**Steps to Reproduce**
1. Set up a library on Plex using the new Plex TV Agent (Beta)
2. Set up notifications for items that were Recently Added to this library
3. Add new episodes to this library
4. Verify that notifications were sent for each episode

**Expected Behavior**
Tautulli should properly send Recently Added notifications for new episodes using the new agent

**Relevant Settings**
- Plex URL (in Docker as well) http://plex:32400
- Recently Added Notification Delay: 60
- Group Notifications by TV Show enabled

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.6.6] 2.6.8
- Git Branch: [eg. master] nightly
- Git Commit Hash: [eg. 2cc5bf812fe05e0666aeaeb37ed550c59816fb4c] a2f661df0d8b92c4af65d63721e7fbc642276f06
- Platform and Version: [eg. Windows 10] Docker (tautulli/tautulli:nightly) running on Windows using WSL2 backend
- Python Version: [e.g. 3.8.8] 3.8.8 (default, Feb 19 2021, 18:07:06) [GCC 8.3.0]

**Link to logs (required)**
Tautulli Logs: https://pastebin.com/pKEwaGxU
Plex Websocket Logs: https://pastebin.com/S8R3U9rn

Correct RatingKeys: 124303, 124304, 123405, 123406

**Comment by costaht** [comment]
I reported it on Discord two days ago I think, but I didn't want to be annoying and just assumed the problem was my Plex server.
Here's the error I get immediately after adding a new episode:
```
2021-03-13 01:41:31 | WARNING | Tautulli Pmsconnect :: Unable to parse XML for get_metadata_details: 'NoneType' object has no attribute 'getElementsByTagName'.
2021-03-13 01:41:31 | ERROR | Failed to access uri endpoint /library/metadata/60816. Status code 404 Client Error: Not Found for url: http://192.168.1.20:32400/library/metadata/60816
```
Honestly, I'm glad someone influent on the group has had the same issue :)

**Comment by alfgut** [comment]
I am having the exact same issue. Any workaround until it gets fixed up?

**Comment by Nomelas** [comment]
Also experiencing this same behavior - i guess the workaround would be to switch back to the old plex agent

**Comment by dhaos21** [comment]
I wonder if it is a fix within tautulli or within plex itself considering it is a beta agent.

**Comment by costaht** [comment]
I ran some tests adding 4 new episodes to different shows and all notifications seem to be working again

Running nightly commit hash: 73496c5075211d914eb12592358fd51e29e7a5ba
