### ISSUE TITLE
cannot import name 'HTTPSHandler'; Tautulli fails to start

### ISSUE THREAD

**Issue by nojohnny101** [Tautulli/Tautulli#1394]
**Describe the Bug**
I have Tautulli in a TrueNAS iocage jail and it has been flawless up until today. I noticed that Tautulli was not working so I went to start it manually and it printed the below stacktrace. 

**Steps to Reproduce**
1. Execute `service tautulli start` within a iocage jail
2. See error

**Expected Behavior**
Tautulli starting

**Screenshots**
Provide screenshots to help explain your problem.

**Relevant Settings**
NA

**Tautulli and System Info (see Tautulli settings page)**
- LATEST
- Git Branch: master
- TrueNAS 12.0-U2.1
- Iocage 12.2-RELEASE p4
- Python Version: 3.7

**Link to logs (required)**
(can't get logs because it won't start)

Here is the stack trace:
```
Starting tautulli.
Traceback (most recent call last):
  File "/usr/local/share/Tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/usr/local/share/Tautulli/plexpy/__init__.py", line 37, in <module>
    from UniversalAnalytics import Tracker
  File "/usr/local/share/Tautulli/lib/UniversalAnalytics/__init__.py", line 1, in <module>
    from . import Tracker
  File "/usr/local/share/Tautulli/lib/UniversalAnalytics/Tracker.py", line 2, in <module>
    from future.moves.urllib.request import Request, HTTPSHandler
ImportError: cannot import name 'HTTPSHandler' from 'future.moves.urllib.request' (/usr/local/share/Tautulli/lib/future/moves/urllib/request.py)
/usr/local/etc/rc.d/tautulli: WARNING: failed to start tautulli
```
Let me know if you need anything else, willing to help.

**Comment by JonnyWong16** [comment]
Please provide complete logs from your `tautulli.log` file.

https://github.com/Tautulli/Tautulli/wiki/Asking-for-Support#how-can-i-share-my-logs

**Comment by nojohnny101** [comment]
Thanks for the quick reply. I'm trying to find the log file within the install, but can't find it. I found a directory called "Tautulli" located here `/usr/local/share/Tautulli` but it doesn't contain a logs file.

**Comment by JonnyWong16** [comment]
If you installed according to our installation wiki then it would be located in `/usr/local/share/Tautulli/logs`. I don't know where the data would be located if you used the TrueNAS plugin. You might be able to find the `datadir` using the `sysrc -a` command.

**Comment by nojohnny101** [comment]
I did not use the plugin, it is a self install via the git clone method outlined under TrueNAS. Here is a screenshot inside the `Tautulli` directory:
https://share.getcloudapp.com/yAu657q8

**Comment by nojohnny101** [comment]
Ok found the logs, they were located at `/root/config/logs/` from within the iocage jail.

Here they are: [download here](https://www.dropbox.com/s/vlxory5mnbcmrvg/tautulli-logs.txt?dl=0)

Unfortunately I don't think you'll find much, looking at the logs it doesn't show any of my attempts to start the service. Last logs it has was when it was working and I don't see anything in the tail of the logs to indicate why it stopped. But I might have missed something.

**Comment by JonnyWong16** [comment]
Try running `/usr/local/share/Tautulli/contrib/clean_pyc.sh`.

If that doesn't work try deleting `/usr/local/share/Tautulli` and reinstalling. Your data should be safe since it's in a completely different folder.

**Comment by nojohnny101** [comment]
Thanks. First command didn't fix, re-install did. All data was retained as you stated.

If you do have a suspicion of why it was all of a sudden missing that library, I'm curious and would like you to share. If not no big deal, I'm back up and running

**Comment by JonnyWong16** [comment]
I don't know how your libraries got messed up.

**Comment by nojohnny101** [comment]
Fair enough, thanks.
