### ISSUE TITLE
Tautulli and its Uninstaller blocked in Cortex and Bkav Pro

### ISSUE THREAD

**Issue by ZaphodJustSomeGuy** [Tautulli/Tautulli#1397]
I've noticed in the last couple of updates (where I've switched from the Python version to Windows exe), that both the uninstaller and Tautulli trigger the malware protection with PaloAlto's Cortex AV, and according to totalvirus.com it's the same with Bkav Pro.

Now these realtime malware engines are looking for what it deems malicious activity rather than relying on known pattern matches.  More sophisticated than the heuristic engines of old, but they still trigger false positives and usually on homebrew code.

On this latest version (2.6.10), I found the wildfire report to be a little worrying.  Wildfire is the secondary pass on "Cortex Prevent", which copies the .exe up to a sandbox in their cloud and runs it against several environments which have honey traps and other typical user files lying around.

I'm attaching the automated wildfire report for the uninstaller, as this is the one that worries me.  It is 77 pages long as it tests against 3 different environments.  Normally with false positives this is like 5-10 pages long.
[global-verdict-report (2).pdf](https://github.com/Tautulli/Tautulli/files/6163029/global-verdict-report.2.pdf)

The Tautulli.exe itself gets blocked by the local realtime engine, but after its run through wildfire it is cleared as benign.  I won't bother posting the wildfire report for that as it has nothing of concern in it.

So are you doing something different with the uninstaller than with other Windows apps?  I'm no expert in understanding the Windows installer wrappers, but maybe you are using one that isn't typically used?

**Comment by JonnyWong16** [comment]
It's a standard [NSIS](https://nsis.sourceforge.io/Main_Page) installer/uninstaller. It doesn't touch any user files.

You can view the source code here:
https://github.com/Tautulli/Tautulli/blob/master/package/Tautulli.nsi
