### ISSUE TITLE
Feature Request - Option to configure Statistic Past Days on Home Page

### ISSUE THREAD

**Issue by nomadore** [Tautulli/Tautulli#14]
I would like to request field in the options to specify the number of days for the Statistics on the home page.  It is currently hardcoded to 30 days but I personally would like to set it to 7 days to have more dynamic data.

Thank you

**Comment by drzoidberg33** [comment]
This has been pushed to the dev branch, will be available on next release in master.

**Comment by nomadore** [comment]
Thank you for this, I just donated!

**Comment by drzoidberg33** [comment]
Thanks @nomadore! Much appreciated.
