### ISSUE TITLE
Constant disk activity when a stream is active

### ISSUE THREAD

**Issue by smiba** [Tautulli/Tautulli#1401]
**Describe the Bug**
When one stream is running (paused or not) Tautulli accesses the disk once a second (SQLite & log file). This creates this very annoying ritmic ticking of the hard drives every second which gets on my nerves. Also this leads to increased power draw and possibly wear on the drives.

**Steps to Reproduce**
1. Have stream open in Plex, have Tautulli running
2. Enjoy your clock ticking, your hard drives will make noise on the second

**Expected Behavior**
Less disk interactions, either keep it in memory or write-cache it somewhere.

**Screenshots**
I don't think screenshots are relevant, but I do have the output of truss on FreeBSD to show its behaviour (this repeats every second). These are in the log section

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.6.10
- Git Branch: master
- Git Commit Hash: 53121adfee474402e49d07b725dcf78285ef88c0
- Platform and Version: FreeNAS 11.2-U8, FreeBSD 11.2
- Python Version: 3.7.10
- Browser and Version: Not related

**Link to logs (required)**
https://gist.github.com/smiba/2ceabb8b027ba35754474a1a43cc7369 (Truss)
https://gist.github.com/smiba/e30ea565626ea83d53138d88aeaaa896 (plex_websocket.log)
https://gist.github.com/smiba/6491ef97a853dff03322f88509a522ce (tautulli.log)

**Comment by samwiseg0** [comment]
I am not sure what you want here? This is entirely normal for an application that is logging to a database and keeping a log file? The data has to be stored somewhere. I am sure Tautulli is not the only application that has a log file on your system?

**Comment by smiba** [comment]
It didn't used to do this, I'm not sure what changed. I updated Tautulli a few days ago.
(Either that or I didn't notice it before, plex is not being used too often)

The log file is most likely being cached by the system, so I don't worry about that. The SQLite likely does cause the multiple drive head movements.
If nothing can be done about it feel free to close, although I wouldn't mind seeing something that would limit the amount of seperate write calls

**Comment by ggscott** [comment]
This feels like expected behavior for the application

If you don’t want the disk sync ticking; move the logging to a ram based file system, then create a sync point of your own.

**Comment by samwiseg0** [comment]
> It didn't used to do this, I'm not sure what changed. I updated Tautulli a few days ago.

Can you roll back to the previous version that you were running and see if the issue persists?
