### ISSUE TITLE
macOS - Tautulli .pkg "Installation Failed"

### ISSUE THREAD

**Issue by poiromaniax** [Tautulli/Tautulli#1402]
Hi there,

I am upgrading to v2.6.10.0 using the .pkg as referenced in the Wiki (because of Python)

The installer fails and Tautulli does not start
When attempting to start Tautulli by clicking on the icon in Applications (tailing the system log) I get:
`com.apple.xpc.launchd[1] (com.Tautulli.Tautulli.43172[1961]): Service exited with abnormal code: 255`

macOS 10.13.6

EDIT

Tried to use the 2.6.9 package and it also failed.
Installer Log:

`Mar 29 14:15:48 unifi Installer[4816]: @(#)PROGRAM:Install  PROJECT:Install-1000
Mar 29 14:15:48 unifi Installer[4816]: @(#)PROGRAM:Installer  PROJECT:Installer-920
Mar 29 14:15:48 unifi Installer[4816]: Hardware: Macmini5,3 @ 2.00 GHz (x 8), 8192 MB RAM
Mar 29 14:15:48 unifi Installer[4816]: Running OS Build: Mac OS X 10.13.6 (17G14042)
Mar 29 14:15:48 unifi Installer[4816]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Mar 29 14:15:48 unifi Installer[4816]: Env: TMPDIR=/var/folders/y0/jkj6t03s3tv7n6xwpbd12cl00000gn/T/
Mar 29 14:15:48 unifi Installer[4816]: Env: HOME=/Users/arielgeffen
Mar 29 14:15:48 unifi Installer[4816]: Env: SHELL=/bin/bash
Mar 29 14:15:48 unifi Installer[4816]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.nuddyaUqRL/Render
Mar 29 14:15:48 unifi Installer[4816]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.LSTOqmj7YJ/Listeners
Mar 29 14:15:48 unifi Installer[4816]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Mar 29 14:15:48 unifi Installer[4816]: Env: LOGNAME=arielgeffen
Mar 29 14:15:48 unifi Installer[4816]: Env: XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000003.Installer
Mar 29 14:15:48 unifi Installer[4816]: Env: COMMAND_MODE=unix2003
Mar 29 14:15:48 unifi Installer[4816]: Env: USER=arielgeffen
Mar 29 14:15:48 unifi Installer[4816]: Env: XPC_FLAGS=0x0
Mar 29 14:15:48 unifi Installer[4816]: Tautulli-macos-v2.6.9-x64  Installation Log
Mar 29 14:15:48 unifi Installer[4816]: Opened from: /Users/arielgeffen/Downloads/Tautulli-macos-v2.6.9-x64.pkg
Mar 29 14:15:48 unifi Installer[4816]: Referenced component packages (1) trustLevel=100
Mar 29 14:15:48 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=15371=0x3c0b expectedThread=8459=0x210b
Mar 29 14:15:48 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=15371=0x3c0b expectedThread=8459=0x210b
Mar 29 14:15:48 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=15371=0x3c0b expectedThread=8459=0x210b
Mar 29 14:15:48 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=15371=0x3c0b expectedThread=8459=0x210b
Mar 29 14:15:48 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=15371=0x3c0b expectedThread=8459=0x210b
Mar 29 14:15:48 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=15371=0x3c0b expectedThread=8459=0x210b
Mar 29 14:15:48 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=15371=0x3c0b expectedThread=8459=0x210b
Mar 29 14:15:48 unifi system_installd[659]: PackageKit: Install sandbox purging reclaimed Zero KB
Mar 29 14:15:50 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:50 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:50 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:50 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:50 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:50 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:50 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22023=0x5607 expectedThread=8459=0x210b
Mar 29 14:15:51 unifi Installer[4816]: InstallerStatusNotifications plugin loaded
Mar 29 14:15:53 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:53 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:53 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:53 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:53 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:53 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=43271=0xa907 expectedThread=8459=0x210b
Mar 29 14:15:54 unifi Installer[4816]: Administrator authorization granted.
Mar 29 14:15:54 unifi Installer[4816]: ================================================================================
Mar 29 14:15:54 unifi Installer[4816]: User picked Standard Install
Mar 29 14:15:54 unifi Installer[4816]: Choices selected for installation:
Mar 29 14:15:54 unifi Installer[4816]: 	Install: "Tautulli-macos-v2.6.9-x64"
Mar 29 14:15:54 unifi Installer[4816]: 		Tautulli-macos-v2.6.9-x64.pkg : com.Tautulli.Tautulli : 2.6.9
Mar 29 14:15:54 unifi Installer[4816]: ================================================================================
Mar 29 14:15:54 unifi Installer[4816]: It took 0.00 seconds to summarize the package selections.
Mar 29 14:15:54 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22791=0x5907 expectedThread=8459=0x210b
Mar 29 14:15:54 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22791=0x5907 expectedThread=8459=0x210b
Mar 29 14:15:54 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22791=0x5907 expectedThread=8459=0x210b
Mar 29 14:15:54 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22791=0x5907 expectedThread=8459=0x210b
Mar 29 14:15:54 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22791=0x5907 expectedThread=8459=0x210b
Mar 29 14:15:54 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22791=0x5907 expectedThread=8459=0x210b
Mar 29 14:15:54 unifi deleted[405]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=22791=0x5907 expectedThread=8459=0x210b
Mar 29 14:15:54 unifi Installer[4816]: -[IFPKGDerivedDocument sortedPackageLocations]: result = (
	    "file://localhost"
	)
Mar 29 14:15:54 unifi Installer[4816]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Mar 29 14:15:54 unifi Installer[4816]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/arielgeffen/Downloads/Tautulli-macos-v2.6.9-x64.pkg
Mar 29 14:15:54 unifi Installer[4816]: Set authorization level to root for session
Mar 29 14:15:54 unifi Installer[4816]: Will use PK session
Mar 29 14:15:54 unifi Installer[4816]: Using authorization level of root for IFPKInstallElement
Mar 29 14:15:54 unifi Installer[4816]: Starting installation:
Mar 29 14:15:54 unifi Installer[4816]: Configuring volume "Macintosh HD"
Mar 29 14:15:54 unifi Installer[4816]: Preparing disk for local booted install.
Mar 29 14:15:54 unifi Installer[4816]: Free space on "Macintosh HD": 184.71 GB (184706015232 bytes).
Mar 29 14:15:54 unifi Installer[4816]: Create temporary directory "/var/folders/y0/jkj6t03s3tv7n6xwpbd12cl00000gn/T//Install.4816XxBbi9"
Mar 29 14:15:54 unifi Installer[4816]: IFPKInstallElement (1 packages)
Mar 29 14:15:54 unifi Installer[4816]: Current Path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Mar 29 14:15:54 unifi installd[657]: PackageKit: Adding client PKInstallDaemonClient pid=4816, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Mar 29 14:15:54 unifi Installer[4816]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Mar 29 14:15:54 unifi installd[657]: PackageKit: ----- Begin install -----
Mar 29 14:15:54 unifi installd[657]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Mar 29 14:15:54 unifi installd[657]: PackageKit: packages=(
	    "PKLeopardPackage <id=com.Tautulli.Tautulli, version=2.6.9, url=file://localhost/Users/arielgeffen/Downloads/Tautulli-macos-v2.6.9-x64.pkg>"
	)
Mar 29 14:15:54 unifi installd[657]: PackageKit: Extracting file://localhost/Users/arielgeffen/Downloads/Tautulli-macos-v2.6.9-x64.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/2430155E-4B17-4E9E-8527-ED1322AC6429.activeSandbox/Root/Applications, uid=0)
Mar 29 14:15:55 unifi installd[657]: PackageKit: prevent user idle system sleep
Mar 29 14:15:55 unifi installd[657]: PackageKit: suspending backupd
Mar 29 14:15:55 unifi installd[657]: PackageKit (package_script_service): Preparing to execute script "./preinstall" in /private/tmp/PKInstallSandbox.QD4Ose/Scripts/com.Tautulli.Tautulli.3EcfjN
Mar 29 14:15:55 unifi package_script_service[672]: PackageKit: Executing script "preinstall" in /tmp/PKInstallSandbox.QD4Ose/Scripts/com.Tautulli.Tautulli.3EcfjN
Mar 29 14:15:55 unifi install_monitor[4830]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Mar 29 14:15:55 unifi installd[657]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/2430155E-4B17-4E9E-8527-ED1322AC6429.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/2430155E-4B17-4E9E-8527-ED1322AC6429.activeSandbox
Mar 29 14:15:55 unifi installd[657]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/2430155E-4B17-4E9E-8527-ED1322AC6429.activeSandbox/Root (1 items) to /
Mar 29 14:15:55 unifi installd[657]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.QD4Ose/Scripts/com.Tautulli.Tautulli.3EcfjN
Mar 29 14:15:55 unifi package_script_service[672]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.QD4Ose/Scripts/com.Tautulli.Tautulli.3EcfjN
Mar 29 14:15:57 unifi package_script_service[672]: ./postinstall: LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Tautulli.app.
Mar 29 14:15:57 unifi install_monitor[4830]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Mar 29 14:15:58 unifi installd[657]: PackageKit: releasing backupd
Mar 29 14:15:58 unifi installd[657]: PackageKit: allow user idle system sleep
Mar 29 14:15:58 unifi installd[657]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Tautulli-macos-v2.6.9-x64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/arielgeffen/Downloads/Tautulli-macos-v2.6.9-x64.pkg, PKInstallPackageIdentifier=com.Tautulli.Tautulli, NSLocalizedDescription=An error occurred while running scripts from the package “Tautulli-macos-v2.6.9-x64.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cTautulli-macos-v2.6.9-x64.pkg\U201d.";
	    NSURL = "file://localhost/Users/arielgeffen/Downloads/Tautulli-macos-v2.6.9-x64.pkg";
	    PKInstallPackageIdentifier = "com.Tautulli.Tautulli";
	}
Mar 29 14:15:58 unifi installd[657]: PackageKit: Running idle tasks
Mar 29 14:15:58 unifi Installer[4816]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Tautulli-macos-v2.6.9-x64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/arielgeffen/Downloads/Tautulli-macos-v2.6.9-x64.pkg, PKInstallPackageIdentifier=com.Tautulli.Tautulli, NSLocalizedDescription=An error occurred while running scripts from the package “Tautulli-macos-v2.6.9-x64.pkg”.}
Mar 29 14:15:58 unifi installd[657]: PackageKit: Removing client PKInstallDaemonClient pid=4816, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Mar 29 14:15:58 unifi installd[657]: PackageKit: Done with sandbox removals
Mar 29 14:15:58 unifi Installer[4816]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Mar 29 14:15:58 unifi Installer[4816]: IFDInstallController 3350 state = 8
Mar 29 14:15:58 unifi Installer[4816]: Displaying 'Install Failed' UI.
Mar 29 14:15:58 unifi Installer[4816]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
`

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli/wiki/Installation#macos

> * Note: The `.pkg` installer requires macOS 10.14 (Mojave) or newer. For macOS 10.13 (High Sierra) and older please use the alternate installation instructions below.
