### ISSUE TITLE
Failed command "get_pms_token" -> request() got an unexpected keyword argument 'encode_multipart'

### ISSUE THREAD

**Issue by James-S-Thrasher** [Tautulli/Tautulli#1406]
**Describe the Bug**
A returned string with PMS token.

**Steps to Reproduce**
1. send GET request with command "get_pms_token"

**Expected Behavior**

**Screenshots**
<img width="404" alt="Screen Shot 2021-04-10 at 17 22 43" src="https://user-images.githubusercontent.com/2694500/114285205-5e350d00-9a23-11eb-971a-36bcc8c9e2d3.png">
<img width="1604" alt="Screen Shot 2021-04-10 at 17 23 53" src="https://user-images.githubusercontent.com/2694500/114285206-5e350d00-9a23-11eb-8444-0935e63fd4aa.png">

**Tautulli and System Info (see Tautulli settings page)**

Git Branch: | master
Git Commit Hash: | v2.6.10
Configuration File: | /config/config.ini
Database File: | /config/tautulli.db \| Status
Log File: | /config/logs/tautulli.log
Backup Directory: | /config/backups
Cache Directory: | /config/cache
Export Directory: | /config/exports
Newsletter Directory: | /config/newsletters
Arguments: | ['--datadir', '/config']
Platform: | [Docker] Linux 5.10.21-Unraid (#1 SMP Sun Mar 7 13:39:02 PST 2021)
System Timezone: | America/New_York (UTC-0400)
Python Version: | 3.8.8 (default, Mar 15 2021, 13:10:14) [GCC 10.2.1 20201203]

**Link to logs (required)**
https://gist.github.com/HH0718/c5d32d85c8135eaae0574ebba71be7c5

**Comment by JonnyWong16** [comment]
I think the `get_pms_token` API command should be deprecated. You should be retrieving a Plex token directly from Plex.tv instead of passing credentials through Tautulli.

**Comment by James-S-Thrasher** [comment]
> I think the `get_pms_token` API command should be deprecated. You should be retrieving a Plex token directly from Plex.tv instead of passing credentials through Tautulli.

Thanks for the prompt response.

Can you clarify:

You think it should be depreciated or it is and shouldn't be available (documentation needs to be updated)?

Thanks!

**Comment by JonnyWong16** [comment]
It's broken, but I don't plan on fixing it.

**Comment by James-S-Thrasher** [comment]
> It's broken, but I don't plan on fixing it.

Thank you for the response.

and thank for the amazing work.
