### ISSUE TITLE
Library section ID not cast to int for collections, playlists, and exporter after PlexAPI 4.5.2 upgrade

### ISSUE THREAD

**Issue by Jerome2103** [Tautulli/Tautulli#1408]
**Describe the Bug**
The collections are no longer loaded since the latest update.

**Steps to Reproduce**
1. Go to 'libraries'
2. Click on 'Movie'
3. Click on 'Collections'

**Expected Behavior**
Showed collections

**Tautulli and System Info (see Tautulli settings page)**
- Version: V2.7.0
- Git Branch:  master
- Git Commit Hash: c780f1fd6c57763bd0e39253ffc55be2618050ea

**Link to logs**
Logs removed

**Comment by Jerome2103** [comment]
When will it appear?

**Comment by samwiseg0** [comment]
> When will it appear?

In the next major release. ie v2.7.1

**Comment by Jerome2103** [comment]
Yes, But when will it come?

**Comment by samwiseg0** [comment]
> Yes, But when will it come?

We do not give ETAs on releases. Typically there are releases every ~30+ days. Please do not use issues for these types of inquires. In the future please use one of our support methods. https://github.com/Tautulli/Tautulli/wiki/Asking-for-Support
