### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by Jerome2103** [Tautulli/Tautulli#1410]
**Describe the Bug**
Export Error
If I want to make an export on the library level, nothing happens. but if I make the export on a film or series, it works perfectly.
Same error at the user level

**Steps to Reproduce**

1. Go to 'libraries'
2. Click on 'Movie'
3. Click on 'Export'

**Tautulli and System Info (see Tautulli settings page)**
- Version: V2.7.0
- Git Branch: master
- Git Commit Hash: c780f1fd6c57763bd0e39253ffc55be2618050ea
- 

**Link to logs (required)**
[tautulli.log](https://github.com/Tautulli/Tautulli/files/6303600/tautulli.log)

**Comment by JonnyWong16** [comment]
Duplicate #1408.
