### ISSUE TITLE
Search is case sensitive for cyrillic symbols/russian language

### ISSUE THREAD

**Issue by enchained** [Tautulli/Tautulli#1411]
**Describe the Bug**
Search is case sensitive for cyrillic symbols/russian language. I have to try both uppercase and lowercase variants if I want to find something.

**Steps to Reproduce**
1. In Plex rename any movie title to Russian with mixed case, i.e. `Лига справедливости Зака Снайдера`
2. Start to watch it until it scrobbles to the Tautulli history.
3. Open the History page.
4. Try searching `лига`, it won't work, but `Лига` will work.

**Expected Behavior**
Search should be case insensitive.

**Relevant Settings**
Plex Library that contains affected items has its language set to Russian.

**Tautulli and System Info**
- Version: v2.7.0
- Git Branch: master
- Platform and Version: linuxserver.io docker, latest tag
- Python Version: 3.8.8
- Browser and Version: Chrome 89.0.4389.114

**Link to logs (required)**
The search doesn't log itself as far as I can tell.

**Comment by JonnyWong16** [comment]
This is a limitation with SQLite, it only supports case-insensitive search for ASCII characters.

https://sqlite.org/faq.html#q18

This likely won't be fixed because I am not going to compile my own SQLite with ICU extensions.
