### ISSUE TITLE
Homepage library showed as 'None' or 'Plex Media'

### ISSUE THREAD

**Issue by keliansb** [Tautulli/Tautulli#1413]
**Describe the Bug**
On the homepage, under the MOST ACTIVE LIBRARIES section, I can see a library displayed as 'None' (see first screenshot below). On the Libraries page this 'None' library is not displayed, it's just on the homepage.
Don't know if it's related but for some users (my admin user doesn't have this issue) the media name and cover are not displayed. They are displayed as 'Plex Media' (see the second screenshot below).

**Steps to Reproduce**
1. Go to Tautulli homepage
2. Click on the 'None' library
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/22099779/114987384-6531a480-9e95-11eb-9b89-d5cbc7decb6f.png)
![image](https://user-images.githubusercontent.com/22099779/114989987-5b5d7080-9e98-11eb-9631-ca24f5ca10df.png)

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.7.0
- Git Branch: master
- Git Commit Hash: v2.7.0
- Platform and Version: [Docker] Linux 3.10.0-1160.21.1.el7.x86_64
- Python Version: 3.8.8
- Browser and Version: Firefox 87.0

**Link to logs (required)**
I suspect the related error is this one :
```
Traceback (most recent call last):
  File "/app/tautulli/lib/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/app/tautulli/lib/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/app/tautulli/lib/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/tautulli/lib/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/tautulli/plexpy/webserve.py", line 4650, in pms_image_proxy
    return self.real_pms_image_proxy(**kwargs)
  File "/app/tautulli/plexpy/helpers.py", line 83, in wrapper
    return function(*args, **kwargs)
  File "/app/tautulli/plexpy/webserve.py", line 4709, in real_pms_image_proxy
    img_rating_key = img_split[rating_key_idx]
IndexError: list index out of range
```
[Link to full logs](https://gist.github.com/CaptAintHere/14e8bc8b7d7dc847ec85bc09f67fdbfe)

**Comment by JonnyWong16** [comment]
Already solved in this thread:

https://reddit.com/r/Tautulli/comments/mq4ge4/databaselibrary_errors/

**Comment by keliansb** [comment]
Thanks, provided solution worked for both issues ('None' library and 'Plex Media' items)
