### ISSUE TITLE
Show total watch time on show or movie page

### ISSUE THREAD

**Issue by JoshNotWright** [Tautulli/Tautulli#1417]
**Is your feature request related to a problem? Please describe.**
If a show isn't in my top 10, there's no easy way for me to see how much it's been viewed

**Describe the solution you'd like**
It would be nice if the page for a show or movie showed Last 24 hours, Last 7 days, Last 30 days, All Time, like shown on an individual user's page

**Describe alternatives you've considered**
As of now I can get a rough estimate by changing the timeframe for the watch statistics (usually if a show is newer)

**Comment by herby2212** [comment]
You can get the All Time plays in the media info section of the corresponding library down to a per episode base. Just as a tip.
