### ISSUE TITLE
Memory Leak on TrueNas Core

### ISSUE THREAD

**Issue by Jon87** [Tautulli/Tautulli#1419]
**Describe the Bug**
There still seems to be a memory leak issue, Tautulli slowly creeps up the amount of memory it's using. I've been running about 5 days now and am over 9GB

**Steps to Reproduce**
1. Standard install on TrueNas Core in a jail
2. Start Tautulli
3. Leave running.

**Expected Behavior**
Lower and consistent memory use

**Screenshots**
![image](https://user-images.githubusercontent.com/22343326/115361568-9cb39000-a1b8-11eb-9c04-8b21b685e180.png)

**Link to logs (required)**
https://gist.github.com/Jon87/58a8d66214103ba7a37f1763f64a006f

Tautulli version: 2.7.0
Git Branch: | master
-- | --
Git Commit Hash: | c780f1fd6c57763bd0e39253ffc55be2618050ea
Arguments: | ['--daemon', '--pidfile', '/usr/local/share/Tautulli/tautulli.pid', '--quiet', '--nolaunch']
Platform: | FreeBSD 12.2-RELEASE-p6 (FreeBSD 12.2-RELEASE-p6 f2858df162b(HEAD) TRUENAS - FreeBSD 12.2)
System Timezone: | local (UTC+0100)
Python Version: | 3.7.10 (default, Mar 2 2021, 01:19:31) [Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611a

**Comment by JonnyWong16** [comment]
I have not been able to reproduce this.

**Comment by Jon87** [comment]
It does seem to be worse if tautulli has started with the jail after a server reboot.
If I stop the service and restart it manually without restarting the jail the memory use seems to still creep up, but it takes a lot longer.
Current use is around 4gb after 14 days uptime following me bouncing the service.

Let me know if you want me to collect any other info... My library is fairly large and I've been using tautulli for a few years now, something to do with the database maybe?

Thanks for the help!

**Comment by JonnyWong16** [comment]
Does the problem still occur on the latest version v2.7.2? And upload new logs when the problem occurs again.

**Comment by Jon87** [comment]
Ah, it seems auto update has pulled me to 2.7.2. so I'm not actually sure how long the service has been running now.

I'll check in the morning (UK time) and upload new logs and current memory usage.

**Comment by Jon87** [comment]
New log;
https://gist.github.com/Jon87/0f5033597e9d2d386b68135135f9dcdd

Running 2.7.2 current memory use around 4gb;

![image](https://user-images.githubusercontent.com/22343326/117137707-054a6180-ada2-11eb-8bba-c3afdd3b3d29.png)

**Comment by drinking12many** [comment]
I too have encountered this. I have seen it using as much as 13GB of RAM causing other jails to run out of memory etc. As recently as yesterday with both the current version of tautulli and Freenas 12 U4. I currently have IOCAGE attempting to limit it to 4GB, but I only made the change yesterday so I don't know if it will work... at current its still below 4GB usually it took a few days for mine to show huge growth in usage.

**Comment by drinking12many** [comment]
As a note, I tried adding some media (4-5 CDS) to my server to see what happened after I scanned it that's when it seemed to blow the memory usage up it went from a few hundred MBs to 4GB physical/8GB virtual. It may even have something to do with the amount of media I have. 
![image](https://user-images.githubusercontent.com/34074305/120831569-abb68d80-c52d-11eb-8586-681a9ec111eb.png)

**Comment by drinking12many** [comment]
Added a few more CDs usage jumped up even more. There is nothing I can see in the logs about errors etc but I can include them if needed. 
![image](https://user-images.githubusercontent.com/34074305/120836120-377ee880-c533-11eb-8739-b2dd29e343f4.png)

**Comment by JonnyWong16** [comment]
I run Tautulli on TrueNAS-12.0-U3 (jail is 12.2-RELEASE-p6) and I have not been able to reproduce this. Maybe my database is not large enough or my Plex server is not as active. I have no idea what is causing this. It doesn't seem to happen on other operating systems.

**Comment by Jon87** [comment]
I'm not sure if my library is that big but it would be interesting to compare and contrast as I'm not sure.

I've got around 700 movies and around 13,000 TV episodes. Users is pretty small, 2 or 3 regular with a couple of extras who occasionally watch. 

Happy to upload my database of it'd be of help? I'll see if I can find the database size for you tomorrow. I wondered if it was the age of the database, I've been a long time user so my oldest entry in history is over 4 years ago?

Many thanks again though for this great software. I hope this is helpful.

**Comment by Jon87** [comment]
Interesting comment around adding media though. Happy to pause all my media adds, bounce the service and monitor for a few days to see if causes the memory to stay low if it'd help?

**Comment by Jon87** [comment]
My database is around 54Mb. What's a normal sort of range for this? How much memory would you normally expect Tautulli to consume?

**Comment by drinking12many** [comment]
I have arount 750 movies, 3800 TV episodes and 22K songs. For reference on items.  My Tautulli DB is about 53MB or so. I didn't really add any new media this weekend maybe 3-4 items and memory usage is below.

![image](https://user-images.githubusercontent.com/34074305/121024320-1b1cbf00-c772-11eb-80b4-d199c868aec8.png)

**Comment by SteffanLong** [comment]
**![image](https://user-images.githubusercontent.com/5157291/123497357-ecac3a00-d5e1-11eb-80c2-e6357f430f33.png)**

I'm currently running Tautulli v2.7.4 and the current memory usage is sitting at 27GB. Tautulli database is 210MB.
[tautulli.log](https://gist.github.com/SteffanLong/489b963226755d475443d194cdc8d4fe)

| | |
| --- | --- |
| Git Branch | master |
| Git Commit Hash | 9476897527899927f19d467b57c3247bd76e8512 |
| Arguments | ['--datadir', '/mnt/config', '--daemon', '--pidfile', '/usr/local/share/Tautulli/tautulli.pid', '--quiet', '--nolaunch', '--datadir', '/mnt/config'] |
| Platform | FreeBSD 12.2-RELEASE-p6 (FreeBSD 12.2-RELEASE-p6 facd5d71c97(HEAD) TRUENAS - FreeBSD 12.2) |
| Python Version | 3.7.10 (default, Mar 27 2021, 01:23:30) [Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611a |

**Comment by JonnyWong16** [comment]
I still have no idea what is causing this.
