### ISSUE TITLE
export is missing episode-number

### ISSUE THREAD

**Issue by snickers2k** [Tautulli/Tautulli#1423]
don't know if this is really a bug or a feature-request.. but feels like a bug 

**Describe the Bug**
export file is missing episode-number

**Steps to Reproduce**
export, look for episode number 

**Expected Behavior**
find an episode number in export file

**Screenshots**
hmpf

**Relevant Settings**
highest export level

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.7.2

**Link to logs (required)**
[tautulli.log](https://github.com/Tautulli/Tautulli/files/6394473/tautulli.log)

**Comment by JonnyWong16** [comment]
Please provide logs. Logs show everything Tautulli is doing for the export which will show if there is a bug.

**Comment by snickers2k** [comment]
done.
so it should export the episode-number ? like S01E01 ? because thats definitely missing

**Comment by JonnyWong16** [comment]
Season and episode numbers are there.

Season number: `seasons.index`
Episode number: `seasons.episodes.index`

**Comment by snickers2k** [comment]
O_o still can't find it in export .xml :/
and the guys from filebot can't neither .. https://www.filebot.net/forums/viewtopic.php?t=5378&f=5&sid=a7a6c1cf4161aa7959d70a9b990dfbee#p54437

[Library - Spielshows - All [63].txt](https://github.com/Tautulli/Tautulli/files/6394758/Library.-.Spielshows.-.All.63.txt)
 .xml > .txt because of github restrictions.

**Comment by snickers2k** [comment]
oh... i guess now i found it ... it's not S01E01 style, but only Season 1 on "Season-Layer" and Episode 1 on "Episode-Layer" , right ? 
 would it be possible to have this for every single episode in style of S01E01 ? thanks

**Comment by JonnyWong16** [comment]
It's in the XML you posted. `CTRL+F` `index`.

**Comment by snickers2k** [comment]
O_o
for me searching "S12E03" for example only shows the one in the filename itself O_o :/

**Comment by JonnyWong16** [comment]
I have no idea what you are doing.

![image](https://user-images.githubusercontent.com/9099342/116472761-30c1cf00-a82b-11eb-8781-ec507d1665e8.png)

**Comment by snickers2k** [comment]
okay... had no clue what that index thing meant. sorry.
i guess the guys from filebot expect something like S01E01 .. written exactly that way ... :/ because thats the way filebot looks for a episode-id ..

so then its more a feature-request i guess ..

**Comment by JonnyWong16** [comment]
It's called `index` in the Plex API. There is no `S01E01` format because Plex doesn't provide that in their API (XML).

https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

Closing this issue, not a bug.

**Comment by snickers2k** [comment]
my bad. sorry and thank you
