### ISSUE TITLE
Missing job arg for recently added queue modal

### ISSUE THREAD

**Issue by Jerome2103** [Tautulli/Tautulli#1429]
**Describe the Bug**
No output when a item is in waitinglist

**Steps to Reproduce**
1. Go to 'Setings'
2. Click on 'Check for recently added items'
3. See error

**Expected Behavior**

**Screenshots**
Provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/27641713/117259534-6af42780-ae4e-11eb-8909-f99c363335df.png)

**Tautulli and System Info (see Tautulli settings page)**
- Version: V2.7.2
- Git Branch: master
- Git Commit Hash:  39ad3f9047fb3f8ed7b18b1584b079a70280d37b
- Python Version: 3.8.8

**Link to logs (required)**
Include a link to your **FULL** logs (not just a few lines) on [Gist](http://gist.github.com).
https://gist.github.com/Jerome2103/85d9d41669e0982295d485d52b864a0d

**Comment by JonnyWong16** [comment]
> Include a link to your FULL logs (not just a few lines) on Gist.

Logs must be uploaded to gist. We will not download attachments.

**Comment by samwiseg0** [comment]
Also make sure its your **complete** log and not just a small section or snip.

**Comment by Jerome2103** [comment]
Thats is the full log.
I have cleared the log, in the morning.

**Comment by Jerome2103** [comment]
updated, this is the full log, because i cleared in the morning
