### ISSUE TITLE
Unexpected api changes with edit_user

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli#1432]
**Describe the Bug**
`edit_user` modifies optional parameters, even if they are not set.

**Steps to Reproduce**
1. Enable "Keep history" and "Allow guest access" for a user
2. Call `edit_user` api with the user id and friendly name
3. Check user details
4. "Keep history" and "Allow guest access" are both disabled

**Expected Behavior**
The api should not touch values that are optional.

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.7.2
- Git Branch: beta
- Git Commit Hash: 39ad3f9047fb3f8ed7b18b1584b079a70280d37b
- Platform and Version: [Docker] Linux 4.15.0-142-generic
- Python Version: 3.8.8 (default, Feb 19 2021, 18:07:06) [GCC 8.3.0]
- Browser and Version: Chrome 90

**Comment by JonnyWong16** [comment]
The API docs should actually be fixed since the way it's coded those are required parameters, not optional.
