### ISSUE TITLE
Notification agents - get remaining time in seconds

### ISSUE THREAD

**Issue by ATypescriptEnjoyer** [Tautulli/Tautulli#1434]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but the duration remaining in minutes is pretty inaccurate and seconds would be a lot more accurate

**Describe the solution you'd like**
A new parameter that got the remaining duration in seconds would be really awesome.

**Describe alternatives you've considered**
At the moment, i'm just using the minutes remaining, but it ends up being off by up to 50 seconds

**Additional context**
i've tried {remaining_time} and {remaining_duration} but they're both pretty inaccurate, if seconds isn't possible via plex, then thats fine, it'd just be a nice parameter is all :)

**Comment by samwiseg0** [comment]
Can you describe what you are trying to do? There maybe another option but there does not seem to be a clear picture of what you are trying to accomplish?

**Comment by ATypescriptEnjoyer** [comment]
I use the tautulli notifications to show on discord what im currently watching and how long it has left, at the moment i just use minutes remaining as time remaining, project is here https://github.com/SashaRyder/Plex-Discord-Rich-Presence
