### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 26: invalid continuation byte

### ISSUE THREAD

**Issue by KoRnEr007** [Tautulli/Tautulli#1437]
**Describe the Bug**
I have this error and my notification is not send

**Steps to Reproduce**
Define notification:

![image](https://user-images.githubusercontent.com/44002636/118817160-356e2600-b8b3-11eb-9cbf-746bba1b1e96.png)

![image](https://user-images.githubusercontent.com/44002636/118817232-49b22300-b8b3-11eb-8442-62bc400a74a4.png)

Argument:
`--jbop stream --username {username} --sessionId {session_id} --killMessage 'Transcoding streams are not allowed for 4K content (Yours: {stream_bitrate}). Contact the Plex admin for help.'`

**Expected Behavior**
The notification is not sent and i have this issue on logs:

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
- Version: [V2.7.2]
- Git Branch: [eg. master]
- Git Commit Hash: [eg. 2cc5bf812fe05e0666aeaeb37ed550c59816fb4c]
- Platform and Version: [10]
- Python Version: [3.9.5
- Browser and Version: [Chrome 90.0.4430.212]

**Link to logs (required)**
Include a link to your **FULL** logs (not just a few lines) on [Gist](http://gist.github.com).
https://gist.github.com/KoRnEr007/d0a79d722b1c1ee860502cefb1ff60c0

**Comment by samwiseg0** [comment]
@KoRnEr007 you must provide _full logs_ not just a snip. Please re upload your entire log.

**Comment by KoRnEr007** [comment]
Done
