### ISSUE TITLE
Search icon/feature missing on mobile browsers

### ISSUE THREAD

**Issue by Kryptonit3** [Tautulli/Tautulli#1446]
**Is your feature request related to a problem? Please describe.**

search icon and feature works fine and fully visible on a desktop browser but disappears when desktop browser is resized smaller or when using a mobile phone browser. 

**Describe the solution you'd like**

change CSS to allow search icon and functions to work on mobile browsers. 

**Describe alternatives you've considered**

Go grab my laptop?

**Additional context**

Using linuxserver/tautulli:latest docker image which is using V2.2.0. Unaware if this has been addressed in a later release.

**Comment by samwiseg0** [comment]
@Kryptonit3 As a side note you should really update as that version is well over a year old.

**Comment by Kryptonit3** [comment]
> @Kryptonit3 As a side note you should really update as that version is well over a year old.

Thanks. Switched to linuxserver/tautulli:develop docker image which is using V2.7.3. 

Still no mobile search.

**Comment by JonnyWong16** [comment]
You *should not* be using the develop/nightly branch unless you are actually developing.

**Comment by Kryptonit3** [comment]
> You _should not_ be using the develop/nightly branch unless you are actually developing.

Using the latest tag on dockerhub only had my container at V2.2.0 (rebuilt container and selected pull latest image) so not sure where the happy medium is?

**Comment by JonnyWong16** [comment]
This is becoming off-topic and has nothing to do with your original feature request. GitHub issues is not the place for support. Please use the [Discord Server](https://tautulli.com/discord) if you need help updating.

**Comment by Kryptonit3** [comment]
> This is becoming off-topic and has nothing to do with your original feature request. GitHub issues is not the place for support. Please use the [Discord Server](https://tautulli.com/discord) if you need help updating.

I didn’t drag us off topic. My issue is still persistent.

**Comment by Kryptonit3** [comment]
![image](https://user-images.githubusercontent.com/72818445/120940883-87a1aa80-c6ed-11eb-9c2d-e177e8b87d2c.png)

This appears to be the culprit. A hidden class on the list element. `hidden-sm hidden-xs`. Removing both of those classes bring back the search in the navigation.
