### ISSUE TITLE
Install-as-a-daemon Not Functioning On v2.7.3

### ISSUE THREAD

**Issue by ThePieMonster** [Tautulli/Tautulli#1450]
**Describe the Bug**
Following the below Wiki guide for version 2.7.3 will not work as there is no longer a Tautulli.py file for the Windows x64 install.

https://github.com/Tautulli/Tautulli/wiki/Install-as-a-daemon#non-interactive

Hopefully we can get a option to have Tautulli run as Windows service as part of the Web Interface or General options. 

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.7.3
- Platform and Version: Windows Server 2019 - Platform: | Windows 10 (10.0.17763)
- Python Version: 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
- Browser and Version: Chrome - Latest

**Comment by samwiseg0** [comment]
This is not a bug as those instructions are under the deprecated section.
