### ISSUE TITLE
macOS 10.13.6 - Tautulli no longer starts

### ISSUE THREAD

**Issue by poiromaniax** [Tautulli/Tautulli#1453]
**Describe the Bug**
Tautulli Auto-Restart or Manual start fails on macOS 10.13 because the app has been built by a higher OS version and not "targeted" to a lower version:

```
[608] Error loading Python lib '/Applications/Tautulli.app/Contents/MacOS/libpython3.8.dylib': dlopen: dlopen(/Applications/Tautulli.app/Contents/MacOS/libpython3.8.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Tautulli.app/Contents/MacOS/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Tautulli.app/Contents/MacOS/libintl.8.dylib
```

Looks to be solved here:
https://github.com/esy/esy/issues/1169
https://stackoverflow.com/questions/58426186/dyld-symbol-not-found-chkstk-darwin

**Steps to Reproduce**
1. Go to '/Applications/Tautulli/Contents/MacOS'
2. Click on 'Tautulli'
3. Terminal will open

**Expected Behavior**
Tautulli should start

**Relevant Settings**
N/A - Tautulli does not start

**Tautulli and System Info (see Tautulli settings page)**
- Version: [2.7.4]
- Git Branch: [master]
- Platform and Version: [macOS 10.13.6]
- Python Version: [3.8.0 pyenv (also have 3.9.2 but same issue, so I tried 3.8.0)]

**Link to logs (required)**
N/A - Tautulli does not start

**Comment by JonnyWong16** [comment]
The MacOS pkg doesn't support macos 10.13. This is already mentioned in the installation guide. 

https://github.com/Tautulli/Tautulli/wiki/Installation#macos

We use Github actions to build the app automatically which doesn't support macos 10.13.
