### ISSUE TITLE
Homepage counts library time double with deleted libraries of same section_id

### ISSUE THREAD

**Issue by sinholueiro** [Tautulli/Tautulli#1456]
**Describe the Bug**
Homepage has double the time in libraries that have the same `section_id` as a deleted library, when you enter the library you can see the correct time.

**Steps to Reproduce**
1. Have two libraries with the same `section_id`, one of which is deleted
1. Go to Homepage
2. Check the time
3. Click in the library
4. Check the time and check that it is exactly half of the homepage

**Expected Behavior**
Same time in the homepage and in the library

**Screenshots**
https://imgur.com/a/UiCq6FB

**Relevant Settings**
-

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.7.4
- Git Branch: master
- Git Commit Hash: v2.7.4
- Platform and Version: [Docker] Linux 5.12.12-arch1-1
- Python Version: 3.8.10
- Browser and Version: Firefox 89.0.2

**Link to logs**
https://gist.githubusercontent.com/sinholueiro/c42bba54576ec208a301644198115c4d/raw/34e9a0d8ccfc8a1300e67d8d15c341f3a7368990/gistfile1.txt

**Comment by Arcanemagus** [comment]
I'm not able to reproduce this, are you sure that your homepage is set to the same timeframe (30 days)?

**Comment by sinholueiro** [comment]
The problem seems to be sorted [here](https://www.reddit.com/r/Tautulli/comments/o94uoa/double_watch_time_in_libraries_only_in_the/) . It seems to be that the homepage counts double if you had a previous deleted library with the same name and section_id.
