### ISSUE TITLE
Fresh install password issue

### ISSUE THREAD

**Issue by ferdydek** [Tautulli/Tautulli#1468]
**Describe the Bug**
Fresh install via Home Assistant's addons; 
Any password entered into the login webui produces no reaction in frontend and argument error in backend. 
Note: not related with password complexity.

**Steps to Reproduce**
Fresh install, define user+password, restart container, attempt login.

**Expected Behavior**
Successful login.

**Screenshots**
Provide screenshots to help explain your problem.

**Relevant Settings**
NA

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.7.4
- Git Branch: as per log defauled to master
- Git Commit Hash: NA
- Platform and Version: HA Docker 
- Python Version: unknown
- Chrome 91

**Link to logs (required)**
https://gist.github.com/ferdydek/bdf545e01d24b8e7a23e59df24cbe5f0
```2021-07-17 10:21:12 - ERROR :: CP Server Thread-8 : [17/Jul/2021:10:21:12] HTTP 
Traceback (most recent call last):
  File "/opt/lib/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/opt/lib/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/opt/lib/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/lib/cherrypy/lib/jsontools.py", line 58, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/lib/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/plexpy/webauth.py", line 373, in signin
    valid_login, user_details, user_group = check_credentials(username=username,
  File "/opt/plexpy/webauth.py", line 135, in check_credentials
    if username == plexpy.CONFIG.HTTP_USERNAME and check_hash(password, plexpy.CONFIG.HTTP_PASSWORD):
  File "/opt/lib/hashing_passwords.py", line 51, in check_hash
    algorithm, hash_function, cost_factor, salt, hash_a = hash_.split('$')
ValueError: not enough values to unpack (expected 5, got 1)```

<!--
Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
-->

**Comment by JonnyWong16** [comment]
I do not provide support for 3rd party installations because I don't know what modifications they have made to the application. Please use one of the official installation methods.
