### ISSUE TITLE
add color coded locks for when a user watches plex ?

### ISSUE THREAD

**Issue by SuperUser123677** [Tautulli/Tautulli#1469]
Is there a way to add a color coded lock for tautulli for when a user watches plex instead of the default white lock for a secure connection. like have green for a secure connection and red for any unsecure connection if the connection is allowed.  I was just curious if this was possible .

**Comment by JonnyWong16** [comment]
No.

And Github Issues is not the place to ask questions. Please use one of the support options instead.
