### ISSUE TITLE
[Feature Request] Enable translations

### ISSUE THREAD

**Issue by drzoidberg33** [Tautulli/Tautulli#147]
Investigate best method to implement translations.

**Comment by Jonn3y** [comment]
Maybe gettext is a good one:
https://docs.python.org/2/library/gettext.html 
https://en.wikipedia.org/wiki/Gettext
After editing the whole sourcecode you could generate a language-file "en.po"
With it everyone can translate the output.

# Just an idea.

**Comment by JigSawFr** [comment]
@drzoidberg33 great to see this enhancement, if you need help, let me know.

**Comment by meisenring** [comment]
+1
