### ISSUE TITLE
Newsletters now use dark background with black font on synopsis info for media

### ISSUE THREAD

**Issue by CanonCan** [Tautulli/Tautulli#1470]
**Describe the Bug**

**Steps to Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior**

**Screenshots**
Provide screenshots to help explain your problem.
![1024-1539](https://user-images.githubusercontent.com/31594024/126071868-5c2f2afa-5c1f-4819-be96-9873d35eb9c4.png)

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.7.5]
- Git Branch: [eg. master]
- Git Commit Hash: 5fbe9d476b8dec441869085a195794d9efb1ef72
- Platform and Version: [eg. Docker for Unraid]
- Python Version: [e.g. 3.8.8]
- email newsletter

**Link to logs (required)**
Include a link to your **FULL** logs (not just a few lines) on [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by JonnyWong16** [comment]
The CSS on the newsletter template has not been modified in 3 years. This is an issue with your email client and not Tautulli.

**Comment by CanonCan** [comment]
Well it's not just mine it's a friends the screenshot is my friends and mine is doing the same thing I'm using Gmail as my mail client but it's all integrated into Tautulli

**Comment by CanonCan** [comment]
This was verified via Blue mail for Android and the default mail application for Apple devices

**Comment by CanonCan** [comment]
Newsletters sent a week ago and more did not have the issue

**Comment by JonnyWong16** [comment]
The code is open source. You can literal go view the history of the template and see that the CSS hasn't been changed in 3 years. 

https://github.com/Tautulli/Tautulli/commits/master/data/interfaces/newsletters/recently_added.html

If you don't believe me then downgrade to the previous version.

Github issues is only for bug reports and not support requests so I am closing and locking this issue. Please use one of the support options for help with Tautulli.
