### ISSUE TITLE
A cookie with slashes in its name breaks Tautulli's cherrypy

### ISSUE THREAD

**Issue by gkovacsp** [Tautulli/Tautulli#1477]
**Describe the Bug**
If Tautulli is running in a reverse proxy environment sharing the domain with multiple services, then a cookie created by a different service might break Tautulli, if the name of the cookie contains slashes. In my example tvheadend is causing this problem.

**Steps to Reproduce**
Use tautulli and tvheadend on the same domain with reverse proxy:
mydomain.com/tautulli
mydomain.com/tvheadend

Create a cookie with tvheadend by simply adjusting a width of any of the columns in any view

Try to open tautulli: the following error appears:
`400 Bad Request
Illegal key 'ys-api/dvr/entry/grid_upcoming'

Traceback (most recent call last):
  File "/app/tautulli/lib/cherrypy/_cprequest.py", line 732, in process_headers
    self.cookie.load(value)
  File "/usr/lib/python3.8/http/cookies.py", line 529, in load
    self.__parse_string(rawdata)
  File "/usr/lib/python3.8/http/cookies.py", line 593, in __parse_string
    self.__set(key, rval, cval)
  File "/usr/lib/python3.8/http/cookies.py", line 485, in __set
    M.set(key, real_value, coded_value)
  File "/usr/lib/python3.8/http/cookies.py", line 352, in set
    raise CookieError('Illegal key %r' % (key,))
http.cookies.CookieError: Illegal key 'ys-api/dvr/entry/grid_upcoming'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/tautulli/lib/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/app/tautulli/lib/cherrypy/_cprequest.py", line 658, in _do_respond
    self.process_headers()
  File "/app/tautulli/lib/cherrypy/_cprequest.py", line 734, in process_headers
    raise cherrypy.HTTPError(400, str(exc))
cherrypy._cperror.HTTPError: (400, "Illegal key 'ys-api/dvr/entry/grid_upcoming'")
`

**Expected Behavior**
It should open without a problem, like my other services actually do (e.g. Nextcloud, grafana, heimdall...)

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.7.5
- Git Branch: master
- Git Commit Hash: v2.7.5
- Platform and Version: Raspbian GNU/Linux 10 (buster) 
- Browser and Version: Raspbian GNU/Linux 10 (buster)

**Link to logs (required)**
https://gist.github.com/gkovacsp/5cf38d4ee5c6b1b26367477f0191eb55

**Comment by JonnyWong16** [comment]
I'm not sure what I can do here.

Cookies are all handled by the [standard Python cookie library](https://docs.python.org/3/library/http.cookies.html).

> The character set, string.ascii_letters, string.digits and ``!#$%&'*+-.^_`|~:`` denote the set of valid characters allowed by this module in Cookie name (as key).

The standard library follows [RFC 2109](https://datatracker.ietf.org/doc/html/rfc2109.html#section-4.1) which specifies cookies as "a sequence of non-special, non-white space characters".

>   The two state management headers, Set-Cookie and Cookie, have common
>   syntactic properties involving attribute-value pairs.  The following
>   grammar uses the notation, and tokens DIGIT (decimal digits) and
>   token (informally, **a sequence of non-special, non-white spaced i
>   characters**) from the HTTP/1.1 specification [RFC 2068] to describe
>   their syntax.

[RFC 2068](https://datatracker.ietf.org/doc/html/rfc2068#page-16) defines special characters as

>          tspecials      = "(" | ")" | "<" | ">" | "@"
>                         | "," | ";" | ":" | "\" | <">
>                         | "/" | "[" | "]" | "?" | "="
>                         | "{" | "}" | SP | HT

Therefore, a slash (`/`) is a special character which is invalid in cookie names according to the standard cookie specifications. Tvheadend should fix their cookies to follow the standard cookie specifications. I don't know what all your other applications are doing but you should research to see if they are following the specifications or just hacking around it with a workaround. I'm very much against hacking a workaround into Tautulli.

**Comment by gkovacsp** [comment]
This is the [tvheadend forum](https://tvheadend.org/issues/2706) talking about this problem, they state that the latest standard is RFC 6265

These are the other services which run successfully parallel with tvheadend, behind an nginx based reverse proxy:

- heimdall
- nextcloud
- grafana
- portainer
- dozzle
- webssh
- transmission
- pihole
- phpmyadmin

Probably it is a cherrypy configuration issue, I seem to remember that I had another service some time ago, which showed similar errors with cherrypy, but at that time I did not know the reason.

Of course you should not hack anything into Tautulli.

**Comment by gkovacsp** [comment]
I've found one more reference: https://bugs.python.org/issue44104#msg393539 about exactly the same issue.

**Comment by JonnyWong16** [comment]
Tvheadend can follow RFC 6265, but Python does not.

It doesn't matter how many other services run successfully.

It's not a cherrypy issue because it's part of the Python standard library.

That Python issue was closed because `/` is not a valid character. And the suggestion to filter it out is asking to hack a solution into Tautulli.

**Comment by gkovacsp** [comment]
OK, I've reported it to tvheadend to see what they say: https://tvheadend.org/issues/6078
Thank you for looking into it.
