### ISSUE TITLE
Save EXPORT 

### ISSUE THREAD

**Issue by INPHOman** [Tautulli/Tautulli#1479]
Ability to save an export (script if you will) so it doesn't have to be "rebuilt" each time you want to execute.

**Comment by JonnyWong16** [comment]
Use the API and save the URL.

https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference#export_metadata

**Comment by INPHOman** [comment]
Thanx. I was thinking more an object I could select in a pulldown on the "export" option. I will work on this option though.
