### ISSUE TITLE
Abilty to monitor sync status

### ISSUE THREAD

**Issue by pmcfarland** [Tautulli/Tautulli#1481]
It would be useful for Tautulli to be able to monitor sync status, and ideally trigger notifications on it.

As in pull up the dashboard for Tautulli or nowadays the app to be able to monitor the sync status. 
For example: Device **Tablet123** is currently syncing library **Movies** at **73% complete** (item 23 of 34).

I know that you can view the status from the device itself or the Plex dashboard, but it would be nice to track it here, and be able to trigger notifications off of status or certain things. For instance send a telegram message, sync completed (2 items) on device Tablet123. Potentially it could monitor for stalls as in Sync may have stalled on device Tablet123 (sync status 73% complete for >10 min while both device and server online).

Definitely not required, Tautulli works beautifully as is, but recently as I've been messing around with using Sync/Downloads with Plex and devices it would be great if I could use Tautulli to help keep an eye on things.

**Comment by JonnyWong16** [comment]
Plex is already replacing Sync with Download so I it's not worth developing features for Sync anymore. It's also not possible to view Download status the same way you can view Sync status on the Plex server at the moment. Notifications for download events are possible, but that's it for now until Plex implements a way to view Downloads from the server.
