### ISSUE TITLE
Default Anonymous Redirect Service dereferer.org No Longer Functional

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#1482]
**Describe the Bug**
When clicking links inside Tautulli to external pages, the link redirection results in a DNS lookup failure on the dereferer.org domain, which is the default Anonymous Redirect service in Tautulli settings. Research of the WHOIS of the domain shows that the domain registration is in a "clientHold" and "pendingDelete" state as of 2021-06-20.

**Steps to Reproduce**
1. Go to 'Settings'
2. Click on 'Help & Info'
3. Scroll down to 'Resources'
4. Click on 'Tautulli Website'

**Expected Behavior**
A new tab should open, first taking you to https://dereferer.org/?https://tautulli.com. It should then redirect you to https://tautulli.com.

**Screenshots**
N/A

**Relevant Settings**
- Tautulli Settings > Web Interface > Anonymous Redirect > Currently set to default value of 'http://dereferer.org/?'

**Tautulli and System Info (see Tautulli settings page)**
- Version: `2.7.5 (via snap)`
- Git Branch: `master`
- Git Commit Hash: `5fbe9d476b8dec441869085a195794d9efb1ef72`
- Platform and Version: `Linux 5.4.0-80-generic (#90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 - Ubuntu Core 18)`
- Python Version: `3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]`
- Browser and Version: `Microsoft Edge 92.0.902.62`

**Link to logs (required)**
N/A

**Comment by samwiseg0** [comment]
This is not a bug. This service has been temporarily down before. If you would like to use another service you may change it in settings. If the issue persists we will consider changing the default value to another service.

**Comment by JonnyWong16** [comment]
The default isn't even `dereferer.org`, it's `nullrefer.com`.

Source code is here:

https://github.com/Tautulli/Tautulli/blob/master/plexpy/config.py#L78

**Comment by ghost** [comment]
> The default isn't even `dereferer.org`, it's `nullrefer.com`.
> 
> Source code is here:
> 
> https://github.com/Tautulli/Tautulli/blob/master/plexpy/config.py#L78

I'm not even sure how I would have gotten `dereferer.org` then, unless it was a default in some older version that never got updated. I've never changed that setting until I noticed it wasn't working 4 days ago.

Looking back through previously reported issues, there was a post in 2016 reporting problems with `nullrefer.org` where your reply made it seem like the default had become `dereferer.org` at some point:

https://github.com/Tautulli/Tautulli/issues/714

Digging into previous commits, looks like default changed from `dereferer.org` to `nullrefer.com` here: 
https://github.com/Tautulli/Tautulli/blob/581b8375b996084021a580da5f199c0b6abfca1c/plexpy/config.py

As the previous commit just before it still set the value to `dereferer.org`:
https://github.com/Tautulli/Tautulli/blob/1f7e8b4d9a68aa410e1c90aab517c22afeec27f5/plexpy/config.py

**Comment by JonnyWong16** [comment]
Yes, it used to be `dereferer.org` years ago. The current default is `nullrefer.com`.

So this entire bug report is moot because I had already changed it.

**Comment by putnam** [comment]
I don't see how this isn't a bug. I have never changed this setting, and the new default should have overridden the old default, no? Same issue as OP. "Deferer" (which was always misspelled, for the record, just like Referer in the HTTP spec)  is now a domain squatter site.

Why would a default value be stored hard-coded in the config?
