### ISSUE TITLE
Library Exports for Collections/Playlists Broken

### ISSUE THREAD

**Issue by rg9400** [Tautulli/Tautulli#1484]
**Describe the Bug**
When exporting an entire library's collections or playlists (via the webpage or the API), I get the below error. It works fine when exporting individual collections/playlists or an entire library's media

```
    Uncaught exception: Traceback (most recent call last):
    File "/app/plexpy/logger.py", line 405, in new_run
        old_run(*args, **kwargs)
    File "/usr/local/lib/python3.8/threading.py", line 870, in run
        self._target(*self._args, **self._kwargs)
    File "/app/plexpy/exporter.py", line 1819, in _real_export
        items = method()
TypeError: collection() missing 1 required positional argument: 'title'
```

**Steps to Reproduce**
1. Go to Libraries tab, select a library, then go to Collections tab
2. Select Export and select Level 1 for all metadata and art, individual files, JSON file format
3. Check logs for error

**Expected Behavior**
The Library export for Collections/Playlists should work even with above settings

**Relevant Settings**
- Level 1 Metadata and Art selected in Export
-  Individual Files
- JSON File Format

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.7.5
- Git Branch: nightly
- Git Commit Hash: 670d2b31f75b4b5a4be39843aa972bf881b653c2
- Platform and Version: Docker (official version)
- Python Version: 3.8.10

**Comment by JonnyWong16** [comment]
PlexAPI 4.6.0 deprecated `collection()` and `playlist()`. It should be plural `collections()` and `playlists()`.

Maintain singular in Tautulli API, handle plural internally.
