### ISSUE TITLE
Set LWT on the MQTT notifier topic

### ISSUE THREAD

**Issue by psarossy** [Tautulli/Tautulli#1488]
**Is your feature request related to a problem? Please describe.**
Currently the MQTT notifier does not set or have the option to set Last Will (and Testament). If Tautulli crashes/goes offline unexpectedly, the reporting just stops. I use it to tell me when Plex is misbehaving, but if Tautulli itself goes down I can't get notified.

**Describe the solution you'd like**
A LWT should be set up to indicate that Tautulli went offline.
The Paho MQTT library already supports setting and clearing the LWT: https://github.com/Tautulli/Tautulli/blob/53121adfee474402e49d07b725dcf78285ef88c0/lib/paho/mqtt/client.py#L1172

**Describe alternatives you've considered**
I have not considered alternatives as this is the canonical method, and supported by the libraries used.

**Additional context**
I can attempt to make a PR for this but not super familiar with the codebase...

**Comment by JonnyWong16** [comment]
I don't think this will work. Tautulli disconnects from MQTT after the notification is sent.

https://github.com/Tautulli/Tautulli/blob/5fbe9d476b8dec441869085a195794d9efb1ef72/lib/paho/mqtt/publish.py#L176-L180

So it doesn't keep a constant connection for the MQTT broker to detect an unexpected disconnection and publish the LWT.
