### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by myktek** [Tautulli/Tautulli#149]
Graphs/totals for paused.

One of the things that annoys me about my friends/family using Plex is they like to put it on pause for long periods of time.  Could we get some graphs or totals for time paused?
I can see how much they paused in the history, but a total or graphs so I can be like, stop pausing the shows and leaving it there forever.

It's not too important but cool to have :)

Sidenote, thank you very much for the program, it's very useful!

**Comment by zenjabba** [comment]
I'm not sure why your family pausing the shows is a problem, there is no bandwidth being consumed, nor any CPU power being used. 

I've just accepted they got busy and will either come back to watch it or watch something else.

**Comment by JonnyWong16** [comment]
You can view paused time in the tables. A new graph just for paused is too much.
