### ISSUE TITLE
Add playback error parameter for notification agent text

### ISSUE THREAD

**Issue by polklabs** [Tautulli/Tautulli#1493]
**Describe the solution you'd like**
It's nice to be able to receive a notification on playback error, but without actually knowing what that error is it doesn't help too much.

**Describe alternatives you've considered**
Other than contacting the user that encountered the error, or searching through the Plex logs, I'm not aware of any alternatives.

**Additional context**
The message body for the Playback Error notification would look something like this.

`{user} ({player}) encountered an error trying to play {title}. Error: {error_message}`
Becomes
`Bob (Roku) encountered an error trying to play The Avengers. Error: Transcoder Failed to Start`
`Jane (Apple TV) encountered an error trying to play Interstellar. Error: Connection Not Fast Enough`

**Comment by JonnyWong16** [comment]
It's actually not possible because Plex doesn't provide the error reason server side. The error message is only available on the client.

This is all the data available on the server.

```json
{"NotificationContainer":{"type":"playing","size":1,"PlaySessionStateNotification":[{"sessionKey":"16","clientIdentifier":"bsa256dspr4svju3zq3ssndfx","guid":"","ratingKey":"6263","url":"","key":"/library/metadata/6263","viewOffset":0,"playQueueItemID":411763,"playQueueID":21343,"state":"error"}]}}
```
