### ISSUE TITLE
Tautulli fails to start with no warning to user

### ISSUE THREAD

**Issue by EarthBoundX5** [Tautulli/Tautulli#1494]
**Describe the Bug**
When another application is installed using port 8181 and Tautulli is launched via the shortcut on the Desktop from installation, the application does not load, no browser is launched, and no error message is displayed to the user.  Solved issue by changing http port in Tautulli config.

**Steps to Reproduce**
1. Have port 8181 bound to another application
2. Install Tautulli
3. Attempt to launch Tautulli from the Desktop icon post installation

**Expected Behavior**
I would expect a user to not require looking at logs, and an error message should be displayed reflecting the issue.  Something such as "Error: Tautulli failed to start because port 8181 is in use by another application.  Please resolve and try again"

**Screenshots**
N/A

**Relevant Settings**
- Running Headphones application on port 8181

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.7.5
- Git Branch: master
- Git Commit Hash: 5fbe9d476b8dec441869085a195794d9efb1ef72
- Platform and Version: Windows 10 (10.0.17763) [Actually Windows Server 2019]
- Python Version: 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
- Browser and Version: Firefox 91.0.1

**Link to logs (required)**
https://gist.github.com/EarthBoundX5/af4a0acabb29856948ee90049cada081

**Comment by Arcanemagus** [comment]
Tautulli's interface _is_ the web interface, if it can't bind to the port to launch that the only other place it has to communicate is the logs. As a backend tool for server administrators checking the logs isn't a huge thing to ask of users.

**Comment by JonnyWong16** [comment]
I can try adding an alert box.

**Comment by JonnyWong16** [comment]
Added in v2.7.6.
