### ISSUE TITLE
Use without Plex

### ISSUE THREAD

**Issue by fugkco** [Tautulli/Tautulli#1496]
**Describe the solution you'd like**
Having looked through the screenshots, this looks like it's a nice, self-hosted alternative to trakt.tv. Seems it has similar features and at least has the core offerings of Trakt. However, there are many people who don't use Plex for different reasons. I'm one of those, and I'd love to be able to run this to track my Movies and TV Shows. I just tried running it and it seems Plex is a requirement for this. It would be great to make the Plex connection optional so that it can act as a stand alone application to track moves and shows.

**Comment by Jerome2103** [comment]
This tool is for Plex.
It has no connection like trakt.tv to the different streaming providers. Moreover, this database is only filled with meta data from Plex server.

**Comment by samwiseg0** [comment]
This entire project centers around Plex. Tautulli’s entire purpose is to give users insights into their Plex server usage and enhance its capabilities. It is not possible to use it without Plex. Nor would we create such a “feature” as it would require a complete rewrite of the code and at that point would be another project.
