### ISSUE TITLE
Library Exports for Playlists with Tidal Tracks Broken

### ISSUE THREAD

**Issue by EpicWolverine** [Tautulli/Tautulli#1498]
### Describe the Bug

I just updated to 2.7.6 and I still (#1484) can't export all my playlists. I get this error:
```
Tautulli Exporter :: Failed to export 'Library - Music - Playlist [3]': (404) not_found; https://192-168-1-98.<censored>.plex.direct:32400/library/metadata/5b8889fb9eea390033cc6606?includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
Traceback (most recent call last):
    File "plexpy\exporter.py", line 1844, in _real_export
    File "multiprocessing\pool.py", line 364, in map
    File "multiprocessing\pool.py", line 771, in get
    File "multiprocessing\pool.py", line 125, in worker
    File "multiprocessing\pool.py", line 48, in mapstar
    File "plexpy\exporter.py", line 1874, in _do_export
    File "plexpy\exporter.py", line 2208, in _export_obj
    File "plexpy\exporter.py", line 2132, in export_obj
    File "plexpy\helpers.py", line 1341, in get_attrs_to_dict
    File "plexpy\helpers.py", line 1341, in <listcomp>
    File "plexpy\exporter.py", line 1187, in <lambda>
    File "plexpy\exporter.py", line 2130, in export_obj
    File "plexapi\base.py", line 341, in reload
    File "plexapi\base.py", line 350, in _reload
    File "plexapi\server.py", line 650, in query
plexapi.exceptions.NotFound: (404) not_found; https://192-168-1-98.<censored>.plex.direct:32400/library/metadata/5b8889fb9eea390033cc6606?includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```
I did some experimenting with individual playlists and I can export a playlist if it has only local files in it but it fails immediately if there's any Tidal tracks in it. I assume this is the cause.

### Steps to Reproduce

1. Create a playlist with Tidal tracks.
2. Go to Libraries > Music > Playlists
3. Press Export Playlists
4. Use the default settings and press Export
5. See the export fail in the Exports tab and see the above error in the logs.

### Expected Behavior

All playlists with all tracks are exported.

### Tautulli Version

v2.7.6

### Git Branch

master

### Git Commit Hash

db90b8ad18023fe5cfc3d8e302b45d3db6ff2387

### Platform and Version

Windows 10 (10.0.19043)

### Python Version

3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

### Browser and Version

Firefox 91.0.2

### Link to Logs

https://gist.github.com/EpicWolverine/73a1079b1767059aaa392c3bdd3a4a06

**Comment by JonnyWong16** [comment]
This is an upstream issue with the `python-plexapi` library because it doesn't have Tidal support.

https://github.com/pkkid/python-plexapi/issues/671

It would need to be implemented there first before it can be supported in Tautulli. 

None of the people working on `python-plexapi` (including myself) use Tidal or have a Tidal subscription so we don't have the ability to implement it. It might have to wait for someone else who does use Tidal to come along and contribute to that project.

**Comment by EpicWolverine** [comment]
Ah dang. Well I do have Tidal (for songs I haven't bought yet) and I know Python, so I could help be your test bench and debug if you'd like. I'd be pretty lost diving in and doing it solo.
