### ISSUE TITLE
Feature Request: Option to override user's profile picture URL

### ISSUE THREAD

**Issue by nomadore** [Tautulli/Tautulli#15]
Currently users have their profile pictures as a letter.  It would be nice to be able to specify a different URL for the location of the user profile instead of the Gravatar URL.

**Comment by tylordurton** [comment]
+1

**Comment by drzoidberg33** [comment]
@jroyal has been kind enough to help out with this and pushed into dev.

Commit: https://github.com/drzoidberg33/plexpy/commit/375bd733f1dca37d0c845c3c61fb2760c7e708a1

**Comment by drzoidberg33** [comment]
Released in v1.1.0

https://github.com/drzoidberg33/plexpy/releases/tag/v1.1.0
