### ISSUE TITLE
Newsletter for music always empty and not sent

### ISSUE THREAD

**Issue by mada199122** [Tautulli/Tautulli#1501]
### Describe the Bug

Newsletter for Music library on Plex always empty whatever the time frame is selected.

### Steps to Reproduce

- Create a new newsletter agent
- Add only Music library
- Select a time frame where you are sure you have added at least a new track
- Add all the mail account info in the correct tab
- 
- Go to the Test Newsletter tab and then press the button "Preview recently added Newsletter" 
- A new tab will open with just the "title" without the new music content 

Or

- Try to press  "Test Recently Added Newsletter"
- Then no mail will be sent

### Expected Behavior

Receive a mail with the recent added Music trac or Artist in the timeframe selected in the option

or

Preview the newsletter in the browser with the correct Music track information added in the time frame selected

### Screenshots

![Screenshot 2021-09-04 at 11 27 32](https://user-images.githubusercontent.com/61902329/132089750-8f4060f8-9c1d-4ae5-ac2c-a125cfa4bac5.jpg)

### Tautulli Version

2.7.6

### Git Branch

master

### Git Commit Hash

db90b8ad18023fe5cfc3d8e302b45d3db6ff2387

### Platform and Version

Docker official image

### Python Version

3.9.6

### Browser and Version

Safari 15

### Link to Logs

https://gist.github.com/mada199122/115dd69342c420e0af9cd4260ecdfa92

**Comment by JonnyWong16** [comment]
Logs must be uploaded to gist.github.com. Attachments are not allowed.

**Comment by mada199122** [comment]
uploaded

**Comment by JonnyWong16** [comment]
Have you read the FAQ? 

https://github.com/Tautulli/Tautulli/wiki/Frequently-Asked-Questions#newsletter-recently-added-library

**Comment by mada199122** [comment]
Ops... no I haven't read...
sorry...

Thanks for the suggestion... I confirm now they work fine.
