### ISSUE TITLE
Wiki instructions for FreeBSD/FreeNAS assume python is 3.7

### ISSUE THREAD

**Issue by lambada** [Tautulli/Tautulli#1505]
### Describe the Bug

The default python install on _some_ variants of freebsd/freenas is now 3.8 - including the latest freenas.
See https://www.freshports.org/lang/python/

But your isntall instructiosn assume python is 3.7 https://github.com/Tautulli/Tautulli/wiki/Installation#freebsd--freenas
`pkg install python py37-setuptools py37-sqlite3 py37-openssl py37-pycryptodomex security/ca_root_nss git-lite`
which causes two problems

1) Running the pkg command as is results in
```
pkg: No packages available to install matching 'py37-openssl' have been found in the repositories
pkg: No packages available to install matching 'py37-pycryptodomex' have been found in the repositories
```

2) Means that tautulli fails to start with
```
# service tautulli start
Starting tautulli.
Traceback (most recent call last):
  File "/usr/local/share/Tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/usr/local/share/Tautulli/plexpy/__init__.py", line 24, in <module>
    import sqlite3
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

### Steps to Reproduce

1. Install a fresh up to date copy of FreeNAS
2. Install a fresh Jail
3. Follow the Tautulli install instructions

### Expected Behavior

The instructions work as written and Tautulli starts

### Tautulli Version

 v2.7.6

### Git Branch

master

### Git Commit Hash

db90b8ad18023fe5cfc3d8e302b45d3db6ff2387

### Platform and Version

TrueNAS-12.0-U5

### Python Version

3.8.10

### Browser and Version

N/A

### Link to Logs

https://gist.github.com/lambada/06cfffa05332be65473a83d596681262

**Comment by lambada** [comment]
Substituting 37 for 38 in the `pkg install` command _apepars_ to have worked (the service starts and web ui comes up). But I'm not a heavy user of all parts of tautulli so there might be gotchas in doing that I'm not likely to find.

**Comment by JonnyWong16** [comment]
This is correct for Python 3.8
```
pkg install python py38-setuptools py38-sqlite3 py38-openssl py38-pycryptodomex security/ca_root_nss git-lite
```

**Comment by JonnyWong16** [comment]
Wiki updated.
