### ISSUE TITLE
Tautulli doesn't run on Python 3.10.0

### ISSUE THREAD

**Issue by Anuruddha094** [Tautulli/Tautulli#1522]
### Describe the Bug

Tautulli doesn't run on Python 3.10.0. I have tested it on Windows 10 pro PC. It works perfectly on Python 3.9.7.

### Steps to Reproduce

1.Windows 10
2. Install Python 3.10.0
3. Install Tautulli latest version using manual method. Please download the code via git.

### Expected Behavior

Doesn't load python on system tray or load python services.

### Tautulli Version

2.7.6

### Git Branch

master

### Git Commit Hash

abcdefghijlknopq1234567

### Platform and Version

Windows 10 Pro 21H1

### Python Version

3.10.0

### Browser and Version

Google Chrome

### Link to Logs

https://nolinks.com/nolinktoshow

**Comment by samwiseg0** [comment]
Please provide more information. What error are you seeing?

Please attempt to run it in a CMD window to see the error.

**Comment by Anuruddha094** [comment]
Hi already I reverted back to python 3.9.7. After I installed Python 3.10.0, I just double click start.bat and CMD windows didn't load at all. I believe python compiler just killed the start up script. Anyway I try to test it in a VM and let you know the status.

**Comment by reloxx13** [comment]
Todays nightly works on 3.10. and win10.   
There were some dependency changes which could have fixed ur issue, too.
Be sure to clear all .pyc files if you switch the python version.

https://github.com/Tautulli/Tautulli/issues/1523#issuecomment-944938745
> That's not a bug. That happens when you try to switch Python versions.
> 
> https://www.reddit.com/r/Tautulli/comments/khk5re/tautulli_fails_to_start_after_upgrading_from/gglngsx/

![grafik](https://user-images.githubusercontent.com/14855001/137597191-2bf37a93-3f2d-4d60-a7fc-9021ca08e8c4.png)

**Comment by samwiseg0** [comment]
> Todays nightly works on 3.10. and win10. There were some dependency changes which could have fixed ur issue, too. Be sure to clear all .pyc files if you switch the python version.
> 
> [#1523 (comment)](https://github.com/Tautulli/Tautulli/issues/1523#issuecomment-944938745)
> 
> > That's not a bug. That happens when you try to switch Python versions.
> > [reddit.com/r/Tautulli/comments/khk5re/tautulli_fails_to_start_after_upgrading_from/gglngsx](https://www.reddit.com/r/Tautulli/comments/khk5re/tautulli_fails_to_start_after_upgrading_from/gglngsx/)
> 
> ![grafik](https://user-images.githubusercontent.com/14855001/137597191-2bf37a93-3f2d-4d60-a7fc-9021ca08e8c4.png)

Thank you for the information. I will close this since you have confirmed that it works on 3.10 with windows.

**Comment by Anuruddha094** [comment]
@samwiseg0  and @reloxx13 Thank you very much for the confirmation. Hopefully soon that patch will be add to master branch. 
cheers

**Comment by fryfrog** [comment]
Arch Linux just pushed 3.10 to everyone, could you do a release w/ this fix so the [tautulli aur package](https://aur.archlinux.org/packages/tautulli/) works again? :)

**Comment by mmozeiko** [comment]
fyi, v2.8.0-beta release works on ArchLinux with python 3.10.
