### ISSUE TITLE
History not showing - Showing 0 to 0 of 0 entries (filtered from 34,250 total entries) 

### ISSUE THREAD

**Issue by stevezau** [Tautulli/Tautulli#1548]
### Describe the Bug

Hi, for some reason the history page is not showing any entires. It shows the below however i have no filters on.

Showing 0 to 0 of 0 entries (filtered from 34,250 total entries) with a duration of 0 (filtered from 0 total)

What is odd is there are entries in the db. If i view the history in a library via https://py.stevez0.com/library?section_id=2#tab_tabs-history it shows.

Can you point me in a direction so i can go troubleshooting?

Thanks

### Steps to Reproduce

1. Open "History"
2. Nothing is shown

### Expected Behavior

History shows :)

### Screenshots

![image](https://user-images.githubusercontent.com/6075483/139168777-648d18e5-e2ed-41dc-9f91-22fda709ea60.png)

### Relevant Settings

.

### Tautulli Version

VERSION V2.7.7 (via docker)

### Git Branch

nightly

### Git Commit Hash

ecb66f39c98e8d7dd01967f28859bfe3f67fdca9

### Platform and Version

[Docker] Linux 5.13.0-20-generic (#20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021)

### Python Version

3.8.10 (default, May 6 2021, 00:05:59) [GCC 10.2.1 20201203]

### Browser and Version

Chrome Version 95.0.4638.54 (Official Build) (x86_64)

### Link to Logs

N/A - do i need to share my logs?

**Comment by TheMeanCanEHdian** [comment]
You need to toggle on the options at the top. Movies, TV, etc.

**Comment by JonnyWong16** [comment]
Or have you simply tried clearing browser cache?

**Comment by stevezau** [comment]
oh geez, how embarrassing, it was due to the filters.

**Comment by TheMeanCanEHdian** [comment]
Don't worry, happened to me too.
