### ISSUE TITLE
[Feature Request] Bandwidth monitoring total/per user 

### ISSUE THREAD

**Issue by srbrunner** [Tautulli/Tautulli#155]
Would it be possible to add bandwidth monitoring total/per user.  Not sure if this is possible, but it would be nice to see how much bandwidth my family is using when they are remote.

Thanks for you consideration if this request.

BTW, have to say I just love this.  It was easier to set up and has some features I wanted over PlexWatchWeb.

**Comment by drzoidberg33** [comment]
This is unfortunately something that is not easy to implement cross-platform and not something that would be reliable.

Plex itself does not provide bandwidth statistics so it would require a third party library which generally only report usage for entire network interfaces (e.g. it wouldn't be able to log a single Plex stream). These libraries also may not be available on all platforms or are available but work differently.

It's just not something that would currently be possible.

**Comment by elRadix** [comment]
maybe use the file size of the movie or serie and use that as total bandwidth watched - its not perfect but it gives an idea

**Comment by pmeeke** [comment]
Using the file size wouldn't work. If the file was transcoded to a lower quality the bandwidth would be substantially lower.
Maybee looking at how the file was played, if it was played directly you could use your option, if it was transcoded it might be possible to look at the ffmpeg logs.

**Comment by drzoidberg33** [comment]
@elRadix That's too unreliable. Somebody may have a 40Mbit BluRay rip but it gets streamed at 4Mbit.
