### ISSUE TITLE
Feature: Mobile Device rendering fixes

### ISSUE THREAD

**Issue by sbaydush** [Tautulli/Tautulli#156]
Currently when you view the site, it sort of renders in a mobile view. When you click on the history tab, there is no way to see desired columns for example. Would it be possible to fix up the rendering of the tabs for mobile users?

Thank you so much for creating this website! I love how dynamic it is and how fast it loads!

**Comment by drzoidberg33** [comment]
Yes, this is something that I want to improve on. The tables are tricky though as you can only fit so much on to a mobile display.

Is there anything specific you want to see on the history tables when viewing on mobile?

**Comment by sbaydush** [comment]
The most important thing for me to see on the table would be name of the user, what they were watching and what time they started and stopped.  I know that's a lot of data to put on a phone screen but there has to be an aesthetically pleasing way to display it.

Would it be possible to be able to pan around the table using the touchscreen controls on a phone?
or maybe try something like the following where it turns each row into a mini table that can be scrolled through.

 ![sample](https://www.digitalgov.gov/files/2014/10/600-x-300-orig.jpg)

**Comment by Hellowlol** [comment]
Or you can make the table scrollable  I had to use that since i didnt want to hide anything :(

**Comment by RafaelSchridi** [comment]
Showing more on bigger devices would be nice too. 2 tables look huge on my moto x.

**Comment by JonnyWong16** [comment]
Tables now show all columns on mobile devices in v1.4.0. It's a start, but I think there are still things to improve.

**Comment by sbaydush** [comment]
Thank you so much for implementing that! I love this application and use it every day! Thanks for helping create such a useful web application :)
