### ISSUE TITLE
Migrate Database?

### ISSUE THREAD

**Issue by hgpot** [Tautulli/Tautulli#158]
I am moving my PlexPy to another machine in the house, separate from my main machine. I reinstalled it and it is simple enough, but I wanted to know if I could import the history from my original installation? Windows X64 environment.

**Comment by drzoidberg33** [comment]
You can just copy the plexpy.db file straight over. Just make sure that PlexPy isn't running on either of the installs when copying this file over.

**Comment by hgpot** [comment]
Thank you, worked like a charm. I wasn't sure where the DB was so I had
initially copied the entire directory over but that didn't run.

[image: --]

Sam Lewis
[image: http://]about.me/hgpot
http://t.sidekickopen16.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX48pTxS8W1q0NZC2BWb98W3Mx_5x56dGLGdCxRmT02?t=http%3A%2F%2Fabout.me%2Fhgpot%3Fpromo%3Demail_sig&si=4707841952710656&pi=1bdf5db5-8d5c-42d6-8007-75168b5e5746
