### ISSUE TITLE
[Regression] Mobile layout issues

### ISSUE THREAD

**Issue by drzoidberg33** [Tautulli/Tautulli#159]
There are several regressions with regard to mobile device layouts in the dev branch with the new style changes on the home and info pages.

The home cards and activity pane no longer fits in the standard viewport for many mobile devices:

<img width="595" alt="screenshot 2015-09-06 01 41 24" src="https://cloud.githubusercontent.com/assets/1313205/9701728/a00daffc-5438-11e5-84e0-0e5a7c7457f2.png">

The info pages are no longer responsive:

<img width="597" alt="screenshot 2015-09-06 01 41 48" src="https://cloud.githubusercontent.com/assets/1313205/9701729/a6b49b36-5438-11e5-9597-4fe8e5d912f7.png">

**Comment by zobe123** [comment]
Same here, since about one mounth.
The history table was never/is actually not readable on iphone 5s (only 2 colums showin up at portrait/landscape)
