### ISSUE TITLE
Option to send user an email

### ISSUE THREAD

**Issue by Elrique64** [Tautulli/Tautulli#16]
It would be great if we could send the user an email directly from the user's stat page.  Barring that, can we get some more user info put into their stat page, such as email, or phone number, etc.  Some sort of contact info, so if we see they are having issues, we can contact them to help resolve them.

I know this would have to be entered in individually on a per user basis, but it could save a lot of time for the admin.

**Comment by drzoidberg33** [comment]
I have some ideas. Just getting the time to implement.

**Comment by aeror1** [comment]
if it matters, i would like to add moral support for this!  i would rather have this baked into plexpy than installing plexemail https://github.com/jakewaldron/PlexEmail.

thanks!

**Comment by ThePierce** [comment]
Any progress/eta on this feature? :)

**Comment by TATUMTOT** [comment]
Would like to see this too. Thanks Everyone.

**Comment by dot-mike** [comment]
Since this is the oldest request, I have begun working on it.
@drzoidberg33 @Elrique64

**Comment by dot-mike** [comment]
Input is needed. See example email template here:
https://jsfiddle.net/eko6w54q/1/

Web-template is yet to be created.

**Comment by Hellowlol** [comment]
Nice

**Comment by dot-mike** [comment]
Work has begun, see ColdIce1/plexpy@1bccc9396abc6023481600027842f84b9a673737

**Comment by Elrique64** [comment]
I think I'm more in line of thinking about hitting the user's name, getting there email and sending a notification of down times, scheduled maintenance, etc.  Not so much this, where it's the newly added.  Although that is nice to have, too.

Maybe setting up a notifications system, where I can send a user a weekly synopsis of newly added, or can see their On Deck and send them a note about a new episode is out now, something like that could be really useful.

**Comment by dot-mike** [comment]
That is a great idea @Elrique64 - the mail handler system can be expanded.

The template I have worked out can be used for nearly everything regard email. Sure, any opinions are appreciated

**Comment by Elrique64** [comment]
Ok, this is just a quick brainstorm...

You go in to edit the user notifications now, so have a place to edit the user's email notifications, for things like "New On Deck" or New Previously Watched or something like that.  If Plex puts it on the "On Deck for the user, PlexPy might be able to see if for that user.

Maybe have other options, too.  "New Movies.  frequency of updates, (as they happen, daily synopsis, weekly, monthly.)  Then have a general "Notify all users of" Maintenance, down times, new features, new series, etc.  And then a way to link back to the series/movies, etc. in question.  

I know some of this might be difficult to get from Plex's API, but some of it can be gotten there, and what can't, should be able to be pulled from the user history.

My thought is, some users don't go into Plex to see if someone has something there or not.  So they wait for it to hit the stores to buy themselves.  This gives them notifications that it's on a Plex Server shared out to them.

**Comment by TATUMTOT** [comment]
yes please im excited this is getting traction.

**Comment by dot-mike** [comment]
Tracking this feature request on my fork, see [Send user mail feature](/ColdIce1/plexpy/issues/1)

**Comment by dot-mike** [comment]
@JonnyWong16 Any inputs regarding Eleique64 past comment? Won't that require a few database changes? Is it a go?

**Comment by JonnyWong16** [comment]
I haven't looked at any of this yet, but quick comments:
- We can only pull a user's On Deck items if we have a server token for the user, which means they need to login at least once into PlexPy first. 
- Isn't notifying of new content just the recently added notifications? Frequency of these notifications can be added as a feature (eventually).
- Yes, some database changes will be needed to store some of this info.

**Comment by fcastilloec** [comment]
@JonnyWong16 I agree that notifying of new content is just the recently added notifications. Adding frequency to this would be great. The problem I see is this: I have email notification for watched movies/shows and other triggers, so I collect statistics on my email address (for some other reason not important here). In addition to this I'd like to send notification of newly added content and server down to some users. It's impossible to setup this case without my friends getting all other notifications emails, or sacrificing my email statistics for the friends emails.
What to do in a case like this?

**Comment by JonnyWong16** [comment]
@fcastilloec I think this is what you're trying to describe:  http://feathub.com/drzoidberg33/plexpy/+40

So you can setup multiple email agents, each with different recipients.

**Comment by stephen304** [comment]
Glad to see there's an issue for this - I'm planning server upgrades and want to be able to easily notify all my friends of the downtime.
