### ISSUE TITLE
PS4 name shows up as Mystery 4 in Graphs section

### ISSUE THREAD

**Issue by 5stringdeath** [Tautulli/Tautulli#162]
In the History list my PS4 correctly reports itself as Plex for Playstation 4.  However in the Graphs section it gets reported as Mystery 4 :-)

![clients](https://cloud.githubusercontent.com/assets/1191140/9704601/75f63864-547a-11e5-9ed9-c97d9b019a60.png)

**Comment by majora2007** [comment]
I have this same issue. Another user has said that PS3 is Mystery 3.

**Comment by drzoidberg33** [comment]
Fixed in https://github.com/drzoidberg33/plexpy/commit/e386d3ee21863b1687f307915057d0cf39084faa
