### ISSUE TITLE
Consolidate User's View History

### ISSUE THREAD

**Issue by camjac251** [Tautulli/Tautulli#164]
I converted my PlexWatch DB to PlexPy and really like it. I would like to request a feature though that would make it a lot better for me. I have changed my username 3 times since I started running plexwatch. Is there a way that I can join the older username data with my current one so I can have an accurate watch history? Easiest way I could see as far as the UI goes is selecting the old user and typing in the current username for the Friendly Name field, then it could join them together.

**Comment by JonnyWong16** [comment]
Currently, there is no way to accomplish this in the UI. However, you can edit the plexpy.db manually with a SQLite browser like http://sqlitebrowser.org/

Back up your plexpy.db file first, then you can execute this SQL:

```
UPDATE session_history SET user = replace( user, 'old_username', 'new_username' ) WHERE user LIKE 'old_username';
UPDATE session_history SET user_id = replace( user_id, 'old_user_id', 'new_user_id' ) WHERE user_id LIKE 'old_user_id';
```

Replace `old_username` and `new_username` with the names you want to change, and `old_user_id` and `new_user_id` with the user ids you want to change.

**Comment by drzoidberg33** [comment]
I think this is something that should remain a manual process if somebody want to do this. Use Jonny's example above.

We won't work directly with usernames on a fresh install (only with user_ids) so this should not be an issue with 99% of the usage cases out there.
