### ISSUE TITLE
"Local" user?

### ISSUE THREAD

**Issue by fduchene** [Tautulli/Tautulli#165]
With the latest version, a "Local" user is created, appears in the user list with all the infos "N/A".

![capture d ecran 2015-09-07 a 13 18 15](https://cloud.githubusercontent.com/assets/2494283/9715676/f52cc146-5562-11e5-8988-c825167bd0e7.png)

Looking in the log :

06-Sep-2015 16:05:14 - INFO    :: MainThread : Checking to see if the database has all tables....
06-Sep-2015 16:05:14 - DEBUG   :: MainThread : User "Local" does not exist. Adding user.

**Comment by drzoidberg33** [comment]
Somebody asked this on the Plex forum also, here is the answer from that thread:

> The Local user was added as it is necessary. If an unauthenticated user streams something it will show as Local for the user. This actually addresses a bug where the user list would be refreshed constantly when looking for this user as it doesn't get pulled like normal users from plex.tv.
> You cannot and should not delete this user.

**Comment by fduchene** [comment]
Thanks! For "cosmetic" reasons, is it possible to add a "Show unauthenticated streams" checkbox somewhere in the settings that would hide/display the Local user?

**Comment by drzoidberg33** [comment]
I know JonnyWong was working on a feature to show/hide users in the Users list, it's just not complete yet.

**Comment by JonnyWong16** [comment]
Still working on it.

**Comment by lampemw** [comment]
Hey, I see this was closed a few months ago, but I just encountered this.  I was looking through users and noticed a user named Local, so I deleted it without thinking anything of it.  PlexPy still seems to be running okay, but I wanted to make sure that I didn't mess anything up on the backend or need to reinstall PlexPy.  Or if it actually deleted that user from the Plex Server.

I also see that drzoidberg33 stated that "You cannot and should not delete this user" but I was still able to delete it, so maybe things have change since september.  Let me know if I need to open this as a new issue or if I was okay in re-opening this issue, as I have hardly ever written issues for github repos.

**Comment by JonnyWong16** [comment]
It's fine, PlexPy should continue to function properly. The delete feature actually only hides the user from showing up. 

If you want to get the user back you can go to

```
http://localhost:8181/undelete_user?username=Local
```

**Comment by lampemw** [comment]
Awesome, that is exactly what I wanted.  Even though the local user didn't have any info, it was making me paranoid not having that user listed any longer and wondering if I messed things up.

So what exactly is that local user for?  Is there any situation where data would be recorded for that user watching a show? Perhaps if I watched something directly on the server?

Also, do you is there a list somewhere of API commands such as undelete_user that I can use with PlexPy?  I am getting more and more into writing my own scripts and would be nice to possibly interface with PlexPy.

**Comment by JonnyWong16** [comment]
Exactly. If you watch directly on the server without any user login. 

There is an API v2 in the works, but it will be a while before it is ready.

**Comment by lampemw** [comment]
Awesome, thank you so much for the quick responses and the help.  Much appreciated.

On December 23, 2015 at 11:11:08 PM, JonnyWong16 (notifications@github.com) wrote:

Exactly. If you watch directly on the server without any user login.

There is an API v2 in the works, but it will be a while before it is ready.

**Comment by steetiehj** [comment]
I'm getting Local user appear and streaming stuff.. I've actually no idea who it is? 

2016-06-11  Local   ##.##.##.## Safari  
 Plex Web (Safari)
 House of Cards (US) - Chapter 2 (S1· E2)
1

How can I debug this further to try and find out who it is? Cheers

(Synology install on DSM 6)

**Comment by JonnyWong16** [comment]
Local is anyone who is streaming from your server but is not logged into a Plex account. I would make sure your server is secured and you don't have random people accessing your server. 
https://www.reddit.com/r/PleX/comments/4lwu9l/server_being_claimed_by_someone_else/d3qrfat

**Comment by steetiehj** [comment]
I have one person logged into plex and streaming but comes up local...  cheers

I've added to last of networks that allowed without auth too:

127.0.0.1/255.255.255.255

Is that fine or should it be blank?

**Comment by JonnyWong16** [comment]
Blank means all connections will require a Plex login.

`127.0.0.1/255.255.255.255` means that only the Plex server computer itself does not require a login.
