### ISSUE TITLE
errors in python in 1.1.7

### ISSUE THREAD

**Issue by miniop** [Tautulli/Tautulli#169]
I am getting same error all the time.
I think is ascii / unicode problem as my library and many things are not in English.
(as i remember plexconnect had the same problem before  they fixed it)

![1212](https://cloud.githubusercontent.com/assets/5842145/9735265/30aa4f1a-5642-11e5-9e4c-879967647e4f.png)

**Comment by drzoidberg33** [comment]
I still need to track this down. Could you post a full PlexPy log?

**Comment by miniop** [comment]
I am attaching the logs but it doesnt have any details.

http://www.filedropper.com/plexpy

Is there any option for debug logs ?

**Comment by miniop** [comment]
did you spot this problem ?

**Comment by JonnyWong16** [comment]
Closing this old issue. There have been so many updates it might be fixed.

Reopen the issue if it is still a problem.

**Comment by miniop** [comment]
no its not.
In the logs there is no error the errors are displayed only in the dos prompt

![2](https://cloud.githubusercontent.com/assets/5842145/12538391/5ded4084-c2e1-11e5-80cd-573164aa5974.png)
![1](https://cloud.githubusercontent.com/assets/5842145/12538392/5ded667c-c2e1-11e5-8867-482cd9adf017.png)
