### ISSUE TITLE
Feature request: configure notifications

### ISSUE THREAD

**Issue by kaiguy** [Tautulli/Tautulli#17]
The only thing I miss from PlexWatch is the ability to customize the notifications.  

For example, using Pushover, instead of just getting "Playback started" for the notification title, PlexWatch defaulted to having the user's name in the title, providing meaningful information at a glance.  Also, it was nice being able to see whether the item was being transcoded or direct played, and having SxxExx on TV shows was a helpful feature as well (to see when someone is churning through a season).

Just a humble request.  This is already becoming such a powerful tool!  Thanks so much!

**Comment by drzoidberg33** [comment]
Yep, I agree. Notifications do need some work.

**Comment by tylordurton** [comment]
Would also be good to have greater control over notifications (for example exclude trailer streams if required).

**Comment by drzoidberg33** [comment]
Notifications are coming together. I've just added the initial implementation to customise the text sent for notifications. I still need to add more fields but at least you can change things around a bit now.

@tylordurton Trailer streams and other 'clips' (like channels) already don't generate notifications neither do they get logged.

**Comment by drzoidberg33** [comment]
I think all this has been taken care of in the latest commit https://github.com/drzoidberg33/plexpy/commit/824d4dfea2e0660353e29f2d945934d5407a1262.

If there are bugs please open new issues.

**Comment by tylordurton** [comment]
Hi drzoidberg33,

I can confirm that I don't receive notifications for clips/trailers but my movie intro is triggering a notification, can this be prevented as it is skewing my stats?

Regards
Tylor

**Comment by drzoidberg33** [comment]
@tylordurton Only movie, tv and track items trigger notifications (if set), if an item is triggering a notification then it must be one of those.

If you don't want a certain media item triggering a notification then that would be a new feature request.

**Comment by tylordurton** [comment]
I'm surprised it has not been mentioned earlier, it's the intro feature plex introduced (when they also launched trailers). I have a custom 20th century fox intro that plays before every movie, this never used to get picked up by PlexWatch/Web? The trailer is not triggered but for some reason the intro is so most likely treating it like a movie when it's just a clip?

**Comment by drzoidberg33** [comment]
I'll have to see if there is something that distinguishes these from a normal movie items.

**Comment by tylordurton** [comment]
Ok no problem, just let me know if you need any testing/logs or general assistance.

Thanks again
