### ISSUE TITLE
Adding html login

### ISSUE THREAD

**Issue by camjac251** [Tautulli/Tautulli#171]
Would it be possible to add an html login instead of using an http login?  I would like plexpy to use a cookie and automatically log me in as right now it asks for authentication everytime I open my browser.

**Comment by camjac251** [comment]
Also a "remember me" option with no expiration

**Comment by drzoidberg33** [comment]
See here: https://github.com/drzoidberg33/plexpy/issues/54

**Comment by camjac251** [comment]
Sorry :/
