### ISSUE TITLE
[Feature Request] Server Stats

### ISSUE THREAD

**Issue by Foebik** [Tautulli/Tautulli#175]
I'm pretty sure I read this request somewhere else, but couldn't find it.

So I ran across this package and was wondering if a dev could maybe glance at it and see if this is something we could use to add a server stats page? Just a thought, would be really cool to have.

https://pypi.python.org/pypi/psutil

**Comment by Arcanemagus** [comment]
The problem with server stats is you have no guarantee that PlexPy is running on the same server as Plex. (I know in my setup at least it isn't)

**Comment by Foebik** [comment]
Agreed. In those situations there is an added layer of complexity. 
I'm just guessing here, but I think the percentage of people that have PlexPy installed locally is far higher than those that do not. (maybe take a poll somewhere?)
But if there is in option in the settings asking if it is installed locally then something like this can become visible to use, otherwise it is just a hidden setting.

**Comment by curlz620** [comment]
Mine is installed on a different machine than my plex server.

**Comment by Hellowlol** [comment]
You can take a look on how htpc-manager uses psutil if your interested in adding this to plexpy

**Comment by Foebik** [comment]
@Hellowlol 
PSutil is the link I originally posted. If it is not difficult to implement, I would love to see this integrated. I know Plexpy has to be local install to the server that you want to monitor and some people run Plexpy from a different computer. But those people will have to know the limitations of making such a setup and most likely already have alternatives.

If there is something out there that can do local and remote installs work then that would be even better. I just haven't found it.

**Comment by Hellowlol** [comment]
Its easy to add support for that. HTPC-Manager uses psutil for local stats and openhardware monitor for remote stats (supports linux and wimdows) Maybe you can look into that.

**Comment by Foebik** [comment]
I've looked at HTPC-Manager before. I thought it was pretty cool. But it doesn't seem to support most of the clients I use (NZBGet, Sonarr and Plex) so I haven't check it out further than just looking at the screen caps.

**Comment by Hellowlol** [comment]
@Foebik the webpage hasn't been updated in ages. My fork support all the apps you mentioned :) oh I meant look into open hardware monitor.

**Comment by Foebik** [comment]
Pretty cool, I got the computer stats the work right away. That's the kind of stuff that I think would be neat in PlexPy.

**Comment by majora2007** [comment]
I wrote something in a few mins to demonstrate how Psutil would be able to calculate uptime and other server stats. In the case of a remote connection, sshing into the machine would be the simplest solution.

Here is my code if anyone wants to look at it: https://gist.github.com/majora2007/e0cb2c80a1641cb7b732

**Comment by DrEVILish** [comment]
Feature Request:
Log Server Stats and Perf Data
to monitor media bottlenecks and ability to correlate data to videos watched, codecs played devices streamed to. etc. to see what needs more power or if a certain device / codec is causing a system hog.

My Plex Server currently is 3 computers + NAS

1 for Plex Media Server
1 Synology NAS
2 for offhost transcoding see here for details: https://github.com/wnielson/Plex-Remote-Transcoder

Would be cool to add the ability to monitor more than one machine. I dare say a lot of people store their media in a NAS, would be nice to monitor the relative performance of each of these systems in the chain.

All of my servers have SSH enabled with a "plex" user, that does all the talking and signaling to all my systems. Installing a small python script on each system using the plex user every 5mins to receive data about the network. PlexPy -> SSH -> SERVER (run data collector) -> reply

This could be completely backwards thinking.

**Comment by dot-mike** [comment]
This is very much interesting, but people might run Plex on docker or similar which might create issues.

I suggest closing this issue, as PlexPy is focusing on improving the Plex administrator experience and NOT server monitoring or real time data regarding CPU, memory, IO statistics and so on.

If you really are interesting in such things, look into Collectd and set it up with Graphite. Then you got your logging going.

@Hellowlol Any thoughts?

**Comment by Hellowlol** [comment]
I like the suggestion. While plexpy isn't app to monitor hardware I can see some benefit with this. We could check the cpu usage every minute and log it to a new db table. Combined with watch history you can see when/if you need to upgrade. 

Imo you shouldn't be running plex on anything less then i7, as for the docker users they can make a new docker with both plex and plexpy. 

Is a "nice" to have feature, but I don't think it would use it more then 3 times. Just like the data added over time pr I sent

**Comment by DrEVILish** [comment]
I'm transitioning my PLEX environment to docker the idea of docker is to totally isolate each item. ie. PlexPy should not run on the Plex container. If I want to update / restart PlexPy I don't want my active plex server to have to be stopped / restarted at the same time.

Maybe to change that keep a log of the transcoding speeds (average per video?), and alert if <1 and ability to correlate the data to the played video files, resolution and codecs. To see if the CPU is actually struggling with the transcode jobs, without having to have PlexPy and Plex running in the same logical environment.

This would still give you an idea if you need to upgrade your CPU or if you should instead pre-transcode your footage into something that your CPU is better capable of handling.

**Comment by Hellowlol** [comment]
I know ill always run mine in a combined environment atlest until plex api is better. I think ppl are docker crazy and is isolating way to much. Ps, you dont need to shutdown the docker to update plexpy. Just as same as you dont need to shutdown your computer to update plexpy.

**Comment by ezspot** [comment]
I would love this! Then i could just skip to use HTPC as a side install. Becuase i'm only using it for the Machine stats, like CPU,HDD and stuff. Assume this is something that is needed: https://github.com/styxit/HTPC-Manager/blob/master/modules/stats.py

**Comment by Hellowlol** [comment]
That version of http manager has many broken modules. Even the stat module (the module that you linked to) is broken because of some changes to psutil. 

Disclaimer: I wrote that module for htpc manager.

**Comment by ezspot** [comment]
@Hellowlol Aha, see it now :) - But is it hard to implement that stuff into PlexPy? Just the CPU and HDD part, it's kinda what's important.

**Comment by Foebik** [comment]
Yeah, I see this as a perfect fit for PlexPy and definitely within the scope of the project. I use PlexPy now to watch for actively levels and stress on the hardware (aka direct vs transcode) or when how many concurrent streams starts kicking off buffering issues. Also use PlexPy to help determine what to videos to drop when space gets low (drive monitoring mixed in would be awesome). To be able to determine what file types or at least which movies are causing the most stress to my CPU would also be a huge win.

**Comment by ezspot** [comment]
This feature could easy be inside the "Graphs", and enabled if Plex and PlexPy is installed on the same machine. - Would be awesome......

**Comment by ezspot** [comment]
Could anyone with enough skills add this please? @Hellowlol pointing to you :D
This could be implemented like a tab: https://github.com/deepwather/plexDash ?

**Comment by Hellowlol** [comment]
It would be "easy" to add support for it. But dont point at me. I dont need this feature and im busy with a new project. :P

**Comment by JonnyWong16** [comment]
Nothing is ever "easy". Asking repeatedly won't make it go any faster, just gets kinda annoying. And I'm on vacation.

Edit: To clarify, contributing ideas and solutions are welcome, asking someone to work on it is not ok. We all work on these project for free on our own time.

**Comment by mcmaxl** [comment]
Would also love to see this feature. Like @DrEVILish said, correlating transcoding videos and cpu usage would be awesome. And the beautiful graphs this would make... ;)

**Comment by filoor** [comment]
Like to see cpu could load
