### ISSUE TITLE
Time spent paused is included in play duration on the graphs

### ISSUE THREAD

**Issue by ericjeney** [Tautulli/Tautulli#176]
My graphs of play duration are greatly skewed by a couple of users who often pause what they're watching for hours at a time. This has the effect of greatly inflating the reported play duration, essentially making those graphs useless to me. Duration is properly calculated in the Users -> History page (under the heading "Duration"), while the Graphs page seems to just do stopped time - started time.

**Comment by drzoidberg33** [comment]
Fixed in https://github.com/drzoidberg33/plexpy/commit/e386d3ee21863b1687f307915057d0cf39084faa
