### ISSUE TITLE
Synced media not showing after being watched

### ISSUE THREAD

**Issue by pawnynz** [Tautulli/Tautulli#178]
When media that has been synced and downloaded to a device (iPad) is watched and synced back to Plex, PlexPy as not displaying these items. The device doesn't show as a recently used player and the media doesn't show as recently watched.

**Comment by drzoidberg33** [comment]
This isn't something PlexPy can do. Unless you're watching synced content while connected to the internet (which I know works on the new iOS app), the only way PlexPy can retrieve the information it needs is by pinging the server and asking what's going on.

If the Plex server doesn't know that there is a stream playing, PlexPy will not log an item.

Watch statutes do not count as they're just an on or off switch, it doesn't have any information on the playback period, metadata or stream quality info.
