### ISSUE TITLE
More graph ideas.

### ISSUE THREAD

**Issue by Elrique64** [Tautulli/Tautulli#18]
I should probably add these all as separate requests, but they all deal with graphing...

When you hover the mouse over a day in the main graph, it shows you how many TV shows and Movies get watched on the given day.  It would be nice to have it show the actual shows/movies when you click on the given day.  (Just a little pop up.)  

Right now you have the Most Active Platform on the home page.  Would it be possible to have a graph showing the clients, say in the last 30 days, listing all of the client apps that have watched a stream.  Helps to know how many clients the admin has to support.

Transcode vs DP, vs DS.  A graph showing how much has been transcoded vs direct played vs direct streamed, and can click on either to see what show were affected.  I'm thinking something like the main graph, but 3 traces.  Click on a day and it gives a report of the day, showing what, how, and who.  Could be useful for setting clients up correctly for your server or finding problem media files.

**Comment by tylordurton** [comment]
+1

Is it also possible to have a monthly count of total plays (similar to PlexWatchWeb)?

**Comment by Foebik** [comment]
+1 for
Transcode vs DP, vs DS. A graph showing how much has been transcoded vs direct played vs direct streamed

**Comment by nomadore** [comment]
@Foebik that's a great idea for a graph.

**Comment by drzoidberg33** [comment]
Plays by top 10 platforms added in https://github.com/drzoidberg33/plexpy/commit/94d2d04bf9b343a55d0ed011a3a21ddc40edafb4

More graphs on the way.

**Comment by drzoidberg33** [comment]
History modal popup for daily views added in https://github.com/drzoidberg33/plexpy/commit/45885074264c2ab79c4ded28e099baf7019a9d81

**Comment by mbnn** [comment]
Would it be possible to include Top TV Show (last 30 days), Top Users (Top 10) of last 30 days and Top Movies (last 30 days)? :)

**Comment by drzoidberg33** [comment]
@mbnn Top Users is already there. I'm still working on adding more graphs.

**Comment by mbnn** [comment]
Cool, good to hear :) Love plexpy so far, very handy!

**Comment by drzoidberg33** [comment]
Transcode decision graph added in https://github.com/drzoidberg33/plexpy/commit/7f75966f435d40f4c520f375ff55066ec79fea17

That covers the original request. Please add new requests or bug reports for anything else graph-related.

**Comment by drzoidberg33** [comment]
Please note that Plex isn't always very generous with information and often the API doesn't provide a resolution for transcoded streams, this is when you'll see the "unknown" resolution for the resolution graphs.

Also version 0.9.12.4 of PMS was completely broken with regards to transcode decision information - this version of Plex reported everything as direct play even when items were being transcoded. Any items logged during the time using this version will provide incorrect data for the transcode decision graph.

**Comment by Foebik** [comment]
I like it!
