### ISSUE TITLE
[Feature Request] play count against each media item

### ISSUE THREAD

**Issue by tylordurton** [Tautulli/Tautulli#181]
Would it be possible to add a total play count against a how once drilled into from History at the top of the page (next to the star rating for example) ?
Also would be useful to see the play count at a user level broken down between Movie & Tv in the stack graph [like it does on the overall play count)

**Comment by JonnyWong16** [comment]
I you scroll to the bottom of the page it should say "Showing X to Y of Z history items..."
Z is the total play count.

Separating Movie/TV/Music in the stacked graphs is already implemented in #177. :smile:

**Comment by tylordurton** [comment]
Thanks for confirming the first point, on the second should I read this as this is live now?
I'm sure I have the latest build 1.18 but don't see a stack graph on the user graphs

**Comment by JonnyWong16** [comment]
It is currently in the dev channel, and will be included in master with the next update.

**Comment by tylordurton** [comment]
Got ya - thx :-)

**Comment by drzoidberg33** [comment]
Resolved.
