### ISSUE TITLE
[Feature Request] Most Concurrent Streams Log / Graph / Stats

### ISSUE THREAD

**Issue by rickcab1** [Tautulli/Tautulli#184]
First off much props on the app!  I love it!  Moved over from PlexNotify > PlexWatchWeb > now PlexPy!

I was wondering if it might be possible to get "Most Concurrent Streams" in the graphs and logs.  I thought that was useful to me to gauge data during peak times to see how my server is handling all the concurrent streams at one time and I can also look at my BW usage at the time it happens to see if I need to upgrade or make adjustments.  Thanks!   Keep up the good work and I hope to definitely not only donate monetarily soon to this project but give some decent feedback as well.

**Comment by Foebik** [comment]
+1

**Comment by curlz620** [comment]
+1

**Comment by majora2007** [comment]
+1

**Comment by krsandvik** [comment]
+1

**Comment by zobe123** [comment]
+1

**Comment by rickcab1** [comment]
Hey guys just wondering if you guys have given this one any cycles to try and implement?

**Comment by rickcab1** [comment]
Hey guys I am no developer at all so feel free to slap me virtually.  I was just wondering since the PlexWatch code is already out there; is the feature that shows most concurrent streams easily adaptable into PlexPy to introduce this data stat?

**Comment by JonnyWong16** [comment]
I don't think anyone has looked into this yet.

I don't remember this in PlexWatch. Basically something like this?

```
Most Concurrent Streams
Dec. 10, 2015 6:45pm
4 streams
```

**Comment by Arcanemagus** [comment]
@rickcab1 Are you talking about the "Max hourly plays" chart? That was never the number of concurrent streams but rather the number of plays recorded for that hour.

**Comment by rickcab1** [comment]
@Arcanemagus let me see if I can get you guys a screen shot.  Shoot this was in PLexNotify not PlexWatch (dont worry I just slapped myself)  Here is the screen shot:v

![image](https://cloud.githubusercontent.com/assets/14242464/11725297/db0f5250-9f2d-11e5-85a2-2194abd6d8b1.png)

Basically it keeps track of the most simultaneous streams that occurred while monitoring is enabled.  This will allow me to see what the server can sustain.  If a time and date stamp could be also included it would allow me to check other statistical data to look how the server was performing at that given time to see if I need to upgrade any resource allocation or bandwidth etc.   Let me know if that makes sense.

**Comment by Arcanemagus** [comment]
I'm not positive as I haven't dug into their code, but I would bet that they are simply taking the maximum number from the chart above, which is the same information plexWatch/Web showed, which is _not_ the actual number of concurrent streams (but is usually a pretty good estimate unless your users are watching many small things).

For reference this is what the same data looks like in plexWatch/Web:
![image](https://cloud.githubusercontent.com/assets/427137/11725590/59089b02-9f2f-11e5-8561-cf79a6a390ab.png)

It doesn't look like PlexPy currently has a chart like this, but that chart isn't really what you are asking for, although the real information can probably be calculated from the history information.

**Comment by JonnyWong16** [comment]
If someone can figure out the logic (SQL query) I'll take a look at it.

I.e. `stop time on line n > start time on line n+1 and n+2 and n+3`, etc. and keep a running count, and restart `n` when needed.

**Comment by rickcab1** [comment]
@JohnnyWong16

That's about right what you had posted above:

Most Concurrent Streams
Dec. 10, 2015 6:45pm
4 streams

**Comment by JonnyWong16** [comment]
[Relevant problem](https://stackoverflow.com/Questions/19155454/find-the-time-period-with-the-maximum-number-of-overlapping-intervals).

Someone find me a good icon to use
![](http://i.imgur.com/NVMSOUW.png)

**Comment by drzoidberg33** [comment]
@JonnyWong16 Maybe something like this: https://cdn1.iconfinder.com/data/icons/basic-ui-elements-round/700/06_menu_bullet_unjustified-2-512.png
- Basically a list icon

**Comment by zobe123** [comment]
If you like, i will try to create a mix of these: http://sparklink.co/wp-content/uploads/2015/06/Business_intelligence2.png

https://lh3.ggpht.com/kMZIw5nVEiXSVdIQA9uIZuzkTH4z3-Pe4X4Qm4P20cvJbLi-tR4qJ0dab7nvAu8_Vvg=w300

**Comment by JonnyWong16** [comment]
Hmm...good idea, but it's not really a graph.

What about something similar to the list icon, but change the three bars to right pointing arrows (of different length)? I can throw something together when I get home.

**Comment by zobe123** [comment]
maybe this is what you meant:
![arrow_icon](https://cloud.githubusercontent.com/assets/13840542/11757146/54aa4980-a05f-11e5-808c-c099f5bdd7b1.png)
this was in my mind:
![graph_flat](https://cloud.githubusercontent.com/assets/13840542/11757149/5b89b4f2-a05f-11e5-8eb5-0b7afcf27bc1.png)
also a simple Play logo could serve the purpose:
![play_flat](https://cloud.githubusercontent.com/assets/13840542/11757154/6405a5e6-a05f-11e5-9c93-d4a25495bca8.png)

**Comment by JonnyWong16** [comment]
Yeah, the first one was what I was describing.

Can you send me your source files? I just want to modify it slightly.

**Comment by zobe123** [comment]
can't upload it as psd or zip. pls rename it yourself to poster.psd
[poster.pdf](https://github.com/drzoidberg33/plexpy/files/60271/poster.pdf)

**Comment by rickcab1** [comment]
Awesome! Now you guys got me as excited as a kid waiting for Santa to come down that chimney! Cant wait!

**Comment by zobe123** [comment]
there is something wrong with the "Most Concurrent Streams" - Watch Statistic. when i had activated it was "6" - then 5 min later it was "7" and after a full server restart it shows "8". always with same date and time.

**Comment by JonnyWong16** [comment]
Interesting...Any ideas why?

**Comment by zobe123** [comment]
Mhmm... Now after I have made a few thoughts about it is calculated, maybe it is because multiple persons watching with the same account at the same time. Maybe there is a missing start or stop in my plexpy.db 
...btw actually its counting "9"

**Comment by JonnyWong16** [comment]
Can you PM me your `plexpy.db` file on the forum so I can take a look?

**Comment by zobe123** [comment]
really!? ...i didn't guess how to PM you 

[removed for privacy] - JonnyWong16

**Comment by JonnyWong16** [comment]
Thanks. I found the bug and it should be fixed in 3eebb58.

**Comment by zobe123** [comment]
...incredible fast! Thx, now it shows "6" that seems to be correct. I'll keep an eye on😉

**Comment by JonnyWong16** [comment]
Should be good now. Released in v1.2.15.

**Comment by rickcab1** [comment]
OK let me just say you all rock!  I just updated last night only to have Santa drop off the following to me!!

![image](https://cloud.githubusercontent.com/assets/14242464/11936641/10e27f08-a7c4-11e5-8e33-546b06c8dde6.png)

I had a question now that I have added a Music Library.  Is the data taken from Movies and Music together?  If so would it be difficult to get one for movies and one for Music and would it be a separate feature request?

**Comment by JonnyWong16** [comment]
It's all movies/tv shows/music together. It also doesn't take into account direct play/direct stream/transcode.

I'll reopen this request for possibly implementing separate stats in the future.

**Comment by zobe123** [comment]
Maybe i found another bug, plexpy shows actually 6 streams, there were already 7streams and then i started anotherone by myself, so it should count 8streams. 
The value for date switched but not the counter.

**Comment by JonnyWong16** [comment]
Did all the streams stop?

**Comment by zobe123** [comment]
Sure, I've been waiting overnight and made a restart.

**Comment by rickcab1** [comment]
Devs,

Question.  Running 1.2.16 and have my most streams currently showing 6 back on 11-07-15.  I now have 7 streams going at once and was just wondering when its supposed to trigger the next level to 7 in my case? I refresh the page and nothing BTW,.

**Comment by JonnyWong16** [comment]
The stats only pull data from the database, so any current activity won't be reflected in the stats.

Wait for all the streams to stop and it should show 7 streams.

**Comment by rickcab1** [comment]
Oh OK wait and update once all the streams stop.  Thanks @JonnyWong16

**Comment by zobe123** [comment]
Yeah, pls make feedback after stopping, great interest in. But I think i'm not the only one who has this problem, so only the timestamp will change.

**Comment by rickcab1** [comment]
OK I checked this morning and it looks like it changed to reflect last night activity:

![image](https://cloud.githubusercontent.com/assets/14242464/12022705/4582700a-ad47-11e5-881e-41ea735a609c.png)

**Comment by zobe123** [comment]
maybe I was wrong with my assumption that "Most concurrent stream" counts wrong. Another day, again 7 streams and now it has counts like it should two times. 
- But at what point is a stream counted? immediately or only after the "Ignore Interval" setting under Monitoring is reached?
- has the setting "Keep History" under the user Settings any effect to this?
- how the "Local" user is counted?

**Comment by JonnyWong16** [comment]
Basically it follows any of the logging rules, since it calculates based on history in the database.
- Item logged after stopping and stream duration longer than ignore interval.
- "Keep history" is enabled for the user.
- Local user should work like any other user in this case.

**Comment by wilsonic** [comment]
Are there any plans to expand this to graphs and notifications? Would love to be able to send a notification whenever Plex is streaming to more than 'n' people at once as well as see the data over time.

**Comment by Hellowlol** [comment]
@wilsonic you can use the script notification for stuff like that.
