### ISSUE TITLE
Bug - Homepage statistics - timeframe less than 5 days

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#186]
There is a bug/error when the timeframe is below than 5 day, see below error. Nothing gets logged in the log file.

 PlexPy Version 1.1.8 

``` html
Error !
ValueError: invalid literal for int() with base 10: 'None'
DOCUMENTATION :: END </%doc> <%! from plexpy import helpers # Human readable duration def hd(minutes): if int(minutes) > 60:
/opt/plexpy/data/interfaces/default/home_stats.html, line 50:
<%!
/opt/plexpy/data/interfaces/default/home_stats.html, line 439:
${top_stat['rows'][loop.index]['total_duration'] | hd}
lib/mako/runtime.py, line 860:
callable_(context, *args, **kwargs)
lib/mako/runtime.py, line 835:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
lib/mako/runtime.py, line 803:
**_kwargs_for_callable(callable_, data))
lib/mako/template.py, line 443:
return runtime._render(self, self.callable_, args, data)
/opt/plexpy/plexpy/webserve.py, line 48:
return template.render(**kwargs)
```

**Comment by JonnyWong16** [comment]
This isn't a problem with the time frame. I think it's something in your database goes wrong when it tries to pull the stats when it's less than 5 days.

This might be fixed already. I changed the code for this in a recent update. If you can, try switching to the dev branch to see if the issue is still there, and report back.

**Comment by elRadix** [comment]
indeed, in dev this issue is resolved

**Comment by drzoidberg33** [comment]
The new version has been pushed to master. https://github.com/drzoidberg33/plexpy/commit/e386d3ee21863b1687f307915057d0cf39084faa
