### ISSUE TITLE
[Issue] [Resolved] - IP Logging was working now not working

### ISSUE THREAD

**Issue by rickcab1** [Tautulli/Tautulli#187]
Hey guys.  So weird thing happened after a reboot.  I rebooted my Windows Server 2008 R2 Server over the weekend.  Now my IP Logging is back to "N/A" and no longer logging IP's of clients.  I did the most recent update of PMS and it required my server to restart.  Any ideas on how to resolve?  I toggled the IP Logging on and off and no change as well. 

![image](https://cloud.githubusercontent.com/assets/14242464/9855785/631269a6-5ac5-11e5-8d02-82783796ce16.png)

**Comment by rickcab1** [comment]
Actually Self resolved.  Looks like I had some corruption in the files in the PlugIN's bundle on my PMS.  After deleting the bundles the issue still was there and the server page was still unavailable in the PMS server tab.  I went in a did a repair of my OMS install and that seems to have fixed the issue with PMS and as well as the IP Logging issue.

**Comment by drzoidberg33** [comment]
Thanks for updating. I'm closing this.
