### ISSUE TITLE
Importing stats from previous plexpy install

### ISSUE THREAD

**Issue by bonyboy** [Tautulli/Tautulli#188]
For some reason, I got stuck on 1.1.7 and the application wouldn't update itself, so I pulled it down again after the update to 1.1.9 and now my user stats are gone.  Is that information in a file that I can just copy/paste into the new directory?

**Comment by JonnyWong16** [comment]
Shut down PlexPy, copy `plexpy.db` and `config.ini` from your old install folder to your new install folder, and restart PlexPy.

**Comment by bonyboy** [comment]
I was hoping for something like this.  Thanks for the reply!
