### ISSUE TITLE
Can't save config from web

### ISSUE THREAD

**Issue by MaartenMol** [Tautulli/Tautulli#19]
I can't seem to save the config from the web. Just changed a check mark and hit "save" it then said in a red bar "Please verify your settings"

Am i doing something wrong here? Or is this a bug?

**Comment by drzoidberg33** [comment]
Bug and fixed: https://github.com/drzoidberg33/plexpy/commit/a1f52d2bc8fb922bc1bf3b827ab938565d623678

**Comment by MaartenMol** [comment]
Great! thx! Already better than PlexWatch, I really like it!!!
