### ISSUE TITLE
Transcode / DirectStream miss match

### ISSUE THREAD

**Issue by ashleyuk90** [Tautulli/Tautulli#191]
I have seen a couple of times a item will show as transcoding, however both Video & Audio show as Direct Stream with a transcode speed of (0.0) always in a (Throttled) state.

This is with files that are converted to MP4(H264) & 2 Channel AAC which I know are DirectPlay compitable.

Looks more like a miss presentation within PlexPy, I have attached an image showing an example, if log's are required please let me know.

![tran](https://cloud.githubusercontent.com/assets/14320114/9918740/80104242-5cc0-11e5-94db-ce0aefc85259.PNG)

**Comment by JonnyWong16** [comment]
Hm...I've always been king of confused with Plex's direct play/direct stream/transcode.

Seems like a simple logic fix. Is this correct?
- If video OR audio is transcode, then stream is transcode.
- Else if video OR audio is direct stream, then stream is direct stream
- Else if video AND audio is direct play, then stream is direct play

**Comment by ashleyuk90** [comment]
Sounds correct to me, not sure where the transcoding is coming from, but im sure it isnt actually transcoding, nothing in the log's to show a transcode session for that user/file.

**Comment by Arcanemagus** [comment]
You do mean AND for that second point, right @JonnyWong16?

**Comment by Arcanemagus** [comment]
Here is how I always thought it worked:

| Container | Video | Audio | Play State |
| --- | --- | --- | --- |
| Compatible | Direct | Direct | Direct Play |
| Incompatible | Direct | Direct | Direct Stream |
| ------------ | Transcode | ------------ | Transcode |
| ------------ | ------------ | Transcode | Transcode |

Container compatibility being on the client side, of course.

**Comment by Arcanemagus** [comment]
Here is the official source on the matter, but as far as I can see my table above summarizes it: https://support.plex.tv/hc/en-us/articles/200250387-Streaming-Media-Direct-Play-and-Direct-Stream

**Comment by ashleyuk90** [comment]
@Arcanemagus  Yup agree with what your saying, somewhere the logic is broken or PlexPy is being fed something its not expecting.

**Comment by JonnyWong16** [comment]
@Arcanemagus

I used OR because I assumed these are possible combinations. Am I wrong?

| Video Container | Audio Container | Video | Audio | Play State |
| --- | --- | --- | --- | --- |
| Compatible | Incompatible | Direct Play | Direct Stream | Direct Stream |
| Incompatible | Compatible | Direct Stream | Direct Play | Direct Stream |

**Comment by ashleyuk90** [comment]
Direct Play is where everything is fine and nothing needs to be completed (this only a play state)

The only two options for Video/Audio are Direct Stream / Transcode.

The options for Play State are Direct Stream / Transcode / Direct Play

**Comment by Arcanemagus** [comment]
@JonnyWong16 @ashleyuk90 beat me to it. One could even argue that the chart is wrong and _anything_ other than DirectPlay should show as Transcode for the "Play State" as the server has to do some sort of work to get the media to the client.

Also there is no such thing as separate Video and Audio containers, all the media is always within a single container (barring those crazy subtitles).

**Comment by JonnyWong16** [comment]
@Arcanemagus That's the current logic, anything not "Direct Play" is "Transcode", but it's an easy fix to include a "Direct Stream" state.

**Comment by ashleyuk90** [comment]
@JonnyWong16 @Arcanemagus What charts do you mean? The charts I see already break it down into the 3 sections, its more about changing the logic I think that PlexPy uses to show the information on the ! on the dashboard.

Which is causing things to be listed as a transcode in the History e.t.c when actually it was just a DirectStream. Small logic change I guess.

**Comment by Arcanemagus** [comment]
@ashleyuk90 I meant the one I wrote just earlier in this thread, sorry :stuck_out_tongue:.

@JonnyWong16 I do rather like the idea of having is shown as a unique state from transcoding (as translating the container is essentially a free operation). If you split it out the earlier chart would be perfect since as @ashleyuk90 said there is no such thing as "DirectPlay" on an individual stream.

**Comment by JonnyWong16** [comment]
Fixed in 1f3a238 in #189.

The logic in the history table seems to correctly display the three states.

**Comment by ashleyuk90** [comment]
@JonnyWong16 Will await for this to be pushed and will test and come back with feedback.

**Comment by drzoidberg33** [comment]
Released.
