### ISSUE TITLE
[Feature Request] - Stats / Graph on Least Watched Movies and TV Shows

### ISSUE THREAD

**Issue by rickcab1** [Tautulli/Tautulli#192]
Hey guys,

As my servers libraries expand and I am constantly upgrading HDD's every year to accommodate new content I was thinking it would be great to pull up data on what users are NOT Watching.  I find it useful to know whats HOT and popular but even more so I would love to see a reverse count of watches on my entire library to see what can be eliminated or archived for more active content.  I guess it might be a two prong request:
1.  Would you be able to show me whats most popular and being watched the most; ranking the entire library spiting TV and Movies?
2. Would you also be able to show the exact opposite for what has never been watch and / or watched the least in ranking the entire library folder?

This would allow me to determine what to pull down off the servers to free up space for possibly better content for my user base,

Please let me know if that makes sense or if it doesn't then I can re-write it if necessary as I tend to ramble.  And thanks again!

**Comment by Foebik** [comment]
+1 If this is possible it would be one of the biggest features for me and using PlexPy.

**Comment by SAKUJ0** [comment]
Now, if we do this right, we want to be able to browse TV shows fully. Plexpy already implies this. When you click a tv show / season / episode, it will link up the hierarchy on top.

Every level of said hierarchy is clickable, except for the first one: The root level of tv shows.

We need to make this clickable and offer an easy table, similar to how users or the history are presented. A few variables we are interested in:
- How many users are watching a show?
- How many minutes has a show been watched?

This can be build up on. Variables that are interesting are those that give an idea about the usage pattern. Data can be used to find out if a user seems to ditch a show (at least for the time being). It can be shown if a show is mostly binge watched, or watched in random.

For now, the foundation is important, though! The dashboard is quite nice, but we need a more sophisticated implementation IMHO. I hope I can find time for something like this. I wonder, if I did, if a pull request such as this would be accepted.

**Comment by Foebik** [comment]
I would definitely use features like you described.

**Comment by JonnyWong16** [comment]
@SAKUJ0 When I originally implemented that navigation bar, I intended to add that top level hierarchy (TV show / Movies / Music) to the info pages. I just haven't thought of the best way to display this information or pull all the metadata from Plex efficiently. It's a lot of metadata especially for libraries with thousands of items.

I'm open to ideas.

**Comment by SAKUJ0** [comment]
@JonnyWong16 It is impressive, I suspected exactly that, having read the history of how plexpy has been developed.

For now, the tv-shows table should follow the same UX as i.e. users, just with different columns. Ideally it would allow displaying the library similar to how Plex itself or Sonarr allows that. The important columns would be:
- Show name
- Number of users watching the show
- Duration the show has been watched

The sorting alone would give insane insight into the user base's preferences.

You might be considering to show the history, much like you do after a particular show/season/episode/user is selected. However, as you pointed out, that is a lot of data to present (moreso without being able to filter/group entries nicely).

One approach could be to keep that history browser inside the actual history with strong filtering preferences. A little bit like Plex allows for filtering, but we don't need their whole UX of course. There, one could filter by series/show/user etc.

Once that is implemented, one could expose this inside the other places, either inline or with a simple link. A pop-over like Plex's info or Sonarr's episode info is also a nice way.

For actual content the history is not a user's focus. When a user is under "TV Shows", he likely, primarily wants a tabular representation of all TV shows. Once a user enters the show's hierarchy, he wants similar information about seasons or episodes exposed.

I can certainly help out with some leg work when I have the time. But it is likely best having the collaborator lead the way with his main ideas.

**Comment by JonnyWong16** [comment]
This sounds just like the "Most Watched" and "Most Popular" watch statistics on the homepage, but a complete list of all shows in tabular form.

Getting the watched shows isn't a problem, it's all logged in the PlexPy database. It's the _unwatched_ shows that are the problem, and need to be pulled from Plex. From they way I see it, we would be pulling a lot of metadata just to display a zero beside them.

**Comment by rickcab1** [comment]
Wow I just caught up on the post here. Lots of good thoughts and you guys some sharp guys!  I seriously wish I knew how to code like you all do so I could participate and help more on this stuff and it makes it all the more frustrating at times for me at least.  Its kinda of like if you were all in a room coding I could at least go out and buy the beer and pizza!

Any hoo.   I still think it would be valuable information to know from the perspective of getting to know what people are not watching as I would love to keep the content fresh and also manage the TB's of storage without having to go into 100's of TB's of storage.

**Comment by Hellowlol** [comment]
@JonnyWong16 It is a lot of data to pull from plex, but its pretty fast. (see htpc manager "typeahead" filter sort function for a example)

**Comment by damianeickhoff** [comment]
Are you already looking in to it? (reference to the Developers)

**Comment by Krazypoloc** [comment]
My use case for this feature is purging unwatched content.

So the key datapoints I need are.
1. An "Unwatched" Card on the home page
   This would contain any show that has not been watched. Or a show with a watch status of only episode one.
2. Column information should include
   Show name
   Length of time the show has resided in Plex (just a timestamp would be fine, or a tabulation in total days)
   Show status (Continuing, canceled, ect)

**Comment by Hellowlol** [comment]
I think id prefere a table just for the unwatched show, it you have a extensive collection (like i assume we all do...) it can very long.

**Comment by Krazypoloc** [comment]
Yeah I wouldn't care either way. I'd just like to see Unwatched Items, whether its sexy or not makes no difference to me.

**Comment by damianeickhoff** [comment]
I agree, its not something to make it "complete". Its just for knowing what people don't watch (or almost nobody) so I could remove it from the server. I hope this funcionality would come soon! It would be awesome!

**Comment by SAKUJ0** [comment]
About the unwatched thing, it should likely be exposed to the same 7/30/90 day filter (or maybe even longer term periods). Just because something has been watched 4 years ago it is not quiet "watched".

But I want to emphasize @Krazypoloc's point (funny to stumble upon you here). We want to clear content neither us, our wives, children, friends or other family end up watching. Obviously some stuff we keep regardless, some stuff we clear if it hasn't been watched in a year or more and other we would likely kill off if it has not been touched in weeks or a couple of months.

To get a picture about the latter, and to entirely solve the many redundant "zeroes", I would recommend adding an "unwatched" timer. Why? I want to not only know whether a show is unwatched, but whether it is unwatched for 1-2 months or 8-12 months (the second being a far bigger reason to delete). This is particularly important for sorting! Sorting by this "unwatched" timer would put the least relevant content on top.

**Comment by Hellowlol** [comment]
I have started on this and I'm pretty much finished with the backend. You can find all unwatched items and/or watched item older then xxx. It includes the file paths, file size for each file and total filesize for that show/move/artist. (Just found 350 gb off "the e.r"...)

The query is slow, since it has to do 1 http call for each tvshow/artist to get the file info. But you can drop  file info to speed it up.

I'm not sure how to present it on the web page? Any ideas?

**Comment by JonnyWong16** [comment]
@Hellowlol I was going to add this to #263.

**Comment by Hellowlol** [comment]
@JonnyWong16  feel free to use your own method. You got a better grasp of the code base. The call takes 50ish seconds to run with 1k movies 88 artists and 500 tv shows. 

Edit 23ish sec with file info, 1 sec without

**Comment by JonnyWong16** [comment]
Yeah, this was my concern earlier (scroll up), that'd it be pulling a lot of data. I'd like to see how you implemented it, might give me some ideas

**Comment by Hellowlol** [comment]
Yeah, I'll clean it up and add async http to fetch the file info and a caching method. It have to be some other day, I finally got the iPad/iPhone screens so i can replace the broken glasses.

**Comment by Hellowlol** [comment]
@JonnyWong16 I think it will be fine, its down to 5-6 sec.

**Comment by JonnyWong16** [comment]
Cool, submit a P/R and I'll look at it tonight.

**Comment by Hellowlol** [comment]
@JonnyWong16 https://github.com/drzoidberg33/plexpy/pull/353

**Comment by dot-mike** [comment]
+1. This is very much needed.

**Comment by Cruv** [comment]
PlexPy rocks as it is but this feature would be the cherry on top! I have a server that I have shared with a few people and it would be good to know what shows nobody is watching so I can delete them without running out of space. Keep up the great work!

**Comment by JonnyWong16** [comment]
This has been implemented in the dev branch. There is a new table with the media info for all the items in a library (video/audio details, date added and watched, play count, and file sizes).

We are still testing and fixing bugs, but it should be released soon.

**Comment by Cruv** [comment]
Thanks @JonnyWong16 . I'll experiment with the dev branch tonight just for fun.

**Comment by damianeickhoff** [comment]
When will this be available in the master branch?

**Comment by JonnyWong16** [comment]
The media info table has been on master since v1.3.0.

**Comment by Cruv** [comment]
It is now, at least it is for me on 1.4.0. You can find it by going to Libraries>{Library Name}>Media Info. Then look to the right two columns.

**Comment by damianeickhoff** [comment]
Aaah, you're right! Thanks!
