### ISSUE TITLE
[Feature Request] MAL and Hummingbird.me Notification agents

### ISSUE THREAD

**Issue by FloatingPointVar** [Tautulli/Tautulli#193]
Updates Hummingbird and MAL anime list upon watching an episode of anime... been searching for somthing like this, but its a bit hard to find. also should have an ability to use alternate titles based off of anidb and HAMA.

**Comment by majora2007** [comment]
I think this extends the functionality and purpose of PlexPy. A plugin would be better for Plex, like track.tv plugin.

**Comment by Arcanemagus** [comment]
This would probably also be better handled by a custom script (#25).

**Comment by drzoidberg33** [comment]
As per the above comments, this isn't something PlexPy was designed to do.

Both above suggestions are good ones.
