### ISSUE TITLE
Feature Request: Monthly/Weekly view limits for users

### ISSUE THREAD

**Issue by ghzgod** [Tautulli/Tautulli#194]
Developer,
I was thinking, is there anyway you could implement a system that limits VIEWS per user? For example I set 5 views per week/month for User A and after 5 views it unshares my library until the next week/month rolls over. When the next week rolls over it re shares the library to that user.

I think this would be a great feature to have, plexpy is the best monitoring out there with all the statistics included. You're doing such a great job as a developer and I appreciate it. I am definitely going to donate, you update your software constantly. Thank you!

**Comment by zobe123** [comment]
i think this would be possible but not via plexpy - plexpy 'only' shows you the plex-logfile as human-readable in a nice gui.
you should post this Feature in the plexforums (https://forums.plex.tv/categories/general-discussions-public)

**Comment by drzoidberg33** [comment]
This isn't something PlexPy will do. Plexpy is only for monitoring and notifications and is not designed to interfere with the workings of PMS.
