### ISSUE TITLE
[Feature Request] 'Guest' view of plexpy statistics

### ISSUE THREAD

**Issue by Collisionc** [Tautulli/Tautulli#197]
A read-only version of the web interface would be really nice. I sometimes go through the statistics on my server to see what I should watch next, and I think my family/friends who use my server would also appreciate that, but with the added restriction of not being able to see IP addresses or edit any settings.

A guest login that only allows viewing of "Home", "Graphs" and "History" without the IP Addresses would be awesome.

**Comment by Hellowlol** [comment]
If anybody want to add this they pretty much copy this file https://github.com/Hellowlol/HTPC-Manager/blob/master2/libs/cherrypy/lib/auth2.py

**Comment by whiltseymour** [comment]
+1, it would be nice

**Comment by tylordurton** [comment]
Agree, especially with the new Plex db search facility. I'm sure a locked down view of the Plex/Plexpy stats would be a great addition.

:-)

**Comment by BehrozKarimi** [comment]
+1 maybe permission groups also?

**Comment by brentrahn** [comment]
+1 I was thinking something similar to this - but more along the lines of a status page. Perhaps if we could have some uptime statistics/status that could be integrated into a public facing page for existing plexpy statistics.

**Comment by wcomartin** [comment]
+1 love this idea

Using the Plex Auth would be awesome too, like [PlexRequests](https://github.com/lokenx/plexrequests-meteor) does. we don't necessarily want anybody being able to view our library

**Comment by antoinesylvia** [comment]
+1 would be a great feature, especially if it is tied to a landing page for fam/friends etc..

**Comment by Collisionc** [comment]
Added this enhancement to the feathub -- http://feathub.com/drzoidberg33/plexpy/+2

**Comment by JonnyWong16** [comment]
Added in v1.4.0.

Submit further improvements to guest statistics on FeatHub.
