### ISSUE TITLE
[FQ] Encrypt Plex password

### ISSUE THREAD

**Issue by patschi** [Tautulli/Tautulli#2]
After doing some configuration in the webinterface I saw that the password(s) get's saved unencrypted in the config.ini file. So I would wish me that the passwords gets encrypted in the future :)

**Comment by Arcanemagus** [comment]
Even better (at least in my opinion) would be to not store the password at all. I've changed plexWatch/Web to only store the authentication token. If the token is ever invalidated it directs the users to the settings page to generate a new one.

I don't want to be responsible for storing the password, and encrypting it is pointless as the decryption must be able to be performed by the same application... and thus just as easily accessible as the password.

**Comment by drzoidberg33** [comment]
Indeed. There is actually no need to save the password. I'll work that into the next commit.

Thanks.

**Comment by drzoidberg33** [comment]
Latest commit now only stores your token (https://github.com/drzoidberg33/plexpy/commit/d2c65e6a65b5cff301aa7728ac3fa2d71acc69cc)

You can enter it manually or use the new javascript auth tool which talks directly with plex.tv.

**Comment by Arcanemagus** [comment]
That's even better than sending it back to the server at all, I might have to move plexWatch/Web to that model :stuck_out_tongue:.

**Comment by drzoidberg33** [comment]
It made the most sense to do it this way. Otherwise you you're adding another layer to slow things down as well as the issue of sending the credentials over an insecure connection if the user hasn't enabled SSL on the installation.

**Comment by Arcanemagus** [comment]
Yep, exactly. Also this way you are using the browser to handle the HTTPS, which is going to be one of the most up to date things out there for support of that. Python probably does this better but in PHP land quite often you are stuck with very old OpenSSL libraries unless the user has done some customization.
