### ISSUE TITLE
I'll Be Back!

### ISSUE THREAD

**Issue by aaronchi** [Tautulli/Tautulli#20]
I got this error trying to do the automatic update.

```
Traceback (most recent call last):
  File "lib/cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\plexpy\plexpy\webserve.py", line 497, in update
    return self.do_state_change('update', 'Updating', 120)
  File "C:\plexpy\plexpy\webserve.py", line 460, in do_state_change
    quote = self.random_arnold_quotes()
  File "C:\plexpy\plexpy\webserve.py", line 1048, in random_arnold_quotes
    return quote_list[int(random_number)]
IndexError: list index out of range
```

Looks like you forgot a `-1` in there :)

**Comment by drzoidberg33** [comment]
That's what happens when you write a 2 minute function :smile: 

Just running the update again should work.

**Comment by drzoidberg33** [comment]
Actually looked at this now, not sure why you would get this error, the random number should always be in range.

Do an update to the latest version and see if you still see this error.

**Comment by aaronchi** [comment]
Shouldn't it be `random_number = randint(0, len(quote_list)-1)` ?

**Comment by drzoidberg33** [comment]
Ah yes, my bad. I'm so used to starting to count at zero I forgot that the list size is a count of the items not an iterator from 0. Will fix in next commit.

Thanks

**Comment by drzoidberg33** [comment]
Fix in https://github.com/drzoidberg33/plexpy/commit/9a5348dbfa02028c929b7ddc0666f37dfd5387c4

Thanks for the report.
