### ISSUE TITLE
Feature request: discover plex

### ISSUE THREAD

**Issue by Hellowlol** [Tautulli/Tautulli#203]
It would have been nice if we got a list with plex servers on the local network when doing the wizard. I can do this myself, it's mostly a reminder :p

**Comment by drzoidberg33** [comment]
This would be cool. Maybe a dropdown list should appear when you focus on the IP/Hostname input - if there are local servers available.

**Comment by Arcanemagus** [comment]
That's a great idea, are you planning on using the GDM functionality?

**Comment by Hellowlol** [comment]
Yes, and I'll try to add a fallback to normal dlna (just need to check what info it returns)

**Comment by Hellowlol** [comment]
https://github.com/drzoidberg33/plexpy/pull/205

**Comment by Hellowlol** [comment]
https://github.com/drzoidberg33/plexpy/pull/213
