### ISSUE TITLE
[Feature Request] Update database for moved library items

### ISSUE THREAD

**Issue by JonnyWong16** [Tautulli/Tautulli#204]
Feature to update the PlexPy database when library items are moved (rating key is changed).
- If no metadata is found when generating info pages, use the Plex `/search` API to get a list of possible matches.
- Display the matches to the user to select the correct item.
- Update the PlexPy database with the new metadata, and generate the info page.

(This is mostly a note to myself to implement)

**Comment by drzoidberg33** [comment]
Integrated.
