### ISSUE TITLE
[Bug] Windows - Logs Folder

### ISSUE THREAD

**Issue by Conq1942** [Tautulli/Tautulli#209]
With the following setup for Logs Folder: `%LOCALAPPDATA%\Plex Media Server\Logs\` also tried the full path. 

The directory won't be found, the logs print the following error: 

`Unable to open Plex Log file. [Errno 2] No such file or directory: '%LOCALAPPDATA%\\Plex Media Server\\Logs\\Plex Media Server.log'`

Why there is a double backslash?

**Comment by drzoidberg33** [comment]
`%LOCALAPPDATA%` is a shortcut that PlexPy doesn't understand. You must supply the full path like:

`C:\Users\YourUserName\AppData\Local\Plex Media Server\Logs\`

**Comment by Conq1942** [comment]
Ahh, thanks! :)
