### ISSUE TITLE
Feature Request: Way to indicate User is connecting with SSL

### ISSUE THREAD

**Issue by nomadore** [Tautulli/Tautulli#21]
Can Plexpy indicate if a client is connecting securely with SSL?  It would be useful to figure out with users needs to upgrade to a SSL compatible client before turning on the require SSL option.

**Comment by drzoidberg33** [comment]
I don't really think there is an elegant way to do this currently. The only way I can think of is to look in the logs but that can be unreliable at times. The Plex api's don't have any information (that I know of) if the session is being initiated using a secure connection.

I'll keep my eyes open to see if they add anything to the APIs.

**Comment by nomadore** [comment]
Okay, thank you for the response.

**Comment by drzoidberg33** [comment]
I'm closing this for now as there is nothing I can do here until the Plex API allows it.
