### ISSUE TITLE
Configure notification sounds for Pushover

### ISSUE THREAD

**Issue by mrchops1024** [Tautulli/Tautulli#210]
I think Pushover has an API for pulling all the available notification sounds. Possible to add this and provide the ability of specifying a specific sound? The frequency at which I receive these notifications makes me want a less-annoying sound since I don't need to check them all the time. I still like using my default sound for other notifications that require my attention.

**Comment by drzoidberg33** [comment]
Can't you just set it on the device?

**Comment by mrchops1024** [comment]
Unless I'm just blind I can set the default sound for all Pushover messages, but not just the ones from PlexPy.

**Comment by ThePierce** [comment]
+1 
Same as for Boxcar V2. Used to have this choice before in plexwatch :)

**Comment by drzoidberg33** [comment]
Released in 1.2.2.
