### ISSUE TITLE
[Feature] easier way to filter user history between movies/episodes

### ISSUE THREAD

**Issue by tylordurton** [Tautulli/Tautulli#219]
I would like to be able to easily filter the user history between episodes and movies, sounds trivial but my user base watch a LOT of episodes (kids mainly) but would be interested to see what movies are being viewed by simple filtering.

**Comment by drzoidberg33** [comment]
I like what Jonny has done with the breadcrumbs but I know this isn't accessible from the history table directly.

**Comment by JonnyWong16** [comment]
Also accessible from the "Library statistics" on the homepage.

**Comment by JonnyWong16** [comment]
Filtering in history table added in v1.2.4.
