### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tylordurton** [Tautulli/Tautulli#22]
I know this is a small qwerk on my part but would it be possible to toggle the completed symbol to a numeric percentage if so desired?

**Comment by drzoidberg33** [comment]
The percent complete value is more often than not a very broad approximation, especially when you have a user configurable ping interval and with music tracks thrown into the mix.

This is why I opted to use the icon instead as it takes up very little column space and just give you an overall idea of the progress.

I most likely will not change this.

**Comment by tylordurton** [comment]
Ok understood, guess it makes sense certainly from a music perspective (which I don't use Plex for).

thanks for confirming
