### ISSUE TITLE
All History Items Listed as Unwatched

### ISSUE THREAD

**Issue by mannibis** [Tautulli/Tautulli#221]
As of Git hash: c65d8a1ec66837a9c99fd6f664d213fd6cb3532b, all of my items in History are shown as unwatched. This is obviously messing with stats, etc.

**Comment by JonnyWong16** [comment]
See https://forums.plex.tv/discussion/comment/1027276/#Comment_1027276

**Comment by mannibis** [comment]
Thank you sir, fixed.
