### ISSUE TITLE
[FEATURE] Webroot Support (Reverse Proxy)

### ISSUE THREAD

**Issue by mannibis** [Tautulli/Tautulli#222]
I'd like to bury PlexPy behind a reverse proxy (so I can access it via https://ip.address/plexpy

I configured the reverse proxy in apache, but afraid without a webroot option, I get CSS/HTML errors when navigating.

**Comment by JonnyWong16** [comment]
See #49.

**Comment by mannibis** [comment]
Thank you, will look into this

**Comment by drzoidberg33** [comment]
Duplicate.
