### ISSUE TITLE
New search bar obscures top of page

### ISSUE THREAD

**Issue by xomnia** [Tautulli/Tautulli#223]
I really like the new search par in the floating navigation at the top of the interface!  It seems that the rest of the content on the page hasn't been moved down the page however and I can't see the links (for example) on the users page to edit names.  I am using the newest version of chrome on osx.

**Comment by xomnia** [comment]
Testing in safari this doesn't appear to be an issue, only shows up in chrome (Version 45.0.2454.101)

**Comment by drzoidberg33** [comment]
Just refresh the page. It's pulling the css from the browser cache (cache invalidation is still something that we need to do).

This is also highlighted on the troubleshooting page :smile:

https://github.com/drzoidberg33/plexpy/wiki/Troubleshooting
