### ISSUE TITLE
[Bug] History reporting exceedingly long play times

### ISSUE THREAD

**Issue by majora2007** [Tautulli/Tautulli#226]
After enabling History grouping, I have noticed that some shows or music are reported to have been watched much more than they should. For example, in the screenshot attached, notice that one single count of an episode is recorded for over 2,000 mins. This is happening on music and TV shows. 

![image](https://cloud.githubusercontent.com/assets/735851/10263767/3d42b5ce-69bf-11e5-8a32-5eb3efcee902.png)

**Comment by JonnyWong16** [comment]
Was PlexPy shut down after someone started watching something? and then restarted hours later after they finished watching?

**Comment by majora2007** [comment]
Nope. I have it on always. I did notice that the path to my Log file was not set correctly, but that doesn't explain why it would miscalculate playing time. I also saw this on an album I listened two twice. I listened to it fully, then started again, took a break (few hours), then came back and listened to a few more songs. I noticed that PlexPy recorded me listening to it for 20 hrs 9 mins. 

Not sure if related, but I also noticed that 4 episodes from a user were not recorded during this time. I assumed it was due to websockets being on, so I disabled and after reset, his episodes were recorded.

**Comment by drzoidberg33** [comment]
I don't think this has anything to do with the grouping. This looks like a stop event wasn't captured properly for that item. I'll run some tests using PlexWeb as I think I have a related issue with some of my users.

**Comment by majora2007** [comment]
Yeah I just noticed that one of the music items I was listening to today, when I stopped, PlexPy didn't get updated and as I got home today, my PlexPy now thinks this artist has been listened to for 28 hours (I had to play a music item and force stop after a min of listening to clear PlexPy).

**Comment by majora2007** [comment]
Any update on this? I'm still seeing this on my server. Here is another example:

![image](https://cloud.githubusercontent.com/assets/735851/10719610/d83b957c-7b59-11e5-8f9b-0f949317c4a7.png)

**Comment by JonnyWong16** [comment]
Reopen if the issue persists.

**Comment by korzynski** [comment]
I'm seeing this issue a lot on my server.
