### ISSUE TITLE
[REQUEST] Graph to show simultaneous users/streams

### ISSUE THREAD

**Issue by kylerw** [Tautulli/Tautulli#229]
It would be nice to see when Plex is being utilized most. Couple ways I see this being used:

--Dashboard to show across all users
--user specific to see when/if a user is utilizing multiple streams
--item specific to see when specific video files are popular

**Comment by rickcab1** [comment]
+1 on this.  I would even love to know if it would be possible to restrict how many streams one could have per account.

**Comment by JonnyWong16** [comment]
Duplicate #184
