### ISSUE TITLE
Pushbullet Channel

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#23]
Could you please add the channel functionality so that I could redirect all plexpy notifications to my own custom channel ie. plexserver for example.

channel_tag - Send the push to all subscribers to your channel that has this tag.

I use pushbullet for other services as well, this way I keep them all organized and separated from each other.

see here for the documentation
https://docs.pushbullet.com/

**Comment by drzoidberg33** [comment]
I'll add this with the notifications rewrite.

**Comment by drzoidberg33** [comment]
Added in https://github.com/drzoidberg33/plexpy/commit/b394ebc1a39fe2e6dc05cd10e0957ed8ac801cd6
