### ISSUE TITLE
PleXBMC

### ISSUE THREAD

**Issue by dbowles1975** [Tautulli/Tautulli#230]
I'm not sure if it's designed to but PlexPy does not appear to update watch statistics when viewing from PleXBMC. It works fine when viewing from other Plex apps. Is there something I need to change or is this just not something PlexPy will do?

**Comment by Arcanemagus** [comment]
When watching something from that does the activity show in Plex's own "Now Playing" screen? Some ancient (and somewhat broken) clients don't show there, and PlexPy uses the same data source as that.

**Comment by drzoidberg33** [comment]
I don't think PlexBMC reports timeline data to PMS so we won't know what it's doing.
