### ISSUE TITLE
hi to all need help

### ISSUE THREAD

**Issue by marciobooi** [Tautulli/Tautulli#232]
![captura de ecra 2015-10-08 as 17 19 16](https://cloud.githubusercontent.com/assets/8172023/10372671/e51a6b96-6de0-11e5-995c-98c82f69f819.png)
![captura de ecra 2015-10-08 as 17 19 34](https://cloud.githubusercontent.com/assets/8172023/10372670/e519814a-6de0-11e5-9281-139ac57e306c.png)

i have an issue with plexpy as you can see in the images
someone can point me in the right direction

**Comment by drzoidberg33** [comment]
@JonnyWong16 Any idea what this may be? You know this part better than I do.

**Comment by JonnyWong16** [comment]
Can you look for these two lines in your config.ini file and post them here:

```
home_stats_cards
home_library_cards
```

I can already see one bug in the screenshot, but not sure it that is the problem.

**Comment by marciobooi** [comment]
[Growl]
growl_enabled = 0
growl_on_play = 0
growl_on_buffer = 0
growl_on_pause = 0
growl_host = ""
growl_on_resume = 0
growl_password = ""
growl_on_stop = 0
growl_on_watched = 0
[PMS]
pms_use_bif = 1
pms_uuid = 9873c6ad56f64b76a2283c9049e808e5
pms_url = http://127.0.0.1:32400
pms_logs_folder = ""
ms_token =""
pms_port = 32400
pms_is_remote = 0
pms_identifier = 0fee8c21852d8eaae5ae099e4a672a412c9c36cb
pms_ip = 127.0.0.1
[Monitoring]
movie_notify_enable = 1
notify_on_stop_body_text = {user} ({player}) has stopped {title}.
notify_on_resume_body_text = {user} ({player}) has resumed {title}.
notify_on_pause_body_text = {user} ({player}) has paused {title}.
buffer_wait = 900
movie_notify_on_pause = 0
music_notify_enable = 1
notify_on_watched_subject_text = PlexPy ({server_name})
notify_on_watched_body_text = {user} ({player}) has watched {title}.
music_notify_on_pause = 0
notify_on_buffer_body_text = {user} ({player}) is buffering {title}.
tv_notify_on_stop = 0
music_logging_enable = 0
notify_on_stop_subject_text = PlexPy ({server_name})
movie_notify_on_stop = 0
notify_on_start_body_text = {user} ({player}) started playing {title}.
notify_watched_percent = 85
tv_notify_enable = 0
buffer_threshold = 3
notify_consecutive = 0
refresh_users_interval = 12
monitoring_use_websocket = 0
notify_on_start_subject_text = PlexPy ({server_name})
movie_notify_on_start = 0
monitoring_interval = 60
tv_notify_on_pause = 0
refresh_users_on_startup = 1
tv_notify_on_start = 0
video_logging_enable = 1
notify_on_resume_subject_text = PlexPy ({server_name})
music_notify_on_stop = 0
logging_ignore_interval = 120
music_notify_on_start = 0
notify_on_pause_subject_text = PlexPy ({server_name})
notify_on_buffer_subject_text = PlexPy ({server_name})
[PushBullet]
pushbullet_on_play = 0
pushbullet_channel_tag = ""
pushbullet_deviceid = ""
pushbullet_apikey = ""
pushbullet_on_resume = 0
pushbullet_on_buffer = 0
pushbullet_on_pause = 0
pushbullet_on_stop = 0
pushbullet_enabled = 0
pushbullet_on_watched = 0
[NMA]
nma_priority = 0
nma_on_watched = 0
nma_on_stop = 0
nma_on_play = 0
nma_on_resume = 0
nma_apikey = ""
nma_on_buffer = 0
nma_enabled = 0
nma_on_pause = 0
[Advanced]
verify_ssl_cert = 1
journal_mode = wal
cache_sizemb = 32
[Email]
email_on_pause = 0
email_smtp_password = ""
email_tls = 0
email_smtp_port = 25
email_on_watched = 0
email_smtp_server = ""
email_enabled = 0
email_on_resume = 0
email_smtp_user = ""
email_on_stop = 0
email_on_buffer = 0
email_to = ""
email_from = ""
email_on_play = 0
[PlexWatch]
grouping_user_history = 0
plexwatch_database = ""
grouping_global_history = 0
grouping_charts = 0
[OSX_Notify]
osx_notify_on_buffer = 0
osx_notify_on_stop = 0
osx_notify_enabled = 0
osx_notify_on_watched = 0
osx_notify_on_pause = 0
osx_notify_app = /Applications/PlexPy
osx_notify_on_play = 0
osx_notify_on_resume = 0
[Pushover]
pushover_enabled = 0
pushover_on_watched = 0
pushover_on_buffer = 0
pushover_on_pause = 0
pushover_on_stop = 0
pushover_apitoken = ""
pushover_on_play = 0
pushover_keys = ""
pushover_priority = 0
pushover_on_resume = 0
[Twitter]
twitter_on_resume = 0
twitter_enabled = 0
twitter_username = ""
twitter_on_stop = 0
twitter_on_buffer = 0
twitter_on_watched = 0
twitter_password = ""
twitter_on_pause = 0
twitter_prefix = PlexPy
twitter_on_play = 0
[Boxcar]
boxcar_on_watched = 0
boxcar_on_buffer = 0
boxcar_on_stop = 0
boxcar_on_pause = 0
boxcar_on_play = 0
boxcar_on_resume = 0
boxcar_enabled = 0
boxcar_token = ""
[Pushalot]
pushalot_enabled = 0
pushalot_on_watched = 0
pushalot_on_play = 0
pushalot_on_pause = 0
pushalot_on_stop = 0
pushalot_apikey = ""
pushalot_on_buffer = 0
pushalot_on_resume = 0
[Prowl]
prowl_on_pause = 0
prowl_enabled = 0
prowl_priority = 0
prowl_on_watched = 0
prowl_keys = ""
prowl_on_buffer = 0
prowl_on_play = 0
prowl_on_resume = 0
prowl_on_stop = 0
[General]
freeze_db = 0
http_proxy = 0
ip_logging_enable = 0
launch_browser = 1
http_username = ""
do_not_override_git_branch = 0
home_stats_length = 30
http_host = 0.0.0.0
http_root = /
first_run_complete = 1
enable_https = 0
check_github = 1
api_enabled = 0
config_version = 0
check_github_interval = 360
group_history_tables = 0
http_password = ""
home_stats_count = 10
cleanup_files = 0
check_github_on_startup = 1
http_port = 8181
log_dir = /Applications/plexpy/logs
update_db_interval = 24
interface = default
pms_ssl = 0
git_path = ""
home_stats_cards = "watch_statistics, top_music, popular_music"
time_format = HH:mm
cache_dir = /Applications/plexpy/cache
https_cert = /Applications/plexpy/server.crt
api_key = ""
date_format = YYYY-MM-DD
home_stats_type = 0
https_key = /Applications/plexpy/server.key
git_user = drzoidberg33
home_library_cards = "library_statistics, 8, 7, 5, 3, 6, 1, 9, 4, 2, 10"
git_branch = master
[Plex]
plex_client_host = ""
plex_on_play = 0
plex_on_stop = 0
plex_on_resume = 0
plex_on_watched = 0
plex_on_buffer = 0
plex_on_pause = 0
plex_enabled = 0
plex_username = ""
plex_password = ""
[XBMC]
xbmc_on_pause = 0
xbmc_on_stop = 0
xbmc_username = ""
xbmc_on_buffer = 0
xbmc_enabled = 0
xbmc_on_watched = 0
xbmc_on_play = 0
xbmc_host = ""
xbmc_on_resume = 0
xbmc_password = ""

**Comment by Hellowlol** [comment]
Remove your plex_token from what you pasted. I can get access to your account with it.

**Comment by marciobooi** [comment]
thanks i remove it

**Comment by JonnyWong16** [comment]
Would you mind sending me your plexpy.db file? I would suggest not to post it publicly here.

**Comment by marciobooi** [comment]
Ok no problem and what is the email adress?

Atenciosamente
Marcio oliveira 

No dia 11/10/2015, às 21:35, JonnyWong16 notifications@github.com escreveu:

**Comment by JonnyWong16** [comment]
You can send me a message on the [Plex Forums](http://forums.plex.tv/profile/Jonny.Wong.16).

**Comment by marciobooi** [comment]
Can you confirm that recive the file?

Atenciosamente
Marcio oliveira 

No dia 11/10/2015, às 23:18, JonnyWong16 notifications@github.com escreveu:

**Comment by JonnyWong16** [comment]
Found the bug.

**Comment by marciobooi** [comment]
And?

Atenciosamente
Marcio oliveira 

No dia 12/10/2015, às 07:12, JonnyWong16 notifications@github.com escreveu:

**Comment by Hellowlol** [comment]
It needs to be merged.

**Comment by marciobooi** [comment]
ok so what i should do? wait?

**Comment by Hellowlol** [comment]
Yeah

**Comment by marciobooi** [comment]
ok thanks a lot bro

**Comment by JonnyWong16** [comment]
It's fixed now. v1.2.2 is released.

**Comment by marciobooi** [comment]
Thanks dude you are great

I have a request
It is possible to add in grafics page the info of the charge of the cpu?
And the mb of the trancode, and stuff like that?

Again thanks a lot

Enviado do meu iPad

No dia 12/10/2015, às 19:47, JonnyWong16 notifications@github.com escreveu:

**Comment by drzoidberg33** [comment]
Resolved in 1.2.2.
