### ISSUE TITLE
[Feature Request] Setup notification sounds for Boxcar V2

### ISSUE THREAD

**Issue by ThePierce** [Tautulli/Tautulli#233]
Using plexwatch as back-end and plexpy as front end i was able to setup the notification sounds for boxcar. Would love to see that feature in plexpy since i only use plexpy since a couple of weeks.

**Comment by ThePierce** [comment]
Just updated and tested it! works like a charm! thanks guys. Keep up the good work :) :+1:

**Comment by JonnyWong16** [comment]
Could you test one thing for me since I don't use Boxcar? If you set the notification sound to "blank", does it still fire off a notification? with the default sound? no sound?

It's not mentioned in the Boxcar API docs so I just assumed that's what a "blank" sound would do.

**Comment by ThePierce** [comment]
Hi JonnyWong16,

Set notification to blank. Boxcar plays my default sound. Hopes this will clarify it for you. If there is anything i can do, lemme know :)

**Comment by drzoidberg33** [comment]
Integrated into 1.2.2.
