### ISSUE TITLE
[Request] Path Prefix Support

### ISSUE THREAD

**Issue by rix1337** [Tautulli/Tautulli#234]
This project runs great! Cudos on the easy setup!

Since I run multiple services on my server I would love to see path prefix support.

I have plexpy running on a subdomain atm (plexpy.my.svr), but would love to see it at my.svr/plexpy

Any chance this can be done?

**Comment by drzoidberg33** [comment]
This is a duplicate - the answer is here: https://github.com/drzoidberg33/plexpy/issues/49#issuecomment-144706644

**Comment by Hellowlol** [comment]
set the http_root in the settings/conf file

**Comment by rix1337** [comment]
Thank you, working great!
