### ISSUE TITLE
IndexError: List out of range on home screen

### ISSUE THREAD

**Issue by jemus42** [Tautulli/Tautulli#236]
- [Screenhot](http://dump.jemu.name/4JEyK.png)
- [Copypasta of said error on homescreen](https://paste.xinu.at/2Ka/)
- [Log directly after restart of plexmediaserver and then restart of plexpy](https://paste.xinu.at/NXVYQ/)
- Platform: FreeBSD (FreeNAS standard jail)
- Both Plex and PlexPy are installed in that same jail, both are up to date
- PlexPy reporting of currently watched items works fine
- Logging of who has watched what seems to work fine, too (not tested for long, only 2 watches by one user yet)

**Comment by marciobooi** [comment]
hi its the same as me in issue #232

**Comment by drzoidberg33** [comment]
I believe this has been resolved with 1.2.2. Please just reopen this if the issue persists.
