### ISSUE TITLE
Least watched shows and movies?

### ISSUE THREAD

**Issue by damianeickhoff** [Tautulli/Tautulli#240]
Hi,

So I want to figure out what shows and movies are least watched. This is because I don't want any unwanted movies or series stored on my hdd. Is there a possibility to build this in PlexPy (because you already have "most watched") or is this already possible?

I hope to hear from you,

Kind Regards,

Damian

**Comment by drzoidberg33** [comment]
There is already a request for this here: https://github.com/drzoidberg33/plexpy/issues/192
