### ISSUE TITLE
Movies served through PlexConnect don't appear in PlexPy

### ISSUE THREAD

**Issue by madmaiike** [Tautulli/Tautulli#242]
Hi guys,

First off very nice work from drzoidberg33 on PlexPy. 

I was just implementing PlexConnect to see how it worked and was surprised to see that there was update on the PlexPy interface or notification when starting a movie. I actually wanted to see if it was direct streamed, transcoded or direct played :) 

Am I missing someting ? 

Thanks

**Comment by Arcanemagus** [comment]
Check the Now Playing in the Activity tab of the official app (plex.tv) to double check, but I would imagine that PlexConnect is using the ancient method of streaming the content from Plex that does not show in the usage status of Plex itself (and thus PlexPy would have no information on it either).

**Comment by madmaiike** [comment]
Found the delicious parameters section - since I wasn't logged in to any account it didn't appear. Logged in and works perfectly. Good night all and thank you for an amazing piece of software

**Comment by Arcanemagus** [comment]
Glad to hear it was as simple as that, you might want to mark this as closed as it's not actually an issue with PlexPy :wink:.

**Comment by drzoidberg33** [comment]
Resolved. Closing issue.
