### ISSUE TITLE
Database Error on 1.2.2

### ISSUE THREAD

**Issue by zenjabba** [Tautulli/Tautulli#243]
When selecting History, I get the following error. Clicking OK allows the process to continue, but going back to the history screen brings it back.

<img width="449" alt="screenshot 2015-10-12 18 25 16" src="https://cloud.githubusercontent.com/assets/679864/10440590/b7f32c08-710e-11e5-8413-0335b79b69eb.png">

**Comment by Hellowlol** [comment]
force update your browser cache (ctrl + f5)
