### ISSUE TITLE
[Feature Request]  Auto Backup of PlexPy DB

### ISSUE THREAD

**Issue by rickcab1** [Tautulli/Tautulli#244]
I was wondering if a feature to make automated backups of the PlexPy DB to possibly another folder or drive all together might be helpful for those that might want o safe guard all this great data from possible data corruption?  Maybe a feature set in Settings with a check box and directory location for automated backups and a selection of how many to retain and how often to backup?  Was just thinking about this as this great application progresses and gets bigger and better.

**Comment by drzoidberg33** [comment]
Task already exists for this: https://github.com/drzoidberg33/plexpy/issues/89

I just don't have much time lately.
