### ISSUE TITLE
[Feature Reqeust] Add {time_left} parameter to notifications

### ISSUE THREAD

**Issue by cookandy** [Tautulli/Tautulli#247]
Hi,

I am trying to create a pushover notification which will show me the number of minutes remaining when a stream is started.  In plexWatch this was called **{time_left}**.

Similarly, it was possible to get the user's IP address via the **{ip_address}** parameter.  

I think both of these variables would be good to add to plexPy.

**Comment by chopeta** [comment]
+1 here for the {ip_address}

**Comment by JonnyWong16** [comment]
`{time_left}` is easy to implement.
See #179 regarding `{ip_address}`.

**Comment by cookandy** [comment]
Hi @JonnyWong16. Why is the IP address unknown when the state == play? Doesn't the IP come from the Plex Logs? These logs should be updated as soon as something had been started. This is how plexWatch does it I believe. Thanks.

**Comment by drzoidberg33** [comment]
We're firing off notifications before we know what the IP is, the IP check can take between 5 and 8 seconds and I don't want to delay the notifications. This will however be implemented sometime in the future.

**Comment by drzoidberg33** [comment]
Released in v1.2.3.
