### ISSUE TITLE
[bug] V 1.2.2 DataTables warning

### ISSUE THREAD

**Issue by aelberling** [Tautulli/Tautulli#248]
when i click the users tab i now get a pop up message saying
"DataTables warning: table id=users_list_table - Requested unknown parameter '8' for row 0. For more information about this error, please see http://datatables.net/tn/4"

**Comment by drzoidberg33** [comment]
Have you refreshed the page as per the Troubleshooting guide: https://github.com/drzoidberg33/plexpy/wiki/Troubleshooting?

**Comment by drzoidberg33** [comment]
I'm closing this as I'm guessing a page refresh likely fixed this. Reopen if not the case.
