### ISSUE TITLE
Run custom script

### ISSUE THREAD

**Issue by martinorob** [Tautulli/Tautulli#25]
Please may you add an option for "Run custom script"
ad example:

Run custom script(%user%, %title%, %library%)
run: "say %user% is watching %title%"

Thanks!

**Comment by drzoidberg33** [comment]
Not sure I understand exactly what this is supposed to do.

Is it for notifications or a command line option?

**Comment by martinorob** [comment]
Is for notification! 
A new notification type thai run a custom (shell) command..

**Comment by drzoidberg33** [comment]
Thanks for the clarification, I understand now what you mean.

**Comment by martinorob** [comment]
thanks to you.. but you think is a good request or not? 😊

**Comment by drzoidberg33** [comment]
This is definitely not something that will happen soon, but also when I do the first release I will be opening up pull requests, so if another developer wants to add this they're free to do so.

What is this for specifically? Is it like home automation stuff?

**Comment by martinorob** [comment]
Yes! Is like to switch on Philips Hue!

**Comment by kylerw** [comment]
This might also be used to throttle download programs (although I've put in a separate request for that)

**Comment by martinorob** [comment]
Any news about this request? 

Thanks

**Comment by onedr0p** [comment]
If anyone can give **in detail** how they want this to work I can look into added it.

**Comment by Hellowlol** [comment]
I would have added new option in the config for a script folder. In the html there would be a list of states and a dropdown for each of them where you can choose what script to run. Not very detailed, but its a start atleast

**Comment by martinorob** [comment]
for example:
![schermata 2015-10-29 alle 16 01 11](https://cloud.githubusercontent.com/assets/6664936/10822570/08c3911c-7e58-11e5-9090-90fc92ca3f0e.png)

![schermata 2015-10-29 alle 16 01 34](https://cloud.githubusercontent.com/assets/6664936/10822469/af056aec-7e57-11e5-9283-467d5a41289a.png)

Run "/opt/script/SwitchPhilipsHueOff.sh" when Film Start.

**Comment by onedr0p** [comment]
Thanks for the insight guys, I got a few questions..

**A) How would we handle multiple scripts?**
Maybe we could have Multiple Scripts on the Notification Agents (i.e. Custom Script 1, Custom Script 2, Custom Script 3) just have at most 3 or 4. 
With the example above there would need to be a SwitchPhilipsHueOn.sh when a film ends right? That means there would have to be another script run, thus another notification agent for the custom scripts.

**B) What if the Plex Media Server isn't located on the same machine as PlexPy?**
To keep it simple, I think we should allow this feature for computers with both apps installed on the same machine. We could implement a SSH way of doing things, but this will take more work.

Maybe I am thinking to much about these 2 things, anyone have any input?

**Comment by Hellowlol** [comment]
I think ssh is over the top. It should be scripts accessible from the same computer plexpy. If someone wants to do some fancy like ssh they can do it in the script.

If you still want ssh you can see how i did it for htpc manager vnstat module here https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/vnstat.py

**Comment by martinorob** [comment]
Thanks to you onedr0p!

A) How would we handle multiple scripts?
Yes i thinks is okay to have multiple script paths.

example:
On play:
Path1 (/usr/script/hueoff.sh)
On pause:
Path2 (/usr/script/huenon.sh)
On resume:
Path3 (/usr/script/hueoff.sh)
On stop:
Path4 (/usr/script/hueon.sh)

B) What if the Plex Media Server isn't located on the same machine as PlexPy?
I think that with ssh i can run script anywhere.
with ssh key i can do ssh to my other server and run script without authentication:

Example:
On play:
Path1 (/usr/script/hueoff.sh)
hueoff.sh = ssh user@server -x turnhueoff.sh

C) If you can add a personalized user script to do different action for different user:

example:
On play of user "username1":
Path1 (/usr/script/hueoff.sh)
On pause  of user "username1":
Path2 (/usr/script/huenon.sh)
On rerume  of user "username1":
Path3 (/usr/script/hueoff.sh)
On stop  of user "username1":
Path4 (/usr/script/hueon.sh)

On play of user "username2":
Path1 (/usr/script/sayfilmstarted.sh)
On pause  of user "username2":
Path2 (/usr/script/sayfilmpaused.sh)
On rerume  of user "username2":
Path3 (/usr/script/sayfilmresumed.sh)
On stop  of user "username2":
Path4 (/usr/script/sayfilmstopped.sh)

it would be nice!

Thanks
M.

**Comment by martinorob** [comment]
Any news @onedr0p ?

😊
Martino

**Comment by roelbeun** [comment]
For Philips hue control, try this Plex plugin.  Works great :

https://github.com/ledge74/HelloHue

**Comment by Hellowlol** [comment]
@onedr0p Any progress on this one? If you havnt i could start/finish it. 

I dont have anything to use this with atm but im hoping i get some home automation stuff for christmas, i can see som awesome uses with this.

Like automatically killing the transcode session if your kid watches xxx after yy.yy pm.

Sending a texts to your mate telling him you know is his guilty pleasures, and that gilmore girls really suck.

Set movie mode in via home automation etc.

**Comment by onedr0p** [comment]
Go for it, I've been busy on Node projects recently and with the holidays coming up I'll be even more busy.

**Comment by JonnyWong16** [comment]
Added in v1.3.0.

**Comment by martinorob** [comment]
WOW! Thanks to all!

**Comment by Hellowlol** [comment]
1.3.0 was a huge improvementent. Id like to thank all the contributors and especially @JonnyWong16  plexpy wouldnt have been where it is today without your massive prs xD
