### ISSUE TITLE
[Feature request] log file viewer

### ISSUE THREAD

**Issue by ThePierce** [Tautulli/Tautulli#251]
I use plexmediaserver on Ubuntu. To watch the logfiles i have to login into my vm using putty. Would be awesome if Plexpy could import the logfiles so i can view them in Plexpy via some sort of text viewer

**Comment by drzoidberg33** [comment]
You can already view the Plex Server logs in PlexPy:

<img width="796" alt="screenshot 2015-10-15 17 59 06" src="https://cloud.githubusercontent.com/assets/1313205/10519560/90e63538-7366-11e5-9eaa-55a751ec40e4.png">

What other logs do you want to see here?

**Comment by ThePierce** [comment]
Epic fail from my side. Apologies
