### ISSUE TITLE
Settings / Homepage Stats [issue]

### ISSUE THREAD

**Issue by vulcanjedi** [Tautulli/Tautulli#254]
The stats setting screen says to select the cards to SHOW on the homepage, but mine seem to work the opposite and you select the cards to HIDE?  Just think need to update the wording  on the page? With None selected all the cards show up as the page suggested which was the way my page was setup as I have not made any changes since that was included in an update as an enhancement

**Comment by drzoidberg33** [comment]
I cannot seem to replicate this. Are you on the latest version (1.2.3)?

Could you also look what the `config.ini` file has for the line `home_stats_cards`?

**Comment by vulcanjedi** [comment]
Sure drzoidberg33....sorry took me forever to recall my creds to this rpi install.
I am on the latest version since I see you guys update all the time I try to take them and have auto updates enabled.
I affirm I'm on v1.2.3.
I noticed the extra options in settings the other day and last night just thought perhaps I'd turn some off cause its a bit sluggy on my rpi.  So I have never changed those value from the default of whenever they got implemented. When I select the main ones I wanted, it actually hid them.
My config.ini values are below. These appear to be the ones I want and are correctly showing. Is the default GUI set to select all? This reminds me of an issue on rasplex when the gui highlight is very unclear on which is the active / inactive highlight, particularly when the default is completely 'highlghted'
home_stats_cards = "watch_statistics, top_tv, popular_tv, top_movies, popular_movies, top_users, top_platforms, last_watched"
home_library_cards = "library_statistics, 2, 3"

Obviously mostly cosmetic issue and not really an issue of performance. You guys are doing bang up work. Much regards.

**Comment by JonnyWong16** [comment]
Default is all selected. Highlight (lighter colour) is selected.

**Comment by drzoidberg33** [comment]
Is this still an issue?
