### ISSUE TITLE
[Feature Request] Import watch history from PMS database

### ISSUE THREAD

**Issue by benadderson** [Tautulli/Tautulli#258]
It would be really cool if PlexPy could query the PMS db to get the watch history for the relevant sections, and import those into the PlexPy db.

I'm sure many of us have been running a PMS instance for a long time by the time they set up PlexPy, so there's a wealth of data to be gotten there. I appreciate that some data may not be available (e.g. who was watching), but even just getting the watch count with placeholders for the rest would be really interesting/helpful!

**Comment by drzoidberg33** [comment]
This has been requested in the past: https://github.com/drzoidberg33/plexpy/issues/53

The bottom line is that this data is not consistent and doesn't provide enough information to generate useful statistics with.

It has been suggested to just add this into a separate list somewhere which is independent from graphs/stats.

**Comment by benadderson** [comment]
Ah, apologies for the dupe. I did look through the list but I obviously missed that one.

If the data cannot be integrated into the same graphs/stats, then I'd say it isn't worth the effort to grab it. Which is a shame.

Thanks anyway!
