### ISSUE TITLE
Config file Re-writing itself [Pushover bug]

### ISSUE THREAD

**Issue by Goas123** [Tautulli/Tautulli#26]
It appears that after last nights update when a change is made in the settings, the save is not committed to the config file. For example, when adding the API token to the PushOver settings, after setting and going back in to the setting it is showing a value of 1. This has lead to the notification function no longer working. Also I tried to remove the server credentials from the settings, and while it does not ask me for user name or password on logging, no matter how many times i delete the setting, it is still in there when I navigate back to the settings.

**Comment by drzoidberg33** [comment]
The notification stuff should be fixed in the next 24 hours, in the interim you can try and use the old config page: http://yourip:8181/config and set the settings there for now until the rewrite is complete.

Which server credentials are you trying to remove exactly? The token?

**Comment by Goas123** [comment]
Thanks for the quick response! I can wait for the notification fixes.

The credentials I am talking about are in Access Controls setting page, the HTTP Username and Password. It keeps on refilling itself, after I delete and save.

**Comment by drzoidberg33** [comment]
Ah okay, can you try the old config page and see if that helps.

**Comment by Goas123** [comment]
When I try to make any updates on the old config page, i get a red box in the bottom left that says "Please Verify Settings"

**Comment by drzoidberg33** [comment]
Please update and see if it helps otherwise please do a config reset by shutting down PlexPy, deleting the config.ini file manually and then restarting PlexPy. You will just have to set the configuration again but  any watch data will not be affected.

**Comment by Goas123** [comment]
Thanks, unfortunately still looks like there are issues. I updated, which did not fix the issue. I also performed the config resent, still having issues with entering the API Token in the PushOver settings. Anything i enter in there is wiped out after a save. Another odd thing is the old config page seems to be out of sync with the settings page. When I go into the Config page it has check boxes to enable the various notification settings, regardless of whether I have them turned on in settings. If i try to perform updates on the Config page i get an error that i need to verify settings

**Comment by Goas123** [comment]
So good news! It appears it is in fact working now! While the settings page does not retain the api token entered, it does appear to be updating the config file correctly, because I am now getting notifications, and I see in the logs that the api is being passed (The settings page still shows 0 in the field). Thanks!

**Comment by drzoidberg33** [comment]
This appears to be a Pushover specific bug. Will be fixed in the next commit.

**Comment by drzoidberg33** [comment]
Thanks. The pushover bug has been squashed. Please confirm.

**Comment by Goas123** [comment]
yup, all looks good now! thanks for your work!

**Comment by drzoidberg33** [comment]
Confirmed fixed. Closing.
