### ISSUE TITLE
[Bug] Apostrophe in user name causes data to break

### ISSUE THREAD

**Issue by SmallwoodDR82** [Tautulli/Tautulli#260]
I have a user with an apostrophe in the name.  The name shows up fine in Plexpy however when I click on their name to view data the page just hangs.

The name shows fine in the all users page with correct stats, however once I click on their name under the profile - global data, players stats, and recently watched never load.  IP Addresses, History and Synced Items don't show data either.

Also out of 39 users this is the only one that does it.

**Comment by JonnyWong16** [comment]
PM me your `plexpy.db` file on the Plex Forums and I'll take a look tonight.

**Comment by SmallwoodDR82** [comment]
sent.

**Comment by drzoidberg33** [comment]
Fixed in dev https://github.com/drzoidberg33/plexpy/commit/dc8996c4d2add74f0e508bdbc682aa5a3f8915bf

Will be in the next release.

**Comment by SmallwoodDR82** [comment]
very nice!

**Comment by JonnyWong16** [comment]
Fixed in v1.2.4.
