### ISSUE TITLE
Plays not correct when grouping activated.

### ISSUE THREAD

**Issue by Swiftnesses** [Tautulli/Tautulli#261]
Hello,

I have grouping activated, but the plays on the homepage do not correlate. i.e. the movie has been played 6 separate times, and correctly grouped as once within the history, sadly the homepage displays 6 plays.

**Comment by drzoidberg33** [comment]
Grouping is only for tables, hence the option name "Group Table History". It does not change any values elsewhere.

**Comment by Swiftnesses** [comment]
In that case the name makes sense, albeit I'm not sure the functionality does with regards the stats.

**Comment by drzoidberg33** [comment]
@markaswift You can take a look at https://github.com/drzoidberg33/plexpy/issues/77 and https://github.com/drzoidberg33/plexpy/pull/190 where a lot of these things are discussed and reasons why it's not that simple.
