### ISSUE TITLE
Add support for Plex Media Player

### ISSUE THREAD

**Issue by RafaelSchridi** [Tautulli/Tautulli#262]
Currently all plays on Plex Media Player appear as "Konvergo" and have no image.

**Comment by RafaelSchridi** [comment]
For the unaware, Plex introduced a new player:
https://blog.plex.tv/2015/10/20/introducing-the-plex-media-player/

**Comment by drzoidberg33** [comment]
I'll add a correction for this one, Konvergo is the internal project name before it had an official name.

**Comment by drzoidberg33** [comment]
Pushed this to dev.

**Comment by RafaelSchridi** [comment]
Figured as much about the name.Thanks!
