### ISSUE TITLE
In memory log

### ISSUE THREAD

**Issue by Hellowlol** [Tautulli/Tautulli#266]
Is there any reason why plexpy is using a in memory log instead of reading the logline or is it simply a relic from headphones? 

Just for lols i wrote one million lines of junk to the log, the log kept rotation as it should but memory usage was very high.

I also was annoyed with losing debug info every i restarted plexpy while i worked on the api. 

I would like to change the way to do it today so we read the log instead of the "memory log"

**Comment by drzoidberg33** [comment]
I haven't touched the logger functionality from how it was implemented in Headphones, so I don't actually even know how it works.

Feel free to improve on it if you wish.

**Comment by Hellowlol** [comment]
Ok, will do.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.0.
