### ISSUE TITLE
running plexPy opens in chrome

### ISSUE THREAD

**Issue by dualznz** [Tautulli/Tautulli#271]
for some issue when i double click on python.py it wont run instead it opens up the code in chrome.
i have python32 installed, server is on windows server 2008

**Comment by dualznz** [comment]
ok update so i told the .py file to open in python, so when i double click on it, i get a quick console 100 milliseconds then it closes and when i navigate to http://localhost:8181 no page can be displayed

**Comment by JonnyWong16** [comment]
Did you install python 2.7?

**Comment by dualznz** [comment]
sorted thank you it was the version of python i had installed
