### ISSUE TITLE
Feature Request: Library Statistics for API

### ISSUE THREAD

**Issue by dualznz** [Tautulli/Tautulli#272]
Hi
i would like t0 request that if its possible for the Library Stats to be added to a api response, this was people can show their server media stats on external sites and apps.

cheers

**Comment by roelbeun** [comment]
Maybe also possible for future telegram bot by then?

**Comment by zobe123** [comment]
+1

**Comment by JonnyWong16** [comment]
Some library stats have been added to API v2 (in v1.3.7), but it's all _extremely_ experimental right now.

**Comment by JonnyWong16** [comment]
Library stats are available in APIv2 with v1.4.0.
