### ISSUE TITLE
Feature Request: Add genre and poster url to notifications

### ISSUE THREAD

**Issue by zobe123** [Tautulli/Tautulli#273]
Thank you guys for the recently added feature. Great work. Can you also add the keywords "genre" and a poster-link? Thx

**Comment by JonnyWong16** [comment]
Genre is okay, but a poster url would be messy.

**Comment by zobe123** [comment]
how would the recommended practice be, to insert posters into email?

I'm the only one where the TV Tag is not working properly? (Movie Tag all fine)

...is it possible to highlight each Tag? (Feature Request?)
...is it possible to get more than one line for the code? (Feature Request?)

![11 11](https://cloud.githubusercontent.com/assets/13840542/11089484/5c572d4a-886a-11e5-805b-49977d767473.png)

**Comment by drzoidberg33** [comment]
@zobe123 Please open up your own issue for feature requests (note that multi-line has been implemented already.)
