### ISSUE TITLE
Pushover not working..? Or I'm dumb..?

### ISSUE THREAD

**Issue by Damienlee69** [Tautulli/Tautulli#275]
Hey, I just discovered this and am quite impressed! Seriously considering givin ya a few beers! However...I can't get any pushover notifications! lol. I'm obviously a pushover user, i have everything set properly as far as I can tell in both pushover and plexpy. I've tried leaving the API token blank to use default, I've created the app in pushover and I do not get any notifications!? Some help and there's beer in it for ya Dev! :D

**Comment by drzoidberg33** [comment]
Have you configured which triggers to use by using the bell icon?

Any info in the logs?

**Comment by onedr0p** [comment]
I know this works, I have it set up now. Double check your config. :)

**Comment by Damienlee69** [comment]
Wow, didn't even think to click those bells or any info to make sure to click them. Well, actually i didn't even notice them. Seems to be working now. Thanks! _Just donated_ Have a few on me! Btw, great work, keep it up!

**Comment by JonnyWong16** [comment]
@Damienlee69 It's in the first sentence at the top of the Notification Agents settings page.

**Comment by Damienlee69** [comment]
Lol, i see this now. Guess i wasn't paying attention.

**Comment by drzoidberg33** [comment]
Closing.

**Comment by chuckkay** [comment]
Please help.... or tell me I am not alone...
I have clicked the bell and checked the boxes.... i set everything up for pushover but it's not working log shows "PlexPy Notifiers :: Pushover notification failed: Bad Request".. 

everything else works.... twitter pushbullet etc...

**Comment by chuckkay** [comment]
Fixed.. I had the 2 API Keys reversed...
