### ISSUE TITLE
Dev branch status

### ISSUE THREAD

**Issue by camjac251** [Tautulli/Tautulli#277]
Is it safe to use the dev branch or is it too unstable? I'm asking because a lot of fixes have been made but none have reached the master branch in almost a month.

**Comment by Hellowlol** [comment]
That depends on what type of user you are. I'd say go for it, but remember stuff might break. As long as your using git its easy to switch back to the master branch.

**Comment by drzoidberg33** [comment]
We're monitoring an issue with the recently added where it sometimes fails, hence the reason for the long delay in pushing to master. Because it happens sporadically it's tricky to track down.

**Comment by camjac251** [comment]
Would the dev branch ever corrupt the DB or not log a watched item?

**Comment by drzoidberg33** [comment]
@camjac251 Yes, that is possible. Maybe not the corruption, but we've already had a dev release that broke history logging.

**Comment by krohrsb** [comment]
Good to know. Thanks! All the work on the dev branch recently is awesome by the way. Thanks for taking the time to develop it all.
