### ISSUE TITLE
Hybrid IP notation 

### ISSUE THREAD

**Issue by pax0707** [Tautulli/Tautulli#279]
It's providing " Invalid IP Address" for location feature.

 12.11.2015.    pax0707 ::ffff:192.168.0.10 iOS 
 Pax
 Monty Python and the Holy Grail (1975)
20:17   0 mins  20:20   3 mins  

 12.11.2015.
ursuea  ::ffff:212.15.178.89    iOS 
 Tigana
 The Man from U.N.C.L.E. (2015)
20:17   0 mins  20:21   4 mins

**Comment by JonnyWong16** [comment]
IPv6 added in v1.2.4.
