### ISSUE TITLE
Feature Request: Web root

### ISSUE THREAD

**Issue by anaxagorasbc** [Tautulli/Tautulli#280]
I have couchpotato/transmission/sabnzbd/headphones/sonarr/etc configured with webroots for the purpose of an apache reverse http proxy.  These services all use different ports and it's a pain to open a dozen holes in my firewall.  Instead I use a reverse http tunnel with apache and a secure login portal to access all these services from the outside world.  One of the requirement of setting this up is a webroot.  In other words going to http://192.168.x.x:8181/PlexPy as opposed to just http://192.168.x.x:8181/. 

I would think ideally this could be a user configurable option to chose my own desired webroot.

**Comment by JonnyWong16** [comment]
See #49

**Comment by anaxagorasbc** [comment]
Aweomse, guess i should have searched first.  editing that config file did it.

**Comment by drzoidberg33** [comment]
Duplicate.
