### ISSUE TITLE
Errors after rebuild of Plex server

### ISSUE THREAD

**Issue by cookandy** [Tautulli/Tautulli#283]
Hello,

I recently had to rebuild my entire plex library due to a bug with one of the plexpass releases.  Because of this, I had to setup a new server from scratch.  Now, I notice that plexpy isn't displaying metadata correctly, and I am seeing things like `Server name not found` on the home page next to "Library Statistics".  I also see things in the logs like:

`Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/metadata/164180/thumb/1437478468&width=300&height=300. Status code 404`

I have tried to fetch a new plex authentication token, but it doesn't help.  I'm still receiving notifications for newly watched items, but all of the old metadata is broken.  Is this stuff stored in the DB?  Is there any way to tell plexpy to go fetch the new images?

Thanks for the great app!

**Comment by JonnyWong16** [comment]
Metadata is stored in the PlexPy database, so rebuilding your library broke all the links.

I'm working on a feature to update/fix metadata. It's still very early though, so it will be quite a while before it is released.

**Comment by cookandy** [comment]
@JonnyWong16 thanks for confirming what I suspected.  I'd be happy to help test your feature when it's available.  I've got backups of my database if problems arise.

**Comment by JonnyWong16** [comment]
Perfect timing actually, I was just working on it in #263.

If you can help test it that would be great. Let me know if you need instructions.

**Comment by cookandy** [comment]
@JonnyWong16 I've updated to that branch but I don't see any libraries page.  Can you give me some basic details?  Thanks.

**Comment by JonnyWong16** [comment]
There is no Libraries page yet.

But there should be a "Fix metadata"  button if you click on a entry from the history table.

**Comment by cookandy** [comment]
Thanks.  When selecting any item, it takes approximately 4-5 minutes before doing anything.

On media I've watched _after_ the library move, if I wait the 4-5 minutes, the info page will load and I'll see the history correctly.

On media I've watched _before_ the library move, after the 4-5 minutes I'll eventually get a timeout.  I notice that the page automatically gets redirected from

`http://<server>:8181/plexpy/info?source=history&item_id=10722` to 

`http://<server>:8181/update_metadata?rating_key=10722` right before it times out.  

Meanwhile, in the logs I constantly see stuff like this (several/second):

```
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Failed to access uri endpoint /library/metadata/125382. Status code 404
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Unable to parse XML for get_metadata.
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Failed to access uri endpoint /library/metadata/125218. Status code 404
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Unable to parse XML for get_metadata.
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Failed to access uri endpoint /library/metadata/75457. Status code 404
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Unable to parse XML for get_metadata.
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Failed to access uri endpoint /library/metadata/75458. Status code 404
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Unable to parse XML for get_metadata.
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Failed to access uri endpoint /library/metadata/75459. Status code 404
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Unable to parse XML for get_metadata.
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Failed to access uri endpoint /library/metadata/121447. Status code 404
15-Nov-2015 16:16:52 - WARNING :: CP Server Thread-4 : Unable to parse XML for get_metadata.
```

I just noticed, I am using a path after my url (`http://<server>/plexpy`).  When the redirect happens, it doesn't include the `/plexpy` part of the URL.

**Comment by JonnyWong16** [comment]
Thanks for testing, it really helps!

The large delay is due to updating library IDs in the database (still trying to find a more efficient way to do this). It looks like you have a really large database (>10000 entries) so it will take longer. It should still only need to update once though... I'll have to look into this again.

Try going to the PlexPy homepage, and clicking one your libraries, it should bring you to page with `library_id` in the URL and a message saying it's updating the database.

I also see the redirect to `update_metadata` is using the wrong `rating_key`. Need to fix this too.

**Comment by cookandy** [comment]
I selected the Movies library from my home page.  It took a couple minutes and then finally loaded the page and displayed the updating message you mentioned.  After about 5 minutes the message went away and the history table refreshed, but was still empty.  

I then went back to the home page and repeated the process.  The updating message didn't display, but it still took a few minutes to load the page.  When it loaded, I still got the message `No matching records found.   Showing 0 to 0 of 0 entries (filtered from 10,734 total entries)`.

**Comment by JonnyWong16** [comment]
I pushed a change to the `library-id-changes` branch.

Can you edit your `config.ini` file and change `update_library_ids` to `1` and restart PlexPy? It should now load the `/info` page instantly from the homepage, and display the updating message. If you check the logs do you find `Updating library_id's in database.` and `Updated all library_id's in database.`?

**Comment by cookandy** [comment]
Hi there,

I pulled the change and tried again (after updating `update_library_ids` to `1` and rebooting).  The info page loaded instantly as you said it would, and the updating message appears for a few minutes - after which, I had the same `No matching records found` message.  

When I search the logs, I don't see anything about `Updating`, but I do see the finished `Updated` message:

```
[/apps/plexpy/logs] # cat plexpy.log | grep Updating
[/apps/plexpy/logs] # cat plexpy.log | grep Updated 
15-Nov-2015 18:27:53 - DEBUG   :: CP Server Thread-6 : Updated all library_id's in database.
```

**Comment by JonnyWong16** [comment]
Can you use a database browser such as [SQLite browser](http://sqlitebrowser.org/) to open up your plexpy.db file, and check if the `library_id`s updated in the `session_history_metadata` table?

SQLite Browser > Browse Data > Table: `session_history_metadata` > `library_id` column should be filled in.

**Comment by cookandy** [comment]
Some do, some don't:

`select count(*) from session_history_metadata`

`10734`

`select count(*) from session_history_metadata where library_id = '1'`

`2478`

**Comment by JonnyWong16** [comment]
They should have different `library_id`s unless you only have one library.

The entries that don't have an id, are they `NULL` or blank?

**Comment by cookandy** [comment]
I've only got the one library (and a few views on my newly rebuilt library).  So 2478 rows have an ID of `1`, and the rest are `NULL`.

**Comment by JonnyWong16** [comment]
Hmm...so for some reason it's only updating some of them.

The history table when you click your movies library should still list the entries that have the ID...

On the `/history` page, click on one of the entries in the history table that have an ID. You should be able to fix the metadata. Try with an entry that doesn't have an ID as well.

**Comment by cookandy** [comment]
Ok, I think I know why only some have an ID.  It's because I've only ever clicked on the `Movies` library, since I know the history on it is smaller than the `TV Shows` library.  So, that said - when I click on any Movie from the `history` page, I get an error:

`Error retrieving item metadata. This media item is not available in the Plex Media Server library.`

When clicking on a TV show, sometimes it will come up - no problem . Other times I get prompted to select a match from below (which is the same), to update the database.  This sometimes works, and other times it mismatches shows as shown below:

![](https://dl.dropboxusercontent.com/u/64324/plex/Screen%20Shot%202015-11-15%20at%207.57.00%20PM.png)

**Comment by JonnyWong16** [comment]
Oh, duh. It can't auto update the `library_id`s because you rebuilt the library. It doesn't know what the ID is because the item was moved in Plex.

You will have to update the metadata manually for each item. Movies need to be updated individually. Updating any episode of a TV show should update every the entire show in the database. By updating manually, I mean selecting the correct match when prompted or by clicking the "Fix Metadata" button on the info page.

As for the incorrect match in your screenshot, were all those history items from **before** you rebuilt your library? I think you'll need to restore a backup of your database before you try again.

**Comment by cookandy** [comment]
Hi,

Ok, so there's no way to go out to my new Plex server and match the old history items **automatically**?

Everything in my new server has the same name as the items in my history list.  So can this not be automated?

With regards to your question: yes, all of those history items were from **before** I rebuilt my server.

**Comment by JonnyWong16** [comment]
There's no way to guarantee that the match will be correct, even with the exact same name.

**Comment by cookandy** [comment]
Is this a limitation of the Plex API, or the way you've implemented the matching logic?

**Comment by JonnyWong16** [comment]
The way I currently have it set up is just using the Plex search API list all possible items based on the title. That's why I still need the user intervention to select the correct item.

I have already filtered out the search results based on the type of media it's trying to match (i.e. move, show, episode, etc.). So I guess it's really just a matter of _how probable is the first item the correct match?_

**Comment by cookandy** [comment]
Maybe this should be configurable?  For example, in my case I know that all of the title names _should_ be an exact match.  So if there was an option to "automatically select first match", most of them should match correctly.  What do you think?

**Comment by JonnyWong16** [comment]
It might be possible if I add in more matching criteria (show name, year, episode number, etc.).
Side note: I pushed another change to the branch. Manually updating should be working now.

@drzoidberg33 
Thoughts?

**Comment by drzoidberg33** [comment]
Sorry, missed this question previously.

@JonnyWong16 

You could possible look at using the `guid` it's actually included in the database for specifically this type of goal in mind.

**Comment by JonnyWong16** [comment]
Moved to #458.
