### ISSUE TITLE
getHistory Not Functional

### ISSUE THREAD

**Issue by wesleykirkland** [Tautulli/Tautulli#284]
I am in the processing of archiving my plex watch history and plexpy seems to allow access to this data much better then plex directly.

I am using Invoke-RestMethod in powershell to pull the data and other functions works such as getVersion,getPlayby,checkGithub

The url I am using for these functions is 
(Invoke-RestMethod -Uri "https://plexpapp01.lan.local:8181/api?apikey=$PlexPYAPI&cmd=getVersion")

My current commit version is 428706d9a7f358ae71e7b04494ad6d0f00ba5b50 and it appears to be the latest

Also getUserips appears to be broken and both of these functions return error while getPlayby returns a success.

**Comment by Hellowlol** [comment]
The api isnt updated like the main http calls. When i added those i just copied them from mainhandler, its should be refactored so its it gets changed both places.

**Comment by drzoidberg33** [comment]
Ye, sorry there is not much effort being put into the api currently but I heard @wcomartin had made some progress here, will just need to hang tight for this one.

**Comment by wesleykirkland** [comment]
@drzoidberg33 Thanks for the update on this, I was able to create a data warehouse by mounting the Plex SQLLite DB but it is a warehouse and it refreshes every hour so I can't accurately keep a good view history. Once the API function to PlexPY is working I am going to be logging them more.

Thanks

**Comment by wcomartin** [comment]
right now i found a workaround that if you send json_data in the get params it will work.

```
{
  "draw": 4,
  "columns": [
    {
      "data": "date",
      "name": "",
      "searchable": false,
      "orderable": true,
      "search": {
        "value": "",
        "regex": false
      }
    }
  ],
  "order": [
    {
      "column": 0,
      "dir": "desc"
    }
  ],
  "start": 0,
  "length": 25,
  "search": {
    "value": "",
    "regex": false
  }
}
```

**Comment by wesleykirkland** [comment]
@wcomartin How are you implementing that workaround?

Here is my code without the API key and I am still getting a error.

```
$body = '{
"draw": 4,
"columns": [
{
    "data": "date",
    "name": "",
    "searchable": false,
    "orderable": true,
    "search": {
    "value": "",
    "regex": false
    }
}
],
"order": [
{
    "column": 0,
    "dir": "desc"
}
],
"start": 0,
"length": 25,
"search": {
"value": "",
"regex": false
}
}
'

Invoke-RestMethod -Uri "https://plexpapp01.lan.local:8181/api?apikey=$PlexPYAPI&cmd=getHistory" -Body $body -Method Post
```

**Comment by wcomartin** [comment]
I added the JSON to the GET params, not the body, 
Also it is a GET request not post.

```
String url = "http://${PlexpyHost}/api_data?apikey=${PlexpyApikey}&cmd=getHistory&json_data={\"draw\":4,\"columns\":[{\"data\":\"date\",\"name\":\"\",\"searchable\":false,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}}],\"order\":[{\"column\":0,\"dir\":\"desc\"}],\"start\":0,\"length\":25,\"search\":{\"value\":\"\",\"regex\":false}}";
```

**Comment by creamers** [comment]
@wcomartin Thanks for the assistance though I am still having trouble with it, I guess I will have to wait till PlexPY is updated officially. Also api_data is invalid on commit fc0be6bce20c0452abd1b7b5f5faab1a98ae72ee

Query String
$test = Invoke-RestMethod -uri 'https://$uri:8181/api?apikey=$PlexAPIKey&cmd=getHistory&json_data={\"draw\":4,\"columns\":[{\"data\":\"date\",\"name\":\"\",\"searchable\":false,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}}],\"order\":[{\"column\":0,\"dir\":\"desc\"}],\"start\":0,\"length\":25,\"search\":{\"value\":\"\",\"regex\":false}}'

From $test.response.data
data            : null
draw            : 0
error           : Unable to execute database query.
recordsFiltered : 0
recordsTotal    : 0

**Comment by JonnyWong16** [comment]
You can now grab the history with APIv2 in v1.4.0.
