### ISSUE TITLE
Feature Request: Total Watch Time (all videos) card on the homepage

### ISSUE THREAD

**Issue by tj1816** [Tautulli/Tautulli#285]
Also, a total watch time for each episode/season/show would be pretty cool!  For example, when you click on a certain show, that page will show total watch time for every episode of that show... When you click on a season, that page will show total watch time for every episode in that season... When you click on an episode, that page will show total watch time for that specific episode.

**Comment by JonnyWong16** [comment]
Total watch time has been added to the table footer in v1.2.15.

I'll leave a total watch time card for another time.
