### ISSUE TITLE
Feature Request: Add Slack as a notification agent

### ISSUE THREAD

**Issue by ejdme7** [Tautulli/Tautulli#287]
I did figure out how to do this with IFTTT, but it would be great if we had Slack as an option so the messages can come in with their own username, the Plex icon, and such.

**Comment by Thr3d** [comment]
+1 I'd love to have a built in option for slack notices

**Comment by ecleese** [comment]
+1 For slack notifications.

**Comment by pilothaz** [comment]
I would like to have this working as well.  I am currently using this notifications in my telegram - might be moving to Slack..  +1

**Comment by JonnyWong16** [comment]
This is already in the `dev` branch and will be available in the next release.

**Comment by JonnyWong16** [comment]
Added in v1.3.0.
