### ISSUE TITLE
Notifications: Allow sending pushover messages by devices and/or delivery groups.

### ISSUE THREAD

**Issue by sirmeili** [Tautulli/Tautulli#288]
Pushover.net allows you to limit notifications to specific devices and/or deliver groups (that are set up on their site). I would like the ability to limit my notifications sent via pushover by these options if possible. This could be application wide (select device or delivery group for all of plexpy).

My preference would be delivery groups since you can set up a delivery group for just one device.

**Comment by JonnyWong16** [comment]
It should work by just entering your group key into the user key setting.

**Comment by sirmeili** [comment]
I am testing this now. If this works than this satisfies my need. I have some applications that actually let you enter the name instead of the key, but this works just as well.

(I just started getting notifications. Thanks for the quick reply!!)

**Comment by JonnyWong16** [comment]
Added wording to indicate a group key is usable in v1.2.4.
