### ISSUE TITLE
Feature Request : Buffering notications. 

### ISSUE THREAD

**Issue by HitsvilleUK** [Tautulli/Tautulli#29]
As said in the title I think buffering notifications would be a great feature for people who administer a shared server.

**Comment by Foebik** [comment]
+1 If this is possible.

**Comment by happytrail** [comment]
+1 vote.  Would be a nice feature for sure

**Comment by drzoidberg33** [comment]
This is now in the dev branch, waiting for release. Please feel free to test it out.

Commit: https://github.com/drzoidberg33/plexpy/commit/a96482ee3ce4a257ffa7cd6467a50832e96f23b9

Please note that it appears only certain Plex clients report buffering states, so you results may vary. I started this thread on the Plex forum to get some answers on this: https://forums.plex.tv/discussion/177461/when-do-buffer-events-get-triggered

**Comment by drzoidberg33** [comment]
Released in v1.1.0

https://github.com/drzoidberg33/plexpy/releases/tag/v1.1.0
