### ISSUE TITLE
Do not send a notification of added items in certain directories 

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#290]
E.g. I don't want a notification when things are added in directories with /archive/ in it. Is this possible? 

Keep up the good work! 

Grts

**Comment by cdrracing** [comment]
+1

**Comment by roelbeun** [comment]
@JonnyWong16 do you know if this can be implemented? else iam going to figure out another way through PlexPy. Would be great if directory info is available for you guys.

**Comment by JonnyWong16** [comment]
Directory or Plex Library? If you mean library, we are working on a lot of library stuff in #263.

**Comment by roelbeun** [comment]
Yeah that would be great. Then you know that there are /archive directories added to the library. And a preg match or something can filter those out for not sending notifications.

**Comment by cdrracing** [comment]
I would also love to see this happen.  I'm looking for a way to update my users of recently added movies but not notify them when a new picture from my phone gets added.

**Comment by JonnyWong16** [comment]
Added in v1.3.0.

You can disable recently added notifications per library.

**Comment by cdrracing** [comment]
How?   I can't seem to find it.  I'm running 1.30

**Comment by JonnyWong16** [comment]
Libraries > Edit mode.

**Comment by cdrracing** [comment]
Got it, thank you for the quick response!

**Comment by roelbeun** [comment]
This is not what i meant with this feature request. Both of my /incoming/movies and /archive/movies are in the same library: Movies. This is a Plex feature to add multiple folders to one library.

I want to distinct /incoming/ and /archive/ from eachother to send notifications. Is this possible?

**Comment by JonnyWong16** [comment]
It is possible, but I think it would be a lot of work for something so specific.

I would suggest using the Script notification agent with your own script to filter them out.

**Comment by roelbeun** [comment]
Good alternative. Is the played item directory available in a variable to use in the script? Can't find it in the argument list.

**Comment by JonnyWong16** [comment]
Hmm, I can add stuff like `{rating_key}` to the available options in the next update.

Then you can pass `{rating_key}` as an argument to your script and parse the XML at the Plex API endpoint `/library/metadata/<rating_key>` to get the `file` attribute in the `<Part>` tag. From there you can perform your directory filters.

For now (until we update the PlexPy API), I think you can send a request back to PlexPy `/test_notifier` with the parameters `config_id`, `subject`, and `body` for PlexPy to send the notification. The `config_id` for the notification agents can be found here: https://github.com/drzoidberg33/plexpy/blob/master/plexpy/notifiers.py#L43

**Comment by JonnyWong16** [comment]
Unique identifiers for notifications are added in v1.3.4.

**Comment by roelbeun** [comment]
I find it very hard to reproduce for example the Facebook notification including the skip directory part. Maybe a good enhancement is to pre-notify run a script and post-notify ability.

So for example.
1. New item has been added in /archive/movies
2. Pre-notify script runs
3. pre-notify script looks at directory and skips because /archive/ is in it
4. No notify is being send

Example 2:
1. New item has been added in /archive/incoming
2. Pre-notify script runs
3. Pre-notify script looks at directory and checks pass on directory
4. Notify (all agents) are triggered

**Comment by roelbeun** [comment]
@JonnyWong16 you think the above is a proper enhancement?

**Comment by JonnyWong16** [comment]
Just use the script notification agent and disable Facebook notifications.
