### ISSUE TITLE
Always show active stream timestamps

### ISSUE THREAD

**Issue by realvz** [Tautulli/Tautulli#295]
Perhaps others are interested in this one too....
I wanted PlexPy to always show me stream activity timestamps [PLAYED:TOTAL e.g., 14:00/28:00 ] and not just on hover.

I changed "opacity" value from 0 to 1 in plexpy/data/interfaces/default/css/plexpy.css

.dashboard-activity-poster-info-bar {
    position:absolute;
    width: 100%;
    height: 100%;
    background-image: -webkit-gradient(linear,left 30%,left 100%,from(rgba(0,0,0,0)),to(rgba(0,0,0,0.75)));
    background-image: -webkit-linear-gradient(top,rgba(0,0,0,0),30%,rgba(0,0,0,0.75),100%);
    background-image: -moz-linear-gradient(top,rgba(0,0,0,0) 30%,rgba(0,0,0,0.75) 100%);
    background-image: linear-gradient(to bottom,rgba(0,0,0,0) 30%,rgba(0,0,0,0.75) 100%);
    opacity: 0;
    -webkit-transition: all .2s;
    transition: all .2s;
    z-index: -2;

**Comment by drzoidberg33** [comment]
Thanks for the tip. Closing this.
