### ISSUE TITLE
Telize (http://telize.myhtpc.co.za/) returning incorrect IP

### ISSUE THREAD

**Issue by realvz** [Tautulli/Tautulli#296]
Telize hosted at http://telize.myhtpc.co.za/ is returning incorrect IP. Instead of returning info about the queried IP, it shows info of the IP that is requesting info.

https://telize.myhtpc.co.za/geoip/X.X.X.X will return source IP info.

Not sure if this should be filed here at PlexPy but just wanted to let someone know.

**Comment by drzoidberg33** [comment]
Derp. My bad, I'll fix this now.

Thanks for the report.

**Comment by drzoidberg33** [comment]
Fixed

**Comment by realvz** [comment]
Works now! Thanks.
