### ISSUE TITLE
Bug: HTTPAuth is always set to default values when updating settings

### ISSUE THREAD

**Issue by onedr0p** [Tautulli/Tautulli#297]
I use my own http_auth via nginx. Anytime I make a change in the settings, and plexpy restarts, http_auth gets set back from null to the username dev and password dev. I have to clear those inputs before saving.

**Comment by drzoidberg33** [comment]
Sounds like your browser has saved these values or you have a password manager autofilling them in.

Just remove this saved password and it will solve your issue.

**Comment by onedr0p** [comment]
That's prolly it, weird I don't use those username and passwords for anything. That's why I was confused lol
