### ISSUE TITLE
Show library name in notification message. e.g. {library_name}

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#298]
Is it possible to add a Notification string substitution for the library name the item is added? Now the closest info i can find is "{media_type} The type of media being played (movie, episode, track).". I want to show the library name in the notification.

**Comment by zobe123** [comment]
+1

**Comment by JonnyWong16** [comment]
Todo in #263.

**Comment by JonnyWong16** [comment]
Added in v1.3.0.
