### ISSUE TITLE
After start over terminal

### ISSUE THREAD

**Issue by patschi** [Tautulli/Tautulli#3]
When I start PlexPy without any additional parameters the following text appears:
![image](https://cloud.githubusercontent.com/assets/2029878/8393322/3d0a919a-1d0b-11e5-9ec6-1cc61c88afb1.png)

Log messages are overwriting this text; nothing is updating and it just looks a bit strange. Should that be updated? Is that a planned feature?

**Comment by drzoidberg33** [comment]
This happens if the "Launch browser on Startup" option in the settings is enabled. What you're essentially seeing is a browser in your terminal. To fix this just disable that option in the settings.

**Comment by patschi** [comment]
Ah, right. Thank you! :)
