### ISSUE TITLE
Broken after commit 69403dbf07dd597652238d58d39af2c2d95635dd

### ISSUE THREAD

**Issue by MaartenMol** [Tautulli/Tautulli#30]
I just updated to commit 69403dbf07dd597652238d58d39af2c2d95635dd

After that I got this on my home page: There was an error communicating with your Plex Server. Please check your settings.

Nothing in the settings menu seems to work. When I hit save on PMS it even says Server Verified!

I rather not throw away my database.... Bug or is this totaly my fault?

PS: When I hit this link: There was an error communicating with your Plex Server. Please check your **settings**. I land on the old settings page. Don't think that is supposed to be ;)

**Comment by drzoidberg33** [comment]
The commit you references had no code changes at all (only images) so it's definitely not that which caused your issue.

Please update to the commit I just made, it fixes the issue of links directing to the wrong page.

Also, please just go to your settings and re-enter you server settings afterwards to see if that helps.

**Comment by MaartenMol** [comment]
I don't  know what fixed it, but it did! Very strange.... Thanks tho!
