### ISSUE TITLE
Pushover error

### ISSUE THREAD

**Issue by cdrracing** [Tautulli/Tautulli#301]
I had pushover working for a while and it suddenly stopped.  The only thing I can think of that I changed was the notification message.
I've tried changing disabling pushover and reinserting my Pushover key but I'm still getting "Pushover request failed"
Any ideas?

**Comment by JonnyWong16** [comment]
See http://forums.plex.tv/discussion/comment/1069637/#Comment_1069637

**Comment by cdrracing** [comment]
Got it. Thank you!
