### ISSUE TITLE
Can't import plexWatch database

### ISSUE THREAD

**Issue by pinklon** [Tautulli/Tautulli#302]
I get the following error and can supply a link to the DB file if needed.  The database is over 2 years old and ~ 120MB.  Thanks for the terrific application!  Can't wait to successfully import the plexWatch data!!

26-Nov-2015 17:29:17 - DEBUG   :: Thread-27 : PlexPy Importer :: PlexWatch data import in progress...
26-Nov-2015 17:29:17 - DEBUG   :: Thread-27 : PlexPy Importer :: Disabling monitoring while import in progress.
26-Nov-2015 17:29:17 - INFO    :: Thread-27 : Removed background task: Check for active sessions
26-Nov-2015 17:29:17 - INFO    :: Thread-27 : Removed background task: Check for recently added items
26-Nov-2015 17:29:17 - INFO    :: Thread-27 : Requesting users list refresh...
26-Nov-2015 17:29:18 - INFO    :: Thread-27 : Users list refreshed.
26-Nov-2015 17:29:18 - ERROR   :: Thread-27 : Uncaught exception: Traceback (most recent call last):
  File "/opt/plexpy/plexpy/logger.py", line 210, in new_run
    old_run(_args, *_kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/opt/plexpy/plexpy/plexwatch_import.py", line 344, in import_from_plexwatch
    session_history_metadata = {'rating_key': helpers.latinToAscii(row['rating_key']),
  File "/opt/plexpy/plexpy/helpers.py", line 95, in latinToAscii
    for i in unicrap:
TypeError: 'NoneType' object is not iterable

**Comment by drzoidberg33** [comment]
Which version of PlexWatch is this from? The database must be from version 0.3.2 or higher.

**Comment by pinklon** [comment]
v0.3.3-DEV

**Comment by drzoidberg33** [comment]
Can you send me the db? Probably easiest to send a PM on the Plex Forum.

**Comment by pinklon** [comment]
Sent a PM on Plex Forum.  Many thanks!

**Comment by drzoidberg33** [comment]
Thanks got it. Will test in a moment.

**Comment by drzoidberg33** [comment]
Cool, it's pretty simple fix. For some reason one of the entries in your plexWatch db has a blank `ratingKey` value which we hadn't checked for.

I'll release a fix for this shortly.

**Comment by pinklon** [comment]
Excellent!  Thanks!

**Comment by drzoidberg33** [comment]
Please test with v1.2.6.

**Comment by pinklon** [comment]
Working now!  Thanks again!
