### ISSUE TITLE
Notifications not working - tested with Pushover/Pushbullet/Telegram

### ISSUE THREAD

**Issue by b2001l** [Tautulli/Tautulli#304]
I have just installed Plexpy and I am having difficulty getting the notifications to work.

Error: Request Failed 
When starting/pausing/stopping TV Show

I have tested for Telegram, Pushover and Pushbullet apps and all three are not working. 

Notifications are all enabled in the UI (see screenshot)
Notification Agent enabled in the UI with correct API info

Logging shows::(for Pushover)

27-Nov-2015 10:32:21 - DEBUG   :: Thread-13 : PlexPy ActivityProcessor :: Requesting log lines...
27-Nov-2015 10:32:22 - DEBUG   :: Thread-13 : PlexPy ActivityProcessor :: Unable to find IP address on first pass. Attempting fallback check in 5 seconds...
27-Nov-2015 10:32:22 - INFO    :: Thread-32 : Pushover request failed: 
27-Nov-2015 10:32:27 - DEBUG   :: Thread-13 : PlexPy ActivityProcessor :: Requesting log lines...
27-Nov-2015 10:32:27 - DEBUG   :: Thread-13 : PlexPy ActivityProcessor :: Matched IP address (XX.XXX.XXX.XX) for stream ratingKey 5146.
27-Nov-2015 10:33:21 - DEBUG   :: Thread-21 : PlexPy Monitor :: Removing sessionKey 536 ratingKey 5146 from session queue
27-Nov-2015 10:33:21 - DEBUG   :: Thread-21 : PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 5146
27-Nov-2015 10:33:22 - INFO    :: Thread-33 : Pushover request failed: 
27-Nov-2015 10:35:22 - INFO    :: Thread-34 : Pushover request failed: 
27-Nov-2015 10:36:22 - INFO    :: Thread-35 : Pushover request failed:

![image](https://cloud.githubusercontent.com/assets/1453356/11444442/52d2278a-9525-11e5-916b-1d29d6d1e40c.png)

![image](https://cloud.githubusercontent.com/assets/1453356/11444448/5ac8ff54-9525-11e5-9490-82df4c463eaa.png)

![image](https://cloud.githubusercontent.com/assets/1453356/11444496/89afe4c2-9525-11e5-95cb-ebaae9080512.png)

**Comment by drzoidberg33** [comment]
Regarding Pushover, you must use your own API token (see here: https://pushover.net/api). The default one only has capacity for 7,500 messages (for everyone using it) which gets used up mid-month normally, if you use your own API token you can have 7,500 just for yourself.

With Telegram ensure your bot has been started (/start).

With Pushbullet, I'm not sure why it's failing, it's working on my end. All I can recommend is double checking your access token.

Please ensure you have gone through these points, if you still have trouble please let me know.

**Comment by drzoidberg33** [comment]
@b2001l:

Do you have any feedback on this?

**Comment by b2001l** [comment]
Hi,
My apologies. 

Telegram is working as per your suggestion. 

I have removed the other two. However it was most likely config issues on my side as they were working for you.

Thanks for your help.

Regards,

**Comment by lazyb0nes** [comment]
Hey there thought id post here since I have managed to get the test notifications workig with pushbulletand email, and I have enabled notifications for movies/series/music but itdoesn't send me any, any idea why?

The tests works fine but it doesn't send me any emails or Pushbullet notifications. 

Anyway drzoidberg, thanks for an awesome application.
