### ISSUE TITLE
Disable Git updates by default.

### ISSUE THREAD

**Issue by falstaff1288** [Tautulli/Tautulli#307]
Hi. I would like to manage PlexPy updates through a package manager (ex: pacman for ArchLinux) instead of through the app with Git. Is it possible to disable the update functionality so that default installs, especially for the master branch, will never get the possibility of upgrading through the service?

**Comment by Hellowlol** [comment]
I cant possible understand why you would prefere pacman, but you can start with reading the config ini. There are several option related to git there.

**Comment by falstaff1288** [comment]
- I'm making an AUR package since there's none atm for this app. Updates in this case needs to be managed by the PKGBUILD file and related files, the AUR and the package manager.
- I believe the config.ini file won't appear until it's been generated after the first launch of PlexPy.py

**Comment by Arcanemagus** [comment]
I would imagine you could create a config.ini file with just the parts related to disabling `git` updates, and it would fill in the rest on first launch. Test it though as I'm just guessing :stuck_out_tongue:.

**Comment by falstaff1288** [comment]
Arcanemagus: Tried it and it doesn't work. I guess I'll just use the default method for now.

**Comment by JonnyWong16** [comment]
It should work if you create `config.ini` with 

```
[General]
check_github = 0
check_github_on_startup = 0
```

Before running PlexPy for the first time.

**Comment by falstaff1288** [comment]
After shutting down the initial run, this is the options written automatically in the config file by the app:

[General]
check_github = 1
check_github_on_startup = 0

Not sure if that first option being true will cause any issues. Two small details though: a notification at the bottom right still asks to update since the version is deemed unknown and the "Git updates" option in the parameters is still checked. 
- After all, I'll just distribute the code as you guys intended. I'll do a plexpy-git package for Arch's AUR to put the right files at the right places and that's it.

**Comment by drzoidberg33** [comment]
@falstaff1288 

That flag gets set on the first run wizard, here: https://github.com/drzoidberg33/plexpy/blob/master/data/interfaces/default/welcome.html#L172

Because we're using the same configuration save procedure as the main settings we need to send through things we want enabled otherwise it will be off by default.

**Comment by falstaff1288** [comment]
@drzoidberg33 I've set the "check_github" option to 0 before starting an new install for the first time and yep, it works. I'll add a patch to my PKGBUILD.

Thank you guys for helping me.

**Comment by falstaff1288** [comment]
BTW, here's the AUR package for PlexPy I've just done, including a patch that disables Git Updates (which isn't possible anyway with the way the permissions are set):

https://aur.archlinux.org/packages/plexpy-git/

Thanks again.
