### ISSUE TITLE
Group Music Tracks into Album for Notifications

### ISSUE THREAD

**Issue by phunkysai** [Tautulli/Tautulli#310]
Currently I'm getting a notification for every single music track when someone plays an album. It would be nice if there was an option in PlexPy to group music notifications into albums so that I would only get one notification that says -  {user} has started playing {album}  - and then does not notify me again as long as they stay on that same album.

Thanks for this great application...love it!

**Comment by drzoidberg33** [comment]
I'd like this too.

**Comment by spuniun** [comment]
second this for recently added notification as well.

**Comment by mbnn** [comment]
Yes, this would be awesome, please add this since right now, even with Music notifications disabled it spams notifications with every single track of music. (for purely music that is, not for tv shows) :)
