### ISSUE TITLE
Twitter Setup Issues

### ISSUE THREAD

**Issue by realvz** [Tautulli/Tautulli#313]
I am trying to setup Twitter notifications and when I hit Request Authorization button, it doesn't do anything. I have tried this in multiple browsers and made sure popups are not blocked.

There are no entries in the log when I hit the button. I tried to get the oauth username and password and saved it in the config.ini file and enabled twitter but plexpy is still asking me for a key.

Also tried running plexpy manually in verbose mode and didnt see any activity when I hit the "Request Authorization" button.

**Comment by drzoidberg33** [comment]
Could you see if there is any error in the browser's console when you click the button.

I am unable to replicate this issue on any of my installations.

**Comment by realvz** [comment]
Figured out the issue.... I have the base URL changed for my Reverse Proxy and links on notifications_config.html page do not accommodate that.

Here's what I changed, to make it work. I suppose other links in that file also need to be modified for other notifications agents setup.

/opt/plexpy/data/interfaces/default$ diff notification_config.html notification_config.html.bak 
109c109

## <         $.get("twitterStep1", function (data) {window.open(data); })

> ```
>     $.get("/twitterStep1", function (data) {window.open(data); })
> ```
> 
> 115c115
> 
> ## <         $.get("twitterStep2", { 'key': twitter_key }, function (data) { $('#ajaxMsg').html("<i class='fa fa-check'></i> " + data); });
> 
> ```
>     $.get("/twitterStep2", { 'key': twitter_key }, function (data) { $('#ajaxMsg').html("<i class='fa fa-check'></i> " + data); });
> ```
> 
> 119c119
> 
> ## <         $.get("testTwitter",
> 
> ```
>     $.get("/testTwitter",
> ```

**Comment by drzoidberg33** [comment]
Thanks for the info.

Can you share what your reverse proxy config looks like?

**Comment by realvz** [comment]
Here it is. 
http://paste.ubuntu.com/13715265/

**Comment by JonnyWong16** [comment]
I believe this should be fixed in v1.3.1.
