### ISSUE TITLE
Incorrect IP reporting

### ISSUE THREAD

**Issue by camjac251** [Tautulli/Tautulli#315]
Not sure if this was reported or not but IPs appear as ::ffff:1.1.1.1 (1.1.1.1 being an example, my ip would go here) and trying to see the ip info gives an error.

**Comment by JonnyWong16** [comment]
Mentioned here: https://forums.plex.tv/discussion/comment/1070008/#Comment_1070008

I'm thinking of just changing it to IPv4 only.

**Comment by Arcanemagus** [comment]
That's one of the ways that IPv4 addresses can be translated to IPv6, in other words this is probably correct if you have enabled IPv6 in Plex.

**Comment by drzoidberg33** [comment]
As this is not really a bug (and I think Jonny has already addressed this), I'm closing this.
