### ISSUE TITLE
Making calls for server availability even when disabled

### ISSUE THREAD

**Issue by drzoidberg33** [Tautulli/Tautulli#318]
I have remote monitoring disabled and no notification triggers enabled yet on every monitor call PlexPy is still making requests for availability.

```
02-Dec-2015 22:03:07 - DEBUG :: Thread-14 : PlexPy HTTP Handler :: [PUT] http://192.168.1.3:32400/myplex/refreshReachability
02-Dec-2015 22:03:15 - DEBUG :: Thread-14 : PlexPy HTTP Handler :: [GET] http://192.168.1.3:32400/myplex/account
```

**Comment by JonnyWong16** [comment]
The setting "Monitor Plex Remote Access" toggles the check for the port mapping. The check for a server response runs regardless of that setting.

I guess the setting should be changed to include both checks.

**Comment by drzoidberg33** [comment]
The regular server up/down check shouldn't need to poll those URLs. The refreshReachability endpoint causes PMS to talk to plex.tv every time, if we don't need this it should be disabled.

**Comment by drzoidberg33** [comment]
Cool, I believe this is resolved.

Thanks Jonny.
