### ISSUE TITLE
Recently added calls being made even when disabled

### ISSUE THREAD

**Issue by drzoidberg33** [Tautulli/Tautulli#319]
The recently added job is doing a lot of calls to PMS, if we don't have recently added enabled it shouldn't be making these calls.

**Comment by JonnyWong16** [comment]
Check if any notifier has `on_created` enabled? or implement another global toggle for recently added?

**Comment by drzoidberg33** [comment]
I'd prefer (and would be easier) to include a global toggle.

**Comment by JonnyWong16** [comment]
Should be fixed in v1.3.0.
