### ISSUE TITLE
PlexPy not recognizing password

### ISSUE THREAD

**Issue by rstuke82** [Tautulli/Tautulli#322]
I have PlexPy all setup, I went to restart it and now it isn't accepting my password.  It was working just fine until I restarted it. Any ideas?

**Comment by JonnyWong16** [comment]
You can reset the username and password by setting the following in the `config.ini` file.

```
http_username = ""
http_password = ""
```

**Comment by rstuke82** [comment]
Got it, thank you

**Comment by drzoidberg33** [comment]
Most likely the browser saving a password.

Closing.

**Comment by rstuke82** [comment]
Yes it was browser saving password.  Apparently I have another app that also uses port 8181.  Hoping to find a way to change it.

**Comment by Arcanemagus** [comment]
You can change the PlexPy port in the settings. (Edit the config file before starting if you are unable to access it.)
