### ISSUE TITLE
Daemon setup on 10.11.1

### ISSUE THREAD

**Issue by nojkepop** [Tautulli/Tautulli#323]
I am having issues getting PlexPy setup as a Daemon.  I am running 10.11.1.  Pglexpy runs fine when I use the python command from the terminal but I can't seem to get it to work as a Daemon.  I followed the instructions for Yosemite or later but when I reboot its not running. I also can't seem to manually launch it other than the terminal command.

**Comment by drzoidberg33** [comment]
I have no problem on 10.11.1 using the exact instructions outlined here: https://github.com/drzoidberg33/plexpy/wiki/Install-as-a-daemon#mac-os-x

Please can you provide exactly the commands you're running and the output you're receiving.

**Comment by ghost** [comment]
Sadly, I'm stuck trying to setup a daemon myself. I'm using OS X 10.9.5 and get the following when I try to launchctl:

Epicurus:PlexPy paulpangrazzi$ launchctl [load | unload] ~/Library/LaunchAgents/com.drzoidberg33.plexpy.plist
-bash: unload]: command not found
launchctl: unknown subcommand "[load"

(I can successfully launch manually with "python PlexPy.py")

**Comment by JonnyWong16** [comment]
The `[load | unload]` means pick one.

So either `launchctl load ~/Library/LaunchAgents/com.drzoidberg33.plexpy.plist` to start  PlexPy.
Or `launchctl unload ~/Library/LaunchAgents/com.drzoidberg33.plexpy.plist` to stop PlexPy.

**Comment by ghost** [comment]
@JonnyWong16 Firstly: Thank you.
Secondly: Facepalm.

**Comment by nojkepop** [comment]
I am copying and pasting the commands directly into the terminal and they all seem to run fine.  Since I have done it more than once it isn't actually copying the .plist file since it is already there.  After running these commands PlexPy is not running even if I reboot.  The only way I can access it via the browser is if I run the python command. Here is a copy of terminal after I run the commands.

Mac-Mini:~ User$ cp /Applications/PlexPy/init-scripts/init.osx ~/Library/LaunchAgents/com.drzoidberg33.plexpy.plist
cp: /Users/User/Library/LaunchAgents/com.drzoidberg33.plexpy.plist and /Applications/PlexPy/init-scripts/init.osx are identical (not copied).
Mac-Mini:~ User$ sudo chmod 0600 ~/Library/LaunchAgents/com.drzoidberg33.plexpy.plist
Password:
Mac-Mini:~ User$ sudo chown root ~/Library/LaunchAgents/com.drzoidberg33.plexpy.plist
Mac-Mini:~ User$ launchctl load ~/Library/LaunchAgents/com.drzoidberg33.plexpy.plist
Mac-Mini:~ User$

**Comment by JonnyWong16** [comment]
Have you tried deleting the `.plist` file and copying again? Someone else has this problem and that seemed to work.

**Comment by nojkepop** [comment]
That fixed it!  I knew it had to be something simple. Thanks for your help.

**Comment by JonnyWong16** [comment]
Resolved, closing.
