### ISSUE TITLE
Feature Request: Notifications - Add a tag for Video Resolution and Audio codec and channels

### ISSUE THREAD

**Issue by dshokouhi** [Tautulli/Tautulli#329]
Hope this is the right way to make this request.  It would be neat to be able to add a tag for video output resolution (i.e. SD, 720p, 1080p, 4k, etc...) and also audio codec (i.e. Dolby Digital, DTS, Dolby TrueHD, etc..) and the amount of supported channels (i.e. 2.0, 5.1, etc...).  This way we can put that information in our custom notifications :)

**Comment by JonnyWong16** [comment]
Added inn v1.2.15.

**Comment by dshokouhi** [comment]
thank you :)

**Comment by dshokouhi** [comment]
@JonnyWong16 I am noticing that the new tags are showing blank results, i double checked to make sure I am using them right but no dice.  Do you need me to grab logs and post them/create a new issue?

**Comment by JonnyWong16** [comment]
Which tags in particular? Depending on the stream/media, some tags might not be available.

**Comment by dshokouhi** [comment]
Oh ok, I was trying to use it to display the quality of recently added media in a notification but looks like its for a stream only huh?

**Comment by JonnyWong16** [comment]
If it's listed under stream details on the settings page, then it's stream only for now. But that's a good idea to add some of them for metadata details.

**Comment by dshokouhi** [comment]
I guess I should provide a use case with my next feature request....but seriously though thank you for implementing this :)
