### ISSUE TITLE
Stuck at refresh users list

### ISSUE THREAD

**Issue by Qosmo** [Tautulli/Tautulli#330]
Plexpy isn't starting all the way.  I recently did a Freenas update, and noticed today Plexpy will start, but sits at Refresh Users List.  Eventually it times out, and shuts down.

![image](https://cloud.githubusercontent.com/assets/10797352/11611356/d6fbc8da-9b8e-11e5-94ce-f9006eee622c.png)

**Comment by JonnyWong16** [comment]
That looks right,  I don't see anything wrong with the logs. The scheduled tasks should be the last items when starting up PlexPy (with websockets disabled).

**Comment by Qosmo** [comment]
So it's been sitting there now for over an hour, and looks like this now.
![image](https://cloud.githubusercontent.com/assets/10797352/11612171/02c416ae-9bb5-11e5-9622-68087e208279.png)

**Comment by JonnyWong16** [comment]
What is the problem exactly? You can't access PlexPy in the web browser?

Everything seems to be working.

**Comment by Qosmo** [comment]
I have an active connection to my NAS, but as soon as I close the connection the PlexPy web interface stops working.

**Comment by JonnyWong16** [comment]
By connection you mean ssh? I think you need to set up PlexPy as a service so you can close the ssh connection.

**Comment by Qosmo** [comment]
Thanks for getting back to me JonnyWong16.  Yes, I'm using an SSH connection into my Freenas server.  I installed PlexPy about a month ago, and it's been running without issue since then.  I'll look around about starting this a service.

**Comment by JonnyWong16** [comment]
I wrote instructions for running PlexPy as a service here:
http://forums.plex.tv/discussion/comment/1056738/#Comment_1056738

**Comment by drzoidberg33** [comment]
Seeing as this is not an issue, I'm closing.
