### ISSUE TITLE
[Bug] Notification {server_name} tag value not populated in v1.2.8

### ISSUE THREAD

**Issue by mcroach** [Tautulli/Tautulli#331]
Using Prowl Notifications.

Subject line: PlexPy ({server_name})
Results in: PlexPy ()
Instead of the expected: PlexPy (PLEXSERVER)

**Comment by JonnyWong16** [comment]
Does your server name have any special characters?

**Comment by mcroach** [comment]
No it's straight ASCII (MISFITNAS).

**Comment by JonnyWong16** [comment]
Does your server name show up elsewhere on PlexPy?
- Home page beside "Library Statistics"
- In the title of the browser tab

**Comment by JonnyWong16** [comment]
I think this is fixed in 87ca432

**Comment by johnthepink** [comment]
I just installed PlexPy and had this issue too. The server name isn't in the browser tab title, and it's not in any notification that I tried (Boxcar, Pushover, Pushbullet, Telegram). I tried restarting a couple times.

**Comment by johnthepink** [comment]
It's not beside "Library Statistics" either

**Comment by JonnyWong16** [comment]
It should grab the name after a restart. If not check the logs for any errors or warnings.

**Comment by JonnyWong16** [comment]
Fixed in v1.3.0.
