### ISSUE TITLE
Error 500  on home screen page when plex server is offline

### ISSUE THREAD

**Issue by Magikarplvl4** [Tautulli/Tautulli#336]
When the plex server is offline or not responding, an ugly 500 error shows up on the home screen instead of a nice a beautiful text which indicates that the server is offline.
![plex error](https://cloud.githubusercontent.com/assets/2944704/11613789/febe198c-9c2d-11e5-9e10-2c292e88b264.png)

**Comment by JonnyWong16** [comment]
I am aware of this. It will be fixed with #263.

**Comment by JonnyWong16** [comment]
Fixed in v1.3.0.
