### ISSUE TITLE
[REQUEST] Throttle NZBGet

### ISSUE THREAD

**Issue by kylerw** [Tautulli/Tautulli#34]
Would be awesome to be able to throttle NZBGet (or SAB) based on the number of active streams. All in the name of great experience for those you share with.

**Comment by drzoidberg33** [comment]
This is a very specific task, this could be achieved by using a script notification as requested here already: https://github.com/drzoidberg33/plexpy/issues/25

Closing and marking as duplicate.

**Comment by kylerw** [comment]
Fair enough... I guess I assumed it would be used widely enough to warrant its own setting or notification type.
