### ISSUE TITLE
Music tracking

### ISSUE THREAD

**Issue by wsmeichinllc** [Tautulli/Tautulli#342]
I recently added my music collection to Plex, then turned on Music tracking in PlexPy.  It appears that the graphs pick up when music is played from the plex app, but not when it's played via DLNA.  Is there an easy fix to this?

Thanks, in advance, for a truly useful app.

**Comment by drzoidberg33** [comment]
Does it show up in Plex Web's Now Playing screen? If not, then PlexPy won't be able to track it.

**Comment by wsmeichinllc** [comment]
No, it doesn't show up there.  It does appear in '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex DLNA Server.log', but it doesn't actually contain the file name, just an object UUID.

**Comment by JonnyWong16** [comment]
Sorry, PlexPy can only log items if they show up on Plex Web's now playing.
