### ISSUE TITLE
There was an error communicating with your Plex Server. Please check your settings.

### ISSUE THREAD

**Issue by Drewster727** [Tautulli/Tautulli#344]
Looks like v1.2.8 - v1.2.12 seems to have broken my plexpy "streams" view on the main page. I can't seem to find anything out of the ordinary in the logs except for a couple warnings:

Failed to access uri endpoint /identity with error [Errno 113] No route to host
Failed to access uri endpoint /status/sessions with error [Errno 111] Connection refused

Everything is exactly as it was before, except that I ran the plexpy updates this morning. I tried toggling SSL, changing to use the IP instead of hostname, rebooting both servers, etc... No luck.

I'm on PMS v0.9.12.19. -- I haven't updated this in a while. Nothing has changed in my PMS configuration.

Any ideas?

<img width="581" alt="screen shot 2015-12-06 at 1 04 42 pm" src="https://cloud.githubusercontent.com/assets/4528753/11615003/f31e5736-9c19-11e5-95ac-77b8583a1ccd.png">
<img width="860" alt="screen shot 2015-12-06 at 1 05 11 pm" src="https://cloud.githubusercontent.com/assets/4528753/11615005/06727880-9c1a-11e5-8311-2e5cdaef25fe.png">

**Comment by drzoidberg33** [comment]
Jonny just pushed a fix. Update to 1.2.13

**Comment by JonnyWong16** [comment]
Should be fixed in v1.2.13.

EDIT: Got ninja'd.

**Comment by Drewster727** [comment]
Looks good now. Thanks guys.
