### ISSUE TITLE
Feature Request: Support for multiple plex servers

### ISSUE THREAD

**Issue by Drewster727** [Tautulli/Tautulli#347]
I'm starting to hit a fair number of users and am considering setting up a secondary PMS install on another server to handle certain types of content. I would love to see plexpy allow me to add more than one server. I understand this would be a difficult task to some degree, but would be rather useful to allow monitoring from one interface. (as opposed to setting up a secondary plexpy)

My apologies if this has been requested before.

Thanks!

**Comment by JonnyWong16** [comment]
Duplicate #113.
