### ISSUE TITLE
Recently Added Notifications (Pushbullet) Not Working in Version 1.2.13 

### ISSUE THREAD

**Issue by mannibis** [Tautulli/Tautulli#348]
Git hash: fc0be6bce20c0452abd1b7b5f5faab1a98ae72ee

After updates today, notifications for Recently Added stopped working. Other notifications (Started, Watched) are OK. I'm using the Websocket method.

I see the following in PMS logs:

Dec 06, 2015 16:53:15   ERROR   EventSource: Retrying in 15 seconds.
Dec 06, 2015 16:52:59   ERROR   EventSource: Retrying in 15 seconds.
Dec 06, 2015 16:52:48   ERROR   Couldn't get remote endpoint: remote_endpoint: Invalid argument

**Comment by JonnyWong16** [comment]
There's a new checkbox to enable recently added notifications. Is that checked?

**Comment by mannibis** [comment]
Well, I feel dumb. Was that there before? Sorry

**Comment by JonnyWong16** [comment]
It was changed in v1.2.8+.
