### ISSUE TITLE
[Request] Quality of movie/epsisode

### ISSUE THREAD

**Issue by Drewster727** [Tautulli/Tautulli#349]
I like that I can click on a movie or episode in PlexPy and it will provide me with most of the info about it. I would love to see the quality of the video file somewhere on this info page as well. Similar to how plex web shows it:

![q](https://cloud.githubusercontent.com/assets/4528753/11615864/aee57050-9c31-11e5-96b1-965f93d2a3d6.png)

Thanks!

**Comment by dshokouhi** [comment]
+1

**Comment by HamilcarH** [comment]
+1

**Comment by JonnyWong16** [comment]
Added in v1.3.0.
