### ISSUE TITLE
Mako runtime error: "TypeError: sequence item 299" when trying to enter the Settings menu

### ISSUE THREAD

**Issue by falstaff1288** [Tautulli/Tautulli#351]
It's a white page showing this:

"Error !

TypeError: sequence item 299: expected string or Unicode, NoneType found

return self.delim.join(self.data).encode(self.encoding, self.errors) else: return self.delim.join(self.data) class LRUCache(dict): """A dictionary-like object that stores a limited number of items, discarding lesser used items periodically.

/opt/plexpy/lib/mako/util.py, line 145:
return self.delim.join(self.data)

/opt/plexpy/lib/mako/runtime.py, line 804:
return context._pop_buffer().getvalue()

/opt/plexpy/lib/mako/template.py, line 443:
return runtime._render(self, self.callable_, args, data)

/opt/plexpy/plexpy/webserve.py, line 50:
return template.render(server_name=server_name, **kwargs)"

**Comment by falstaff1288** [comment]
Found the source of the issue: it happens because 'CHANGELOG.md" wasn't present into the /opt/plexpy folder in my install. That didn't happened with v1.2.7

**Comment by drzoidberg33** [comment]
@falstaff1288 Do you know why the file wasn't there?

**Comment by falstaff1288** [comment]
Don't worry, it's me who've arbitrarily chosen to not included the file in the ArchLinux's PKGBUILD script I've written this past week. Thought it wasn't necessary to keep it after disabling git updates; I was wrong.

**Comment by drzoidberg33** [comment]
Thanks. Closing this issue then.
