### ISSUE TITLE
[Request] Viewed TV/Movies List and Export to Excel

### ISSUE THREAD

**Issue by Coolmanchambers** [Tautulli/Tautulli#354]
Looking for an easier way to manage my TV and Movie selection, and removing stuff that hasn't been accessed to save space.  For a future enhancement, is it possible to click on one of your libraries, and see a list of your shows/movies (similar to user view). Seeing data like when it was last accessed, how many plays it has, last user to access, and maybe the last episode to be watch for TV shows?

Another request would be have an export to excel button for the history/user data?  I would love to play around with it once i get a good amount of data and look at some of the statistical and analytical data in there.

Thanks for the amazing work you have done with Plexpy, i absolutely love it!

**Comment by JonnyWong16** [comment]
Duplicate, see #192, #154.

Working on library features in #263.
