### ISSUE TITLE
Server Is Not Sending Recently Added Notifications

### ISSUE THREAD

**Issue by slamanna212** [Tautulli/Tautulli#357]
I have recently added notifications setup for pushbullet and twitter, and the settings under notifications are: https://i.imgur.com/8dJwdLk.png

It sends tests tweets successfully and i can see that plexpy notices new media being added, but does not send the notification

**Comment by JonnyWong16** [comment]
Do you have the global "Enable Recently Added Notifications" checked?

**Comment by slamanna212** [comment]
Yes: https://i.imgur.com/BHP0MMp.png

**Comment by JonnyWong16** [comment]
And Twitter > Bell icon > Notify on Recently Added checked?

**Comment by slamanna212** [comment]
Yes it is! https://i.imgur.com/2DZ6o0I.png

**Comment by JonnyWong16** [comment]
And the logs say "Item ### was recently added to Plex."? Any other errors or warnings?

**Comment by slamanna212** [comment]
08-Dec-2015 12:15:57 - DEBUG :: Thread-17 : PlexPy Monitor :: Library item 2228 has been added to Plex.
08-Dec-2015 12:33:57 - DEBUG :: Thread-16 : PlexPy Monitor :: Library item 2229 has been added to Plex.

**Comment by slamanna212** [comment]
Those are the 2 newest entries

**Comment by JonnyWong16** [comment]
Oh, currently, you also need to check "Enable Movie/TV Show/Music Notifications".

I plan on changing this in the future.

**Comment by slamanna212** [comment]
Ah!!! Thank you! Let me try that!

**Comment by slamanna212** [comment]
Its working now! Thanks!
