### ISSUE TITLE
Can´t communicate with server, most likely because invalid character in device name

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#358]
![untitled](https://cloud.githubusercontent.com/assets/7231558/11669117/3a40e560-9dfb-11e5-8a21-a7349ba920ed.png)

Hi there and thanks for a great software!

Straight to point. I´ve been having some issues that plexpy cant communicate with server properly. It´s rare, but I think I found the culprit. Whenever this device is used "Theréses ipad", plexpy gets "can´t communicate with server" or something similar, and I cant get stats or users currently playing. Nor does plexpy register this session in "history". Not sure if this is a known issue? Thanks!

**Comment by JonnyWong16** [comment]
This is a known issue with the Plex iOS app, not PlexPy. There is nothing we can do until Plex fixes it.

#212

**Comment by ghost** [comment]
Ok thanks for the answer!

tisdag 8 december 2015 skrev JonnyWong16 notifications@github.com:
