### ISSUE TITLE
Ability to generate a log file of all the current settings

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#359]
When someone has an issue with plexpy there is always asked if certain settings are set. 

For one, maybe it means there is allot to set and the users/me included, are not aware of what's is necessary to enable a feature. 

But maybe it is possible to easily generate a text which holds all the current settings in the plexpy instance, and maybe some debug info. 

It can make debugging issues more helpful I think. 

Any thoughts?

**Comment by JonnyWong16** [comment]
All settings are stored in the `config.ini` file.
