### ISSUE TITLE
Notification for recently added tv/movies

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#36]
can you also add the possibility to send push notification for recently added movies like plexwatch /opt/plexWatch/plexWatch.pl --recently_added=movie,tv

**Comment by drzoidberg33** [comment]
I actually have a different plan for recently added.

I won't be adding it to the regular notifications but plan to do something like scheduled mailer to subscribed users that sends out a weekly/daily mail with recently added, recommendations, watch stats, etc.

Not sure yet though when this will be done yet.

**Comment by krsandvik** [comment]
@drzoidberg33 That will be very nice! Would also like an option to easily send a mail when I do maintenance with the server. And how about getting a notification when the server is offline? Then you can also make a new graph with up time stats. Thanks for an awesome application!

**Comment by Arcanemagus** [comment]
@drzoidberg33 just my two cents, but having the recently added be a part of the regular notification system is a requirement for me if this is to replace plexWatch. I have it automatically send out a push to Pushbullet whenever a new item is added so people I have shared it to can just subscribe to that to see when things they have asked for are ready.

**Comment by drzoidberg33** [comment]
@Arcanemagus I won't be adding this functionality to the current notification agents settings but it most likely will find it's way into a new section which will be dedicated to communication with shared users. 

I'm not yet sure on what this is going to look like and what it will encompass but I have some general ideas which I'm going to start playing with.

**Comment by mbnn** [comment]
It would be very handy if you could add Pushover/Twitter notifications for newly added stuff :)

**Comment by mbnn** [comment]
@drzoidberg33 if you could add recently added (tv show episodes/movies) with the option to push it to pushover/twitter, i can drop plexwatch completely :P thx!

**Comment by AcidRain999** [comment]
so you are not adding a notification push for new content? is there a reason why, its a popular feature because to be honest i dont care when people start, stop or finish watching something, what i do care to know is when things are added

**Comment by drzoidberg33** [comment]
@AcidRain999 Please see my last reply on this.

**Comment by mbnn** [comment]
Completely agree with @AcidRain999 here, I mean I never understood why people care about when someone stops/starts something, pushing notifications to twitter/pushover/others is more interesting for when things get added (New content).

**Comment by Arcanemagus** [comment]
@mbnn as @drzoidberg33 said in https://github.com/drzoidberg33/plexpy/issues/36#issuecomment-126450336 he is planning on addressing this, just not yet.

**Comment by roelbeun** [comment]
Translation of Comment #36: It will be added, but not in that particular screen.

So i assume we can use pushover for new entries in de Plex DB but it wont be able to set the notification in the screen Notification Agents.

+1 for this feature!

**Comment by ghost** [comment]
this sounds great!

Can you also had the conventional notification of newly added to twitter? I have a private twitter account setup in which plexwatch posts a new tweet when something is added.

**Comment by zobe123** [comment]
would be nice to see this Feature very soon, actually i use PlexReport but it does not work like it should.

thank you @drzoidberg33 for your work and your Future-work!

**Comment by kylerw** [comment]
Love this. +1

**Comment by vulcanjedi** [comment]
Both PlexNotify/PlexWatch did this, PW did it best for more media. I agree to most that recently added is more usful but the other is good too, so that other people can know if the PMS is taxed and thus they  could save their frustration or support issues.

**Comment by zobe123** [comment]
...would be nice if you realize posting into a Facebook Group :+1: +1

**Comment by mbnn** [comment]
Any update on this? :)

**Comment by drzoidberg33** [comment]
@t-enk requested:

It would be very nice if you add an Recently added report where is send to all or specific users in a defined time period.
-send report by mail with recently added movies/tv shows
-define recipients
-define time interval when report should send

**Comment by yajinni** [comment]
+1 on getting push notifications on when something is added to my plex server!

**Comment by rock7632** [comment]
@Arcanemagus Can you please tell how you set up Recently added notifications in PlexWatch for your Pushbullet channel subscribers? I created a channel but in the Plexwatch config file the only option for pushbullet is "Device Iden" and that pushes to your own device and not on the channel. I would appreciate your help. Thanks

**Comment by Arcanemagus** [comment]
@rock7632 It sounds like you need to update your plexWatch script, the current version's config.pl-dist should be rather clear on how to configure it.

https://github.com/ljunkie/plexWatch/blob/dev/config.pl-dist#L147-L149

The key is leaving the device field blank, and filling in the channel.

Also as this is the PlexPy account you should probably have filed that question over on the plexWatch account :wink:.

**Comment by rock7632** [comment]
@Arcanemagus Thanks for the link. Yes, I realize that but since I read your comment that you had done this, I thought about asking you here. :+1:

**Comment by derek3x** [comment]
I will add a plus 1 to this feature as well.

Especially being able to send an email once a week to selected people with the recently added movies and tv for the week.  That would make plexpy amazing.

**Comment by mpatton125** [comment]
+1 Would also love this functionality to be added.  Whilst PlexPy looks great and I am sure has many uses for many people - personally I am just looking for it to take over notiying my (via NMA) when new content is added.  Currently I have SickRage do this for TV and CouchPotato do this for movies but would rather be notified by Plex when the content is added to the library.

**Comment by Swiftnesses** [comment]
I'd love this too, great for my IFTTT recipes!

**Comment by zobe123** [comment]
I am planning post into a Facebook group via Twitter notification/or Mail.

**Comment by mbnn** [comment]
From what I know, you cannot post from twitter into a facebook group ;) That needs to go direct.

**Comment by zobe123** [comment]
@mbnn: Don't tell me what I can do or not, when I already doing it ;-)

btw, plexnotify/plexpy is posting into a facbook group via email and also IFTT works as well.

**Comment by mbnn** [comment]
If you do twitter > fb group, pls tell me how :P With IFTTT i only see Facebook and FB Pages not groups.

**Comment by zobe123** [comment]
off-topic:
aktivate the group mailadress of your facebook-group. via IFTT yo can send from twitter to your group via mail. don't think so narrow-minded... 
or use the integrated twitter function: https://support.twitter.com/articles/31113#

**Comment by drzoidberg33** [comment]
@JonnyWong16 

I see when we use the Websocket method with grouping enabled that Premium music libraries are reporting when new Vevo music videos are added too.

I don't see this as an issue really but there is no information in event to let us know it's music videos being added. Possibly have to call up the metadata and check there first if we want to exclude them.

What the `completed` event looks like:

``` javascript
{u'itemID': 29471, u'title': u'Bloc Party', u'sectionID': 12, u'_elementType': u'TimelineEntry', u'state': 5, u'updatedAt': 1447030594, u'queueSize': 4, u'type': 8}
```

**Comment by JonnyWong16** [comment]
@drzoidberg33 

Is `"sectionID": 12` your music library? I know when Movie extras are added the `sectionID` is `-1`, I'm not sure if Music videos work the same way.

**Comment by drzoidberg33** [comment]
`sectionID` is only -1 for the separate items. The `state=5` event that triggers the notification when grouped doesn't look any different than if a new album was added.

**Comment by chopeta** [comment]
+1 for this enhancement... excellent discussion by the way.

I would like to see both options enabled :D

A real-time notification with details (this would be only for me - actually I just bout an app on Play Store for this) and an email summary for my shared users and people that doesn't want to get disturbed by daily notifications or don't/can't go check on external apps or sites like FB and Twitter.

**Comment by JonnyWong16** [comment]
@drzoidberg33 

I can't think of a way to get the metadata for the music video when we're triggering a notification at the Artist level.

Also, for the issue with notifications for episodes:
I was wrong, the metadata for episodes isn't complete until the TV Show is done refreshing. This might be why episodes are missing the `state=5` event.

If we can figure out a way to get the child metadata when we see `state=5` for Artists and TV Shows, then we can solve both these problems.

The activity pinger seems more reliable than web sockets right now.

**Comment by mbnn** [comment]
Guys, I expect that this will work as Recently added Message body?

`Added: <movie>Movie: {title} ({year})</movie> <tv>TV: {title} {show_name} {episode_name} (S{season_num}E{episode_num})</tv> <music>Music: {artist_name} - {album_name}</music>`

To Pushover and Twitter.

**Comment by JonnyWong16** [comment]
@mbnn 

Yes, it should work.

**Comment by mbnn** [comment]
Im not getting any push notifications at all (for recently added) when using what i pasted above, not on Twitter, nor on Pushover. Ive added a few episodes and movies, but nothing. It does say the new stuff on Recently added on the main page of Plexpy though. Any idea?

I have enabled: Enable Movie and TV Notifications
and on Notification Agents i have pushover and twitter enabled (with the right keys).

The only thing i see in the logs is:
2015-11-11 21:20:48 INFO    Pushover request failed: Bad Request
2015-11-11 21:20:47 INFO    Pushover request failed: Bad Request

**Comment by JonnyWong16** [comment]
Did you enable Notification Agents > Bell icon > Notify recently added?

**Comment by mbnn** [comment]
@JonnyWong16 

Yes I did, actually it seems Twitter works but shows like this:
`Servername: Added: <movie>Movie: The Flash (2014) (2014)</movie> <tv>TV:  The Flash (2014) (SE1)</tv> <music>Music:  - </music>`

**Comment by JonnyWong16** [comment]
Do you have "Group notifications for recently added TV Shows or Music" enabled?

I think that might be the bug.

**Comment by mbnn** [comment]
I did, i disabled that now.

**Comment by mbnn** [comment]
Still shows to much on twitter: Servername: Added: Scream Queens (2015) - Mommie Dearest TV: Scream Queens (2015) Mommie Dearest (S1E8).

And pushover still says: Pushover request failed: Bad Request

Im gonna try this:
`<movie>Movie: {title} ({year})</movie> <tv>TV: {show_name} {episode_name} (S{season_num}E{episode_num})</tv> <music>Music: {artist_name} - {album_name}</music>`

This seems to be working :) It was indeed a problem with group notifications.

**Comment by JonnyWong16** [comment]
I will have to do some more testing on this.

As for Pushover request failed, that seems like a different problem.

**Comment by mbnn** [comment]
Im now using this:

Subject line:
`{media_type} added`

Message body:
`<movie>{title} ({year})</movie> <tv>TV: {show_name} {episode_name} (S{season_num}E{episode_num})</tv> <music>{artist_name} - {album_name}</music>`

This seems to work :)

**Comment by krohrsb** [comment]
So I was reading the comments and it seemed there was support already for added notifications. I had to dig it it looks like its on the `dev` branch. Good to know :)

Thank you for the telegram integration! I was hoping that would come about.

I got telegram to work, so thank you.

I am finding some odd behavior with some of the meta tags. `{year}` and `{content_rating}` don't seem to be working. Is this info not available yet (plex still parsing metadata?)

**Comment by JonnyWong16** [comment]
Do you have websockets enabled?
What type of media (movie, episode, track)?
Do you have "Group notifications for recently added TV Shows or Music" enabled?

**Comment by JonnyWong16** [comment]
Another bug with websockets.

Overnight I got ~50 recently added notifications. I think it has to do with the scheduled maintenance on the server which refreshes metadata.

**Comment by mbnn** [comment]
Websockets I have disabled btw.
But I would suggest to built in a 60 sec delay on sending out notifications. As sometimes the scanners are not done yet and then it will show: movie added: Ant-Man () instead of movie added: Ant-Man (2015).

**Comment by zobe123** [comment]
+1 Yes! delay would be fine.

**Comment by mbnn** [comment]
Also, disabling Music notifications only doesnt seem to work, it still gives me every single track of a newly added album :(

**Comment by JonnyWong16** [comment]
@drzoidberg33 
I think we just need to stick with the activity pinger for checking for recently added items. The websocket just doesn't provide reliable responses.

**Comment by drzoidberg33** [comment]
@JonnyWong16 

Agreed. That's fine with me.

**Comment by mbnn** [comment]
Can we please fix the option to not throw Recently added music to all notification agents? I can enable or disable that option now but it still shows up everywhere when i add new music (each and every song gets pushed). And I cannot enable Group notifications since then it wont display correctly as said above :P

**Comment by drzoidberg33** [comment]
It should only send to agents which have the option enabled. If it's not doing this then could you log this as a separate bug?

**Comment by drzoidberg33** [comment]
Added in 1.2.4.
