### ISSUE TITLE
[Request] Automatic SABnzbd throttling

### ISSUE THREAD

**Issue by danswiser** [Tautulli/Tautulli#360]
When I have a number of users streaming from my Plex server, I sometimes need to pause or throttle the downloads in SABnzbd to prevent all my bandwidth from being used.

Since plexpy is always monitoring my plex usage, it seems like its the best tool to also manage the max speed in SABnzbd when certain criteria are met.

My idea was something as simple as:

If streams < 1 then SABnzbd max = 10MB,
If streams < 2 then SABnzbd max = 6MB,
If streams < 3 then SABnzbd max = 2MB

**Comment by Hellowlol** [comment]
I think it should be a script "notification." (on event)

**Comment by JonnyWong16** [comment]
#25
