### ISSUE TITLE
4k TV shows not showing up in Plexpy, totally ok in PMS 

### ISSUE THREAD

**Issue by icenine9** [Tautulli/Tautulli#361]
So here's something I recently noticed... Plexpy seems to think my 4k TV section doesn't exist. Not sure why. Can this be corrected somehow?

![image](https://cloud.githubusercontent.com/assets/16182988/11677650/0444fd26-9e0e-11e5-8943-c6c26ffc5760.png)

**Comment by drzoidberg33** [comment]
Check Settings -> Homepage Statistics -> Library Statistics and make sure the section is selected.

**Comment by icenine9** [comment]
Yep. That was it. I guess I missed that somehow and assumed your code was ignoring it. Sorry about that.

**Comment by drzoidberg33** [comment]
No problem, glad you sorted.
