### ISSUE TITLE
Feature request: Hardware stats/transcoding details

### ISSUE THREAD

**Issue by alexc-MSFT** [Tautulli/Tautulli#362]
Thought of an idea for a feature addition to PlexPy today - add a section on the homepage - probably at the top to show the stats of the machine itself i.e. CPU Load/CPU Temp, No of Plex transcoder processes active, Memory usage etc.

PlexPy may do some of this already so please advise.

If you think it's viable i'm keen to contribute (.NET dev by trade) - let me know if you are happy for me to contribute.

**Comment by Hellowlol** [comment]
You can use psutil to do this. There are some code in htpc manager that you can use https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/stats.py, I think it would be a cool feature, it has been requested before see https://github.com/drzoidberg33/plexpy/issues/175

**Comment by alexc-MSFT** [comment]
Nice one! I take it the previously requested feature hasn't actually been done yet?

**Comment by Hellowlol** [comment]
I dont think anybody has started on it now. You might wanna check with @drzoidberg33 and @JonnyWong16 before you start :) I think you would make alot of users happy ^^

**Comment by drzoidberg33** [comment]
We all would welcome contributions, the only requirement that I have for this is that any solution like this is cross platform or if that's not possible should be completely invisible to unsupported platforms.

**Comment by drzoidberg33** [comment]
I'm going to close this issue. Any further discussion on this can be done on #175
