### ISSUE TITLE
[REQUEST] Disable tracking of a certain library

### ISSUE THREAD

**Issue by my95z34** [Tautulli/Tautulli#364]
First of all, I just set up PlexPy today and I absolutely love it.  I've got quite a few people on my server so it's great knowing what's going on at all times.

Anyway, on to the request.  I have a Pre-Roll library that plays a video before anyone plays a movie.  PlexPy is logging those as 'Movie' plays and it's messing with the overall playback numbers.  I have the library in Plex listed as 'Home Movies'.

Is there any setting I can change to fix this?  Or is it something that would have to be implemented on your end?

I just looked through the settings and I don't see anything.  I've disabled that library from showing on my home page but it still logs the plays.

Thanks for the great 'app' (I guess that's what it would be called, lol) and thanks in advance for any input!

**Comment by JonnyWong16** [comment]
Duplicate #216, and disable logging by library will be in #263.

**Comment by my95z34** [comment]
Shit... Sorry man.  I fail.-___-
