### ISSUE TITLE
[Request] Support GitHub API token to avoid update errors

### ISSUE THREAD

**Issue by apicht** [Tautulli/Tautulli#366]
I was unable to update today due to hitting the GitHub API ratelimit. I can generate an OAuth token to be used by the app to avoid this but I don't see anywhere to put it in the PlexPy configuration.

```
10-Dec-2015 23:30:10 - INFO :: MainThread : Retrieving latest version information from GitHub
10-Dec-2015 23:30:10 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
10-Dec-2015 23:30:10 - ERROR :: MainThread : Request raise HTTP error with status code 403 (local client error).
10-Dec-2015 23:30:10 - DEBUG :: MainThread : Server responded with message: {"message":"API rate limit exceeded for 68.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documen...
10-Dec-2015 23:30:10 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?
```

**Comment by Hellowlol** [comment]
The limit is 60 request pr hour. Wtf are you using it for?

**Comment by apicht** [comment]
Something odd must be going on then. I simply clicked on the update notification when I logged into PlexPy and after it restarted the notification was still there. Once I dug into logs I saw it was unable to update due to the rate limit.

**Comment by Arcanemagus** [comment]
Are you on a shared connection?

**Comment by apicht** [comment]
I live with a couple other people, one of which is a developer. It is possible that he was pulling something down in the same hour, but unlikely given the time of day.

**Comment by OmgImAlexis** [comment]
I'm getting the same issue as I use quite a few tools that connect to the API without a token.

```
Server responded with message: {"message":"API rate limit exceeded for ********. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documen...
```

**Comment by JonnyWong16** [comment]
GitHub API token added in v1.3.12.
