### ISSUE TITLE
Recently added custom notification

### ISSUE THREAD

**Issue by HamilcarH** [Tautulli/Tautulli#369]
hi,

I'm trying to add a custom notification for recently added music: 

<music>{album_name} ({year}) from {artist_name}.</music>

but the notification I get on my agent (I tried with twitter and telegram, same result, is this: Recently Added: () from .

is there anything I'm missing ? I have a fairly large library but new content gets picked up first so metadatas are loaded relatively quickly, even if my library scan ends an hour later.

also the custom notification I use for movies works fine and looks like this:

<movie>{title} ({year})

Directed by: {directors}

Starring: {actors}

Plot: {summary}</movie>

Thanks for your help !

**Comment by JonnyWong16** [comment]
Do you see any errors or warnings in the PlexPy logs?

**Comment by HamilcarH** [comment]
It just logs that the notification was sent

**Comment by HamilcarH** [comment]
I just tried another custom notification for TV Shows: <tv>{show_name} S{season_num00}E{episode_num00} {episode_name}.</tv>

Again, none of the fields are showing anything.

**Comment by JonnyWong16** [comment]
Do you have the setting "Group notifications for recently added TV Shows or Music" checked or unchecked?

**Comment by HamilcarH** [comment]
Checked.

**Comment by JonnyWong16** [comment]
I think I found a bug in the code, but you also won't get any of 
`{album_name}`, `{year}` for music or `{season_num00}`, `{episode_num00}`, `{episode_name}` for tv shows because of the checked setting.

The setting sends notifications at the Artist or TV Show level, so it doesn't have any album/track or season/episode data.

**Comment by HamilcarH** [comment]
Ah ok, so it means that I'll get a notification for each track, when adding music ?

**Comment by JonnyWong16** [comment]
Yes, with the setting _unchecked_. I'll have to fix the bug with the setting _checked_.

**Comment by HamilcarH** [comment]
So if the bug is fixed, will my custom notification work ?

**Comment by JonnyWong16** [comment]
Hopefully. I'm fixing it now.

**Comment by HamilcarH** [comment]
Thanks a lot for the quick support !

**Comment by JonnyWong16** [comment]
Metadata for group recently added notifications should be fixed in v1.2.15.
