### ISSUE TITLE
/etc/init.d/plexpy: 425: .: 3: Too many open files

### ISSUE THREAD

**Issue by Jonn3y** [Tautulli/Tautulli#372]
Heyho,

i used the Install-as-a-Deamon-Guide https://github.com/drzoidberg33/plexpy/wiki/Install-as-a-daemon
After doing all the steps and trying to start the service: service plexpy start
it says:
/etc/init.d/plexpy: 425: .: 3: Too many open files

Im using Debian and tried the ubuntu-skript
what i've done wrong?!

**Comment by Jonn3y** [comment]
found a solution:
i copied the ubuntu-script into /etc/default/plexpy (THAT'S WRONG :D)
after recreating the empty file i works!

**Comment by drzoidberg33** [comment]
Did you follow the instructions in the script file: https://github.com/drzoidberg33/plexpy/blob/master/init-scripts/init.ubuntu
