### ISSUE TITLE
[Request] Change default port from Headphones default port

### ISSUE THREAD

**Issue by boopzz** [Tautulli/Tautulli#375]
Most people who will use PlexPy will have Headphones installed already (like myself).

Seems obvious to me to change the default port to something other than the default for Headphones.

Maybe change it to 8182 for instance?

**Comment by zobe123** [comment]
You can edit in config.ini - you have to stop plexpy first

**Comment by boopzz** [comment]
Yeh I know you can change it, I thought it might be helpful for new users is all.

**Comment by Hellowlol** [comment]
Yeah but it would be pain for all other. After a update they can't find a there yo. Breaks reverse proxy etc. that's why I haven't changed it for htpc manager

**Comment by JonnyWong16** [comment]
If I change the default, it won't change any existing configs. It would only affect new installs.

Can anyone think of a way this might screw something up?

**Comment by zobe123** [comment]
How about a fallback port (eg. 7171) if on 8181 Something else is running... 
So it remains simple.
Later adjust the port in the settings table, whatever you want...

**Comment by JonnyWong16** [comment]
How about this? #449

**Comment by zobe123** [comment]
not sure if you zuckerberging me or just make this idea better. :D :D
![image](https://cloud.githubusercontent.com/assets/13840542/12376872/51e8d452-bd09-11e5-8b68-6a23eaa97d73.png)
