### ISSUE TITLE
Any chance this could be ported to Emby?

### ISSUE THREAD

**Issue by tymanthius** [Tautulli/Tautulli#379]
I'm switching to Emby from Plex (both are great, just Emby will fit me better), and was wondering if anyone was willing to port this to support Emby?  Emby already logs the data, so it shouldn't be impossible. But I'm not a coder, so I don't have a clue as to how hard it would be.

**Comment by Arcanemagus** [comment]
Basically the entire backend would need to be re-written, so... rather time consuming.

**Comment by tymanthius** [comment]
Gotcha, so it would have to be a true port, not just a tweak.  Damn. Was hoping.  

One day, the day right after I get to sleep in, I'll learn to program.  ;)
