### ISSUE TITLE
[Aliases for player names] Option to rename the platorm/user

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#38]
Like in plexwatch, have this option in plexpy

Give a user a more friendly name. I.E. REAL_USER will now be Frank
you may also specify the platform with user+platform
$user_display = {'User+TV UE55D7000' => 'TV Living',
                 'User+TV UE46ES8000' => 'TV Bedroom',
                 'User+Chromecast' => 'Chromecast',
                 'User+Plex Web (Chrome)' => 'iMac',
                 'User+Plex for Sony (PlayStation 4 01.17)' => 'PS4',

**Comment by kylerw** [comment]
You can already do this for the User (from the user profile, click the edit pencil). I don't believe it works specifically with the platform, though.

**Comment by drzoidberg33** [comment]
Thanks @kylerw. Yes the current Friendly name only matches the user name and not a username+platform combo.

It actually gets a bit complicated if I had to implement something like this as I'm primarily matching records in the database with the user_id, so having "different" users with the same id is going to pose some challenges.

Not impossible but not something that I'm probably going to get to soon, if ever.

**Comment by drzoidberg33** [comment]
Friendly names have been available since the start but I won't be adding aliases for user+platform combos. It complicates things too much and will require changes to practically every database query that references users.

If somebody else wants to take a stab at this feel free.

**Comment by elRadix** [comment]
I understand, can we the an alias name for the platform names ?

TV UE55D7000 = Room 1
TV UE46ES8000 = Room 2

**Comment by drzoidberg33** [comment]
@elRadix Yep. We can do that.

**Comment by jroyal** [comment]
I actually started looking at this last night. It might be possible to have a friendly name given to each device using the machine_id. Granted this would require a slight reworking of the platform list to show unique devices instead of a the platform as a whole.

**Comment by Lardnapkin** [comment]
Greetings...
Any update to this?. I would love to be able to assign an alias to either of the above mentioned...

**Comment by Stankerne** [comment]
I know that issue is open for a long time now, but, any update please ? I also really would like this feature...
