### ISSUE TITLE
[Feature Request] Improve card selection in settings

### ISSUE THREAD

**Issue by zobe123** [Tautulli/Tautulli#383]
cant select any Library Statistics Cards neither IE, FF, Safari. (Watch Statistics Cards is workin)

also i would prefer this solution for this purpose: http://formvalidation.io/examples/bootstrap-multiselect/
(the example "Browser" without the searchbar)

**Comment by JonnyWong16** [comment]
I'm in the process of changing the card selections similar to Plex Web > Settings > Web > Dashboard.

**Comment by zobe123** [comment]
ok, thank you, sounds all fine

**Comment by JonnyWong16** [comment]
Added in v1.3.0.
