### ISSUE TITLE
Most Active User vs Play Duration

### ISSUE THREAD

**Issue by DFKnight** [Tautulli/Tautulli#384]
Does Most Active User under Watch Statistics on the Home page include Paused Time as well?

**Comment by JonnyWong16** [comment]
No, it doesn't count paused time.

**Comment by DFKnight** [comment]
I was under the impression that the most active user would have the highest play duration but I've noticed that the most active user is not the same as the user with the highest Play Duration (Shown in the Graphs page at the bottom right chart). Do these represent two different values?

EDIT: I have changed the title to reflect the question being asked here: What is the distinction between the Most Active User and Play Duration?

**Comment by JonnyWong16** [comment]
Is your time range for the watch statistics and graphs set to the same value?

**Comment by DFKnight** [comment]
I have data for about 3 months. My time range is set to 1 year.

**Comment by DFKnight** [comment]
I just noticed the Time Frame value in the Settings Page. After changing it to 1 year, it's showing the correct information.

Sorry for any confusion this might have caused!
