### ISSUE TITLE
Telegram bot notification recently added, subject not mandatory 

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#385]
Can you make the subject optional for telegram notifications? Now I see "Server name: my message content" when I have "Server name" as subject. 

Maybe it is mandatory for other types of notification like pushover.. Not for telegram. 

Thanks.

**Comment by jackwilsdon** [comment]
+1 same for Twitter, don't need a subject.

**Comment by JonnyWong16** [comment]
Added in v1.3.7.

Optional subject line toggle for Facebook, Slack, Telegram, and Twitter.
