### ISSUE TITLE
Pushover notification issue after latest update

### ISSUE THREAD

**Issue by nojkepop** [Tautulli/Tautulli#386]
Ever since updating to the latest version I am not longer receiving Pushover notifications.  I get this error in the logs.  
20-Dec-2015 17:20:47 - INFO    :: Thread-33 : Pushover request failed: 

I've tried removing all account details and reconfiguring.  I also setup Boxcar2 and can confirm that is working.  Any help would be greatly appreciated.

I was also wondering if you'd consider adding like a test notification button where it sends a notification to all that are setup.

**Comment by JonnyWong16** [comment]
But, no changes were made to the Pushover code... :confused: 

Just tested, still works for me.

```
20-Dec-2015 15:45:41 - INFO :: Thread-24 : Pushover notifications sent.
```

**Comment by nojkepop** [comment]
Hmm, well I just tried creating a new pushover account and set up the app on my iPad(I was using an iPhone originally) and I am still not receiving notifications. 

Is there anyway to completely reset the notification settings? I deleted my entire PlexPy directory and downloaded a fresh copy but both my Pushover and Boxcar settings are still in there even after rebooting.

**Comment by JonnyWong16** [comment]
Try clearing your browser cache?

**Comment by drzoidberg33** [comment]
Are you using your own API token? This is required.

**Comment by JonnyWong16** [comment]
Is this still a problem?

Your own Pushover API token is required starting with v1.3.0.

Reopen the issue if it is still a problem.
