### ISSUE TITLE
Plex.py run as a Service

### ISSUE THREAD

**Issue by scotth4711** [Tautulli/Tautulli#387]
Was wondering if there was a way to run the Plex.py as a service or minimized in the task bar rather than as a normal program?

**Comment by Hellowlol** [comment]
Open the program with pythonw.exe or see htpcguides.com how to run Python programs as a service

**Comment by JonnyWong16** [comment]
See http://forums.plex.tv/discussion/comment/1022992/#Comment_1022992
or https://www.reddit.com/r/PleX/comments/3u3c3y/how_do_you_monitor_your_server_usage/cxccbxi

**Comment by RobertSmits** [comment]
This is what I use to make programs run as service:
https://nssm.cc/

**Comment by drzoidberg33** [comment]
Please use above resources, this isn't a PlexPy issue.
