### ISSUE TITLE
Double History Play

### ISSUE THREAD

**Issue by damianeickhoff** [Tautulli/Tautulli#388]
Goodmorning! (From the Netherlands)

I've updated to 1.2.15 this morning and the first thing I noticed was that the history was doubled. So if one episode was played, plexpy shows it as 2. Its hard for me to explain, so I added an picture. Do you have any idea what the problem is?

![capture](https://cloud.githubusercontent.com/assets/12126826/11927068/f89b57ac-a7c9-11e5-96e5-50c5eeab140e.PNG)

Kind Regards

**Comment by drzoidberg33** [comment]
Is this for all history or only new things after the update?

**Comment by damianeickhoff** [comment]
Its also happening to history before the update, but is variable. There is no structure in it, because sometimes its just normal and sometimes its double. It almost looks like its random.

**Comment by drzoidberg33** [comment]
When you say _sometimes_ what do you mean exactly? As only some of the items are duplicated or all of them are duplicated but only on some page loads?

**Comment by damianeickhoff** [comment]
Ah, sorry for being unclear. I ment that some items are duplicated. As far as I can see, the first duplicated entry is at 25-11. But as I said, its not with all the history, but it looks like its getting more duplicated the more you go to the present. 

Again, sorry if i'm being unclear, English is not my native language haha.

**Comment by damiantje99** [comment]
@drzoidberg33 Have you forgotten me, good man? :)

**Comment by JonnyWong16** [comment]
Reopen if this is still an issue.
