### ISSUE TITLE
[Request] Make Log show 100 lines pr page Default

### ISSUE THREAD

**Issue by DesertRec** [Tautulli/Tautulli#389]
I find myself always change the log to show 100 lines pr. page, would like to see this default.

**Comment by moexius** [comment]
in your PlexPy installation folder go to \plexpy\data\interfaces\default\js\tables.Open history_table.js with your text editor of choice. Search for history_child_options.pageLength and change the value to 100. As far as I could see this edit does the trick. 

Hopefully DrZoidBerg33 will add an option to the settings or history page to select own defaults.

**Comment by drzoidberg33** [comment]
@moexius: I wouldn't recommend changing any source files as it will break auto updates.

**Comment by JonnyWong16** [comment]
And that's not the right file or the right line in the code to change...

**Comment by moexius** [comment]
i think i was too enthusiastic trying to help. That edit is not necessary i can see that I only need to select the value i want like 25 or 100. And the change is persistent after restarting PlexPy

**Comment by moexius** [comment]
@JonnyWong16 I already realized that. Thanks!

**Comment by Hellowlol** [comment]
+1

**Comment by moexius** [comment]
Tested it with chrome and firefox and the change to 100 in History and Logs is permanent in my end.

**Comment by Hellowlol** [comment]
I assume its this one, didnt test it. https://github.com/drzoidberg33/plexpy/blob/master/data/interfaces/default/js/tables/logs.js#L7

**Comment by moexius** [comment]
@Hellowlol do you also have the issue reported by @coz2001?

**Comment by Hellowlol** [comment]
Yes, i think 10 is to little.

**Comment by DesertRec** [comment]
Excellent, Thanks for the fast update.
