### ISSUE TITLE
[REQUEST] Movie/TV Requests

### ISSUE THREAD

**Issue by kylerw** [Tautulli/Tautulli#39]
There are plans to do a mailer for recently added which is pulling in functionality from other tools built by the community. I like the idea and feel it makes sense to have it within plexpy.

Similarly, I think a "requests" feature much like PlexRequests (https://github.com/lokenx/plexrequests-meteor) might also be a nice fit and a great addition to the tool.

**Comment by MaartenMol** [comment]
I +1 this! Keep up the great work btw!

**Comment by alexandrupaulpopa** [comment]
+1

**Comment by phunkysai** [comment]
I would love to see this as well!

**Comment by antoinesylvia** [comment]
+1
