### ISSUE TITLE
Log IP

### ISSUE THREAD

**Issue by Tubweb** [Tautulli/Tautulli#392]
My Plexpy does not log ip addresses for my users. I use it in Windows 7 nad Plexpy version 1.2.15
The settings is on - Enable IP loging is ON.

Is it something i missed ?

**Comment by Arcanemagus** [comment]
Have you specified your log folder path under the Plex Media Server section? As far as I know this is still necessary to get the IP address (It might not be as of 0.9.14 though).

**Comment by Tubweb** [comment]
Yes - Logs Folder: goes to C:/Users/xxxx/AppData/Local/Plex Media Server/Logs

**Comment by JonnyWong16** [comment]
Check the PlexPy logs for any lines with the text `Matched IP address` or `Unable to find IP address`.

You can also check if you set up the logs folder path correctly by going to the Logs tab and clicking on Plex Media Server.

**Comment by Tubweb** [comment]
Cant find any of those texts

**Comment by zobe123** [comment]
I'm not sure but there was anything about extended server protocols in my plex server config, under general tab, this checkbox must also been activated.

**Comment by JonnyWong16** [comment]
Did you figure this out?

Reopen the issue if it is still a problem.
