### ISSUE TITLE
[request] Notifications Indexers

### ISSUE THREAD

**Issue by damianeickhoff** [Tautulli/Tautulli#393]
Hi,

I was looking for a program that could monitor my services, like Sonarr, Couchpotato. Couldn't find anything good so I thought, maybe its an idea to add it to PlexPy? I'm aiming at notifications when a service is down, like you already did with Plex.

Could this be possible?

**Comment by elRadix** [comment]
you can use monit which best suited for these kind of services, it even can send pushbulllet/pushover notifications, you can find many examples if you google it 

sample for plex
http://www.htpcguides.com/monitor-autorestart-plex-media-server-service-failure/

![Image of Monit](http://i.imgur.com/7UYaege.png)

**Comment by damianeickhoff** [comment]
@elRadix It looks good, but i'm not running an UNIX OS, i'm running Server 2012.

**Comment by elRadix** [comment]
check here available for multiple platforms
https://mmonit.com/monit/

**Comment by damianeickhoff** [comment]
@elRadix Nope, not compatible with windows, checked also here: https://mmonit.com/wiki/MMonit/SupportedPlatforms

**Comment by elRadix** [comment]
otherwise run  linux through vmware or virtualbox

**Comment by damianeickhoff** [comment]
Could be an option, but still curious if its possible to add it to this repository. But thanks for your help!

**Comment by JonnyWong16** [comment]
Maybe this is more suited for [HTPC Manager](https://github.com/Hellowlol/HTPC-Manager) if not there already. @Hellowlol

**Comment by Hellowlol** [comment]
You can only control stuff, monitor stuff. There is no notification arm. But this has been requested before, I just haven't had the time since my services are never down.

**Comment by damianeickhoff** [comment]
@JonnyWong16 @Hellowlol Ah alright! I used HTPC Manager before and its very nice. If notifications are added, i will use it again!
