### ISSUE TITLE
Telegram notification error

### ISSUE THREAD

**Issue by HamilcarH** [Tautulli/Tautulli#394]
Hi, I'm trying to set up telegram notifications and I get this error using 1.2.15:

> Uncaught exception: Traceback (most recent call last):
> File "/opt/plexpy/plexpy/logger.py", line 210, in new_run
> old_run(_args, *_kwargs)
> File "/usr/lib/python2.7/threading.py", line 763, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "/opt/plexpy/plexpy/notification_handler.py", line 130, in notify
> body=notify_strings[1])
> File "/opt/plexpy/plexpy/notifiers.py", line 400, in send_notification
> telegramClient.notify(message=body, event=subject)
> File "/opt/plexpy/plexpy/notifiers.py", line 1535, in notify
> body=urlencode(data))
> File "/usr/lib/python2.7/httplib.py", line 979, in request
> self._send_request(method, url, body, headers)
> File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
> self.endheaders(body)
> File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
> self._send_output(message_body)
> File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
> self.send(msg)
> File "/usr/lib/python2.7/httplib.py", line 797, in send
> self.connect()
> File "/usr/lib/python2.7/httplib.py", line 1178, in connect
> self.timeout, self.source_address)
> File "/usr/lib/python2.7/socket.py", line 553, in create_connection
> for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> gaierror: [Errno -2] Name or service not known

My telegram bot isn't receiving anything, everything seems to be configured correctly.

thanks for your help !

**Comment by JonnyWong16** [comment]
Sorry, I missed this issue. Are your notifications still not working?

**Comment by HamilcarH** [comment]
Yep, still the same message with the latest version !

**Comment by JonnyWong16** [comment]
What is the notification subject and body you are trying to send? Have you tried other notification agents? Double checked your bot token and chat id?

**Comment by HamilcarH** [comment]
I've double checked my bot token and chat ID, same result.

Subject Line is: Recently Added

Message Body is: <movie>{title} ({year})

Directed by: {directors}

Starring: {actors}

{summary}</movie>
<tv>{show_name} S{season_num00}E{episode_num00} {episode_name}.

{summary}</tv>
<music>{album_name} ({year}) from {artist_name}.</music>

I've tried pushbullet without success.

**Comment by JonnyWong16** [comment]
Does telegram still not work?

Reopen the issue if it is still a problem.

**Comment by HamilcarH** [comment]
It wasn't working after the update so I reinstalled my docker container, it seems to be working now, thanks !
