### ISSUE TITLE
Error! KeyError: 'started'

### ISSUE THREAD

**Issue by dirtycajunrice** [Tautulli/Tautulli#395]
. I have just installed and it seems that it reads my library fine because it sees all users/movies/tv shows. but i have this odd info on the home page :
https://i.imgur.com/oFKhJDX.png

Would anyone know why this is occuring?

**Comment by JonnyWong16** [comment]
Just answered here:
https://forums.plex.tv/discussion/comment/1088651/#Comment_1088651

**Comment by dirtycajunrice** [comment]
Awesome i didnt see that thank you Jonny
