### ISSUE TITLE
Notifications show_name same as episode_name

### ISSUE THREAD

**Issue by jadsaffar** [Tautulli/Tautulli#397]
in the subject of the notifications i have set it to be as follows

started <movie>{title}</movie><tv>{show_name}({season_num}x{episode_num})</tv>

yet instead of the show name (ex. Suits) i get the episode name

any help or comments regarding this?

**Comment by JonnyWong16** [comment]
`{title}` returns the full title (show name and episode name)

**Comment by drzoidberg33** [comment]
Just remove the `{title}`.

**Comment by JonnyWong16** [comment]
It was a bug 7e5dce1.
