### ISSUE TITLE
[Feature Request] iOS (web)app

### ISSUE THREAD

**Issue by Patrick1610** [Tautulli/Tautulli#398]
Hi, 

I really like PlexPy and it is very usefull that I have it working outside my local network. 
The thing I really miss is the fact that there is no app (or webapp) available. 

~~Another thing that I would like to see fixed is the double history when a movie is played in two parts (see attached photo). This messes up the watch count and statistics.~~

Thanks for this great app and keep up the good work!!

Regards, 
Patrick 

<img width="1411" alt="screen shot 2015-12-25 at 16 09 22" src="https://cloud.githubusercontent.com/assets/6585375/12003505/b6a07556-ab22-11e5-98de-96bbb91e54ae.png">

**Comment by JonnyWong16** [comment]
See #156.

And enable "Group history" in the settings.

**Comment by Patrick1610** [comment]
Thanks for the tip! Didi't see that option :smile:

**Comment by Hellowlol** [comment]
Making it look like a webapp is like a 1 min fix :)

**Comment by realvz** [comment]
I've never used plexpy on a laptop other than for css debugging purposes, my primary device is ipad mini and with the help of a few css modifications plexpy web app is a fully functional app for me.

**Comment by Patrick1610** [comment]
@realvz: can you tell me how to do these modifications so it works like aan app?

@Hellowlol: why do you think so? I've added it to my homescreen and think it in easier If it worked like an app than just as a link te safari.

**Comment by JonnyWong16** [comment]
I'm not against modifying the code to suit your needs, but note that it will break updates.

**Comment by Hellowlol** [comment]
@Patrick1610 because it's like a one line of code. I don't "apps" but it would be easy to support both.

**Comment by JonnyWong16** [comment]
Added in v1.3.0.
