### ISSUE TITLE
[Feature Request] Intergrate PlexRequests into PlexPy

### ISSUE THREAD

**Issue by jkaberg** [Tautulli/Tautulli#399]
Is it only me or wouldn't it be cool to intergrate the functionality of [PlexRequests](https://github.com/lokenx/plexrequests-meteor) into PlexPy?

For this to happen one would need to,
- [ ] refactor user system with permission levels (perhaps with some kind of interaction with plex.tv account so that user can track his own history etc)
- [ ] add request system (with checks against CP/SR/Sonarr and Plex) and optional admin approval
- [ ] add issue system (eg. flag movie/series as broken/corrupt etc, perferebly with optional description for each submitted issue)
- [ ] notify owner on new requests/issues by push messages
- [ ] more..?

I like the idea of gathering tools like PlexPy and [PlexRequests](https://github.com/lokenx/plexrequests-meteor) into one seamless experience for end user convinience. 

What say you dev's?

**Comment by Sperryfreak01** [comment]
I would love this feature too!

**Comment by drzoidberg33** [comment]
Feel free to submit PRs, just please remember to work from the dev branch.

**Comment by Jonn3y** [comment]
+1 would be nice to use PlexRequest without meteor ect. !

**Comment by JigSawFr** [comment]
+1 coold be great !

**Comment by jkaberg** [comment]
User system could be done with [LgAuthority](http://tools.cherrypy.org/wiki/LgAuthority), long since updated tho

**Comment by thatsnasty** [comment]
+1

**Comment by dmptrluke** [comment]
I feel this is a bit beyond the scope of what PlexPy is supposed to do. All PlexPy does is collect and aggregate existing data and metadata from Plex. Adding TVDB/IMDB searching, a user login system, and API communication with download backends is a big ask and would add a significant amount of code

**Comment by Jonn3y** [comment]
All I'd need is a request-system! Auto download isn't necessary. Maybe as you sad, it should become it's own project. :/ just without meteor

**Comment by Majawat** [comment]
There's a newer build off of .NET instead of meteor: https://github.com/tidusjar/PlexRequests.Net

**Comment by Pakorro** [comment]
+1 with WhatsApp notifications included...

**Comment by lazyb0nes** [comment]
This would be really nice becuase then those latenight texts could stop if people could just put up requests and then ahv ethe owner deal with it as is.

**Comment by roelbeun** [comment]
Check out https://github.com/tidusjar/PlexRequests.Net

**Comment by luxus** [comment]
I found this old FR...
Ombi (thats what Plexrequests.net now called) have a api.. it would be awesome If I could see in Plexpy who requested a movie in my Plex library.. 
I still search a for a way to delete watched movies if the requester watched it.

**Comment by joewalch** [comment]
+1

Would love this too with Whatsapp integration. Both projects seemed to have moved on as far as integration is concerned, perhaps this would be easier now?

Reeuqest>admin
admin>whatsapp group when done.
