### ISSUE TITLE
DatabaseError: file is encrypted or is not a database

### ISSUE THREAD

**Issue by aaronchi** [Tautulli/Tautulli#4]
I get this error on Windows. Tried the advice in the troubleshooting but the downloadable sqllite3 dll doesn't seem like a drop in replacement and throws an error. Any other ideas on what might be causing this?

**Comment by drzoidberg33** [comment]
What is the exact version of Python you're using and what version of Windows?

**Comment by aaronchi** [comment]
Windows 8.1 and python 2.7 (latest). I'm going to try installing python 3.4 and using sqllite.dll from that installation.

**Comment by drzoidberg33** [comment]
PlexPy will not work with Python 3.4.

Did you shutdown and restart PlexPy after copying in the new dll?

**Comment by aaronchi** [comment]
Ah ok. Replacing the DLL works with the x86 version of python (I had x64 installed). Seems like downloading the latest DLL works, but would be nice if it worked out of the box.

**Comment by drzoidberg33** [comment]
Thanks for the update. I'm not sure why this is affecting some users. I tested on Windows 10 with Python 2.7.10 and didn't have this issue.

When I've got some time I'll see if I cannot figure out the cause of this.
