### ISSUE TITLE
[REQUEST] A few changes to the History section

### ISSUE THREAD

**Issue by Unbridle0065** [Tautulli/Tautulli#40]
1) Show cover art along with the text title.  (maybe a toggle to turn cover art on/off)
2) Make IP address clickable for each history item, showing the same IP information available in the Users section for each individual stream.
3) Show the actual viewing date AND time in the time column.

**Comment by drzoidberg33** [comment]
I think number 3 is actually a bug. It should allow you to do this, I'll look into that but marking this as Enhancement.

**Comment by drzoidberg33** [comment]
Okay, 3 is not a bug. It works fine on my end. I can set it to show exactly what I want by setting the date format in the Settings -> General tab.

**Comment by drzoidberg33** [comment]
Request 2 was just implemented here: https://github.com/drzoidberg33/plexpy/commit/c02b7a00791d8686036874161c017780903b0f2b

**Comment by Unbridle0065** [comment]
You are right, I missed that in the settings.  Thanks

IP info showing up in History.  Looks great, thank you!

**Comment by drzoidberg33** [comment]
Please just refresh the page.

**Comment by JonnyWong16** [comment]
Can close this issue.
