### ISSUE TITLE
No "Recently Added" notifications since last Plexpy update

### ISSUE THREAD

**Issue by fkick** [Tautulli/Tautulli#400]
Hi, I've been running Plexpy and Plex on my Mac (10.10.5) and since the latest PlexPy update, I'm unable to get recently added notifications for either tv or movies through email or iftt. I am getting playback and watch notifications normally, just not recently added. The web interface does show that it's detecting the new content under "recently added", but I'm not seeing anything in the Plexpy logs regarding attempts to send the notifications. 

Thanks!

**Comment by JonnyWong16** [comment]
Do you have "Enable Recently Added Notifications" checked in the settings?

**Comment by fkick** [comment]
Thanks, somehow missed that option after the update. All working again.
