### ISSUE TITLE
Incorrect duration on stats card when using history grouping.

### ISSUE THREAD

**Issue by drzoidberg33** [Tautulli/Tautulli#402]
When enabling history grouping it seems when your stats cards use duration it only shows the duration last play.

For example I watched a movie and stopped it half way and then resumed later, now it only shows the duration of the last watch session. Disabling grouping fixes the issue.

**Comment by JonnyWong16** [comment]
For the "Last Watched" card?

**Comment by drzoidberg33** [comment]
Most Watched.

**Comment by JonnyWong16** [comment]
See if it's fixed with 1c539f0.

**Comment by JonnyWong16** [comment]
Fixed in v1.3.0.
