### ISSUE TITLE
PlexPy Notifications - How to make a new line?

### ISSUE THREAD

**Issue by MrFisher1990** [Tautulli/Tautulli#403]
First of all, thanks for PlexPy I enjoy using it almost every day!

But I have a question because I can't seem to get a new line for my notifications. This is handy especially when I have a lot of tags to use in the notification itself.

How do I do this, or is it simply not developed yet?

Thanks in advance,
MrFisher1990

**Comment by JonnyWong16** [comment]
Can you post an example of what your body text looks like right now and what you are trying to achieve?

**Comment by MrFisher1990** [comment]
Right now I use the following example:

Playback Start

{user} ({player}) started playing {title}. <tv>(S{season_num00}E{episode_num00})  - PLOT: {summary}</tv><movie>({year}) - PLOT: {summary}</movie>

It already gets messy like this. What I want to archieve is this (Quick example)
1. User + Title and year or season00
2. Director
3. Actors
4. Plot

And maybe some more technical lines with details for debugging etc. Like Transcode decisions. 

But when I get 1,2,3 and 4 on a seperate line (or know how to archieve this) I might already have the answer I am looking for. The rest is then just a repeat I think.

A line break that's all I need.

If you need more info, just ask me.

Thanks,
MrFisher1990

**Comment by JonnyWong16** [comment]
Line breaks already work in the message body, but are not available in the subject. Just enter them in the textbox.

**Comment by MrFisher1990** [comment]
Thanks, it worked! Strangely I couldn't get it working a few months ago. Is this recently added?

The topic can be closed as my question is answered. Keep up the good work! :-)
