### ISSUE TITLE
Unknown Version Notification Issue

### ISSUE THREAD

**Issue by kaishichan** [Tautulli/Tautulli#405]
Have run the commands located here, updated and old
https://github.com/drzoidberg33/plexpy/issues/368

even with fresh install, stopped the service, ran the updated and old commands still have the notification update error

```
27-Dec-2015 23:34:02 - INFO :: MainThread : Restarting PlexPy with ['C:\_Utilities\Python 2.7.10\pythonw.exe', 'C:\_HomeTheater\5 - PlexPy\PlexPy.py', '--nolaunch']
27-Dec-2015 23:34:03 - INFO :: MainThread : Checking to see if the database has all tables....
27-Dec-2015 23:34:03 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:_HomeTheater\5 - PlexPy
27-Dec-2015 23:34:03 - DEBUG :: MainThread : Command failed: git rev-parse HEAD
27-Dec-2015 23:34:03 - ERROR :: MainThread : Couldn't find latest installed version.
27-Dec-2015 23:34:03 - ERROR :: MainThread : Output doesn't look like a hash, not using it
27-Dec-2015 23:34:03 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:_HomeTheater\5 - PlexPy
27-Dec-2015 23:34:03 - DEBUG :: MainThread : Command failed: git rev-parse --abbrev-ref HEAD
27-Dec-2015 23:34:03 - ERROR :: MainThread : Could not retrieve branch name from git. Falling back to master
27-Dec-2015 23:34:03 - INFO :: MainThread : Retrieving latest version information from GitHub
27-Dec-2015 23:34:03 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
27-Dec-2015 23:34:04 - DEBUG :: MainThread : Latest version is 9409303f249e8ca854cba9362c2f8a2a9a51d0b7
27-Dec-2015 23:34:04 - INFO :: MainThread : You are running an unknown version of PlexPy. Run the updater to identify your version
```

After that i figured out that git wasnt added to my path so it couldnt run git commands at all from cmd
After adding it to path and restarted computer, i ran the commands and it was pulling proper values

```
C:_HomeTheater\5 - PlexPy>git rev-parse --abbrev-ref HEAD
master

C:_HomeTheater\5 - PlexPy>git rev-parse HEAD
9409303f249e8ca854cba9362c2f8a2a9a51d0b7
```

not sure why plexpy running it in "shell" commands are failing

possible seperate issue saw this in logs too

```
27-Dec-2015 23:57:22 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
File "C:_HomeTheater\5 - PlexPy\PlexPy.py", line 232, in <module>
main()
File "C:_HomeTheater\5 - PlexPy\PlexPy.py", line 215, in main
time.sleep(1)
IOError: [Errno 4] Interrupted function call
```

**Comment by JonnyWong16** [comment]
See http://forums.plex.tv/discussion/comment/1091522/#Comment_1091522

The second error is most likely from shutting down PlexPy unexpectedly.

**Comment by kaishichan** [comment]
should i remove what i added to the path of my enviromental variables?

**Comment by JonnyWong16** [comment]
Not sure if it's necessary, but I'm inclined to say yes. The Git installer will add it back for you anyways.

**Comment by kaishichan** [comment]
unfortunately still the same in the logs

**Comment by kaishichan** [comment]
Issue solved: seems to be an issue with NSSM running plex.py as a service, elevated privilege might not apply to git commands from there on version check.

ran plex.py seperately instead of starting/stopping service in services.msc and was able to get version properly

thanks guys! will leave a note if i ever figure out nssm issue
