### ISSUE TITLE
[Bug] PlexPy cannot show running sessions if device has special characters

### ISSUE THREAD

**Issue by yoyostile** [Tautulli/Tautulli#406]
Hey,

there seems to be some kind of parsing error while fetching running session from plex server.
I do have a client whose device is called "Matzes wei�es iPhone". PlexPy cannot fetch sessions because of the special char:

> Error parsing XML. not well-formed (invalid token): line 172, column 158
> Unable to parse XML for get_sessions.

Is there anything we can do about this, or is this some kind of charset problem within Plex Server itself?

Best,
Johannes

**Comment by Hellowlol** [comment]
Its a bug in plex i think.

**Comment by JonnyWong16** [comment]
See #212.

**Comment by yoyostile** [comment]
Ah, thanks. I guess we can close this issue.
