### ISSUE TITLE
Features/Merge?  Super App!!! :)

### ISSUE THREAD

**Issue by causefx** [Tautulli/Tautulli#407]
@drzoidberg33 ,

I came across this guys script:

https://forums.plex.tv/discussion/156041/plexsentry-20151218-update/p1

WOW!  this would jump the functionality of PlexPy 10 fold if you could incorporate some of these features such as setting stream limits to users and being able kill off stream in PlexPy.... check it out when you have some free time :)

thank you for all you do!

**Comment by JonnyWong16** [comment]
Yes, we are aware of PlexSentry (and PlexEmail, PlexRequests, etc)

**Comment by causefx** [comment]
oh, sorry about that.  Thank you replying.

**Comment by roelbeun** [comment]
Would be awesome to manipulate streams. E.G. Stopping a stream or enable/disable users to transcode.

**Comment by TATUMTOT** [comment]
Would like to see this too. Thanks Everyone.
