### ISSUE TITLE
Add "Watch Statistics Last 30 days" to notifications

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#408]
Would be great to send out a notification (e.g. Telegram bot) with the most popular TV shows from the last 30 days. The period of sending this should be adjustable e.g. daily at 20:00h/weekly on sundays etc.

Let me hear your thoughts :)

**Comment by Hellowlol** [comment]
Imo this is something that should be scripted. Its gonna be a pain to manage this. Are you asking for a "report" xx in the last y days where you can choose one of the notifiers?

**Comment by roelbeun** [comment]
Yeah, basically notifying the lists on the home page: "Watch Statistics Last 30 days" but then on a daily or weekly basis.

**Comment by neebski** [comment]
+1, this would be nice. Especially with the new Facebook notification agent. Inform users on Facebook what this week's most watched content was. Think it would be cool!

Thanks
