### ISSUE TITLE
Unable to open Plex Log file

### ISSUE THREAD

**Issue by BenHornerTech** [Tautulli/Tautulli#409]
Hi,

I am running PlexPy on a Windows machine (192.168.0.100) and Plex is running on my QNAP (192.168.0.111).  I have created a symlink to my Plex Server logs directory in /share/Public/PlexLogs, but I get the error below when I try and view the Plex Server logs via PlexPy:

Unable to open Plex Log file. [Errno 22] invalid mode ('r') or filename: '\\192.168.0.111\Public\PlexLogs\Logs\Plex Media Server.log'

I also get the below if I try and view user stats:

"Unable to retrieve data from database. Please check your settings."

It does seem odd that the error is adding in extra slashes to the path.  The path I have entered into the PlexPy settings is: \192.168.0.111\Public\PlexLogs\Logs

Any ideas?  Thanks in advance

**Comment by JonnyWong16** [comment]
Try `\\192.168.0.111\Public\PlexLogs\Logs` in the PlexPy settings. The double backslash is for a network location. 

The `Unable to retrieve data from database. Please check your settings.` message usually indicates no data in the database.

**Comment by Dustjunky** [comment]
Apologies, that was a copy and paste error on my part.  I do have 2 slashes at the start of the path to my logs file: \\192.168.0.111\Public\PlexLogs\Logs

**Comment by BenHornerTech** [comment]
Ah - just noticed, when I paste the error and path into this the slashes are getting taken out.  Correct pasting below:

Path in settings: `\\192.168.0.111\Public\PlexLogs\Logs`
Error: `Unable to open Plex Log file. [Errno 22] invalid mode ('r') or filename: '\\\\192.168.0.111\\Public\\PlexLogs\\Logs\\Plex Media Server.log'`

**Comment by JonnyWong16** [comment]
Can you access `\\192.168.0.111\Public\PlexLogs\Logs` in Windows explorer?

**Comment by BenHornerTech** [comment]
Sorted it - credentials on Windows were not using the same password as on the QNAP.  Once i set the password in Windows to match the QNAP user password everything kicked into gear.  Thanks.
