### ISSUE TITLE
Bug - Unable to parse custom notification body. Using default.

### ISSUE THREAD

**Issue by kaiguy** [Tautulli/Tautulli#41]
I've noticed that for one particular shared user with one particular device (iPad), I get a different notification style than what I have set.

I decided to investigate and saw this in the console log:

`03-Aug-2015 15:34:14 - ERROR :: Thread-132 : PlexPy Notifier :: Unable to parse custom notification body. Using default.`

It will show the default only for that one user/device combo, regardless of whether its a movie or TV show. With other devices, the notification is displayed as it should.  Here is what I have set for the notification:

`{user} watching Plex - {transcode_decision}`
`{title} <movie>({year})</movie><tv>{season_num}x{episode_num}</tv> [{progress} mins in, {progress_percent}%] on {player}`

I think there must be some problem with it displaying either the progress, progress_percent, or player with that particular user, as the subject notification is still using my custom one.   Everything does seem to be populating as expected in the history section within PlexPy.

**Comment by drzoidberg33** [comment]
Thanks for the report. Do you by any chance have some more info regarding the user? I would be good to know the player name and username.

**Comment by kaiguy** [comment]
I do, but I'd rather not provide it publicly.  I will PM you within the Plex forums.

**Comment by drzoidberg33** [comment]
Not a problem, thanks.

**Comment by drzoidberg33** [comment]
Please update to the latest commit. I have added clearer exceptions for when a parameter cannot be parsed. This should help us pin point the field causing issues.

**Comment by kaiguy** [comment]
Ok, will do.  

Changing the notification from player to platform has the notification coming through fine, so I think that may have been the sticking point.  I'll change it back though with the new commit and see what happens.

**Comment by kaiguy** [comment]
So switched back and it seems that "player" is causing the issue here.  Not too sure why, since I believe player is still part of the default notification.  I got this in the console log:

```
04-Aug-2015 18:33:08 - DEBUG :: Thread-14 : PlexPy Monitor :: Removing sessionKey 15 ratingKey 11325 from session queue
04-Aug-2015 18:33:08 - DEBUG :: Thread-14 : PlexPy Monitor :: Fetching metadata for item ratingKey 11325
04-Aug-2015 18:34:08 - ERROR :: Thread-30 : PlexPy Notifier :: Unable to parse custom notification body. Using fallback.
04-Aug-2015 18:34:09 - INFO :: Thread-30 : Pushover notifications sent.
04-Aug-2015 18:34:10 - INFO :: Thread-31 : Pushover notifications sent.
04-Aug-2015 18:39:08 - DEBUG :: Thread-17 : PlexPy Monitor :: Removing sessionKey 17 ratingKey 11465 from session queue
04-Aug-2015 18:39:08 - DEBUG :: Thread-17 : PlexPy Monitor :: Fetching metadata for item ratingKey 11465
04-Aug-2015 18:40:08 - ERROR :: Thread-34 : PlexPy Notifier :: Unable to parse custom notification body. Using fallback.
04-Aug-2015 18:40:08 - INFO :: Thread-34 : Pushover notifications sent.
```

So strange!  The problem "player" has an apostrophe in it.  I wonder if PlexPy doesn't like apostrophe's when using the media type parameters (tv, movie).

**Comment by drzoidberg33** [comment]
Thanks, that actually helps. I just have to narrow it down further now.

Will get back to you on this.

**Comment by drzoidberg33** [comment]
I tracked down this bug to a unicode issue. v1.1.7 fixes this issue.
