### ISSUE TITLE
[ISSUE] DataTables warning: table id=history_table/id=users_list_table (Refresh/reorder didn't work)

### ISSUE THREAD

**Issue by evenwebb** [Tautulli/Tautulli#412]
Hey everyone.

Long time user and loving the software. Having a problem since removing two entries from the history today now every time I enter the user tab I get the following error:

DataTables warning: table id=users_list_table - Unable to execute database query.
DataTables warning: table id=users_list_table - Requested unknown parameter 'user_thumb' for row 0. For more information about this error, please see http://datatables.net/tn/4

And this on the history tab:

DataTables warning: table id=history_table - Unable to execute database query.
DataTables warning: table id=history_table - Requested unknown parameter 'date' for row 0. For more information about this error, please see http://datatables.net/tn/4

All the other graphs work fine. I have tried refreshing and clicking one of the headers after. Really don't want to loose a years worth of stats. Could anyone help me with this please? :)

Thank you in advance and happy holidays.

**Comment by JonnyWong16** [comment]
You deleted entries from the history table using the delete feature? Are there any other errors or warnings in the logs?

**Comment by evenwebb** [comment]
There was an invalid entry in the history (TV Show that I never watched), so I deleted it thats when the problems started. Maybe the server hung when it was deleting it?

The users tab now works, but the history and log tabs dont. I have put some screenshots here:

http://imgur.com/a/xDtyF

Thank you for the reply :)

**Comment by JonnyWong16** [comment]
Are there any errors or warnings in the logs?

**Comment by evenwebb** [comment]
2016-01-02 22:07:00 WARNING Unable to execute database query for get_history.

**Comment by JonnyWong16** [comment]
I think something might have gone wrong with your database. Can you PM me your `plexpy.db` file on the [forum](http://forums.plex.tv/profile/JonnyWong16) and I'll take a look?

**Comment by JonnyWong16** [comment]
Update:
- Database got corrupted.
- Fixed by manually deleting corrupted entries using SQLite browser.
- Not sure how it got corrupted.

**Comment by evenwebb** [comment]
Server hung during database write causing corruption.

All fixed. Thanks for the support. Will backup the DB from now on.
