### ISSUE TITLE
Feature Request: Send one-off custom messages to notification agents

### ISSUE THREAD

**Issue by krohrsb** [Tautulli/Tautulli#413]
I love all the notification abilities with PlexPy. However it may be useful to allow sending custom one off messages through the user interface.

I realize there is plex server up/down notifications. But what if I wish to send something specific? Such as   notifying a telegram chat about maintenance or server issues, or general broadcast type messages?

I envisioned it as simply a Text Box in the UI that i can type in whatever and hit "send" to send it to notification agents that enable this 'custom message' type notification.

If it's out of scope or too crazy feel free to say so! Thanks.

**Comment by Hellowlol** [comment]
Dunno about a text field, but i intend to add a notifications to the api :)

**Comment by JonnyWong16** [comment]
I was thinking of adding a "Test notification" button to each of the agents. I could possibly just have a custom textbox for the "Test" notification.

**Comment by krohrsb** [comment]
Yeah that would work for my current needs I believe. I just need to provide custom text on demand occasionally

**Comment by JonnyWong16** [comment]
Added in v1.3.0.
