### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by Symbiot78** [Tautulli/Tautulli#415]
hi

when launching plexpy I get:

400 Bad Request

Illegal cookie name snatched_view2

Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 635, in respond
    self.process_headers()
  File "lib/cherrypy/_cprequest.py", line 737, in process_headers
    raise cherrypy.HTTPError(400, msg)
HTTPError: (400, 'Illegal cookie name snatched_view2')

I am using Python 2.7.3 on deb wheezy

**Comment by JonnyWong16** [comment]
Try upgrading to Python 2.7.11.

**Comment by Symbiot78** [comment]
I tried on another system with python 2.7.9 and it worked there..
