### ISSUE TITLE
No email notifications

### ISSUE THREAD

**Issue by hstorey219** [Tautulli/Tautulli#416]
Hi,

I tired 2 different smtp accounts and can not figure out what is wrong with receiving notifications when Plex server is down etc.

Has anyone else got email notifications to work

**Comment by JonnyWong16** [comment]
Did you wait 3x the monitoring interval for the Plex server down notification? PlexPy waits for three failed ping before sending the notification.

**Comment by hstorey219** [comment]
Hi

Yes, had Plex Server turn off for several minutes

I don’t see where PlexPy is calling email to send in the Python window

**Comment by hstorey219** [comment]
Hi Jonny,

yes, waited several minutes, I also noticed in the Python windows, no commands to send emal

**Comment by JonnyWong16** [comment]
Did you check the triggers for the email notification agent (bell icon on the left)?

**Comment by hstorey219** [comment]
Hi Jonny,

What a dumb end user :) I didn't even noticed that bell, Thank you!!!
