### ISSUE TITLE
[Feature Request] EventGhost Notification Agent

### ISSUE THREAD

**Issue by syndac** [Tautulli/Tautulli#417]
Any chance you could add an EventGhost notification agent? I'm not familiar enough with programming to do it myself, but it should be fairly easy. To create an EventGhost notification, you just open Eventghost.exe via command line with the argument:

-e PAYLOAD

where PAYLOAD is whatever you want the even to be, so:

Eventghost.exe -e "David Paused Homeland"

would show up, in the EventGhost log as:

Main.David Paused Homeland

**Comment by Hellowlol** [comment]
https://github.com/drzoidberg33/plexpy/pull/373

**Comment by syndac** [comment]
Don't worry about working on this one. I'm teaching myself Python (which I was going to do anyway) and working on it. I'll submit a pull request once I get it working. I may need the code fine-tuned once it's done, though.

**Comment by JonnyWong16** [comment]
It seems like this can already be achieved very easily with the new script notification agent that @Hellowlol mentioned above.

**Comment by syndac** [comment]
@JonnyWong16 
Ah, yes. That will probably work. Having a little trouble with my script (very much a programming novice). Hope you don't mind me asking, but I'm having trouble getting my script to "import" the message and subject variables.

I get the error:

```
File "H:\Program Files (x86)\PlexPy\custom_scripts\EventghostNotify.py", line 3, in 
message = body 
NameError: name 'body' is not defined
```

Here's my code:

```
import subprocess

message = body
subject = subject

subprocess.call(["H:\Program Files (x86)\EventGhost\Eventghost.exe", '-e', subject + ':' + message], shell=True)
```

I know I'm missing something simple, but don't know what it is.

Also, I could still write the Eventghost agent...I'm fairly close. Would you find it useful at all? I was also thinking of writing one for AutoRemote.

**Comment by JonnyWong16** [comment]
`message = body`
`body` is coming from nowhere. Unless you mean the string `"body"`.

We already have a lot of agents already. The whole point of the script agent was to allow people to write their own scripts to use the less common agents such as EventGhost and AutoRemote.

**Comment by syndac** [comment]
@JonnyWong16 

Thanks. I accidentally copy/pasted the wrong code as I was trying different things.

Should be:

```
import subprocess

subprocess.call(["H:\Program Files (x86)\EventGhost\Eventghost.exe", '-e', subject + ':' + message], shell=True)
```

Still, I can't seem to get it to understand where to get subject and message from.

And no problem with EventGhost and AutoRemote. I understand.

**Comment by JonnyWong16** [comment]
You haven't defined `subject` or `message` yet.

**Comment by Hellowlol** [comment]
You also need to access the args given to the script. See sys.argv
"David Paused Homeland"
In the script arguments inside plexpy: {user} {action} {title}

**Comment by JonnyWong16** [comment]
Side note for @Hellowlol 
Add `.exe` to possible script extensions?

**Comment by Hellowlol** [comment]
Yeah

**Comment by JonnyWong16** [comment]
@Hellowlol 
If the argument is `{user} {action} {title}`, it's going to come out as `"David" "paused" "Homeland"`

We should revisit the quoting to allow the user someway to group tags, such as `"{user} {action} {title}"` or `{{user} {action} {title}}` as an argument for `David paused Homeland`.

**Comment by Hellowlol** [comment]
@JonnyWong16 Yeah, that is the wanted behaviour. If the user want anything else he would have to fix it in the script.

**Comment by syndac** [comment]
@Hellowlol 

Thanks for your help thus far. I'm sure you've got better things to do than answer my very inane questions. I still seem to be having problems getting the subject and message to transfer over. Here is my current code:

```
import subprocess
import sys

subject = sys.argv[1]
message = sys.argv[2]

subprocess.call(["H:\Program Files (x86)\EventGhost\Eventghost.exe", '-e', subject + ':' + message], shell=True)
```

In the Scripts setting modal, if I enter in the args, {action} {show_name}, I get the EventGhost event: Main.{action}:{show_name}, which is actually "action" and "show_name", not something like Paused:Suits

If I hit save and then re-open the modal, my args are no longer there (maybe intentional?). Now, if I pause and play a show, I get the error:

```
File "H:\Program Files (x86)\PlexPy\custom_scripts\EventghostNotify.py", line 4, in 
subject = sys.argv[1] 
IndexError: list index out of range
```

I know this should be really simple, but after reading up a lot on sys.argv, I'm still pretty lost. Mind helping me figure out how to call the right Subject and Message variables?

**Comment by JonnyWong16** [comment]
Can you post the PlexPy logs?
There should be some debug lines about running scripts.

The arguments text box in the modal is just for testing. The actual arguments used when you play/pause/stop/etc. is on the Notifications settings page.

**Comment by syndac** [comment]
@JonnyWong16 

I restarted, cleared the logs, and here's from startup to hitting pause on Dexter:

```
14-Jan-2016 14:10:08 - INFO    :: MainThread : Users list refreshed.
14-Jan-2016 14:10:08 - INFO    :: MainThread : Starting PlexPy web server on http://0.0.0.0:8181/
14-Jan-2016 14:10:08 - INFO    :: MainThread : Web server authentication is enabled, username is 'syndac'
14-Jan-2016 14:10:09 - INFO    :: MainThread : Scheduled background task: Refresh Plex Server URLs
14-Jan-2016 14:10:09 - INFO    :: MainThread : Scheduled background task: Refresh Plex Server Name
14-Jan-2016 14:10:09 - INFO    :: MainThread : Scheduled background task: Check for active sessions
14-Jan-2016 14:10:09 - INFO    :: MainThread : Scheduled background task: Refresh users list
14-Jan-2016 14:11:10 - DEBUG   :: Thread-20 : PlexPy Notifiers :: Trying to run notify script, subject: PlexPy (D&M), message: syndac (Plex Web (Chrome)) has paused Dexter - The Damage a Man Can Do., action: pause, script_args: []
14-Jan-2016 14:11:10 - DEBUG   :: Thread-20 : PlexPy Notifiers :: Full script is: python H:\Program Files (x86)\PlexPy\custom_scripts\EventghostNotify.py
14-Jan-2016 14:11:10 - DEBUG   :: Thread-20 : PlexPy Notifiers :: Script returned pydev debugger: process 6576 is connecting



Traceback (most recent call last):

  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.1\helpers\pydev\pydevd.py", line 2403, in <module>

    globals = debugger.run(setup['file'], None, None, is_module)

  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.1\helpers\pydev\pydevd.py", line 1794, in run

    launch(file, globals, locals)  # execute the script

  File "H:\Program Files (x86)\PlexPy\custom_scripts\EventghostNotify.py", line 4, in <module>

    subject = sys.argv[1]

IndexError: list index out of range
14-Jan-2016 14:11:10 - INFO    :: Thread-20 : PlexPy Notifiers :: Script notification sent.
```

Note that I'm running this via PyCharm

**Comment by JonnyWong16** [comment]
Like I said you need to specify the arguments on the Notifications settings page.

**Comment by syndac** [comment]
@JonnyWong16 

Oh my gosh. How did I not see that? I am so sorry for wasting your time. Thank you to both you and @Hellowlol for helping me out with this.

And I guess I WAS using sys.argv appropriately. Thanks for pointing me in the right direction!

**Comment by JonnyWong16** [comment]
But is it still showing "action: show_name" instead of "paused: Suits"?

Because that would be a bug we need to fix.

**Comment by syndac** [comment]
It is now showing as "paused":"Suits"

Too many quotes, but I think I can remove them with: 

```
subject = subject[1:-1]
```

Right? trying it now...

**Comment by syndac** [comment]
Yep. That works. Thanks again to both of you!

**Comment by Hellowlol** [comment]
@JonnyWong16 Thats a regex fix, ill leave that to you :)
