### ISSUE TITLE
[Request] Import from PlexNotify

### ISSUE THREAD

**Issue by Mirabis** [Tautulli/Tautulli#42]
I happen to have over 9 months of historical data in the sqlite db belonging to plexNotify, which I couldn't port to plexWatch before.

Would it be possible to allow importing from plexNotify ? It would do my graphs very good hehe

**Comment by drzoidberg33** [comment]
Could you share the database with me? I don't have plexNotify (or a Windows machine) so it's a mission to test myself.

You can share to my email address: timvdwest (at) gmail (d0t) com

**Comment by Mirabis** [comment]
I've sent you the SQLite , .csv, .xls database by e-mail.

**Comment by drzoidberg33** [comment]
Thanks. Took a quick look and doesn't look like it's worth it. It's missing a bunch of important fields so I wouldn't want to spend my time trying to create an import tool that has to rebuild everything.

If you want to take a crack at it feel free :smile:

**Comment by Mirabis** [comment]
damn thats a bummer... I once managed to import it into plexWatch but somehow the unique key generation was .. wel... not working.

which important fields were missing?

**Comment by Mirabis** [comment]
Oh and the .csv/xlsx files were me trying to convert it to plexWatch , it might not be 100% equal to the schema in the .db file attached.

**Comment by drzoidberg33** [comment]
Things like the summary, content rating, directors, writers, etc. Basically a lot of the metadata stuff. It's possible to rebuild that from Plex again but if the media no longer exists on the server it won't help.

If you want to take a deeper look at what's required, take a look at the fields I'm using here: https://github.com/drzoidberg33/plexpy/blob/master/plexpy/__init__.py#L354 (the three tables are session_history, session_history_media_info and session_history_metadata).

**Comment by Mirabis** [comment]
Ah okay will do in a few weeks :) still have the same media and server

**Comment by drzoidberg33** [comment]
I'm closing this as I won't be working on this.
