### ISSUE TITLE
Telegram "added" notification not working.

### ISSUE THREAD

**Issue by nexitem** [Tautulli/Tautulli#424]
It seems that the "Notify on recently added" function isn't working correctly or at all. I will help reproduce the bug if needed.

Other Notification options are working fine when using telegram.

**Comment by JonnyWong16** [comment]
Any errors or warnings in the logs?
Have you checked all the toggles?
- Notifications > Enable Recently Added Notifications
- Notification Agents > Telegram > Bell icon

Do you have "Group notifications for recently added TV Shows or Music" checked or unchecked?
Have you tried recently added notifications with a different notification agent?

**Comment by nexitem** [comment]
Okay I have enabled the function under notifications... For some reason I must have overseen it on the desktop version. Instantly found it on my mobile browser...

I had and have grouped notifications enabled.

Testing if it functions now.

**Comment by JonnyWong16** [comment]
Assuming this is resolved.

Reopen if it is still an issue.
