### ISSUE TITLE
[Feature Request] Weekly Updates

### ISSUE THREAD

**Issue by grokdesigns** [Tautulli/Tautulli#425]
It would be awesome if you could email users with whom your library is shared (username and email can be pulled from pulled from https://plex.tv/pms/friends/all?X-Plex-Token="SERVERTOKEN"). Similar to the project here: https://github.com/jakewaldron/PlexEmail, but built in to PlexPy. The way I envision it is a page where the users are enumerated from the previously referenced friends page and you can set up a daily, weekly, monthly, etc. email (including SMTP config) with the latest media added to the server.

**Comment by drzoidberg33** [comment]
Duplicate. Refer to #16 and #407.
