### ISSUE TITLE
Starting/stopping and episode counts as multiple views

### ISSUE THREAD

**Issue by jonkit** [Tautulli/Tautulli#426]
New to PlexPy, not new to Plex, and I apologize if this is how PlexPy is supposed to work.

If I stop watching an episode and then start again, the play counts on the PlexPy Home screen show multiple viewings for a single episode. 

I've attached a screenshot of my history and home screens. In the history screen you see that only 3 episodes were watched but there were 8 entries because I stopped/started. The Home screen shows the count of 8 for the show that should be 3. 

![image](https://cloud.githubusercontent.com/assets/10313334/12131679/e2f55662-b3e2-11e5-82ae-73278f49ea4a.png)
![image](https://cloud.githubusercontent.com/assets/10313334/12131680/e304d1be-b3e2-11e5-810c-b5aa5fb27fa2.png)

**Comment by JonnyWong16** [comment]
Enable "Group Table and Watch Statistics History" in the settings.

**Comment by jonkit** [comment]
That worked. Thank you!
