### ISSUE TITLE
Vizio app shows up as Opera

### ISSUE THREAD

**Issue by jscottelblein** [Tautulli/Tautulli#427]
Just thought I'd add an FYI in case anyone isn't aware (and cares to have PlexPy be a bit more accurate in reporting), Under Platform/Player for the Vizio Smart TV Plex app, it shows Opera, and/or the opera Icon.

[i.e. Screenshot](http://i.imgur.com/tnNvc0v.png)

Not a huge issue, but would be nice to have it be more accurate.

**Comment by drzoidberg33** [comment]
What does it shows as under the Devices tab in Plex Web?

**Comment by unkindlykiller** [comment]
not op..this is what it shows in mine http://i.imgur.com/6wVmzdG.png its the samething thats in plexpy

**Comment by JonnyWong16** [comment]
If that's how it shows up on Plex, then that's how it will show up on PlexPy.  (Unless we decide to manually add our own icon.)

**Comment by jscottelblein** [comment]
Good point, I hadn't checked Plex Devices before posting. Mine does the same as well. Either way, like I mentioned, not a huge deal. =)

http://i.imgur.com/PMnMY5l.png
