### ISSUE TITLE
Unable to parse XML for get_recently_added

### ISSUE THREAD

**Issue by dannyhanes** [Tautulli/Tautulli#428]
I have the full path listed for the logs location. On the home screen it wont show any recently added items. When I went to the logs it said "Unable to parse XML for get_recently_added"

**Comment by JonnyWong16** [comment]
Can you access this page?

```
http://<pms-ip>:32400/library/recentlyAdded?X-Plex-Token=<your-plex-token>
```

**Comment by dannyhanes** [comment]
It pulls up a very long XML file.

**Comment by dannyhanes** [comment]
I just looked at the logs again. Got this as well: "Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=6 with error timed out"

**Comment by JonnyWong16** [comment]
Are those the only errors or warnings in the logs?
PlexPy might be having errors connecting to your Plex server.
Do you have SSL set to "preferred" or "required"?

**Comment by dannyhanes** [comment]
I have tried with both Require SSL and also leaving the box unchecked. 

2016-01-06 13:59:51 WARNING Unable to retrieve data.
2016-01-06 13:59:51 WARNING Unable to parse XML for get_recently_added.
2016-01-06 13:59:51 WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=6 with error ('The read operation timed out',)
2016-01-06 13:59:46 WARNING Unable to parse XML for get_recently_added.
2016-01-06 13:59:46 WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=10 with error timed out
2016-01-06 13:59:38 INFO    Re-scheduled background task: Check for active sessions
2016-01-06 13:59:38 INFO    Re-scheduled background task: Check for server response
2016-01-06 13:59:38 INFO    Re-scheduled background task: Check for recently added items
2016-01-06 13:59:38 INFO    Server URL retrieved.

**Comment by JonnyWong16** [comment]
Is your server local server or remote? And using the corresponding "Remote Server" checkbox in the PlexPy settings?
"Force SSL" checked or unchecked in the PlexPy settings?

**Comment by Arcanemagus** [comment]
If your server is taking a long time to generate the list of recently added you will see this. The default timeout is [10 seconds](https://github.com/drzoidberg33/plexpy/blob/v1.2.16/plexpy/http_handler.py#L59), if your server is heavily loaded and you recently added a lot of new items it can easily take longer than that to generate the list.

**Comment by JonnyWong16** [comment]
We are already limiting the number of items fetched (`X-Plex-Container-Size`) to ~10 so it shouldn't take more than 10 seconds unless your server is REALLY loaded.

**Comment by dannyhanes** [comment]
PlexPy is running on the same box as the Plex Server. I have tried both Force SSL as checked and unchecked. I have not tried the remote server checkbox. 
Define....really loaded. lol

**Comment by JonnyWong16** [comment]
Leave "Remote server" unchecked then.

Everything else on PlexPy works fine?

**Comment by dannyhanes** [comment]
Yeah, remote server has been unchecked. And yup, right now my kids are streaming from two different rooms and it shows that along with the history from the day. The ONLY thing that doesn't work is recently added. Which wouldn't be a big deal, but I REALLY want notifications when something new is added. haha

**Comment by Arcanemagus** [comment]
If you open the page in your browser like @JonnyWong16 suggested, and then open Developer Tools (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>), switch to the network tab, and then reload the page you should get a time on how long it took your browser to load the data.

If that is longer than 10 seconds you are simply hitting the timeout, if less than 10 seconds then you have a configuration issue.

**Comment by dannyhanes** [comment]
13.12 seconds. lol - Anyway to adjust the timeout?

**Comment by Arcanemagus** [comment]
Manually edit the file I linked above, there are 3 places where it is listed as `timeout=10`.

**Comment by JonnyWong16** [comment]
Note: you won't be able to apply the updates if you edit the files, unless you change it back first.

**Comment by dannyhanes** [comment]
So if there is a new software update, I need to change it back to 10, then run the update, then change it back to whatever I set it to?

**Comment by Arcanemagus** [comment]
Correct

**Comment by Arcanemagus** [comment]
(Specifically the output of `git status` should show no changed files before attempting to update)

**Comment by dannyhanes** [comment]
Alright. For anyone else who may find this in the future... 

I went into settings and shutdown PlexPy
Navigated to <plexply folder>/plexpy and opened http_handler.py with notepad
Found and replaced "timeout=10" with "timeout=20"
Saved the closed notepad. 
Restarted Plexpy. 

It looks like it is loading it my recently added now. 

Don't suppose you could just change it to 20 so I can run updates in the future ;-) lol

**Comment by JonnyWong16** [comment]
I would suggest trying to figure out why it takes so long to get the data when it's on the same machine.

**Comment by dannyhanes** [comment]
That would be beyond the scope of my abilities. 

My only thought is that I had just rebuilt my Plex server and last night added ALL of my media back to it. The XML file isn't listing everything...but it is still showing things from my rebuild. 

Any suggestions on that front? Or would, over time, the list generate faster as those items get phased out?

**Comment by JonnyWong16** [comment]
Then possibly "REALLY loaded" could mean pulling a lot of metadata. Are you also generating bif thumbnails? That could be another reason.

I'm just tossing ideas out there. I really don't know.

**Comment by dannyhanes** [comment]
Yeah. Generating / Streaming / Just added over 6k of items last night. I'll give it a few days to finish up all its background stuff and see if it connects faster.

**Comment by Arcanemagus** [comment]
That's essentially what I had to do when I just recently rebuilt my server, just wait a while for it to settle down a bit.

You could try running the "Optimize Database" task within Plex, but be warned that it's possible that will lock up Plex, and since it is heavily modifying the DB I'd suggest getting a backup before attempting that manually. (Just schedule it as maintenance and let that take care of it.)

**Comment by JonnyWong16** [comment]
Timeout has been increased to 20s.

Reopen issue if it is still an problem.
