### ISSUE TITLE
Is there a way to prevent duplicate notifications ?

### ISSUE THREAD

**Issue by davis78** [Tautulli/Tautulli#429]
On my PlexPy i have 'Playback Start' notification enabled. I've noticed that if a video is started, stopped, and then started again, i will get the playback started notification twice. Is there any way to prevent this sequential repetition of the same notification in PlexPy ? Couldn't see any way to do this in settings, nor find any similar issues related to this. Thanx. 

-DaViS

**Comment by JonnyWong16** [comment]
No, there isn't any way to prevent this at the moment.

**Comment by davis78** [comment]
Sounds good, thanx.
