### ISSUE TITLE
pms_identifier not updated on server re-install

### ISSUE THREAD

**Issue by jabbera** [Tautulli/Tautulli#435]
In the event of a re-installation of plex with plex home on the same server with the same friendly name: pms_identifier is not correctly updated when the token is re-fetched. This causes plexpy to not connect and fail with errors that imply having SSL set to required is causing an issue. It took me a long time to figure out that the pms_identifier was set to the value of the previous server installation, not the newly generated one with the new installation.

Workaround: go to /servers and manually extract the machine identifier and manual edit the config file.

Steps to reproduce (I think):
Install plex on server and give friendly name : "A"
Enable Plex Home
Require SSL
install and configure plexpy with plex.tv authentication.
make sure it works.
Stop plex on the plex server.
Delete installation.
Reinstall following steps 1-3.
Request new token in plexpy.
Restart plexpy
Go to home page in plexpy
Notice error saying it cannot communicate with server.
Pulling the machineIdentifier from /server from the plex server and putting it in pms_identifier\restarting plexpy solves the issue.

**Comment by JonnyWong16** [comment]
Should be fixed with 754df5bea7425c39b91d4a34bbeabdf25bb564cf

**Comment by JonnyWong16** [comment]
Fixed in v1.3.0.
