### ISSUE TITLE
[Feature Request] Multiple Notification Agents

### ISSUE THREAD

**Issue by vortexrap** [Tautulli/Tautulli#438]
Sonarr allows you to have multiple connections (Pushbullet, Growl, etc.) which allows you to specify for each connection what you would like to pass in the notification.

In my situation, it allows me to push all notifications (on grab, on download) to my personal account, then just on download to my pushbullet channel (which has my Plex Server users).

Currently, PlexPy only allows 1 connection setting.

I'm envisioning being able to notify users if Plex Server Remote Access is down, and when it is back up using PlexPy or completely migrating over to PlexPy for all media added notifications since it seems like you all do a much better job at updating and adding features faster than sonarr.

Thanks!

**Comment by JonnyWong16** [comment]
I'm not quite following what you mean.

Isn't this just all the individual toggles under the bell icon on the Notification Agents settings page?

**Comment by vortexrap** [comment]
To clarify, yes. You can toggle one instance of a Pushbullet agent, but you cannot set up multiple Pushbullet agents with different settings. 

If you have 2 Pushbullet accounts that you want to push notifications to you would not be able to do this via the current setup since you can only link 1 API Key.

Look at sonarr's implementation as reference.

**Comment by JonnyWong16** [comment]
Got it.

**Comment by elRadix** [comment]
the same goes for Telegram, having multiple channels would be help full to have multiple agents as well

ie. 
Channel 1 = internal for start/stop for myself
Channel 2 = newly added/plex server status for a private group

**Comment by pax0707** [comment]
Would love this for telegram.

**Comment by rjorgenson** [comment]
Would also love to have this feature in plexpy, have a couple of slack instances that I would like to send notifications to.

**Comment by Hellowlol** [comment]
Until somebody has time to work on this it would be easy to do this via the script notifier.

**Comment by elRadix** [comment]
i'm using a second instance of plexpy to solve this temporarily 

Others, pls cast your vote here ;-)
http://feathub.com/drzoidberg33/plexpy/+40

**Comment by plittlefield** [comment]
Hello, I am trying to have multiple notifications which include posters.

I have a Pushover one and would like an email one.

If I don't have any images, then the email one works as it should.

However, if I have tick Enable Posters in Notifications and created an anonymous Imgur API app with a callback URL of https://dereferer.org/ then the email notification stops.

What have I done wrong?

Paul

**Comment by plittlefield** [comment]
_bump_

**Comment by vortexrap** [comment]
@plittlefield this is a completely different problem than my original issue, as it doesn't have to do with multiple notifications from the same provider. please create a new issue.

**Comment by Hellowlol** [comment]
Adding a bug/support question to a feature request is a sure way of not getting a response :D

**Comment by plittlefield** [comment]
Ah, understood. Will do!

**Comment by nate8199** [comment]
I would love to have multiple ways to send alerts to the same provider also

**Comment by mmedic** [comment]
Any plans on implementing this?

**Comment by austinarchibald** [comment]
Casting my support as well for this feature. Have couple users of server that want notifications. E.G. wish I could enter more than one boxcar access token.

**Comment by Banthaf0dder** [comment]
This would be fantastic for Slack so I could have one Slack channel for an activity log for played/watched notifications and another channel for recently added items.

**Comment by simonk83** [comment]
I'd really like this as well.   I'd like TV downloads to go to a sonarr slack channel and Movie downloads to go to a radarr channel, for example.

**Comment by riemers** [comment]
Just to add my voice, using slack with discord webhooks (using /slack) at the end, they work fine but i want to seperate series/movies per channels since series is more spammy then movies.

**Comment by vortexrap** [comment]
please vote here: https://feathub.com/JonnyWong16/plexpy/+40 to show support for this feature.

**Comment by drakonstein** [comment]
It seems like it would be possible to just create a slack1, slack2, slack3, etc in the files in plexpy/{notifiers.py,config.py,webserve.py}.  I'm well over my depth on this one, but I feel like it should be possible to duplicate any existing agent and have multiple of them with their own settings.

I just set up a slack instance for my wife to be able to see plexpy notifications, but alas I can't implement it without disabling the existing one.
