### ISSUE TITLE
Recently Added notification doesn't send custom Subject

### ISSUE THREAD

**Issue by thespaz** [Tautulli/Tautulli#439]
I have the following subject line set for Recently Added...

PlexPy: Added the {meda_type} "{title} (<tv>s{season_num00}e{episode_num00}</tv><movie>{year}</movie>)"

When the notification is sent the Subject shows "PlexPy ({server})", which was the previous subject.  Note that the body of the notification is as follows and works just fine...

Title: {title} (<tv>s{season_num00}e{episode_num00}</tv><movie>{year}</movie>)
Content Rating: {content_rating}
Rating: {rating}
Duration: {duration}

Studio: {studio}
Directors: {directors}
Writers: {writers}
Actors: {actors}
Genres: {genres}

{summary}

I looked at other custom changes to see if something might be affecting the code and didn't see anything.  I checked in /opt/plexpy/config.ini and the following is there...

notify_recently_added_grandparent = 1
notify_recently_added = 1
notify_recently_added_delay = 180
notify_on_created_subject_text = 'PlexPy: Added the {meda_type} "{title} (<tv>s{season_num00}e{episode_num00}</tv><movie>{year}</movie>)"'
notify_on_created_body_text = '''Title: {title} (<tv>s{season_num00}e{episode_num00}</tv><movie>{year}</movie>)^M
Content Rating: {content_rating}^M
Rating: {rating}^M:q
Duration: {duration}^M
^M
Studio: {studio}^M
Directors: {directors}^M
Writers: {writers}^M
Actors: {actors}^M
Genres: {genres}^M
^M
{summary}^M
'''
growl_on_created = 0
boxcar_on_created = 0
pushbullet_on_created = 0
nma_on_created = 0
email_on_created = 1
osx_notify_on_created = 0
pushover_on_created = 1
twitter_on_created = 0
pushalot_on_created = 0
prowl_on_created = 0
plex_on_created = 0
xbmc_on_created = 0
ifttt_on_created = 0
telegram_on_created = 0

So it looks like the gui is updating the config.ini file.  Is that the place plexpy is looking when it sends notifications?

I'm not sure where else to look.

**Comment by JonnyWong16** [comment]
The subject reverts back to `PlexPy ({server})` if it has problems substituting the tags.

Check the logs, it should tell you which tag is causing the problem.

**Comment by thespaz** [comment]
Yea, just forced it to add something and got this...

ERROR   PlexPy Notifier :: Unable to parse field u'meda_type' in notification subject. Using fallback.

**Comment by JonnyWong16** [comment]
You have a typo, you forgot the "i" in "media"
`{media_type}`

**Comment by thespaz** [comment]
yup, just saw that.  :)  Sorry to waste your time.  Ugh.

Fantastic app, you are to be applauded.
