### ISSUE TITLE
Some Notification Parameters are Empty

### ISSUE THREAD

**Issue by m1lkman** [Tautulli/Tautulli#440]
When I try to use some of the extra notification parameters they're coming up as empty or zeros. Below is what I put in for my recently added message body.

{title} - {season_num}x{season_num00} - {episode_name} was recently added to Plex.

This is an example of the notification being sent.

Inside Amy Schumer - 0x00 -  was recently added to Plex.

This is what it should have said

Inside Amy Schumer - 2x03 - A Chick Who Can Hang was recently added to Plex.

Anyone else seeing this or have a solution?

**Comment by JonnyWong16** [comment]
You didn't read the settings...

```
[x] Group notifications for recently added TV Shows or Music

Enable to only get one TV Show or Artist notification for a batch of recently added Episodes or Tracks. Movies are unaffected.
Note: No Season/Episode or Album/Track metadata will be available.
```

**Comment by m1lkman** [comment]
Got it, thanks for the clarification. I missed that. Would be nice to get all this data available for the group notifications in the future. Appreciate all your hard work.

**Comment by JonnyWong16** [comment]
You can't show episode or track info when it's grouped... What would you show?...

**Comment by m1lkman** [comment]
I would be nice to be able to get episode name/number & season. I'm doing this today. Thanks.

{show_name} - {season_num}x{episode_num00} - {episode_name} was recently added to Plex.

**Comment by JonnyWong16** [comment]
Resolved.
