### ISSUE TITLE
Can't update when pulled from github

### ISSUE THREAD

**Issue by bobloadmire** [Tautulli/Tautulli#441]
I just nuked my plexpy install because it woulldn't update. Still won't update now either.

Pulled a fresh copy from GIT using GIT GUI, and started it up, configured everything. It's wants to update since it's first run, so I click the update notification at the bottom right, and it restarts. But after multiple tries, it still hasn't updated and doesn' know what version it is. The only thing I have change din the config is move it from port 8181 to 8182 because of Headphones.

**Comment by JonnyWong16** [comment]
I assume you're on Windows.

Did you make sure you followed this step in the Git installation
- Run the installer, select all the defaults except for the section called "Adjusting your PATH environment" - here select "Use Git from the Windows command prompt"

**Comment by jabbera** [comment]
There is also a github api rate limit that is per ip address. https://developer.github.com/v3/rate_limit/

Unauthenticated requests are capped a 60 per hour per ip address so if you share your IP\you have alot of apps that use the github api\you have 1 bad app that uses all your requests you need to wait for an hour.

**Comment by JonnyWong16** [comment]
This should be resolved with my comment above.

Reopen the issue if it is still a problem.
