### ISSUE TITLE
Data Tables Warning

### ISSUE THREAD

**Issue by pittsmaster** [Tautulli/Tautulli#443]
ajax error in chrome when clicking on history

**Comment by Arcanemagus** [comment]
Do you have a specific error message?

**Comment by pittsmaster** [comment]
![screenshot_2016-01-14-18-54-51](https://cloud.githubusercontent.com/assets/16711524/12344343/f1f033fc-baf0-11e5-865b-c0aefee85a01.png)
It says Ajax erorr and says look at "http://datatables.net/manual/tech-notes/7" for help

Ill get more info shortly

**Comment by pittsmaster** [comment]
I updated with an image of the error.

**Comment by JonnyWong16** [comment]
Check the logs. See if there are any errors or warnings.

**Comment by pittsmaster** [comment]
Don't see anything...does anyone?
![screenshot_2016-01-14-19-19-04](https://cloud.githubusercontent.com/assets/16711524/12344594/c2770382-baf3-11e5-8869-e31655208616.png)

**Comment by JonnyWong16** [comment]
You need to provide more information. We can't help you if all you tell us is there is an error.

Did you update PlexPy recently? Is it a new install? Old install? Was it working properly before? Did you change any settings? Anything happen specifically to cause the error?

**Comment by pittsmaster** [comment]
What about these entries?
![capture](https://cloud.githubusercontent.com/assets/16711524/12346569/66d0aef4-bb0a-11e5-9ce6-9826ac3a47c7.PNG)

I have had this running fine for months. I always updated when prompted. All of a sudden i could not get the history. it was not brought on by an update and i did not change anything.

**Comment by JonnyWong16** [comment]
There could be something wrong with your database then.

**Comment by JonnyWong16** [comment]
PM me your `plexpy.db` file on the [forum](http://forums.plex.tv/profile/JonnyWong16) if this is still a problem, and I'll take a look at it.

**Comment by pittsmaster** [comment]
Actually, my fault for not updating sooner, but a few days after I posted this it magically started working again with no issues. Thank you for the offer to look at my db though. It's awesome that people care about issues for this. Wish I would have waited a little longer to post my issue. I'm sure you have more important things to tend to. Thanks again.

**Comment by JonnyWong16** [comment]
Thanks for the update.

Resolved. Closing issue.
