### ISSUE TITLE
ImportError: No module named plexpy

### ISSUE THREAD

**Issue by Diablosblizz** [Tautulli/Tautulli#445]
Hi,

I'm trying to install a new version of PlexPy on Windows Server 2012 R2 Essentials using Python 2.7.11 and am getting this error:

```
C:\PlexPy>python PlexPy.py
Traceback <most recent call last>:
File "PlexPy.py", line 25, in <module>
   from plexpy import webstart, logger, web_socket
ImportError: no module named plexpy
```

If I double click the PlexPy file, it opens then closes with the same error. Any suggestions?

**Comment by JonnyWong16** [comment]
~~You're missing the `plexpy` folder inside the PlexPy folder. (If that makes any sense).~~

There should be a subfolder named `plexpy` in the same folder as the file `PlexPy.py`.

What install method are you using?

**Comment by Diablosblizz** [comment]
Yeah, that seemed to have been the problem. It had cloned to C:\PlexPy\plexpy (with another folder named plexpy inside). I moved the root folder (C:\PlexPy\plexpy) to just C:\PlexPy which did it.

Thanks!
