### ISSUE TITLE
[Feature Request] Disable notifications for certain users

### ISSUE THREAD

**Issue by popescu2289** [Tautulli/Tautulli#446]
Not a huge deal, just wanted to know if it'd be possible to disable notifications for when the primary user is using PMS. Obviously, if I'm playing something I don't need an email from plexpy telling me about it.

Thx,
~Pops

**Comment by monstar316** [comment]
If you go into the Users tab -> Edit mode, you can click on the bell symbol
to toggle notifications on/off for individual users.

**Comment by popescu2289** [comment]
Awesome thanks
