### ISSUE TITLE
Unable to open Plex Log file

### ISSUE THREAD

**Issue by jonkit** [Tautulli/Tautulli#447]
On OS X using PlexPy Version 1.2.16 and PMS Version 0.9.12.19.

In my PlexPy Settings > Plex Media Server screen I have "~/Library/Logs" (no quotes) in the Logs Folder section. 

If I navigate to that folder in Finder I can see the Plex Media Server.log file.

In the PlexPy Logs screen, under Plex Media Server Logs I see "No log information available. Have you set your logs folder in the settings?" and in the PlexPy Logs screen I see the error message, "Unable to open Plex Log file. [Errno 2] No such file or directory: '~/Library/Logs/Plex Media Server.log'"

**Comment by JonnyWong16** [comment]
http://forums.plex.tv/discussion/comment/977303#Comment_977303

**Comment by jonkit** [comment]
And I thought I tried using the actual path instead of the ~ version... obviously not... and next time I'll try the Plex forums first.

Thank you!

**Comment by JonnyWong16** [comment]
Resolved.
