### ISSUE TITLE
[Feature] estimated completion time

### ISSUE THREAD

**Issue by tylordurton** [Tautulli/Tautulli#448]
Hi guys,

I was just wondering if it would be possible to add the estimated completion time on the now playing activity overview. Basically just calculating the time difference between the remaining time left on the media file against the actual time.

I know I would find this useful
:-)

Kind Regards
Tylor

**Comment by JonnyWong16** [comment]
Really that lazy to do the math yourself? :stuck_out_tongue: 

Time in duration (i.e. finish in 30 mins remaining) or actual time (i.e. finish at 9:24pm)?

**Comment by tylordurton** [comment]
lol, actual time 9:24

:-)

**Comment by JigSawFr** [comment]
:+1: Could be great to see that, as we can plan so much things

**Comment by JonnyWong16** [comment]
Added in v1.3.7.
