### ISSUE TITLE
No history for any user

### ISSUE THREAD

**Issue by rfrowe** [Tautulli/Tautulli#451]
My PlexPy installation was working fine until today I noticed it stopped recording history for one user. I deleted /opt/plexpy and reinstalled and chowned to user plexpy. Whenever I try to view a user's history all I see is "Unable to retrieve data from database. Please check your settings." When I look in the log file, all I see is a very undescriptive:

```
17-Jan-2016 23:37:52 - WARNING :: CP Server Thread-9 : Unable to retrieve data.
17-Jan-2016 23:37:52 - WARNING :: CP Server Thread-2 : Unable to retrieve data.
17-Jan-2016 23:38:10 - WARNING :: CP Server Thread-9 : Unable to retrieve data.
17-Jan-2016 23:38:10 - WARNING :: CP Server Thread-2 : Unable to retrieve data.
```

PlexPy can successfully connect to my Plex server as I can see current activity on the main page. I tried purging my user too but when I watch something, it still does not show up. How can I fix this?

Plex log dir:
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/`

Here's the output of `ls -la /opt` in case anyone thinks this is a permissions issue.

```
drwxr-xr-x 10 plexpy nogroup  4096 Jan 17 23:42 .
drwxr-xr-x  5 root   root     4096 Jan 17 23:08 ..
-rw-r--r--  1 plexpy nogroup  1839 Jan 17 23:08 API.md
drwxr-xr-x  2 plexpy nogroup  4096 Jan 17 23:11 cache
-rw-r--r--  1 plexpy nogroup 10540 Jan 17 23:08 CHANGELOG.md
-rw-r--r--  1 plexpy nogroup  8139 Jan 17 23:35 config.ini
drwxr-xr-x  2 plexpy nogroup  4096 Jan 17 23:08 contrib
-rw-r--r--  1 plexpy nogroup  2715 Jan 17 23:08 CONTRIBUTING.md
drwxr-xr-x  3 plexpy nogroup  4096 Jan 17 23:08 data
drwxr-xr-x  8 plexpy nogroup  4096 Jan 17 23:08 .git
-rw-r--r--  1 plexpy nogroup   669 Jan 17 23:08 .gitignore
drwxr-xr-x  2 plexpy nogroup  4096 Jan 17 23:08 init-scripts
drwxr-xr-x 25 plexpy nogroup  4096 Jan 17 23:11 lib
-rw-r--r--  1 plexpy nogroup 35147 Jan 17 23:08 LICENSE
drwxr-xr-x  2 plexpy nogroup  4096 Jan 17 23:35 logs
drwxr-xr-x  2 plexpy nogroup  4096 Jan 17 23:17 plexpy
-rw-r--r--  1 plexpy nogroup 15360 Jan 17 23:39 plexpy.db
-rwxr-xr-x  1 plexpy nogroup  7777 Jan 17 23:08 PlexPy.py
-rw-r--r--  1 plexpy nogroup  9251 Jan 17 23:08 pylintrc
-rw-r--r--  1 plexpy nogroup  4734 Jan 17 23:08 README.md
-rw-r--r--  1 plexpy nogroup    40 Jan 17 23:35 version.lock
```

**Comment by JonnyWong16** [comment]
```
"Unable to retrieve data from database. Please check your settings."
```

means that there is no data in the database. (i.e. there are no statistics to show)
If you purged the user, then you erased their history.

It's just not a very user friendly error message (I've already fixed this).

**Comment by rfrowe** [comment]
I understand this, but what I'm saying is it's not recording any new history. People have been watching things but nothing is showing up.

**Comment by JonnyWong16** [comment]
Check the logs when someone is watching something, especially when they stop the stream, to see if there are any other errors or warnings.

**Comment by rfrowe** [comment]
Ah so it logs plays when the player is closed. I assumed it logged them once it hit the threshold time.
