### ISSUE TITLE
 Recently Added Error: Failed to Access Endpoint

### ISSUE THREAD

**Issue by Kolmain** [Tautulli/Tautulli#452]
Getting the following errors from PlexPy, and my Recently Added section now shows this error: There was an error communicating with your Plex Server. Please check your settings. However, everything else works. Just swapped to Dev, same problem. Could anyone lend a hand?

`2016-01-18 14:30:57    WARNING PlexPy Pmsconnect :: Unable to parse XML for get_recently_added: 'NoneType' object has no attribute 'getElementsByTagName'.`

`2016-01-18 14:30:57    WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=10 with error timed out`

`2016-01-18 14:30:09    WARNING Unable to retrieve data for get_recently_added.`

`2016-01-18 14:30:09    WARNING PlexPy Pmsconnect :: Unable to parse XML for get_recently_added: 'NoneType' object has no attribute 'getElementsByTagName'.`

`2016-01-18 14:30:09    WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=9 with error timed out.`

`2016-01-18 14:30:03    WARNING Unable to retrieve data for get_recently_added.`

`2016-01-18 14:30:03    WARNING PlexPy Pmsconnect :: Unable to parse XML for get_recently_added: 'NoneType' object has no attribute 'getElementsByTagName'.`

`2016-01-18 14:30:03    WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=9 with error timed out`

`2016-01-18 14:29:57    WARNING Unable to retrieve data for get_sync.`

`2016-01-18 14:29:57    WARNING PlexPy PlexTV :: Unable to parse XML for get_synced_items.`

**Comment by JonnyWong16** [comment]
Your calls to Plex are timing out (taking longer than 10 seconds). For some reason the connection between PlexPy and your Plex server is acting slow. Is your Plex server busy? i.e. Updating a bunch of metadata, generating video thumbnails, etc.?

**Comment by Kolmain** [comment]
Nope, not doing anything. Its been like this for about a week.

**Comment by JonnyWong16** [comment]
I increased the timeout duration to 20 seconds (from 10 seconds). If you're running the dev branch you can try it out.

**Comment by Kolmain** [comment]
Just updated the dev branch, that fixed it thank you!

**Comment by Hellowlol** [comment]
Why does plex takes so long time to respond, i can hit plex with 100 request /s and it still responds.. Seems like i need to increase the timeout so i dont mess up for other users.

**Comment by Kolmain** [comment]
I'm not sure as it didn't used to be that way. I am dealing with ~20TB of media.
EDIT: Now that I've swapped back to my previous DB (still running DEV), this issue is back.

**Comment by JonnyWong16** [comment]
Update to v1.3.0 to see if it is resolved.

Reopen the issue if it is still a problem.
