### ISSUE TITLE
PushBullet Notifications Issue (Bad Request)

### ISSUE THREAD

**Issue by thehomerepot** [Tautulli/Tautulli#454]
I'm trying to configure PushBullet notifications but I continually get the following in my logs.

DEBUG: Sending test Pushbullet notification.
WARNING: PlexPy Notifier :: PushBullet notification failed: Bad Request

I don't see anything more detailed in the log file in /opt/plexpy. I've tried using an API key from another app that functions properly as well as generating a new API key and neither work.

**Comment by JonnyWong16** [comment]
Have you tried any of the other notification agents?

**Comment by thehomerepot** [comment]
I haven't, I've only ever used PushBullet with any of my other programs. I'll take a look and see if any others are worth trying.

Are you thinking something is wrong with my system or firewall that would prevent PushBullet? (I have other things running on the exact same server that use PushBullet without issue)

**Comment by JonnyWong16** [comment]
That's my thinking. It's still working for me. Do you have a device or channel set as well?

**Comment by thehomerepot** [comment]
I had a channel tag set and just removed it. It's now working. I have to admit I've never used a channel tag before. I assumed it was just like a hashtag I could use to filter data. Looks like there is more configuration to it than that. Sorry for wasting your time!

**Comment by JonnyWong16** [comment]
You can set up Pushbullet channels, but I think you enter the name without the `#` tag.

**Comment by Arcanemagus** [comment]
Yep, channels should work just fine, enter the tag without the `#`.
