### ISSUE TITLE
"Uncaught exception" when trying to import from PlexWatch, using latest update of PlexPy

### ISSUE THREAD

**Issue by iAmMrinal0** [Tautulli/Tautulli#46]
I started from scratch just to test few things out and when trying to import the "plexwatch.db" file I get an "Uncaught exception." The on screen logging says as follows:

```
08-Aug-2015 00:14:06 - ERROR :: CP Server Thread-10 : PlexPy Importer :: Uncaught exception.   
08-Aug-2015 00:14:24 - ERROR :: CP Server Thread-2 : PlexPy Importer :: Uncaught exception.   
08-Aug-2015 00:15:44 - ERROR :: CP Server Thread-7 : PlexPy Importer :: Uncaught exception.   
08-Aug-2015 00:16:53 - ERROR :: CP Server Thread-8 : PlexPy Importer :: Uncaught exception.
```

I have tried to import from other locations too but still the same. Any other information if required let me know will share.

**Comment by drzoidberg33** [comment]
Please see the wiki: https://github.com/drzoidberg33/plexpy/wiki/Troubleshooting

**Comment by iAmMrinal0** [comment]
God! I have installed on various systems and everytime I forget this but eventually remember copying the sqlite file but not this time. Sorry for the trouble.
