### ISSUE TITLE
[Feature Request] More Detailed Media Data

### ISSUE THREAD

**Issue by m1lkman** [Tautulli/Tautulli#464]
I'd love to see more data available for media via the web interface. Resolutions and audio channels, sortable and searchable by library, series, season, etc...Would be nice to be able to pull up an entire series and quickly be able to tell what I don't have in 1080p or 5.1dts. An entire new tab with the ability to filter would be great. Thanks for the great product.

**Comment by JonnyWong16** [comment]
Everything you mentioned has been implemented in the dev branch. There is a new table with the media info for all the items in a library (video/audio details, date added and watched, play count, and file sizes).

We are still testing and fixing bugs, but it should be released soon.

**Comment by m1lkman** [comment]
Awesome, sorry for bugging you then. I should have dug more. Thank you.

**Comment by JonnyWong16** [comment]
Added in v1.3.0.
