### ISSUE TITLE
Items without a year/season show empty brackets.

### ISSUE THREAD

**Issue by dmptrluke** [Tautulli/Tautulli#466]
I've made a custom library on my server for short videos and stuff from youtube. When looking at the history in PlexPy, it shows empty brackets where the year would be.

![image](https://cloud.githubusercontent.com/assets/894343/12534015/60d0405c-c2ab-11e5-870c-29bd7fdaed76.png)

**Comment by JonnyWong16** [comment]
Fixed in v1.3.1.
