### ISSUE TITLE
Errors accesing Libraries / Users / History tabs

### ISSUE THREAD

**Issue by cesalo** [Tautulli/Tautulli#467]
I just installed plexpy today. I'm using Plex in a QNAP, version: 0.9.15.2 and plexpy 1.3.0.
When I tried to go to the user tab get the following error:

_DataTables warning: table id=users_list_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7_

When I try to go to the history tab get the following error:

_DataTables warning: table id=history_table - Unable to execute database query._ and then: _DataTables warning: table id=history_table - Requested unknown parameter 'date' for row 0. For more information about this error, please see http://datatables.net/tn/4_

When I try to go to the Library tab get the following error:

_DataTables warning: table id=libraries_list_table - Unable to execute database query._ and then: _DataTables warning: table id=libraries_list_table - Requested unknown parameter 'library_thumb' for row 0. For more information about this error, please see http://datatables.net/tn/4_

The same errors are in the plexpy log.

Any assistance will be appreciated.

**Comment by JonnyWong16** [comment]
Force refresh (Ctrl+F5)

**Comment by cesalo** [comment]
Thanks for the help. Already try that also cleared cache manually and even testing in different browsers (chrome and ffox) still having the same issues.

**Comment by cesalo** [comment]
Was able to fix the issue. The python version in QNAP was 2.7.9, Installed the last version I could find and the issues got fixed. This is the link in case helps somebody else:
http://forum.qnap.com/viewtopic.php?f=217&t=109899
then you just restart plexpy:
export PATH=/opt/QPython2/bin:$PATH
cd /opt/plexpy; python2.7 PlexPy.py
