### ISSUE TITLE
duplicated Library Statistics

### ISSUE THREAD

**Issue by fliiiix** [Tautulli/Tautulli#469]
![librarystats](https://cloud.githubusercontent.com/assets/1682954/12535731/34e4bf40-c28d-11e5-9ac1-2599057d5f46.png)

I just upgraded to the latest version with `git pull` and restarting plexpy. And now every Library is duplicated in Library Statistics.

**Comment by JonnyWong16** [comment]
I don't know what happened here. Are the libraries duplicated on the Libraries page? Can you just reselect the cards in Settings > Homepage Statistics?

**Comment by fliiiix** [comment]
Strange I updated to v.1.3.3 still the same problem. If I deselect it on the Homapge Statistics page both cards are gone but both reappear if I select it again. 
![2016-01-26--1453834800_1920x1080](https://cloud.githubusercontent.com/assets/1682954/12591351/a9892b98-c467-11e5-8d15-200407ef2a8f.png)

Also as you can see these library are duplicated here. And If I select for example both Movies libraries I have 4 cards on the front page. Interesting is that all link to the same thing.

**Comment by JonnyWong16** [comment]
I think the libraries might have gotten duplicated in your database somehow.

Try opening your `plexpy.db` file using [SQLite Browser](http://sqlitebrowser.org/) and looking at the `library_sections` table.

**Comment by fliiiix** [comment]
I can temporary fix it if I remove the items from the database and copy the clean db while plexpy is running. If I stop plexpy and restart it they get duplicated again. :confused: 

Oh and if plexpy is stopped and I copy the clean db an start it the library's are also duplicated. 

Any Ideas?

And here my library related log entries, but I guess that's normal? 

```
26-Jan-2016 23:56:45 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
26-Jan-2016 23:56:45 - DEBUG   :: MainThread : PlexPy Pmsconnect :: No library data.
26-Jan-2016 23:56:46 - DEBUG   :: MainThread : PlexPy Pmsconnect :: No library data.
26-Jan-2016 23:56:47 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
```

**Comment by JonnyWong16** [comment]
Did you remove all the rows from the database or just the duplicates?

Also make sure the `server_id` column matches the `pms_identifier` in your `config.ini` file.

**Comment by JonnyWong16** [comment]
Can you also send me your `plexpy.db` file on the [Plex forums](https://forums.plex.tv/profile/JonnyWong16)?

**Comment by geekcroft** [comment]
I also have this issue - I removed all libraries (and had to re-add them via the hidden URL). However just to add that the last library I added to plex (Added yesterday) ISNT duplicated.

I'll comment on both bugs related to this to hope it helps.

(Oh, and thanks for all your work on this - it's an awesome little app!)

EDIT: Also adding that doing this seems to have removed all my play history for the removed/re-added libraries :(

**Comment by Christopher3712** [comment]
This one just hit me too.  Plex updated to version 0.9.15.2 last night and created this problem.  It's maddening.

**Comment by JonnyWong16** [comment]
Can you compare the `machineIdentifier` found here:

```
http://<plex_ip>:32444/identity?X-Plex-Token=<your_plex_token>
```

with the `pms_identifier` in your `config.ini` file?

**Comment by Christopher3712** [comment]
Oh, I cleaned it up. This thread was a great help. It's happened 3 times now, causing me to reapply library permissions to all my users.

**Comment by JonnyWong16** [comment]
1. Update PlexPy to v1.3.5.
2. Backup your `plexpy.db` file.
3. Go to `http://localhost:8181/delete_duplicate_libraries`
4. Hope I didn't screw up.

**Comment by JonnyWong16** [comment]
Report further issues in #491.

**Comment by Jovetic** [comment]
Thanks Jonny, that fixed mine.  Mine happened after moving my plex instance from one login to another.

**Comment by jemus42** [comment]
Had the same problem, https://github.com/drzoidberg33/plexpy/issues/469#issuecomment-179019404 worked for me, too, thanks!
