### ISSUE TITLE
[REQUEST] Twitter support

### ISSUE THREAD

**Issue by mbnn** [Tautulli/Tautulli#47]
For notifications it would be really cool if you could support Twitter :)

Thanks!

**Comment by jroyal** [comment]
@drzoidberg33 How are you handling imports? Are you just downloading the source and sticking them in lib? Just asking for if we used a twitter python library for this or something.

**Comment by drzoidberg33** [comment]
Basically yes, everything that isn't part of core Python libraries I build and include in the libs folder. 

Twitter doesn't require any additional libraries though as the functionality is already there it just needs to be activated and we need a PlexPy Twitter developer account so we can set the API details.

You can see Headphones's repo on how it's been implemented: https://github.com/rembo10/headphones

**Comment by kylerw** [comment]
+1

**Comment by drzoidberg33** [comment]
Released.
