### ISSUE TITLE
Data Table Warning

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#470]
I get a popup warning whenever I access the users tab that says this?

DataTables warning: table id=users_list_table - Requested unknown parameter 'last_watched' for row 0. For more information about this error, please see http://datatables.net/tn/4

Last few log items:
Unable to retrieve data for get_sync.
PlexPy PlexTV :: Unable to parse XML for get_synced_items.

I wasn't quite sure where to go from there. Thanks for the awesome application!

**Comment by victordk** [comment]
Try refreshing cache with CTRL+F5 when you are on the users list page.

**Comment by ghost** [comment]
Worked perfectly! Just so I can prevent this in the future, my caching settings in apache broke this guy?

**Comment by JonnyWong16** [comment]
The datatables cache themselves to remember searching, what page you're on, etc. I can disable the caching, I guess...
