### ISSUE TITLE
Title column padding causing other columns to hide

### ISSUE THREAD

**Issue by pmow** [Tautulli/Tautulli#472]
In non-mobile view in Chrome I'm using half of a 4K (3840x2160) screen.  Half of the light grey container for "History" is taken up by Title space.  The rest is taken up by the Title text, User, and Time.  That's it.

It would be really great if this could be adjusted so that other columns can show up.  In my case, the Player column easily fits with room to spare.  I have considered that there might be a title somewhere in the history taking up so much room.  While true, there is still a considerable amount of "hard" padding which appears to be kicking more columns out.

**Comment by JonnyWong16** [comment]
Duplicate #156.

**Comment by JonnyWong16** [comment]
Screenshot?

**Comment by pmow** [comment]
![before](http://imgur.com/2bS3Rio.png)

![after](http://imgur.com/scOydGV.png)

**Comment by JonnyWong16** [comment]
@pmow I don't know if this is fixed in v1.4.0. Can you let me know?

**Comment by pmow** [comment]
Certainly.  I've set a reminder for it as I'm out of town until Friday, and can't get my hands on a 4K screen currently.
