### ISSUE TITLE
User Page not Pulling in Last Played after 1.3.1 update

### ISSUE THREAD

**Issue by Coolmanchambers** [Tautulli/Tautulli#475]
Just updated to 1.3.1 this morning, and when i went into the user page i am getting the error below:

![image](https://cloud.githubusercontent.com/assets/16180124/12537568/69653afa-c27f-11e5-97c1-51613b1f7622.png)

Under the Last played column for all users it is showing "Null" but everything else appears to be coming in fine.

![image](https://cloud.githubusercontent.com/assets/16180124/12537576/9398cd32-c27f-11e5-8ccb-5fc1c62a11d1.png)

**Comment by JonnyWong16** [comment]
Use the search for the issues next time. #467
Force refresh (Ctrl+F5)

**Comment by Coolmanchambers** [comment]
I tried that based off another thread but it wasn't working at first and thought it might be update related.  Initially i had tried to reboot PlexPy, force refresh, reboot computer and force refresh again. 

I dont know if something was just stuck and it took a 2nd or 3rd reboot to clear it, but it looks like it is working now. Thanks Jonny

**Comment by JonnyWong16** [comment]
Resolved. Closing.
