### ISSUE TITLE
Users screen generating table error

### ISSUE THREAD

**Issue by my95z34** [Tautulli/Tautulli#479]
I noticed that this commit: https://github.com/drzoidberg33/plexpy/commit/b1ea3bcd4e1d704477695d8e629dfeb213894475 changes last watched to last played.  Now when I open my users screen I get a table error: http://i.imgur.com/PSJADlE.png and my table looks like this: http://i.imgur.com/oZPaK7K.png

I'm assuming my table wasn't properly changed.  Not sure if it's an issue just on my end, or if the upgrade process needs some fine tuning. 

Thanks!

**Comment by my95z34** [comment]
I am on the master branch, by the way.

**Comment by JonnyWong16** [comment]
Did you try force refreshing? Ctrl+F5

**Comment by crotinger** [comment]
I was having the same issue. However Force refreshing resolved the issue. Thanks for the prompt reply.

**Comment by my95z34** [comment]
Well shit.  Sorry about that.  Force refresh fixed it.  Thanks!
