### ISSUE TITLE
Include Changelog

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#48]
Can you include somewhere  a changelog of all updated items during a per day/period

I like how sickrage does it, see example 

<a href="http://nl.tinypic.com?ref=24nogi1" target="_blank"><img src="http://i59.tinypic.com/24nogi1.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by drzoidberg33** [comment]
I'll be doing this when the first release is out. Not long now, I just have two sections to finish up with before the first "stable" release.

**Comment by drzoidberg33** [comment]
Changelog will be updated with upcoming releases. Currently no access to it from the interface though.
