### ISSUE TITLE
New library feature never seems to populate.

### ISSUE THREAD

**Issue by cwire4** [Tautulli/Tautulli#482]
Since the new version (0ba50124647e27b8815cf6a28be73931cccdc170) my libraries never seem to populate even after leaving it overnight.

Also, when going to the libraries page I just started getting this message:

DataTables warning: table id = libraries_list_table requested unknown parameter "last_watched" for row 0.

Points to this error: https://datatables.net/manual/tech-notes/4

Edit: I'm running my Plexpy instance on a raspberry pi for what that's worth.

**Comment by JonnyWong16** [comment]
The library update might have crashed. You can try shutting down PlexPy, and setting `update_section_ids=1` in the `config.ini` file, then restarting PlexPy to force the update again.

As for the datatables warning. Do a force refresh (Ctrl+F5)

**Comment by JonnyWong16** [comment]
Try updating to v1.3.2.

**Comment by cwire4** [comment]
Setting update_section_ids=1 seems to have fixed it.

**Comment by p1r473** [comment]
Do we leave it at update_section_ids=1 forever or do we change it back?
The latest version I installed last night still had this issue, so I don't think its fixed in 1.3.3

**Comment by JonnyWong16** [comment]
It will automatically set itself back to `update_section_ids = 0` when it is done updating.

**Comment by p1r473** [comment]
I am using Version 1.3.3 and still not fixed
It went back to update_section_ids = 0 but still the libraries are empty, even after trigger the update.
And I had changed it to = 1 while it was shut down, so I know that wasn't the issue
I do see in the console 
27-Jan-2016 16:51:44 - WARNING :: CP Server Thread-9 : Unable to retrieve data for get_library_sections.

**Comment by JonnyWong16** [comment]
Post your full logs please.

**Comment by p1r473** [comment]
Hi, undeleting the libraries as you mentioned in #491 fixed my issue here.

**Comment by JonnyWong16** [comment]
This seems like it has been resolved.
