### ISSUE TITLE
Plexpy hanging after update

### ISSUE THREAD

**Issue by realvz** [Tautulli/Tautulli#483]
My plexpy install on 2 different machines is completely hosed. I performed the update manually and after install plexpy starts normally but after homepage is rendered it hangs. I can't even curl the homepage, it results in connection timed out. 

Logs. Update occurred after 4pm on 24 Jan. 
http://paste.ubuntu.com/14655673b

**Comment by realvz** [comment]
In the meanwhile I rolled back to 45c2f5 and things are up again on one machine, the other machine is still running latest update and hanging at startup.

**Comment by JonnyWong16** [comment]
What do you mean by "hangs"? It's just unresponsive and you can't click on any links?

**Comment by realvz** [comment]
The page never finished loading. If I try to refresh it just times out. The page only loads once when I restart the service and that too not completely.  After that all I get is connection timed out.

**Comment by JonnyWong16** [comment]
See if v1.3.2 fixes it. If not, try setting `update_section_ids=0` in the `config.ini` file and starting it up again to see if the library updating is the problem.

**Comment by erodewald** [comment]
@JonnyWong16 I had this issue after doing an update from git about 2 hrs ago (Ubuntu 15.10). The pid was hung/stale so I set `update_section_ids=0` (it was `-1`) and then restarted the service. It seems to be working now.  

edit: Library statistics is empty - I see another thread on that so I'll check that out.

**Comment by JonnyWong16** [comment]
Yeah, `update_section_ids=0` disables the library update (so the stats will be empty).
`update_section_ids=1` starts the update (-1 means its updating).

But it seems like PlexPy just freezes when it's trying to update. And it seems like it only happens on Ubuntu.

**Comment by erodewald** [comment]
@JonnyWong16 I see, I'll try setting it to 1 and see if it hangs again. 

Not hanging - but no stats yet. Possibly still generating them? I'll give it some time before investigating a problem that may not exist.

**Comment by realvz** [comment]
My update_section_ids is already set to 0 and already running latest version, still no dice. Btw it's happening on both Ubuntu 15.10 and raspbian wheezy.

**Comment by alternativesurfer** [comment]
1.3.2 just broke this for me.
Timing out when attempting to load the app.

Update_section_ids is already set to 0

this is on Win server 2012 R2

**Comment by JonnyWong16** [comment]
Everyone post your logs please.

**Comment by realvz** [comment]
Here are my logs. I deleted the log file before restarting, these logs include everything after restarting plexpy service. The web interface never opens for me anymore. 

http://paste.ubuntu.com/14675964/

**Comment by realvz** [comment]
I copied config.ini from a fresh install and I was able to get plexpy to run. After that I stopped the service and restored the config file and plexpy started properly with good config.

**Comment by spalger** [comment]
This just happened to me too. Order of events as I saw them:
1. plex server out of date, updated it
2. open plexpy, things seem broken
3. plexpy update available notification, start update
4. plexpy update completes fine
5. watch statistics and library statistics are taking forever to load
6. open the network inspector to debug
   1. jquery and moment js files are taking 12+ seconds to load, but they do eventually load
   2. several other requests succeed normally
   3. several stats api calls are hanging, I don't see them complete
7. reload the page and now I'm getting timeouts in the browser
8. attempts to curl index from localhost timeout
9. found this issue, config.ini already had `update_section_ids = 0` set
10. made several attempts to restart plexpy gracefully with `kill $(cat plexpy.pid)`, has no effect
11. `kill -9` takes it down
12. start again and all seems fine

Here is are the logs from today: https://gist.github.com/anonymous/bd4324852f298af0256c

**Comment by JonnyWong16** [comment]
@drzoidberg33 @Hellowlol Help?

I think this is because I started the library update thread prior to daemonizing?
https://github.com/drzoidberg33/plexpy/blob/master/plexpy/pmsconnect.py#L84

**Comment by Hellowlol** [comment]
Im not sure, but i would the do daemonizing before i started any threads

**Comment by JonnyWong16** [comment]
Possibly fixed in v1.3.5.
