### ISSUE TITLE
Unable to set notifications

### ISSUE THREAD

**Issue by 2fst4u** [Tautulli/Tautulli#485]
I'm unsure if this is a bug or a feature request but I can't for the life of me figure out how to select which notifications I want to receive. How do I do it/can it be made easier?

**Comment by JonnyWong16** [comment]
Instructions are on the settings page

**Notification Agents**
Toggle the desired notification options by clicking the bell icon and configure it by clicking the settings icon to the right.

**Comment by JonnyWong16** [comment]
Assuming this is resolved.

**Comment by 2fst4u** [comment]
Assume so, unless you see fit to make it easier to find. Up to you.
