### ISSUE TITLE
Request: Notifications per library by user

### ISSUE THREAD

**Issue by p1r473** [Tautulli/Tautulli#489]
Hello. I have multiple libraries- one is a library for my girlfriend of her shows, and one is a library for me of my shows.
I want to be able to send a notification to my girlfriend, when a new show is added to her library (new episode ready for her to watch)
However, it seems the current implementation will let the email user know about ANY new media added. And I don't want to send her an email when I added one of MY shows. Only want to tell her when I added one of her shows.
Another example of usability like this is so I can maybe send an email to my girlfriend when a new episode is released for her, and send myself an email when a new show is ready to watch for me.

Also more modular, maybe to send an email to her when her show is added and ready, but an email to me when she  finishes watching so I can delete it.
So different triggers for different emails.

On another note: why is the max percentage a show can be considered watched be 100?

**Comment by Hellowlol** [comment]
You can use the script notification to do this today, but you might need get your hands dirty ;)

**Comment by p1r473** [comment]
It looks like notification exclusion tags can only be if Movie, TV, or Music. Any way to make the exclusion tag be per library?
Also, without the exclusion tag, and without being able to do some sort of IF statement, I don't know how to exclude certain libraries with {library_name}

**Comment by Hellowlol** [comment]
The if statements etc would be handled by the script. So say you use {library_name}

This is a quick example show to make a simple script in python

```
from email.mime.text import MIMEText
import requests
import email.utils
import smtplib
import sys
import urllib

ln = sys.argv[1]
from = 'addedtoplex@domain.zomg' #editme
name = 'Your name' # editme
your_email_server = '' # editme
your_email_port = 1111  # editme
your_email_username = '' # editme
your_email_password = '' # editme


if ln == 'gf_library_name': # editme
    subject = '' #editme
    body = '' #editme
    to = 'babe85@gmail.com' #editme
elif ln == 'my_library_name': #editme:
    subject = '' #editme
    body = '' #editme
    to = '' #editme

else:
    return # stops the script.

message = MIMEText(body, 'plain', "utf-8")
message['Subject'] = subject
message['From'] = email.utils.formataddr((name, from))
message['To'] = to

mailserver = smtplib.SMTP(your_email_server, your_email_port)
mailserver.starttls()
mailserver.ehlo()
mailserver.login(your_email_username, your_email_password)
mailserver.sendmail(from, to, message.as_string())
mailserver.quit()
```

**Comment by JonnyWong16** [comment]
Note that the notification with still be sent to all emails setup in PlexPy. If you want separate emails you'll need to send it from the custom script, and not PlexPy's `/test_notifier`.

**Comment by Hellowlol** [comment]
Yeah it was just a quick example. Thanks for the clarification, I forgot about that

**Comment by p1r473** [comment]
So I swap in my names, IP, and port, like so:

import sys
import urllib
import requests

user = sys.argv[1]
ln = sys.argv[2]

if user == 'Georgina' and ln == 'Georgina's Library':
    subject = ''
    body = ''
    url = 'http://localhost:8181/test_notifier?config_id=10&subject=%s%&body=%s' % (urllib.quote_plus(subject), urllib.quote_plus(message))
    requests.get(url)

I see where to specify both subject and body, but I dont see where to change the message in the above code.

And I paste that whole thing into the "script arguments" under custom notification message?
If not under script arguments, where do I put that? Under the message body?

**Comment by JonnyWong16** [comment]
Save it to a python script file like `recently_added_by_user.py` or something to your computer. 

Then in PlexPy:
- Settings > Notifications > Script arguments: `{user} {library_name}`
- Settings > Notification Agents > Scripts: enter the folder where you saved the script, and select the script in the dropdown menu for recently added.

**Comment by Hellowlol** [comment]
I updated the example script so we dont have to relay on plexpy test notification. You might want to add some more arguments since subject and body is omitted by default.

**Comment by p1r473** [comment]
I actually have a few batch files that can call some command line programs like SendSMTP (a mailer) and pushbullet I know has a CLI too, so I am trying that way.

I've tried to integrate your logic, but nothing seems to happen when I click the notify test.

My script is:

import sys
import subprocess

user = sys.argv[1]
ln = sys.argv[2]

if user == 'Babe' and ln == 'Babe\'s TV Shows': 
    subprocess.call("1.bat")
elif user == 'Me' and ln == 'My Shows': #editme:
    subprocess.call("2.bat")
else:
    subprocess.call("3.bat")

Right now, the bat files just print out either Babe, Me, or Fail... so far, nothing is happening when I click notify test. In fact, even if I choose the test script to just be a test bat file that contains "echo hello world" it doesn't do anything.

Here is the log:
2016-01-29 02:24:16 INFO    PlexPy Notifiers :: Script notification sent.
2016-01-29 02:24:16 DEBUG   PlexPy Notifiers :: Full script is: ['S:\Shows\babe\helloworld.bat']
2016-01-29 02:24:16 INFO    Writing configuration to file
2016-01-29 02:24:16 DEBUG   PlexPy Notifiers :: Trying to run notify script, action: None, arguments: None
2016-01-29 02:24:16 DEBUG   Sending test Scripts notification.

No batch file is opening up like it should

Also, I am trying to figure out the if statement.
First, it seems user must == 'Babe'... so won't this only work if she is signed in to the server?
Second, only works if the library name is 'babe's TV shows'... is the script smart enough to figure out that we mean the library where the new episode was added?

**Comment by JonnyWong16** [comment]
It's possible that the script is running properly, but the output is sent somewhere hidden.

Also realized that a "Recently Added" notification won't have a user associated with it.

**Comment by p1r473** [comment]
That seems to be the case.
I almost have it working. I will post back a script that I used so other novices like me can get it working easily when its done.

**Comment by Hellowlol** [comment]
Have you tried the one i posted?

**Comment by p1r473** [comment]
Hello, I could not get it to work

email.py
  File "S:\email.py", line 1
    from email.mime.text
                        ^
SyntaxError: invalid syntax

So here is the script I ended up using:

import subprocess
import sys

ln = sys.argv[1]

if ln == "Babe\'s TV Shows": 
    subprocess.call("notifyBabe.bat")
elif ln == "TV Shows":
    subprocess.call("notifyMe.bat")
else:
    subprocess.call("notifyFail.bat")

And in each notify bat file, is a call to an email program, like 
SendSMTP.exe /nos /host smtp.gmail.com /port 587 /auth 2 /userid sender@gmail.com /pass YourGmailPassword /from sender@gmail.com /to recipient@email.com /subject subject /body message

I found the script here:
https://www.raymond.cc/blog/sending-email-using-command-line-useful-for-downtime-alert-notification/

Also should work with other CLI programs like Pushbullet, etc

**Comment by Hellowlol** [comment]
ooops. I fixed it now :P, anyway im glad you found something that works for you.

**Comment by Hellowlol** [comment]
Remember that you can write a log of the script by adding > log.txt to the command line args

**Comment by p1r473** [comment]
Thanks, can you show me how I would do that with a code sample?
Thanks!
