### ISSUE TITLE
Feature Request: Override base url (for use in reverse proxies)

### ISSUE THREAD

**Issue by mescon** [Tautulli/Tautulli#49]
It would be lovely for an option to to set a base URL, for use in reverse proxies.
For instance, in nginx I have configured /plexpy/ as an endpoint to go to http://127.0.0.1:8181/, but when I go to the URL I get this:

```
404 Not Found

The path '/statistics' was not found.

Traceback (most recent call last):
  File "/opt/plexpy/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/plexpy/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/plexpy/lib/cherrypy/_cperror.py", line 411, in __call__
    raise self
NotFound: (404, "The path '/statistics' was not found.")
Powered by CherryPy 3.8.0
```

**Comment by drzoidberg33** [comment]
Where does the /statistics path come from?

**Comment by mescon** [comment]
I defined it in my nginx reverse proxy.. for instance, /couchpotato goes to http://localhost:5050. In CouchPotato I can define "base url" as /couchpotato and links will be rewritten to /couchpotato/image.jpg instead of /image.jpg if you get what I mean.

**Comment by drzoidberg33** [comment]
Ah okay, you mentioned the path /plexpy in your post so was confused. I'll test this out, as far as I know it should already work but I haven't tested it.

**Comment by mescon** [comment]
Are you IRC somewhere, in case you want to have look at my setup and have me try things out?

**Comment by drzoidberg33** [comment]
The problem is with the CherryPy redirects, for now you can go directly to the /home path which will work fine.

So instead of going to: http://yourdomain.com/plexpy

go to:

http://yourdomain.com/plexpy/home

I'll sort out the issue with the base url.

**Comment by mescon** [comment]
Wow, cool - thanks for looking into it!

**Comment by mbnn** [comment]
Does anyone have any idea how to get that to work in Apache2? :)

**Comment by drzoidberg33** [comment]
@mbnn 

I have a subdomain for each service, so for PlexPy i have for example: http://plexpy.mydomain.com which then proxies to localhost:8181. Here is my apache vhost config:

```
<VirtualHost *:80>
    ServerName plexpy.mydomain.com

    ProxyRequests Off
    ProxyPreserveHost On
    ProxyPass / http://localhost:8181/
    ProxyPassReverse / http://localhost:8181/    
</VirtualHost>
```

If you're using SSL, you need extra parameters - but let me know if you need an example for that too.

I would recommend using the subdomain option as using a separate path (like in this specific issue) causes issues with the internal redirects - using a subdomain like above works perfectly on my end.

**Comment by mbnn** [comment]
When i enter that in a vhost i get:

AH00526: Syntax error on line 9 of /etc/apache2/sites-enabled/site1:
Invalid command 'ProxyRequests', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.

**Comment by mbnn** [comment]
I entered in the sites-enabled/vhostname

<VirtualHost *:80>
    ServerName subdomain.domain.com
    ProxyRequests Off
    ProxyPreserveHost On
    ProxyPass / http://localhost:8181/
    ProxyPassReverse / http://localhost:8181/
</VirtualHost>

When i then browse to subdomain.domain.com i get Internal Server Error. Any idea?

Update, nvm i had to a2enmod mod_proxy and a2enmod proxy_http

**Comment by drzoidberg33** [comment]
> When i enter that in a vhost i get:
> 
> AH00526: Syntax error on line 9 of /etc/apache2/sites-enabled/site1:
> Invalid command 'ProxyRequests', perhaps misspelled or defined by a module not included in the >server configuration
> Action 'configtest' failed.

You probably don't have mod_proxy enabled in apache, see here: https://httpd.apache.org/docs/2.2/mod/mod_proxy.html

If you need to know how to enable it for your specific distribution just Google for example: mod_proxy Ubuntu 14.10

**Comment by mbnn** [comment]
Thank you for the help drzoidberg33 :)

**Comment by mescon** [comment]
That's the name of my reverse proxy endpoint.
Den 10 aug 2015 01:31 skrev "drzoidberg33" <notifications@github.com>:

**Comment by fduchene** [comment]
The override of the base URL is already implemented (inherited from headphones).
Shutdown plexpy, edit config.ini and change http_root = /YOURDIR/  and voilà.

**Comment by xrolfex** [comment]
This didn't work for me it seems to redirect to the base url but as a # anchor link.

**Comment by poenn** [comment]
it works for me with the following nginx configuration, setting http_root = /plexpy/

location /plexpy {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass          http://localhost:8181;  
        }

**Comment by xrolfex** [comment]
Hmm this is mine for apache2

```
<Location /plexstats/>
          ProxyPass http://localhost:8181/home/
          ProxyPassReverse http://localhost:8181/home/
</Location>
```

I just keep getting a 404 back and I made sure to change the config.ini http_root = /plexstats both with and without the /

**Comment by drzoidberg33** [comment]
@xrolfex You cannot set your base as /home, it just needs to be http://localhost:8181/

**Comment by xrolfex** [comment]
@drzoidberg33 Still didn't seem to make a difference, all my other reverse proxies are working. Not quite sure at the moment.

**Comment by mannibis** [comment]
Same issue here

Using apache2

```
 <Location /plexpy>
                order deny,allow
                deny from all
                allow from all
                ProxyPass http://192.168.1.135:8181/
                ProxyPassReverse http://192.168.1.135:8181/
 </Location>
```

Gives me error saying /home is not found. If I then go to domain.com/plexpy/home, it works...

So seems as if I need to just bookmark domain.com/plexpy/home rather than just /plexpy

**Comment by Hellowlol** [comment]
Should https://github.com/Hellowlol/plexpy/blob/master/plexpy/webstart.py#L72 be bool(options['http_proxy']) ? dunno if its handled correctly its its a string or int

**Comment by drzoidberg33** [comment]
A quick look and it looks like this may already be built in but has to be changed in the config file. I haven't tested this so not sure if it works - but please give it a go:

https://github.com/drzoidberg33/plexpy/blob/master/plexpy/config.py#L97

Changing the `http_root` option in the config.ini might do the trick.

**Comment by xrolfex** [comment]
I have tried changing the http_root and it still fails for me too.

**Comment by Hellowlol** [comment]
Can you try to set 
http_proxy to: True

**Comment by drzoidberg33** [comment]
Seems to work for me:

config.ini:

`http_root = /plexpy`

My vhost:

```
<VirtualHost *:80>
    ServerName plexpy.mydomain.com

    ProxyRequests Off
    ProxyPreserveHost On
    ProxyPass /plexpy http://localhost:8181/plexpy/
    ProxyPassReverse /plexpy http://localhost:8181/plexpy/
</VirtualHost>
```

**Comment by drzoidberg33** [comment]
As has been demonstrated, this functionality exists already you just have to edit the config.ini file manually.

**Comment by scottjasso** [comment]
If anyone happens to be using nginx and a non-standard port, you want the following (along with http_root = /plexpy):

```
location /plexpy {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://localhost:8181;
}
```

I'm using https on port 8443, and nginx would drop the port number if the Host is just $host (from @poenn's comment). $http_host will include hostname and port.

**Comment by SpartacusIam** [comment]
I can't get plexpy to work behind my reverse proxy even after changing the http_root = /plexpy.  My vhost is below:

VirtualHost *:443>
    ServerName domainname

Location /plexpy/>
        ProxyPass http://localhost:8181/plexpy/
        ProxyPassReverse http://localhost:8181/plexpy/
/Location>
/VirtualHost>

**Comment by nexxai** [comment]
Has anyone been able to get this working with an IIS reverse proxy using the URL Rewrite/ARR method?  I've tried both with and without changing the subdirectory of the http_root setting in config.ini and neither seems to work.  Without gives me a bigger problem (straight up 404) but with just gives me a blank page.

**Comment by jgillman** [comment]
Worked like a charm for me using nginx! Didn't realize this was in [the FAQ](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#why-does-plexpy-not-work-with-my-reverse-proxy-setup) as well.

**Comment by SpartacusIam** [comment]
@jgillman Where did you enter the proxy_set_header info in your config file?

**Comment by jgillman** [comment]
@jimphreak to be honest I didn't actually need to make that change. I only made the changes in the `config.ini` for PlexPy itself.

Based on your previous comment, it looks like you're using Apache, not Nginx.

---

#### If you decided to use Nginx instead:

If you think you need it, the `proxy_set_header` stuff would go in a server block in your `nginx.conf` file (or wherever you define your servers for Nginx). It would look something like this: https://gist.github.com/jgillman/2b8e644878a3141873a8

I'm guessing you could move the proxy header stuff out of the `location` block so that it would work for the whole server, but I've literally only been using Nginx for one day so I have very little authority :sweat_smile:

**Comment by zackbcom** [comment]
If you are getting this error "This request has been blocked; the content must be served over HTTPS." when you are trying to proxy a http plexpy to a https nginx, include this line in your nginx config `proxy_redirect http:// $scheme://;`
Example:

``` nginx
#Plexpy
server {
  listen 443 ssl;
  server_name example.com;

  ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

  location / {
    proxy_pass http://localhost:8181;
    proxy_redirect http:// $scheme://;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }  
} 
```

Source: https://www.nginx.com/resources/wiki/start/topics/examples/SSL-Offloader/

**Comment by JDIacobbo** [comment]
I have been unable to get this to work.

Every time I update the http_root in the config.ini and save, I restart PlexPY.  When it restarts, the config file has the value I put into http_root reset back to "/"

Any ideas why this is happening?

**Comment by drzoidberg33** [comment]
@JDIacobbo You must first shut down PlexPy, then edit the config file then start PlexPy back up again.

**Comment by JDIacobbo** [comment]
@drzoidberg33 That did it.  Thanks!

**Comment by msaeedm** [comment]
I know this is an old thread but I thought I would give it a shot try to ask here instead of opening a new thread that could essentially be a duplicate.

So I just installed Plexpy in a jail in Freenas. I have my apache server in a different jail with a reverse proxy for other services (sickrage/couchpotato/owncloud). The problem I am having is that the reverse proxy is not working for plexpy but works fine for the other services. I have http_root = /plexpy and http_proxy =1 in config.ini of plexpy which was edited manually with plexpy turned off.

Here is my vhost:

<Virtualhost *:80>
ServerName 192.168.1.9
ProxyRequests Off
ProxyPreserveHost On

## couchpotato
ProxyPass /couchpotato http://192.168.1.7:5050/couchpotato
ProxyPassReverse /couchpotato http://192.168.1.7:5050/couchpotato
ProxyPass /cp http://192.168.1.7:5050/couchpotato
ProxyPassReverse /cp http://192.168.1.7:5050/couchpotato

## sickrage
ProxyPass /sickrage http://192.168.1.5:8081/sickrage
ProxyPassReverse /sickrage http://192.168.1.5:8081/sickrage
ProxyPass /sr http://192.168.1.5:8081/sickrage
ProxyPassReverse /sr http://192.168.1.5:8081/sickrage

## plexpy
ProxyPass /pp http://192.168.1.2:8181/plexpy
ProxyPassReverse /pp http://192.168.1.2:8181/plexpy
ProxyPass /plexpy http://192.168.1.2:8181/plexpy
ProxyPassReverse /plexpy http://192.168.1.2:8181/plexpy

## owncloud
ProxyPass /owncloud http://192.168.1.9/
ProxyPassReverse /owncloud http://192.168.1.9/
ProxyPass /oc http://192.168.1.9/
ProxyPassReverse /oc http://192.168.1.9/
</Virtualhost>

**Comment by StelArian** [comment]
Hello there!

Debian 9 installed following the guide. All good. I want to reverse proxy with Apache like...

`ProxyPass /plexpy http://127.0.0.1:8181/plexpy`
`ProxyPassReverse /plexpy http://127.0.0.1:8181/plexpy`

I see **NO** `config.ini` file inside `/opt/plexpy` in order to edit `http_root = /plexpy`, as described above.

Editing `/opt/plexpy/plexpy/config.py` as...

`'HTTP_PROXY': (int, 'General', 1),`
`'HTTP_ROOT': (str, 'General', 'plexpy'),`

...has no effect.

Is there a way to generate the `config.ini` file on Debian?

Thank you...

**Comment by zackbcom** [comment]
You might need to start plexpy for it to generate a config.ini file.
If you have it running, maybe try searching for the file: find -name "config.ini"

**Comment by JonnyWong16** [comment]
The base url setting is on the Web Interface tab in the settings.

**Comment by sophware** [comment]
After setting this, is plexpy only accessible via reverse proxy? My experience is that it is no longer accessible the old way. This causes a few issues.

**Comment by G4Zz0L1** [comment]
I've set HTTP Root and HTTP Proxy, and with the following mod_rewrite I get 404 from plexpy

```apache
    RewriteRule ^/plexpy$ https://weburl/plexpy/ [L,R=301]
    <Location /plexpy/>
        ProxyPass "http://localhost:8181/plexpy" connectiontimeout=5 timeout=30 keepalive=on
        ProxyPassReverse "http://localhost:8181/plexpy"
    </Location>
```
