### ISSUE TITLE
Duplicate libraries

### ISSUE THREAD

**Issue by p1r473** [Tautulli/Tautulli#491]
Hi, so my Libraries screen in PlexPy was showing double of every library! Is this a known issue?

So I deleted ALL the libraries in PlexPy. Now, they are not repopulating and I have tried refreshing libraries in both Plex and PlexPy. (this is issue #482... won't deal with that here).

Also to note: the libraries weren't deleted from plex (and the files weren't deleted from HD) when I deleted them in PlexPy. I hope this is working as intended, because if the PlexPy library view gets bugged, and I delete them from PlexPy, I dont want them deleted from Plex.

**Comment by p1r473** [comment]
Sorry, I realize this is a duplicate of issue #482
However, this ticket also contained the double libraries bug, and deleting libraries did not delete libraries in plex (bug or feature?) so let us make this ticket about these 2 issues now.

**Comment by JonnyWong16** [comment]
This looks like it's related to #469.

That is intended behaviour. A library refresh won't repopulate a deleted library in PlexPy.

For now, there is a hidden feature to re-add a delete library. Go to

```
http://localhost:8181/undelete_library?section_id=<section_id>
```

where `<section_id>` is the ID number for the library. You can find the section ID by looking at the very end URL of the library in Plex Web. It should look something like this

```
/server/<machine_identifier>/section/<section_id>
```

To help me fix this bug:
1. Are you on the `dev` or `master` branch?
2. Were you previously on `dev` (beta testing) then moved to `master`?
3. Could you PM me your `plexpy.db` file on the [forum](https://forums.plex.tv/profile/JonnyWong16)?

**Comment by p1r473** [comment]
Is it also intended that deleted the library in PlexPy doesn't delete the library in Plex?

Thanks for this hidden feature. (I'd recommend leaving it in... unless you plan to add it into the GUI.)

Also, for me, it wasn't the statistics that were duplicated, rather the libraries in the library list themself. In this picture, you can see each library is shown twice.
![image](https://cloud.githubusercontent.com/assets/9235633/12629870/af7ca466-c517-11e5-8c1c-40cd8107a7b9.png)

**Comment by JonnyWong16** [comment]
Yeah, I plan on adding the feature to the UI sometime.

Deleting in PlexPy will not delete in Plex. (That's just too dangerous)

I still think it's related to the other issue somehow. Can you still send me your `plexpy.db` file?

**Comment by p1r473** [comment]
Sure, can you give me your email?

**Comment by JonnyWong16** [comment]
Send it through a message on the [Plex forums](https://forums.plex.tv/profile/JonnyWong16).

**Comment by p1r473** [comment]
Hi, I sent you my DB.

I'm not sure if I had downloaded master or dev. I think I would have downloaded master. Its under drzoidberg33-plexpy-v1.3.3-0-g8902b93

I have not switched from one release to another. I downloaded a release last night. That release was showing up as "unknown version, please update", and so I had updated. But never switched branches.

Oddly enough, the the screenshot above, my last library, TV shows, has a different episode/count in the duplicate than the original. 527/529.

**Comment by JonnyWong16** [comment]
Thanks! I immediately found the bug. Are they still showing double in the table?

**Comment by p1r473** [comment]
Yes, still showing doubles (I have not made any changes to fix it)

**Comment by JonnyWong16** [comment]
I sent a fixed `plexpy.db` file back to you on the forum.

**Comment by geekcroft** [comment]
I also have this issue - I removed all libraries (and had to re-add them via the hidden URL). However just to add that the last library I added to plex (Added yesterday) ISNT duplicated.

I'll comment on both bugs related to this to hope it helps.

(Oh, and thanks for all your work on this - it's an awesome little app!)

EDIT: Also adding that doing this seems to have removed all my play history for the removed/re-added libraries :(

**Comment by JonnyWong16** [comment]
@geekcroft Can you also PM me your `plexpy.db` file on the forum? I want to see if its the same issue as @p1r473

**Comment by geekcroft** [comment]
@JonnyWong16 Sent you a link :)

**Comment by hoovdizz** [comment]
im also having this issue, started about 2 days after i switched from beta to master
i was able to see the Duplicate in the library_sections Table.
after i deleted it about a day later it came back, but this time they show as two different server ID's  Other than that they are identical.

**Comment by JonnyWong16** [comment]
Did you update the Plex server recently? Delete the rows in the `library_sections` table where the `server_id` **does not** match the `pms_identifier` in your `config.ini` file.

**Comment by hoovdizz** [comment]
2016-02-02 13:57:18 INFO    Writing configuration to file
2016-02-02 13:57:18 INFO    PlexPy PlexTV :: PMS identifier changed from 1e84e7XXXX to 66ffb7126XXXX.
2016-02-02 13:57:17 INFO    Writing configuration to file
2016-02-02 13:57:17 INFO    PlexPy PlexTV :: Requesting URLs for server...
2016-02-02 13:57:17 INFO    PlexPy is up to date

yet 1e84XXXXX  is my pms_identifier in the config.ini  and via  http://localhost:32400/identity?X-Plex-Token=<your_plex_token>

**Comment by JonnyWong16** [comment]
What about the `clientIdentifier` here?

```
https://plex.tv/api/resources?includeHttps=1
```

**Comment by hoovdizz** [comment]
if i delete the opposite way 
2016-02-02 14:10:29 INFO    Writing configuration to file
2016-02-02 14:10:29 INFO    PlexPy PlexTV :: PMS identifier changed from 66ffb71XXXX to 1e84e72d7XXXX.
2016-02-02 14:10:29 INFO    Writing configuration to file

i stopped it and wacked ALL the rows in Library_section

2016-02-02 14:14:10 INFO    Writing configuration to file
2016-02-02 14:14:10 INFO    PlexPy PlexTV :: PMS identifier changed from 1e84e72dXX to 66ffb7XXX.
2016-02-02 14:14:10 INFO    Writing configuration to file

no more duplicates, but the PMS_ID is wrong compared to the server,

it also seems to be doing a round robin on the PMS ID

**Comment by JonnyWong16** [comment]
So both of these show the `1e84e72dXX`?

```
http://localhost:32400/identity
https://plex.tv/api/resources?includeHttps=1
```

**Comment by hoovdizz** [comment]
http://localhost:32400/identity  = yes
https://plex.tv/api/resources?includeHttps=1  = yes

but now my config.ini shows 66ffb7XXX. due to the last start up

**Comment by JonnyWong16** [comment]
I forgot to "save" the config file after the ID change in the code. Just go to the settings and click "Save", then see if it changed in the config file.

**Comment by hoovdizz** [comment]
set config.ini to 1e84e72dXX saved.
opened the DB and deleted all records of library
started up plexpy
2016-02-02 14:38:17 INFO    PlexPy PlexTV :: PMS identifier changed from 1e84e7XXXX to 66ffb7XXX.
not sure where its pulling the 66ffb7XXX.

but since its loaded, (with no doubles) i saved all the settings via GUI. Restarted plexpy. 

2016-02-02 14:43:37 INFO    PlexPy PlexTV :: PMS identifier changed from 66ffb71XXXX to 1e84e72d7XXX.

back to doubles. rebooted again to test the round Robbin theory (no file alterations)

2016-02-02 14:46:00 INFO    PlexPy PlexTV :: PMS identifier changed from 1e84e7XXX to 66ffb71XXX.

so as long as there is no reboot we are good LOL. 

3rd reboot
2016-02-02 14:47:20 INFO    PlexPy PlexTV :: PMS identifier changed from 66ffb7126XXX to 1e84e72d7XXXX.

**Comment by JonnyWong16** [comment]
Ok wow lol. I'll have to look into this when I get home.

**Comment by hoovdizz** [comment]
i went digging for that 66FF i found it. 

`<Device` name="Xbox 360 (54B6F)" product="Plex for Xbox 360" productVersion="1.0.0.0" platform="Mystery 5" platformVersion="1.0.0.0" device="Xbox 360" clientIdentifier="66ffb7126e90XXX" createdAt="1452324161" lastSeenAt="1454433295" provides="player" owned="1" publicAddressMatches="1" presence="0">
<Connection protocol="http" address="192.168.0.11" port="32400" uri="http://192.168.0.11:32400" `local="1"/>`

ill have to check my network later to see whats up.

**Comment by JonnyWong16** [comment]
~~Where was the `66ffb71XXX`?~~

Posted before your edit.

Do your Plex server and the XBOX have the same IP and port listed?

**Comment by hoovdizz** [comment]
with my DHCP pool, i find it odd that they would, but i will double check when i get home, the Xbox isn't currently on right now So i am unable tell what IP its pulling. It is the main means of streaming, so if they did have the same IP i would have expected issues. 
i did how ever remove it from the list of devices. 

rebooted plexpy
2016-02-02 15:06:24 INFO    PlexPy PlexTV :: PMS identifier changed from 66ffb7126XXX to 1e84e72d7XXX.

2nd reboot. 
NO PMS ID change line !

shut down plexpy. 
deleted all the 66ff entries in the DB
started up Plexpy
no doubles, 
restarted plexpy just to double check
no doubles. 

so for some reason it saw my Xbox as the server. ... crazy. 

nothing like an over extended lunch break to troubleshoot. 

Thanks jonny.

**Comment by JonnyWong16** [comment]
Thanks, this info was really helpful. Let me know what your Xbox reports when you have a chance.

**Comment by hoovdizz** [comment]
ip address of xbox on local network is .21 

but on the https://plex.tv/api/resources?includeHttps=1 it shows as the same IP as my server. 
`<Device name="Xbox 360 (54B6F)" product="Plex for Xbox 360" productVersion="1.0.0.0" platform="Mystery 5" platformVersion="1.0.0.0" device="Xbox 360" clientIdentifier="66ffb7126XXX" createdAt="1454451831" lastSeenAt="1454452287" provides="player" owned="1" publicAddressMatches="1" presence="0">
<Connection protocol="http" address="192.168.0.11" port="32400" uri="http://192.168.0.11:32400" local="1"/>
</Device>`

after i started playing a show i rebooted plexpy

2016-02-02 17:32:52 INFO    PlexPy PlexTV :: PMS identifier changed from 1e84e72dXXXXX to 66ffbXXXXX

and we are back to duplicates

**Comment by JonnyWong16** [comment]
Thanks. I think I know how to fix it. 

It's weird that the it shows the same IP address on plex.tv though..

**Comment by hoovdizz** [comment]
glad i could help ! let me know if you need any more testing. 
be more than happy to switch over to DEV if need be.

**Comment by JonnyWong16** [comment]
1. Update PlexPy to v1.3.5.
2. Backup your `plexpy.db` file.
3. Go to `http://localhost:8181/delete_duplicate_libraries`
4. Hope I didn't screw up.

**Comment by hoovdizz** [comment]
That did it, it deleted the XBOX ID, 
I rebooted a few times just to make sure. 

Good job, hope it works for others as well :)

**Comment by fliiiix** [comment]
Yeah I can confirm that it worked. :+1: Good work!

**Comment by pducharme** [comment]
Thanks, the fix did work.

**Comment by wilcosec** [comment]
I have been experiencing this issue as well. The URL `http://localhost:8181/delete_duplicate_libraries` fixed it for me. Thanks!

**Comment by JonnyWong16** [comment]
Issue has been fixed in v1.3.5.

**Comment by rix1337** [comment]
This is working!

**Comment by AngryNoodlez** [comment]
Nice!

Jonny saves the day again, thanks for this fix - sorted my issue too when I recently had to rebuild my Plex server!

**Comment by EpicWolverine** [comment]
I just had this same issue (I think caused by having to reinstall PMS after a failed update) and going to `http://localhost:8181/delete_duplicate_libraries` fixed it for me as well. Thank you! This should probably be a button in settings somewhere through for the rare situation that this does happen.

**Comment by fleinbach** [comment]
Not sure if this is the right place if not just tell me where to post. I have 10 Libraries in my Plex database. Plexpy was showing all as duplicates. I went to Libraries in Plexpy and and selected a single library to delete the duplicate. Since it said it was permanent I decided to try just one of the duplicates to see what would happen before doing the rest. What happened supersized me. It removed both instances of the library I selected and all duplicate entries from the remaining 9 libraries.  

   Should that have happened?

  Is there any way to get back the now missing Library?

**Comment by JonnyWong16** [comment]
Read the FAQ please.

**Comment by fleinbach** [comment]
Thank you that put back the missing library. 

Is there any explanation for my other question. If not OK,  I thought it was strange removing one library removed all the other 9 library duplicates.

**Comment by JonnyWong16** [comment]
Was it 10 duplicates of the same library? The delete function works by removing libraries with the same `section_id` of the library (you can see the `section_id` in the URL of the library page).

**Comment by fleinbach** [comment]
No, There were 10 different Libraries each one having just one duplicate of it. When I deleted one of them, all the  remaining 9 libraries each having there own duplicate lost the duplicate.

**Comment by lastb0isct** [comment]
Anyway to get the history back after deleting the library?  I noticed two of each of my libraries and deleted what i thought would delete the duplicate.  Stupid of me, i know...

I was able to add the libraries back, but I can only see history up until about 10 months ago.

**Comment by JonnyWong16** [comment]
@lastb0isct Restore a backup db from the backups folder.

**Comment by lastb0isct** [comment]
@JonnyWong16 Thank you...i should have read the FAQ =/ sorry...
