### ISSUE TITLE
Wrong data in episode watch history

### ISSUE THREAD

**Issue by BuggeringHell** [Tautulli/Tautulli#495]
For certain episodes, incorrect watch history is displayed in the list. For example, the screenshot below even shows the incorrect thumbnail which is from a different series entirely.

Note: This data was imported from plexWatch

![plexpy](https://cloud.githubusercontent.com/assets/2572212/12634179/1d34a33a-c56f-11e5-8a3e-608cc71977b1.png)

**Comment by JonnyWong16** [comment]
Likely that the item was moved in Plex after plexwatch recorded the data. 

You should be able to use the "Fix Metadata" feature to correct it.
