### ISSUE TITLE
[Feature Request] Transcoding performance stats

### ISSUE THREAD

**Issue by bagobones** [Tautulli/Tautulli#496]
The plex server logs indicate the rate at which trans-coding is taking place. It would be nice to have a report or even an average for the server to know if it is keeping up, or to know what resolutions or codecs it is having trouble trans-coding.

**Comment by tripflex** [comment]
This would be great!  Would be even better if we could add Buffering stats as well which would help track down issues ... or potential issues before they arise 👍 

http://feathub.com/JonnyWong16/plexpy/+157
