### ISSUE TITLE
"Failed to retrieve image"

### ISSUE THREAD

**Issue by patschi** [Tautulli/Tautulli#5]
On the latest version (2aa833d) I'm getting the following errors in the terminal:

<pre>02-Jul-2015 17:33:45 - WARNING :: CP Server Thread-8 : Failed to retrieve image. Status code 500
02-Jul-2015 17:33:45 - WARNING :: CP Server Thread-8 : Image proxy queried but errors occured.</pre>

Also the picture of "Most Active User" on the website is just a placeholder picture.

**Comment by drzoidberg33** [comment]
Which operating system?

Are the items which thumbnails are failing still in your Plex library?

The user thumbs will pull from whatever is available, if you run a refresh users from the Users menu, it will pull the ones that Plex Web uses, if it cannot find one it just shows the default image.

**Comment by patschi** [comment]
> Which operating system?
> Ubuntu 14.04.01 LTS.
> 
> Are the items which thumbnails are failing still in your Plex library?
> Just the user pictures were empty; the media picture were available.

Just clicking on "Refresh users" fixed it. (I don't know why it didn't update automatically...) Before updating it worked, but after the update and the restart of PlexPy the image vanished. However, it seems to work again. Maybe it was because the recent PlexTv password reset...

However: Thank you for your fast response! :)
