### ISSUE TITLE
Feature Request: Disable stats function for PMS operator

### ISSUE THREAD

**Issue by happytrail** [Tautulli/Tautulli#50]
It would be nice if I could disable the stats/logs for my personal account.  

Having my plex user account listed along with the guest accounts throws off the recorded stats and trends, thus skewing the true data set.  I often repeatedly test videos that I remux and that leads to a lot of outlyer data generated by only my account.

Just think that would be a cool feature to be able to disable the stats for the 'admin' of the PMS.

Overall, a nice project you have going on here.  Highly appreciated.

**Comment by drzoidberg33** [comment]
Are you referring to the "Local" user (the account that doesn't require authentication) or is this just a normal Plex account?

**Comment by happytrail** [comment]
The Local user I guess is what it would be.  Basically I'm referring to the user that controls the administrator settings from the plex.tv web interface as well as, naturally, controlling the administrator settings in PlexPy.

I hope I'm making sense.  It's late and past my bedtime...

**Comment by drzoidberg33** [comment]
Well if it is the "Local" user then it will show up as "Local" user in PlexPy when you play something. If you see your own username there then it's not the Local account.

**Comment by happytrail** [comment]
Will it show as a “local user" if I’m using my “administrator” account through the roku plex app?

I assure that the account being tracked here is my “administrator” account that is exclusively in control of running the PMS as well as PlexPy.

What exactly is a “local” user then?

How about the feature to maybe just kill the stats of any particular user that logs into the PMS?  Maybe that would be the more beneficial route to explore in order to improve the availability to view the output of stats for particular PlexPy user while excluding other users.

Like I said, it’s late and past my bedtime.  If I’m not making rational sense, I’ll continue the conversation in the morning after my morning coffee.

**Comment by drzoidberg33** [comment]
Yes, it would make sense to just have a "do not monitor" flag per account.

I'll make this the feature request.

**Comment by happytrail** [comment]
Thank you very much for the quick interaction and responses.

I love this project of yours and am excited to be able to witness it grow and mature.

**Comment by drzoidberg33** [comment]
This has been pushed to the dev branch. Will probably get released in the next few days.

https://github.com/drzoidberg33/plexpy/commit/0877a6bf21ddf882d6c9fa687207e9bd7440e30f

**Comment by drzoidberg33** [comment]
Released in v1.1.0

https://github.com/drzoidberg33/plexpy/releases/tag/v1.1.0
