### ISSUE TITLE
script not running

### ISSUE THREAD

**Issue by naq90** [Tautulli/Tautulli#500]
@Hellowlol helped me out with creating a script that would throttle SABnzbd when somebody was streaming something on plex. The script however does not seem to work. I've attached a photo of my log file, script, and script notification settings. It seems like plexpy cannot find the script despite having it be selected in the drop down menu. 

[Log File](http://pastebin.com/Uw4khCLW)
[Script](http://pastebin.com/1865wpHH)
[Script Notification Settings](https://i.imgur.com/7Givgzo.png)

**Comment by JonnyWong16** [comment]
Is that the full path to the script folder? or a relative path?

**Comment by naq90** [comment]
I think that it's a relative path? I have PlexPy jail set up in freenas and storage mounted to that jail 
![screen shot 2016-01-30 at 6 39 20 pm](https://cloud.githubusercontent.com/assets/7684792/12699451/daba3966-c780-11e5-90a8-b62a94d0135b.png)
.

**Comment by JonnyWong16** [comment]
Try the full path and check the folder permissions.

**Comment by Hellowlol** [comment]
The script works just fine, just tested it. Python can't find the script. We should just find the abs path for the users. Or atlest try

**Comment by Hellowlol** [comment]
Thanks for the logs and screenshots! It helps when trying to figure out stuff like this.

**Comment by naq90** [comment]
I'm not sure if this is what you meant by absolute but I changed the destination to match the source, /mnt/nasa/misc and it still came up with the same error.

**Comment by JonnyWong16** [comment]
You can change it back to `/misc`.

What happens if you just type in `python /misc/scripts/throttle_nzbclient.py` in your jail shell?

**Comment by naq90** [comment]
root@plexpy:/ # python /misc/scripts/throttle_nzbclient.py
Traceback (most recent call last):
  File "/misc/scripts/throttle_nzbclient.py", line 29, in <module>
    import requests  # pip install requests
ImportError: No module named requests
root@plexpy:/ #

**Comment by naq90** [comment]
So python wasn't installed I guess, so I ran pkg install python and then ran the script again. Above is the error I got.

**Comment by JonnyWong16** [comment]
If you installed PlexPy using the wiki, then try `python2 /misc/scripts/throttle_nzbclient.py`.

Or in the jail shell:

```
pkg install py27-pip
pip install --upgrade pip
pip install requests
python /misc/scripts/throttle_nzbclient.py
```

**Comment by naq90** [comment]
I ran the pip install requests and then ran the command. However I a different error saying I needed to run pip install jsonrpclib-pelix. So I did that and viola it works! Thanks so much everybody for their help. 

I was wondering, however, @Hellowlol will this script also set the speed back to default when something is not streaming? So far I have it set to run when something starts and when something resumes.

**Comment by JonnyWong16** [comment]
Looking at the script, it looks like it only reduces the speed, but it's really easy to modify to make it set the speed back.

**Comment by naq90** [comment]
I apologize but I'm a bit new to the whole idea of scripting. In fact @Hellowlol wrote the script for me. Could you tell me what I would need to add so that it resumes once playback is stopped? I'd greatly appreciate it.

**Comment by Hellowlol** [comment]
The simple solution would be to have two scripts. Copy that script, change to value of reduce_speed_to 90% off your full speed and set plexpy to execute that script on playback stopped. I'll make it more advanced when i get access to a computer.

**Comment by Hellowlol** [comment]
I updated the script.
i would have using the {stream} argument

**Comment by naq90** [comment]
@Hellowlol, thanks again for your script. I'm not sure if I know how exactly to use your script with the new parameters. The old script ran perfect if there was only one stream however, if I had more than one stream going on I ran into a few issues.

My settings:
I have Plexpy throttle SAB on playback start and playback throttle.
I have Plexpy remove the SAB limit on playback pause or playback stop.

Now if I have a few streams going and a user pauses or stops playing SAB will go back to full speed regardless of if there are other users currently streaming something. Is there a way to check to make sure there are no current streams still playing before it unthrottles SAB?

Also, a side question. Is playback stop the same as finishing an episode/movie? Or does it only trigger when playback is stopped in the middle of the episode/movie?

Thanks again for all your help!

**Comment by Hellowlol** [comment]
There is a a scream count argument. So you could do something like:

-sc {streams} -s 100 -mts 2 -ms 10000

The script would then check if there are2 or more stream at the same time, reduce the speed to 100 kbs. if its less increase the speed to 10mbit
