### ISSUE TITLE
[Feature Request] Post Poster Image to Facebook

### ISSUE THREAD

**Issue by RichStevenson** [Tautulli/Tautulli#503]
I know the Facebook notification is experimental right now, but would it be possible to have a parameter that would upload the movie poster along with the notification?

**Comment by lucidonlinenet** [comment]
Second this enhancement request.  My family love the Facebook notification and having the movie/tv show poster would really improve the experience.

**Comment by After-Shock** [comment]
Also, designating a set image to post when the Server is down would also be beneficial.  Example:  Picture of Homer Simpson with a big "D'oh!!" when the server loses connection and is down, then a Woohoo!!! image once the server is back up.  Would save me from answering a lot of texts.  Great job Jonny thus far, been following since a little before you started on the project.

**Comment by JigSawFr** [comment]
As a media is correctly associated, we have some ID's from Plex as IMDB. So we can build image link from IMDB with media ID i think.

**Comment by peva3** [comment]
With the newest dev commits, some of my TV recently added items are getting posters when posted on my facebook group, but other aren't.

**Comment by Hellowlol** [comment]
Have you checked if that show has a image on tvmaze?

**Comment by peva3** [comment]
Seeing as most of my content is going to be anime, it would make more sense to pull it from thetvdb.

Or better yet, just pull the image that plex is using.

**Comment by Hellowlol** [comment]
I think he choose tvmaze since it the best solution. Its based on indexer api and with tvmaze your can search after tvrage, tvdbid and imdbid. It wouldnt be hard to add fallback to tvdb or imdb. I assume that would be done later.

**Comment by JonnyWong16** [comment]
I'm still playing around with this. ~~Currently movies use IMDB (if the Plex agent is Freebase) and TV Shows use TVMaze (if the Plex agent is TVDB). I chose these because they are easier and free to setup.~~

~~Other sources (like directly from TVDB) would require the user to setup their own API. Maybe that is the better solution?~~

~~I also can't pull the images directly from Plex because they are not publicly accessible by Facebook.~~ I would need to pull the image then reupload to Imgur or something before posting to Facebook. 

~~EDIT: I might be able to pull from Plex, but only if the server has remote access enabled.~~
EDIT2: I decided on uploading the Plex poster to Imgur.

**Comment by JonnyWong16** [comment]
Added in v1.3.7.

**Comment by JigSawFr** [comment]
@JonnyWong16 Thank you !

**Comment by zerolimit30** [comment]
don't see the Notification for imgur do you guys?

**Comment by JonnyWong16** [comment]
Settings > Notifications > Enable Posters in Notifications

**Comment by zerolimit30** [comment]
but how do you add it to imgur? I enable it but didn't see a poster added on my system

**Comment by JonnyWong16** [comment]
Imgur upload is automatic. The poster will show up in your Facebook posts.

If it doesn't, check your logs for Imgur errors.

**Comment by zerolimit30** [comment]
WARNING PlexPy Notifiers :: Error sending Facebook post: API calls from the server require an appsecret_proof argument I keep getting this

**Comment by JonnyWong16** [comment]
You didn't set up the Facebook agent properly. Did you follow all the steps? Did you received a "Key verification successful" message after you requested authorization?

**Comment by zerolimit30** [comment]
yes

**Comment by zerolimit30** [comment]
2016-02-22 22:25:44	INFO	Writing configuration to file
2016-02-22 22:25:43	INFO	PlexPy Notifiers :: Requesting access token from Facebook

**Comment by JonnyWong16** [comment]
You must have toggled some setting on your app's Facebook page. Is the following setting set to "No" in your Facebook app's advanced settings?

> Require App Secret
> Require app secret for server API calls

**Comment by zerolimit30** [comment]
ok now I am here ... "2016-02-22 22:44:44   WARNING PlexPy Notifiers :: Error sending Facebook post: (#200) The user hasn't authorized the application to perform this action"

**Comment by JonnyWong16** [comment]
Remove the app from your account (https://www.facebook.com/settings?tab=applications) and request authorization again.

**Comment by zerolimit30** [comment]
i did that and i still get the same msg. did it 5 times already!

**Comment by JonnyWong16** [comment]
Did you change the permissions when you allowed PlexPy to access your Facebook?

**Comment by zerolimit30** [comment]
no nothing has changed. trust me I did exactly as its telling me

http://imgur.com/bvIuUnn

**Comment by JonnyWong16** [comment]
"Embedded Browser OAuth Login" should be set to "No".

And I was referring to the permission window when you click "Request Authorization".

**Comment by zerolimit30** [comment]
ok I changed it to "No" and yes I get "Key verification successful, PlexPy can send notification to Facebook. You may close this page now."

**Comment by zerolimit30** [comment]
2016-02-23 19:28:23 WARNING PlexPy Notifiers :: Error sending Facebook post: (#200) The user hasn't authorized the application to perform this action
2016-02-23 19:28:23 INFO    Writing configuration to file
2016-02-23 19:28:23 DEBUG   Sending test Facebook notification.
2016-02-23 19:25:57 DEBUG   PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 370
2016-02-23 19:25:57 DEBUG   PlexPy Monitor :: Removing sessionKey 78 ratingKey 370 from session queue

**Comment by JonnyWong16** [comment]
Did you change this permission? It needs to be "Public" or "Friends". It can't be "Only Me".

![](http://i.imgur.com/QtxBC7a.png)

**Comment by zerolimit30** [comment]
it was under me only but change it to "Friends"

016-02-23 19:44:13  WARNING PlexPy Notifiers :: Error sending Facebook post: (#200) The user hasn't authorized the application to perform this action

**Comment by JonnyWong16** [comment]
Did you remove the app and re authorize as "Friends"?

**Comment by zerolimit30** [comment]
yes and redid everything.

**Comment by JonnyWong16** [comment]
I'm out of ideas. It works for me and a lot of other people.

**Comment by zerolimit30** [comment]
thanks for your help! I really appreciate it!!!!

**Comment by zerolimit30** [comment]
I got twitter to work but its not posting posters :(

**Comment by JonnyWong16** [comment]
There are no posters for twitter. Only the `{poster_url}` if you use that option. And > Notifications > Enable Posters in Notifications is checked.

**Comment by roelbeun** [comment]
Feature is working great, thanks. Quick question, is it possible to not let it show things related to Plex? I now see on Facebook : view in plex Web. 

Dunno if it's wise to post things like that on Facebook. Any thoughts?

**Comment by TheDogg** [comment]
I have enabled the poster to imgur but I dont see the poster on facebook (enabled for FB also).

Version 1.3.14

Here is what's displayed in the logs:

`2016-03-31 15:06:49 - ERROR   :: Thread-28 : PlexPy Notifier :: Unable to retrieve poster for rating_key 333: [Errno 2] The system cannot find the path specified: '\\library\\metadata\\333\\thumb\\1459451140?X-Plex-Token=********tU'.`

any idea why i'm getting this?

I see the poster just fine in both Plex and PlexPy, just not in notifications

**Comment by JonnyWong16** [comment]
Do you have a `pms_url` in your `config.ini` file?

Can you view the poster from

```
http://<plex_ip>:32400/library/metadata/333/thumb/1459451140?X-Plex-Token=<your_pms_token>
```

or just

```
http://<plex_ip>:32400/library/metadata/333/thumb?X-Plex-Token=<your_pms_token>
```

**Comment by TheDogg** [comment]
> Do you have a pms_url in your config.ini file?

it's empty.  do I put `http://<plex_ip>:32400/` in it?

**Comment by JonnyWong16** [comment]
PlexPy should grab it automatically. What are your settings for your Plex Media Server?
- Hostname (localhost, local ip, remote ip)?
- Port
- Remote Server
- Use SSL

**Comment by TheDogg** [comment]
- Hostname: 127.0.0.1
- Port:32400
- Remote Server OFF (server is local)
- Use SSL ON

everytime I put a value in the config.ini it get erased by plexpy.

**Comment by JonnyWong16** [comment]
Restart PlexPy then post your logs to [pastebin](http://pastebin.com).

**Comment by TheDogg** [comment]
http://pastebin.com/x0Jfnz79

**Comment by JonnyWong16** [comment]
PlexPy is having troubles getting your `pms_url`. What is your "Secure connections" setting in Plex (disabled, preferred, required)? Are you using your own SSL certificate/key for Plex?

**Comment by TheDogg** [comment]
Secure Connections is set to Prefered

Im not using my own SSL certificate

**Comment by TheDogg** [comment]
I just disabled the "Use SSL" checkbox and I got the pms_url populated in the config.ini

and now the covers are working.

Any idea why SSL wont work?  Ill try on my other plex server to see if I can reproduce it

**Comment by JonnyWong16** [comment]
Check the `uri` under your server's `<Connection>` in these locations. Specifically the one with `local="1"`.

```
https://plex.tv/api/resources?includeHttps=1
https://plex.tv/api/resources
```

The first link is where PlexPy checks if you have SSL checked, the second is where it checks without SSL checked.

If you do not have SSL checked, the `uri` should be `http://<local_ip>:32400`.
If you have SSL checked, the `uri` should be `http://<ip>.<hash>.plex.direct:32400`

**Comment by TheDogg** [comment]
I have values for both and they are valid.

One thing i noticed is that for this specific server, I do not have the entry with  `local=1` but I do have it for my other servers.

thanks for all this live help btw ;)

**Comment by JonnyWong16** [comment]
> One thing i noticed is that for this specific server, I do not have the entry with local=1 but I do have it for my other servers.

That's probably why it's failing to grab the url. I don't know why that is missing though.

**Comment by TheDogg** [comment]
I just enabled the manual port for plex and now plex reports 

Private Unknown IP  <- Public xx.xx.xx.xx : 32400 <-   Internet

I will have to look in to this issue.  

thanks for all your help, at least I got it working by disabling SSL.

**Comment by JonnyWong16** [comment]
No problem. Next time [Gitter](https://gitter.im/drzoidberg33/plexpy) is probably quicker for back and forth.

**Comment by lpreams** [comment]
It would be cool if poster images could be posted to Twitter as well. There is an API for uploading media https://dev.twitter.com/rest/reference/post/media/upload

**Comment by mikeymatrix70** [comment]
Is there a trick to making this work with Music? I get the posters for Movies but Music shows blank image with the link of https://raw.githubusercontent.com/JonnyWong16/plexpy/master/data/interfaces/default/images/cover.png
