### ISSUE TITLE
[Feature Request] Expand all TV shows

### ISSUE THREAD

**Issue by haboutnnah** [Tautulli/Tautulli#504]

**Comment by drzoidberg33** [comment]
Care to elaborate?

**Comment by Hellowlol** [comment]
I believe he's refering to expanding all the tvshows in the library page.

**Comment by haboutnnah** [comment]
I am indeed referring to expanding all tvshows on the library page.

**Comment by sltyler1** [comment]
such as being able to see the entire library?
