### ISSUE TITLE
[Feature Request] The ability to customize git command for checkout

### ISSUE THREAD

**Issue by MikeDawg** [Tautulli/Tautulli#505]
It would be a nice "advanced" option, if the server admin, had the ability to customize the git pull command, which is used to update plexpy.

Purely out of (bad?) habit, I fork repositories, and pull from my newly created repository. Therefore, in order to update, I need to sync the fork, with my repo, and then attempt to pull the latest version of plexpy. If I had the ability to run a 'git pull upstream master' as opposed to 'git pull origin master' it would help me, and others that use git the same way, that I do.

**Comment by Hellowlol** [comment]
I agree on the bad part :p

**Comment by MikeDawg** [comment]
So, for projects that are in a near-constant state of development, why is it bad practice to fork repos (and contribute, when I have the ability/skills to)?

**Comment by Hellowlol** [comment]
I'm not saying you shouldn't contribute, quite the contrary. I send some prs from time to time to. It just seems like your making stuff harder then it is. I'm just using two seperate folders one is a clone and one is a "fork". Then I don't have to mess with stuff like that

**Comment by MikeDawg** [comment]
So, I'm not being defensive about my use of git; but maybe I'm looking for some tips and advice.

But even, as if its a developer option, to be able to do, what I said in the first post, would help/assist in the development, of plexpy, wouldn't it?

**Comment by Hellowlol** [comment]
I personally don't think so, however adding support for this would be a tiny, tiny addition it's like 3 lines of code. If that would make people contribute more then yes. 

Your should edit the header since what you really want is to pull from upstream not checkout anything.
