### ISSUE TITLE
[Feature Request] Seperate FireTV devices and Android devices

### ISSUE THREAD

**Issue by ItTakesTwo** [Tautulli/Tautulli#508]
On the PlexPy dashboard the Most Active Platform includes FireTV devices (FireTV Stick aswell as the FireTV itself) into Android devices. I know that the FireTV hardware runs a modified Android version but for detailed statistics it would be nice to seperate these devices from each other just like the Chromecast is, too.

Thoughts on that?

**Comment by JonnyWong16** [comment]
If that's how Plex reports the platform, then that's how it gets grouped.

"Platform" and "Player" are different. The homepage groups by platform and the user page groups by player.

**Comment by ItTakesTwo** [comment]
Oh. I see the difference between player and platform now that you point it out.
Well then I guess we can consider this case closed.

Thanks!
