### ISSUE TITLE
Parameters not being pulled

### ISSUE THREAD

**Issue by RichStevenson** [Tautulli/Tautulli#509]
Playing with the 'Recently Added' notification, and it doesn't appear that it's pulling all of the parameters.
Attached is the content of the email notification that contains all of the parameters, and the XML for the show from Plex. I was looking specifically at the season and episode parameters when I noticed the issue, but it looks like it's missing others as well.

[PlexShow.txt](https://github.com/drzoidberg33/plexpy/files/114061/PlexShow.txt)
[EmailNotification.txt](https://github.com/drzoidberg33/plexpy/files/114062/EmailNotification.txt)

**Comment by JonnyWong16** [comment]
#440
