### ISSUE TITLE
New notification agent: Telegram Bot - feature request

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#51]
There seems to be a project where plex can interact with telegram. I would be nice if it can be integrated

The user needs to create his own bot and generate his personal telegram token

https://github.com/brownsmart/telegram-plexbot
https://forums.plex.tv/discussion/176090/new-app-telegrambot-plex-api#latest

Thank you for looking into it !

**Comment by elRadix** [comment]
@drzoidberg33 @JonnyWong16 @Hellowlol 

There is a simple script created by a user to send telegram notifications
https://gist.github.com/matriphe/9a51169508f266d97313

you only need a userid and a botkey, can you integrate this ?

would be also nice to send a cover of movie/serie optionally ...

**Comment by onedr0p** [comment]
This has been implemented in the pull request below.

**Comment by elRadix** [comment]
would it be possible to add sending the cover photo of the media from plex to your telegram bot ?
you can do this in the Notification string substitutions, so that each user can choose what he wants to add.

**Comment by JonnyWong16** [comment]
Telegram added in v1.2.4.

Request for posters in notifications in #273.
