### ISSUE TITLE
[Feature Request] Graph showing added media

### ISSUE THREAD

**Issue by mattman86** [Tautulli/Tautulli#512]
Perhaps you could add a graph showing media that has been added over time.

**Comment by Arcanemagus** [comment]
Are you thinking the total number of items each period, or the number of items _added_ in the last monitoring period?

**Comment by mattman86** [comment]
Last monitoring period I suppose. I'm thinking something like the 'Daily Play Count' graph except as a 'Daily Added Count'. Does that make sense?
