### ISSUE TITLE
[Feature Request] User Login / Plex Token / User Graph

### ISSUE THREAD

**Issue by m1e1w1** [Tautulli/Tautulli#513]
Similar to #382 and #197 

A feature that would authenticate users who are shared with a Plex Media Server using your PMS token;
Graphs only the logged in users retentive information / watched history etc. (not editable)
Admin login shows all information collected. (editable) (normal plexpy view) (required to use plex token for individual user login)

**Comment by JonnyWong16** [comment]
Please comment on similar existing feature requests instead of creating a new one. Thanks.
