### ISSUE TITLE
[Feature Request] IMDB Link available for Notifications

### ISSUE THREAD

**Issue by mcqweb** [Tautulli/Tautulli#514]
I've just started using the facebook notification and it's brilliant but the page ends up like a wall of text. Would it be possible to pass the IMDB link for Movies and TVDB for TV (Or ID so we can make the link).

It looks like the IMDB link is in the XML under GUID
eg 

guid="com.plexapp.agents.imdb://tt2024544?lang=en"
guid="com.plexapp.agents.thetvdb://79488/1/1?lang=en"

**Comment by spuniun** [comment]
This would be huge

**Comment by JonnyWong16** [comment]
Added in v1.3.7.

**Comment by LwsBtlr** [comment]
feeling really dumb, but is the IMDB link feature ONLY for movies? I'd like to link the TV shows to IMDB as well.

**Comment by JonnyWong16** [comment]
I haven't tested it, but it might work if you have "The Movie Database" as your TV Show agent instead of "TheTVDB".
