### ISSUE TITLE
Error Notifications - Version 1.3.5

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#515]
Hi,

The minutes are reported incorrectly and I  got error message in the log, can you pls check

**input**
- Length:  {duration} mins 
- Unwatched:  {remaining_duration} min. or {progress_percent}% 

**output**
- Length: 5916918 mins 
- Unwatched: 60 min. or 39% 

**error log**

> Uncaught exception: Traceback (most recent call last):
> File "/opt/plexpy/plexpy/logger.py", line 221, in new_run
> old_run(_args, *_kwargs)
> File "/usr/lib/python2.7/threading.py", line 763, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "/opt/plexpy/plexpy/notification_handler.py", line 64, in notify
> notify_strings = build_notify_text(session=stream_data, state=notify_action)
> File "/opt/plexpy/plexpy/notification_handler.py", line 452, in build_notify_text
> helpers.cast_to_float(session.get('paused_counter', 0)))
> File "/opt/plexpy/plexpy/helpers.py", line 386, in cast_to_float
> return float(s)
> TypeError: float() argument must be a string or a number

**Comment by an3k** [comment]
{duration} is now in milliseconds. Ruvetuve as well as I have experienced the same bug.

**Comment by Hellowlol** [comment]
The duration from pms is now in ms?

**Comment by an3k** [comment]
PMS still shows the correct duration in minutes (Plex clients) but PlexPy is now (since the last update) showing ms instead of mins

**Comment by Hellowlol** [comment]
Ok, found it now. https://github.com/drzoidberg33/plexpy/commit/3248e6500e8043f5165160dd458032fdbd3f462d#diff-3ce0c9e407297279b309aa70a0f237a3R455

Thanks

**Comment by roelbeun** [comment]
thanks for making the report @elRadix

PlexPy and PMS shows the correct duration in minutes. Only not in the {duration} parameter.

**Comment by elRadix** [comment]
Has the update been pushed already ?

**Comment by JonnyWong16** [comment]
My bad... >.<

**Comment by Hellowlol** [comment]
Wtf the millisecond duration isn't used its the one from the metadata unless I'm reading this wrong. That isn't unlikely since I'm on my phone..

**Comment by JonnyWong16** [comment]
Yeah I accidentally used `metadata['duration']` instead of `duration`.

**Comment by JonnyWong16** [comment]
@Hellowlol Check my commit ~~78c8bfdbaeb6378d61e4d8381eb23c80e4bbb116~~ 0b301fff3ffbfe5f39a61269ceac084b3bcf948d

**Comment by roelbeun** [comment]
Would be great to fix this asap :)

**Comment by Hellowlol** [comment]
I think it's fixed already.

**Comment by JonnyWong16** [comment]
Fixed in v1.3.6.
