### ISSUE TITLE
[Feature Request] Capability to display specific element of plexpy in Wordpress Widget

### ISSUE THREAD

**Issue by niwrik** [Tautulli/Tautulli#516]
I would like to be able to display recent releases as you have them laid out in a Wordpress Widget.  I'm wondering if it may be possible to use an iFrame and imbed an anchor in the <div> for now, but ultimately it would be awesome to have a few of the key areas of the plexpy available for embedding in other sites...like a blog.

Thanks!

**Comment by JonnyWong16** [comment]
The is probably something that can be created by yourself using the API.

(The API is currently in limbo right now though.)
