### ISSUE TITLE
No logging in 1.3.5

### ISSUE THREAD

**Issue by universelover4** [Tautulli/Tautulli#517]
Plexpy is not logging anything, no history is showing up, only what is currently being watched and that is it. Running version 1.3.5

Error log: 
03-Feb-2016 10:20:49 - WARNING :: CP Server Thread-2 : Failed to access uri endpoint /servers/**_(server number removed)**_/sync_lists. Status code 401
03-Feb-2016 10:20:49 - WARNING :: CP Server Thread-2 : PlexPy PlexTV :: Unable to parse XML for get_synced_items: must be string or read-only buffer, not None
03-Feb-2016 10:20:49 - WARNING :: CP Server Thread-2 : Unable to retrieve data for get_sync.

Things i have tried:
Ctrl+F5 on the user list page.
checking the http_handler timeout is set to 20
setting cert_verify_ssl to 0
Running cacls /g everyone:f on plexpy.py  to try and fix permissions
checked and unchecked forceSSL
deleting plexpy.db
reinstalling plexpy
installing plexpy on different drives
enabling websocket

so far no luck, any suggestions?

**Comment by JonnyWong16** [comment]
Please use the search function next time. Post in #484 with your COMPLETE logs.

**Comment by universelover4** [comment]
i did and i had seen that post, i have tried what is listed and it did not work.
