### ISSUE TITLE
[Feature Request]  Date/Time column added to Synched Items Tab

### ISSUE THREAD

**Issue by hoopdeetoo** [Tautulli/Tautulli#518]
Please add date/time column in synched items tab so we can sort by most recently synched files.
thanks so much!!!

**Comment by JonnyWong16** [comment]
Sorry, this isn't possible. Sync time isn't reported by the Plex API.

**Comment by hoopdeetoo** [comment]
Thank you. What about just date?

**Comment by JonnyWong16** [comment]
Neither date nor time is reported.

**Comment by hoopdeetoo** [comment]
Thanks very much for your reply

**Comment by drzoidberg33** [comment]
@JonnyWong16 This is possible, but you have to call the data for each individual sync item also, e.g. http://127.0.0.1:32400/sync/items/123456

**Comment by JonnyWong16** [comment]
Ah, that `addedAt` time is for the sync, not for adding to the library. Thanks!

**Comment by hoopdeetoo** [comment]
This would be awesome! Thanks for getting it on the enhancement list!  Much appreciated.

**Comment by JonnyWong16** [comment]
Wait, no it's not. `addedAt` still isn't sync time. Unless I'm missing something...
