### ISSUE TITLE
[Feature Request] Notifications based on Devices/Players

### ISSUE THREAD

**Issue by triney37** [Tautulli/Tautulli#520]
Would like the ability to assign notifications based on the device being used. Currently I use the scripts notification to turn off my main lights and turn on my Hue lights, in the living room. Would like the ability to specify a different set of scripts to run if I'm watching media in the bedroom. The living room uses a Roku and the Bedroom uses an amazon fire. This could be done by allowing notifications to be set up on a per device/player basis.

**Comment by JonnyWong16** [comment]
Why not let your script handle this by passing the `{player}` argument to your script?

```
if player = "Roku":
    run these commands
elif player = "Fire TV":
   run these other commands
```

(Note to self: Add `machine_id` to notification options)

**Comment by triney37** [comment]
Because I'm new at this, and I don't know how to do that. My script doesn't
have a way (yet) right now when I start playing media, it fires off the
script notification which fires off a batch file that turns off my Wemo
lights and on my Hue lights. I'll have to do a lot of research to see how
to add that to the batch file it runs. Is that possible?

**Comment by JonnyWong16** [comment]
It's a good time to learn. :)

So your chain right now is PlexPy > "Script" > Batch file?

Then it should be really easy to add the if/else statements to the "Script" to fire off different batch files. Let us know what language is the script written in and we can help.

**Comment by triney37** [comment]
I'm looking into it now, thanks for the advice.
Here is my bat file. it's very basic I just started doing this the other
day. What I would like for it to do is look at this if it's player1 and or
maybe have another section for it to goto if it's player2.

:wemo
set PATH=C:\cygwin\bin;%PATH%
c:\cygwin\bin\sh.exe c:\cygwin\home\triney\wemo.sh 192.168.1.138 OFF
goto hue

:hue
set PATH=C:\cygwin\bin;%PATH%
c:\cygwin\bin\sh.exe c:\cygwin\home\triney\hue_on.sh

**Comment by JonnyWong16** [comment]
Ok, you need something to handle the batch files (to determine which batch file to run).

Here is an example in Python.

```
import sys
import subprocess

player = sys.argv[1]

if player == "player1": 
    subprocess.call("player1.bat")
elif player == "player2":
    subprocess.call("player2.bat")
```

Or if you prefer all in a batch file (I think, I don't know batch)

```
set player=%1

IF %player% == "player1" (
    do something here
) ELSE IF %player% == "player2" (
    do something else here
}
```

**Comment by triney37** [comment]
Awesome I'll take that and run with it thanks!

**Comment by triney37** [comment]
Next question I'm gong to try to do the batch file, in hopes of cutting
down on delay. If i'm using using {player} in the argument  will that set
the %1 in that script you gave me? Also is there a way to make plexpy
recognize when  media has started and stopped sooner? right now I have
about a 2 minute delay before the script is launched.

**Comment by JonnyWong16** [comment]
Yes, `{player}` will be the first argument.

You can try enabling websockets. That should trigger events instantaneously.

**Comment by triney37** [comment]
Thanks for all your help I've just about got it figured out I just have one
more question. If my player name has a space in it, will the argument have
a space in it. The device in question is "My AFTB" how will the argument
come across? Does that make sense? I'm not sure how my script will handle
the space, it gives me an error right now when I put a space in.

**Comment by Hellowlol** [comment]
Post your script and your error.

**Comment by triney37** [comment]
Thanks I've got most of it figured out, the last part is trying to figure
out how the notification argument will come over if the player has a space
in the name? Any ideas?

**Comment by JonnyWong16** [comment]
A space should be fine. The argument will just be passed to your batch file as "My AFTB"

**Comment by triney37** [comment]
Thanks I didn't know if it would come over with the "" that takes care of
my problem I think I've got the script written, and I'll test it out when I
get home. Thank You for all your help!

**Comment by JonnyWong16** [comment]
Oh, it won't have the quotes. Just `My AFTB`. You can compare the player name as normal.

```
IF %player% == "My AFTB"
```

If you want to be more exact (or in case the player name changes), I've added `machine_id` to the dev branch, so you can compare:

```
IF %machineid% == "XXXXXXXXXX"
```

It will be on the master branch in the next update.

**Comment by triney37** [comment]
Ok so that's going to be my problem. when I run the script with out the
quotes it just uses the MY off of MY AFTB as the variable.

**Comment by JonnyWong16** [comment]
PlexPy is intelligent enough to pass `My AFTB` as one argument for the automatic triggers. You shouldn't need any special handling for the spaces. If you are running the batch file manually (i.e. from the command line or using "Test Scripts" in PlexPy), then you need to quote it first.

**Comment by triney37** [comment]
Ok awesome, well thank you for all your help, I'll try it when I get home.
