### ISSUE TITLE
[Feature Request] Notify when [user/users/anyone] watches [movie/show/season/episode]

### ISSUE THREAD

**Issue by deepseth** [Tautulli/Tautulli#521]
"Notify me when [user/users/any] watches this [movie/tv show/season/episode]"
Would be a wonderful feature to add to know when a friend has seen a show and you can talk about it without spoilers. Or share memorable quotes.

**Comment by JonnyWong16** [comment]
This seems like a very specific feature. Probably best handled with a custom script.

**Comment by deepseth** [comment]
Yep, could totally be scripted manually under the current interface, for each specific movie/show/season/episode and user/users/anyone combination, set a bunch of conditionals in a script, looking up the IDs manually and then filling it out accordingly...

...or if it was an option when browsing through watch history on plexpy, noticing that you're up to date on a show but your friends aren't, and can easily click and select a bunch of users... given that plexpy already has the IDs for movie/show/season/episode and users related to your account/server.... ;D

**Comment by Hellowlol** [comment]
So your to lazy to script it and think its "easier" to just add it to plexpy since it already has the data? :P

**Comment by JonnyWong16** [comment]
I can assure you that adding it to PlexPy is going to be a lot more work than writing a short script.

Sorry, for bashing on your request, but the whole point of adding the Script notifier was for things like this, It takes some load off us so we can focus our efforts on other features which can't be implemented in an external script.

(You can write a script that adds a button to the info pages which then adds the ID to some text file that's read by the script.)

**Comment by Arcanemagus** [comment]
@deepseth never said it would be easy to add to PlexPy, just that it would be easy to use _once in there_. That being said, this is relatively simple to do in a script and would be quite the undertaking to add to PlexPy itself.

**Comment by Hellowlol** [comment]
True, maybe it was the "tone" and all the dotdotdots that threw me off :), Shit maybe im having a bad day :D

**Comment by deepseth** [comment]
Totally valid, I have no idea how much work it'll be to actually implement within the app, I'm looking at this purely from an end-user usability POV.

It sounds like it's going to be too much work to implement this as a point-and-click function within the app, and given that there's a scripting framework in place to cover this already, I'm happy to accept 'wontfix'.

Thanks for taking the time to consider and for the feedback.

**Comment by Hellowlol** [comment]
@deepseth I can help you out as long its a python script. Let me know if you need any assistance

**Comment by deepseth** [comment]
@Hellowlol Thanks, appreciate the offer. I will post a link to a gist at the weekend once I've had some time to write something.
