### ISSUE TITLE
Feature: Track Plex Channel Views

### ISSUE THREAD

**Issue by neebski** [Tautulli/Tautulli#522]
Took a look for this in the issue tracker didn't see anything. Currently, I have HDHR Viewer channel installed on my server in order to view live TV via my HDHomeRun. Plays do show up in PlexPy as "playing" but is not actually saved in the history or under the user statistics. Not sure if this is by design but I'd love to track this information as well. ESP since my kids will view their live TV this way and I can see how many hours they have viewed!

Thanks a bunch!

**Comment by JonnyWong16** [comment]
This has been discussed before. "Clips" (videos from Plex channels) don't report enough session/metadata info for logging. We can show current activity on the homepage, but history won't be logged.

**Comment by neebski** [comment]
That's too bad, can't use just generic data for the missing pieces? From the now playing it's showing a lot of information. Just not a cover photo and no information regarding the clip like year/actors/description/etc. Everything important is there though, transcoder decision/audio and video details/current minute count/etc. A lot of good information for  aggregate statistics for users.

Just my two cents ;)

**Comment by JamminR** [comment]
I may have been one of the original requesters of this in the Plex forum Plexpy topic.
I still agree in wanting this feature, clip monitoring would be great.
Even if it's a simple "username" "clip name or URL" transcode/directplay/what device/when it started, could easily dummy the completion data, since it's not recorded in Plex I presume for direct play.

**Comment by login4me** [comment]
Would love this too... I do not get "activity" of HDHR channel on the PlexPy home screen. I checked setting... am I missing something? Thanks for PlexPy... absolutely fabulous!

**Comment by JonnyWong16** [comment]
And you've just discovered one of the reasons why PlexPy doesn't track channel views.

If it doesn't show up on Plex Web's now playing page, then it won't show up on PlexPy's current activity.

**Comment by kelemvor33** [comment]
Just found out about PlexPy a couple days ago and wanted something that would also track Channels.  We use the HGTV and Food Network Channels to watch show episodes and I was hoping to be able to view a history of what was watched and when.  Even if it had a way of saying that an episode was viewed starting at a certain time, that'd be something.

But I don't know how all this work behind the scenes so I'm assuming it's not possible?  :(

**Comment by katar25** [comment]
can add option to iptv?

**Comment by brianmxwll** [comment]
Just tossing a +1 for this request. Even a minimum amount of tracking would be useful here. WRT HDHomeRun, even specific channel tracking isn't needed. It would just be helpful to know how often the Plex Transcoder is burning on watching live TV.

**Comment by katar25** [comment]
v2 is support iptv??? any improvement??

**Comment by chasgames** [comment]
+1

**Comment by azinck** [comment]
@JonnyWong16 You state "If it doesn't show up on Plex Web's now playing page, then it won't show up on PlexPy's current activity."...but *both* live TV watching activity as well as watching streaming video via channel plugins (such as ABC or CBS) do show up in Plex Web's "Now Playing" page as well as on the PlexPy interface.  They're just not logged to the history.  I'd second the request to at least put in some dummy placeholder metadata where it's missing and log these to the history.

I know different people have different needs, but for what it's worth, live TV and channel plugins are the 2 primary uses of my Plex server, so it's really disappointing not to have either of these uses reflected in PlexPy somehow.

I also want to add that I know how much thankless effort it is to maintain open source software and I want to thank you for PlexPy -- it's a highly-featured, well-built tool!
