### ISSUE TITLE
Illegal cookie name _pk_id.1.0528

### ISSUE THREAD

**Issue by pkkid** [Tautulli/Tautulli#523]
I hit this twice over the past couple days. After I delete the cookies in my browser the page loads fine. perhaps an upstream bug, but filing it here.

```
400 Bad Request
Illegal cookie name _pk_id.1.0528
Traceback (most recent call last):
  File "/home/mjs7231/Sources/plexpy/lib/cherrypy/_cprequest.py", line 635, in respond
    self.process_headers()
  File "/home/mjs7231/Sources/plexpy/lib/cherrypy/_cprequest.py", line 737, in process_headers
    raise cherrypy.HTTPError(400, msg)
HTTPError: (400, 'Illegal cookie name _pk_id.1.0528')
```

**Comment by danmazzella** [comment]
Out of curiousity, are you running PlexWatch as well?

I was having the exact same issue, it's been about a week without an issue and I believe only two things changed. I shut down PlexWatch and also I am now using a domain name rather than my IP address.

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/issues/453
