### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by crack00r** [Tautulli/Tautulli#525]
Maybe someone know some help?

> 2016-02-05 02:17:49   INFO    PlexPy PlexTV :: Requesting users list refresh...
> 2016-02-05 01:46:11   WARNING Unable to retrieve data for get_sync.
> 2016-02-05 01:46:11   WARNING PlexPy PlexTV :: Unable to parse XML for get_synced_items.
> 2016-02-05 01:45:42   INFO    Writing configuration to file
> 2016-02-05 01:41:45   WARNING Unable to retrieve data for get_user_player_stats.
> 2016-02-05 01:41:45   WARNING Unable to retrieve data for get_user_recently_watched.
> 2016-02-05 01:22:59   WARNING Unable to retrieve data for get_library_user_stats.
> 2016-02-05 01:22:59   WARNING Unable to retrieve data for get_library_recently_watched.
> 2016-02-05 01:22:35   WARNING Unable to retrieve data for get_sync.
> 2016-02-05 01:22:35   WARNING PlexPy PlexTV :: Unable to parse XML for get_synced_items.
> 2016-02-05 01:22:29   INFO    Writing configuration to file

**Comment by JonnyWong16** [comment]
See https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#cat1-q7

(Look @an3k I used the wiki!)

**Comment by crack00r** [comment]
thx, and sorry :)
