### ISSUE TITLE
Local bind to real user

### ISSUE THREAD

**Issue by crack00r** [Tautulli/Tautulli#526]
I enabled history for local too, like DLNA etc, but log tells me
2016-02-06 13:02:40 DEBUG   PlexPy ActivityProcessor :: History logging for user 'Local' is disabled.

Can you kmay add a  option to bind "local" to a real user?
I think local is everything that will played per dlna, but all my dlna´s in my house are used by my account, so it would be cool if you may add a option that i can bind local history to an real user in the user-list

**Comment by JonnyWong16** [comment]
Do you have history enabled for the Local user? Users > Edit mode > Toggle History?

**Comment by crack00r** [comment]
yes, its enabled.

**Comment by JonnyWong16** [comment]
And DLNA is not logged, by the way. It's not possible.
