### ISSUE TITLE
[Feature Request] Notifications via Hangouts

### ISSUE THREAD

**Issue by digiblur** [Tautulli/Tautulli#527]
It would be great if it Plexpy could integrate itself as a bot in a Hangouts chat and post notifications of various events to a chat.  That way different users could see them on their phones/devices.  

I did find this when searching for a way to send messages.  https://github.com/hangoutsbot/hangoutsbot

**Comment by Arcanemagus** [comment]
This will probably be best handled by a script notification.

**Comment by digiblur** [comment]
Any thoughts on where to look for a script to send text to a chat?

**Comment by Arcanemagus** [comment]
Something that translates the notification information from PlexPy to the format `hangoutsbot` understands?

If you were looking to just message individual people you could use any XMPP library to do so, but if you want group support you need something that has reverse engineered the Hangouts protocol as they still don't have an API for that that I know of.

**Comment by Hellowlol** [comment]
https://github.com/tdryer/hangups

**Comment by digiblur** [comment]
Thanks but it doesn't look straight forward for now. Maybe things will get easier one day to just run a command to drop a message in a group hangout chat. Would be pretty sweet to have your share users in there.

**Comment by calvinbrown085** [comment]
Just an FYI, Google is dropping support for hangouts, when re-reading this ticket maybe integration into their new chat system would be good? @JonnyWong16 @digiblur

**Comment by digiblur** [comment]
Dropping support of hangouts?  I believe you are mistaken.  There is a different direction for Allo but Hangouts will be around for quite sometime.

**Comment by calvinbrown085** [comment]
@digiblur Ah, apologies, I didn't realize the difference.
