### ISSUE TITLE
Feature Request: Import viewing history from server

### ISSUE THREAD

**Issue by Omicron-five** [Tautulli/Tautulli#53]
You can see the entire viewing history of a plex server at `localhost:32400/status/sessions/history/all`. Can we import this into this app?

**Comment by drzoidberg33** [comment]
I didn't even know this existed. However there is one big problem with the data which makes it unsuitable to import and that is that it has no end time.

There is only a viewedAt key which is not enough information to build the data we need.

**Comment by Omicron-five** [comment]
@drzoidberg33 Can you not get the metadata for each item and then get the length and calculate the finish time by assuming they watched it in one go? It'd be a very slow import process but it would work.

**Comment by drzoidberg33** [comment]
@Omicron-five 

Nope, that would be just be horribly inaccurate. Those stats also don't include any stream data so i have no idea if it was transcoded, direct played, etc.

**Comment by Omicron-five** [comment]
I see, thanks.
