### ISSUE TITLE
Movie not registered as completely played.

### ISSUE THREAD

**Issue by gardinerbk** [Tautulli/Tautulli#530]
During a viewing where the user stop playing and then continued playing the movie was not registered as completely played in the total instance. However it was registered as completely watched in one of the sub-instances. See image for more details.
![bug](https://cloud.githubusercontent.com/assets/15112109/12875264/78490534-cde6-11e5-90ff-ffbe37c7e10b.PNG)

**Comment by JonnyWong16** [comment]
Is it possible that in the second instance the movie was viewed from an earlier point in the movie?

What is the percentage that shows up when you hover over the dots?

**Comment by gardinerbk** [comment]
Its 97% for the full dot and 12% for the other dots. I'm not sure if it was viewed from an earlier point, and I'll have trouble figuring that out. It was my mom who watched it and she most likely has already forgotten if she did :P.

**Comment by JonnyWong16** [comment]
I'm going to assume that's what happened then. The watched percent is just calculated as the point where you stop the movie / the total duration of the movie.

**Comment by Magikarplvl4** [comment]
Have the same problem

**Comment by gardinerbk** [comment]
But shouldn't it then still register the movie as watched?

**Comment by JonnyWong16** [comment]
The grouped line in the table takes the most recent stream, which in this case is the 2nd one at 12%

**Comment by Arcanemagus** [comment]
Shouldn't the group take the min starting point and the max end point?

**Comment by JonnyWong16** [comment]
It should probably take the highest percent in the group.

**Comment by gardinerbk** [comment]
Okay thanks! I would delete the 12% entry would it then take the 97% one?

**Comment by JonnyWong16** [comment]
Yeah

**Comment by JonnyWong16** [comment]
This should be fixed in v1.3.7.
