### ISSUE TITLE
Incorrect season/episode info being reported in notifications for recently added.

### ISSUE THREAD

**Issue by zprewitt** [Tautulli/Tautulli#531]
I'm using this code:

`<tv>Season {season_num} Episode {episode_num} of</tv> {title} <movie>({year})</movie> was recently added to Plex.`

And getting this info:

Season 0 Episode 1 of Portlandia was recently added to Plex.

Haven't seen a movie notification yet, but I suspect it will work fine. Expecting correct season and episode, as well as episode name. Can someone show me where I went wrong?

Thanks!

**Comment by drzoidberg33** [comment]
You probably have **Group notifications for recently added TV Shows or Music** enabled right?

If so, read the help block underneath:

> Enable to only get one TV Show or Artist notification for a batch of recently added Episodes or Tracks. Movies are unaffected.
> Note: No Season/Episode or Album/Track metadata will be available.

**Comment by zprewitt** [comment]
Ahh, that's probably it. Thanks!
