### ISSUE TITLE
Formatting options for notifications?

### ISSUE THREAD

**Issue by zprewitt** [Tautulli/Tautulli#532]
I would like to include parameters for various movie metadata in my FB notifications (cast/crew, summary, rating), but it doesn't look like I have any formatting options so it's all just lumped together in one paragraph. Is it possible to add basic HTML code to the message body to break it up as well as add bold and italics? Sorry if this has been addressed previously, I couldn't find anything in search.

**Comment by JonnyWong16** [comment]
Currently, line breaks do work. No HTML support yet.

**Comment by zprewitt** [comment]
Great, thanks!

**Comment by JigSawFr** [comment]
@zprewitt We can format messages on Facebook ?

I've done this for my facebook notifications if you want: https://github.com/drzoidberg33/plexpy/pull/419#issuecomment-174225159
