### ISSUE TITLE
{stream_duration} tag is always 0

### ISSUE THREAD

**Issue by bowlingbeeg** [Tautulli/Tautulli#533]
Since I updated to 1.3.5 the {stream_duration} value is always zero.  To verify I went back to 1.3.4 and it worked just fine so something in 1.3.5 seems to have broken it.  Not sure what kind of debug you need but it happened to both of my plexpy installations so it seems like you should be able to reproduce it in your environment.  I'm running plexpy on Win 7 and Win 10.

**Comment by ZeroFlame007** [comment]
This is also happening on mine as well. Win 7, Plex and PlexPy run on same box

**Comment by JonnyWong16** [comment]
Fixed in v1.3.7.
