### ISSUE TITLE
Feature: Manually change Timezone/Time within PlexPy

### ISSUE THREAD

**Issue by LennyM8472** [Tautulli/Tautulli#534]
Hi,

it would be great if someone can change the time and timezone within PlexPy manually.
Default is GMT or UTC it seems. As I'm running PlexPy as a docker container the timezone is not correctly recognized - thus running on default timezone.

thanks
Lenny

**Comment by MACwayne** [comment]
+1

**Comment by x-limitless-x** [comment]
+1

**Comment by x-limitless-x** [comment]
Pasting a supposed answer from another post, located here:
[FeatHub](http://feathub.com/drzoidberg33/plexpy/+53)

> _JamminR commented:_
> You already CAN set timezone offsets manually. Plexpy - Settings - Time format - Click here for parameter list Click the link that says Timezone ZZ UTC offset E.g. +0100, -0700 Z UTC offset E.g. +01:00, -07:00
> 
> Also, this isn't a Plexpy issue - you should research if there's a way to set docker timezones to match your actual one.

**Comment by marksuman** [comment]
That is not a way to set the timezone offset, but rather have the offset displayed in the UI. Right?

The time zone in the History is correct.  The graphs; however, are displayed with UTC. It would be awesome if those respected the timezone of the timestamp.
