### ISSUE TITLE
TV Notifications occurring even though Enable TV Notifications Unselected

### ISSUE THREAD

**Issue by mjn138** [Tautulli/Tautulli#536]
During one of the recent updates, PlexPy has started sending notifications for new TV shows, even though the "Enable TV Shows Notifications" box is unselected.  This didn't occur in the past, so I'm guessing it's related to one of the updates.  I've try unselecting, reselecting the box, as well as restarting the service.

If you need any debugging information, screenshots, etc, let me know.

I use Boxcar2 and Email for notifications, and both are set to "Notify on recently added".

**Comment by Hellowlol** [comment]
You should just post the full log so the devs has something to work with :)

**Comment by JonnyWong16** [comment]
This functionality was changed in v1.3.4. Recently added notifications can be controlled per library now instead of globally by media type. (Libraries > Edit mode > Toggle recently added)

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/default.js#L20 Not sure if this is the best method, but its the one im using.

**Comment by mjn138** [comment]
Thanks Jonny.  Not sure how I missed that, but that's useful.  Sorry for the unnecessary "bug" report.
