### ISSUE TITLE
Add a check to include/exclude data on graphs based on libraries present.

### ISSUE THREAD

**Issue by mattman86** [Tautulli/Tautulli#537]
Perhaps you could add a check in the graphs to take an inventory of the types of libraries or media present on the server and display only relevant data on the graph. For example, I have libraries for both movies and TV shows but not for music. When I go to the graphs section, I see data for music that is consistently 0 on all graphs.

**Comment by JonnyWong16** [comment]
If you _uncheck_ "Enable Music Logging" in the settings, the music line on the graphs is hidden.

(Only the music logging checkbox does this, movies and tv shows are not affected.)

**Comment by mattman86** [comment]
Good to know. Thank you.
