### ISSUE TITLE
Stats on Optimization

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#538]
It would be great to see current optimization queues, how many shows in each waiting to be done, how many shows done, break down of conversion speed, conversions/day, etc.

Though this info may not be available [since the plex interface is sparse on info]. Thanks!

**Comment by Hellowlol** [comment]
We can find info here: http://127.0.0.1:32400/status/sessions/background

**Comment by ghost** [comment]
Easy way to access this with a cloud hosted server? 

Also, nice to have the data in plexpy for reporting/graphing.

**Comment by ghost** [comment]
I usually access my server through Plex.tx/web,wheni sub in my domain for 127.0.0.1 I get "This Web page is not available".

**Comment by edddeduck** [comment]
This would be very useful to show when thumbnails for example are bring generated. Plex actually doesn't have any UI for this so you have to look at logs or just notice your CPU being pegged at 100%.
