### ISSUE TITLE
Feature Request Notification Tab..

### ISSUE THREAD

**Issue by chuckkay** [Tautulli/Tautulli#539]
I send my Plexpy notifications to Pushover (finally go it  working - I had the 2 API Keys reversed)... 

I customized my notifications so they look nice simple in 'Pushover' and give me a brief overview of whats been happening on my PLEX SERVER...

But unfortunately things are not so simple to see on the PlexPY history tab, or Log screen..

Can you add a PlexPy as its own Notification Agent, so Notifications show up on the Plexpy Portal Somewhere Perhaps on the dashboard or on an Activity Tab..

![2016-02-12 14 33 23](https://cloud.githubusercontent.com/assets/10617746/13018094/c37679c6-d195-11e5-8129-5355898e3b08.png)

**Comment by JonnyWong16** [comment]
Added a notification log table in v1.3.8.
