### ISSUE TITLE
[Create styled HTML login page] Allow password to be saved by browsers

### ISSUE THREAD

**Issue by alexandrupaulpopa** [Tautulli/Tautulli#54]
Hi,

Can you please allow password to be saved by browsers, it would make the login in process just a bit easier

THanks

**Comment by drzoidberg33** [comment]
I'm guessing you mean you want a HTML login page? Currently authentication is just using HTTP Basic auth which will use your browsers pop-up to get the username and password.

**Comment by alexandrupaulpopa** [comment]
Thats exactly it. Thanks

**Comment by alexandrupaulpopa** [comment]
any updates on this issue?

**Comment by JonnyWong16** [comment]
I tried. Didn't work. Got confused. Gave up.

If anyone else attempts this, I have the html login template made. :stuck_out_tongue:

**Comment by drzoidberg33** [comment]
Hehe, thanks Jonny :smile:

I'll give it a go when I have some time.

**Comment by alexandrupaulpopa** [comment]
Updates?

**Comment by drzoidberg33** [comment]
Nobody has had time to work on this yet as far as I'm aware.

**Comment by Hellowlol** [comment]
@JonnyWong16 can you send me the login screen in a gist?
@drzoidberg33 
I also have question how we should handle this. 
Should the users be added manually. Picked from the friends list? 
Should the views be limited in any way only admin as access to settings?
Should there be a restricted user limited to only see page xxx?

**Comment by JonnyWong16** [comment]
You''ll have to wait until January. I'm on vacation and I don't have access to my computer.

**Comment by drzoidberg33** [comment]
You and me both :christmas_tree:

**Comment by Hellowlol** [comment]
Np, no rush.

**Comment by jkaberg** [comment]
> Should the users be added manually. Picked from the friends list? 

Friends list, eg. only users invited to browse the server are able to login

> Should the views be limited in any way only admin as access to settings?

Admin/Owner only for settings

> Should there be a restricted user limited to only see page xxx?

Yes, or well I don't want to see users being able to see other users activity etc. Privacy concerns you know. Only the owner should be able to see the activity of all users

my 2 cents :-)

**Comment by Hellowlol** [comment]
1. Easy
2. Easy
3. There is no way i can do this. My sql sucks.

**Comment by jkaberg** [comment]
I don't know about cherrpy but if in flask (with flask-security) you can implement decorators for each view, eg

```
@requires_admin
def setttings_page():
    pass

@login_required
def recent_activity_page():
    pass
```

You can also use the same in the html, eg.(requires a proper modell)

```
{% if current_user.is_admin %}
 html goes here
{% end if %}
```

Perhaps cherrypy has something like this?

**Comment by Hellowlol** [comment]
Yeah, you can see how I use it htpc manager. It's a decorator just like flask.  Dunno is use can use it in the HTML as I have never tried that. The problem will be the awl as the decorator just makes that unreachable. 

We would have to rewrite a lot of sql.

**Comment by JonnyWong16** [comment]
I agree that one (non-admin) user should only be able to see their own history, but I don't want to rewrite all the SQL queries so that it only show one users history. There has to be a more elegant way to achieve this.

**Comment by Hellowlol** [comment]
If the user name exist in the data we can simply use a list comprehension to filter out everything that isn't related to that user.

**Comment by JonnyWong16** [comment]
@Hellowlol Here is the html page and additional css for the login page:
https://gist.github.com/JonnyWong16/9fab990a65b3f16ec459

**Comment by vortexrap** [comment]
chiming in to say this would be greatly appreciated! Sonarr has the option for basic http auth (what plexpy is currently), as well as form view. Maybe check out their github and see their implementation?

Thanks for all the hard work!

**Comment by Hellowlol** [comment]
@drzoidberg33 @JonnyWong16 
So i started on this, im unsure how to handle the users. Should we use the users from the users table?
How where/should we edit the users? What i have started on now does nothing regarding the data. It will only protect pages.

**Comment by JonnyWong16** [comment]
Let's just change add the admin login for now. We can deal with individual user login/guest view later. Unless it's easier to do it all at the same time?

**Comment by Hellowlol** [comment]
Not really, access to different pages in only a different decorator. I could use some help with the sql since im awefull. 

We need 3 more cols in the user table, password, session_id, last_login.

**Comment by JonnyWong16** [comment]
But changing all the SQL queries based on user is going to be a huge pain.

What are the three columns used for?

**Comment by Hellowlol** [comment]
password, sessionid from cherrypy and last_login to expire cookies.
Im not gonna change any sql. Some body else has to do that :P 

Yeah.. I was thinking a decorator that filters the output or sqlstuff, and/or in the templates. Best solution would be template and sql. We dont have to do that now.

**Comment by JonnyWong16** [comment]
For the "password", can we grab tokens using the user's Plex login?

I can work on the SQL once you have something.

**Comment by Hellowlol** [comment]
I don't think that is listed anywhere.

**Comment by JonnyWong16** [comment]
I believe PlexRequests fetches tokens from the Plex login.

**Comment by JonnyWong16** [comment]
Added in v1.4.0.
