### ISSUE TITLE
[Feature Request] Monitor media availability, notify on unavailable

### ISSUE THREAD

**Issue by ameswarb** [Tautulli/Tautulli#545]
I sometimes have an issue where my network shares decide to unmount themselves or my OS forgets their authentication credentials. Under these circumstances, the Plex server will still appear to be up to plexpy, but the server itself will be ultimately useless to clients.

It would be nice if plexpy could allow either the admin to specify a list of plex media UUIDs to track availability status, or to have the monitor randomly jump around selected media libraries' items and notify on unavailability.

**Comment by Hellowlol** [comment]
I think you should fix your issue with your computer or write a script that checks this for you and run it in a cron. This seems like a small use case. 

Then again I'm not the dev they might think this a super awesome. Imo it's a bit off plexpys domain.

**Comment by JonnyWong16** [comment]
Sorry, I'm with @Hellowlol on this one.
