### ISSUE TITLE
Pushbullet/email notifications problem

### ISSUE THREAD

**Issue by lazyb0nes** [Tautulli/Tautulli#546]
Hey there, first of all i have to thank you for a really good application!, but ive run into some issues, I have setup email notifications and Pushbullet but it seems to only be able to send me the test notifications/email, which is really confusing since I have set the progress to 50% and I have also enabled notifications for movies/seris/music so it should mail me then?

I am probb just missing here but I thought id post anyway

Kind Regards

**Comment by JonnyWong16** [comment]
Looks like you found the solution on the Plex forum thread.
