### ISSUE TITLE
New to plexpy, hardly anything updates after using

### ISSUE THREAD

**Issue by gimp1124** [Tautulli/Tautulli#547]
so i followed the walk thru and everything looks awesome except almost nothing updates as being watched. My dad shows having watched something 17 days ago (he uses it daily), and 1 friend shows a movie a few weeks ago, but even all of my daily stuff doesnt update. Icurrently have about 10 shares and I know people have at least watched SOMETHING.  Ive made sure ip logging is clicked and i have the logs entered at "c:\users\my name\appdata\local\plex media server\logs". What am i missing? I did have plexwatch enabled first and hated it so maybe that jamming it up somehow?

**Comment by JonnyWong16** [comment]
From [README.md](https://github.com/drzoidberg33/plexpy/blob/master/README.md).
1. Make sure you provide the following information:
   - [x] Branch
   - [x] Version/Commit hash
   - [x] Your operating system and python version
   - [ ] What you did?
   - [X] What happened?
   - [X] What you expected?
   - [ ] How can we reproduce your issue?
   - [X] What are your (relevant) settings?
   - [x] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

**Comment by gimp1124** [comment]
So I see you checked 3 of those boxes so Ill only answer those. I followed the walk through install correcty (i assume). I'm on Win7, plexpy 1.3.6, plex port is 32400 and the log files are in "c:\users\brian\appdata\local\plex media server\logs". What other pertinent setting info do you need? sorry new at this. I expected to see all my shares and what theyre watching etc. I see all the user names but only my dads tv and my 1 friends tv have anything posted and its weeks ago. I use it daily as do other friends

**Comment by JonnyWong16** [comment]
Sorry, checked means you provided it. I need the unchecked info. Log file is in the folder `logs/plexpy.log`

**Comment by gimp1124** [comment]
oh ok sorry, would you like me to copy / paste the entire log?

**Comment by gimp1124** [comment]
also not sure what a branch is

**Comment by JonnyWong16** [comment]
> Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

If you don't know the branch, then it's probably `master`.

**Comment by gimp1124** [comment]
<script src="//pastebin.com/embed_js/fz5EWSq2"></script>

**Comment by gimp1124** [comment]
<script src="//pastebin.com/embed_js/eqvLcPBr"></script>

**Comment by gimp1124** [comment]
<iframe src="//pastebin.com/embed_iframe/eqvLcPBr" style="border:none;width:100%"></iframe>

**Comment by gimp1124** [comment]
`<script src="https://gist.github.com/gimp1124/827739e466d48efac444.js"></script>`

**Comment by gimp1124** [comment]
that deosnt seem to be readable,ill try again shortly thanks

**Comment by JonnyWong16** [comment]
Um..all you have to do is open the `plexpy.log` file, copy and paste everything into a new [Gist](https://gist.github.com/), then paste the URL here.

Also, you can edit your comment using the pencil icon.

**Comment by gimp1124** [comment]
https://gist.github.com/gimp1124/4f44d98271954d0d70f3#file-gistfile1-txt

thanks for your help

**Comment by JonnyWong16** [comment]
Looks like PlexPy is losing connection with your Plex server earlier, but it looks like the most recent sessions were recorded to your history properly.

Is your Plex server on the same machine as PlexPy? What are your Plex Media Server settings in PlexPy?

**Comment by gimp1124** [comment]
while talking to you yesterday i realized i might be sharing the wrong log folder for PMS logs. Upon changing that I have seen stuff start appearing on my plexpy (stuff ive watched here). Now i guess the best bet might be wait for a friend to stream something as well. PMS on same machine as plexpy, Under PMS settings on plexpy i have my ip, port as 32400, the 2 boxes for remote unchecked, and the folder location for logs as stated in first post

**Comment by gimp1124** [comment]
ok so as of now the status is all of my rokus/players are showing up, no one elses. if that makes sense

**Comment by JonnyWong16** [comment]
So it's only working for you, but not other people? Post your logs again.

**Comment by gimp1124** [comment]
https://gist.github.com/gimp1124/88a2ff5f722c07e99597

**Comment by gimp1124** [comment]
Someones viewing showed up today (he watched it tuesday night). I checked it yesterday and had  nothing. Worst case if we cant figure it out then this will do i guess. thanks again for all your help

**Comment by JonnyWong16** [comment]
Everything looks like it's working fine. Just a couple notes on how PlexPy works.

History is only logged:
- After the stream is stopped.
- If the total stream duration is longer than the "Ignore interval" you set in the settings.
- If "Keep History" for the user is enabled (Users > Edit Mode > Toggle Keep History)
- If "Keep History" for the library is enabled (Libraries > Edit Mode > Toggle Keep History)

If all those conditions are satisfied, then everything should be working.

**Comment by gimp1124** [comment]
great thanks. im going to go and change those settings now

**Comment by JonnyWong16** [comment]
Assume resolved? Comment again if you still need help.
