### ISSUE TITLE
[QNAP SSL cert issues] User screen throws AJAX eror

### ISSUE THREAD

**Issue by zenjabba** [Tautulli/Tautulli#55]
When selecting the User tab, AJAX error is thrown.

<img width="1666" alt="screen shot 2015-08-12 at 2 11 45 pm" src="https://cloud.githubusercontent.com/assets/679864/9232540/41c6fc22-40fc-11e5-8699-9e31037fcdef.png">

**Comment by drzoidberg33** [comment]
I think there is a deeper problem here (as per your other post).

Please post your full PlexPy logs.

**Comment by zenjabba** [comment]
[/opt/plexpy/logs] # more plexpy.log 
12-Aug-2015 13:50:33 - INFO    :: MainThread : Checking to see if the database has all tables....
12-Aug-2015 13:50:34 - DEBUG   :: MainThread : Generating UUID...
12-Aug-2015 13:50:34 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 13:50:34 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 13:50:34 - DEBUG   :: MainThread : Git output: a039641aba69b9d09aaebdb7f177567cd383c9e8
12-Aug-2015 13:50:34 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 13:50:34 - DEBUG   :: MainThread : Git output: master
12-Aug-2015 13:50:34 - INFO    :: MainThread : Retrieving latest version information from GitHub
12-Aug-2015 13:50:34 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
12-Aug-2015 13:50:34 - ERROR   :: MainThread : Unable to connect to remote host because of a SSL error. It is likely that your system cannot verify the validityof the certificate. The remote certificate is either self-signed, or the remote server uses SNI. See the wiki for more information on this topic.
12-Aug-2015 13:50:34 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?
12-Aug-2015 13:50:34 - INFO    :: MainThread : Starting PlexPy web server on http://0.0.0.0:8181/
12-Aug-2015 13:50:35 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
12-Aug-2015 13:51:23 - INFO    :: CP Server Thread-11 : Writing configuration to file
12-Aug-2015 13:51:23 - INFO    :: CP Server Thread-11 : Scheduled background task: Refresh Plex Server URLs
12-Aug-2015 13:51:23 - INFO    :: CP Server Thread-11 : Scheduled background task: Check for active sessions
12-Aug-2015 13:51:23 - INFO    :: CP Server Thread-11 : Scheduled background task: Refresh users list
12-Aug-2015 13:51:23 - INFO    :: CP Server Thread-11 : Requesting URLs for server...
12-Aug-2015 13:51:23 - INFO    :: CP Server Thread-11 : Writing configuration to file
12-Aug-2015 13:51:23 - INFO    :: CP Server Thread-11 : Writing configuration to file
12-Aug-2015 13:51:23 - INFO    :: Thread-12 : Requesting users list refresh...
12-Aug-2015 13:51:28 - INFO    :: Thread-12 : Users list refreshed.
12-Aug-2015 13:51:49 - INFO    :: Thread-13 : Requesting users list refresh...
12-Aug-2015 13:51:49 - INFO    :: CP Server Thread-2 : Manual user list refresh requested.
12-Aug-2015 13:51:52 - INFO    :: Thread-13 : Users list refreshed.
12-Aug-2015 13:53:34 - INFO    :: CP Server Thread-10 : Writing configuration to file
12-Aug-2015 13:53:34 - INFO    :: CP Server Thread-10 : Re-scheduled background task: Check for active sessions
12-Aug-2015 13:53:34 - INFO    :: CP Server Thread-10 : Requesting URLs for server...
12-Aug-2015 13:53:34 - INFO    :: CP Server Thread-10 : Writing configuration to file
12-Aug-2015 13:53:34 - INFO    :: CP Server Thread-10 : Writing configuration to file
12-Aug-2015 13:53:35 - INFO    :: Thread-24 : Requesting users list refresh...
12-Aug-2015 13:53:38 - INFO    :: Thread-24 : Users list refreshed.
12-Aug-2015 13:53:54 - INFO    :: CP Server Thread-8 : Retrieving latest version information from GitHub
12-Aug-2015 13:53:54 - DEBUG   :: CP Server Thread-8 : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
12-Aug-2015 13:53:54 - ERROR   :: CP Server Thread-8 : Unable to connect to remote host because of a SSL error. It is likely that your system cannot verify the validityof the certificate. The remote certificate is either self-signed, or the remote server uses SNI. See the wiki for more information on this topic.
12-Aug-2015 13:53:54 - WARNING :: CP Server Thread-8 : Could not get the latest version from GitHub. Are you running a local development version?
12-Aug-2015 13:54:35 - DEBUG   :: Thread-14 : PlexPy Monitor :: Removing sessionKey 103 ratingKey 49148 from session queue
12-Aug-2015 13:54:37 - DEBUG   :: Thread-14 : PlexPy Monitor :: Fetching metadata for item ratingKey 49148
12-Aug-2015 13:59:34 - DEBUG   :: Thread-22 : PlexPy Monitor :: Removing sessionKey 91 ratingKey 48269 from session queue
12-Aug-2015 13:59:34 - DEBUG   :: Thread-22 : PlexPy Monitor :: Fetching metadata for item ratingKey 48269
12-Aug-2015 14:00:34 - DEBUG   :: Thread-30 : PlexPy Monitor :: Removing sessionKey 102 ratingKey 1686 from session queue
12-Aug-2015 14:00:35 - DEBUG   :: Thread-30 : PlexPy Monitor :: Fetching metadata for item ratingKey 1686
12-Aug-2015 14:03:34 - DEBUG   :: Thread-14 : PlexPy Monitor :: Removing sessionKey 109 ratingKey 33489 from session queue
12-Aug-2015 14:03:35 - DEBUG   :: Thread-14 : PlexPy Monitor :: Play duration for ratingKey 33489 is 61 secs which is less than 120 seconds, so we're not logging it.
12-Aug-2015 14:04:06 - INFO    :: MainThread : Signal 2 caught, saving and exiting...
12-Aug-2015 14:04:06 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 14:04:06 - INFO    :: MainThread : PlexPy is shutting down...
12-Aug-2015 14:04:17 - INFO    :: MainThread : Checking to see if the database has all tables....
12-Aug-2015 14:04:17 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 14:04:17 - DEBUG   :: MainThread : Git output: a039641aba69b9d09aaebdb7f177567cd383c9e8
12-Aug-2015 14:04:17 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 14:04:17 - DEBUG   :: MainThread : Git output: master
12-Aug-2015 14:04:17 - INFO    :: MainThread : Retrieving latest version information from GitHub
12-Aug-2015 14:04:17 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
12-Aug-2015 14:04:17 - ERROR   :: MainThread : Unable to connect to remote host because of a SSL error. It is likely that your system cannot verify the validityof the certificate. The remote certificate is either self-signed, or the remote server uses SNI. See the wiki for more information on this topic.
12-Aug-2015 14:04:17 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?
12-Aug-2015 14:04:17 - INFO    :: MainThread : Requesting URLs for server...
12-Aug-2015 14:04:17 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 14:04:17 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 14:04:17 - INFO    :: MainThread : Requesting users list refresh...
12-Aug-2015 14:04:24 - INFO    :: MainThread : Users list refreshed.
12-Aug-2015 14:04:24 - INFO    :: MainThread : Starting PlexPy web server on http://0.0.0.0:8181/
12-Aug-2015 14:04:24 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
12-Aug-2015 14:04:24 - INFO    :: MainThread : Scheduled background task: Refresh Plex Server URLs
12-Aug-2015 14:04:24 - INFO    :: MainThread : Scheduled background task: Check for active sessions
12-Aug-2015 14:04:24 - INFO    :: MainThread : Scheduled background task: Refresh users list
12-Aug-2015 14:05:24 - DEBUG   :: Thread-12 : PlexPy Monitor :: Removing sessionKey 99 ratingKey 33489 from session queue
12-Aug-2015 14:05:26 - DEBUG   :: Thread-12 : PlexPy Monitor :: Fetching metadata for item ratingKey 33489
12-Aug-2015 14:05:26 - DEBUG   :: Thread-12 : PlexPy Monitor :: Removing sessionKey 92 ratingKey 49897 from session queue
12-Aug-2015 14:05:28 - DEBUG   :: Thread-12 : PlexPy Monitor :: Fetching metadata for item ratingKey 49897
12-Aug-2015 14:07:24 - DEBUG   :: Thread-16 : PlexPy Monitor :: Removing sessionKey 114 ratingKey 49148 from session queue
12-Aug-2015 14:07:25 - DEBUG   :: Thread-16 : PlexPy Monitor :: Fetching metadata for item ratingKey 49148
12-Aug-2015 14:07:25 - DEBUG   :: Thread-16 : PlexPy Monitor :: Removing sessionKey 126 ratingKey 33489 from session queue
12-Aug-2015 14:07:25 - DEBUG   :: Thread-16 : PlexPy Monitor :: Play duration for ratingKey 33489 is 61 secs which is less than 120 seconds, so we're not logging it.
12-Aug-2015 14:08:12 - INFO    :: MainThread : Signal 2 caught, saving and exiting...
12-Aug-2015 14:08:12 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 14:08:12 - INFO    :: MainThread : PlexPy is shutting down...
12-Aug-2015 14:09:56 - INFO    :: MainThread : Checking to see if the database has all tables....
12-Aug-2015 14:09:56 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 14:09:56 - DEBUG   :: MainThread : Git output: a039641aba69b9d09aaebdb7f177567cd383c9e8
12-Aug-2015 14:09:56 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 14:09:56 - DEBUG   :: MainThread : Git output: master
12-Aug-2015 14:09:56 - INFO    :: MainThread : Retrieving latest version information from GitHub
12-Aug-2015 14:09:56 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
12-Aug-2015 14:09:57 - ERROR   :: MainThread : Unable to connect to remote host because of a SSL error. It is likely that your system cannot verify the validityof the certificate. The remote certificate is either self-signed, or the remote server uses SNI. See the wiki for more information on this topic.
12-Aug-2015 14:09:57 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?
12-Aug-2015 14:09:57 - INFO    :: MainThread : Requesting URLs for server...
12-Aug-2015 14:09:57 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 14:09:57 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 14:09:57 - INFO    :: MainThread : Requesting users list refresh...
12-Aug-2015 14:10:00 - INFO    :: MainThread : Users list refreshed.
12-Aug-2015 14:10:00 - INFO    :: MainThread : Starting PlexPy web server on http://0.0.0.0:8181/
12-Aug-2015 14:10:00 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
12-Aug-2015 14:10:00 - INFO    :: MainThread : Scheduled background task: Refresh Plex Server URLs
12-Aug-2015 14:10:00 - INFO    :: MainThread : Scheduled background task: Check for active sessions
12-Aug-2015 14:10:00 - INFO    :: MainThread : Scheduled background task: Refresh users list
12-Aug-2015 14:16:00 - DEBUG   :: Thread-14 : PlexPy Monitor :: Removing sessionKey 131 ratingKey 49148 from session queue
12-Aug-2015 14:16:00 - DEBUG   :: Thread-14 : PlexPy Monitor :: Play duration for ratingKey 49148 is 119 secs which is less than 120 seconds, so we're not logging it.
12-Aug-2015 14:20:00 - DEBUG   :: Thread-25 : PlexPy Monitor :: Removing sessionKey 132 ratingKey 49148 from session queue
12-Aug-2015 14:20:01 - DEBUG   :: Thread-25 : PlexPy Monitor :: Fetching metadata for item ratingKey 49148
12-Aug-2015 14:26:00 - DEBUG   :: Thread-13 : PlexPy Monitor :: Removing sessionKey 105 ratingKey 4796 from session queue
12-Aug-2015 14:26:01 - DEBUG   :: Thread-13 : PlexPy Monitor :: Fetching metadata for item ratingKey 4796
12-Aug-2015 14:34:17 - INFO    :: CP Server Thread-4 : Writing configuration to file
12-Aug-2015 14:34:18 - INFO    :: CP Server Thread-4 : Re-scheduled background task: Check for active sessions
12-Aug-2015 14:34:18 - INFO    :: CP Server Thread-4 : Requesting URLs for server...
12-Aug-2015 14:34:18 - INFO    :: CP Server Thread-4 : Writing configuration to file
12-Aug-2015 14:34:18 - INFO    :: CP Server Thread-4 : Writing configuration to file
12-Aug-2015 14:34:18 - INFO    :: Thread-30 : Requesting users list refresh...
12-Aug-2015 14:34:22 - INFO    :: Thread-30 : Users list refreshed.
12-Aug-2015 14:34:37 - INFO    :: CP Server Thread-9 : Writing configuration to file
12-Aug-2015 14:34:37 - INFO    :: CP Server Thread-9 : Re-scheduled background task: Check for active sessions
12-Aug-2015 14:34:37 - INFO    :: CP Server Thread-9 : Requesting URLs for server...
12-Aug-2015 14:34:37 - INFO    :: CP Server Thread-9 : Writing configuration to file
12-Aug-2015 14:34:37 - INFO    :: CP Server Thread-9 : Writing configuration to file
12-Aug-2015 14:34:37 - INFO    :: Thread-31 : Requesting users list refresh...
12-Aug-2015 14:34:42 - INFO    :: Thread-31 : Users list refreshed.
12-Aug-2015 14:34:44 - INFO    :: CP Server Thread-9 : Writing configuration to file
12-Aug-2015 14:34:47 - INFO    :: CP Server Thread-9 : Writing configuration to file
12-Aug-2015 14:41:28 - WARNING :: CP Server Thread-11 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/38832/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 14:41:28 - WARNING :: CP Server Thread-11 : Image proxy queried but errors occured.
12-Aug-2015 14:41:37 - DEBUG   :: Thread-19 : PlexPy Monitor :: Removing sessionKey 130 ratingKey 33489 from session queue
12-Aug-2015 14:41:38 - DEBUG   :: Thread-19 : PlexPy Monitor :: Fetching metadata for item ratingKey 33489
12-Aug-2015 14:46:31 - WARNING :: CP Server Thread-2 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/52222/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 14:46:31 - WARNING :: CP Server Thread-2 : Image proxy queried but errors occured.
12-Aug-2015 14:56:31 - WARNING :: CP Server Thread-6 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/59791/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 14:56:31 - WARNING :: CP Server Thread-6 : Image proxy queried but errors occured.
12-Aug-2015 14:56:37 - DEBUG   :: Thread-13 : PlexPy Monitor :: Removing sessionKey 106 ratingKey 48405 from session queue
12-Aug-2015 14:56:38 - DEBUG   :: Thread-13 : PlexPy Monitor :: Fetching metadata for item ratingKey 48405
12-Aug-2015 14:59:21 - INFO    :: CP Server Thread-2 : Writing configuration to file
12-Aug-2015 14:59:21 - INFO    :: CP Server Thread-2 : Re-scheduled background task: Check for active sessions
12-Aug-2015 14:59:21 - INFO    :: CP Server Thread-2 : Requesting URLs for server…
12-Aug-2015 14:59:21 - INFO    :: CP Server Thread-2 : Writing configuration to file
12-Aug-2015 14:59:21 - INFO    :: CP Server Thread-2 : Writing configuration to file
12-Aug-2015 14:59:21 - INFO    :: Thread-54 : Requesting users list refresh...
12-Aug-2015 14:59:42 - INFO    :: Thread-54 : Users list refreshed.
12-Aug-2015 15:14:21 - DEBUG   :: Thread-22 : PlexPy Monitor :: Removing sessionKey 140 ratingKey 45569 from session queue
12-Aug-2015 15:14:22 - DEBUG   :: Thread-22 : PlexPy Monitor :: Fetching metadata for item ratingKey 45569
12-Aug-2015 15:19:21 - DEBUG   :: Thread-18 : PlexPy Monitor :: Removing sessionKey 104 ratingKey 48236 from session queue
12-Aug-2015 15:19:22 - DEBUG   :: Thread-18 : PlexPy Monitor :: Fetching metadata for item ratingKey 48236
12-Aug-2015 15:30:34 - WARNING :: CP Server Thread-2 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/11879/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 15:30:34 - WARNING :: CP Server Thread-2 : Image proxy queried but errors occured.
12-Aug-2015 15:31:22 - DEBUG   :: Thread-25 : PlexPy Monitor :: Removing sessionKey 146 ratingKey 11621 from session queue
12-Aug-2015 15:31:23 - DEBUG   :: Thread-25 : PlexPy Monitor :: Fetching metadata for item ratingKey 11621
12-Aug-2015 15:34:21 - DEBUG   :: Thread-22 : PlexPy Monitor :: Removing sessionKey 133 ratingKey 4796 from session queue
12-Aug-2015 15:34:22 - DEBUG   :: Thread-22 : PlexPy Monitor :: Fetching metadata for item ratingKey 4796
12-Aug-2015 15:36:21 - DEBUG   :: Thread-23 : PlexPy Monitor :: Removing sessionKey 149 ratingKey 11624 from session queue
12-Aug-2015 15:36:21 - DEBUG   :: Thread-23 : PlexPy Monitor :: Fetching metadata for item ratingKey 11624
12-Aug-2015 15:40:02 - WARNING :: CP Server Thread-7 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/59791/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 15:40:02 - WARNING :: CP Server Thread-7 : Image proxy queried but errors occured.
12-Aug-2015 15:40:21 - DEBUG   :: Thread-12 : PlexPy Monitor :: Removing sessionKey 139 ratingKey 48511 from session queue
12-Aug-2015 15:40:24 - DEBUG   :: Thread-12 : PlexPy Monitor :: Fetching metadata for item ratingKey 48511
12-Aug-2015 15:42:21 - DEBUG   :: Thread-19 : PlexPy Monitor :: Removing sessionKey 143 ratingKey 45569 from session queue
12-Aug-2015 15:42:22 - DEBUG   :: Thread-19 : PlexPy Monitor :: Fetching metadata for item ratingKey 45569
12-Aug-2015 15:43:23 - WARNING :: CP Server Thread-11 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/15444/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 15:43:23 - WARNING :: CP Server Thread-11 : Image proxy queried but errors occured.
12-Aug-2015 15:44:21 - DEBUG   :: Thread-22 : PlexPy Monitor :: Removing sessionKey 154 ratingKey 15434 from session queue
12-Aug-2015 15:44:23 - DEBUG   :: Thread-22 : PlexPy Monitor :: Fetching metadata for item ratingKey 15434
12-Aug-2015 15:44:25 - WARNING :: CP Server Thread-5 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/51431/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 15:44:25 - WARNING :: CP Server Thread-5 : Image proxy queried but errors occured.
12-Aug-2015 15:46:15 - WARNING :: CP Server Thread-3 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/52223/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 15:46:15 - WARNING :: CP Server Thread-3 : Image proxy queried but errors occured.
12-Aug-2015 15:46:21 - DEBUG   :: Thread-23 : PlexPy Monitor :: Removing sessionKey 138 ratingKey 43357 from session queue
12-Aug-2015 15:46:23 - DEBUG   :: Thread-23 : PlexPy Monitor :: Fetching metadata for item ratingKey 43357
12-Aug-2015 15:51:21 - DEBUG   :: Thread-25 : PlexPy Monitor :: Removing sessionKey 158 ratingKey 4796 from session queue
12-Aug-2015 15:51:22 - DEBUG   :: Thread-25 : PlexPy Monitor :: Fetching metadata for item ratingKey 4796
12-Aug-2015 15:57:17 - WARNING :: CP Server Thread-2 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/11883/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 15:57:17 - WARNING :: CP Server Thread-2 : Image proxy queried but errors occured.
12-Aug-2015 15:57:21 - DEBUG   :: Thread-13 : PlexPy Monitor :: Removing sessionKey 152 ratingKey 11627 from session queue
12-Aug-2015 15:57:22 - DEBUG   :: Thread-13 : PlexPy Monitor :: Fetching metadata for item ratingKey 11627
12-Aug-2015 16:12:02 - INFO    :: MainThread : Signal 2 caught, saving and exiting...
12-Aug-2015 16:12:02 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 16:12:02 - INFO    :: MainThread : PlexPy is shutting down...
12-Aug-2015 16:12:07 - INFO    :: MainThread : Checking to see if the database has all tables....
12-Aug-2015 16:12:07 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 16:12:07 - DEBUG   :: MainThread : Git output: a039641aba69b9d09aaebdb7f177567cd383c9e8
12-Aug-2015 16:12:07 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 16:12:07 - DEBUG   :: MainThread : Git output: master
12-Aug-2015 16:12:07 - INFO    :: MainThread : Retrieving latest version information from GitHub
12-Aug-2015 16:12:07 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
12-Aug-2015 16:12:07 - ERROR   :: MainThread : Unable to connect to remote host because of a SSL error. It is likely that your system cannot verify the validityof the certificate. The remote certificate is either self-signed, or the remote server uses SNI. See the wiki for more information on this topic.
12-Aug-2015 16:12:07 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?
12-Aug-2015 16:12:07 - INFO    :: MainThread : Requesting URLs for server...
12-Aug-2015 16:12:07 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 16:12:07 - INFO    :: MainThread : Writing configuration to file
12-Aug-2015 16:12:07 - INFO    :: MainThread : Requesting users list refresh...
12-Aug-2015 16:12:21 - INFO    :: MainThread : Users list refreshed.
12-Aug-2015 16:12:21 - INFO    :: MainThread : Starting PlexPy web server on http://0.0.0.0:8181/
12-Aug-2015 16:12:21 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
12-Aug-2015 16:12:21 - INFO    :: MainThread : Scheduled background task: Refresh Plex Server URLs
12-Aug-2015 16:12:21 - INFO    :: MainThread : Scheduled background task: Check for active sessions
12-Aug-2015 16:12:21 - INFO    :: MainThread : Scheduled background task: Refresh users list

**Comment by drzoidberg33** [comment]
I believe your issue is with the QNAP not having the correct CA store so it cannot verify if the SSL certificates being used are valid and Python isn't allowing it if it cannot be verified.

This will break everything as PlexPy relies on getting information from plex.tv which also uses SSL.

This appears to be a common issue: http://forum.qnap.com/viewtopic.php?f=320&t=72515&start=45#p480016

I will have to add an option in the settings to disable SSL verification, QNAP should really fix this on their end but I'll add this to the task list.

If you have another computer you can install to in the meantime that should work fine.

**Comment by drzoidberg33** [comment]
@zenjabba 

I've just pushed an update to the dev branch which should allow you to override the SSL cert check. if you want to try it please checkout the dev branch.

Once you have it running shut PlexPy down first then you have to edit the line in the PlexPy config.ini file that says:

```
verify_ssl_cert = 1
```

and change it to:

```
verify_ssl_cert = 0
```

Then start PlexPy up again and see if it works. I'll keep this issue open until somebody confirms this fixes the issue.

**Comment by zenjabba** [comment]
I’ll work on this tomorrow when I get back to work.

**Comment by drzoidberg33** [comment]
I've pushed this in the v1.0.1 release too now.

**Comment by zenjabba** [comment]
13-Aug-2015 14:12:38 - DEBUG :: MainThread : Latest version is 001acfc24d2a41b0b4e56dafe660fe9cc76e0269
13-Aug-2015 14:12:38 - INFO :: MainThread : PlexPy is up to date
13-Aug-2015 14:12:38 - INFO :: MainThread : Requesting users list refresh...
13-Aug-2015 14:12:38 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "./PlexPy.py", line 220, in <module>
    main()
  File "./PlexPy.py", line 155, in main
    plexpy.initialize(config_file)
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/**init**.py", line 168, in initialize
    plextv.refresh_users()
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/plextv.py", line 25, in refresh_users
    result = PlexTV().get_full_users_list()
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/plextv.py", line 191, in get_full_users_list
    friends_list = self.get_plextv_friends()
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/plextv.py", line 147, in get_plextv_friends
    output_format=output_format)
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/http_handler.py", line 56, in make_request
    context = ssl._create_unverified_context()
AttributeError: 'module' object has no attribute '_create_unverified_context'

Traceback (most recent call last):
  File "./PlexPy.py", line 220, in <module>
    main()
  File "./PlexPy.py", line 155, in main
    plexpy.initialize(config_file)
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/**init**.py", line 168, in initialize
    plextv.refresh_users()
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/plextv.py", line 25, in refresh_users
    result = PlexTV().get_full_users_list()
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/plextv.py", line 191, in get_full_users_list
    friends_list = self.get_plextv_friends()
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/plextv.py", line 147, in get_plextv_friends
    output_format=output_format)
  File "/share/CACHEDEV1_DATA/.qpkg/Optware/plexpy/plexpy/http_handler.py", line 56, in make_request
    context = ssl._create_unverified_context()
AttributeError: 'module' object has no attribute '_create_unverified_context'

**Comment by drzoidberg33** [comment]
@zenjabba Do you know what version of Python it's running? I think this option is only available from 2.7, which might be the issue.

**Comment by zenjabba** [comment]
Python 2.7 (r27:82500, Aug 21 2010, 07:52:47)

**Comment by drzoidberg33** [comment]
Hmm. Let me test this on my Linux machine (been testing on Mac).

**Comment by drzoidberg33** [comment]
It appears it requires Python 2.7.9 to be exact. I'm honestly starting to think it's a waste of time to pursue this further though. QNAP should just fix their issue.

What I can do is write a new http handler which doesn't use httplib but requests instead. This will allow me to create a bypass for the certificate verification without having to rely on parameters that only work on certain versions of Python (like the HTTPSConnection class in httplib).

I'm going to close this task for now. New task will need a rewrite of http_handler.py.
