### ISSUE TITLE
Feature Request - Server update

### ISSUE THREAD

**Issue by nzrf** [Tautulli/Tautulli#550]
Request for notification for server version appears to be out of date and needs updating.

This would be nice then I could add to slack or pushbullet etc when server(s) needs updating.

**Comment by drzoidberg33** [comment]
Nice request.

**Comment by JonnyWong16** [comment]
Does anyone else get malformed XML at the endpoint `/updater/status`? (when there is an update available)

**Comment by Hellowlol** [comment]
request json instead?

**Comment by JonnyWong16** [comment]
Nope.

```
Failed format response from uri /updater/status to json error not well-formed (invalid token): line 3, column 347
```

I can hack it by requesting it in `raw` format, then using regex to remove the bad part, and parse the xml again...

---

XML looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1" canInstall="1" checkedAt="1455866795" downloadURL="https://plex.tv/downloads/latest/1?channel=16&amp;build=windows-i386&amp;distro=english&amp;X-Plex-Token=*****" status="0">
<Release key="https://plex.tv/updater/releases/1371" version="0.9.15.3.1674-f46e7e6" added="" fixed="(Media Optimizer) Crash after video transcode with certain subtitle configurations.&#xD;&#xA;(Sync)(Windows) Issues ensuring transcode directory is writable.&#xD;&#xA;(Sync)(iOS) Improve accuracy of synced resolution and bitrate metadata." https://plex.tv/downloads/latest/1?channel=16&build=windows-i386&distro=english&X-Plex-Token=*****="downloadURL" state="available" />
</MediaContainer>
```

Bad part is:

```
https://plex.tv/downloads/latest/1?channel=16&build=windows-i386&distro=english&X-Plex-Token=*****="downloadURL"
```

Hacky solution I'm using:

```
match_pattern = re.compile(r'(?!<Release.+)(https://plex\.tv/downloads/.*"downloadURL")(?<!\s)')
updater_status = re.sub(match_pattern, '', updater_status)
updater_status = helpers.parse_xml(updater_status)
```

**Comment by Hellowlol** [comment]
Seems like the way to go then...

**Comment by drzoidberg33** [comment]
Can you post the output you're getting? Where's the bad xml?

**Comment by JonnyWong16** [comment]
See comment above.

**Comment by drzoidberg33** [comment]
Wo, that's weird. Thanks Jonny, I'll raise this issue internally.

**Comment by JonnyWong16** [comment]
Cool. I'll put this on hold for now then.

Looks like the attribute and value got swapped around: `URL = downloadURL` instead of `downloadURL = URL`

**Comment by drzoidberg33** [comment]
This should be fixed in the next PMS release.

**Comment by JonnyWong16** [comment]
Awesome. Can we pass other API improvement requests though you? XD

**Comment by drzoidberg33** [comment]
Sure.

**Comment by JonnyWong16** [comment]
Here are a few:
- Transcoding stats: bitrate, etc.
- Indicate if an optimized version is being played in `/status/sessions`
- Sync time
- User last login time

Thanks!

**Comment by drzoidberg33** [comment]
Oh yes, this should be fixed from 0.9.15.6.

**Comment by JonnyWong16** [comment]
Awesome! I would still need to hack the XML for anyone not on 0.9.15.6 though.

**Comment by drzoidberg33** [comment]
This only affected a few releases and I think only Plex Pass releases. I would just catch and report the error and not bother about working around it.

**Comment by JonnyWong16** [comment]
Added in v1.3.10.
