### ISSUE TITLE
PlexPy Behind Nginx not working

### ISSUE THREAD

**Issue by Jovetic** [Tautulli/Tautulli#552]
Hi,

I'm running on 1.3.6 with Windows 10 and Python 2.7.  I have configured your wonderful program to run behind an Nginx installation.  I thought that I had broken it recently when I tried to implement SSL in that I could not see any statistics anymore, only the Dashboard and Settings.  I then found the only way I can see the History / Library now is if I go direct to the server on port 1818, it won't show the tables any other way and just stays on Fetching Rows, even after a ctrl f5.  

https://domain.co.uk/plexypy/history - Broke
http://domain.co.uk/plexypy/history - Broke
http://192.168.0.203/plexpy/history - Broke
http://192.168.0.203:1818/plexpy/history - **Works**
[errorold.zip](https://github.com/drzoidberg33/plexpy/files/137178/errorold.zip)
[nginx - Copy.txt](https://github.com/drzoidberg33/plexpy/files/137191/nginx.-.Copy.txt)

I have attached a copy of my Nginx config and some logs from Nginx.  If you require anything else then please let me know.

Regards,

Christian

**Comment by Hellowlol** [comment]
Any console errors in your browser?

**Comment by Jovetic** [comment]
No, nothing.  Iv'e just got it working on port 80 by turning off SSL alltogether in my Nginx.  Would be nice to get it working over SSL, not the end of the world though.

**Comment by JonnyWong16** [comment]
Have you looked at the [FAQ](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#q-why-does-plexpy-not-work-with-my-reverse-proxy-setup)? Or maybe this [comment](https://github.com/drzoidberg33/plexpy/issues/49#issuecomment-162453233)?

**Comment by peva3** [comment]
I got plexpy working with nginx + ssl for my setup.

Plexpy itself has SSL disabled, running on default 8181 port

Mainline Nginx (so I can use http/2) setup as a reverse proxy for http://127.0.0.1:8181 and is setup on a subdomain of the main plex domain I have. This setup wasnt working for me for a while, but the other day I tried it again and it works now.

I hope that helps somewhat.

**Comment by Jovetic** [comment]
Thanks for the suggestions.  I have done a little more tweaking and enabled SSL on Plexpy, turns out it wouldnt work without having Python Open SSL installed.  I'm still at the same place however, it still cannot read my tables or libraries.  Sample of the error can be seen below.

2016/02/19 19:12:58 [error] 6904#10080: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 86.x69.xx.x89, server: domain.co.uk,, request: "GET /plexpy/libraries HTTP/1.1", upstream: "https://192.168.0.203:8181/plexpy/libraries", host: "domain.co.uk", referrer: "https://domain.co.uk/plexpy/history"

My Nginx config can be seen below.

`location /plexpy {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass https://192.168.0.203:8181;
}`

**Comment by Jovetic** [comment]
I just spotted this.

2016/02/19 19:37:14 [info] 3532#8760: *116 client closed connection while waiting for request, client: 86.169.78.189, server: 0.0.0.0:443

I added a host entry for my personal domain to point to local address and removed these from my Nginx config.  Appears to be working now. :) 

 #ssl_session_cache    shared:SSL:1m;
    #ssl_session_timeout  5m;

```
#ssl_ciphers  HIGH:!aNULL:!MD5;
#ssl_prefer_server_ciphers  on;
```

**Comment by Jovetic** [comment]
#ssl_session_cache    shared:SSL:1m;
        #ssl_session_timeout  5m;

        #ssl_ciphers  HIGH:!aNULL:!MD5;
        #ssl_prefer_server_ciphers  on;

**Comment by Jovetic** [comment]
Spoke to soon. It was only working on my browser. Probably something cached. Not working anywhere else. I will carry on looking :)

**Comment by Jovetic** [comment]
All sorted Thanks

**Comment by Quiksmage** [comment]
Hi, I'm having an issue with my nginx reverse proxy with plexpy.

I changed the default port of ssl from 443 to 8000

here is my current config

I've tried a lot of things to no success. I followed a lot of random guides trying to fix this, so I know I have some duplicate entries in here, but it shouldn't be causing anything negative.

I originally tried the example in the FAQ, but it didn't work for me on the changed port.

```
server {
# The IP that you forwarded in your router (nginx proxy)
  listen 443 ssl;
  listen [::]:443 ssl;

# Make site accessible from http://localhost/
 server_name domain.com 192.168.1.80;
 ssl_certificate /etc/nginx/ssl/sslcert.crt;
 ssl_certificate_key /etc/nginx/ssl/sslcert.key;
# port_in_redirect off;

# Redirect the browser to our other ssl port
 rewrite ^ https://$server_name:8000$request_uri;
# return 301 $scheme://domain.com:8000$request_uri;
}

server {
 listen 80;
 return 301 https://domain.com:8000$request_uri;
}

server {
 listen 8000 ssl;
 listen [::]:8000 ssl;
# port_in_redirect off;

 server_name domain.com 192.168.1.80;
 ssl_certificate /etc/nginx/ssl/sslcert.crt;
 ssl_certificate_key /etc/nginx/ssl/sslcert.key;
 ssl_session_cache shared:SSL:10m;
 ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
 ssl_prefer_server_ciphers on;
 ssl_ciphers 'EECD+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
 add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
 
#proxy_set_header Host $http_host;
# proxy_set_header X-Real-IP $remote_addr;
# proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 proxy_set_header Cookie ""

 location /plexpy {

# proxy_bind $server_addr;
 proxy_pass http://192.168.1.72:8555;
 proxy_set_header Host $http_host;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Host $server_name;
 proxy_set_header X-Forwarded-Ssl on;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_redirect off;

 }
}
```

I have port 8000 forwarded on my router.

when I go to 

https://domain.com:8000/plexpy,

it tries to redirect me to https://domain.com/plexpy, which won't work.

I can manually type in https://domain.com:8000/plexpy/auth/login and then login with my credentials.

It will not successfully redirect me to /home after this, as it's using https://domain.com/plexpy/home again, discarding my port.

I can manually go to https://domain.com:8000/plexpy/home after logging in above.

If I forward 443 on my router, then everything works as it should as the https://domain.com/plexpy gets re-written properly to use 8000, but I'd like to avoid having 443 forwarded.

How do I stop it from dropping the port between pages? I haven't had this issue on my other nginx entries.


I have the following in my PlexPy config

HTTP Port: 8555
HTTP Root: /plexpy
Enable HTTP Proxy: yes

**Comment by JonnyWong16** [comment]
Try
```
proxy_set_header X-Forwarded-Host $server_name:8000;
```

**Comment by Quiksmage** [comment]
Thank you so much!!! 

I just started using nginx yesterday, so I'm trying to take in as much as I can. Your quick response has made my day :)
