### ISSUE TITLE
[Feature Request] Send notification when duplicate login detected.

### ISSUE THREAD

**Issue by Trudge** [Tautulli/Tautulli#553]
HI,

would be it be possible somehow to send a notification when plexpy detects a login in use and coming from 2 different IP addresses at the same time.  The idea would be a simple way to help track down people who are sharing logins.

Thx.

**Comment by Hellowlol** [comment]
Are you talking about plexpy logins or plex logins?

**Comment by Trudge** [comment]
plex logins

**Comment by roelbeun** [comment]
duplicate i guess: https://github.com/drzoidberg33/plexpy/issues/305

**Comment by JonnyWong16** [comment]
As mentioned in #305, you can achieve this with a custom script.
