### ISSUE TITLE
Plex update may have broken TV metadata?

### ISSUE THREAD

**Issue by spuniun** [Tautulli/Tautulli#555]
I upgraded Plex to Plex Pass version 0.9.15.4.1679 the other day and now my Recently Added announcements for TV episodes are broken. They no longer are able to display the season and episode numbers or episode title:

`<tv>{show_name} S{season_num00}E{episode_num00} "{episode_name}" was added or upgraded in {library_name}</tv>`

> Top Chef S00E01 "" was added or upgraded in TV Shows

**Comment by JonnyWong16** [comment]
You didn't use the search first... #440, #509, #531

**Comment by spuniun** [comment]
You are correct
