### ISSUE TITLE
Can't connect to the database: database disk image is malformed

### ISSUE THREAD

**Issue by bhavicp** [Tautulli/Tautulli#556]
Hi,

After updating Plexpy (to master - see below). I'm getting a DatabaseError: database disk image is malformed

The log can be found here: https://gist.github.com/bhavicp/67d7570565806a81294a

Actually, just realized from the Logs, that even before updating today, it was crashing before (Jan 24th). Is there anything I need to run manually to upgrade the DB? Or is it another problem? Should I try a fresh checkout and put plexpy.db/config there?

```
Receiving objects: 100% (2216/2216), 35.32 MiB | 6.07 MiB/s, done.
Resolving deltas: 100% (1001/1001), completed with 92 local objects.
From https://github.com/drzoidberg33/plexpy
   9409303..49fb454  master     -> origin/master
 + dcc49cf...94594e9 better-http-handler -> origin/better-http-handler  (forced update)
   14d4940..1f5c605  dev        -> origin/dev
 * [new branch]      frontend-tweaks -> origin/frontend-tweaks
 + 5b0c666...1809b95 library-id-changes -> origin/library-id-changes  (forced update)
 * [new branch]      machine-id-fix -> origin/machine-id-fix
 * [new branch]      scanner-log-view -> origin/scanner-log-view
 * [new branch]      websockets-watched-notify-fix -> origin/websockets-watched-notify-fix
 * [new tag]         v1.2.15    -> v1.2.15
 * [new tag]         v1.2.16    -> v1.2.16
 * [new tag]         v1.3.6     -> v1.3.6
 * [new tag]         v1.3.0     -> v1.3.0
 * [new tag]         v1.3.1     -> v1.3.1
 * [new tag]         v1.3.2     -> v1.3.2
 * [new tag]         v1.3.3     -> v1.3.3
 * [new tag]         v1.3.4     -> v1.3.4
 * [new tag]         v1.3.5     -> v1.3.5
Updating 9409303..49fb454
```

**Comment by JonnyWong16** [comment]
I think your database might have gotten corrupted. If you PM me your `plexpy.db` file on the [forums](https://forums.plex.tv/profile/JonnyWong16) I can try to fix it. Or you can try this yourself: http://froebe.net/blog/2015/05/27/error-sqlite-database-is-malformed-solved/

**Comment by bhavicp** [comment]
That worked - Only took 5 minutes.

Thanks
