### ISSUE TITLE
Bug / Issue? Most Active Platform Stats 

### ISSUE THREAD

**Issue by rickcab1** [Tautulli/Tautulli#557]
Guys,

I tried searching before I posted.  I was wondering if its me on a configuration and have been watching this for over that last week.  My most active platform is Roku and I was at around 1088HRS last week and this week it now shows the following as if it going down.  I tried toggling the days int he graphs section to see if that was associated to it but it didn't do anything.  Any ideas?

![image](https://cloud.githubusercontent.com/assets/14242464/13200367/2cf18d32-d7f9-11e5-98e0-298a799ad94d.png)

![image](https://cloud.githubusercontent.com/assets/14242464/13200368/3e246e8a-d7f9-11e5-83e0-17f9d31c61ee.png)

**Comment by JonnyWong16** [comment]
The stats are only for the "Last X days" (as shown beside the title). The time frame can be changed in the Settings > Homepage Statistics.

**Comment by rickcab1** [comment]
OK let me crawl back into my hole!  Thanks!  I was scratching my head on that for a minute!  Whats max number of days?

**Comment by JonnyWong16** [comment]
There is no maximum.
