### ISSUE TITLE
[Bug] Websocket does not reconnect when changing "Use SSL" setting

### ISSUE THREAD

**Issue by JonnyWong16** [Tautulli/Tautulli#558]
Websocket should reconnect to secure uri (`wss://`) when enabling "Use SSL" and reconnect to insecure uri (`ws://`) when disabling "Use SSL".

 Branch: master
 Version/Commit hash: v1.3.7 / 97c414d1ade6c4dd254104b801a4e1f8e0c41c93
 Your operating system and python version: FreeBSD 9.1-RELEASE, Python 2.7.10

What you did?
- Enabled "Use SSL" in the Plex Media Server settings.

What happened?
- Settings saved, but websocket did not reconnect to secure uri.

What you expected?
- Websocket to reconnect to secure uri.

How can we reproduce your issue?
- Toggle "Use SSL" in the settings.

What are your (relevant) settings?
- Monitoring > Use Websockets enabled.
- Plex Media Server > Use SSL

Workaround: Restart PlexPy.

**Comment by drzoidberg33** [comment]
Ye, that should trigger a restart notification.

**Comment by JonnyWong16** [comment]
Attempted fix in v1.3.10.

Still buggy, I think.
