### ISSUE TITLE
Is not able to acces Plex Server on non-standard port

### ISSUE THREAD

**Issue by zenjabba** [Tautulli/Tautulli#56]
My plex server runs on 32401, but app keeps trying to access the server on 32400

12-Aug-2015 14:41:28 - WARNING :: CP Server Thread-11 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/38832/indexes/sd/&width=300&height=169. Status code 500
12-Aug-2015 14:41:28 - WARNING :: CP Server Thread-11 : Image proxy queried but errors occured.
12-Aug-2015 14:41:37 - DEBUG :: Thread-19 : PlexPy Monitor :: Removing sessionKey 130 ratingKey 33489 from session queue
12-Aug-2015 14:41:38 - DEBUG :: Thread-19 : PlexPy Monitor :: Fetching metadata for item ratingKey 33489
12-Aug-2015 14:46:31 - WARNING :: CP Server Thread-2 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/52222/indexes/sd/&width=300&height=169. Status code 500

**Comment by drzoidberg33** [comment]
The 32400 port is the internal port, which will always be on 32400 as far as I know. Changing the external port in Plex does not affect this.

If you have some strange non-standard setup you will have to provide some more details as to how it's been done.

Also, using 32401 is an odd choice as I know Plex reserves this port by default and I'm not sure if setting this as your port will cause issues.

My server shows Plex listening on both 32400 and 32401:

```
tcp        0      0 *:32400                     *:*                         LISTEN      4086/./Plex Media S 
tcp        0      0 *:32401                     *:*                         LISTEN      4086/./Plex Media S 
```

**Comment by drzoidberg33** [comment]
As below, my server is set up on port 8088, but internally it is still references as 32400:

<img width="438" alt="screenshot 2015-08-12 21 35 43" src="https://cloud.githubusercontent.com/assets/1313205/9234639/40b93a6e-413a-11e5-8feb-e381a10c54b7.png">

**Comment by zenjabba** [comment]
Correct, I’m incorrect in saying it’s 32401, it’s still 32400.

**Comment by Arcanemagus** [comment]
The status code you are getting back is 500, which indicates an internal server error is coming back from Plex. Do you see any information in the Plex logs? If you craft a URL to the Plex server in your browser do you see anything?

**Comment by zenjabba** [comment]
/opt/plexpy/logs] # wget http://127.0.0.1:32400/library/parts/15444/indexes/sd/&width=300&height=169
[1] 16024
[2] 16025
[/opt/plexpy/logs] # pathconf: Value too large for defined data type
pathconf: Value too large for defined data type
--2015-08-12 16:12:14--  http://127.0.0.1:32400/library/parts/15444/indexes/sd/
Connecting to 127.0.0.1:32400... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

**Comment by Arcanemagus** [comment]
@zenjabba the URL should be something along the lines of:

```
https://plex.server.url:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/parts/38832/indexes/sd/&width=300&height=169&X-Plex-Auth-Token=yourplexauthtokenhere
```

Note the aditions to the beginning and end.

**Comment by zenjabba** [comment]
12-Aug-2015 15:46:15 - WARNING :: CP Server Thread-3 : Failed to access uri endpoint /photo/:/transcode?url=http://127.0.0.1:32400/library/parts/52223/indexes/sd/&width=300&height=169. Status code 500

**Comment by Arcanemagus** [comment]
You already posted that, please try a URL like above _in your browser_. And check the _Plex_ (not PlexPy!) logs.

**Comment by drzoidberg33** [comment]
@Arcanemagus @zenjabba 

This issue here is with the QNAP and it's lacking SSL CA store. It's breaking everything in PlexPy because I need SSL to communicate with Plex.tv.

**Comment by Arcanemagus** [comment]
@drzoidberg33 gotta love horribly broken SSL installations :disappointed:.

**Comment by zenjabba** [comment]
Roger, I’ll install on the Windows machine that supports the plex installation and get back to you.

**Comment by zenjabba** [comment]
Working perfectly on Windows 7

**Comment by drzoidberg33** [comment]
Cool. I'm looking into the SSL check bypass - will hopefully have a solution sometime soon.
