### ISSUE TITLE
Merging 2 databases

### ISSUE THREAD

**Issue by camjac251** [Tautulli/Tautulli#564]
Is it possible to either merge two separate installation databases together into 1? I have two databases that were made from plexwatch installs but then became their own with new months of new watch history. I was hoping now that it would be possible to join them together since I'm merging the two server (plex). Is there an export/import tool available that I could use?

**Comment by JonnyWong16** [comment]
There isn't a way to do this from within PlexPy, but it should be possible to combine them manually with a tool like [SQLiteBrowser](http://sqlitebrowser.org).

**Comment by camjac251** [comment]
Wouldn't that interfere if two logged items have the same ID?

**Comment by JonnyWong16** [comment]
~~I'll test it out later tonight but it should work if you export/import from SQL dump files. Make sure both databases are on the same version of PlexPy so the tables are the same.~~

EDIT: Actually, I think you're right. If they are from two different servers then the Plex IDs might conflict.

**Comment by camjac251** [comment]
Would it be possible to add a function for exporting and importing?

**Comment by JonnyWong16** [comment]
Possible, but not anytime soon.

**Comment by vortexrap** [comment]
+1 for this. I have several databases & watch histories from an older PMS library and the metadata / IDs are incorrect. A Merge All button or an option to do bulk changes instead of one by one would be very very helpful.

**Comment by JesseHawkins-zz** [comment]
I moved my Plex server from one machine to another by moving the entire /var/lib/plexmedia/* directory. I installed PleyPy on this new server before reading that I could just move the db file to keep my history. 6 days elapsed between the Plex server move and the PlexPy database move. This left me with two PleyPy.db's - the old one with the history I want, and the new one with 5 days of recent usage. The Plex server has not changed, other than it's physical location.

What are the SQL commands to merge the two databases?

**Comment by saitoh183** [comment]
I would like to know as well...i have a DB now that shows 3 copies of the same library because i have had to move my plexpy db to other vps and i wanted to keep the user data. but it would be nice to merge it

**Comment by JonnyWong16** [comment]
Just Google "merge sqlite database".

**Comment by saitoh183** [comment]
yup...found what i needed...forgot that you had posted it on the forum for me... thanks

link for others:
https://forums.plex.tv/discussion/comment/1208116/#Comment_1208116
