### ISSUE TITLE
Notification bug - Version 1.3.8

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#567]
Another bug ?

> Uncaught exception: Traceback (most recent call last):
> File "/opt/plexpy/plexpy/logger.py", line 221, in new_run
> old_run(_args, *_kwargs)
> File "/usr/lib/python2.7/threading.py", line 763, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "/opt/plexpy/plexpy/notification_handler.py", line 272, in notify_timeline
> set_notify_state(session=stream_data,
> NameError: global name 'stream_data' is not defined

**Comment by Hellowlol** [comment]
is this dev or master? Using the latest update?

https://github.com/drzoidberg33/plexpy/blob/master/plexpy/notification_handler.py#L272

**Comment by elRadix** [comment]
I'm on master, latest update

PlexPy Configuration
Git Branch: master
Git Commit Hash:    965fd170bdd5161d8ea2e9730c00e28ffe09424a

**Comment by Hellowlol** [comment]
The traceback says that line is something else then it is. Try to shutdown plexpy and remove all pyc, pyo files in the plexpy folder and start it again.

**Comment by elRadix** [comment]
in which subfolder, there is  nothing in the root of plepxy

**Comment by elRadix** [comment]
I have just updated to your latest release 1.3.9
I'll keep an eye is this issue comes again

**Comment by JonnyWong16** [comment]
This was fixed in v1.3.9.
