### ISSUE TITLE
[Feature Request] poster-url embed as picture in email

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#568]
Is there a possibility to have the poster url embedded as in image when sending an email, in my case gmail

**Comment by thatsnasty** [comment]
+1

**Comment by alternativesurfer** [comment]
+1

**Comment by Mr-Quinn** [comment]
+1

**Comment by nickiman** [comment]
+1

**Comment by magaman** [comment]
+2 on this, would be very useful plus save the need for running other email plugins

**Comment by elRadix** [comment]
all,

please cast your vote on feathub below

http://feathub.com/drzoidberg33/plexpy/+55

**Comment by JonnyWong16** [comment]
Posters can be added to emails using HTML in v1.4.0.

```
<img src="{poster_url}" width="150" height="225">
```

**Comment by elRadix** [comment]
Does is it conflict with other notification agents ie. telegram/pushbullet which cant handle html tags? 
May be its better to create a separate custom notifications just for email/html capable agents.

**Comment by JonnyWong16** [comment]
Tags that are not allowed by other agents will be removed.
- e.g. `<img>` tags don't work with Telegram or Pushbullet, so it won't show up in either of them.

Tags that common between agents will show up.
- e.g. `<b>` will show up for Email, Pushover, etc.
