### ISSUE TITLE
Notification Episode Meta Data not woriking

### ISSUE THREAD

**Issue by chuckkay** [Tautulli/Tautulli#569]
{show_name}  {season_num00}x{episode_num00} - {episode_name} was recently added to Plex.

Resulting in 
Talking Dead 00x01 - was recently added to Plex. 

should be 

Talking Dead - 5x06 - Always Accountable - was recently added to Plex.

**Comment by JonnyWong16** [comment]
Please search next time:

https://github.com/drzoidberg33/plexpy/issues/440
https://github.com/drzoidberg33/plexpy/issues/509
https://github.com/drzoidberg33/plexpy/issues/531
https://github.com/drzoidberg33/plexpy/issues/555

**Comment by chuckkay** [comment]
sorry...

can you help me..
whats wrong with this in the body of notification? I'm not getting HTML

<a href="{poster_url}"><tv>TV SHOW - {show_name}
{season_num00}x{episode_num00} - {episode_name} </tv> <movie>MOVIE -
{title} ({year})</movie> was recently added to Plex.</a>

**Comment by JonnyWong16** [comment]
What does it show up as?

**Comment by chuckkay** [comment]
I get this
TV SHOW - Talking Dead 05x06 - was recently added to Plex.

Originaly tried
<a href="{poster_url}"><tv><b><font
color="blue">{show_name}</font></b></tv> <b><font
color="blue">{title}</font></b></a>   was recently added to Plex.

had same problem.. i figure it's something wrong with my html code. or im
missing something...

**Comment by JonnyWong16** [comment]
What about in the Logs > Notification Logs?

I think the html tags are being stripped out. PlexPy bug.

**Comment by chuckkay** [comment]
same

2016-02-22 16:41:35 Pushover created Plex Added a TV SHOW - Talking Dead
 TV SHOW - Talking Dead 05x06 - was recently added to Plex.

**Comment by JonnyWong16** [comment]
Yeah, PlexPy is stripping out all html tags. I didn't actually test the html for Pushover...I'll fix it later.

**Comment by chuckkay** [comment]
PS Where is they Paypal Donate button

**Comment by JonnyWong16** [comment]
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=DG783BMSCU3V4
