### ISSUE TITLE
Unclear 'Please check your settings' and not logging.

### ISSUE THREAD

**Issue by excenter** [Tautulli/Tautulli#571]
Downloaded the windows package of 1.3.9, installed it, added it as launch script, yadda yadda. 
I go through the onboarding screens, signing in to my plex account. yay. I get this message: 
`There was an error communicating with your Plex Server. Please check your settings.`
Firstly there is no indication what setting is unhappy.
I restarted, added a proper path to my Plex logs, ran the updater, restarted my computer, et cetra. 
Here's my log http://pastebin.com/Uussd4Qg
I don't know what's going wrong, I told it to fetch a new token a dozen times, it stays the same.
I think it might be related to https://github.com/drzoidberg33/plexpy/issues/450 or https://github.com/drzoidberg33/plexpy/issues/212 because the ios devices that tend to read from this server have all kinds of special characters. That being said, it wont detect "normal" devices like the computer it runs on, or my work laptop.

**Comment by drzoidberg33** [comment]
Do you have a device viewing media that has non-ascii characters in it's name?

See https://github.com/drzoidberg33/plexpy/issues/212

**Comment by excenter** [comment]
my iphone, it has  ö in the name. And many devices I'm trying to log and don't control.
It's correctly reading the library and user group I forgot to add

**Comment by drzoidberg33** [comment]
That's the problem then. The current work around is to remove the characters from the device names.

I'm closing this issue as a duplicate.

**Comment by excenter** [comment]
is there an ETA on a fix?

**Comment by drzoidberg33** [comment]
See the issue I linked in my first post.
