### ISSUE TITLE
ISSUE: Fetching Rows

### ISSUE THREAD

**Issue by yeyeoke** [Tautulli/Tautulli#573]
I've cleared the cache and I'm still getting the "fetching rows" message when trying to view the user-tab. The log says: 

WebUI :: /users : Uncaught TypeError: Illegal invocation. (jquery-2.1.4.min.js:4)

**Comment by JonnyWong16** [comment]
Please use the search function next time. #565

https://forums.plex.tv/discussion/comment/1133412/#Comment_1133412
https://forums.plex.tv/discussion/comment/1134743/#Comment_1134743
