### ISSUE TITLE
PlexPy Notifiers :: Email notification fails

### ISSUE THREAD

**Issue by vjbonan** [Tautulli/Tautulli#576]
With gmail, i get this response:
PlexPy Notifiers :: Email notification failed: (534, '5.7.14 Please log in via your web browser and\n5.7.14 then try again.\n5.7.14 Learn more at\n5.7.14 https://support.google.com/mail/answer/78754 f66sm1489362qkb.5 - gsmtp')

The url google references is not valid.. So I am really not sure waht's going on.

I tried a secondary smtp server I have access to:
but receive
PlexPy Notifiers :: Email notification failed: [Errno -2] Name or service not known

When tried Yahoos it says connection ended unexpectedly.

What can I do to setup mail notification properly?

**Comment by JonnyWong16** [comment]
This is my Gmail setup for reference:

```
SMTP Server: smtp.gmail.com
SMTP Port: 587
SMTP User: MyEmail@gmail.com
SMTP Password: App password since I have 2-factor authentication (https://security.google.com/settings/security/apppasswords)
TLS: checked
```

**Comment by vjbonan** [comment]
Hi Jonny, thanks for the quick response. 
Those are the exact settings I have, but I do not have 2-factor authentication.  I went to the link you have ( ) and it said  
The setting you are looking for is not available for your account.

Not sure where go next, anything more detailed in the logging that I can check?

**Comment by JonnyWong16** [comment]
Maybe this (option 2)? https://support.google.com/accounts/answer/6010255?hl=en&ref_topic=2401957

**Comment by vjbonan** [comment]
I did try that before, and it didn't work.   I tried it again just now and it worked. Perhaps one of the other options I had set was wrong (like the port) when I was just trying different things.    I did receive the email. Great!  Thanks

**Comment by JonnyWong16** [comment]
Great!

Just for future reference. My source: http://stackoverflow.com/a/27515833
