### ISSUE TITLE
Facebook Notification Agents problems...

### ISSUE THREAD

**Issue by FCIK** [Tautulli/Tautulli#579]
Hi!
I have set up everything OK. All is good. I have check the button i want (in the Bell option) for the Notification to my facebook group.

When i send a test Notification i work fine.

But when i add new media item, there is no Notification in my Facebook group. What am i doing wrong?

**Comment by JonnyWong16** [comment]
Please read "Issues" in the Readme file.

**Comment by JigSawFr** [comment]
Review permissions of your app. Set it to friends or public. Check logs.

And as said @JonnyWong16, please read before posting an issue :)

**Comment by FCIK** [comment]
Where is the Readme file? Sorry if i missed it.

App is set to public. It feels i have done everything right, just it does now send me added stuff to Facebook group. =( Hmm.

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#issues

Settings > Notifications > Enable Recently Added Notifications

**Comment by FCIK** [comment]
Thank you so much! Working now!
