### ISSUE TITLE
Graphs section not working properly on safari 8.0.8(OS X 10.10.5) same on iOS 8.4

### ISSUE THREAD

**Issue by izeen** [Tautulli/Tautulli#58]
Noticed a slight problem with the graphs on Safari(both on OS X and on iOS), Changing the graphs options(30 days, 90 days, 1 year) changes nothing in safari, graphs dont update, switching to chrome it works instantly. If you change the view to Play totals to get the total plays for a year back the chart just get stuck at loading chart, if i change to chrome it works instantly. Since it works in chrome and other browsers i recon there is a bug.

Would appreciate you looking into this, im in love with PlexPy. Thank you very much.

**Comment by drzoidberg33** [comment]
Thanks, I found the problem and it'll be fixed in the next release.

**Comment by izeen** [comment]
Thank you very much, donated a small sum to show my appreciation!

**Comment by drzoidberg33** [comment]
@izeen Always much appreciated :smile: :+1:

**Comment by drzoidberg33** [comment]
Fix in https://github.com/drzoidberg33/plexpy/commit/5abe314f9f7ca6296a3f02782370dc5965acf5a8

Currently only on dev branch, this will be pushed to the master branch on next release.

**Comment by drzoidberg33** [comment]
Released in https://github.com/drzoidberg33/plexpy/releases/tag/v1.0.1
