### ISSUE TITLE
Feature request - clear notification log per agent

### ISSUE THREAD

**Issue by stefsims** [Tautulli/Tautulli#580]
I would like to able to clear the notification log per agent and/or notification trigger.

**Comment by JonnyWong16** [comment]
What would be the point of clearing the log?

**Comment by stefsims** [comment]
in a couple of months I have almost 3000 notifications. I would like to delete some of them but keep others...

**Comment by JonnyWong16** [comment]
I'll add a "clear all". Making it clear per agent or trigger is a lot of work.

**Comment by JonnyWong16** [comment]
Clear all button added in v1.3.10.
