### ISSUE TITLE
Question: Merging 2 Movies Libraries

### ISSUE THREAD

**Issue by rickcab1** [Tautulli/Tautulli#581]
I was wondering how this will affect my Data.  I have two Libraries for example "Movies 1" and one Movies 2".  If I wanted to combine the Libraries (not the folders where the movies are being housed) and just call it "Movies" how would it affect my data? Is there a suggested way to do this?

**Comment by JonnyWong16** [comment]
When you move anything in your Plex library, the "id" for the item changes. All the history saved in PlexPy will still be available, but connected to the old "ids". Any new history will be logged with the new "ids". The only thing this will affect is the same movie being logged as two different items. You can fix it by going to the history table entry for the old session and clicking on the "Fix Metadata" button (unfortunately, currently, you need to this individually for each item).

Example:
- You watched Movie A (id is 1234) before merging your libraries. PlexPy saves the history as Movie A with id 1234.
- You merged your two libraries.
- You watch Movie A again (id is now 4321). PlexPy saves the history as Movie A with id 4321.
- Click on the first session of Movie A in the history table, in the table it will only show the first session.
- You click the "Fix Metadata" button to link the old session to the new id.
- The table now shows both sessions of Movie A.

**Comment by Arcanemagus** [comment]
Just a note that all your _Plex_ history will also be wiped, so if users have marked items as watched they will no longer be marked as watched after the merger.
