### ISSUE TITLE
[Feature Request] Trakt Scrobbling

### ISSUE THREAD

**Issue by OmgImAlexis** [Tautulli/Tautulli#582]
Currently I'm using [Trakt Scrobbling](https://github.com/trakt/Plex-Trakt-Scrobbler) from within Plex with a plugin it'd be nice to be able to do it straight from PlexPy meaning no plugins have to be installed on Plex or be kept up to date.

**Comment by Salvationdk** [comment]
Would be nice to see this feature aswell.

**Comment by Hellowlol** [comment]
Until someone adds this to core, a simple solution would be to use a script to scrobble the watched videos.

**Comment by JonnyWong16** [comment]
Or use the Plex [Trakt Channel](https://github.com/trakt/Plex-Trakt-Scrobbler) like you mentioned. It works really well.

**Comment by sorel123** [comment]
The beauty to the Plex channel Trakt is it can go both ways.  Allowing you to update plex from say xbmc or if you loose your library/server and have to reinstall from scratch it will update your watched status on new server.  With trakt in  plexpy just seems like it would be less useful and just add more complication.

**Comment by OmgImAlexis** [comment]
@sorel123 with it in Plexpy it'd mean you could go and reinstall Plex at any time or if you're using Docker not need to modify the container after install and just use it through Plexpy. I don't really see any downside to it.

**Comment by sorel123** [comment]
@OmgImAlexis But it won't update your watched status in Plex so it seems a large part of the functionality of Trakt would be lost.  Plexpy is already keeping track of who/what/when, but it's not marking anything as watched/unwatched in plex (unless I missed something).  Either way I guess it wouldn't hurt if it was there.

**Comment by halfluck** [comment]
This  would be a good addition along with Plex Cloud support (which doesn't support Channels).

**Comment by OmgImAlexis** [comment]
Another reason this would be good is that the Trakt plugin currently only supports a single user. Since Plexpy tracks all users each user could have their watched state synced to Trakt.

**Comment by HitsvilleUK** [comment]
@OmgImAlexis 
Are you aware that you can set multiple users and match each user to their Plex and Trakt accounts using the config page 
http://trakt-for-plex.github.io/configuration/#/connect
details are here
https://forums.plex.tv/discussion/102818/rel-trakt-tv/p1  (Fuzemans 2nd post on the page)
It took about 30 mins to set up 6 users for both my local and remote servers.

**Comment by foXaCe** [comment]
any new for this features ? the sync of trakt account it very good idea. on my nvidia shield tv the trakt.tv plug-in can not install
