### ISSUE TITLE
[Feature Request] Facebook Poster Image > make link to Plex Web optional

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#583]
So the poster can be uploaded, just want it to be optional in the Notify agent if the Plex URL is behind the poster.

Thanks

**Comment by JonnyWong16** [comment]
Facebook doesn't allow pictures without a URL.

```
Error sending Facebook post: (#100) A link must be provided if a picture URL is given.
```

There needs to be a link somewhere.

**Comment by roelbeun** [comment]
Link to IMDb or TheTVDB sounds good. Info is already around!

**Comment by spuniun** [comment]
Yeah, I would rather use the imdb/tvdb link for posters and not plex web as well

**Comment by roelbeun** [comment]
Is this something that will be implemented?

**Comment by JonnyWong16** [comment]
It's already in the Dev branch.

**Comment by roelbeun** [comment]
Awesome, safe to test development? Is there a manual for using dev?

**Comment by Hellowlol** [comment]
Just use `git checkout dev` then you start it like normal with python Plexpy.py

**Comment by JigSawFr** [comment]
Thanks you @JonnyWong16

**Comment by JonnyWong16** [comment]
Added in v1.3.10.
