### ISSUE TITLE
Question: Force notification

### ISSUE THREAD

**Issue by lucidonlinenet** [Tautulli/Tautulli#585]
Hi All,

Sorry if this has been answered before but I was wondering if there is a way to force a notification for a particular episode or movie? My server unfortunately had several CPU intensive processes going at once and this seems to have interfered with plex and plexpy being able to communicate and plexpy sending the notification.

**Comment by JonnyWong16** [comment]
Not sure what you mean.

**Comment by lucidonlinenet** [comment]
So, for example plexpy for whatever reason doesn't send a notification out of a newly added item. Is there a way to push the notification out after the fact?

**Comment by Hellowlol** [comment]
No that isn't possible. We could use psutil increase niceness (cross platform) but i don't see the point. If you really need this you can make a script that starts plexpy then set the niceness.

**Comment by JeramieG-IDG** [comment]
i have the same issue sometimes.. i don't know if its limited to facebook or what, but sometimes plexpy just doesn't seem to see the new addition.  its pretty rare, but happens to me.  what is the above "niceness"? could that also help with notifications happening before the metadata has been downloaded in plex and so the facebook notification doesn't have the thumbnail, or doesn't sometimes have the description?  thanks so much.
