### ISSUE TITLE
[Feature Request] Separate stream types on graph

### ISSUE THREAD

**Issue by jstrese** [Tautulli/Tautulli#587]
Goal
I would like to see a list of direct play / transcoded / direct streamed items on the stream info graph. Not all combined, but a list of each individual type.

Implementation
1. When clicking, for example, the transcode data points on the line graph have the list of shows just be the transcoded shows for that day and vice-versa instead of all of the types being listed when clicking any of the data points.
2. Or, have a tab on the popup window for each stream type and a catch-all tab ("All") where all types are listed.
3. Or, add a new column to the popup window indicating what type of stream was used so that we can sort by it.

**Comment by JonnyWong16** [comment]
The history modal is now filtered based on whichever series is clicked in v1.3.10.
