### ISSUE TITLE
Play Totals not respecting play count/duration input box

### ISSUE THREAD

**Issue by OmgImAlexis** [Tautulli/Tautulli#589]
Instead of the play totals tab changing depending on the input box it's statically set at 12 months.
I'm guessing this was just an oversight, can the input box and buttons either be hidden on that tab or can the graph take into account the duration set and change accordingly?

![screen shot 2016-03-02 at 6 14 27 pm](https://cloud.githubusercontent.com/assets/6525926/13453789/b4faf342-e0a2-11e5-9d89-2ac89c9abcf5.png)

**Comment by JonnyWong16** [comment]
Oops, the days input box should be hidden for that tab.

**Comment by JonnyWong16** [comment]
Fixed in v1.3.10.
