### ISSUE TITLE
HTTP 401 for glyphicons only after turning on auth

### ISSUE THREAD

**Issue by chrissearle** [Tautulli/Tautulli#59]
Turned on authentication and restarted - all good - gives me a basic auth popup to get in - and then it works.

Only thing is - I get two resources giving a 401 Unauthorized - on:

http://localhost:8181/interfaces/default/fonts/bootstrap3/glyphicons-halflings-regular.woff
http://localhost:8181/interfaces/default/fonts/bootstrap3/glyphicons-halflings-regular.ttf

so - none of the glyphs work.

Nothing else has a problem - pages are all working - but not the glyphicons.

**Comment by drzoidberg33** [comment]
Which page are you seeing this on? I have authentication enabled and don't see this issue but I may be looking in the wrong place.

**Comment by chrissearle** [comment]
All pages.

**Comment by chrissearle** [comment]
Hmm. Just told it to restart and now I'm seeing 401's on these instead:

fontawesome-webfont.woff2?v=4.4.0
fontawesome-webfont.woff?v=4.4.0
fontawesome-webfont.ttf?v=4.4.0

All from the http://localhost:8181/interfaces/default/fonts/ path - not even seeing it try to load glyphicons now.

**Comment by chrissearle** [comment]
Correction - fontawesome gives 401 on front page - both fontawesome and glyphicons on history etc. Sorry - got a bit confused there.

**Comment by drzoidberg33** [comment]
I would clear your cache and see if that helps.

**Comment by chrissearle** [comment]
Been testing it with "Disable Cache" setting in the browser's network inspector (chrome in this case).

**Comment by drzoidberg33** [comment]
And if you open it in a different browser?

**Comment by chrissearle** [comment]
Fascinating. So far - three machines. Chrome on each - 401 - with caching disabled. Firefox - downloads fine - again - caching disabled. I don't pretend to understand even how that works. But since firefox can get them then it shows that the server isn't rejecting.
