### ISSUE TITLE
Allow user to configure backup directory

### ISSUE THREAD

**Issue by jelliuk** [Tautulli/Tautulli#591]
In reference to following implementation [#89 Automated DB Backup](https://github.com/drzoidberg33/plexpy/issues/89), it would be beneficial to enable the user to set there own path for backups to be created in.

Example use case (reference Windows) would be that PlexPy is operating on C:\, currently all backups will also be placed on C:\  Should this drive fail, both the production and automated backups will be lost.  An improvement would be to enable users to select their own custom path for backups to be created, this would enable users to backup their database to a separate drive avoiding the single point of failure in the current model (assuming no underlying resilience is available).

JohnnyWong16 has identified that this cannot be configured due to current initialise script of PlexPy overwriting any user made changes to the config.ini file, as outlined in the above link and discussion on the 2nd March 2016.

**Comment by roelbeun** [comment]
I just use programs as SyncBackPro to extract the database back-up from the PlexPy directory and write it to another disk/ftp/shell etc.

The back-up is there, so maybe your use case is to specific. Next one will ask if they can be uploaded to a FTP for example.

totally agree with your opinion about using the same disk though :)

**Comment by Hellowlol** [comment]
I just store the shit on my nas with parity protection. Problem solved :P

**Comment by jelliuk** [comment]
Agreed on the points above, there are alternatives available Resilience and Third Party Applications to name but a few that would naturally cover this requirement.  This can be closed if those are deemed the acceptable route forward.  

My personal preference would be that this is managed within PlexPy rather than having a further reliance on a third party application, unfortunately under my current circumstances I have no resilience which may well be the same for other users of PlexPy (ideally later in the year I'll resolve that with my particular setup and this issue will go away anyway for me).

I'm not sure if this is niche request or whether I'm just the first to voice it and no one else has considered/been motivated too.

Either way I thought it was best to do as JonnyWong16 noted in the previous issue note referenced in the original post, happy for the devs to voice their opinion and to take their direction.

**Comment by JonnyWong16** [comment]
Yes, I asked you to open up this feature request. This will be implemented when I get to it.

Also, @Hellowlol parity =/= backup. ;)

**Comment by jelliuk** [comment]
Thanks @JonnyWong16 , I'll be quiet and leave you to it.  Appreciate the hard work yourself and everyone else devotes to the project, it really is a fantastic tool.

**Comment by Hellowlol** [comment]
@JonnyWong16 You got me here! :D I used that since he referred to a disk dieing cus parity would help but its not backup. In my case that folder is uploaded to jottacloud.com so i got that covered ;)

**Comment by JonnyWong16** [comment]
Added in v1.3.10.
