### ISSUE TITLE
IPv6 Addresses Parses Incorrectly

### ISSUE THREAD

**Issue by brettaweston** [Tautulli/Tautulli#592]
Plexpy only parses the last group of an IPv6 address. For example, if the Plex Media Server Log show 2d00:3c03::f03c:91ff:fef1:8729, Plexpy will only show 8729.

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#if-nothing-has-worked

Also PMS version?

**Comment by brettaweston** [comment]
Apologies!

**Plexpy Information**
- Version: 1.3.9
- Branch: master
- Commit hash: 65429975203f64a3b524a6e33b8584d4c0e20e9e
- Operating system: OS X 10.11.3
- Python version: 2.7.10
- What happened? Only last group parsed of IPv6 address
- What you expected? Entire IPv6 address parsed.

**PMS Information**
- Version: 0.9.16.0.1754-23623fb
- Operating system: OS X 10.11.3 (same machine)

UI example: http://imgur.com/f6q7Sej
Plexpy Log: http://pastebin.com/HqmdGmQq

**Comment by JonnyWong16** [comment]
Log file?

**Comment by JonnyWong16** [comment]
Thanks. I found the problem. It's an easy fix.

**Comment by JonnyWong16** [comment]
Fixed in v1.3.10.
