### ISSUE TITLE
[Feature Request] Add IP address to the collection of searchable fields

### ISSUE THREAD

**Issue by briankelley** [Tautulli/Tautulli#593]
I occasionally see "Plex Media Server" log entries of videos either _starting_ or _stopping_ from IP addresses that don't match any of my users. Obviously it's not the job of PlexPy to ferret out unauthorized access or bugs with the Plex product itself, but if I were able to return history items by searching for a specific IP, that would be helpful.

PS: In love with this application. I use it more than Plex itself.

**Comment by JonnyWong16** [comment]
Are you talking about the "History" table? The IP address is already searchable.

**Comment by briankelley** [comment]
I was actually talking about the search functionality found in the header. History table is good enough, thanks. Next time I'll post in the forums before opening a FR. Closing.
