### ISSUE TITLE
[Dev] Recent commit broke database saving. 

### ISSUE THREAD

**Issue by Collisionc** [Tautulli/Tautulli#596]
Noticed that my history hadn't updated since the last time I pulled the dev branch.

Basically, I'm watching a show and the the history never updates even though plexpy can see that I am watching the show and have moved on to the next one. 

I went through my debug log for plexpy to check what commit I was on before it broke, and this is a list of the commits that happened in the last git pull that I did: https://github.com/drzoidberg33/plexpy/compare/0569abd00dd71430a1bcce61feeefbdc8a196de3...c5b2b86786c20ad68c4a88b06aa43e24c5327688

I am running plexpy remotely on a headless ubuntu server, if that matters at all.

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#issues

**Comment by Collisionc** [comment]
Already done all of that, which is why I am here. Rolling back to 0569abd fixes it.

**Comment by JonnyWong16** [comment]
I was pointing you to this: https://github.com/drzoidberg33/plexpy#if-nothing-has-worked

**Comment by Collisionc** [comment]
Removed unique identifiers as well as logs before the commit, but here are the logs.
[plexpy.txt](https://github.com/drzoidberg33/plexpy/files/160642/plexpy.txt)

**Comment by Collisionc** [comment]
I don't know how plexpy's database system works, but it appears that the file 'plexpy.db-shm' is being updated, but the file 'plexpy.db' hasn't been updated since I last restarted the server.

**Comment by JonnyWong16** [comment]
Do you have the database file open in something like SQLiteBrowser?

**Comment by Collisionc** [comment]
No, I am just looking at the last modified timestamp.

**Comment by JonnyWong16** [comment]
Can you PM me your database file on the [Plex forums](http://forums.plex.tv/profile/JonnyWong16)?

**Comment by Collisionc** [comment]
Yeah, not a problem. Just sent it over.

**Comment by JonnyWong16** [comment]
Thanks. Do you know what the last entry in your history should be? Date/time/title? And what it currently shows up as?

**Comment by Collisionc** [comment]
Currently shows up as - 2016-03-05 - Started: 20:28 - Stopped - 20:48 - The Big Bang Theory - S07E07. 

Should be 2016-03-06 - Started (Roughly) 18:44 - Stopped - 19:05 - The Simpsons - 
(There are multiple streams atm, hard to tell)

**Comment by Collisionc** [comment]
Just opened up the database file to check it out, the sessions haven't been updated either. The current session list in the DB is what was playing/stopped when I updated to the latest dev commit.

**Comment by Collisionc** [comment]
Sorry for multiple posts, but here's what I see when ssh'd into my server and checking modified times. I run plexpy as the user 'plexpy' so permissions aren't an issue. :)

![2016-03-06_19-52-27](https://cloud.githubusercontent.com/assets/7837280/13558563/6235a41e-e3d5-11e5-83a2-c7ae7e052d1b.png)

**Comment by JonnyWong16** [comment]
AHA, found the bug in dev!

The `-shm` and `-wal` files usually only show up if the file is open in something else (SQLiteBrowser for example). You can try the following, but I'm not sure if will cause any negative effects.
1. In SQLiteBrowser, delete the two rows in the `sessions` table, and save the database (write changes).
2. Delete the `-shm` and `-wal` files and replace the plexpy.db file with the one you edited.

**Comment by Collisionc** [comment]
I'll backup the database and try it out. I'll let you know in a few.

**Comment by JonnyWong16** [comment]
If you screw up there's still a copy in your Plex Forum message. ;)

EDIT: I updated `dev`. Try updating and running it for a while to see if logging works.

**Comment by Collisionc** [comment]
Completed steps 1/2 and pulled the latest dev commits, still not updating history. The -shm/-wal files came back after deletion.

**Comment by JonnyWong16** [comment]
New logs and db file (while a session is in progress)?

Do the `-shm` and `-wal` files go away when PlexPy is shutdown? It might just be PlexPy using the files.

**Comment by Collisionc** [comment]
Looks like it's getting stuck at backing up the database, that's the last line of the current log, and it hasn't updated the log again in 20~ minutes.

**Comment by JonnyWong16** [comment]
I need the logs and db file.

**Comment by Collisionc** [comment]
Yep, sent.

**Comment by JonnyWong16** [comment]
I think some sessions got stuck just before you pulled the latest commits?

i.e. You replaced the db file and started PlexPy. There were currently some streams and they got added to the database. You updated PlexPy and restarted. Those broken streams from before the update are still in the database.

**Comment by Collisionc** [comment]
Oh, doh. You're right. I'll try it again.

**Comment by Collisionc** [comment]
Yep, that was it. Sorry for being an idiot! Thanks!

**Comment by JonnyWong16** [comment]
Thanks for helping out. This is why we have a dev branch. :)
