### ISSUE TITLE
[Feature Request] Fill season/episode info for one episode even if the option Group notifications is enabled

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#598]
Hi,

This function has a note:

_Note: No Season/Episode or Album/Track metadata will be available._

I want to make a recently added message with season info in it. I dont know upfront if one or multiple episodes are added. So i want to request a tag to exclude information if season info is added or not.

Something like

<_tv_>{episode_name}<**tv_single_ep**>(s{season_num00}e{episode_num00})</**tv_single_ep**></_tv_>

**Comment by JonnyWong16** [comment]
There would be no point because season/episode info will **always** be unavailable with the setting checked, thus the tag will **always** be bank no matter how many episodes are added.

**Comment by roelbeun** [comment]
So, when one episode is added, it won't show that info anyway... hmm maybe that is a good question then hehe

"Fill season/episode info even if the option Group notifications is enabled for one episode"

Possible?

**Comment by JonnyWong16** [comment]
Yes, that could be possible.

**Comment by roelbeun** [comment]
Need a seperate issue for that? Or can this one be labeled as enhancement?

**Comment by wpjiscool** [comment]
Any progress on this?

I feel it would be very useful: if you're adding episodes in bulk (e.g. back-catalogue of a TV Show), you don't want loads of separate notifications, but if a new episode is being added of a show weekly as it comes out, it would be nice for the notification to state the specific release date and episode number.

This may require extra tags to be created beyond < tv >< /tv > (e.g. < tvsingle >< /tvsingle > and < tvbulk >< /tvbulk >)

**Comment by louis-lau** [comment]
+1.

I would love to receive one notification "Season 2 of show is added" instead of a notification for each episode in the season. Even if this delays the notification.

**Comment by louis-lau** [comment]
@wpjiscool I just found out this feature is in the v2 branch, and is works! :)
