### ISSUE TITLE
Activity not logged anymore (+ no notifications)

### ISSUE THREAD

**Issue by JossiEnd** [Tautulli/Tautulli#599]
Hi all,

Since yesterday i am having an error with PlexPy. All activity isnt being logged anymore. It does notice when there is an activity. But the activity is not logged when i go to the History tab. I also dont get any notifications anymore. I should always receive a notification on Telegram when someone starts playing content. The test notification does work, so there shouldnt be a problem with the telegram connectiong.

Log file:
_Edit: See below for detailed specs_

**Comment by JonnyWong16** [comment]
Please provide all the requested info: https://github.com/drzoidberg33/plexpy#issues

**Comment by JossiEnd** [comment]
Oh sorry about that:

Version: 1.3.9
Branch: master
Commit hash: 65429975203f64a3b524a6e33b8584d4c0e20e9e
OS: Windows 10 Pro (64-bit)
Python version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]

What you did?:
Nothing in particular. Yesterday at 18.00 PM notifications and logging worked fine. Later that evening not anymore. I might have restarted my computer in between, unfortunately i cant remember excatly. I looked at Windows Update history for yesterday and only say these updates:
Update for Microsoft Visual C++ 2012 Update 4 Redistributable Package (KB3119142)

What happened?
No notifications or logging anymore.

What you expected: N/A
How can we reproduce your issue? N/A

What are your (relevant) settings?
Notifications are received with Telegram when content is started playing
Test notification with Telegram works fine

Logfile (including reboot)
https://gist.github.com/JossiEnd/e629c1d1a314ee74734a

**Comment by JonnyWong16** [comment]
Thanks. Any earlier logs as well?

I think there is a corrupt session stuck in your database. You can try this:

Shut down PlexPy and create a backup of your `plexpy.db` file. Open your `plexpy.db` file using [SQLiteBrowser](http://sqlitebrowser.org/) and delete all the rows in the `sessions` table and save the database (write changes). Then restart PlexPy.

**Comment by rthunter** [comment]
I was having the exact same issue as @JossiEnd and deleting the rows from the `sessions` table fixed it for me. Thanks so much @JonnyWong16

**Comment by JossiEnd** [comment]
Yes! Thanks. That did the trick. Receiving notifications again and history is being logged!
