### ISSUE TITLE
Libraries Media Info view only shows up to 10 seasons per TV show, 10 episodes per season

### ISSUE THREAD

**Issue by deepseth** [Tautulli/Tautulli#602]
When browsing the Media Info view of a library, when expanding a TV show that has more than 10 seasons, only the first 10 seasons are displayed.

When expanding a season that has more than 10 episodes, only the first 10 episodes are displayed.

When viewing a specific episode, there's no media info displayed on the page showing the poster / plot synopsis / people who have viewed it, so there's no way to view the media info for any episode >10 through PlexPy at the moment.

**Comment by JonnyWong16** [comment]
Can you provide this info: https://github.com/drzoidberg33/plexpy/blob/master/README.md#issues

There should be page buttons for any season or episode list greatest than 10 items. Can you provide screenshots of the pages (expanded media info table) and the episode page)?

**Comment by deepseth** [comment]
Version: 1.3.9
 Branch: master
 Commit hash: 65429975203f64a3b524a6e33b8584d4c0e20e9e
 Operating system: Linux 3.2.0-4-amd64 (debian 7 wheezy)
 Python version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]

You're absolutely right, there are page buttons. Looks like a rendering issue. A lot worse in Safari than Chrome.

Both tested on OS X El Capitan version 10.11.3 (15D21)

Sreenshots for Safari version 9.0.3 (11601.4.4)

Safari season view, can see half of the paging buttons
![safari-season-half-good-half-bad](https://cloud.githubusercontent.com/assets/235387/13639182/6e5c4066-e607-11e5-91ab-3b253ee3b9b6.png)
Safari episode view, cant see any paging buttons at all anymore, lost a bunch of other info about episode counts viewed and dates in the seasons
![safari-episode-bad](https://cloud.githubusercontent.com/assets/235387/13639181/6e56142a-e607-11e5-92b4-47bc6aeae332.png)

Screenshots for Chrome version 48.0.2564.116 (64-bit)
Chrome season view, can see the paging buttons
![chrome-season-good](https://cloud.githubusercontent.com/assets/235387/13639183/6ecdcefc-e607-11e5-91d6-9b1d8410cfdd.png)

Chrome episode view, can partially see the paging buttons, lost a bunch of other info about episode counts viewed and dates in the seasons
![chrome-episode-bad](https://cloud.githubusercontent.com/assets/235387/13639179/6e1d933e-e607-11e5-9526-2bb6ef750072.png)

**Comment by JonnyWong16** [comment]
@deepseth Not sure if this is fixed in v1.4.0. Can you let me know?

**Comment by deepseth** [comment]
There's a scrollbar at the bottom now that lets you scroll across and see the hidden information.
Not ideal but still a good enough solution.
Thanks.

**Comment by JonnyWong16** [comment]
What is your screen resolution?

**Comment by deepseth** [comment]
1440x900 (13" MacBook Air)

**Comment by xorinzor** [comment]
Mine doesn't even show the episodes in a list like yours does, whenever I go to:
libraries -> TV Shows -> media info -> `<any tv show>`

It shows me a poster-style list of the seasons with a list of "watch history" below that, when clicking a season I get a media-thumb-style list of the episodes with again below that a list of the "watch history".

Would be great if this could be fixed so I can see what the containers, bitrates, etc. of these episodes are (ideally without dividing them into shows/seasons, but just as happens with the movies all of them in 1 list)

![screenshot 3](https://cloud.githubusercontent.com/assets/4212335/19021984/f8a8d9c8-88cd-11e6-8ab8-df7ace6384cf.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/4212335/19021985/fad11bd4-88cd-11e6-92a1-dd126814c445.png)

**Comment by JonnyWong16** [comment]
You're clicking the wrong spot 
![image](https://cloud.githubusercontent.com/assets/9099342/19022054/d80ccce6-8883-11e6-9529-77a7bf2800c2.png)

**Comment by xorinzor** [comment]
I clicked on that, but as soon as I click on my tv show, adventure time for example, this happens.

![screenshot 5](https://cloud.githubusercontent.com/assets/4212335/19022081/c70469e4-88cf-11e6-8242-4e4f694bf12d.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/4212335/19022083/c8ccb006-88cf-11e6-8791-dda0cc6d8fe8.png)

**Comment by JonnyWong16** [comment]
![image](https://cloud.githubusercontent.com/assets/9099342/19022092/8725edfc-8884-11e6-8e7a-64683a04f1c2.png)

**Comment by xorinzor** [comment]
Ah. I never noticed those were collapsable, perhaps something worth changing in a future version (or adding an expand-all option)

Thanks!

**Comment by JonnyWong16** [comment]
No votes: http://feathub.com/JonnyWong16/plexpy/+46
