### ISSUE TITLE
"Last Watched" Not updating

### ISSUE THREAD

**Issue by elloboloco** [Tautulli/Tautulli#603]
As of March 5 my "last watched" hasn't been updated. I still still shows as they are streaming the now playing area, but once finished last watched doesn't update.

**Comment by JonnyWong16** [comment]
Have the steams exceeded the "Watched Percent" specified in the settings?

**Comment by elloboloco** [comment]
Actually, I just did some more digging and NONE of my watched shows are being recorded. My graph shows 0 watched items starting March 6. Even though my PMS streams between 50 and 90 shows a day.

**Comment by JonnyWong16** [comment]
Please provide this info: https://github.com/drzoidberg33/plexpy#issues

**Comment by elloboloco** [comment]
Version - 1.3.9
 Branch - Dev
 Commit hash - d4eed9f8fd8f094cd1cb2175526a1bfd2b67803d
 Operating system - Win 7
 Python version - 2.7
 What you did? - Nothing
 What happened? - Stopped recording watched shows. No History, No Graph, No Last Watched
 What you expected? - 
 How can we reproduce your issue? - Not sure. 
 What are your (relevant) settings? - ?

http://pastebin.com/raw/0eRcqRm9

**Comment by JonnyWong16** [comment]
Oh you're on Dev. There was an update to Dev that broke logging. 

Try going here then try again. 

```
http://localhost:8181/delete_temp_sessions
```

**Comment by elloboloco** [comment]
That fixed it! Thanks!

**Comment by 12nick12** [comment]
Thank you so much. Every time I need help and you respond so quick it reminds me why your the only person I donate to haha.
