### ISSUE TITLE
401 error for /status/sessions

### ISSUE THREAD

**Issue by tepkel** [Tautulli/Tautulli#604]
I did my best to search open issues, but the only one that looked similar is [292](https://github.com/drzoidberg33/plexpy/issues/292), which was closed without a good resolution. Sorry if this is a dupe.

Longstanding Plex server, new PlexPy install.

I see an error "There was an error communicating with your Plex Server. Please check your settings."

I cleared the log, and flipped back to home. Here are the resulting logs:

> 2016-03-09 22:11:12   WARNING Unable to retrieve data for get_recently_added.
> 2016-03-09 22:11:12 WARNING PlexPy Pmsconnect :: Unable to parse XML for get_sessions: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2016-03-09 22:11:12 WARNING PlexPy Pmsconnect :: Unable to parse XML for get_recently_added: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2016-03-09 22:11:12 WARNING Failed to access uri endpoint /status/sessions. Status code 401
> 2016-03-09 22:11:12 WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=10. Status code 401
> 2016-03-09 22:11:11 WARNING Unable to retrieve data for get_current_activity_header.
> 2016-03-09 22:11:11 WARNING PlexPy Pmsconnect :: Unable to parse XML for get_sessions: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2016-03-09 22:11:11 WARNING Failed to access uri endpoint /status/sessions. Status code 401
> 2016-03-09 22:11:09 INFO    Web logs cleared

Second go around with clearing and refreshing. Slightly different results. Same general problem:

> 2016-03-09 22:16:59    WARNING Unable to retrieve data for get_current_activity_header.
> 2016-03-09 22:16:59 WARNING Unable to retrieve data for get_recently_added.
> 2016-03-09 22:16:59 WARNING PlexPy Pmsconnect :: Unable to parse XML for get_sessions: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2016-03-09 22:16:59 WARNING PlexPy Pmsconnect :: Unable to parse XML for get_sessions: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2016-03-09 22:16:59 WARNING PlexPy Pmsconnect :: Unable to parse XML for get_recently_added: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2016-03-09 22:16:59 WARNING Failed to access uri endpoint /status/sessions. Status code 401
> 2016-03-09 22:16:59 WARNING Failed to access uri endpoint /status/sessions. Status code 401
> 2016-03-09 22:16:59 WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=10. Status code 401
> 2016-03-09 22:16:55 INFO    Web logs cleared

`Version 1.3.9`
 `Branch master`
 `Commit hash 65429975203f64a3b524a6e33b8584d4c0e20e9e`
 `Operating system  Windows 10`
 `Python version 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`

**Comment by JonnyWong16** [comment]
Status code 401 usually means authentication error. Try fetching a new Plex token in the PlexPy settings.

**Comment by tepkel** [comment]
I had tried this a coupe times prior to this post, and just tried it again without luck. :-(

The method I am using is:
-Remove PlexPy device from plex server.
-On PlexPy, Click "fetch token" on the Plex.tv account tab of settings
-Validate that the token string has changed.

Anything I am doing incorrectly in this process?

**Comment by JonnyWong16** [comment]
That sounds right.

Can you access this page with the new token?

```
http://plex_ip:32400/status/sessions?X-Plex-Token=your_plex_token
```

**Comment by tepkel** [comment]
No, I get a 401 error.

**Comment by JonnyWong16** [comment]
What if you try to get a token manually? Instructions here: https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token

**Comment by tepkel** [comment]
I see a different token string. Probably the one for my browser device?

If I plug this into PlexPy manually, everything seems hunky dory. Starts working. Nothing glaringly wrong jumping out at me from the logs anyway.

Am I OK using this as a workaround on an ongoing basis?

**Comment by JonnyWong16** [comment]
Yeah, that would be the token for your browser. Weird that the PlexPy token doesn't work though.

**Comment by tepkel** [comment]
Awesome. Thanks for the quick help!

Want me to close this? Or keep it around to look into what's up with the tokens being fetched from PlexPy?

**Comment by JonnyWong16** [comment]
Just leave it for now.

**Comment by ctmlr** [comment]
@JonnyWong16 I tried your workaround by manually setting the token but this didn't work for me. I'm having the same issue as OP.

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#if-nothing-has-worked
