### ISSUE TITLE
using external server.key and server.crt files

### ISSUE THREAD

**Issue by zenjabba** [Tautulli/Tautulli#605]
I have domain validated ssl certificates, and I'm trying to incorporate them into plexpy for https sessions. Every time I change the config file, it seems to revert back to the self signed certificates. 

Any thoughts?

**Comment by JonnyWong16** [comment]
Settings > Web Interface > Check "Enable HTTPS", uncheck "Create Self-signed Certificate", and specify the location of your cert and key.

**Comment by zenjabba** [comment]
Yup, I was doing that, screen shots attached

<img width="779" alt="screen shot 2016-03-10 at 7 53 34 pm" src="https://cloud.githubusercontent.com/assets/679864/13689841/eab811d8-e6f9-11e5-9487-1b2be14c13c7.png">
<img width="491" alt="screen shot 2016-03-10 at 7 53 58 pm" src="https://cloud.githubusercontent.com/assets/679864/13689843/ec4e318a-e6f9-11e5-80da-0dfe6f94bc49.png">

**Comment by JonnyWong16** [comment]
Can you provide this info: https://github.com/drzoidberg33/plexpy#issues

**Comment by zenjabba** [comment]
https://drive.google.com/a/thethompsonfamily.com.au/file/d/0B7sWKKWrBgqbSWNVWGI1bTRMUm8/view?usp=sharing

Git Branch: master
Git Commit Hash:    65429975203f64a3b524a6e33b8584d4c0e20e9e
Configuration File: /opt/plexpy/config.ini
Database File:  /opt/plexpy/plexpy.db
Backup Directory:   /opt/plexpy/backups
Cache Directory:    /opt/plexpy/cache
Log Directory:  /opt/plexpy/logs
Arguments:  ['--daemon', '--nolaunch', '--quiet']
Platform:   Linux 3.10.0-327.10.1.el7.x86_64
Python Version: 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

**Comment by JonnyWong16** [comment]
I can't view that file.

**Comment by zenjabba** [comment]
Fixed, forgot to set all with link can read.

**Comment by JonnyWong16** [comment]
It looks like it only generated the self-signed certificate once. How many times did you try it? When you say it reverts back, does the path to the cert/key change?

**Comment by zenjabba** [comment]
I can confirm that the paths are still as per the screenshot. I have restarted the service and checked in another browser

<img width="540" alt="screen shot 2016-03-10 at 9 57 08 pm" src="https://cloud.githubusercontent.com/assets/679864/13691952/11d0202e-e70b-11e5-8036-30f311a67b0c.png">

**Comment by JonnyWong16** [comment]
Did PlexPy overwrite your certificate?

**Comment by zenjabba** [comment]
Negative, it isn't overwriting the files, and I can confirm the certificate files are readable
-rw-r--r--. 1 root root 1704 Mar 10 19:51 privkey2.pem

I can also confirm I have deleted the server.crt and server.key file from /opt/plexpy and it still seems to be finding it from somewhere.

**Comment by JonnyWong16** [comment]
That's weird. Have you restarted your browser? Maybe it got cached?

**Comment by zenjabba** [comment]
Restarted the Browser, used a different browser, even used a different computer outside of my home network. same issue.

Feel free to connect to https://kermit.zarack.com:8181/ and you can see the self signed certificate.

Weird problem.

**Comment by JonnyWong16** [comment]
Try this:
1. Leave HTTPS enabled.
2. Remove your certificate and key from the folder.
3. Start PlexPy.
4. Check the logs to see if it says "Disabled HTTPS because of missing certificate and key."

Then we know that it is looking in the correct folder.

**Comment by zenjabba** [comment]
11-Mar-2016 11:42:07 - ERROR   :: HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "/opt/plexpy/plexpy/logger.py", line 221, in new_run
    old_run(_args, *_kwargs)
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/opt/plexpy/lib/cherrypy/process/servers.py", line 206, in _start_http_thread
    self.httpserver.start()
  File "/opt/plexpy/lib/cherrypy/wsgiserver/wsgiserver2.py", line 1946, in start
    self.bind(af, socktype, proto)
  File "/opt/plexpy/lib/cherrypy/wsgiserver/wsgiserver2.py", line 2000, in bind
    self.socket = self.ssl_adapter.bind(self.socket)
  File "/opt/plexpy/lib/cherrypy/wsgiserver/ssl_pyopenssl.py", line 180, in bind
    self.context = self.get_context()
  File "/opt/plexpy/lib/cherrypy/wsgiserver/ssl_pyopenssl.py", line 193, in get_context
    c.use_privatekey_file(self.private_key)
Error: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_PrivateKey_file', 'PEM lib')]

11-Mar-2016 11:42:07 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/opt/plexpy/PlexPy.py", line 232, in <module>
    main()
  File "/opt/plexpy/PlexPy.py", line 191, in main
    webstart.initialize(web_config)
  File "/opt/plexpy/plexpy/webstart.py", line 122, in initialize
    cherrypy.server.start()
  File "/opt/plexpy/lib/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/opt/plexpy/lib/cherrypy/process/servers.py", line 177, in start
    self.wait()
  File "/opt/plexpy/lib/cherrypy/process/servers.py", line 227, in wait
    raise self.interrupt
Error: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_PrivateKey_file', 'PEM lib')]

**Comment by JonnyWong16** [comment]
Okay....that was unexpected...

Can you post the rest of the log file?

**Comment by zenjabba** [comment]
Ok, new update... 

I removed the filename for the certificates and only had a directory which caused that error. I fixed the error and now reposting the logs

11-Mar-2016 11:56:33 - INFO    :: CP Server Thread-10 : Writing configuration to file
11-Mar-2016 11:56:33 - DEBUG   :: CP Server Thread-10 : Generating self-signed SSL certificate.
11-Mar-2016 11:56:35 - INFO    :: MainThread : Received signal: restart
11-Mar-2016 11:56:45 - INFO    :: MainThread : Writing configuration to file
11-Mar-2016 11:56:45 - INFO    :: MainThread : PlexPy is restarting...
11-Mar-2016 11:56:45 - INFO    :: MainThread : Restarting PlexPy with ['/usr/local/bin/python', '/opt/plexpy/PlexPy.py', '--daemon', '--nolaunch', '--quiet']
11-Mar-2016 11:56:46 - INFO    :: MainThread : Checking to see if the database has all tables....
11-Mar-2016 11:56:46 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
11-Mar-2016 11:56:46 - DEBUG   :: MainThread : Git output: 65429975203f64a3b524a6e33b8584d4c0e20e9e
11-Mar-2016 11:56:46 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/plexpy
11-Mar-2016 11:56:46 - DEBUG   :: MainThread : Git output: master
11-Mar-2016 11:56:46 - INFO    :: MainThread : Retrieving latest version information from GitHub
11-Mar-2016 11:56:46 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
11-Mar-2016 11:56:47 - DEBUG   :: MainThread : Latest version is 65429975203f64a3b524a6e33b8584d4c0e20e9e
11-Mar-2016 11:56:47 - INFO    :: MainThread : PlexPy is up to date
11-Mar-2016 11:56:47 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
11-Mar-2016 11:56:47 - INFO    :: MainThread : Writing configuration to file
11-Mar-2016 11:56:58 - INFO    :: MainThread : Writing configuration to file
11-Mar-2016 11:56:58 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
11-Mar-2016 11:56:58 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
11-Mar-2016 11:57:00 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
11-Mar-2016 11:57:00 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
11-Mar-2016 11:57:02 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
11-Mar-2016 11:57:02 - INFO    :: MainThread : Starting PlexPy web server on https://0.0.0.0:8181/
11-Mar-2016 11:57:02 - INFO    :: MainThread : Web server authentication is enabled, username is 'zenjabba'
11-Mar-2016 11:57:02 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
11-Mar-2016 11:57:02 - INFO    :: MainThread : Scheduled background task: Refresh Plex server URLs
11-Mar-2016 11:57:02 - INFO    :: MainThread : Scheduled background task: Refresh Plex server name
11-Mar-2016 11:57:02 - INFO    :: MainThread : Scheduled background task: Check for Plex remote access
11-Mar-2016 11:57:02 - INFO    :: MainThread : Scheduled background task: Refresh users list
11-Mar-2016 11:57:02 - INFO    :: MainThread : Scheduled background task: Refresh libraries list
11-Mar-2016 11:57:02 - INFO    :: MainThread : Scheduled background task: Backup PlexPy database
11-Mar-2016 11:57:02 - INFO    :: Thread-12 : PlexPy WebSocket :: Opening websocket, connection attempt 1.
11-Mar-2016 11:57:02 - INFO    :: Thread-12 : PlexPy WebSocket :: Ready

**Comment by JonnyWong16** [comment]
So the files are specified in the PlexPy settings, but the actual files are missing from the folder, yet it still started successfully...

I don't know where PlexPy could be pulling the files from? Double check that there are no certificates/keys in the PlexPy directory?

**Comment by Arcanemagus** [comment]
You should also try setting the permissions on your key files properly, they should only be readable by the user that plexpy is running as, not world readable. I would guess that this is why they are being ignored.

**Comment by zenjabba** [comment]
I changed the configuration to /tmp/fullchain.pem and /tmp/privkey.pem and can 100% confirm they don't exist.

**Comment by JonnyWong16** [comment]
I just noticed this line

```
11-Mar-2016 11:56:33 - DEBUG :: CP Server Thread-10 : Generating self-signed SSL certificate
```

So PlexPy did recreate the certificates.

**Comment by zenjabba** [comment]
@Arcanemagus I've thought of that, and I'm testing as root

**Comment by JonnyWong16** [comment]
I'm wondering if this is related to this commit fe10170826225a164e4e81965440ea7be47f2888 on `dev`.

Maybe try the `dev` branch?

**Comment by zenjabba** [comment]
@JonnyWong16 how do I convert to dev branch

**Comment by JonnyWong16** [comment]
Run in the PlexPy directory

```
git fetch
git checkout dev
```

**Comment by zenjabba** [comment]
No difference.

11-Mar-2016 12:28:15 - INFO    :: MainThread : Received signal: restart
11-Mar-2016 12:28:21 - INFO    :: MainThread : Writing configuration to file
11-Mar-2016 12:28:21 - INFO    :: MainThread : PlexPy is restarting...
11-Mar-2016 12:28:21 - INFO    :: MainThread : Restarting PlexPy with ['/usr/local/bin/python', '/opt/plexpy/PlexPy.py', '--daemon', '--nolaunch', '--quiet']
11-Mar-2016 12:28:22 - INFO    :: MainThread : Checking to see if the database has all tables....
11-Mar-2016 12:28:22 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
11-Mar-2016 12:28:22 - DEBUG   :: MainThread : Git output: d4eed9f8fd8f094cd1cb2175526a1bfd2b67803d
11-Mar-2016 12:28:22 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/plexpy
11-Mar-2016 12:28:22 - DEBUG   :: MainThread : Git output: dev
11-Mar-2016 12:28:22 - INFO    :: MainThread : Retrieving latest version information from GitHub
11-Mar-2016 12:28:22 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/dev
11-Mar-2016 12:28:22 - DEBUG   :: MainThread : Latest version is d4eed9f8fd8f094cd1cb2175526a1bfd2b67803d
11-Mar-2016 12:28:22 - INFO    :: MainThread : PlexPy is up to date
11-Mar-2016 12:28:22 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
11-Mar-2016 12:28:22 - INFO    :: MainThread : Writing configuration to file
11-Mar-2016 12:28:26 - INFO    :: MainThread : Writing configuration to file
11-Mar-2016 12:28:26 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
11-Mar-2016 12:28:26 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
11-Mar-2016 12:28:33 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
11-Mar-2016 12:28:33 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
11-Mar-2016 12:28:35 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
11-Mar-2016 12:28:35 - INFO    :: MainThread : Starting PlexPy web server on https://0.0.0.0:8181/
11-Mar-2016 12:28:35 - INFO    :: MainThread : Web server authentication is enabled, username is 'zenjabba'
11-Mar-2016 12:28:35 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
11-Mar-2016 12:28:35 - INFO    :: MainThread : Scheduled background task: Refresh Plex server URLs
11-Mar-2016 12:28:35 - INFO    :: MainThread : Scheduled background task: Refresh Plex server name
11-Mar-2016 12:28:35 - INFO    :: MainThread : Scheduled background task: Check for Plex remote access
11-Mar-2016 12:28:35 - INFO    :: MainThread : Scheduled background task: Refresh users list
11-Mar-2016 12:28:35 - INFO    :: MainThread : Scheduled background task: Refresh libraries list
11-Mar-2016 12:28:35 - INFO    :: MainThread : Scheduled background task: Backup PlexPy database
11-Mar-2016 12:28:35 - INFO    :: Thread-12 : PlexPy WebSocket :: Opening websocket, connection attempt 1.
11-Mar-2016 12:28:35 - INFO    :: Thread-12 : PlexPy WebSocket :: Ready

**Comment by JonnyWong16** [comment]
Did you set the certificate back to your own?

**Comment by zenjabba** [comment]
Sure did, and the PlexPy restarted itself after I configured it.

**Comment by JonnyWong16** [comment]
I really think PlexPy overwrote your own certificates...Same file name, but the contents are changed.

**Comment by zenjabba** [comment]
re-downloaded the certificates, and bingo... you are correct

**Comment by JonnyWong16** [comment]
Ok. I think this should be fixed with the dev commit i mentioned above, so PlexPy won't overwrite the certificates.

If you want to switch back to master

```
git checkout master
```

But PlexPy will overwrite your certificates again. So maybe stay on dev until the next release.

**Comment by zenjabba** [comment]
No moving :) I’ll wait a few weeks till dev gets migrated into master.
