### ISSUE TITLE
[Feature request] Update Facebook api to fetch website previews

### ISSUE THREAD

**Issue by joewalch** [Tautulli/Tautulli#608]
Is it possible to update the Facebook api to fetch website previews for the group post, currently only a link is displayed. 

info here:

http://stackoverflow.com/questions/16286879/i-want-to-create-post-with-web-site-preview

Also IMDB recommends a   /    at the end of links for speed. Not there currently.

**Comment by JonnyWong16** [comment]
It should have the poster image with the link.

And thanks for the tip about the trailing `/`.

**Comment by joewalch** [comment]
Currently I use:

{summary}
{imdb_url}/
{poster_url}

Which produces this on FB:

![facebook](https://cloud.githubusercontent.com/assets/15211061/13749854/05a06f82-e9fb-11e5-93da-391326371aae.PNG)

And this on telegram:

![telegram](https://cloud.githubusercontent.com/assets/15211061/13749862/0f4836be-e9fb-11e5-9f6a-5674ab7ac175.PNG)

It would seem a little tidier if the imdb preview came through without the need to use {summary} & {poster_url}

**Comment by JonnyWong16** [comment]
Summary added to Facebook posts in v1.3.12.
