### ISSUE TITLE
PlexPy username and password changing in Windows 10

### ISSUE THREAD

**Issue by joewalch** [Tautulli/Tautulli#609]
Now and again the PlexPy username and password will change in the Config.ini to my Microsoft username and password used to access W10. Anyone know why this would be and how to stop it?

**Comment by Hellowlol** [comment]
Clear you password manager for the plexpy url

**Comment by joewalch** [comment]
Is this in Config.ini or somewhere else? 

Or do you mean in the browser? If so the change is made to config.ini, the browser password is unchanged.

**Comment by JonnyWong16** [comment]
You mean the "HTTP Username" and "HTTP Password" under Settings > Access Control?

**Comment by joewalch** [comment]
In my
config.ini the "HTTP Username' gets changed to the W10 username and the Plex password gets changed to the W10 password. 

There is no entry in there for HTTP Password. 

These are the entries in settings>access control.
