### ISSUE TITLE
[Feature Request] Notify on Pause/Resume

### ISSUE THREAD

**Issue by mrchops1024** [Tautulli/Tautulli#61]
I've spent the past couple hours testing this, so I hope my observations are expected behavior. All my testing was done via the Plex Web Player in Firefox. I'm also in the process of converting from plexWatch so i've been trying to match up my notifications.

If I start playing a movie, both PlexPy and plexWatch send me a notification. If I pause the movie, only plexWatch notifies me (stating that it's been paused). Same thing with resuming, only plexWatch notifies me. Only if I completey close out the movie does PlexPy notify me that the movie has been stopped.

I notice that the proper "Paused" status shows up in the activity section. Is it possible to add in notifications for Paused/Resumed?

**Comment by drzoidberg33** [comment]
Yep. This is going to be added going forward.

Was going to open a request for it but now you've done it for me :smile:

**Comment by mrchops1024** [comment]
Oh, perfect. When something for it gets pushed into dev, I'm more than happy to help test it out.

**Comment by drzoidberg33** [comment]
Pushed to dev branch, feel free to test.

Commit: https://github.com/drzoidberg33/plexpy/commit/a96482ee3ce4a257ffa7cd6467a50832e96f23b9

**Comment by drzoidberg33** [comment]
Released in v1.1.0

https://github.com/drzoidberg33/plexpy/releases/tag/v1.1.0
