### ISSUE TITLE
PlexPy slack test works but notifications do not get sent

### ISSUE THREAD

**Issue by seitzbg** [Tautulli/Tautulli#610]
I have enabled the Slack notifier and I see events happen in the logs.  The test also works however none of the events make it to Slack.  Please advise.

**Comment by JonnyWong16** [comment]
Have you read the FAQ? https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#cat1-q5

**Comment by seitzbg** [comment]
Of course I have :)

https://www.bsd-unix.net/seitz/screenshots/firefox_2016-03-15_15-38-39.png

**Comment by JonnyWong16** [comment]
Can you provide all this info? https://github.com/drzoidberg33/plexpy#issues

**Comment by seitzbg** [comment]
Version: 1.3.10
Branch: Master
Commit hash: 08537c1d69cacfdb3461a7d916dca5043e03706f
Operating system: CentOS 7.2 x86_64
Python version: 2.7.5
What you did? Set up notifications, the tests for email/slack.
What happened? Test triggers worked, no other notifications were sent
What you expected? Notifications to be sent on the actions I ran through in Plex
How can we reproduce your issue? Not sure
What are your (relevant) settings? Slack/Email notifications (tests both work) on start/stop/down/updates
Include a link to your FULL (not just a few lines!) log file that has the error. Please use Gist or Pastebin: https://www.bsd-unix.net/seitz/private/plexpy.log

**Comment by JonnyWong16** [comment]
Does the notification show up under Logs > Notification Logs?

**Comment by seitzbg** [comment]
Nothing shows up in the notification logs panel.

**Comment by seitzbg** [comment]
I see notifications now for shows being added but not for playback started etc... (And those are checked too)

**Comment by JonnyWong16** [comment]
Post your new logs.

**Comment by seitzbg** [comment]
```
15-Mar-2016 19:00:15 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 6684 has been added to Plex.
15-Mar-2016 19:00:16 - INFO    :: Thread-22 : PlexPy Notifiers :: Email notification sent.
15-Mar-2016 19:00:17 - INFO    :: Thread-22 : PlexPy Notifiers :: Slack notification sent.
```

**Comment by JonnyWong16** [comment]
I need more than that.

**Comment by seitzbg** [comment]
https://www.bsd-unix.net/seitz/private/plexpy.log

**Comment by JonnyWong16** [comment]
Still looks fine. Are global notification toggles enabled (Settings > Notifications)?

**Comment by seitzbg** [comment]
That was it... thanks for the help!

**Comment by spacecakes** [comment]
I'm having the same issue. Test works but nothing shows up in the Slack channel or the logs. Global notifications are enabled.
