### ISSUE TITLE
Service won't start on FreeNAS

### ISSUE THREAD

**Issue by my95z34** [Tautulli/Tautulli#615]
Using the guide in the wiki, I get this error when trying to start the service

```
root@plexpy:/ # service plexpy start
Starting plexpy.
env: python: No such file or directory
/etc/rc.d/plexpy: WARNING: failed to start plexpy
root@plexpy:/ # 
```

I can manually run python2 PlexPy.py from the dir and it runs fine, so it's something with the startup script.  I've tried to symlink python2 all over the place, but can't seem to get it.

Any ideas?

**Comment by JonnyWong16** [comment]
Symlinked with this?

```
ln -s /usr/local/bin/python2 /usr/local/bin/python
```

To help us out with #607, can you tell us what FreeNAS version and type of jail you are using?

**Comment by my95z34** [comment]
Son of a bitch.  I set it up on my server a few months ago, and remember having to symlink something.  Now that I'm setting it up on my mom's server I couldn't remember what it was....  But that's the one symlink I didn't try.  I was keeping the python2 name and that appears to be the issue.

FreeNAS version is 9.3 (the latest stable).  And jail type is Standard from : http://download.freenas.org/jails/9.3/x64/

That symlink fixed it btw.  Thanks!
