### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by Ninja-FSE** [Tautulli/Tautulli#616]
I dont know if this is a plexpy error or a PMS error, but im trying to get plexpy to notificate on facebook when new files are added to the libary (all other stuff is working like, playing and all other). But when i do a libary refresh im not getting any posts on facebook and im getting this error message below.

```
Uncaught exception: Traceback (most recent call last):
File "/usr/local/share/plexpy/plexpy/logger.py", line 246, in new_run
old_run(*args, **kwargs)
File "/usr/local/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/share/plexpy/plexpy/notification_handler.py", line 298, in notify_timeline
agent_id=agent['id'])
File "/usr/local/share/plexpy/plexpy/notification_handler.py", line 630, in build_notify_text
os.path.join(plexpy.CONFIG.CACHE_DIR, 'cache-poster.jpg'))
File "/usr/local/lib/python2.7/urllib.py", line 98, in urlretrieve
return opener.retrieve(url, filename, reporthook, data)
File "/usr/local/lib/python2.7/urllib.py", line 245, in retrieve
fp = self.open(url, data)
File "/usr/local/lib/python2.7/urllib.py", line 213, in open
return getattr(self, name)(url)
File "/usr/local/lib/python2.7/urllib.py", line 469, in open_file
return self.open_local_file(url)
File "/usr/local/lib/python2.7/urllib.py", line 483, in open_local_file
raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: '/library/metadata/201/thumb/1458329034?X-Plex-Token=********6h'
```

What is this error? 

Git Branch: master
Git Commit Hash:    de16fe5108c094792b1de2bb338000f7d26530ea
Platform:   FreeBSD 9.3-RELEASE-p31 (FreeNAS 9.3-Stable)
Python Version: 2.7.11 (default, Mar 12 2016, 02:21:34) [GCC 4.2.1 20070831 patched [FreeBSD]]

This is a new install with PMS on same system/jail, all updated

**Comment by JonnyWong16** [comment]
That error is extremely difficult to read.

Post your complete logs.

Also, that commit hash doesn't match any PlexPy release version.

**Comment by Ninja-FSE** [comment]
That is the log :/

**Comment by JonnyWong16** [comment]
I mean post your entire log file to [pastebin](http://pastebin.com) or [gist](https://gist.github.com/), not just that one error. It's very hard to tell what's going on without all the info and proper formatting.

The location of the log file is listed on the "Help & Info" page.

**Comment by Ninja-FSE** [comment]
aha, sorry 

Here you have a pastebin: [http://pastebin.com/hkn8edse](http://pastebin.com/hkn8edse)

**Comment by Arcanemagus** [comment]
@apax0r if you wrap the text like this:
```
raw text
block
```

```
raw text
block
```

Instead of this:
`
raw text
block
`
`
raw text
block
`

Then the line breaks and indentation will be preserved (making this much more readable).

@JonnyWong16 I believe collaborators should have permissions to edit issue comments, I often just fix that for people so I can read things like that. That might require admin permissions though :confused:.

**Comment by JonnyWong16** [comment]
Oh, haha. I can edit comments. Still better with complete logs though.

@apax0r That's still not the full logs.

**Comment by Ninja-FSE** [comment]
@Arcanemagus thanks for the tip! didnt know about that one!

**Comment by Ninja-FSE** [comment]
... [http://pastebin.com/PzDhQQNM](http://pastebin.com/PzDhQQNM) <-- thats the hole .log file but i cant see why you need the hole log, the error i paste here is in that log several times...

**Comment by Arcanemagus** [comment]
@apax0r Often the context of an error is just as important as the error itself, what is (or isn't!) in the log can be important in figuring out what is going on.

**Comment by Ninja-FSE** [comment]
okey, you have a point, all i see is the "same" error, but for diffrent media file that beeing updated to the libary.. :D

**Comment by JonnyWong16** [comment]
I need the complete logs because then I can see lines like this:

```
18-Mar-2016 16:31:35 - WARNING :: CP Server Thread-3 : PlexPy PlexTV :: Unable to retrieve server URLs. Using user-defined value.
```

which indicate that you probably have your PMS configured incorrectly in PlexPy.

And lines these lines:

```
18-Mar-2016 20:08:48 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/compare/cbf3488de95bfa43ad5b4ec95d37bd219ece4f5c...de16fe5108c094792b1de2bb338000f7d26530ea
18-Mar-2016 20:08:49 - INFO    :: MainThread : Cannot compare versions. Are you running a local development version?
```

mean that your PlexPy install somehow branched off on it's own. Run

```
git reset --hard HEAD
```

to set it back to `master`.

**Comment by Ninja-FSE** [comment]
```
root@plexpy:/usr/local/share/plexpy # git reset --hard HEAD
HEAD is now at de16fe5 Merge branch 'dev' of https://github.com/drzoidberg33/plexpy

```

and in plexpy settings page (after a restart of plexpy) says im on master, but the "git reset --hard HEAD" says im dev?

how should i configure plexpy, i've added the IP (in the same jail) and port..

**Comment by JonnyWong16** [comment]
Hmm.. that's still not the correct hash. Try

```
git reset --hard cbf3488
```

If it's in the same jail, just use `localhost` or `127.0.0.1`.

**Comment by Ninja-FSE** [comment]
that didnt work either, so i went the easy way, i reinstalled plexpy.. and now everything is working! :) awesome program i must say with a yoda influence :+1:

**Comment by Arcanemagus** [comment]
Btw, you probably needed to do a `git fetch` or `git pull` first, you may not have had the current state of the branch. Re-installing would have done this as well though :wink:.
