### ISSUE TITLE
Feature Request: (Anti) User account sharing

### ISSUE THREAD

**Issue by jkaberg** [Tautulli/Tautulli#617]
I'd love to see an option which would tell me who of my users are suspected of shareing their accounts

While I can do this manually, it'd be a lot nicer just to have an small indication in the dashboard where I can view suspected users :-)

I was thinking of detection methods, and while not 100% accurate two would be GeoIP (match the two or more against each other) and "multi viewing" (viewing several items at the same time)

**Comment by JonnyWong16** [comment]
Added in v1.4.7.
