### ISSUE TITLE
Notifications using GMAIL - still can't get it to work

### ISSUE THREAD

**Issue by diecast61** [Tautulli/Tautulli#619]
I keep getting the following error and don't know where to go from here.

Email notification failed: Connection unexpectedly closed.  I have set my gmail account to allow less secure access..

I am running python 2.7.11 and the most recent plexpy.

Here are my settings:
From Name: myaccount@gmail.com
From: myaccount@gmail.com
To: my2ndaccount@gmail.com
CC:
BCC:
SMTP Server: smtp.gmail.com
SMTP Port: 465 (have also tried 587)
SMTP User: myaccount@gmail.com
SMTP Password: myPW
TLS: unchecked

What am I doing wrong?  What did I miss in the set-up?

Thanks in advance afor any help

**Comment by JonnyWong16** [comment]
Have you tried SMTP port 587 with TLS checked?

**Comment by diecast61** [comment]
Yes - that did not work either.

Thanks for your prompt reply

**Comment by JonnyWong16** [comment]
Can you provide the rest of this info? https://github.com/drzoidberg33/plexpy#issues
- [ ] Version
- [ ] Branch
- [ ] Commit hash
- [ ] Operating system
- [X] Python version
- [ ] What you did?
- [ ] What happened?
- [ ] What you expected?
- [ ] How can we reproduce your issue?
- [X] What are your (relevant) settings?
- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

**Comment by diecast61** [comment]
Very weird – working now – after reboot
