### ISSUE TITLE
XBOX/Apple TV icons not displaying/missing

### ISSUE THREAD

**Issue by unixjeff** [Tautulli/Tautulli#621]
![plexwatch](https://cloud.githubusercontent.com/assets/751756/13907064/1aa49924-eebc-11e5-8220-91aacc3e882d.png)

it appears that there is no icon for xbox and apple tv at this time

**Comment by JonnyWong16** [comment]
The icons are there. Try refreshing the page. 

After looking at the screenshot, that's not even PlexPy.

**Comment by unixjeff** [comment]
Well im using Plex Request and opened a ticket with them they said come here

https://github.com/lokenx/plexrequests-meteor/issues/296

**Comment by JonnyWong16** [comment]
Sorry, that's not PlexPy. I don't know what you're using. Maybe plexWatchWeb?

**Comment by unixjeff** [comment]
you know what your right.. im sorry
