### ISSUE TITLE
[Bug] Synced Items shows status for devices that are nolonger attached / approved.

### ISSUE THREAD

**Issue by bagobones** [Tautulli/Tautulli#622]
While the data might be historically accurate it doesn't reflect which devices are currently approved for sync if devices have been removed.

I have a number of old devices listed at show 50% or 100% in PlexPy although they no-longer exist  on the plex https://app.plex.tv/web/app#!/status/sync status page.

**Comment by JonnyWong16** [comment]
The sync table isn't saved or cached in PlexPy. It's retrieved from Plex each time it is loaded. So if that's what's being reported by Plex, then it's a Plex bug not PlexPy. Sorry.

**Comment by bagobones** [comment]
It appears to be a history table however. In plex if you go to https://app.plex.tv/web/app#!/status/sync  you will see fewer devices listed.

In PlexPy it is being represented as a status page, this it should only display the devices from https://app.plex.tv/web/app#!/status/sync  or at a minimum have a filter.

**Comment by JonnyWong16** [comment]
You can check what the Plex API is reporting at 

```
https://plex.tv/servers/<machine_id>/sync_lists
```

Your `<machine_id>` is the `pms_identifier` in your `config.ini` file.

**Comment by bagobones** [comment]
I am on linux so that was actually in the preferences.xml.

However it is likely this information is kept if a client isn't purged by the user, which could create a lot of client buildup on a shared server..

May I suggest adding a filter and column based on the  lastSeenAt  that is in the XML? This would make that screen far more relevant if a client hasn't been seen in a long time.

**Comment by JonnyWong16** [comment]
All new feature requests have moved to [FeatHub](http://feathub.com/drzoidberg33/plexpy). Submit it there.
