### ISSUE TITLE
Notifications enable

### ISSUE THREAD

**Issue by unixjeff** [Tautulli/Tautulli#623]
is there a way to enable only certain ones, I really only want the buffering one

**Comment by JonnyWong16** [comment]
Please read the [Issues guidelines](https://github.com/drzoidberg33/plexpy#issues) next time. 

The answer to your question can be found in the [FAQ](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#q-i-cant-get-notifications-working-is-there-a-magic-trick).
