### ISSUE TITLE
Whatsapp possible?

### ISSUE THREAD

**Issue by joewalch** [Tautulli/Tautulli#624]
I didn't want request this as a feature request just yet as I'm sure its been considered at some point. Can whatsapp be used for notifications just like telegram?

**Comment by JonnyWong16** [comment]
Unfortunately Whatsapp is too locked down and doesn't provide an API for developers to interact with it.

**Comment by joewalch** [comment]
Thought it might be something along those lines.

**Comment by neyestrabelli** [comment]
Hi @joewalch,

you can use a php script with WhatsAPI (https://github.com/mgp25/Chat-API), and set notification script on plexpy.

**Comment by nesrine19992** [comment]
hi n can i add a script in mu plexPY
