### ISSUE TITLE
Syntax Error on first run

### ISSUE THREAD

**Issue by nachoha** [Tautulli/Tautulli#635]
So I installed with the preferred Method 2, and when I run PlexPy.py a window briefly appears and disappears, when I run it from a admin command prompt I get the following error:
D:\plex\Plex.py.git>plexpy.py
Traceback (most recent call last):
  File "D:\plex\Plex.py.git\PlexPy.py", line 25, in <module>
    from plexpy import webstart, logger, web_socket
  File "D:\plex\Plex.py.git\plexpy__init__.py", line 214
    except OSError, e:
                            ^
SyntaxError: invalid syntax

Running Windows 10. Any ideas?

**Comment by JonnyWong16** [comment]
You need Python 2.7. PlexPy does not run on Python 3.

Also very first question in the [FAQ](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#general-q1).

**Comment by nachoha** [comment]
So it is, so it is :)
