### ISSUE TITLE
[FEATURE REQUEST] Option to TURN OFF Recently Added on Homepage

### ISSUE THREAD

**Issue by LilFaceDancer** [Tautulli/Tautulli#637]
Would love to have an options flag to TURN OFF the Recently Added files from the Homepage.  Current Activity and stats is all I need on the homepage.  I already have this information on every Plex apps homepage including the server itself.  For monitoring the user server activity I do not need this information.  A flag in the Homepage options ti turn this information off would be helpful.

**Comment by JonnyWong16** [comment]
Please read the guidelines for [feature requests](https://github.com/drzoidberg33/plexpy/blob/master/README.md#feature-requests).
