### ISSUE TITLE
PlexPy doesn't recognize version. Keeps saying update

### ISSUE THREAD

**Issue by djxmind** [Tautulli/Tautulli#638]
I'm new to this whole Github and everything so please, go easy on me.

PlexPy keeps showing notification saying "You are running an unknown version. Please update." It also won't grab the latest update automatically. How do I fix this issue?

**Comment by JonnyWong16** [comment]
Please read the [guidelines](https://github.com/drzoidberg33/plexpy/blob/master/README.md#issues) before posting new issues. 

Edit: Also read this FAQ: https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#windows-q2
