### ISSUE TITLE
Import to plexpy from plex logs?

### ISSUE THREAD

**Issue by peva3** [Tautulli/Tautulli#639]
I recently accidentally destroyed my plexpy directory, and would love to have the ability for plexpy to scan plex logs and rebuild the database from them.

Any way to do this already? Or interest in this idea?

**Comment by JonnyWong16** [comment]
In the [FAQ](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#history-q5).

**Comment by Arcanemagus** [comment]
And just to save you some future searching, the built in history in Plex (not the logs) isn't enough either: https://github.com/drzoidberg33/plexpy/issues/53
