### ISSUE TITLE
Some suggestions for the box in the corner talking about updates

### ISSUE THREAD

**Issue by jroyal** [Tautulli/Tautulli#64]
I think this box could have two things that make it a bit better. 
1. Make it more solid so that its in the foreground. Right now if you go to the graphs page it kinda gets lost.
2. If you click close it should stay closed during the current session instead of popping back up on every page. 

Let me know if you have any thoughts on this, or if you have started looking into it already. I can look into it if not.

**Comment by jroyal** [comment]
A quick screenshot of the behavior I am talking about.

![image](https://cloud.githubusercontent.com/assets/2245471/9267026/705d2350-420e-11e5-9843-fed2ad29fcb4.png)

**Comment by drzoidberg33** [comment]
To disable this box completely you can uncheck the box in Settings -> General -> Enable Updates.

**Comment by jroyal** [comment]
Ah ok, that will be helpful. I'm going to look at keeping it temporarily closed when you click the closed button. Sometimes I would like to be reminded to update, just not right then.

**Comment by drzoidberg33** [comment]
Thanks. I agree with both your points. And while I was thinking about it I just decided to fix it.

Pushed to dev in: https://github.com/drzoidberg33/plexpy/commit/c4416572cf4e131d1d9a4847f5e153d85d1c2b69

**Comment by jroyal** [comment]
Ok, thanks.
