### ISSUE TITLE
Unable to connect PlexPy to Plex Server Logs

### ISSUE THREAD

**Issue by LilFaceDancer** [Tautulli/Tautulli#644]
I entered the path to my Plex logs as

X:\MediaLibrary\Plex Media Server\Logs\     (this is the directory where Plex Media Server.log is located)

This location can be accessed with windows explorer and through command prompt.

I save the configuration then goto the Logs tab in PlexPy then navigate to Plex Media Server Logs tab.

I get this - No log information available. Have you set your logs folder in the settings?

So I goto the PlexPy logs and see this

Unable to open Plex Log file. [Errno 2] No such file or directory: 'X:\MediaLibrary\Plex Media Server\Logs\/Plex Media Server.log

It doubles the '\" as well as adds a '/' in front of Plex Media Server.log

I think it is the '/' in front of the log file name that is messing it up but have not been able to figure out how to remove it.

Any ideas?

Version 1.3.14
PlexPy Configuration
Git Branch: master
Git Commit Hash:    786a3742332bd9d1266b1c3d01e1432aea4f4143
Configuration File: /apps/plexpy/app-config/config.ini
Database File:  /apps/plexpy/app-config/plexpy.db
Log File:   /apps/plexpy/app-config/logs/plexpy.log
Backup Directory:   /apps/plexpy/app-config/backups
Cache Directory:    /apps/plexpy/app-config/cache
Arguments:  ['--daemon', '--nolaunch', '--pidfile=/var/run/plexpy.pid', '--datadir', '/apps/plexpy/app-config', '--config', '/apps/plexpy/app-config/config.ini', '--port', '3033']
Platform:   Linux 4.1.16.x86_64.1
Python Version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]

Plex Server, Python and PlexPy running on ReadyNAS 516

**Comment by Arcanemagus** [comment]
Have you tried removing the `\` on the end of the setting?

**Comment by LilFaceDancer** [comment]
Yes

Error becomes - 

Unable to open Plex Log file. [Errno 2] No such file or directory: 'X:\MediaLibrary\Plex Media Server\Logs/Plex Media Server.log

**Comment by Arcanemagus** [comment]
Wait a sec, the path you list is a Windows UNC path, but PlexPy appears to be running on a Linux box... are these different systems?

**Comment by LilFaceDancer** [comment]
The Plex Media Server, Python, and PlexPy are all running on a Netgear ReadyNAS 515.  All 3 apps were installed on the NAS from the versions located at the Netgear apps page at 

http://apps.readynas.com/pages/?page_id=9

I have mapped/mounted the plexmediaserver folder on the NAS to X: on my laptop so that I am able to access it.  The laptop is running windows 10 and I use the Chrome browser the on the same laptop to access/config PlexPy

**Comment by Arcanemagus** [comment]
Ah, that path needs to be how the _PlexPy_ instance can get to the Plex server logs, not how you would from your laptop. I'm not sure how easy mounting folders between "apps" are on ReadyNAS, but that's what you would need to do to get this working properly.

**Comment by LilFaceDancer** [comment]
Figured it out

/apps/plexmediaserver/MediaLibrary/Plex Media Server/Logs/

Appreciate the help in pointing me in the right direction to figure it out.  Many Thanks
