### ISSUE TITLE
First few lines of scanner log "Unable to parse log line."

### ISSUE THREAD

**Issue by whiskerz007** [Tautulli/Tautulli#645]
The beginning 6 or so lines of the Media Scanner Log is not able to parsed. Running Archlinux 4.4.5-1-ARCH x86_64, Plex 0.9.16.3, Python 2.7.11, PlexPy v1.3.14.

[Plex Media Scanner.log.txt](https://github.com/drzoidberg33/plexpy/files/196147/Plex.Media.Scanner.log.txt)

**Comment by JonnyWong16** [comment]
Not sure what you're trying to ask here...

**Comment by whiskerz007** [comment]
Here are the screenshots of what I'm getting. I'm not sure what is happening in the Python script that is cause these errors.

![plexpy log](https://cloud.githubusercontent.com/assets/2713522/14155338/f437248c-f686-11e5-9382-c4f4b50b0a8b.png)
![plexpy media scanner log](https://cloud.githubusercontent.com/assets/2713522/14155339/f4380f3c-f686-11e5-83d3-7ad50f0cf70a.png)

**Comment by JonnyWong16** [comment]
I don't know why. But it's not really a problem though. Might be a one time thing.

**Comment by whiskerz007** [comment]
I looked at the logs again and from what I can tell, I'm missing the first 24 lines of the log (at least).

**Comment by Nerwysh** [comment]
Hi  whiskerz007, do you still have the problem?
For some days, I also have the same errors.

I can see the current watching of the users but my history doesn't work.
- Sorry for my english ;)

**Comment by drzoidberg33** [comment]
This is normal. The PlexPy log parser expects the line to contain 3 components - the date/time, the log level (e.g. DEBUG, INFO) and the message. If the line doesn't contain these then it doesn't get parsed it and throws that message.
