### ISSUE TITLE
Loosing Series Number with Grouped Notifications

### ISSUE THREAD

**Issue by jc74uk** [Tautulli/Tautulli#646]
Hi,

Would it be possible to preserve the Series number notifications for grouped newly added content notification messages?   I don't mind if I get two notification for two different series'.  

I'm hoping to be able to use something like this as the Newly Added script:  

`<tv>One or more episodes from {title} Series {season_num00}  has been added to the Plex Library. </tv>
<movie> The Movie {title} has been added to the Plex Library. </movie>`

Currently it reports 0 or 00 as the season number, I'm guessing because of the "Note: No Season/Episode or Album/Track metadata will be available." message under the grouped notification checkbox.

**Comment by JonnyWong16** [comment]
I suggest adding your request to here: http://feathub.com/drzoidberg33/plexpy/+44

**Comment by jc74uk** [comment]
Thanks, will do!  :+1:
