### ISSUE TITLE
[Feature Request] Identify "user" via IP/Device, or provide filtering/graph options per IP/Device

### ISSUE THREAD

**Issue by storerc** [Tautulli/Tautulli#647]
For better or worse, everyone whom I've shared my plex library with uses my single main credential.  I can obviously see source IP's and device details in the history, but it would be fantastic if the concept of a "user", for all intents and purposes (graphs, reporting, top X lists, etc), could be extended to an IP and/or device.  Bonus Brownies for the ability to assign a custom name (or reference, or note, etc) to an IP or Device for additional identification.

Thx!!!!!!

(note, just submitted via feathub.com as well - the "bugs and feature requests" link built-in to the application brings you directly to github - possibly appropriate for seperate bug and feature request links to reflect the separate apps for each?)

**Comment by JonnyWong16** [comment]
The feature request link on the Help & Info page should go to FeatHub. 

I don't think you should be sharing your Plex account. Each person should have their own account.

**Comment by storerc** [comment]
You are correct, the help/info link in-app points to FeatHub - I ended up
with the github link from the plex forums post  @
https://forums.plex.tv/discussion/169591/plexpy-another-plex-monitoring-program

Thanks for the super fast follow up!

Regardless of whether or not I should share my account, could there be
other relevant use cases for sorting/filtering/graphing/viewing via IP or
device?  This information appears to be already tracked, just not
"groupable" ?

Thx!!!

**Comment by JonnyWong16** [comment]
Submitted on FeatHub: http://feathub.com/drzoidberg33/plexpy/+70
