### ISSUE TITLE
Global Notification Toggles do nothing

### ISSUE THREAD

**Issue by mattyteds** [Tautulli/Tautulli#649]
Under **Notification** settings, if I uncheck _Enable TV Show Notifications_ under the **Global Notification Toggles** and then under the **Facebook Notification agent** enable _Notify on recently added_ I still get Facebook notifications about newly added shows. Am I misunderstanding the purpose of these global triggers?

**Comment by JonnyWong16** [comment]
**Global Notification Toggles**

For stream/playback activity:
- [ ] Enable Movie Notifications
- [ ] Enable TV Show Notifications
- [ ] Enable Music Notifications

For recently added:
- [ ] Enable Recently Added Notifications

FAQ: [Q: Can I disable recently added notifications for TV Shows/Movies?](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#notifications-q3)
