### ISSUE TITLE
PlexPy auto updated not notifcations aren't working at all.

### ISSUE THREAD

**Issue by vulcanjedi** [Tautulli/Tautulli#65]
updated when i refreshed page this am, to 001acfc24d2a41b0b4e56dafe660fe9cc76e0269
now I haven't got any notifications today?

**Comment by drzoidberg33** [comment]
I'm not aware of any issues with that release and notifications. You'll have to be more specific.

Which notifications? Which agents? Logs?

Please see this for guidelines before posting issues: https://github.com/drzoidberg33/plexpy#installation-and-notes

**Comment by drzoidberg33** [comment]
Closing issue. No information provided.

**Comment by vulcanjedi** [comment]
thanks turns out this was pushbullet related and they sent out broadcast regarding their issue(s).
keep up the good work/progress on PlexPy.
