### ISSUE TITLE
Notify conditions

### ISSUE THREAD

**Issue by mattyteds** [Tautulli/Tautulli#650]
I have Sonarr setup to add propers and CouchPotato to add better qualities, when this happens I get notifications sent to my Facebook group for every copy. It would be great if there was a way to set PlexPy to only notify once per item.

It would also be handy to only send a single notification when a series is added for the first time, not each time an episode is added for that series. Much like how _Group notifications for recently added TV Shows or Music_ works.

I've been trying to write a pyton script for these but it's a bit above my skill level, I'll continue to work on it but I figured these might make great enhancments.

**Comment by JonnyWong16** [comment]
Please read the guidelines: https://github.com/drzoidberg33/plexpy#feature-requests

(Also, a more descriptive title would help.)

**Comment by mattyteds** [comment]
I did search prior to posting and was unable to locate something similar, would you mind pointing me towards the similar request to I can thumbs it up, rather just closing my suggestion?

**Comment by JonnyWong16** [comment]
> Feature requests are handled on [FeatHub](http://feathub.com/drzoidberg33/plexpy).

Please submit it there (after searching).
