### ISSUE TITLE
[Bug]? Facebook new content notification doesn't always send

### ISSUE THREAD

**Issue by JeramieG-IDG** [Tautulli/Tautulli#653]
I've had this happen about once every other day or so.  A new item will be added to my plex server, tv show, movie, whatever.. and plexpy doesn't post the facebook notification.  in the python.exe window for plexpy is the following for this last time.

download started at 11:38 directly into the plex movie folder.  previous downloads to this same folder have announced fine to facebook.

2016-04-06 11:40:53 - WARNING :: Thread-20 : Failed to access uri endpoint /library/metadata/81192 with error timed out
2016-04-06 11:40:53 - WARNING :: Thread-20 : PlexPy Pmsconnect :: Unable to parse XML for get_metadata: 'NoneType' object has no attribute '
getElementsByTagName'.
2016-04-06 11:40:53 - ERROR :: Thread-20 : PlexPy Monitor :: Unable to retrieve metadata for rating_key 81192
2016-04-06 11:46:34 - DEBUG :: Thread-20 : PlexPy Monitor :: Session 104 has stopped.
2016-04-06 11:46:34 - DEBUG :: Thread-20 : PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 7
2016-04-06 11:46:34 - DEBUG :: Thread-20 : PlexPy Monitor :: Removing sessionKey 104 ratingKey 7 from session queue

Plex and plexpy(via the home page view) see the title fine and have the metadata.  81192 does appear to reference the upload, if i hover over it in plexpy it has this : http://192.168.69.5:8181/info?rating_key=81192 so i'm guessing that error above is related.

i apologize if this has been covered already, i couldn't find any fix.

Thanks so much for your time, LOVE plexpy!

**Comment by JonnyWong16** [comment]
The connection timed out (i.e. your PMS took longer than 20 seconds to respond to PlexPy). This sometimes happen when your PMS is busy (fetching metadata, generating thumbnails, scheduled maintenance, etc.). It could also depend on how you have PMS and PlexPy setup (same machine, same LAN, over the internet, etc.).

Unfortunately, the notification got missed and there's no way of going back to trigger the notification.

**Comment by JeramieG-IDG** [comment]
Thanks Jonny, i appreciate your time!

That is what i suspected, i run plex and plexpy on the same box.  An HP proliant DL360e Gen8, single cpu Xeon E5-2430 @ 2.2Ghz with 12 Gb of ram.  There isn't anything else running on the machine except utorrent and i'm running 6 10k rpm drives in raid 5 for the system/apps/db's/etc.. all the shows go to usb3 external drives.  maybe the usb bus was busy, although there were only 2 streams going and i've done 10 without a problem so far.  Come to think of it there wasn't much going on with regard to utorrent either.  Just one download and some very minor uploads.

But, i will say that sometimes it takes plex forever to grab the metadata.. a couple minutes or more for one title.  

Is there a way for me to set the delay that plexpy waits before it trys to announce an item? or some other relevant delay?

Thanks again, much appreciated

**Comment by JonnyWong16** [comment]
Settings > Notifications > Recently Added Notifications > Notification Delay.

This won't solve the timing out problem though.

If PMS and PlexPy are on the same machine, make sure you're using `localhost` or `127.0.0.1` as the _Plex IP or Hostname_ in the settings to reduce overhead.

**Comment by JeramieG-IDG** [comment]
Thanks, i confirmed its set to 127.0.0.1

**Comment by JeramieG-IDG** [comment]
wow i hadn't even noticed that section (notification delay), sorry about that.  I changed it from 60 to 300s just for giggles, i don't need super fast notifications and it gives the download time to finish too.  hopefully plex lagging on getting metadata was part of the problem.  if you think of anything else i can try i'd appreciate it.

have a good one

**Comment by Aldione** [comment]
so if i incremeSe the delay is gonna fix it?

**Comment by JeramieG-IDG** [comment]
yea i haven't had the problem since increasing the delay, mine is at 5 minutes which works good for me anyway as it ensures that the file is completely finished being received.
