### ISSUE TITLE
Disable web interface ssl without web interface

### ISSUE THREAD

**Issue by fenichelar** [Tautulli/Tautulli#654]
I can't access the PlexPy web interface. Where are the web interface settings stored? Thanks.

**Comment by Hellowlol** [comment]
In the config file :P

**Comment by JonnyWong16** [comment]
Please read the FAQ: [Q: I can't reach the web interface!](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#general-q4)

**Comment by fenichelar** [comment]
I am an idiot. I was searching for 'ssl' not 'https' in the config. For PMS it is called 'PMS_ssl' so I was looking for 'web_ssl' or something. Thanks!
