### ISSUE TITLE
[Feature Request] List Current Play Status in API

### ISSUE THREAD

**Issue by a5m0** [Tautulli/Tautulli#656]
Can the api return currently being played info? This way I can make a plex updater that checks if anything is playing media before the server is updated/rebooted (which can be kicked off by a new update notification script from plexpy itself).

**Comment by JonnyWong16** [comment]
```
/api/v2?apikey=<your_api_key>&cmd=get_activity
```

**Comment by a5m0** [comment]
Perfect! Sorry I had only found documentation for api v1 not v2.

**Comment by Hellowlol** [comment]
You can always use docs_md to get the apidocs
