### ISSUE TITLE
Websocket monitoring stopped working with PMS 0.9.16.4

### ISSUE THREAD

**Issue by arm3n** [Tautulli/Tautulli#659]
I just disabled Websocket and having PlexPy manually poll, and I am getting proper notifications again.

**Comment by JonnyWong16** [comment]
Nope, definitely still working.

![image](https://cloud.githubusercontent.com/assets/9099342/14374931/a1e92834-fd10-11e5-96fb-e38396f1072d.png)

![image](https://cloud.githubusercontent.com/assets/9099342/14374936/b238bde4-fd10-11e5-9724-534eb8573af0.png)

Have you tried restarting?

**Comment by arm3n** [comment]
Apologies - seems all I needed to do was cycle the PlexPy server.
