### ISSUE TITLE
No option to enter SSL certificate chain

### ISSUE THREAD

**Issue by simonarons** [Tautulli/Tautulli#660]
I’ve got an SSL certificate issued by StartCom, but to make it work without a warning on Android I need to provide the intermediate certificate as well. My workaround this far has been to edit line 109 in [lib/cherrypy/_cpserver.py](https://github.com/drzoidberg33/plexpy/blob/master/lib/cherrypy/_cpserver.py#L109) and add the certificate chain manually, but by doing that I can’t update PlexPy correctly.

Is it possible to extend the SSL settings to include a certificate chain?

**Comment by Hellowlol** [comment]
https://github.com/midgetspy/Sick-Beard/pull/907/

**Comment by JamminR** [comment]
@simonarons - Mind sharing what you changed line 109 to? I have two pem files (maybe 3, still tinkering). domain + intermediate for sure.

**Comment by simonarons** [comment]
@JamminR I just pointed it to the intermediate cert if I remember correctly.

**Comment by b2un0** [comment]
create a bundle file:

`cat example.com.crt ca.pem sub.class1.server.ca.pem > example.com.pem`

than use the `example.com.pem` as cert file in PlexPy.

this works for me.

**Comment by simonarons** [comment]
Does it work with Chrome for Android without a warning? Because that's my issue, that a bundled cert - for some reason - doesn't work without a warning in Chrome for Android (no desktop issues, though).

**Comment by b2un0** [comment]
this crt bundles works on all my devices, like iPhone with Chrome/Safari or Android 6 with Chrome - i also use StartCom free ssl certs.

**Comment by simonarons** [comment]
That is so strange. It all works when using a "regular" web server such as apache. But unless I'm manually adding the ssl certificate chain in the CherryPy config file, I get a warning on Chrome on Android (Your connection is not private etc.). 

What version of Android are you using? And you don't get any warning at all on Android?

**Comment by b2un0** [comment]
did you really bundle all three certificate files in on file like my "cat" statement above?

my .pem file has three "-----BEGIN CERTIFICATE-----" lines, so all three certs are in one file.
and my config looks like this:

![image](https://cloud.githubusercontent.com/assets/2155498/16229610/d8a1c59c-37bd-11e6-885c-d8d99b17a413.png)

**Comment by simonarons** [comment]
Yes. As I said, it’s only in PlexPy and the implementation of CherryPy that
seems to be the problem. It’s not the certificate that’s wrong per se, but
how PlexPy/CherryPy handles it. It’s a quite easy fix as well. Here:
https://code.google.com/archive/p/sickbeard/issues/2546

But it's very strange that you don't get "your connection is not private"
warning at all in Chrome for Android. Unless I add the cert chain to the
CherryPy config, I'm stuck with the red status bar.

**Comment by JamminR** [comment]
I too get issues. My cert file is one chain as described in suggestion. Did
that first week of troubleshooting. Only time i dont get prompted is my
win10 machine running firefox.

**Comment by smevawala** [comment]
changing plexpy/webstart.py line 60 from:

```
    if enable_https:
        options_dict['server.ssl_certificate'] = https_cert
        options_dict['server.ssl_private_key'] = https_key
        protocol = "https"

```

to:

```
    if enable_https:
        options_dict['server.ssl_certificate'] = https_cert
        options_dict['server.ssl_certificate_chain'] = https_cert
        options_dict['server.ssl_private_key'] = https_key
        protocol = "https"
```

fixes the issue for me.  My cert is a full chain cert (letsencrypt), so it has the intermediaries and my server cert.

**Comment by orionshock** [comment]
Is there any update on this to have it fixed in the core with out having to hack into the code every time there is an update?

**Comment by Hellowlol** [comment]
@orionshock Send a pr your self? Must be easier then patching plexpy on every update.

**Comment by Napsterbater** [comment]
I ran into this issue as well,  Let's encrypt certs require the chain for alot of devices.

Can there be an option to include the chain Cert. 

What i'm using as a work around is running PlexPy with just HTTP and using Stunnel to accept the TLS connection and forward a plain HTTP connection to PlexPy.

**Comment by csy7550** [comment]
I've also run in to this problem with my Cert from comodo (positivessl) and adding the line to webstart.py as suggested here made PlexPy unable to start.. complained about a missing module (?)

**Comment by dmwilson1990** [comment]
@smevawala fix solved the issue for me while using Let's Encrypt certificates. Please merge.

**Comment by Hellowlol** [comment]
@dmwilson1990 maybe you should start with making a PR?

**Comment by JonnyWong16** [comment]
Wait for v2 270d4f510af19003618c011aabe21f49b09a9a6f

**Comment by Arsur** [comment]
can someone explain me what i have to do?

i created an letsencrypt certificate and changed the webstart.py

than i browsed to Web Interface-->HTTPS Cert and changed the path to /etc/letsencrypt/live/xxxxxxxx.xx/fullchain.pem

i havend done this before, so what else do i have to change?
whats with the HTTPS Key field.
