### ISSUE TITLE
Edit mode is not fully retained between pages

### ISSUE THREAD

**Issue by didyouexpectthat** [Tautulli/Tautulli#661]
If you enter Users and then start edit mode, you are in edit mode. Click page 2 of users and you appear to still be in edit mode (because delete, purge, and the notification show you) but friendly name rename is disabled across the pages. You need to work around by leaving edit mode and then re-entering edit mode. 
I expect between pages that I shouldn't have to exit and re-enter edit mode to rename users.

Page 3 after being in edit mode and making changes:
![image](https://cloud.githubusercontent.com/assets/1329077/14404620/2ffbc698-fe30-11e5-9313-72daf715ce58.png)

Page 4 while still in edit mode, see lack of friendly user rename, but it is still in edit mode.
![image](https://cloud.githubusercontent.com/assets/1329077/14404637/83847d1e-fe30-11e5-9669-5a1f6179df22.png)

Commit: 786a3742332bd9d1266b1c3d01e1432aea4f4143
Version: 1.3.14
Debian 8 systemd 
Python 2.7.9

**Comment by JonnyWong16** [comment]
Thanks for the bug report. I never noticed this because I have less than 10 users so I only have one page.

**Comment by JonnyWong16** [comment]
Fixed in v1.3.16.
