### ISSUE TITLE
PlexPy notifications no longer posting to Facebook

### ISSUE THREAD

**Issue by zprewitt** [Tautulli/Tautulli#663]
Just noticed that FB notifications stopped working 3 days ago. Went into notification agents and clicked the Test button, got this response in the terminal:

2016-04-10 11:48:46 - WARNING :: CP Server Thread-2 : PlexPy Notifiers :: Error sending Facebook post: Error validating access token: The session has been invalidated because the user has changed the password.

I've changed nothing in either my plexpy or FB settings. Any suggestions?

**Comment by JonnyWong16** [comment]
Try reauthorizing.

**Comment by zprewitt** [comment]
Clicked Request Authorization and it took me to a blank page with "This site can't be reached".

**Comment by JonnyWong16** [comment]
Full logs?

**Comment by zprewitt** [comment]
When I click that button, all I see in the terminal is "Writing configuration to file".

**Comment by JonnyWong16** [comment]
Post your full log file. Click your log file on the Help & Info page. 

Also, please read the [guidelines](https://github.com/drzoidberg33/plexpy#issues).

**Comment by zprewitt** [comment]
Ahh, figured it out. Forgot I had changed my port number.
