### ISSUE TITLE
history and user updates never updating?

### ISSUE THREAD

**Issue by gimp1124** [Tautulli/Tautulli#664]
I installed Py a few months ago and with Jonny Wongs help it seemed to be fixed, I was wrong. I know users have been watching my server and i see zero updates on the history of the user or in the graph tab. As a somewhat novice, what can i share with you so that you can tell me how to make this awesome program work? thanks

**Comment by JonnyWong16** [comment]
Please read the [guidelines](https://github.com/drzoidberg33/plexpy#issues)

**Comment by gimp1124** [comment]
Version 1.3.14 Changelog
PlexPy Configuration
Git Branch:     master
Git Commit Hash:    786a3742332bd9d1266b1c3d01e1432aea4f4143
Configuration File:     C:\plexpy\config.ini
Database File:  C:\plexpy\plexpy.db
Log File:   C:\plexpy\logs\plexpy.log
Backup Directory:   C:\plexpy\backups
Cache Directory:    C:\plexpy\cache
Platform:   Windows 7
Python Version:     2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]

what i did?- don't think it ever installed right
what happened- no user updates in users/history/graph tabs (users only shows MY watches)
what i expected- to see everyone who shares my servers plays etc
I dont know how you'd reproduce the error to see whats going on. 

***getting log file now

**Comment by gimp1124** [comment]
[jGxHBVqG.txt](https://github.com/drzoidberg33/plexpy/files/212219/jGxHBVqG.txt)

sorry couldnt figure out pastebin

**Comment by JonnyWong16** [comment]
FAQ
https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#history-q8

**Comment by JonnyWong16** [comment]
Also that's not your entire log file. Just click your log file on the Help & Info page.

**Comment by gimp1124** [comment]
Ok thanks. I'm not home right now as far as finding a full log file. But I did actually see something in FAQ as far as having plexpy running at all times. I didn't see anything about how to make sure it's open at all times. I generally click a shortcut on my desktop and it opens up. Sorry again for my non knowing ass. All this def is way over my head but the program seems awesome

**Comment by JonnyWong16** [comment]
Yes, [PlexPy needs to be running in order to record history](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#history-q4).

If you're just running by clicking the icon, then I assume you have the command window open while PlexPy is running. If you close that window, then PlexPy will shut down. To keep it running in the background without the command window, you can follow the instruction [here](https://github.com/drzoidberg33/plexpy/wiki/Install-as-a-daemon#windows) to create a shortcut.

**Comment by gimp1124** [comment]
seems to be working awesomely!! Thanks so much JW
