### ISSUE TITLE
Get bandwith use

### ISSUE THREAD

**Issue by Hellowlol** [Tautulli/Tautulli#665]
I was just wondering if anybody was interested getting bandwidth usage per user, I was thinking about reading from plex backup db.

**Comment by JonnyWong16** [comment]
You can get bandwidth from the Plex db?

**Comment by Hellowlol** [comment]
Yeah, I think so. I was poking around in the db here the other day and I found a table bytes and usernames.

**Comment by JonnyWong16** [comment]
I see the `statistics_bandwidth` table. Not sure what those numbers correspond to though.

**Comment by Hellowlol** [comment]
@drzoidberg33 Can you enlight us about the statistics_bandwidth table? :S

**Comment by PoppinTaco** [comment]
I would love to have this!

**Comment by halfluck** [comment]
+1 This would be incredible!

**Comment by dot-mike** [comment]
Well, not a people are running PlexPy + Plex on the same server. Some are even running a docker container og similar.

**Comment by Hellowlol** [comment]
@Coldice1 that's there loss :p

**Comment by Arcanemagus** [comment]
@Hellowlol no, it's your loss for not isolating exposed services as much as possible. That's just plain bad habits _not_ to :confused:.

**Comment by Hellowlol** [comment]
That's just a silly statement so ill stop right there.

**Comment by Magikarplvl4** [comment]
+1

**Comment by traxinv** [comment]
+1

**Comment by stickystyle** [comment]
I did some playing around this morning and came up with this information...

`statistics_bandwidth.bytes`, while the column name is called 'bytes' it is actually being recorded in bits, probably one of those "oh damn, well too late to change it now, I'll just add a comment to the code and move along" type of things all programmers know ;-)

`statistics_bandwidth.timespan` values work like this...

| Value | Meaning |
| --- | --- |
| 0 | Totals by Epoch of collection, 2016-01-01 in my database |
| 1 | Totals by month |
| 2 | Totals by week |
| 3 | Totals by day |
| 4 | Totals by hour |

`statistics_bandwidth.lan` boolean field, 0 = WAN; 1 = on local network

With that information you can whip up a query to get the daily total bytes used per user

``` sql
SELECT accounts.name,
       statistics_bandwidth.at,
       statistics_bandwidth.lan,
       sum(statistics_bandwidth.bytes * 0.125) as bytes
FROM statistics_bandwidth
JOIN accounts ON statistics_bandwidth.account_id = accounts.id 
WHERE statistics_bandwidth.timespan = 3
GROUP BY accounts.name, statistics_bandwidth.at, statistics_bandwidth.lan
ORDER BY statistics_bandwidth.at;
```

and see data like this...

```
name           at                   lan         bytes
-------------  -------------------  ----------  ----------
Administrator  2016-07-14 00:00:00  0           189739.75
Administrator  2016-07-14 00:00:00  1           178232.75
Catherine      2016-07-14 00:00:00  1           475292304.
Christa        2016-07-14 00:00:00  1           122152722.
Tucker         2016-07-14 00:00:00  0           10814.125
Tucker         2016-07-14 00:00:00  1           108661497.
Administrator  2016-07-15 00:00:00  0           51413.0
Administrator  2016-07-15 00:00:00  1           23948.75
Christa        2016-07-15 00:00:00  0           10359.625
Tucker         2016-07-15 00:00:00  0           226304091.
Administrator  2016-07-16 00:00:00  0           291.5
Administrator  2016-07-16 00:00:00  1           825392292.
Christa        2016-07-16 00:00:00  0           2739.25
Tucker         2016-07-16 00:00:00  0           32473.375
Administrator  2016-07-17 00:00:00  1           201005550.
Administrator  2016-07-18 00:00:00  1           72316.875
Administrator  2016-07-19 00:00:00  0           44885.875
Administrator  2016-07-19 00:00:00  1           76745095.7
Administrator  2016-07-20 00:00:00  1           115012253.
Administrator  2016-07-21 00:00:00  0           17032001.3
Administrator  2016-07-21 00:00:00  1           10385965.5
Christa        2016-07-21 00:00:00  0           2225.625
```

"Administrator" is my main account that is signed in with plexpass, the others are plex home users. I didn't see anything in the DB that had a reference for "Administrator" to my plex account name, but there must be something somewhere.

**Comment by JonnyWong16** [comment]
That's awesome. Thanks for figuring that out.

**Comment by bigobx** [comment]
+1 on this as well

I would to see this integrated into the main status screen

**Comment by echyzowski** [comment]
That would be an amazing addition - One of things I was looking for. It would be nice to see the amount of KB/s going through my outbound IP so I can see what the upload requirement is for more than 1 user remotely. Sometimes I have 3 or 4 family members watching off Plex outside the home and they continually get buffering - which I'm assuming is due to the upload speed, not the PC transcoding speed.

**Comment by bigobx** [comment]
echyzowski, from some research on the plex forums and looking at my usage stats, a 720P stream takes about 1MB of BW give or take.  I have a little over 6MB of upload BW so i limit my system to about 5 concurrent users and everything seems to work well.  

This feature request would give me a bit more granular details based on user which i can tie back to ISP and stream type and get a better idea of who is using what and how i can tailor my usage.

**Comment by evanrich** [comment]
@bigobx  you mean 6Mbit...or 6MB?  that's 48Mbps up which would be pretty fast.

**Comment by bigobx** [comment]
@evanrich , that is correct, my connection is rated at 200/40Mbps and I can normally get closer to 220/45 or so.
