### ISSUE TITLE
Missing Notifications for Newly Added Movies

### ISSUE THREAD

**Issue by clarenceb5** [Tautulli/Tautulli#678]
Hi I performed a search prior to opening this ticket and found only 1 other issue related to "movie notification" but it did not relate to my problem.

I'm a new user of PlexPy and I like it very much.  Last night CouchPotato fetched 10 movies that all downloaded and added to my Plex Library successfully but only 1 notification was sent to the 3 destinations I have created and it was only sent after I clicked on "Restart" in the PlexPy settings.

Attached is my PlexPy log file.

Thanks,
Clayton
[plexpy.txt](https://github.com/drzoidberg33/plexpy/files/229981/plexpy.txt)

**Comment by JonnyWong16** [comment]
Can you tell me the exact time that one notification was sent?

**Comment by clarenceb5** [comment]
The exact time of the notification I did receive was for the movie Deja Vu
at 8:49 AM and it only came through after I restarted PlexPy.
Thanks.

**Comment by JonnyWong16** [comment]
Unfortunately, I can't tell from the logs since the logs end right at 8:49.

It could be that there were too many items too quickly, and PlexPy just missed them.

**Comment by clarenceb5** [comment]
Hi, I've been reviewing my PlexPy log file, I don't understand a lot of
what I'm reading but I do notice that during the morning hours
of 2016-04-21 there are a lot of 'WARNING' entries the first one appearing
at 2016-04-21 04:01:25 contains the following WARNING :: Thread-14 : Failed
to access uri endpoint /library/metadata/635747 with error ('The read
operation timed out',)

I had 10 movies download between 02:00:00 and 08:30:00 on 2016-04-21 and
there are 9 'WARNING' entries with the error (`The read operation timed
out',)  The last one was successful after PlexPy restart at 08:49:00.

Does this error have anything to do with the Notification setting
"Notification Delay"?

I have a feeling that maybe the "Notification Delay" setting may be too low
for me.

My SABNZBD is hosted on a different computer than Plex and my storage.  I'm
wondering if I increase the "Notification Delay" to allow for transfer time
of the movie file from one computer to another would resolve this problem,
is there a MAXIMUM number of seconds I can enter here?

I've noticed in the past that when CouchPotato moves the file from the one
computer to another, Plex sees the file but sets it to unavailable until it
is completely copied over and if you attempt to play the movie it will not
play.

Can PlexPy hold off on sending this notification until after the movie
becomes available in Plex? Or should we just increase the number of seconds
in the "Notification Delay"?

Thanks,
Clayton

**Comment by JonnyWong16** [comment]
There could be two reasons (that I can think of at the moment)
1. Since you mentioned its early in the morning, your server's scheduled maintenance could be running during this time and causes PlexPy to timeout when requesting info from your server.
2. Increasing the delay won't help with the first reason, but it might help to make PlexPy wait until the movie is no longer "unavailable" in Plex. PlexPy can't tell if it's available or unavailable. All you can do is tell it to wait longer.

**Comment by clarenceb5** [comment]
I will test it tonight, I will increase the wait time to 300 seconds and
see what happens.  May need to go higher than 300 depending on the file
size and transfer speed of my network.

I did not think of the server's scheduled maintenance causing this problem,
that is very much a possibility just strange that it does not cause a
problem for any of the TV shows.

Thanks for your assistance.  I will let you know tomorrow if the wait time
increase helps the problem.

**Comment by JonnyWong16** [comment]
No problem, try increasing the delay and report back.

I mentioned the scheduled maintenance because my sever times out between 2am-8am every night.

**Comment by clarenceb5** [comment]
Hi, so I set the delay to 300 seconds yesterday. I had 12 TV Show episodes
download and received all the notifications.  I had 4 movies download and
did not receive any notifications for the movies.  I'm increasing the delay
to 600 seconds and will try again tonight and report back tomorrow.

**Comment by clarenceb5** [comment]
Hi, so I added 3 more movies to my queue to download with the delay set to
600 seconds.  The first movie file to finish downloading did not have the
notification sent but the other 2 did.  So I believe you are correct when
you said it may be a problem with my server's maintenance schedule running
while these movies are being added to Plex causing PlexPy to timeout when
requesting info from the server.

I will try again one night this week with my maintenance schedule turned
off.

**Comment by clarenceb5** [comment]
Alright so it turns out that the server's maintenance is most likely the
cause of the missing notifications.  I schedule server maintenance to run
during a different time period and all movie notifications were sent
successfully.

**Comment by JonnyWong16** [comment]
Yeah, that's what I thought. Thanks for the update.

**Comment by JonnyWong16** [comment]
Assuming resolved.
