### ISSUE TITLE
Not detecting PMS Update

### ISSUE THREAD

**Issue by a5m0** [Tautulli/Tautulli#679]
There is currently a new plexpass PMS update out but plexpy is not detecting it.

2016-04-21 11:48:20 INFO    PlexPy Monitor :: No PMS update available.
2016-04-21 11:48:20 INFO    PlexPy Monitor :: Current PMS version: 0.9.16.4.1911-ee6e505

**Comment by JonnyWong16** [comment]
I know there's a bug that checking for updates doesn't work if your PMS shows the message below:
![plex_update_available](https://cloud.githubusercontent.com/assets/9099342/14714573/5c11dfd8-079a-11e6-8dfc-24c49a364712.png)

**Comment by a5m0** [comment]
That's unfortunate, I have an update script that will perform the manual upgrade, but I can't have plexpy automatically call it on new update available because it doesn't detect it.

**Comment by pax0707** [comment]
Version 0.9.16.5  Install Update  What's New

Sam bug?

**Comment by a5m0** [comment]
Yeah, seems like auto-update never works on ubuntu. Which I'm fine with, I just wish plexpy could detect the new update is available.

**Comment by JonnyWong16** [comment]
Check for updates should be working on v1.4.7.
