### ISSUE TITLE
Switch Dev/Master channel

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#68]
Can you add the possibility in the gui to switch to the dev or master channel ??

**Comment by kylerw** [comment]
+1

**Comment by alexandrupaulpopa** [comment]
+1

**Comment by mbnn** [comment]
+1

**Comment by zobe123** [comment]
you can do this via comand line.
- on ubuntu: shutdown plexpy via WebIF, then enter installed Folder and type 'git pull origin dev' - after a while you will see something like 40 Files changed.

**Comment by alexandrupaulpopa** [comment]
how do you do this on windows?

**Comment by drzoidberg33** [comment]
@alexandrupaulpopa If you have git installed you do the exact same thing, just use the cmd prompt and cd to the PlexPy folder then run the 'git pull origin dev' command.

If you're not running git then you have to download the dev zip file and install it separately: https://github.com/drzoidberg33/plexpy/archive/dev.zip
