### ISSUE TITLE
"Uncaught exception" when trying to import from PlexWatch, using latest update of PlexPy

### ISSUE THREAD

**Issue by deoT90** [Tautulli/Tautulli#680]
I have just set it up and intend to move from PlexWatch to PlexPY. Installation went without a hitch, however I can't seem to import my plexwatch db (v0.3.3-DEV). Whenever I try it just says Uncaught exception.

**2016-04-21 17:25:50 - ERROR :: CP Server Thread-8 : PlexPy Importer :: Uncaught exception.
2016-04-21 17:26:46 - ERROR :: CP Server Thread-6 : PlexPy Importer :: Uncaught exception.**

[Full Log](http://pastebin.com/5bCYBsAn)

Please, can someone help me? I cant found a solution
(Thanks for this app, is aweseome!)

```
Git Branch: master
Git Commit Hash:    541d2904d3c4b6947dad8bd44b6cde15f8c683de
Configuration File: C:\plexPy\config.ini
Database File:  C:\plexPy\plexpy.db
Log File:   C:\plexPy\logs\plexpy.log
Backup Directory:   C:\plexPy\backups
Cache Directory:    C:\plexPy\cache
Platform:   Windows 10
Python Version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
```

**Comment by JonnyWong16** [comment]
Please read the [guidelines](https://github.com/drzoidberg33/plexpy#issues)

**Comment by deoT90** [comment]
Well... can you be more specefic please?

I found the same issue here https://github.com/drzoidberg33/plexpy/issues/46

but the solution (https://github.com/drzoidberg33/plexpy/wiki/Troubleshooting) is a blank page for me

**Comment by JonnyWong16** [comment]
More specifically, [this list](https://github.com/drzoidberg33/plexpy#if-nothing-has-worked).

**Comment by deoT90** [comment]
I can upload plexWatch.db file if you need it.

Thanks

**Comment by JonnyWong16** [comment]
> 4. Make sure you provide the following information:
>     - [ ] Version
>     - [ ] Branch
>     - [ ] Commit hash
>     - [ ] Operating system
>     - [ ] Python version
>     - [ ] What you did?
>     - [ ] What happened?
>     - [ ] What you expected?
>     - [ ] How can we reproduce your issue?
>     - [ ] What are your (relevant) settings?
>     - [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

**Comment by deoT90** [comment]
http://pastebin.com/5bCYBsAn

**Comment by JonnyWong16** [comment]
Try this: https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#windows-q4

Or there might be something wrong with your `plexWatch.db` file.

**Comment by deoT90** [comment]
Thank you very much

When i try ill tell you

Edit: It works! Thank you really!
