### ISSUE TITLE
Missing Library Size column / row

### ISSUE THREAD

**Issue by JamminR** [Tautulli/Tautulli#681]
It's been asked/mentioned twice in the Plex forums discussion for PlexPy that the libraries tab at one time had a size total.
https://forums.plex.tv/discussion/comment/1161939/#Comment_1161939
https://forums.plex.tv/discussion/comment/1171371/#Comment_1171371
Can we please get that back?
As I don't remember it, not sure if this might also be a feature request - but believe both a data size column for each library, and a calculated last row for all library statistics combined, would be great.

**Comment by JonnyWong16** [comment]
Library size was never a column (on the Libraries tab). It's in the footer of the media info tables (fixed in v1.3.15). Make it a feature request on FeatHub to include it on the Libraries tab..
