### ISSUE TITLE
PlexPy not reflecting library removals.

### ISSUE THREAD

**Issue by benjaminwolf** [Tautulli/Tautulli#682]
Deleted a library called "TV Shows (HEVC Test)" and PlexPy still shows it under the Library statistics on the home screen and under the All Libraries tab.

However this library was deleted from the database sometime ago. I've confirmed the Plexdb does not list it under the library_sections table. Is this a bug or are these going to be retained forever?

**Comment by JonnyWong16** [comment]
Libraries are not removed automatically because some users might want to keep the statistics after deleting the library from Plex. You can delete the library from PlexPy by going to Libraries > Edit Mode.

**Comment by benjaminwolf** [comment]
Thanks!
