### ISSUE TITLE
Pushover errors

### ISSUE THREAD

**Issue by KrunchMuffin** [Tautulli/Tautulli#683]
I am trying to integrate pushover and get the following errors

> PlexPy Notifiers :: Unable to retrieve Pushover notification sounds list: Bad Request
> 
> PlexPy Notifiers :: Pushover notification failed: Bad Request

**Comment by JonnyWong16** [comment]
Double check your API Token. 

Also, please read the [guidelines](https://github.com/drzoidberg33/plexpy#issues) before posting issues.

**Comment by Hellowlol** [comment]
I hope you have added that as a saved response @JonnyWong16  :P

**Comment by KrunchMuffin** [comment]
You should think about doing this https://pushover.net/faq#technical-publicapp so users don't have to create their own app.

**Comment by Hellowlol** [comment]
It wasnt needed before, but i think the api limit was hit every month.

**Comment by KrunchMuffin** [comment]
I think it's per user, not per public application. I use it with Sonarr and don't come near 7500

**Comment by Hellowlol** [comment]
It was a shared apikey, but i see that we can simplify the creation for the end users, that would be nice.

**Comment by JonnyWong16** [comment]
Assuming this is resolved.

**Comment by KrunchMuffin** [comment]
yes. thanks
