### ISSUE TITLE
Feature Request Playlists by User

### ISSUE THREAD

**Issue by clarenceb5** [Tautulli/Tautulli#684]
I would like to be able to have a Playlist screen that would show the Playlist by user as well as the contents of the playlists.

**Comment by JonnyWong16** [comment]
Please read the guidelines for [feature requests](https://github.com/drzoidberg33/plexpy#feature-requests).

Do you mean what playlists the user has created? I not sure if that's possible.

**Comment by clarenceb5** [comment]
Yes, I was just in Plex Web looking at a video playlist I created.  It has
2687 items because I create playlists of old sitcoms and play them on
shuffle.  The problem I was encountering is I was wondering if a certain
sitcom had been added so I started scrolling down the list in Plex Web but
that is a very slow method and Plex Web has no other way of viewing the
contents of a playlist so I thought I'd see if PlexPy could implement some
way of display the playlists a user has as well as the contents of the
playlist.

Thanks for reaching out.
