### ISSUE TITLE
user with '&' in username does not show up

### ISSUE THREAD

**Issue by kuarthepirat** [Tautulli/Tautulli#685]
I am using 1.3.15 on Arch Linux with Python 2.7.11, latest PMS. I have a Plex Home with a plex.tv User in it, that has the username in the form "X & Y". The plex.tv user requires the eMail-address to log in to plex.tv.

No action of this user is recorded. The current plays always show up in PlexPy with the correct user name but there is nothing in the history. My guess is, that this happens because the user itself does not have a name in my plex database.

Can I "fix" it by setting the username for the ID in my plex database or is there another way to fix it?

**Comment by JonnyWong16** [comment]
Please read the [guidelines](https://github.com/drzoidberg33/plexpy#issues) before posting.
