### ISSUE TITLE
[Feature Request] Buffer stats

### ISSUE THREAD

**Issue by BehrozKarimi** [Tautulli/Tautulli#686]
Home/Watch Statistics:
top x users buffering

Graphs/Stream Info:
Buffer time in total pr. user and overall
Buffer count by user and stream type
Buffer count by source resolution
Buffer count by platform and stream type
Buffer count by stream resolution
Daily Buffer type breakdown

Graphs/Buffer by Period
Daily Buffer count
Buffer count by day of week
Buffer count by hour of day
Buffer count by top 10 platforms
Buffer count by top 10 users

Graphs/Buffer by Month

History
Buffer Count per play/entry

Users
Sort by users buffering most/least

Users/xxx
Player Stats:
Buffer per device/player

**Comment by JonnyWong16** [comment]
Please read the [guidelines](https://github.com/drzoidberg33/plexpy#feature-requests) for feature requests.
