### ISSUE TITLE
[Feature Request] Integrate PlexReports into PlexPy

### ISSUE THREAD

**Issue by Pakorro** [Tautulli/Tautulli#688]
I would very interesting that this great job was integrated into PlexPy. Many users are waiting a reporting feature for translate your statistics module or graphics section in a weekly report for users ( adding all features ).
Part of this job is already completed whit PlexReports.-
You can see more information here 👍 
[https://github.com/bstascavage/plexReport](url)
Regards
Paco

**Comment by Hellowlol** [comment]
I wouldnt say its completed, that project is using ruby so we cant reuse a single line off code. Its a nice example tho. Btw, you should fix that link. Try clicking it.

**Comment by drzoidberg33** [comment]
Feature requests info: https://github.com/drzoidberg33/plexpy#feature-requests
