### ISSUE TITLE
Merging PlexPy libraries from two installs

### ISSUE THREAD

**Issue by frakkingtoaster** [Tautulli/Tautulli#690]
I am using PlexPy version 1.3.16 on the master branch

I created a new install of Plex on a new Ubuntu 16.04 VM. I had a running Plex instance on a 14.04 server. I installed PlexPy on the new server, and pointed it to the Plex running on the old server. All was good. 

When I turned off the old server and repointed the new PlexPy to the new Plex instance, all my libraries doubled. Also, all the media metadata disappeared. This seems to be intended behavior as every Plex library has a different ID. Obviously, Plex (and therefore PlexPy) wouldn't know just by name of the library if two libraries were the same.

My question is - is it possible to somehow tell the new PlexPy instance that the new libraries it sees from the new Plex server are logically the same as the old libraries? In other words, can I merge two "Movies" libraries? They are identical in every way (and point to the same media) except for the fact that they reside on different Plex servers, have different IDs, and thus PlexPy sees them as two unique libraries.

**Comment by JonnyWong16** [comment]
#581
#458
