### ISSUE TITLE
TV shows others are watching are shown on plex.tv as in progress to my user

### ISSUE THREAD

**Issue by lmediavilla** [Tautulli/Tautulli#693]
### Reporting Issues:

To ensure that a develpoer has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ 1.3.16] Version
- [ ] Branch
- [ ] Commit hash
- [ windows 10] Operating system
- [2.5.3 ] Python version
- [ ] What you did?
  when some users that is not me is watching from my plex server a tv shows.
- [ ] What happened?
  it shows on my plex.tv that I have that show "in progress"
- [ ] What you expected?
  I should just see my own watched tv shows as "in progress" just my user
- [ ] How can we reproduce your issue?
  it doesn't happen with all users or with all tv shows or movies but it happens 
- [ ] What are your (relevant) settings?
  everything is normal
- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
#### Link to log:

Some pictures
http://i65.tinypic.com/2s7iebl.jpg
http://i67.tinypic.com/302x4rl.jpg
http://i67.tinypic.com/sc3jt1.jpg

**Comment by Arcanemagus** [comment]
If plex.tv itself is showing this, then this is a bug in Plex that can't be fixed here as PlexPy gets it's data from there.

**Comment by JonnyWong16** [comment]
Not a PlexPy issue.
