### ISSUE TITLE
Feature Request: Whatsapp as new notifications agent

### ISSUE THREAD

**Issue by Pakorro** [Tautulli/Tautulli#694]
Hi, it will be possible to add WhatsApp for IOS / Android as new notifications agent?. A created users group receiving a reporting from Plexpy weekly...

Excuse me if this request or new feature is already posted...

Regards.

**Comment by Arcanemagus** [comment]
Duplicate of https://github.com/drzoidberg33/plexpy/issues/624.

**Comment by drzoidberg33** [comment]
https://github.com/drzoidberg33/plexpy#feature-requests
