### ISSUE TITLE
Mako Runtime Error: KeyError: 'art'

### ISSUE THREAD

**Issue by TwilightDuck** [Tautulli/Tautulli#696]
### Reporting Issues:

To ensure that a develpoer has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ 1.3.16] Version
- [master ] Branch
- [ 00c0c96b1b898d325b1babb8e120e8ec88892e2b ] Commit hash
- [ Linux 4.4.0-040400-generic ] Operating system
- [ 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2] ] Python version
- [Clicked on point in graph and wanted to navigate to the show ] What you did?
- [ It gave me the following error: http://i.imgur.com/h7UtaDS.png] What happened?
- [To see the show and it's history ] What you expected?
- [No clue ] How can we reproduce your issue?
- [None ] What are your (relevant) settings?
- [http://pastebin.com/18v2G7Fu ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
#### Link to log:

http://pastebin.com/18v2G7Fu

**Comment by JonnyWong16** [comment]
I believe this is already fixed on the dev branch.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.0.
