### ISSUE TITLE
Not install in WinServer 2008 R2

### ISSUE THREAD

**Issue by bvicil** [Tautulli/Tautulli#697]
### Reporting Issues:

When i want to double-click plexpy.py console appeared and close. 
and i run in command line an error occured shown below 

`http://pastebin.com/BHQWKxC3`

**Make sure you provide the following information below:**
- [ ] Version
  plexpy.py 1.3.16
- [ ] Operating system
  WinServer 2008 R2
- [ ] Python version
  python 2.7

**Comment by JonnyWong16** [comment]
Read these four posts here:
https://forums.plex.tv/discussion/comment/1103917/#Comment_1103917

**Comment by bvicil** [comment]
i changed my timezone to UTC +2 Istanbul than it works.

thanks lot.
