### ISSUE TITLE
Unable to Delete User from User Page Using Edit Mode in Dev

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [Tautulli/Tautulli#698]
- [ ] Version
  1.3.16
- [ ] Branch
  Dev
- [ ] Commit hash
  https://meraki--c.na26.visual.force.com/apex/vfcase?id=50032000010d8pC&srPos=0&srKp=500&sfdc.override=1
- [ ] Operating system
  Linux
- [ ] Python version
  2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]
- [ ] What you did?
  Attempted to delete and/or purge a user from the User page edit mode 
- [ ] What happened?
  A confirmation box with no text appeared and after hitting confirm nothing happens (including no logs generated)
- [ ] What you expected?
  The user to be removed from plexpy
- [ ] How can we reproduce your issue?
  Attempt to delete a user from the User page using edit mode

**Comment by JonnyWong16** [comment]
Fixed in dev.
