### ISSUE TITLE
History not updating

### ISSUE THREAD

**Issue by F13** [Tautulli/Tautulli#699]
### Reporting Issues:

To ensure that a develpoer has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
  1.3.16
- [ ] Branch
  master
- [ ] Commit hash
  00c0c96b1b898d325b1babb8e120e8ec88892e2b
- [ ] Operating system
  Windows 10
- [ ] Python version
  2.7.4 (default, Apr 6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]
- [ ] What you did?
  Uncertain. May have done an update on 5/8.
- [ ] What happened?
  No new activity reported since 5/8. Not sure what exactly is causing the issue. Only error in logs has been occurring for a while, but may be related I suppose. Active streams still show, and newly added media appears, but the history, users, and libraries sections do not reflect that the stream ever occurred.
- [ ] What you expected?
  Streams to be logged.
- [ ] How can we reproduce your issue?
  I'm not sure exactly what's causing it, but the error in the log relates to an SSL plex server. I am using self-signed certs and a reverse proxy server, so it's possible it's related to one of those.

This error is in the logs since before this problem, though.

I'm also seeing errors connecting to uri endpoints, but I can manually enter them in a browser and access them fine.
- [ ] What are your (relevant) settings?
  Plex server port 80 (redirection occurs via reverse proxy at destination), SSL enabled.
- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
#### Link to log:

https://gist.github.com/F13/d59bd2b6170ef4e686c92db6cf3708d6

**Comment by JonnyWong16** [comment]
Either SSL is missing (instructions to install it [here](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#windows-q1)) or try disabling websockets.

**Comment by F13** [comment]
Is this a recent change? It's been functional without any additional steps. Disabling websockets doesn't change anything.

**Comment by JonnyWong16** [comment]
When was it working, and when did it stop working?

In your logs, the websocket never connected. And the fallback to polling on May 07, couldn't access the end point `/status/sessions`. Both of these would prevent history from being logged.

How is PlexPy connected to your Plex server? Same machine, LAN, or WAN? What are you Plex Media Server settings in PlexPy?

**Comment by F13** [comment]
I haven't been monitoring it regularly, I just noticed that the last logged entry was 8 May. That would mean it was recording history as of 8 May, but not after that. I'm reinstalling Python now, as it seems my python install was incomplete (I had no Scripts directory at all).

Still puzzled as to why it was working as of the 8th.

**Comment by F13** [comment]
Reinstalled python, installed SSL, re-enabled sockets, and it seems to be logging now. I'm still baffled why it was working as of the 8th (and the entire time I've had PlexPy installed, since February) if I was missing dependencies....but, so be it, I suppose.
