### ISSUE TITLE
Plex Logs Parser

### ISSUE THREAD

**Issue by aaronchi** [Tautulli/Tautulli#7]
I was having some issues with the Log Parser not parsing certain lines correctly. Some log lines seem to come out with only partial data for some reason. Without solving the problem of why certain lines were not getting read correctly, this solved the issue for me.

```
for i in log_lines:
        try:
            log_time = i.split(' [')[0]
            log_level = i.split('] ', 1)[1].split(' - ',1)[0]
            log_msg = i.split('] ', 1)[1].split(' - ',1)[1]
            full_line = [log_time, log_level, log_msg]
            clean_lines.append(full_line)
        except:
            pass
```

**Comment by drzoidberg33** [comment]
Ye, this was kind of a really rough bit of code.

Didn't notice any malformed log lines on my three test machines though. I will add the check for malformed lines but would you also mind posting the lines (or entire log) which are causing the issue? I would like to see what's happening there.

**Comment by drzoidberg33** [comment]
Addressed this in commit https://github.com/drzoidberg33/plexpy/commit/b4f1bddc0233bba3ec9df6071ffe082092dbd51f.

Please update and see if this helps.

**Comment by aaronchi** [comment]
If I log the lines that are causing problems, I get weird output like this:

```
2015-07-04 06:29:49 ERROR   Jul ive)
2015-07-04 06:29:49 ERROR   Jceeded.
2015-07-04 06:29:49 ERROR   Jul 04s.
2015-07-04 06:29:49 ERROR   Jul 04,
2015-07-04 06:29:49 ERROR   Jul 04,)
2015-07-04 06:29:49 ERROR   Jul 04,
2015-07-04 06:29:49 ERROR   Jceeded.
2015-07-04 06:29:49 ERROR   Jul 04s.
```

I couldn't correlate the errors to actual lines in my log file so It's possible that it may be something about the way the log is read or something specific to windows. Your fix works.

**Comment by aaronchi** [comment]
It must be something about the tail function that is causing the problem. I noticed that all of the bad lines happen at the end of the log list.

**Comment by drzoidberg33** [comment]
Check if commit https://github.com/drzoidberg33/plexpy/commit/7ab590a5ff4d4237fee724855d068f7834901051 fixes it.

I only noticed your issue when actually running the Windows version, the log reads fine on Unix/Linux it seems. I replaced the tail script with a different one which seems to work better on Windows.

**Comment by aaronchi** [comment]
:+1:
