### ISSUE TITLE
Request: Include show title in recently added list on home page

### ISSUE THREAD

**Issue by jroyal** [Tautulli/Tautulli#70]
From the forums

> @wally007 said:
> can you please reconsider or add an option what details are displayed for recently added tv shows/movies ?
> If tv show doesnt have a poster ( any recorded tv, home movie or tv show which is not listed on thetvdb ) I have no idea what was added since plexPy displays only season number and not the show title.
> 
> ![](https://15254b2dcaab7f5478ab-24461f391e20b7336331d5789078af53.ssl.cf1.rackcdn.com/plex.vanillacommunity.com/editor/95/yjxubofpumjb.jpg)

**Comment by jroyal** [comment]
I'll work this, if you haven't already.

**Comment by drzoidberg33** [comment]
I haven't done any work on that.

**Comment by drzoidberg33** [comment]
Released.
