### ISSUE TITLE
notification sub-strings not working

### ISSUE THREAD

**Issue by bbrendon** [Tautulli/Tautulli#701]
Using version. 1.3.16

For example, this string:
{title} <tv>\- {episode_name} (S{season_num00}E{episode_num00}) </tv>was recently added.

Yields:
The Big Bang Theory - (S00E01) was recently added.

Its missing episode names and reports the wrong episode #. The Episode # reported is always S00E01, its never the correct season or episode number.

**Comment by JonnyWong16** [comment]
Did you not see the bright orange text in settings?

```
Note: No Season/Episode or Album/Track metadata will be available.
```

Also answered in the FAQ: [Q: All my recently added notifications are showing S00E01](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#notifications-q4).

**Comment by bbrendon** [comment]
Shit. I googled it and read through the FAQ. I swear!! Sorry.
