### ISSUE TITLE
Maxed users displayed

### ISSUE THREAD

**Issue by Tripletap007** [Tautulli/Tautulli#702]
I believe I hit the limit of 16 users displayed/tracked as new users don't show up.  Is there a way to increase this number?  Updated to latest everything as of 5/12/16 and restarted PlexPy.  Still have the issue.

**Comment by JonnyWong16** [comment]
There is no user limit in PlexPy. 

You didn't follow the guidelines for reporting issues.

**Comment by Tripletap007** [comment]
Every user I've added after 15 (16 counts as "local") don't show up.  There clearly is a a limit but maybe not one you intended, I'm not trying to ruin your day.  I'm sorry I didn't follow the guidelines from my mobile device.

Sent from my iPhone

On May 13, 2016, at 06:49, JonnyWong16 notifications@github.com wrote:

There is no user limit in PlexPy.

You didn't follow the guidelines for reporting issues.

**Comment by Arcanemagus** [comment]
@Tripletap007 if there is a limit, it's not 15...
![image](https://cloud.githubusercontent.com/assets/427137/15296165/e36ed852-1b48-11e6-82c1-064e27ba6c5f.png)

Does Plex itself show the users?

**Comment by JonnyWong16** [comment]
@Tripletap007 We can't help you until you provide all the requested information. https://github.com/drzoidberg33/plexpy/tree/dev#issues
