### ISSUE TITLE
[Feature Request] Additional Notification Agent - "Join"

### ISSUE THREAD

**Issue by nickkarma** [Tautulli/Tautulli#703]
A decent number of people have been leaving Pushbullet for "Join". The one thing stopping me is honestly PlexyPy not having the notifications on it. Any chance it can be implemented? Took a brief look at the code doesn't seem much different than Pushbullet. 

Here's their API page: http://joaoapps.com/join/api/

**Comment by Hellowlol** [comment]
Ye, seems like a simple request that anybody can do. I suggest you make a request on feature hub

**Comment by nickkarma** [comment]
Oh thanks, I made the request over there. Sorry I missed it at the bottom. Impatient me read the first half of the main git page and missed that.

**Comment by JonnyWong16** [comment]
Posted on FeatHub. http://feathub.com/drzoidberg33/plexpy/+88

Closing.

**Comment by JonnyWong16** [comment]
Side note. You can use a custom script to send to Join.

**Comment by JonnyWong16** [comment]
Eh, this will take me like 5 minutes to add.
