### ISSUE TITLE
Most recent 12 dev commits broke something with plexpy

### ISSUE THREAD

**Issue by shottothedome** [Tautulli/Tautulli#704]
### Reporting Issues:

To ensure that a develpoer has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [363d1b07ca90fb32b31b05665fc75484c12d7479 ] Version
- [ Dev] Branch
- [ ] Commit hash - 363d1b07ca90fb32b31b05665fc75484c12d7479
- [ ] Operating system -  Debian 3.2.63-45-amd64-ufs #1 SMP Wed Nov 26 15:57:39 EST 2014 x86_64 GNU/Linux
- [ ] Python version - 2.7.3
- [ ] What you did? - Updated git for dev branch from plexpy gui interface. there were 12 commits listed. Issue with is one of those commits as it never rebooted. manually startup also failed with message below. backed up database and config.ini file. deleted/cloned fresh copy of dev branch. Same issue
- [ ] What happened? - Plexpy no longer loads and has failure message
  error:

```
plex@StappLeeServer1:/opt/plexpy# python PlexPy.py
Traceback (most recent call last):
  File "PlexPy.py", line 35, in <module>
    import plexpy
  File "/opt/plexpy/plexpy/__init__.py", line 34, in <module>
    import activity_pinger
  File "/opt/plexpy/plexpy/activity_pinger.py", line 20, in <module>
    import activity_processor
  File "/opt/plexpy/plexpy/activity_processor.py", line 25, in <module>
    import notification_handler
  File "/opt/plexpy/plexpy/notification_handler.py", line 31, in <module>
    import notifiers
  File "/opt/plexpy/plexpy/notifiers.py", line 41, in <module>
    import twitter
  File "lib/twitter/__init__.py", line 56, in <module>
    from .api import Api                        # noqa
  File "lib/twitter/api.py", line 29, in <module>
    from requests_oauthlib import OAuth1
  File "lib/requests_oauthlib/__init__.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "lib/requests_oauthlib/oauth1_auth.py", line 6, in <module>
    from oauthlib.common import extract_params
ImportError: No module named oauthlib.common
```
- [ ] What you expected? No issues
- [ ] How can we reproduce your issue? not 100% sure. Also backed up mydatabase tried fresh checkout of dev branch and same issue
- [ ] What are your (relevant) settings? nothing special - https/ssl is on, using port 8182. Admin account created. guest user login is active with most users set to guest login
- [ ] Doesn't appear logs are created in the /opt/plexpy/logs - pastebin of traceback error: http://pastebin.com/PiyXB8FP

**Comment by Collisionc** [comment]
I'm seeing the same thing, with nearly similar settings as far as https, admin account + guest login active. 

The error occurred somewhere between these commits: https://github.com/drzoidberg33/plexpy/compare/9e1c4b1a88d5455effbae32631671d54769ba375...363d1b07ca90fb32b31b05665fc75484c12d7479

**Comment by JonnyWong16** [comment]
Try updating now.

**Comment by Collisionc** [comment]
Works fine. Thanks!

**Comment by shottothedome** [comment]
Yep just did a git pull and now everything works again. Thanks
