### ISSUE TITLE
Logs not ordered correctly

### ISSUE THREAD

**Issue by jvoostv1** [Tautulli/Tautulli#705]
**Version:**
VERSION 1.4.0
**Branch:**
master
**Commit hash:**
a726154b1d2231fdc59d2ffb2d567e2008e68348
**Operating system:**
~~Linux 4.0.4-unRAID~~ Ubuntu 14.04 LTS
**Python version:**
2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
**What you did?**
Changed date format and afterwards viewed the logs (I think)
**What happened?**
The log entries aren't sorted by date correctly.
**What you expected?**
Them to be sorted by date correctly..
**How can we reproduce your issue?**
1. Change the Date Format, so that the default increment (Month?) isn't at the start
2. Wait a few moments
3. Look at the logs and notice the newest entries aren't at the top
**What are your (relevant) settings?**
**Date Format:** DD-MM-YYYY
**~~Link to~~ logs:**

> 28-Mar-2016 02:17:21 - INFO    :: MainThread : PlexPy is shutting down...
> 2016-03-28 02:17:31 - INFO    :: MainThread : Checking to see if the database has all tables....

The entry starting with 28-Mar-2016 is the first log entry shown, even though it is not the most recent entry in the log. That would be:

> 2016-05-16 00:37:47 - INFO    :: CP Server Thread-9 : PlexPy is up to date

**Comment by Hellowlol** [comment]
What log entries are you looking on? in the file or via the browser?

**Comment by jvoostv1** [comment]
The issue is regarding the browser view. When I download the log, they are sorted correctly (by date ASC).

**Comment by JonnyWong16** [comment]
The new logs should be using ISO date format `YYYY-MM-DD HH:mm:ss`.

The old logs were using `DD-MMM-YYYY HH:mm:ss` Here 28 > 2016 when sorted alphanumerically.

This can be fixed by clearing the old logs.

**Comment by jvoostv1** [comment]
Guess that explains it. Thanks for the quick response!

**Comment by JonnyWong16** [comment]
@Hellowlol There is a small bug with logs out of order if the timestamp is exactly the same. Not sure how we can fix that though.

**Comment by Hellowlol** [comment]
I think I found the bug. We should only sort when needed, if it's asc or des we should just let it run or do a reverse.

**Comment by JonnyWong16** [comment]
:+1: P/R when you have the time? It's very minor.

**Comment by Hellowlol** [comment]
Ye, I'll do it when I get home from work.
