### ISSUE TITLE
1.4.0 Settings not accessible when auth is disabled

### ISSUE THREAD

**Issue by rix1337** [Tautulli/Tautulli#706]
I was using plexpy behind my muximux portal (embedded in an iframe).

With this setup I could previously pass through my plexpy login using my nginx reverse proxy using setheaders and thus simply bind my plexpy subpath to the iframe.

With the new auth method a blank page would show. Only setting the iframe to plexpy/auth/login would display the new form.

Sadly, no redirect within the iframe would occur, so on pressing "Sign in" the iframe would stay on the login form instead of heading to plexpy/home. (Might be able to fix this?)

I would also love an option to go back to the old login form (because of the ability to secure login for my local network, and ease of login through the passed auth headers on my reverse proxy).

**Now on the bug:**
On disabling auth completely (my current workaround to be able to use muximux with plexpy/home, I cannot access the settings page anymore. Pressing the according button/navigating to plexpy/settings merely redirects me to home. This can't be working as intended :P

Apart from that: super sweet update!

**Comment by rix1337** [comment]
Bonus, without auth enabled I could still log out of my session and now cannot log back in..

Restarting plexpy again fixed this. Maybe this is reproducable!

**Comment by JonnyWong16** [comment]
Recently discussed on the Plex forums [here](https://forums.plex.tv/discussion/comment/1183695/#Comment_1183695) with a solution.

Submit a feature request for an option to use basic HTTP authentication instead of the HTML form.
