### ISSUE TITLE
[Feature Request] Monitorizing streaming from in a live broadcast tv channel.

### ISSUE THREAD

**Issue by Pakorro** [Tautulli/Tautulli#708]
I have tested that Plexpy can not monitorize when I select a channel plugin with stream from a source video.

It's possible to add this feature. I would like contrólate streaming from my users that they are using a sourse from a channel plugin ( IPTV, CCCLOUD, etc )

Regards,
Paco

**Comment by JonnyWong16** [comment]
Duplicate of #522.

And does not follow [guidelines](https://github.com/drzoidberg33/plexpy#feature-requests).

Closing.
