### ISSUE TITLE
Facebook blocking notifications 

### ISSUE THREAD

**Issue by yoharnu** [Tautulli/Tautulli#710]
I get an error (technically a warning) whenever something gets sent to Facebook (below). I was previously including a link to Plex, but thought it might be triggering this. Even without that link, I still get the error. I have now stopped sending the poster, and I'm waiting to see if that resolves the problem. Even if it does, I believe this would still be considered a bug .

PlexPy Notifiers :: Error sending Facebook post: Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive.

**Comment by yoharnu** [comment]
It triggered while I was typing this up. It seems the poster was the issue. I do not have the imgur option checked. Does this notification use that option? Or is it some other issue? I would like to include the poster for aesthetics, but it is definitely not a priority.

**Comment by JonnyWong16** [comment]
http://forums.plex.tv/discussion/comment/1184070/#Comment_1184070
