### ISSUE TITLE
PlexPy Database Import Tool

### ISSUE THREAD

**Issue by camjac251** [Tautulli/Tautulli#711]
A few months ago, I had created an issue asking if it was possible to merge PlexPy databases. I have two installs that became one and wanted to merge the two so I could retain all watched logs from everyone. Could this be added as a feature in PlexPy? I have an older database backed up of PlexPy that I'd like to add into this current database without overriding anything.

**Comment by JonnyWong16** [comment]
And it's still there #564. Please don't create duplicate requests. It won't make it go any faster.

**Comment by camjac251** [comment]
Oh sorry. I was unable to find the issue.
