### ISSUE TITLE
Stream Details showing wrong Resolution

### ISSUE THREAD

**Issue by mannibis** [Tautulli/Tautulli#712]
Hello,

So after this latest major update, I noticed that the Stream Info has changed a bit. It now includes the stream container, which is nice info to have, but I have noticed that the resolution displayed under Stream Details is incorrect. As you can see below, the Width and Height are 1280 and 720 respectively, which is 720p. However, under Resolution it shows 1080p. I have tracked this down and it seems to always display the source resolution. Is this the intended effect? I would imagine that the source resolution would just be under Source Details, and not Stream Details. Thank you for all the work you  have done on this amazing app. Let me know if you don't understand what I'm saying. Thanks

**Git Branch:** master
**Git Commit Hash:**    a726154b1d2231fdc59d2ffb2d567e2008e68348
**Platform:**   Darwin 13.4.0
**Python Version:** 2.7.11 (default, Dec 5 2015, 22:44:43) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
### Stream Details

**Media**
Container: mkv
Resolution: 1080p
**Video**
Stream: transcode
Width: 1280
Height: 720
Codec: h264
**Audio**
Stream: transcode
Codec: aac
Channels: 2
### Source Details

**Media**
Container: mkv
Resolution: 1080p
Bitrate: 9113 kbps
**Video**
Width: 1920
Height: 1080
Codec: h264
Aspect Ratio: 1.78
Frame Rate: 24p
**Audio**
Codec: ac3
Channels: 2

**Comment by JonnyWong16** [comment]
I probably entered the wrong value when I moved the stuff around. Thanks for letting me know.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.1.
