### ISSUE TITLE
Imgur link sends you to nullreferer.org which doesn't exist.

### ISSUE THREAD

**Issue by doonga** [Tautulli/Tautulli#714]
If you click the link to set up the Imgur oauth, it sends you to this link: http://nullreferer.org/?https://api.imgur.com/oauth2/addclient

http://nullreferer.org/ doesn't exist. If you change that to http://nullrefer.com/ then it works.

**Comment by JonnyWong16** [comment]
1. Please follow the [guidelines](https://github.com/drzoidberg33/plexpy#issues) when posting issues.
2. Redirects use http://dereferer.org/ unless you changed it under Settings > Extra Settings.
