### ISSUE TITLE
Disabling certain notifications

### ISSUE THREAD

**Issue by icehuntman** [Tautulli/Tautulli#715]
**Version:**
VERSION 1.4.0
**Branch:**
master
**Commit hash:**
a726154b1d2231fdc59d2ffb2d567e2008e68348
**Operating system:**
Linux 4.4.0-22-generic
**Python version:**
2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413]

Is it possible to disable the "PlexPy has paused" and "PlexPy has resumed" notifications but keep the "PlexPy started" and PlexPy has watched" enabled?
It seems i cannot find the right setting.

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q1
