### ISSUE TITLE
PlexPy unable to start after update to 1.4.1

### ISSUE THREAD

**Issue by jvoostv1** [Tautulli/Tautulli#717]
**Version:**
VERSION 1.4.1
**Branch:**
master
**Commit hash:**
c3378e165339a218bf98d0742d2ecfd0485a519a (I think; version.lock)
**Operating system:**
~~Linux 4.0.4-unRAID~~ Ubuntu 14.04 LTS
**Python version:**
2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
**What you did?**
Updated PlexPy
**What happened?**
Didn't start.
**What you expected?**
PlexPy to start.
**How can we reproduce your issue?**
1. Update PlexPy to 1.4.1
2. Start PlexPy
**What are your (relevant) settings?**
**~~Link to~~ logs:**

> 2016-05-21 14:11:15 - INFO    :: MainThread : Checking to see if the database has all tables....
> 2016-05-21 14:11:15 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
> 2016-05-21 14:11:15 - DEBUG   :: MainThread : Git output: c3378e165339a218bf98d0742d2ecfd0485a519a
> 2016-05-21 14:11:15 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/plexpy
> 2016-05-21 14:11:15 - DEBUG   :: MainThread : Git output: master
> 2016-05-21 14:11:15 - INFO    :: MainThread : Retrieving latest version information from GitHub
> 2016-05-21 14:11:15 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master?access_token=********2f
> 2016-05-21 14:11:15 - DEBUG   :: MainThread : Latest version is c3378e165339a218bf98d0742d2ecfd0485a519a
> 2016-05-21 14:11:15 - INFO    :: MainThread : PlexPy is up to date
> 2016-05-21 14:11:15 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
> 2016-05-21 14:11:15 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
> 2016-05-21 14:11:15 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
> 2016-05-21 14:11:15 - INFO    :: MainThread : PlexPy PlexTV :: Server URL retrieved.
> 2016-05-21 14:11:15 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
> 2016-05-21 14:11:15 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
> 2016-05-21 14:11:17 - WARNING :: MainThread : Failed to access uri endpoint /library/sections. Status code 401
> 2016-05-21 14:11:17 - WARNING :: MainThread : PlexPy Pmsconnect :: Unable to parse XML for get_libraries_list: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2016-05-21 14:11:17 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
>   File "/opt/plexpy/PlexPy.py", line 246, in <module>
>     main()
>   File "/opt/plexpy/PlexPy.py", line 173, in main
>     plexpy.initialize(config_file)
>   File "/opt/plexpy/plexpy/**init**.py", line 194, in initialize
>     plextv.refresh_users()
>   File "/opt/plexpy/plexpy/plextv.py", line 47, in refresh_users
>     shared_libraries = ';'.join(d['section_id'] for d in library_details['libraries_list'])
> TypeError: list indices must be integers, not str

This just keeps repeating.

**Comment by JonnyWong16** [comment]
> 2016-05-21 14:11:17 - WARNING :: MainThread : Failed to access uri endpoint /library/sections. Status code 401

Error 401 is authentication error. Open up the config file and set `refresh_libraries_on_startup = 0` and `refresh_users_on_startup = 0` so that you can get into the WebUI to fetch a new token.

**Comment by jvoostv1** [comment]
That's weird. I changed the settings to 0, as you said. But when PlexPy started after that, I didn't have to re-authorize PlexPy..
Anyway, Thanks for the quick reply!
