### ISSUE TITLE
Notifications work sporadically 

### ISSUE THREAD

**Issue by xilouris** [Tautulli/Tautulli#718]
**Version:1.4.1**

**Branch:master**

**Commit hash:c3378e165339a218bf98d0742d2ecfd0485a519a**

**Operating system:FreeBSD 9.2-RELEASE-p15**

**Python version:2.7.11 (default, Dec 20 2015, 04:36:21) [GCC 4.2.1 20070831 patched [FreeBSD]]**

**What you did?**

I had already in place email notifications for the new additions and also Telegram is working fine. 

**What happened?**

I added Facebook notifications. However they work sporadically, I cannot grasp when or why they work, usually after a reboot or restart of Plexpy I might get one out of date. Since then the email notifications stopped working too. 

**What you expected?**

Well! I expected to get notifications on new additions each time I add some content. 
**How can we reproduce your issue?**

I cannot! Since the update I cannot get any notification on new content. 

**What are your (relevant) settings?**

**Link to logs:**

[Global Notification Settings](https://www.dropbox.com/s/ege54ewe3aguhk9/Screenshot%202016-05-21%2020.27.11.png?dl=0)
[Facebook Notification Settings](https://www.dropbox.com/s/jkwiv4su2qgzifc/Screenshot%202016-05-21%2020.27.38.png?dl=0)
[Facebook Notification settings 2](https://www.dropbox.com/s/fz2cutayqsxerro/Screenshot%202016-05-21%2020.27.53.png?dl=0)
[Log snippet](https://www.dropbox.com/s/46tlbg7jz2vbx77/Screenshot%202016-05-21%2020.31.25.png?dl=0)

> 2016-05-21 20:51:38 - WARNING :: Thread-14 : Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=10 with error timed out
> 2016-05-21 20:51:38 - WARNING :: Thread-14 : PlexPy Pmsconnect :: Unable to parse XML for get_recently_added: 'NoneType' object has no attribute 'getElementsByTagName'.

Thank you for your efforts into building this handy program. :-) 

Regards 

G

**Comment by JonnyWong16** [comment]
Can you post your complete logs?
