### ISSUE TITLE
Problem with ? in streaming device name cant connect to plex server

### ISSUE THREAD

**Issue by happyman1976** [Tautulli/Tautulli#719]
Whenever I have a user that uses a danish letter that is not in the alphabet in english it says theres a problem connecting to the plex server.

eventhoug I asked everybody to remove those letters i still got one with the name apple?tv in the streaming name and that gives the same error, is there a way to correct this, or do I have to again tell him to rename his device name ?!

**Version:**

**Branch:**

**Commit hash:**

**Operating system:**

**Python version:**

**What you did?**

**What happened?**

**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
You mentioned Apple TV.
https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#ios-q1
