### ISSUE TITLE
Asking for username and password after update

### ISSUE THREAD

**Issue by tidusjar** [Tautulli/Tautulli#721]
**Version:**
Latest
**Branch:**
Master
**Commit hash:**
Can't see
**Operating system:**
Server 2016

**What you did?**
Updated using the auto update
**What happened?**
It is now asking for user credentails but I never set any
**What you expected?**
To hit the homepage. 
**How can we reproduce your issue?**

Unsure 
**What are your (relevant) settings?**
Can't see 
**Link to logs:**
Can't access them

**Comment by nayr1991** [comment]
Seems that basic auth has been enabled by default in the latest update. I'm getting similar issues. 
The following is in PlexPy.log

```
2016-05-23 11:10:45 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/opt/plexpy/PlexPy.py", line 247, in <module>
    main()
  File "/opt/plexpy/PlexPy.py", line 219, in main
    webstart.initialize(web_config)
  File "/opt/plexpy/plexpy/webstart.py", line 97, in initialize
    'tools.auth_basic.on': basic_auth_enabled,
UnboundLocalError: local variable 'basic_auth_enabled' referenced before assignment
```

EDIT, my issue might be different. It looks like `basic_auth_enabled` is not defined if you do not have http_password set in config.ini, therefore line 97 of webstart.py fails. As a workaround, setting http_password in config.ini allowed the web server to start and login with that password(username blank) works.

**Comment by JonnyWong16** [comment]
Sorry, please do a manual `git pull` to update again.
