### ISSUE TITLE
PlexPy will not start after web based update

### ISSUE THREAD

**Issue by timmyk0** [Tautulli/Tautulli#722]
PlexPy was working great as usual until I started the update process via the web interface like I have in the past. As you can see in the log file it is failing to do something which seems to be enough to stop it from working at all. 

**Version:** Unsure, it was 26 commits behind as of today, not sure if that helps but I have no way to tell since I can't load anything.

**Branch:** not sure

**Commit hash:** not sure

**Operating system:** Windows Server 2012 R2

**Python version:** 2.7.10

**What you did?** Updated via the web based update like I always do, never had an issue before.

**What happened?** It reloaded, said there was more updates, ran the update again and now PlexPy won't load.

**What you expected?** I expected it to update and then start running again like usual. 

**How can we reproduce your issue?**
Not sure.

**What are your (relevant) settings?**

**Link to logs:**

**Comment by timmyk0** [comment]
I found the config.ini file is missing a password on the `http_password` line. I added a password and now it starts but I can't login. I searched for `http_user` and added a username which still did not appear to let me login. Any other help would be appreciated.

**Comment by JonnyWong16** [comment]
Sorry, please do a manual `git pull` to update again.

**Comment by timmyk0** [comment]
Thank you JonnyWong16, that worked once I figured out the right way to run that command. For anyone that doesn't know:

Open Git Bash in your PlexPy folder, then run `git pull origin master`. This updated PlexPy and it is now running normally again.
