### ISSUE TITLE
Plexpy fails to start if http_password is not defined in config.ini

### ISSUE THREAD

**Issue by nayr1991** [Tautulli/Tautulli#723]
**Version:**
Latest

**Branch:**
MASTER
**Commit hash:**
36e81f44cbe46b2ec4546af53be7b386586e6fed
**Operating system:**
Arch Linux x64. Plexpy from AUR
**Python version:**
2.7
**What you did?**
Updated using the built in updater
**What happened?**
Web server failed to start
**What you expected?**
web server starting
**How can we reproduce your issue?**
Update using the built in updater
start service with `systemctl start plexpy.service`
**What are your (relevant) settings?**
http_password is blank
**Link to logs:**

```
2016-05-23 11:10:45 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/opt/plexpy/PlexPy.py", line 247, in <module>
    main()
  File "/opt/plexpy/PlexPy.py", line 219, in main
    webstart.initialize(web_config)
  File "/opt/plexpy/plexpy/webstart.py", line 97, in initialize
    'tools.auth_basic.on': basic_auth_enabled,
UnboundLocalError: local variable 'basic_auth_enabled' referenced before assignment
```

**Comment by JonnyWong16** [comment]
No need to open up another issue #721.
