### ISSUE TITLE
Unable to configure HTTPS. The pyOpenSSL module is missing

### ISSUE THREAD

**Issue by martinorob** [Tautulli/Tautulli#724]
Hi,
when i try to set up HTTPS i have this error:

The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled.

**Version:**
VERSION 1.4.3
**Branch:**

**Commit hash:**
Git Branch: master
Git Commit Hash:    cfc7d529e1917a88fa5d9038f2f5871c5a60fb4b

**Operating system:**
Synology DSM 6.0-7321 Update 7
Platform:   Linux 3.10.77

**Python version:**
Python Version: 2.7.11 (default, Mar 11 2016, 02:18:13) [GCC 4.9.3 20150311 (prerelease)]

**What you did?**
enable HTTPS with default parameters

**What happened?**
rollback to http

**What you expected?**
configure https

**How can we reproduce your issue?**
Settings
Webinterface
check Enable HTTPS
check Create Self-signed Certificate
keep default for other settings.

**Link to logs:**
http://pastebin.com/ziT1MkR6

**Comment by drzoidberg33** [comment]
https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#windows-q1
