### ISSUE TITLE
Invalid database specified

### ISSUE THREAD

**Issue by fdbgbgsf** [Tautulli/Tautulli#726]
I'm trying to import my Plexivity database into PlexPy, but no matter what I select as file it returns "Invalid database specified.". I can type the path of plexivity.db, or just type gibberish, the result is the same.

The logs aren't really helpful either, all they say is `ERROR    PlexPy Importer :: Invalid database specified.` every-time (that's with debug logging on)

Even tried spinning up a fresh version of Plexivity playing one item and trying to import that db file in a clean version of PlexPy. No Dice.
- Using the latest version of the PlexPy docker image from linuxserver.
- Plexivity database from the latest version.

**Comment by JonnyWong16** [comment]
PM me your Plexivity db file(s) either on the forums or on Gitter. I only have one db file to test with when I added the import tool.

I just tried downloading the latest Plexivity to test and it worked. Did you specify the full path to the `plexivity.db` file (e.g. on Windows this would be `C:\Users\YourName\AppData\Roaming\plexivity\plexivity.db`).

**Comment by fdbgbgsf** [comment]
Sent you two links on Gitter, one full db, one of a single play I used as a test.

As I'm running Plexivity inside docker I mapped a shared volume folder to `/plexivity`
I can access the files via bash as `/plexivity/plexivity.db` so I used that as file path.

**Comment by JonnyWong16** [comment]
I was able to import your plexivity db without any problems.
There might be a problem with the way your folder is mounted between docker containers.

**Comment by fdbgbgsf** [comment]
Ok, yeah I found the problem, the file had no permissions set.
So dumb, sorry.

**Comment by fdbgbgsf** [comment]
Did find a bug, in the plexivity database all IP addresses are formatted as `<Player address="::ffff:255.255.255.255` and they are imported as such in PlexPy.
Tried to manually remove the `::ffff:` from the plexivity.db but that resulted in an `Uncaught exception.` error.
