### ISSUE TITLE
User edit mode first user tooltip for toggles not visible

### ISSUE THREAD

**Issue by fdbgbgsf** [Tautulli/Tautulli#728]
Just a small visibility glitch, when going on the user page into edit mode when hovering above the toggles (notifications, history, access) a tooltip pops up with "Toggle Notifications" etc.

For the first user these tooltips are partially behind the column header. See [image](http://imageshack.com/a/img923/9876/glBXcE.png).
- Latest version of PlexPy master branch
- Latest versions of Safari and Firefox on Mac OS X
- PlexPy running inside linuxserver.io docker container

**Comment by JonnyWong16** [comment]
Fixed in v1.4.4.
