### ISSUE TITLE
Uncaught Exception after Update

### ISSUE THREAD

**Issue by Logvin** [Tautulli/Tautulli#73]
I installed PlexPy and it started and ran great. It said my version was out of date, so I hit the update version and it did its thing. After the update, it never came back online. When I try and execute PlexPy.py from windows 8.1 command prompt, it does the following. I tried installing a fresh copy in a different file location, 100% exact same results.

C:\PlexPy>plexpy.py
15-Aug-2015 18:18:00 - INFO :: MainThread : Checking to see if the database has
all tables....
15-Aug-2015 18:18:00 - INFO :: MainThread : Retrieving latest version informatio
n from GitHub
15-Aug-2015 18:18:00 - DEBUG :: MainThread : Requesting URL via GET method: http
s://api.github.com/repos/drzoidberg33/plexpy/commits/master
15-Aug-2015 18:18:01 - DEBUG :: MainThread : Latest version is fd3daae4915e12099
a7b204decc152568dcd65f3
15-Aug-2015 18:18:01 - INFO :: MainThread : PlexPy is up to date
15-Aug-2015 18:18:01 - INFO :: MainThread : Requesting URLs for server...
15-Aug-2015 18:18:01 - INFO :: MainThread : Writing configuration to file
15-Aug-2015 18:18:01 - INFO :: MainThread : Writing configuration to file
15-Aug-2015 18:18:01 - INFO :: MainThread : Requesting users list refresh...
15-Aug-2015 18:18:02 - ERROR :: MainThread : Uncaught exception: Traceback (most
 recent call last):
  File "C:\PlexPy\PlexPy.py", line 220, in <module>
    main()
  File "C:\PlexPy\PlexPy.py", line 155, in main
    plexpy.initialize(config_file)
  File "C:\PlexPy\plexpy__init__.py", line 168, in initialize
    plextv.refresh_users()
  File "C:\PlexPy\plexpy\plextv.py", line 45, in refresh_users
    if not avatar_urls[0]['custom_avatar_url'] or \
IndexError: list index out of range

Traceback (most recent call last):
  File "C:\PlexPy\PlexPy.py", line 220, in <module>
    main()
  File "C:\PlexPy\PlexPy.py", line 155, in main
    plexpy.initialize(config_file)
  File "C:\PlexPy\plexpy__init__.py", line 168, in initialize
    plextv.refresh_users()
  File "C:\PlexPy\plexpy\plextv.py", line 45, in refresh_users
    if not avatar_urls[0]['custom_avatar_url'] or \
IndexError: list index out of range

**Comment by drzoidberg33** [comment]
Thanks. I'm looking into what would cause this now and will just add some proper exception catching.

**Comment by drzoidberg33** [comment]
Fixed in v1.1.2.
