### ISSUE TITLE
Facebook notifications not working with images

### ISSUE THREAD

**Issue by RichStevenson** [Tautulli/Tautulli#731]
**Version:**
1.4.4

**Branch:**
master

**Commit hash:**
    fc98e2f05294b474fba9e58ae98b143414096678

**Operating system:**
    Linux 4.1.21.alpine.1

**Python version:**
2.7.3 (default, Mar 23 2014, 01:44:56) [GCC 4.6.3]

**What you did?**
Running on NetGear ReadyNAS 6.5. Uninstalled PlexPy and reinstalled.

**What happened?**
Setup FB notifications, and it is no longer posting the poster images or IMDB, etc. Log file says
"Error sending Facebook post: Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive."

**What you expected?**
FB notifications with posters when new content is added to Plex.

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
Please use the search function next time. #710.
