### ISSUE TITLE
Use Play Duration Question

### ISSUE THREAD

**Issue by jackfry** [Tautulli/Tautulli#732]
Hey,

So this isn't an issue just a question. Would it be possible to add the option of using play duration for certain statistics? I.E Most active user and Most active platform. Then have play count used for most watched movie and most watched tv show. As I feel it would show the more popular options rather than just what is longer. For example there could be a movie that's over three hours long but only watched once and then there could be a movie that's an hour long but watched three times. I'd rather the movie that's been watched more be at the top rather than the one that had only been watched once. I hope you understand what I mean. 

Thanks anyway :)

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#feature-requests
