### ISSUE TITLE
Guest Login Not Working

### ISSUE THREAD

**Issue by mrchops1024** [Tautulli/Tautulli#734]
**Version:**
1.4.5

**Branch:**
Master

**Commit hash:**
[ffa208e73f7b67ce29788c625e33d4348de0b30c](https://github.com/drzoidberg33/plexpy/commit/ffa208e73f7b67ce29788c625e33d4348de0b30c)

**Operating system:**
Xubuntu

**Python version:**
2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]

**What you did?**
Been trying to allow my shared users access to see their stats since the feature was released.

**What happened?**
Users are unable to authenticate.

**What you expected?**
Users should be able to login when granted access.

**How can we reproduce your issue?**

**What are your (relevant) settings?**
Settings > Access Control > Allow Guest Access to PlexPy  = Enabled
Allow Guest Access enabled for specific user I've been testing with (have also tried 2 other users).

**Link to logs:**
I cleared the log before capturing the error, since the log was quite large and had a lot of information in it I didn't want to go mask.

> 2016-05-26 09:53:44   DEBUG   PlexPy WebAuth :: Invalid login attempt from 'PLEXUSERNAME'.
> 2016-05-26 09:53:44 WARNING PlexPy WebAuth :: Unable to retrieve Plex.tv server token for user 'PLEXUSERNAME'.
> 2016-05-26 09:53:10 INFO    Cleared the plexpy.log file.

Let me know what else I can provide.

**Comment by JonnyWong16** [comment]
- Do you have remote access enabled for your server?
- Is it published to plex.tv [here](https://plex.tv/api/resources) and [here](https://plex.tv/pms/servers.xml)?
- Have you tried clicking "Verify Server", then "Save" in the settings?

**Comment by mrchops1024** [comment]
> Do you have remote access enabled for your server?

Yes

> Is it published to plex.tv here? https://plex.tv/api/resources

Yes

> Have you tried clicking "Verify Server", then "Save" in the settings?

That fixed it, thanks!
