### ISSUE TITLE
[Bug] login page comes up every time i click on stuff

### ISSUE THREAD

**Issue by stohle** [Tautulli/Tautulli#736]
I was 172 commits behind. shut down plexpy. ran "git pull". fired up plexpy again and now i get the login screen every time i click on anything. i click on settings, im back to the login page. I click libraries, im back to the login page. you get the drill.

LOGS: 
terminal output http://pastebin.com/2CzfqhLj
logfile http://pastebin.com/uvH8Q1ZL

*_Version:_latest*

*_Branch:_master*

**Operating system:Debian

**Python version:2.7

**What you did? git pull

**What happened?
login screen pops up on every click

**How can we reproduce your issue?**

I dont know if its possible. I was 172 commits behind and just ran git pull
**What are your (relevant) settings?**
I have authentication enabled

**Comment by JonnyWong16** [comment]
Have you cleared your browser cache?

**Comment by stohle** [comment]
@JonnyWong16 wow that was easy. works now. may i ask why clearing my cache helps? whats in my cache thats causing this?

**Comment by JonnyWong16** [comment]
I dunno, probably old login cookies from before the update.

Honestly thought, clearing browser cache was just a wild guess.
