### ISSUE TITLE
Email Notification Line Break Missing

### ISSUE THREAD

**Issue by josephsiu** [Tautulli/Tautulli#738]
**What you did?**
The line breaks in email notification messages periodically disappear in the email body but appear correct in the interface. It is possible that this is an effect of periodically updating PlexPy to the latest version and the line breaks are resetting. This is sometimes resolved by re-entering and saving the custom notifications again (not always).

**What happened?**
The email body shows no line break when received. Here is a sample message:

> The following movie was recently added to Server and is now available for streaming! ==================== Movie (2016) ==================== Starring: Bob Doe, Sandra Doe, Tommy Doe Directed By: John Doe Written By: Duration: 115 minutes Genres: Sci-Fi, Action, Thriller, Crime Rated: R

**What you expected?**
Since line break shows up in the interface, it is expected that the received email body should show the same. _See attached screenshots below for the exact custom notification setting._

![interface_setting](https://cloud.githubusercontent.com/assets/7220262/15663812/83e558ea-26b3-11e6-971c-805982b48ea7.PNG)

**How can we reproduce your issue?**
Add line break (new line) to a customized notification message body and send notification.

**Version:** 1.4.5
**Branch:** master
**Commit hash:** ffa208e73f7b67ce29788c625e33d4348de0b30c
**Operating system:** Windows 10
**Python version:** 2.7

**Comment by jaycedk** [comment]
You can use HTML5 tags.
For line breaks use `<br>`

**Comment by JonnyWong16** [comment]
What @jaycedk said. If you have HTML enabled in the Email settings, then use `<br>` for line breaks. Otherwise, disable HTML support and all the line breaks should be kept in plain text.
