### ISSUE TITLE
Same IP for login logs

### ISSUE THREAD

**Issue by daurpam** [Tautulli/Tautulli#739]
**Version:** 1.4.5

**Branch:** Master
**What you did?**  Look "login logs"
**What happened?** The IP logs for all logins is the same: 172.17.0.1

**What you expected?** The real public IP of the users that login into plexpy

![plexpy](https://cloud.githubusercontent.com/assets/18077653/15736773/5cc21c9e-28a2-11e6-8713-80a842e33362.PNG)

**Comment by daurpam** [comment]
No, I connect from Mobile, in the same LAN, from work, without proxies o reverse proxies.

In Users panel all the IPs appears correctly.

**Comment by JonnyWong16** [comment]
This has been answered before. It's not a problem with PlexPy, but with your network configuration instead. ~~PlexPy just pulls whatever IP that Plex tells it, so you need to fix it on the Plex side.~~

You didn't fill out the entire issue template so I have no idea what OS you're using.  I've seen this happen if a docker container isn't configured properly or if you are behind a VPN and your VPN provider does not forward the proper headers.

**Comment by daurpam** [comment]
Ok thanks. I'll try to review that. You're right, Plexpy is dockerize in a DS 716+ of Synology. But I thought that this info for logins in Plexpy was directly extract for the platform itself and Plex doesn't have to work on this.

**Comment by JonnyWong16** [comment]
~~The IP address is reported by the Plex API. You can see the IP address in the XML here when there is a stream going.~~
~~http://<your_plex_ip>:32400/status/sessions?X-Plex-Token=<ypur_plex_token>~~

Sorry, I read your issue wrong.  You're talking about the login IP not the streaming IP. 

My reasoning is still correct though that it's something you need to fix with your docker container. It's the `X-Forwarded-For` header that is not being passed through to your docker container.
