### ISSUE TITLE
Shows transcode when viewer using subtitles

### ISSUE THREAD

**Issue by TwilightDuck** [Tautulli/Tautulli#74]
It shows that it's transcoding, which is technical true but it's confusing because it doesn't take much CPU resources. Maybe there could be some option

**Comment by Mirabis** [comment]
It's still 'transcoding' and burning the subs in. Which does add stress, while direct streaming the audio. So the status is right :p

**Comment by drzoidberg33** [comment]
As @Mirabis states. If a video is transcoding it's transcoding, doesn't matter what triggers it so this request doesn't really make sense.

PlexPy will also only show the transcoding icon in the history if video is transcoded (so won't show if it's a direct stream).
