### ISSUE TITLE
Posters not updated

### ISSUE THREAD

**Issue by daurpam** [Tautulli/Tautulli#740]
**Version:** 1.4.5

**Branch:** Master

**What you did?** Posters didn't update.

**What happened?** 

When a new item is added to a library, Plex Media Server gets metadata, but if this doesn't occur at first time Plexpy show a preview capture of video file. When manually update the association of metadata in Plex and poster updates, Plexpy still showing the preview capture and not the updated poster.

**What you expected?** I hope the posters in Plexpy sync with the Plex Media Server posters.

**How can we reproduce your issue?** Add a new item and don't get an association inmediatly.

**Comment by Hellowlol** [comment]
Its because the plexpy caches the all the images from pms to reduce the load on pms. You can delete the image cache with ..../delete_image_cache or simply disable the image cache in the config file. Maybe there should be a method to manually refresh i image.. :P

**Comment by daurpam** [comment]
In fact I have the "disable image cache" activated, but stil no updates. Even "Use Video Preview Thumbnails (BIF)" option disabled too. :(

**Comment by JonnyWong16** [comment]
http://forums.plex.tv/discussion/comment/1191815/#Comment_1191815

@Hellowlol We should add a method to force refresh a poster in PlexPy.

**Comment by Hellowlol** [comment]
Ye.

**Comment by daurpam** [comment]
Thanks for your answers. After clear cache, cookies and refresh web page, the posters show correctly. Thank you, for your time and your project.

**Comment by Hellowlol** [comment]
https://github.com/drzoidberg33/plexpy/pull/741
