### ISSUE TITLE
Image refresh button breaks layout

### ISSUE THREAD

**Issue by Arcanemagus** [Tautulli/Tautulli#743]
The image refresh button [recently added](https://github.com/drzoidberg33/plexpy/pull/741) breaks the layout in a few places:

![image](https://cloud.githubusercontent.com/assets/427137/15829781/229a2f0e-2bca-11e6-9bd6-3a6064de4b17.png)

![image](https://cloud.githubusercontent.com/assets/427137/15829806/386d773c-2bca-11e6-8802-aa0ac1444198.png)
_(Refresh button is over the border edge)_

And this isn't necessarily breaking, but it just looks bad 😛:
![image](https://cloud.githubusercontent.com/assets/427137/15829902/a93aaeee-2bca-11e6-86cc-8a2b337b28d2.png)

---

I think ideally this button should show similar to how it does on the activity section (after the position is fixed), but only show on hover, and possibly should be slightly transparent.

**Comment by JonnyWong16** [comment]
Hmm... this is how it looks on mine (and only on hover)
![image](https://cloud.githubusercontent.com/assets/9099342/15830604/34574534-2bce-11e6-807e-4e505f73f85a.png)

Possibly browser cache (the `.css` file)?

**Comment by Arcanemagus** [comment]
I hadn't loaded it on this browser since before the feature existed, but I'll try clearing the cache.

**Comment by Arcanemagus** [comment]
Looks _much_ better on a reload, closing this!

**Comment by JonnyWong16** [comment]
> I hadn't loaded it on this browser since before the feature existed, but I'll try clearing the cache.

Well if you loaded it before the feature then it would have the old `.css` file. =P
