### ISSUE TITLE
Combine posters with notifcation

### ISSUE THREAD

**Issue by joewalch** [Tautulli/Tautulli#745]
I have set up an imgur account and enable posters the 'new' way however I get a separate notification for the poster from the main notification. Is there any way to combine both in one message?

**Comment by JonnyWong16** [comment]
Since you did not mention a notification agent, I'm assuming Telegram.

It's separated in Telegram because you cannot format the text (b, i, a[href], code, pre) that accompanies the image.

**Comment by joewalch** [comment]
Sorry rookie error, yes it is telegram. Its only for me would a different agent work better?

**Comment by JonnyWong16** [comment]
You can use any agent you want. I don't know what would work better for you, but Telegram is the only one that sends two messages.

**Comment by joewalch** [comment]
That's helpful thanks.

**Comment by Kedryn** [comment]
Sorry but, if you keep image and text separate, it will often happen that we get batch of images first, then batch of text.
I personally think that having one single message with inline image and without text formattig is way better than having them separate and unsynced text/image but with formatting.

Anyway, you can put an option in the telegram notification config, 
Single message without formatting, or separate with formatting.
