### ISSUE TITLE
Multiple libraries after importing old db

### ISSUE THREAD

**Issue by joewalch** [Tautulli/Tautulli#746]
I have reinstalled W10 and therefore plexpy. I imported the database (by replacing the newly created .db with the old .db. I am getting duplicate library entries as per the attached pics. I have tried purge on all but the first entry as I don't want to lose my data. Any ideas how to tidy this up?

If it helps when I click any toggle icon on the 3rd line only the 1st line of the 3 changes.

![1](https://cloud.githubusercontent.com/assets/15211061/15923041/deefa29c-2e22-11e6-96f6-320e20a5a2f9.PNG)

![2](https://cloud.githubusercontent.com/assets/15211061/15923042/e1428910-2e22-11e6-95fb-7f925ca1a547.PNG)

**Version:1.4.5

**Branch:master

**Commit hash:ffa208e73f7b67ce29788c625e33d4348de0b30c

**Operating system:10

**Python version: 2.7.11

**What you did? import database after reinstalling W10

**Comment by Hellowlol** [comment]
read faq?

**Comment by joewalch** [comment]
Thanks I missed that bit. Worked a treat.

http://[YOURIP]:[YOURPORT]/delete_duplicate_libraries
