### ISSUE TITLE
"Enable HTTP Proxy" no longer respected

### ISSUE THREAD

**Issue by cnf** [Tautulli/Tautulli#747]
**Version:**
1.4.5
**Branch:**
Git Branch:     master
**Commit hash:**
Git Commit Hash:    ffa208e73f7b67ce29788c625e33d4348de0b30c
**Operating system:**
Linux
**Python version:**
Python Version:     2.7.9 (default, Dec 16 2014, 13:36:23) [GCC 4.8.3]
**What you did?**
update plexpy
**What happened?**
with plexpy behind a reverse proxy, it redirects to the configured port, which does not work.
**What you expected?**
To not hardcode ports, so it just redirects to the path on the reverse proxy port.
it seems the "Enable HTTP Proxy" is no longer respected.
**How can we reproduce your issue?**
put plexpy behind a reverse proxy, try to log in

**What are your (relevant) settings?**
v Enable HTTP Proxy
Respect the X-Forwarded-Proto header. Used for reverse proxies with SSL.
**Link to logs:**

**Comment by JonnyWong16** [comment]
My reverse proxy is working fine. "Enable HTTP Proxy" is checked. There is no port redirection in PlexPy.

**Comment by cnf** [comment]
and yet whenever I try to access for example "check for updates", I end up on https://mydomain:8181/plexpy/home...

This has been working fine for ages, and the last time I updated a few days ago, it broke.

**Comment by cnf** [comment]
it looks like https://github.com/drzoidberg33/plexpy/commit/9ecabc3fafb9a0f4aec785ae5cdd332e433fef32 broke it for me? I am trying to debug and see what `plexpy.HTTP_ROOT` is set to

**Comment by cnf** [comment]
So it isn't https://github.com/drzoidberg33/plexpy/commit/9ecabc3fafb9a0f4aec785ae5cdd332e433fef32

What I am seeing is that when I hit /plexpy/checkGithub (as an example), I get back an HTTP Header Location with content `https://<mydomain>:8181/plexpy/home`

I have not figured out where this comes from.

Edit: FYI, I have tried this without the proxy, and I see the same Header.

**Comment by cnf** [comment]
Actually, it does look like https://github.com/drzoidberg33/plexpy/commit/9ecabc3fafb9a0f4aec785ae5cdd332e433fef32 is the culprit. I think it is cherrypy that does the redirect with a 303 to the full url, and it doesn't know about the proxy settings.

**Comment by JonnyWong16** [comment]
`plexpy.HTTP_ROOT` is just the base url you set in the settings, I assume `plexpy` in your case. There is no port info.
https://github.com/drzoidberg33/plexpy/blob/master/plexpy/webstart.py#L82

What does your reverse proxy setup/config look like?

**Comment by cnf** [comment]
plexpy does the exact same thing for me with or without the reverse proxy, on every browser I have tried. (ie, safari on osx, firefox on windows, and chrome on windows).

I get a 303 with a Location header set to `https://<mydomain>:8181/plexpy/home`

If I connect directly, of course this works, but through the reverse proxy I just get directed to something that doesn't work.

```
$  http --session=logged-in http://192.168.13.10:8181/plexpy/checkGithub 
HTTP/1.1 303 See Other
Content-Encoding: gzip
Content-Length: 104
Content-Type: text/html;charset=utf-8
Date: Sat, 11 Jun 2016 22:51:46 GMT
Location: http://192.168.13.10:8181/plexpy/home
Server: CherryPy/5.1.0
Set-Cookie: session_id=4ee829269d4af72b9cb235aa96a4af2e7f2ab114; expires=Mon, 11 Jul 2016 22:51:46 GMT; Path=/
Vary: Accept-Encoding

This resource can be found at <a href="http://192.168.13.10:8181/plexpy/home">http://192.168.13.10:8181/plexpy/home</a>.
```

```
$  http --session=logged-in https://example.com/plexpy/checkGithub 
HTTP/1.1 303 See Other
Content-Encoding: gzip
Content-Length: 111
Content-Type: text/html;charset=utf-8
Date: Sat, 11 Jun 2016 22:54:51 GMT
Location: https://example.com:8181/plexpy/home
Server: Caddy
Server: CherryPy/5.1.0
Set-Cookie: session_id=f83d7e37bbe2e8fe8f0f5b7000088a2e205307a2; expires=Mon, 11 Jul 2016 22:54:51 GMT; Path=/
Vary: Accept-Encoding
Vary: Accept-Encoding

This resource can be found at <a href="https://example.com:8181/plexpy/home">https://example.com:8181/plexpy/home</a>.
```

**Comment by JonnyWong16** [comment]
Accessing locally: HTTP 303 redirect.

```
Request URL: http://localhost:8181/plexpydev/checkGithub
Request Method: GET
Status Code: 303 See Other
Remote Address: 127.0.0.1:8181

Response Headers:
HTTP/1.1 303 See Other
Content-Length: 101
Content-Encoding: gzip
Vary: Accept-Encoding
Server: CherryPy/5.1.0
Location: http://localhost:8181/plexpydev/home
Date: Sat, 11 Jun 2016 23:39:43 GMT
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=e56435cabef5ea15fc84d1853d6fe49853ab787f; expires=Mon, 11 Jul 2016 23:39:43 GMT; Path=/
```

Through my reverse proxy: HTTP 302 redirect (note no port in location header).

```
Request URL: https://mydomain.com/plexpydev/checkGithub
Request Method: GET
Status Code: 302 Found
Remote Address: ***.***.***.***:443

Response Headers:
HTTP/1.1 302 Found
Content-Length: 115
Connection: keep-alive
Content-Encoding: gzip
Vary: Accept-Encoding
Server: nginx/1.8.1
Location: https://mydomain.com/plexpydev/home
Date: Sat, 11 Jun 2016 23:41:55 GMT
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=e335002b6fafb0d2cf4a89c8f5943c5f9cb71133; expires=Mon, 11 Jul 2016 23:41:54 GMT; Path=/
```

---

I'm pretty sure it has something to do with the way your reverse proxy is setup. I'm not sure how Caddy works.

**Comment by jessiebryan** [comment]
@cnf Have you tried using nginx parameter proxy_redirect ?

Below is an example to use it:

location /plexpy  {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://192.168.13.10:8181;
      proxy_read_timeout  90;
      proxy_redirect http://192.168.13.10:8181 https://example.com/plexpy ;
       
 }

**Comment by cnf** [comment]
I have tried it with nginx, and it does exactly the same thing.

Without @jessiebryan ugly hack to REWRITE the Location header, it redirects me to the wrong place.

This worked fine up to a few weeks ago, and after an update stopped working. I have even reinstalled plexpy at one point.

**Comment by cnf** [comment]
So with @JonnyWong16 on gitter, I did a `git checkout v1.4.4`, and it started working again. I am now on `master` and it is working...

Neither of us understand what happened :) Maybe a cache somewhere that stuck around?

Anyway, it works, and no cause was found, so I am closing it.

**Comment by rjorgenson** [comment]
Did anyone ever figure out what the cause of this was? I am running into the same issue both on v1.4.4 and on master. I wasn't running it through a proxy previously so I can't say wether it worked before or not, but now with the Enable HHTP Proxy checked i am constantly redirected to the configured bind port(on logout and a couple times on login as well as the previously mention update check). Without it enabled I am redirected to http without the port. Here is my reverse config in nginx.

> server {
>   listen       443 ssl;
>   server_name  plexpy.domain.com;
> 
>   # Load configuration file for the reverse proxy server block.
>   include /etc/nginx/conf.d/reverse.conf;
> 
>   location / { proxy_pass http://localhost:8181; }
> }

and the contents of reverse.conf

> ssl_certificate "/path/to/cert.pem";
> ssl_certificate_key "/path/to/key.pem";
> ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
> ssl_prefer_server_ciphers on;
> ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
> ssl_session_cache shared:SSL:10m;
> proxy_set_header Host $host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header X-Forwarded-Proto $scheme;

The proxy_redirect suggested by @jessiebryan did work, but I don't think it should need that workaround. Any help would be appreciated, thanks!

**Comment by JonnyWong16** [comment]
Make sure you have all the headers in the FAQ. And try doing a reset.

**Comment by rjorgenson** [comment]
@JonnyWong16 thanks! I was missing a couple that are required by plexpy. Wish that would have come in google before this bug =]
