### ISSUE TITLE
Can't save settings via web interface

### ISSUE THREAD

**Issue by aelberling** [Tautulli/Tautulli#748]
Any time i try to change any settings, no matter the tab, i am met with a red bar "Please verify your settings". I cant for the life of me figure out what i've messed up. Its also persistent after restart of both the system and plexpy.  No errors show up in the plexpy logs, so i'm not really sure where the issue is.

Version: 1.4.5
Branch: Master
Commit hash: ffa208e73f7b67ce29788c625e33d4348de0b30c
Operating system: OSX 10.10.5
Python version: 2.7.10

**Comment by JonnyWong16** [comment]
One of your settings is invalid. Go through all the tabs, General, Homepage, Web Interface, etc. There should be an error message beside the setting that is causing the problem.

**Comment by aelberling** [comment]
Thanks, i guess i missed that the log location was incorrect because of the ~ i had in there. everything works great now.
