### ISSUE TITLE
[bug?] Refresh Icons everywhere

### ISSUE THREAD

**Issue by Jonn3y** [Tautulli/Tautulli#750]
Hey there,

I updated plexpy today to 1.4.6 and now there are a lot of refresh icons?! 
<img width="355" alt="bildschirmfoto 2016-06-12 um 13 32 24" src="https://cloud.githubusercontent.com/assets/11927089/15990902/7a489470-30a2-11e6-836f-6cfdba25cd3f.png">
(Series-Details)

<img width="367" alt="bildschirmfoto 2016-06-12 um 13 31 39" src="https://cloud.githubusercontent.com/assets/11927089/15990903/7a48d840-30a2-11e6-8071-c9f5d672a9a7.png">
(Mainpage)

Doesn't look like there is anything happened when I'm clicking on it. 
And as you can see in:
.. Picture 1 - there is one in the left upper corner?! 
.. Picture 2 - the refresh icon is not fitting into the box ?! 

**Version:** 1.4.6

**Branch:** master

**Commit hash:** d9474cdcc5e72ff311569a234e3abe7dec06d9a2

**Operating system:** Linux Debian 8.4 jessie

**Python version:** 2.7.9

**What you did?** updated plexpy to 1.4.6

**What happened?** 

**What you expected?** -

**How can we reproduce your issue?** -

**What are your (relevant) settings?** standard-settings

**Link to logs:** [plexpy.log (DropBox)](https://www.dropbox.com/s/on9903mhxql1zmt/plexpy.log?dl=1)

**Comment by Hellowlol** [comment]
Refresh your cache

**Comment by Jonn3y** [comment]
Ups, perfect. Thank you. 👍
