### ISSUE TITLE
[Feature Request] Discord Notifications.

### ISSUE THREAD

**Issue by kcstllo** [Tautulli/Tautulli#751]
Possible?

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#feature-requests

**Comment by kcstllo** [comment]
I couldn't find another thread regarding Discord.
Just to confirm, should I have used FeatHub to suggest a feature?

**Comment by JonnyWong16** [comment]
Yes, the first line says

> Feature requests are handled on FeatHub.
