### ISSUE TITLE
There was an error communicating with your Plex Server.  --  I'm at a loss. 

### ISSUE THREAD

**Issue by rfrye** [Tautulli/Tautulli#752]
Im not too sure how to read these logs to find my issue.
I have uninstalled both plex and plexpy, and a few other things but still haven't been able to get my plexpy to connect. It use to connect just fine for the past two years.

http://pastebin.com/tVYxQz3H

**Comment by JonnyWong16** [comment]
Read through the posts on this page: http://forums.plex.tv/discussion/comment/1194492/#Comment_1194492

**Comment by rfrye** [comment]
Got it fixed after much trial and error. I can't say what fixed it, but I went through the instructions from the other thread. Thank you.
