### ISSUE TITLE
{server_uptime} not reporting correctly

### ISSUE THREAD

**Issue by ronwbrown** [Tautulli/Tautulli#753]
**Version:**
1.4.6
**Branch:**
Master
**Commit hash:**
d9474cdcc5e72ff311569a234e3abe7dec06d9a2
**Operating system:**
Server 2008
**Python version:**
latest
**What you did?**
Set notifications to post to facebook, including the {server_uptime} tag.
**What happened?**
messages posted shows hours of uptime, but only up to 24 hours, then resets to 0 again.
**What you expected?**
I expected to see "Days" or at least hours uptime above 24.
**How can we reproduce your issue?**
create a notification using the {server_uptime} tag.
if the server has been up for 25 hours, it will report 1 hour.

**What are your (relevant) settings?**
NA
**Link to logs:**
NA

**Comment by nucshuco** [comment]
Same issue here on FreeNas 9.10.1

**Comment by deed02392** [comment]
Same issue here on CentOS.

**Comment by JonnyWong16** [comment]
`{server_uptime}` has been removed in v2 because there is no accurate way to get this info.
