### ISSUE TITLE
Add mattermost notifications agent

### ISSUE THREAD

**Issue by epatpol** [Tautulli/Tautulli#754]
We are a big team using plex but we've recently switched from Slack to Mattermost. The good thing is that slack webhooks are compatible with Slack, so I think it can be easy to add this integration into plexpy (see http://docs.mattermost.com/developer/webhooks-incoming.html)

Thank you!

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#feature-requests

If it really is the same as Slack, then you should be able to change this one line: https://github.com/drzoidberg33/plexpy/blob/master/plexpy/notifiers.py#L1929
to the mattermost url and used the Slack notification agent.
