### ISSUE TITLE
Telegram notifications include posters even after disabling

### ISSUE THREAD

**Issue by didyouexpectthat** [Tautulli/Tautulli#755]
**Version:**
1.4.6
**Branch:**
master
**Commit hash:**
d9474cdcc5e72ff311569a234e3abe7dec06d9a2
**Operating system:**
Linux
**Python version:**
2.7.9
**What you did?**
I have Telegram notification agent set.
I asked Plexpy to start doing Posters.
After awhile, decided I didn't want posters anymore.
Unchecked posters.
**What happened?**
Plexpy decides to send posters for shows it already uploaded posters to Imgur for even though I've disabled Enabling posters in notifications.
**What you expected?**
Plexpy should never send posters if posters is disabled.
**How can we reproduce your issue?**

Install Plexpy
Configure with your Plex server
Setup Telegram notifications
Tell Plexpy you want Posters in notifications
Include Imgur Client ID
Save
Get tired of seeing posters
Uncheck "Enable Posters in Notifications"
Continue to randomly see posters in notifications
**What are your (relevant) settings?**
Unchecked "Enable Posters in Notifications"
(If checked, Imgur Client ID remains from when it was set)
**Link to logs:**

I will come back and post logs. I'm filing this issue from work.

Here's at time it showed it...
![image](https://cloud.githubusercontent.com/assets/1329077/16137368/6dfe8ccc-33e7-11e6-9590-fc8e49248993.png)

And here's a time it didn't display anything...
![image](https://cloud.githubusercontent.com/assets/1329077/16137380/8766362e-33e7-11e6-9bc6-157a3593b420.png)

**Comment by JonnyWong16** [comment]
Was it right after you changed the setting? Or quite some time after? Did it stop sending posters, then one randomly showed up?

**Comment by didyouexpectthat** [comment]
I turned on the setting awhile ago, but then turned it off after a few weeks since Telegram was saving every poster to my phone. Since turning it off, I did notice that it stopped but then later on that day I noticed that it was still resending posters. I thought maybe it was some weird setting so I turned it on and then immediately off again, and restarted.  It's not just one randomly, it'll do a slew of them and then several without.  It happens to both PlexPy servers I run.  

Here's another example from my other server. 
![image](https://cloud.githubusercontent.com/assets/1329077/16156375/dd8a6396-3468-11e6-918c-f622c3a16acc.png)

If I had to guess, I would say that it is showing me posters for shows that I already started getting posters for when I had the setting on.

**Comment by JonnyWong16** [comment]
> If I had to guess, I would say that it is showing me posters for shows that I already started getting posters for when I had the setting on.

Can you confirm this?

Also, logs please.

**Comment by didyouexpectthat** [comment]
Sure, I will try to confirm that ~~-- last night, my roommate hooked up a heater to my rack and it blew the circuit :P since then, I can't get my containers to resolve DNS properly, so I'm troubleshooting that still (plexpy lets me login but won't go to the settings screen, and tells me There was an error communicating with your Plex Server.)~~ 

Here's some excerpts from my logs. I show where it was consistently providing posters, then another time where it provided no posters but sent a slew of notifications. 

https://gist.github.com/didyouexpectthat/445bd5cf5f34349d151c556d47d142a7

I know that I disabled posters in the UI, but when I checked config.ini for posters, I see that it is set to 1. 

> root@plex-tv-mon:/opt/plexpy/logs# cat ../config.ini  | grep -i post
> notify_upload_posters = 0
> twitter_incl_poster = 1
> telegram_incl_poster = 1
> facebook_incl_poster = 1
> slack_incl_poster = 1
> ![image](https://cloud.githubusercontent.com/assets/1329077/16157338/f52108f8-346c-11e6-992d-32e740b202e7.png)

**Comment by JonnyWong16** [comment]
I think that's the problem there. The setting didn't get saved. Is the checkbox unchecked in the UI?

**Comment by didyouexpectthat** [comment]
> Can you confirm this?

I added this show "Ghost Writer" last night to my server, just tried playing an episode and PlexPy doesn't send a poster notification, just a notification.

```
2016-06-17 09:27:49 - DEBUG   :: Thread-19 : PlexPy Monitor :: Session 2 has started.
2016-06-17 09:28:36 - INFO    :: Thread-28 : PlexPy Notifiers :: Telegram notification sent.
2016-06-17 09:31:49 - DEBUG   :: Thread-19 : PlexPy Monitor :: Session 2 has stopped.
```

But when I play Stargate, something I've had for awhile, it will show me the poster. Doesn't seem to matter the episode that I'm playing, appears to send a poster regardless.

```
2016-06-17 09:31:49 - DEBUG   :: Thread-19 : PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 128668
2016-06-17 09:32:19 - DEBUG   :: Thread-19 : PlexPy Monitor :: Removing sessionKey 2 ratingKey 128668 from session queue
2016-06-17 09:32:19 - DEBUG   :: Thread-19 : PlexPy Monitor :: Session 3 has started.
2016-06-17 09:32:36 - INFO    :: Thread-29 : PlexPy Notifiers :: Telegram notification sent.
2016-06-17 09:33:08 - INFO    :: Thread-30 : PlexPy Notifiers :: Telegram poster sent.
2016-06-17 09:33:09 - INFO    :: Thread-30 : PlexPy Notifiers :: Telegram notification sent.
```

![image](https://cloud.githubusercontent.com/assets/1329077/16157796/fc2805b4-346e-11e6-88f6-216efd723cc3.png)

I stopped Stargate and played another show I've had available for awhile.
2016-06-17 09:38:49 - DEBUG   :: Thread-20 : PlexPy Monitor :: Session 3 has stopped.
2016-06-17 09:38:49 - DEBUG   :: Thread-20 : PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 63148
2016-06-17 09:39:19 - DEBUG   :: Thread-20 : PlexPy Monitor :: Removing sessionKey 3 ratingKey 63148 from session queue
2016-06-17 09:39:38 - INFO    :: Thread-31 : PlexPy Notifiers :: Telegram poster sent.
2016-06-17 09:39:39 - INFO    :: Thread-31 : PlexPy Notifiers :: Telegram notification sent.

2016-06-17 09:40:41 - DEBUG   :: Thread-19 : PlexPy Monitor :: Session 4 has started.
2016-06-17 09:41:30 - INFO    :: Thread-32 : PlexPy Notifiers :: Telegram poster sent.
2016-06-17 09:41:30 - INFO    :: Thread-32 : PlexPy Notifiers :: Telegram notification sent.

And it indeed sent the poster along with it.

I don't have any new other new stuff at the moment so I will have to continue to monitor.

**Comment by JonnyWong16** [comment]
Is "Include Poster Image" checked or unchecked in the Telegram settings? That is the setting that controls posters for Telegram. The "Enable Posters in Notifications" controls Imgur uploads. (I should probably rename it to be more clear).

**Comment by didyouexpectthat** [comment]
> I think that's the problem there. The setting didn't get saved. Is the checkbox unchecked in the UI?

Yes, the checkbox in the UI is unchecked. 
I pulled the config, then I went to the UI, checked the box, saved, pulled config again, unchecked, saved, pulled config. This is the output.

```
root@plex-tv-mon:/opt/plexpy# cat config.ini | grep -i post
notify_upload_posters = 0
twitter_incl_poster = 1
telegram_incl_poster = 1
facebook_incl_poster = 1
slack_incl_poster = 1
root@plex-tv-mon:/opt/plexpy# cat config.ini | grep -i post
notify_upload_posters = 1
twitter_incl_poster = 1
telegram_incl_poster = 1
facebook_incl_poster = 1
slack_incl_poster = 1
root@plex-tv-mon:/opt/plexpy# cat config.ini | grep -i post
notify_upload_posters = 0
twitter_incl_poster = 1
telegram_incl_poster = 1
facebook_incl_poster = 1
slack_incl_poster = 1
```

**Comment by didyouexpectthat** [comment]
> Is "Include Poster Image" checked or unchecked in the Telegram settings?

It's checked.  I assumed that "Enable Posters in Notifications" being disabled would have globally disabled posters.

**Comment by JonnyWong16** [comment]
> I assumed that "Enable Posters in Notifications" being disabled would have globally disabled posters.

Yeah, I should probably change that too...

**Comment by didyouexpectthat** [comment]
Are you going to change the "Enable Posters in Notifications" to globally disable posters, or just rename the setting to something like "Enable Poster upload to Imgur for new shows" (I'm considering using other notification agents in the future) -- For now, I'll just disable posters in Telegram.  Thanks for the help.

**Comment by JonnyWong16** [comment]
I'm going to make it global, since the other 4 check boxes above it are global.

**Comment by didyouexpectthat** [comment]
Thanks again.
