### ISSUE TITLE
Mako Runtime Error on update in shutdown.html

### ISSUE THREAD

**Issue by Arcanemagus** [Tautulli/Tautulli#756]
**Version:**
1.4.6

**Branch:**
dev

**Commit hash:**
8706e72f6abca60517a66da0e30d2f4c9ae9be2b

**Operating system:**
FreeBSD 10.3-STABLE (FreeNAS jail)

**Python version:**
2.7.11 (default, Apr 26 2016, 04:11:54) [GCC 4.2.1 20070831 patched [FreeBSD]]

**What you did?**
Triggered an update to 1120aa3841a482f25b11f40c932ecf54fe983f02.

**What happened?**
I got a Mako Runtime Error screen of the following:

``` text
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 22: ordinal not in range(128)

</div> </div> <div class="modal-footer"> <div style="float: right;"><span class="text-muted" id="rquote">${quote}</span></div> </div> </div> </div> </div> </div>
/usr/local/share/plexpy/data/interfaces/default/shutdown.html, line 30:
<div style="float: right;"><span class="text-muted" id="rquote">${quote}</span></div>
/usr/local/share/plexpy/data/interfaces/default/base.html, line 310:
${next.body()}
/usr/local/share/plexpy/lib/mako/runtime.py, line 860:
callable_(context, *args, **kwargs)
/usr/local/share/plexpy/lib/mako/runtime.py, line 835:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/usr/local/share/plexpy/lib/mako/runtime.py, line 803:
**_kwargs_for_callable(callable_, data))
/usr/local/share/plexpy/lib/mako/template.py, line 443:
return runtime._render(self, self.callable_, args, data)
/usr/local/share/plexpy/plexpy/webserve.py, line 70:
_session=_session, **kwargs)
```

Note that the update _did_ succeed in the background, it just didn't show the regular screen. 

**What you expected?**
No error message, PlexPy showing the restarting/updating screen

**How can we reproduce your issue?**
Unsure... restarting the server again after the update doesn't reproduce the error. Feel free to close this and write it off as a one time fluke if nobody else reports the same.

**Comment by JonnyWong16** [comment]
I think it was the apostrophe in this arnold quote:

```
Remember when I said I’d kill you last... I lied!
```

**Comment by Arcanemagus** [comment]
Looks like this should be fixed by https://github.com/drzoidberg33/plexpy/commit/b12bde4f79bd4e6784b1a18f6c0852ceb9fe6e29, thanks @JonnyWong16!
