### ISSUE TITLE
Forcing connections to non-local IPs even when publicAddressMatches is true

### ISSUE THREAD

**Issue by maran** [Tautulli/Tautulli#757]
**Branch:** master

**Commit hash:** d9474cdcc5e72ff311569a234e3abe7dec06d9a2

**Operating system:** Ubuntu 14.04

**Python version:** 2.7

**What you did?**
I am hosting various virtualised Plex environments. Because of this I always need to use the the local="0" connection entry from the /api/resources end-point. However when I run Plexpy from of the servers where I also host a virtualized server it grabs the internal 172._._.\* ip. However on each Plex restart this IP changes.

**What you expected?**
I would love to have a config setting that forces Plexpy to always discover the remote IPs instead of the local ones. Or perhaps a checkbox during the wizard to enforce remote IPs.

I am open to discuss writing a PR if this is something that would be mergeable.

**Comment by JonnyWong16** [comment]
Check the box that says "Remote server".

**Comment by maran** [comment]
Is there no way to force this? Otherwise I would have to tell all my users to do this somehow and users don't like reading.
