### ISSUE TITLE
User missing under Users tab:

### ISSUE THREAD

**Issue by mikeyfind** [Tautulli/Tautulli#758]
**Version:**
1.4.6
**Branch:**
Master
**Commit hash:**
d9474cdcc5e72ff311569a234e3abe7dec06d9a2
**Operating system:**
Linux 3.13.0-85-generic
**Python version:**
2.7.6

I have a missing user under the user tab... 

However the data is there if I visit the full page URL: /user?user_id=6713182
How can I get this users data to appear on the main User page like the rest?

Kind regards,
MikeyFind

**Comment by JonnyWong16** [comment]
Please read the FAQ for deleted users.

**Comment by mikeyfind** [comment]
Amazing, it worked... Thank you kindly... :)

You can re-enable the user by going to http://localhost:8181/undelete_user?username=<the_username>
