### ISSUE TITLE
Duplicate Libraries:

### ISSUE THREAD

**Issue by mikeyfind** [Tautulli/Tautulli#759]
**Version:**
1.4.6
**Branch:**
Master
**Commit hash:**
d9474cdcc5e72ff311569a234e3abe7dec06d9a2
**Operating system:**
Linux 3.13.0-85-generic
**Python version:**
2.7.6

Under Libraries, I have duplicates...  

If I delete one, it shall delete both; any idea how I can fix this?

Screenshot (red boxes are incorrect data count) want these removed if possible?
URL:  http://pasteboard.co/1Qz6HIqJ.png

Kind regards,
MikeyFind

**Comment by b2un0** [comment]
did you recreate your sections on Plex self? if yes, delete the old section in PlexPy (Edit Mode Button on the top right)

**Comment by mikeyfind** [comment]
When I press delete within PlexPy on the duplicated library, it also deletes the one I wish to keep... :(

**Comment by JonnyWong16** [comment]
Please read the FAQ.

**Comment by mikeyfind** [comment]
Thank you kindly... :)

delete_duplicate_libraries
