### ISSUE TITLE
Could not get the latest version from GitHub. Are you running a local development version?

### ISSUE THREAD

**Issue by 5stringdeath** [Tautulli/Tautulli#76]
The update check leaves this in my log.  If I do a git pull myself, it updates fine.  Not sure what the issue is ...

**Comment by drzoidberg33** [comment]
Please can you post your full log.

**Comment by 5stringdeath** [comment]
There's only one line really:

```
2015-08-16 09:22:10 WARNING Could not get the latest version from GitHub. Are you running a local development version?
```

**Comment by drzoidberg33** [comment]
I need the full log.

**Comment by gcoan** [comment]
I don't know what to tell you ... that's all there is in the log after I hit the "check for updates" button

**Comment by drzoidberg33** [comment]
Are you by any chance starting PlexPy with the --quiet flag set? If so, shutdown PlexPy and start it up without the --quiet flag. Then post the entire contents of the log.

**Comment by 5stringdeath** [comment]
```
16-Aug-2015 09:24:59 - INFO    :: CP Server Thread-7 : Retrieving latest version information from GitHub
16-Aug-2015 09:24:59 - DEBUG   :: CP Server Thread-7 : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
16-Aug-2015 09:25:00 - ERROR   :: CP Server Thread-7 : Request raise HTTP error with status code 403 (local client error).
16-Aug-2015 09:25:00 - DEBUG   :: CP Server Thread-7 : Server responded with message: {"message":"API rate limit exceeded for xx.xxx.xxx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docum...
16-Aug-2015 09:25:00 - WARNING :: CP Server Thread-7 : Could not get the latest version from GitHub. Are you running a local development version?
```

Redacted my IP .  I was not using the -quiet flag.  I guess its because of that "authenticated requests" line but I don't know the document its trying to refer to.

**Comment by drzoidberg33** [comment]
It's the Github API that limits the number of calls an IP can make per hour. You really should never hit this limit - I'm constantly starting and restarting my app while developing and have never reached the limit (which is 60 per hour).

Wait an hour and see if the issue resolves itself, it could also be that Github was experiencing issues.

**Comment by 5stringdeath** [comment]
So I noticed that Headphones was throwing the same error.  Must have been github acting up as they are both checking in fine now.  Cheers.
