### ISSUE TITLE
ETA not displaying in Chrome, but does in Firefox

### ISSUE THREAD

**Issue by depraved22** [Tautulli/Tautulli#761]
Version Information:

Version 1.4.6 Changelog
PlexPy Configuration
Git Branch:     master
Git Commit Hash:    d9474cdcc5e72ff311569a234e3abe7dec06d9a2
Configuration File:     /opt/plexpy/config.ini
Database File:  /opt/plexpy/plexpy.db
Log File:   /opt/plexpy/logs/plexpy.log
Backup Directory:   /opt/plexpy/backups
Cache Directory:    /opt/plexpy/cache
Arguments:  ['--quiet', '--daemon', '--nolaunch', '--config', '/opt/plexpy/config.ini', '--datadir', '/opt/plexpy']
Platform:   Linux 4.2.0-27-generic
Python Version:     2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413]
Plex Forums:    https://forums.plex.tv/discussion/169591/plexpy-another-plex-monitoring-program
Source:     https://github.com/drzoidberg33/plexpy
Wiki:   https://github.com/drzoidberg33/plexpy/wiki
Issues:     https://github.com/drzoidberg33/plexpy/issues
Feature Requests:   http://feathub.com/drzoidberg33/plexpy
Gitter Chat:    https://gitter.im/drzoidberg33/plexpy

When I check the ETA seems to show up in Firefox but not in Chrome. Both are the latest versions:

[Removed your screenshots because it showed an IP address]

Not sure what the difference is causing that between the 2 browsers. This is on MacOS as well.

**Comment by JonnyWong16** [comment]
It looks like the css didn't load properly. Try a forced refresh (Ctrl+F5) or clearing your browser cache in Chrome.

**Comment by depraved22** [comment]
I swear I did both of those prior to posting, but that did work. I'll just say thanks for the quick response and move on :)
