### ISSUE TITLE
Updated Plexpy last night not keep getting this error.

### ISSUE THREAD

**Issue by morpheus2n2** [Tautulli/Tautulli#763]
I updated to the latest build of Plex and Plexpy last night and not I keep getting this error

ERROR   :: Thread-13 : PlexPy Database :: Fatal Error executing INSERT INTO session_history_metadata (id, rating_key, parent_rating_key, grandparent_rating_key, title, parent_title, grandparent_title, full_title, media_index, parent_media_index, section_id, thumb, parent_thumb, grandparent_thumb, art, media_type, year, originally_available_at, added_at, updated_at, last_viewed_at, content_rating, summary, tagline, rating, duration, guid, directors, writers, actors, genres, studio, labels) VALUES (last_insert_rowid(), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) :: database disk image is malformed

**Comment by JonnyWong16** [comment]
Please use the search function. This has been solved in #556 and #673.

**Comment by morpheus2n2** [comment]
I did but nothing came up, but have just realised I didn't click "Issues" on the left hand side so it was showing me just code results which obviously would be empty lol. Sorry :)
