### ISSUE TITLE
DNS Lookup Local IP address 

### ISSUE THREAD

**Issue by traxinv** [Tautulli/Tautulli#766]
This is more of a feature request. 

But it would be great for local IP's to try and reverse lookup the IP address to return the DNS name to display instead of "Local"

Since devices are generally on DHCP they dont always have the same address and when you are watching on your browser for instance there is no device name. SO the DNS name would be great to have.

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#feature-requests
