### ISSUE TITLE
You're running an unknown version of PlexPy.

### ISSUE THREAD

**Issue by bakman2** [Tautulli/Tautulli#770]
This message shows up when Plexpy can't seem to find git - even if it exists. (running on a synology here).

The check for git could be a made a little more robust. 
ie. the config.ini by default states: `git_path=""` 

versioncheck.py:

```
if plexpy.CONFIG.GIT_PATH:
        git_locations = ['"' + plexpy.CONFIG.GIT_PATH + '"']
    else:
        git_locations = ['git']
```

instead of "assuming" that there is a valid path,  a `which git` could be fired which could either: update the config file or or use the output as path directly (without the need for a config setting).

**Comment by JonnyWong16** [comment]
Doesn't work in Windows though?

**Comment by Hellowlol** [comment]
Nope

**Comment by bakman2** [comment]
For windows there is `where.exe c:\ git /r`

**Comment by JonnyWong16** [comment]
Submit a pull request.
