### ISSUE TITLE
Feature Request: Widget for status and actual users

### ISSUE THREAD

**Issue by daurpam** [Tautulli/Tautulli#771]
I would like to know how many people would be interested, in the creation of Widget for external web site that shows status, stats or other relevant information about or Plex Media Server.

The idea is to show in a personal web (blog, website, etc) a widget with information about the plex media server in realtime, The users could know if a server is online, or with high CPU usage or too many concurrent streams. It would be great if it can be customized with the info show, colours, themes, sizes, etc.

I add a suggestion of new feature in FeatHub: http://feathub.com/drzoidberg33/plexpy/+120

Thanks in advance.

**Comment by Hellowlol** [comment]
I dont understand this request, what stopping you from just using the api from php or what ever to make this your self?

Anyway it would be pretty cool to use mako to handle this ^^

Feks in webserve.py

```
@cherrypy.expose()
def widget(self, template, **kwargs):
    return serve_template(template)

```

some template folder in userdata. widget.mako

```
import plepypy
    ......
```

**Comment by JonnyWong16** [comment]
I also suggest using the API and creating a widget for yourself.

**Comment by daurpam** [comment]
Thanks for your answers,

but I don't have knowledge for develop something like that. :S 

Perhaps, someone else can get the idea and make it real.

**Comment by Hellowlol** [comment]
It would be a nice opportunity to learn something new.
