### ISSUE TITLE
PlexPy fails to load without (external) internet connection

### ISSUE THREAD

**Issue by fdbgbgsf** [Tautulli/Tautulli#775]
Issue is the following line:
`<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet" type="text/css">`

webpage just keeps trying to connect to that resource in Safari, no timeout.

In the meantime it also failed to record any watched items.
Logs are just a reapeat of the 2 following lines:

```
2016-07-10 16:23:14 WARNING PlexPy Pmsconnect :: Unable to parse XML for get_current_activity: 'NoneType' object has no attribute 'getElementsByTagName'.
2016-07-10 16:23:14 WARNING Failed to access uri endpoint /status/sessions with error [Errno -2] Name or service not known
```
- PlexPy 1.4.6
- running in docker by linuxserver.io
- Linux 3.10.77
- Python 2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]

**Comment by JonnyWong16** [comment]
Firstly, on the very first page of the setup wizard it says:

> PlexPy requires a permanent internet connection to ensure a reliable experience.

Secondly, the first issue seems like a Safari problem. It worked fine in Chrome when I disabled by ethernet to test it.

Thirdly, do you have "Remote Server" or "Use SSL" checked in the settings? If either is checked then PlexPy needs to connect to plex.direct over the internet.

**Comment by fdbgbgsf** [comment]
To be honest, I can't be expected to remember every setup page I've ever seen. Also this seems unnecessary, why aren't the fonts stored locally? Seems rather wasteful to download these on every page refresh.
I generally dislike it when things need an internet connection for no apparent reason.

I also tried it in Firefox and had the same issue.

PlexPy and Plex are running on the same machine, and SSL is handled through reverse proxy (also didn't load when bypassing it). So both options are set to no.

**Comment by JonnyWong16** [comment]
~~It looks like deleting that line completely has no effect on the font.~~ Mine was just cached.

```
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet" type="text/css">
```

**Comment by JonnyWong16** [comment]
Font is now hosted locally on v1.4.7.
