### ISSUE TITLE
Failure when requesting FB authorization

### ISSUE THREAD

**Issue by zprewitt** [Tautulli/Tautulli#776]
Just set up PP on a new media server. Requesting FB authorization redirects to blank page saying Unable to Verify Key. 

All the correct info (ID, secret, host) has been used, and my IP has been whitelisted. Redirect URI was added as well.

From the log:
PlexPy Notifiers :: Error requesting Facebook access token: This IP can't make requests for that application.

**Version:**

**Branch:**

**Commit hash:** d9474cdcc5e72ff311569a234e3abe7dec06d9a2

**Operating system:** Windows 10

**Python version:** 2.7.11

**What you did?** Clicked Request Authorization

**What happened?** Redirect to blank screen. Message: Unable to Verify Key

**What you expected?** Facebook authorization confirmation page loads.

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
Already saw your post on reddit: https://www.reddit.com/r/PleX/comments/4sfeen/plexpy_facebook_notifications_unable_to_verify_key/
