### ISSUE TITLE
Fatal Error executing SELECT 

### ISSUE THREAD

**Issue by gjosang** [Tautulli/Tautulli#777]
Hi, 

I'am getting the error under, the log is full of them. 
Worked fine util a couple of hours ago.. 
Can't access Libaries, users or histrory. 
Running on ubuntu 16.04 lts
Branch: master (v1.4.6)
Hash: d9474cdcc5e72ff311569a234e3abe7dec06d9a2

PlexPy Database :: Fatal Error executing SELECT \* FROM (SELECT users.user_id, (CASE WHEN users.friendly_name IS NULL OR TRIM(users.friendly_name) = "" THEN users.username ELSE users.friendly_name END) AS friendly_name, users.thumb AS user_thumb, users.custom_avatar_url AS custom_thumb, COUNT(session_history.id) AS plays, SUM(CASE WHEN session_history.stopped > 0 THEN (session_history.stopped - session_history.started) ELSE 0 END) - SUM(CASE WHEN session_history.paused_counter IS NULL THEN 0 ELSE session_history.paused_counter END) AS duration, MAX(session_history.started) AS last_seen, MAX(session_history.id) AS id, session_history_metadata.full_title AS last_played, session_history.ip_address, session_history.platform, session_history.player, session_history.rating_key, session_history_metadata.media_type, session_history_metadata.thumb, session_history_metadata.parent_thumb, session_history_metadata.grandparent_thumb, session_history_metadata.parent_title, session_history_metadata.year, session_history_metadata.media_index, session_history_metadata.parent_media_index, session_history_media_info.transcode_decision, users.do_notify as do_notify, users.keep_history as keep_history, users.allow_guest as allow_guest FROM users LEFT OUTER JOIN session_history ON session_history.user_id = users.user_id LEFT OUTER JOIN session_history_metadata ON session_history.id = session_history_metadata.id LEFT OUTER JOIN session_history_media_info ON session_history.id = session_history_media_info.id WHERE users.deleted_user = ? GROUP BY users.user_id) ORDER BY friendly_name COLLATE NOCASE :: database disk image is malformed

**Comment by JonnyWong16** [comment]
Search please: https://github.com/drzoidberg33/plexpy/search?q=database+disk+image+is+malformed&type=Issues&utf8=%E2%9C%93
