### ISSUE TITLE
Slack Quit Working DEV

### ISSUE THREAD

**Issue by LexusSpeed03** [Tautulli/Tautulli#778]
**Version:**
DEV

**Commit hash:**
a26d6ec6bb54f916fc1b7d003fc30a771b2976db

**Operating system:**
Windows 10 x64

**Python version:**
2.7

**What you did?**
Added new movies and shows

**What happened?**
Added and shows in plex and wont send slack notifications

**What you expected?**

**How can we reproduce your issue?**
Add new movies or shows no slack notifications are happening. In the logs are not even showing it tried to send?

https://gist.github.com/DereckR/b6d80ba897a8c25090560046da34e81a.js

**Comment by LexusSpeed03** [comment]
Now all of sudden it starts working? But its not the TV shows folder it is sending notifications on.

**Comment by LexusSpeed03** [comment]
Link corrected:

https://gist.github.com/DereckR/b6d80ba897a8c25090560046da34e81a

Performed update yesterday to newest DEV. Slack stopped working but emails continued. I had restarted entire PC to test to make sure no issues. Added 3-4 more shows and nothing. They showed in PlexPy under recently added but no notifications. I continued to receive all email notifications no issues. 

Checked again this morning and now its working again?

Nothing in settings or anything has changed simply clicked update.

**Comment by JonnyWong16** [comment]
It's a bug. I didn't account for recently added notification in the new user notifications.

**Comment by LexusSpeed03** [comment]
And was working had to restart the PlexPy and it stopped again don't know what jump started it last time.

**Comment by JonnyWong16** [comment]
It's a bug. Restarting won't fix it.

**Comment by JonnyWong16** [comment]
Fixed on dev. 20edcbf7fab6e0da7e210e520a74ed239bc62701
