### ISSUE TITLE
[REQUEST] Output history to log file

### ISSUE THREAD

**Issue by tb2007** [Tautulli/Tautulli#78]
Request to output history page to log file automatically, much like how PlexWatch has the "plexwatch.log" file.

I use the Splunk Universal Forwarder agent to monitor and forward the log file to my Splunk server for central logging.

Thanks and great app by the way!!

**Comment by drzoidberg33** [comment]
Should it just be output with the exact same rows as the table?

Should it be in CSV or tab separated or some other format?

**Comment by tb2007** [comment]
I'm using Linux (Ubuntu), so I'd envision something as to a simple text file output to the already present /log directory that houses the plexpy.log.  The information that's on the history page would just be concatenated when a new entry is added.

Called something like 'history.log' and just look like:
"2015-08-16 User Device  IP Better Call Saul - Mijo 19:55   0 mins  20:00   5 mins"
"2015-08-15 User Device IP Top Gear - Typhoon Jet Fighter 18:20 2 mins  19:22   60 mins"

**Comment by drzoidberg33** [comment]
Ah okay, so you want it to be updated when new history is added. That is actually quite simple, just will take time to implement.

I'll look into this when I get a moment.
