### ISSUE TITLE
Libraries refresh interval ignored

### ISSUE THREAD

**Issue by valesi** [Tautulli/Tautulli#782]
master v1.4.7

I noticed a long time ago that the library refresh interval never did anything, so I finally went looking around. Looks like there was a minor oversight when the library interval was created many moons ago.

Relevant section: https://github.com/drzoidberg33/plexpy/blob/26ac539bc46a72fc79d184da0a4e24b3858e5db1/plexpy/__init__.py#L334-L347

The `pmsconnect.refresh_libraries` schedule uses `hours` that is still set to `CONFIG.REFRESH_USERS_INTERVAL`, when (as far as I can determine) it should be `CONFIG.REFRESH_LIBRARIES_INTERVAL`.

Is there a reason we ignore the libraries refresh interval?

**Comment by JonnyWong16** [comment]
Ah, thanks for finding this bug.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.8.
