### ISSUE TITLE
Error sending Facebook post: Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive.

### ISSUE THREAD

**Issue by peva3** [Tautulli/Tautulli#783]
I'm getting this error from the notifications log, not all the time, but no notifications are being posted successfully. I'm running the most recent dev commits on Ubuntu 16.04 x64. This is a private group and other than updating plexpy over the past few weeks, no changes have been made elsewhere, and the notifications have been working properly for almost a year.

"Error sending Facebook post: Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive."

**Comment by JonnyWong16** [comment]
https://forums.plex.tv/discussion/comment/1182016/#Comment_1182016
