### ISSUE TITLE
Home Video libraries not correct type

### ISSUE THREAD

**Issue by mattcartlidge** [Tautulli/Tautulli#784]
Hi

Just a simple issue which is easily recreated on the latest version.

My "Home Video" libraries show incorrectly as "Movies" type libraries. Is this a bug or do I need to set them manually?

Thanks,

**Comment by Arcanemagus** [comment]
What type are they set to in Plex? PlexPy should follow that setting.

**Comment by mattcartlidge** [comment]
Ah, so it is a bug. 

Well, when I set up a Plex library I get the following standard options which are "Movies", "TV Shows", "Music", "Photos" and "Home Videos". 

I use the "Home Videos" for stuff like personal videos and gym videos for exercise routines. When a library is set to "Home Videos" in Plex, it shows as "Movie" library type in PlexPy. I've also noticed that my libraries which are set to "Music" in Plex are showing as "Artist" library type in PlexPy.

**Comment by JonnyWong16** [comment]
That's just the Plex terminology from the API. There are only four types: movie, show, artist, and photo.

**Comment by mattcartlidge** [comment]
So there's no way to seperate home videos in plexpy?

**Comment by JonnyWong16** [comment]
Not easily.
