### ISSUE TITLE
Concurrent Stream Notifications by IP Address option not working

### ISSUE THREAD

**Issue by Drewster727** [Tautulli/Tautulli#785]
I've noticed that with the latest version (1.4.7) that I cannot get the "User Concurrent Streams Notifications by IP Address" option under Settings > Notifications to work.

I'll navigate to Settings > Notifications. Check the box. Save. It prompts for a restart. I let it restart. Go back into settings, the option is unchecked.

![screen shot 2016-07-15 at 5 26 24 pm](https://cloud.githubusercontent.com/assets/4528753/16890129/7e293a44-4ab1-11e6-877e-9626eb6d55f0.png)

I see no log errors/warnings for this.

However, I just checked my config.ini and saw this:

```
notify_concurrent_by_ip = 1
```

So, I assume the 1 value means the checkbox should be showing checked? **However, after testing this, it still  sends the notification if there are concurrent streams for the same user under the same IP address.**

Git Branch: master
Git Commit Hash:    26ac539bc46a72fc79d184da0a4e24b3858e5db1
Configuration File: /opt/plexpy/config.ini
Database File:  /opt/plexpy/plexpy.db
Log File:   /opt/plexpy/logs/plexpy.log
Backup Directory:   /opt/plexpy/backups
Cache Directory:    /opt/plexpy/cache
Platform:   Linux 4.2.0-16-generic
Python Version: 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]

**Comment by JonnyWong16** [comment]
It shouldn't ask for a restart after checking that box. Some other setting is being changed. Something on the Web Interface, Access Control, or Monitoring tabs is being changed.

Try completely shutting down PlexPy and starting it back up.

**Comment by Arcanemagus** [comment]
@Drewster727 if you use a password manager, for some reason it will _always_ think that a "restart required" setting has been changed.

**Comment by JonnyWong16** [comment]
@Arcanemagus Because it will auto fill the username and password on the Access Control tab.

**Comment by Pakorro** [comment]
@Drewster727: Same problem here... no write error, but checkbox is unmarked... I am running Plexpy in my QNAP TS-470 Pro and I am calling plexpy from Chrome in Windows 10.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.8.
