### ISSUE TITLE
UnknownTimeZoneError when attempting to start after update.

### ISSUE THREAD

**Issue by tidusjar** [Tautulli/Tautulli#787]
**Version:**
Latest

**Operating system:**
Windows 10

**Python version:**
2.7

**What you did?**
Updated

**What happened?**
Getting the following:
![image](https://cloud.githubusercontent.com/assets/6642220/16897420/dcd3d840-4ba8-11e6-8961-6c21fe3fa3a5.png)

Any idea how I can fix it?

**Comment by JonnyWong16** [comment]
I would have expected a more complete issue report from the PlexRequests.net dev. :stuck_out_tongue: 

But honestly, I have no idea what happened. Only thing I can think of is try to change your system timezone to see if it changes anything.

**Comment by tidusjar** [comment]
Haha sorry. Wasn't sure what to include! There was nothing related in the logs! 

I'll give it a go and report back.

**Comment by tidusjar** [comment]
Didn't seem to work changing the timezone. Also followed [this](http://stackoverflow.com/questions/21717411/timezone-information-missing-in-pytz/21717676#21717676) and still no luck. Looks like I'll have to downgrade

**Comment by Hellowlol** [comment]
wtf. How did you install python? Just asking since python isnt a internal or external command in your ss

**Comment by tidusjar** [comment]
Using the Python windows installer...

**Comment by JonnyWong16** [comment]
PlexPy includes the [pytz library](https://github.com/drzoidberg33/plexpy/tree/master/lib/pytz). Maybe I just need to [update it](https://pypi.python.org/pypi/pytz?#downloads).

**Comment by tidusjar** [comment]
Creating a fresh install and copying over the db seems to have sorted things out.
