### ISSUE TITLE
Concurrent Stream Notifications sending false positives

### ISSUE THREAD

**Issue by Drewster727** [Tautulli/Tautulli#788]
Hi,

On PlexPy 1.4.8 - I have the concurrent stream notifications turned on. I also have the setting to notify only when the IP address is different, and to only notify when there are 2 or more concurrent streams. It has been working fine on 1.4.8 until this morning, I'm getting a notification from plexpy saying one of my users is streaming concurrently. However, the email only indicates that there is one stream, which seems to be the case (I don't see the 2nd stream in the main plexpy page). The user seems to have their stream paused if that helps.

E-mail Notification:
![image](https://cloud.githubusercontent.com/assets/4528753/16918953/65b8df5a-4ccd-11e6-8710-6a917d35c923.png)

Setting is set to notify when the 2 stream threshold is hit:
![image](https://cloud.githubusercontent.com/assets/4528753/16918836/e34cecbe-4ccc-11e6-9901-bc9b8de7c16e.png)

Notification Logs from this morning:
![image](https://cloud.githubusercontent.com/assets/4528753/16919219/6a7d4606-4cce-11e6-9f07-404e4782774f.png)

Only seeing the one stream (paused) in the front-end for the users:
![image](https://cloud.githubusercontent.com/assets/4528753/16920135/15eb9562-4cd2-11e6-9608-66a387bf1c36.png)

Thanks for adding this feature btw. It's incredibly useful.

VERSION 1.4.8 
Git Branch: master
Git Commit Hash:    2150961d2742afc24d5982fe3d0ddee141f89a26
Configuration File: /opt/plexpy/config.ini
Database File:  /opt/plexpy/plexpy.db
Log File:   /opt/plexpy/logs/plexpy.log
Backup Directory:   /opt/plexpy/backups
Cache Directory:    /opt/plexpy/cache
GeoLite2 Database:  /opt/plexpy/GeoLite2-City.mmdb | Reinstall / Update | Uninstall
Arguments:  ['--quiet', '--daemon', '--nolaunch', '--config', '/opt/plexpy/config.ini', '--datadir', '/opt/plexpy']
Platform:   Linux 4.2.0-16-generic
Python Version: 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]

**Comment by JonnyWong16** [comment]
Try flushing the current sessions in the database to make sure nothing got stuck:

http://localhost:8181/delete_temp_sessions

**Comment by Drewster727** [comment]
I think that solved it. Is this something I'll need to do often?

**Comment by JonnyWong16** [comment]
No, you should need to use it often or at all, but sometimes sessions get stuck in the database for whatever reason.

**Comment by Drewster727** [comment]
Thanks @JonnyWong16 -- is this delete temp sessions call something that can be added to the settings screen? Kind of a "nice to have" feature when people are troubleshooting issues. Thanks!

**Comment by JonnyWong16** [comment]
It can be added, but it's not something that should be used often. You also lose some of the stats with any currently active sessions when you use it.
