### ISSUE TITLE
notification agent telegram doesn't work

### ISSUE THREAD

**Issue by Magikarplvl4** [Tautulli/Tautulli#789]
**Version:**
1.4.8
**Branch:**
Master
**Commit hash:**
    2150961d2742afc24d5982fe3d0ddee141f89a26
**Operating system:**
Windows 10 pro
**Python version:**
2.7.11
**What you did?**
Turn on the telegram and test a test message. Test messages is ok.
**What happened?**
notification agent telegram doesn't work,  its look like plexpy doesn't send messages at all.
I set every option on but nothing happend.
**What you expected?**
Receive a message in telegram. Only the test message i received
**How can we reproduce your issue?**
Turn on the telegram agent and set every option on.

**What are your (relevant) settings?**

**Link to logs:**

https://gist.github.com/whitecollar17/29ee3e5a242581176c9b09a665b4119a

**Comment by JonnyWong16** [comment]
Have you read the [FAQ](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#notifications-q1)?

**Comment by Magikarplvl4** [comment]
half
didn't read "also, make sure the "Global Notification Toggles" are enabled under Settings > Notifications. " :$
