### ISSUE TITLE
GeoIP DB Install Fails/Nothing Happens

### ISSUE THREAD

**Issue by x-radeon** [Tautulli/Tautulli#790]
**Version:**
1.4.8

**Branch:**
master

**Commit hash:**
2150961d2742afc24d5982fe3d0ddee141f89a26

**Operating system:**
Ubuntu 16.04

**Python version:**
2.7.12

**What you did?**
Clicked "Click here to install the GeoLite2 database."

**What happened?**
Nothing
I believe the correlated log entry is:
Uncaught ReferenceError: confirmAjaxCall is not defined. (settings:8)

**What you expected?**
Not sure, maybe a box to put in a path to the DB? I don't think there's a wiki on this yet since it's new so I don't now what should happen when I click the link.

**How can we reproduce your issue?**
Go to settings -> Click "Click here to install the GeoLite2 database."

**What are your (relevant) settings?**
GeoIP DB

**Link to logs:**
[Gist](https://gist.github.com/x-radeon/f09a5d05aad9c95d13aaf4a7fe1a44e7)

**Comment by JonnyWong16** [comment]
Search please...

#780 #786

https://forums.plex.tv/discussion/comment/1217998/#Comment_1217998
https://forums.plex.tv/discussion/comment/1218147/#Comment_1218147

**Comment by x-radeon** [comment]
That fixed it. To clarify for anyone reading this, just hard refresh your browser (Ctrl + F5) and it will popup a dialog asking to install the db.
