### ISSUE TITLE
[Feature Request] Show stream info in concurrent stream notification

### ISSUE THREAD

**Issue by Drewster727** [Tautulli/Tautulli#791]
I really love the concurrent stream notifications. I would really like to get some more information about each of the streams in the notification:
- IP address
- Item being watched
- Is the stream playing or paused

Often times, my users will leave their stream paused at their home (or where-ever) and stream from their phone somewhere else. Which would indicate two different streams. This is one example of many where I can just ignore the notification.

A notification example of this would be something like:

> xyzuser has 2 concurrent streams with different IP addresses:
> 
> 172.168.1.1 - Playing - The Revenant (2015)
> 172.168.1.2 - Paused - Interstellar (2014)

and... if you wanted to take this one step further... Grab the location data for each stream/ip as well!

VERSION 1.4.8  
Git Branch: master
Git Commit Hash:    2150961d2742afc24d5982fe3d0ddee141f89a26
Configuration File: /opt/plexpy/config.ini
Database File:  /opt/plexpy/plexpy.db
Log File:   /opt/plexpy/logs/plexpy.log
Backup Directory:   /opt/plexpy/backups
Cache Directory:    /opt/plexpy/cache
GeoLite2 Database:  /opt/plexpy/GeoLite2-City.mmdb | Reinstall / Update | Uninstall
Arguments:  ['--quiet', '--daemon', '--nolaunch', '--config', '/opt/plexpy/config.ini', '--datadir', '/opt/plexpy']
Platform:   Linux 4.2.0-16-generic
Python Version: 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy#feature-requests

**Comment by Drewster727** [comment]
added to Feathub. Thanks and my apologies for totally missing that.
