### ISSUE TITLE
Can't send webhook notification to mattermost

### ISSUE THREAD

**Issue by gravufo** [Tautulli/Tautulli#792]
**Version:**

1.4.8

**Operating system:**

Ubuntu, docker. Mattermost is also in a docker.

**What you did?**

Tried to send a test notification from plexpy to mattermost using slack integration
Simply added the webhook url generated by mattermost, didn't touch anything else in that notification agent.

**What happened?**

PlexPy Notifiers :: Slack notification failed.

**What you expected?**

A working notification. I'm pretty sure the incoming webhook works on mattermost since we also have a custom bot pushing notifications through a webhook and that works.

**How can we reproduce your issue?**

Run mattermost docker.
Run plexpy docker.
Create incoming webhook url.
Add the url to your plexpy Slack notification agent.
Save.
Test the notification.

**Link to logs:**

Logs are sadly very basic and only display the following:
Sending test Slack notification.
PlexPy Notifiers :: Slack notification failed.

Thanks!

**Comment by JonnyWong16** [comment]
I never actually tested Mattermost. I just assumed it would be identical to Slack. Maybe I should go test it... 

Edit: Realized I can't because I don't run any of the supported platforms.

**Comment by JonnyWong16** [comment]
Does changing this line: https://github.com/drzoidberg33/plexpy/blob/master/plexpy/notifiers.py#L2028
to the following fix it? 

```
headers={'Content-type': "application/json"},
```

**Comment by gravufo** [comment]
It worked!
Does this mean you're gonna have to create a new agent, or you can simply replace that and it works for both slack and mattermost?

Thanks!

**Comment by JonnyWong16** [comment]
It should work for both. Technically it should be that for Slack in the first place. I don't know why Slack was even working...

**Comment by epatpol** [comment]
Can someone test to see if it still works with Slack? If so I think it should be permanently changed to "application/json". Maybe even change the agent name to something like Mattermost/Slack just so people can know that it's working (assuming it works correctly with this change).

Thanks @JonnyWong16 !

**Comment by JonnyWong16** [comment]
You can test it yourself... 

I already made the change to the dev branch.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.9.
