### ISSUE TITLE
Reverse Proxy redirecting to logout

### ISSUE THREAD

**Issue by bjay1404** [Tautulli/Tautulli#794]
**Version:** 1.4.8

**Branch:** Master

**Commit hash:** 2150961d2742afc24d5982fe3d0ddee141f89a26

**Operating system:** Ubuntu 16.04

**Python version:** 2.7.6

**What you did?** Added an Nginx reverse proxy with ssl. With my internal apache reverse proxy i can hit plexpy fine. Nginx is working with my other applications like sickrage and couchpotato
https://xyz/plexpy redirects to
https://xyz.ddns.net:8007/plexpy/auth/logout

**What happened?** 

**What you expected?**
I had it working okay yesterday, but I can't fix it... 
**How can we reproduce your issue?** 

I have no idea how you can reproduce the steps... 
**What are your (relevant) settings?**
the proxy settings is at 1 
**Link to logs:**
NGINX Config
http://pastebin.com/tEyCj7BY

**Comment by bjay1404** [comment]
My internal apache server works fine with http://host/plexpy !

**Comment by JonnyWong16** [comment]
It redirects to logout if your logged in session expires.

**Comment by bjay1404** [comment]
So how do I fix that?

**Comment by JonnyWong16** [comment]
Not sure if this will fix it or not, but try adding this header to your `/plexpy` location block.

```
proxy_set_header        X-Forwarded-Host     $server_name;
```

**Comment by bjay1404** [comment]
That did the trick! Thank you!

**Comment by Parkie** [comment]
Sorry to bring this back, but I keep searching the web and coming back to this and don't fully understand the answer. I have a reverse proxy setup for Plexpy and I cannot seem to get it to work. It will forward to a non working URL. How do I fix this with Apache2 as my reverse proxy

**Comment by lkgarrison** [comment]
In case anyone else is using CaddyServer for reverse proxy functionality instead of nginx, you need to use {host} in place of $server_name in the FAQ (https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#q-why-does-plexpy-not-work-with-my-reverse-proxy-setup). My proxy block for plexpy looks like this:

```
		transparent
		header_upstream X-Forwarded-Host {host}
		header_upstream X-Forwarded-Ssl on
```

**Comment by safusu** [comment]
For those using Apache, I've found that the normal

```
ProxyPass / http://localhost:8181/
ProxyPassReverse / http://localhost:8181/
```

Options in the apache conf file work fine. 

Even when clearing cache, https://plexpy.domain.com doesn't resolve, but going to https://plexpy.domain.com/auth/login resolves fine. Once you're logged in there, _then_ https://plexpy.domain.com/home resolves. 

Not sure what this means, but something to try out.

**Comment by the1poet** [comment]
> In case anyone else is using CaddyServer for reverse proxy functionality instead of nginx, you need to use {host} in place of $server_name in the FAQ (https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#q-why-does-plexpy-not-work-with-my-reverse-proxy-setup). My proxy block for plexpy looks like this:
> 
> 		transparent
> 		header_upstream X-Forwarded-Host {host}
> 		header_upstream X-Forwarded-Ssl on

Thank you @lkgarrison, that worked for me.
