### ISSUE TITLE
Problems with special characters in devicename (ÆØÅ)

### ISSUE THREAD

**Issue by alberthaff** [Tautulli/Tautulli#798]
**Version:**
1.4.8

**Branch:**
master

**Commit hash:**
2150961d2742afc24d5982fe3d0ddee141f89a26

**Operating system:**
Ubuntu (Docker) on Linux-UnRaid v. 6.1.8

**Python version:**
2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]

**What you did?**
I tried to view the dashboard.

**What happened?**
I get the error-message: "There was an error communicating with your Plex Server."

This error only occurs when a device with danish letters (ÆØÅ) in the name are playing media from PMS. I would imagine that it is an issue with formatting (eg. UTF-8 / ISO-xxxx or vice versa).

The dashboard works just fine once i stop playback on the device, that has a name containing the letter "Æ". I have experienced a similar problem while playing media from an iPhone with a name containing the letter "Ø".

**How can we reproduce your issue?**
Start playback from a device, which name contains one or more of following characters: Æ, Ø or Å.

The dashboard will no longer show which media are currently being streamed. PlexPy will neither log the playback.

**What are your (relevant) settings?**
PlexPy connects just fine to PMS. The problems only occur when there is an active playback from a device with a name containg Æ, Ø or Å.

**Link to logs:**
[log.txt](https://github.com/drzoidberg33/plexpy/files/384950/log.txt)

**Comment by JonnyWong16** [comment]
What platform is your device? What is your Plex server version?

This should have been fixed in PMS 0.9.17.0. See here: https://github.com/drzoidberg33/plexpy/issues/212#issuecomment-222491519

**Comment by alberthaff** [comment]
@JonnyWong16 Thanks for the quick reply.

Both devices are iPhones.

I am running PMS 0.9.16.6. I see there is an update for Plex. However, the Docker container by limetech has not yet been updated. I will just have to wait for them to patch it. :-)
