### ISSUE TITLE
[Bug] After update, does not interpret watched time correctly in one instance

### ISSUE THREAD

**Issue by pironic** [Tautulli/Tautulli#799]
**Version:**
2150961d2742afc24d5982fe3d0ddee141f89a26

**Branch:**
master

**Commit hash:**
https://github.com/drzoidberg33/plexpy/compare/d9474cdcc5e72ff311569a234e3abe7dec06d9a2...2150961d2742afc24d5982fe3d0ddee141f89a26

**Operating system:**
Ubuntu

**Python version:**
2.7

**What you did?**
upgrade

**What happened?**
![image](https://cloud.githubusercontent.com/assets/541154/17168918/2c9eed46-53a2-11e6-8f86-36d2c2952cff.png)
previous to the upgrade the most watched tv show was something entirely different and by a different user. this put 'Lynn' above the person in first and shows her up there now.

**What you expected?**
not 11k minutes of watch time on a 22min episode... math somewhere wrong?

**How can we reproduce your issue?**
Upgraded via in-plexpy upgrade button from-to: https://github.com/drzoidberg33/plexpy/compare/d9474cdcc5e72ff311569a234e3abe7dec06d9a2...2150961d2742afc24d5982fe3d0ddee141f89a26

**What are your (relevant) settings?**

**Link to logs:**
https://gist.github.com/pironic/3583a1120cc9a4d89a0e1a6aec977b52 (last 50 lines)
ignore the connection closed as i was updating the plex media server at that time too.

**Comment by JonnyWong16** [comment]
This can happen if you shutdown PlexPy while a stream is running. You can try to manually fix it in the database or just delete that entry.

**Comment by pironic** [comment]
Unfortunate.

Leave the issue open? Close it as known issue?
