### ISSUE TITLE
IP Lookup not working

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#80]
IP lookup is not working inside plexpy

![Image of IP Lookup](http://i.imgur.com/Tij7fjD.png)

But checking the outstide plexpy using a browser at http://ip-api.com/ works, there is something wrong inside plexpy.

**Comment by drzoidberg33** [comment]
Are you running PlexPy with SSL?

If so, most browsers will block mixed HTTP/HTTPS content by default, it should show you an alert somewhere where you can allow it.

Here is the doc for this for Chrome: https://support.google.com/chrome/answer/1342714?hl=en

ip-api.com doesn't allow SSL on it's free service (it does on the paid service). Most other providers I tried were very unreliable or didn't provide as much detail as ip-api.

**Comment by elRadix** [comment]
No i'm not running SSL with plexpy

**Comment by drzoidberg33** [comment]
Check your browser console output to see if you can see any errors there.

I've set the timeout time to be quite short on this query, so if the call takes longer than 5 seconds it will automatically time out. The server busy message could happen when the ip-api service is busy and requests are taking long.

**Comment by elRadix** [comment]
ok, thank you for pointing me in the right direction. it seems the adblocker in chrome was the main culprit here. solved now!

**Comment by drzoidberg33** [comment]
Ok thanks. Closing.

**Comment by alexanderthegreat96** [comment]
same problem for me and no , i don t use SSL. its just plain http

**Comment by drzoidberg33** [comment]
> same problem for me and no , i don t use SSL. its just plain http

The service was down temporarily, it's back now.
