### ISSUE TITLE
[Bug] Slack notification agent sending default posters.

### ISSUE THREAD

**Issue by Rsslone** [Tautulli/Tautulli#800]
Plexpy is sending default covers to slack instead of the cover of the title.

**Version:**
1.4.8
**Branch:**
Master
**Commit hash:**
2150961d2742afc24d5982fe3d0ddee141f89a26
**Operating system:**
Windows 8.1
**Python version:**
2.7.11
**What happened?**
Plexpy sends blank covers to slack.
http://puu.sh/qgg8r/59a356c318.jpg
**What you expected?**
For cover of title to be displayed.
**What are your (relevant) settings?**
http://puu.sh/qgoXK/d0383af1f7.png
**Link to logs:**
http://puu.sh/qgp2i/3737f42b49.png

**Comment by JonnyWong16** [comment]
Settings > Notifications > Enable Posters in Notifications

**Comment by Rsslone** [comment]
I didn't notice that, sorry.
