### ISSUE TITLE
Time graphs gridline labels

### ISSUE THREAD

**Issue by fdbgbgsf** [Tautulli/Tautulli#803]
All the time based graphs have their gridlines labels as a multiple of seconds, which are not that user friendly.

For example: 
6h56m ~ 25000 seconds
13h53m ~ 50000 seconds
20h50m ~ 75000 seconds

It would look much nicer if these where more time range based, hour based for anything between 1h-24h above that day based.
- Git Branch:   master
- Git Commit Hash:  2150961d2742afc24d5982fe3d0ddee141f89a26
- Arguments:    ['--datadir', '/config', '--nolaunch']
- Platform: Linux 3.10.77
- Python Version:   2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]

**Comment by JonnyWong16** [comment]
Good point. [Done](https://github.com/drzoidberg33/plexpy/commit/54af92251c61932c9db3e09638df83b5c3ff7170).

**Comment by fdbgbgsf** [comment]
Sweet! So quick! Tried it on dev, waiting for it to be merged with master. Thanks.
