### ISSUE TITLE
Select Columns Does Not Persist/Save Between Log-ins

### ISSUE THREAD

**Issue by mannibis** [Tautulli/Tautulli#804]
I'm not sure if this is a browser/cookie issue, but when I select which columns to show in History view (or any view), my preferences are not saved between log-ins or even browser sessions. Every time I close out my PlexPy tab/window, it resets my column preferences. It would be nice if it would save my choices so I do not have to manually select the columns I want every time. Because of my window size/resolution, having all the columns active makes the History view look weird.

**Comment by JonnyWong16** [comment]
It's a problem with your browser. My selections are saved. Try clearing your browser cache.

**Comment by mannibis** [comment]
You're right. I run PlexPy within Muximux and it's definitely doing something funky with cookies or whatever is involved with saving stuff like Columns, because whenever I reload the iframe, my preferences are reset . I'm going to submit an issue on Muximux's hub. Thanks for the reply and apologies.
