### ISSUE TITLE
Spikes in graphs causing strange output

### ISSUE THREAD

**Issue by didyouexpectthat** [Tautulli/Tautulli#805]
**Version:**
1.4.8
**Branch:**
master
**Commit hash:**
2150961d2742afc24d5982fe3d0ddee141f89a26
**Operating system:**
Debian 8
**Python version:**
    2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]
**What you did?**
I am noticing that there is a huge spike on some days, equaling "4 days" worth of viewing time.
**What happened?**
![image](https://cloud.githubusercontent.com/assets/1329077/17608353/c3756b10-5fe0-11e6-97b2-de016e982b90.png)
There's a huge spike on one day, saying that 1 day, I had someone watching something for 4 days. 
I had some various other spikes that I was able to remove from the sql database, and it cleaned up the spike. seems to happen when a show rolls over to the next day. 
Maybe this is counting for time someone had something paused? 
![image](https://cloud.githubusercontent.com/assets/1329077/17608377/02d33968-5fe1-11e6-8666-0ff2732fdb15.png)

**What you expected?**
I don't expect plexpy to report people watching 4 days worth of content in one day. 

**How can we reproduce your issue?**

I don't know how to reproduce this. It could be time related?

sqlite> select \* from session_history where rating_key is 145567 limit 1;
id|reference_id|started|stopped|rating_key|user_id|user|ip_address|paused_counter|player|platform|machine_id|parent_rating_key|grandparent_rating_key|media_type|view_offset
5630|5630|1469918212|1469920080|145567|$USER_ID|$USERNAME|$IP|1|Roku 2 - 1RE3C1029946|Roku|Plex1RE3C1029946|8520|8508|episode|3339000

This is one of the ones that appears strangely in the time frame (from 15:00 to 10:00). 

**What are your (relevant) settings?**
I don't have anything I consider relevant.
**Link to logs:**
I don't have logs that far back, sorry. I can try to see if the spikes happen again. (I didn't see any other open issues on this, but I can guarantee nobody watched 4 days worth of content that day).

**Comment by JonnyWong16** [comment]
Is it possible that you had PlexPy shutdown while that stream was still playing? Then when you restarted PlexPy hours later, it saw that the stream ended and recorded the current time as the stop time for the stream.

**Comment by JonnyWong16** [comment]
No response.

**Comment by didyouexpectthat** [comment]
Sorry, I thought I responded to this one. It's likely that I restarted Plexpy. Sometimes Plexpy runs out of memory and gets killed but most times, it restarts again instantly. There might be a time or two where I have to restart the process manually, but very rarely. The end time that appears in the UI doesn't coincide with the next day's start times.

**Comment by Hellowlol** [comment]
Plexpy should never use that much memory. What is the memory usage and what hardware does it run on?

**Comment by didyouexpectthat** [comment]
I run 2 instances of Plexpy in two separate LXC containers. I've only designated the containers that I use for Plexpy to use 512M of RAM with 2 CPUs.  The hardware is a Dell R900 with 64 GB RAM and 4x E7330 CPUs (total 16 CPUs/cores). 
The most recent Plexpy OOM happened was when I moved 13 TB from one zfs subvolume to another zfs subvolume, which caused Plex (running on another LXC container) to do a lot of updating between two libraries. That instance of Plexpy monitored that Plex server. 

Plexpy doesn't run out of RAM constantly, just once in a while when I'm doing huge amounts of IO that triggers Plex to do lots of updating. I used to have 2 GB of RAM on the Plexpy servers but reduced it to 512M when I realized it didn't need that much.
![image](https://cloud.githubusercontent.com/assets/1329077/18616969/ecac8272-7d7a-11e6-8c9d-350a83172c66.png)

**Comment by Hellowlol** [comment]
Seems like you need it if there is a lot of io going on. Anyway I'll see if we can reduce the memory usage. I need to move some tbs anyway.

**Comment by JonnyWong16** [comment]
I have no idea why that spike occurred in your graph with logs or something. It was likely a one-time glitch, but if it is happening all the time, then comment again with logs.

If you really care about your statistics then you can manually change the entry in the database, or just delete that one entry. It looks like you are familiar with SQLite already.

**Comment by didyouexpectthat** [comment]
Thanks. I'll keep an eye on it and make sure to get logs. It was too long ago that the spikes occurred so I don't have logs to share from how far back the spikes occurred.
