### ISSUE TITLE
Can't see history page as of v1.4.9.

### ISSUE THREAD

**Issue by sbaydush** [Tautulli/Tautulli#806]
**Version:** 1.4.9

**Branch:** Release

**Commit hash:** 

**Operating system:** Ubuntu 14.04

**Python version:** 2.7

**What you did?** I updated to the latest release 1.4.9 from 1.4.8

**What happened?** The history table never loads and it has the following error in the log file.
ERROR   :: CP Server Thread-4 : WebUI :: /history : Uncaught TypeError: Cannot read property 'split' of null. (history_table.js:294)

**What you expected?** I expected it to show the history page

**How can we reproduce your issue?**

Update to 1.4.9 from 1.4.8 and try and view the history page

**What are your (relevant) settings?**

**Link to logs:** See attached

[plexpy.zip](https://github.com/drzoidberg33/plexpy/files/418080/plexpy.zip)

**Comment by JonnyWong16** [comment]
Have you refreshed the page? Crtl+F5?

**Comment by sbaydush** [comment]
Yep that fixed it :/ sorry about the waste of time. I will close this
