### ISSUE TITLE
No notifications for local user

### ISSUE THREAD

**Issue by ormanya** [Tautulli/Tautulli#807]
When playing Plex as "local" user (PlexBMC in Kodi), I do not receive notifications like I do for other users (i.e., when a new show is started playing).

Everything else for that session works as expected: session shows up in now playing by "local" user on PlexPy, I can see the session in history for the "local" user.

**Comment by JonnyWong16** [comment]
Are notifications disabled for "Local"? Users > Edit mode > Toggle Notifications.

**Comment by ormanya** [comment]
They are enabled: https://puu.sh/qCsas/0e2d578153.png

The user_id for local is 0. Could this be causing a problem?

**Comment by JonnyWong16** [comment]
Logs please. Use [pastebin](http://pastebin.com).

**Comment by ormanya** [comment]
Logs here: http://pastebin.com/bbDt1gJM

An example of a session does not result in a notification is at 2016-08-15 06:53:28.

Also, there is second user called "local" in the user list, but the link to the user is "/user?user_id=" with no user id, and the page that comes up is " Error retrieving user information. Please see the logs for more details." As you will see in my logs, the only error message is that user_id does not exist. This second "local" user with no id could be be an artefact from importing PlexWatch settings and logs? Note that history indicates this second "local" has not accessed the server for 6 months - around the time I switched from PlexWatch to PlexPy.

**Comment by ormanya** [comment]
I should add that nothing appears in the Notifications log when user "local" starts a show, but an entry does appear when any other user starts a show

**Comment by JonnyWong16** [comment]
There should only be one "Local" user with `user_id=0`. The two might be causing a conflict, but I don't see how.

I don't see any other notifications being sent. Is all of that activity in the logs from the "Local" user?

**Comment by ormanya** [comment]
Only one session was for a non-local user in the logs I posted above. I have posted logs that go back further: http://pastebin.com/pNt5tLzw

The following sessions are non-local user activity: 178, 179, 181, 182, 188

**Comment by JonnyWong16** [comment]
PM me your `plexpy.db` file on the [forums](https://forums.plex.tv/profile/JonnyWong16) and I'll take a look when I get home.

**Comment by ormanya** [comment]
Sent :)

**Comment by JonnyWong16** [comment]
Sorry for the late response. Can you try changing this line: https://github.com/drzoidberg33/plexpy/blob/master/plexpy/users.py#L282
to the following and test it.

```
        if user_id is None and not user and not email:
```

**Comment by ormanya** [comment]
That did the trick. I now get notifications when playing as local user. Nice work!

**Comment by JonnyWong16** [comment]
You will need to undo the change in order to update, or else you will get this: https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#q-when-i-try-to-update-plexpy-it-keeps-telling-me-please-commit-your-changes-or-stash-them-before-you-can-merge
