### ISSUE TITLE
External activity with a local account

### ISSUE THREAD

**Issue by JeanNetryValere** [Tautulli/Tautulli#808]
Hello,

External activity logging is working perfectly for my registered users (5 users) except for one. 
This user is running locally (My admin user) without any logging errors, but externally (from the internet) no trace of activities. 
Could confirm an existing issue similar to mine ?

Git Branch: master
Git Commit Hash:    2a701a6dfea6ef4abda0c6db5f23f59d2a251a35
Configuration File: \AppData\Local\PlexPy\config.ini
Database File:  \AppData\Local\PlexPy\plexpy.db
Log File:   \AppData\Local\PlexPy\logs\plexpy.log
Backup Directory:   \AppData\Local\PlexPy\backups
Cache Directory:    \AppData\Local\PlexPy\cache
GeoLite2 Database:  Click here to install the GeoLite2 database.
Arguments:  ['--nolaunch']
Platform:   Windows 8.1
Python Version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]

**Comment by JonnyWong16** [comment]
Logs please. Use [pastebin](http://pastebin.com).
