### ISSUE TITLE
History doesn't load after 1.4.10 update

### ISSUE THREAD

**Issue by brettaweston** [Tautulli/Tautulli#809]
**Version:**
1.4.10
**Branch:**
master
**Commit hash:**
2a701a6dfea6ef4abda0c6db5f23f59d2a251a35
**Operating system:**
OS X 10.11.6
**Python version:**
2.7.10
**What you did?**
Updated to 1.4.10. Authenticated. Clicked "History"
**What happened?**
Infinite "Fetching Rows"
**What you expected?**
History to be returned
**How can we reproduce your issue?**

Log in.
Click History.
**What are your (relevant) settings?**
N/A?
**Link to logs:**
https://gist.github.com/brettaweston/74c9b073a36d168c7fc74a30574f272a#file-gistfile1-txt

**Comment by JonnyWong16** [comment]
#806

**Comment by brettaweston** [comment]
Saw that. Have refreshed multiple times and it still doesn't load. Have tried safari and chrome. Also clear cache, cookies, etc.
