### ISSUE TITLE
Broken users page after updating

### ISSUE THREAD

**Issue by Magikarplvl4** [Tautulli/Tautulli#81]
Can't see my users page after updating to the last version. I get 2 errors:
![fout 1](https://cloud.githubusercontent.com/assets/2944704/9314209/c9aaf42a-4527-11e5-82fc-27b4ba095a46.png)

![fout2](https://cloud.githubusercontent.com/assets/2944704/9314211/cd2734ec-4527-11e5-9cd5-c307431edb7e.png)

After i get this 2 errors its look likte this: 
![fout3](https://cloud.githubusercontent.com/assets/2944704/9314213/cf355980-4527-11e5-90a5-e7f258d63b32.png)

Error logs says:

17-aug-2015 21:31:08 - ERROR   :: CP Server Thread-11 : Database error: near " ": syntax error
17-aug-2015 21:31:08 - WARNING :: CP Server Thread-11 : Unable to execute database query.

i run it on a windows 8.1 machine.

Can you help me?

**Comment by drzoidberg33** [comment]
Have you tried refreshing the page?

**Comment by Magikarplvl4** [comment]
lol, no :$. but after a ctrl + f5 it working again. Thanks!

**Comment by drzoidberg33** [comment]
Cool. Closing.
