### ISSUE TITLE
Error after update with "Current activity in history tables" checked

### ISSUE THREAD

**Issue by FeroMind** [Tautulli/Tautulli#810]
**Version:**
1.4.10
**Branch:**
Master
**Commit hash:**
2a701a6dfea6ef4abda0c6db5f23f59d2a251a35
**Operating system:**
Windows 8.1
**Python version:**
2.7.11
**What you did?**
Updated to newest commit, by default the new option "Current activity in history tables" was checked.
**What happened?**
When checking history page it would hang at "Fetching Rows" and console would give error (see logs). I went into settings and unchecked the "Current activity in history tables" option and after restart I was able to view history page properly again.

**Link to logs:**
In the pastebin link below, you can see the first error at line 53.
[pastebin](http://pastebin.com/vV8z2LRT)

**Comment by JonnyWong16** [comment]
#806

**Comment by FeroMind** [comment]
So what you're saying is, doing research before submitting an issue helps? :p Thanks, sorry for the trouble.
