### ISSUE TITLE
History unable to load after most recent update (Version 1.4.10)

### ISSUE THREAD

**Issue by ebaneham** [Tautulli/Tautulli#811]
Version: 1.4.10
Branch: Master
OS: Windows 10
Commit Hash: 2a701a6dfea6ef4abda0c6db5f23f59d2a251a35
Python Version: 2.7.10

When you click on the History menu at the top of the page, you are stuck with "Fetching rows" and no log data shows.

Error log screengrab below

![image](https://cloud.githubusercontent.com/assets/13102854/17695958/2d385e0c-63a3-11e6-829c-acf31087c8f0.png)

**Comment by JonnyWong16** [comment]
You didn't search. 

https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q2

#806, #809, #810.

http://forums.plex.tv/discussion/comment/1235634/#Comment_1235634
http://forums.plex.tv/discussion/comment/1235665/#Comment_1235665
