### ISSUE TITLE
Cant view history

### ISSUE THREAD

**Issue by morbidpete** [Tautulli/Tautulli#812]
Version: 1.4.10

Branch: Master

Commit hash:    2a701a6dfea6ef4abda0c6db5f23f59d2a251a35

Operating system: Unraid 6.2.0-rc3 Docker

Python version: 2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]

What you did? Tried to view history

What happened? Showed "Fetching rows" indefinitely (all other tabs including graphs operational)

What you expected? To see my watch history

How can we reproduce your issue?
Updated Py using "update" link on gui
waited the 120 seconds
Log into web gui using plex server owner credentials
click history on the nav bar

What are your (relevant) settings?

config in pastebin
http://pastebin.com/ZLXepmPk

Link to logs:
Py Log
http://pastebin.com/CMbWMnwc

**Comment by Arcanemagus** [comment]
https://github.com/drzoidberg33/plexpy/issues/811#issuecomment-240110132

**Comment by morbidpete** [comment]
My bad!
