### ISSUE TITLE
Searching through a users history no longer functions

### ISSUE THREAD

**Issue by mauirixxx** [Tautulli/Tautulli#813]
**Version:**
v1.4.10

**Branch:**
master

**Commit hash:**
2a701a6dfea6ef4abda0c6db5f23f59d2a251a35

**Operating system:**
CentOS 7 (Linux 3.10.0-229.20.1.el7.x86_64)

**Python version:**
v2.7.5 (default that comes with CentOS 7)

**What you did?**
Before the update (I was 27 commits behind it the notification stated) I would click on: "Users -> username -> History -> Search" and type in the name of the media that their history is already showing they've watched, and get result of just that media.

Now, say I have a user that watches Modern Family regularly, and it shows that in the history - when I type Modern Family in the search box I get 0 results.

**Link to logs:**
PlexPy.log (2016-08-16 log) http://pastebin.com/gKgfPBqh

**Comment by JonnyWong16** [comment]
Thanks for letting me know.

**Comment by vjbonan** [comment]
I would also agree with this,  I recently upgrade.   I noticed last night when I clicked history, it said fetching rows and never came back.  I restarted plexpy just now and its still saying fetching rows and seems to never be coming back as well.     

_UPDATE_  I came back 4 hours later after the restart, and it was still fetching rows *

I am on ubuntu 14.04  ... if you need my logs too I will try to get them.

Plexpy is at Version 1.4.10 
Git Branch:     master
Git Commit Hash:    2a701a6dfea6ef4abda0c6db5f23f59d2a251a35
