### ISSUE TITLE
PlexPy - PlexWatch Import Data Base Error

### ISSUE THREAD

**Issue by Pyhrra** [Tautulli/Tautulli#816]
Having an issue importing my plexWatch db. 
plexWatch version is: # Version: 0.3.4

Version: 1.4.10

Branch: master

Commit hash:    2a701a6dfea6ef4abda0c6db5f23f59d2a251a35

Operating system: CentOS-7.2.1511 64bit

Python version: 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

What you did? Tired to import from /opt/plexWatch/plexWatch.db from the web.

What happened? PlexPy Importer :: Invalid database specified

What you expected? the import to happen .

How can we reproduce your issue? I can provide link to db, just let me know.

What are your (relevant) settings?

Link to logs: http://pastebin.com/wLVXHLKw

**Comment by JonnyWong16** [comment]
1. Do this: https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#q-i-am-getting-a-databaseerror-file-is-encrypted-of-is-not-a-database.
2. Import is broken right now: #815.
