### ISSUE TITLE
History page won't load...Uncaught TypeError

### ISSUE THREAD

**Issue by mannibis** [Tautulli/Tautulli#817]
As of the latest update, when I try to view my history page I get this error:

`WebUI :: /history : Uncaught TypeError: Cannot read property 'split' of null. (history_table.js:294)`

Which results in "Fetching Rows" spinning forever. A restart didn't fix it.

Git Branch: master
Git Commit Hash:    2a701a6dfea6ef4abda0c6db5f23f59d2a251a35
Configuration File: /Applications/PlexPy/PlexPy/config.ini
Database File:  /Applications/PlexPy/PlexPy/plexpy.db
Log File:   /Applications/PlexPy/PlexPy/logs/plexpy.log
Backup Directory:   /Applications/PlexPy/PlexPy/backups
Cache Directory:    /Applications/PlexPy/PlexPy/cache
GeoLite2 Database:  /Applications/PlexPy/PlexPy/GeoLite2-City.mmdb | Reinstall / Update | Uninstall
Arguments:  ['--nolaunch']
Platform:   Darwin 13.4.0
Python Version: 2.7.12 (default, Jun 29 2016, 14:04:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

**Comment by JonnyWong16** [comment]
[I wonder how many more of these I'm going to get](http://i.imgur.com/08NCX29.png)...

https://github.com/drzoidberg33/plexpy/issues/811#issuecomment-240110132
