### ISSUE TITLE
HTTPS Failure

### ISSUE THREAD

**Issue by DocFusion** [Tautulli/Tautulli#819]
**Version:**
1.4.10
**Branch:**
Master
**Operating system:**
Ubuntu Server 16.04.1 64 bit
**Python version:**
2.7.12
**What you did?**
Enabled SSL
**What happened?**
[Screenshot](http://i.imgur.com/pTMym8v.png)
**What you expected?**
Https working correctly
**How can we reproduce your issue?**
-Apt-update/upgrade
-Install Plex Media Server
-Install python & python-openssl
-Enable https

PlexPy works fine without SSL including a username/pass, however https enabled breaks it. Other things such as nginx, webmin, plex, all work fine over https, so I'm genuinely confused.

**Comment by JonnyWong16** [comment]
Are you using a reverse proxy? Is the proxy handling the SSL? or PlexPy? Are you sending all the correct headers to PlexPy through your reverse proxy?

**Comment by DocFusion** [comment]
I am using a reverse proxy which is handling the SSL. I guess that's my issue then.

Edit: Solved. Thanks for maintaining the [FAQ](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#general-q10),
