### ISSUE TITLE
Logs spam "Unable to retrieve sync data for user"

### ISSUE THREAD

**Issue by Magikarplvl4** [Tautulli/Tautulli#82]
Hi,

My users don't use the plex sync option in plex. So its empty. 
But the plexpy spam evertime this  after a check:
2015-08-17 21:43:40 WARNING Unable to retrieve sync data for user.
2015-08-17 21:43:40 WARNING Error parsing XML for Plex sync lists.

it is possible to not have to log an error?

**Comment by Magikarplvl4** [comment]
?

**Comment by drzoidberg33** [comment]
You could run PlexPy in quiet mode.

When starting PlexPy add the --quiet flag in the command.
