### ISSUE TITLE
FreeBSD rc.d init script doesn't stop plexpy

### ISSUE THREAD

**Issue by fliiiix** [Tautulli/Tautulli#820]
**Operating system:**

FreeBSD

**What you did?**

`service plexpy stop`

**What happened?**
Nothing.

**What you expected?**

```
# service plexpy restart 
Stopping plexpy
Waiting for PIDS: 90720
```

**How can we reproduce your issue?**

`service plexpy stop`

**What are your (relevant) settings?**

So basically there was in the old script a wget command to shut it down over the web interface
https://github.com/drzoidberg33/plexpy/blob/master/init-scripts/init-alt.freebsd#L76

and now it's just waiting that the it magically shutdown 
https://github.com/drzoidberg33/plexpy/blob/master/init-scripts/init.freebsd#L62

Maybe we can use something similar to the one in the FreeBSD ports tree 
https://svnweb.freebsd.org/ports/head/multimedia/plexpy/files/plexpy.in?view=markup

**Comment by JonnyWong16** [comment]
Try the FreeNAS script. It should be similar. (You might need to change `python2` to `python`.

**Comment by JonnyWong16** [comment]
FreeBSD service script updated in v1.4.12.
