### ISSUE TITLE
Plexwatch Database Import Error

### ISSUE THREAD

**Issue by Denverboarder** [Tautulli/Tautulli#821]
I run the conversion tool and can see the shm wal files create and go away. Log shows an error. My PlexWatch was 0.3.3-dev I believe.

![image](https://cloud.githubusercontent.com/assets/16323017/17841727/ce3e8c70-67d8-11e6-942c-e53dbd21e871.png)

Uncaught exception: Traceback (most recent call last):
    File "C:\PlexPy\plexpy\logger.py", line 270, in new_run 
        old_run(_args, *_kwargs) 
    File "C:\Python27\lib\threading.py", line 754, in run 
        self.__target(_self.__args, *_self.__kwargs) 
    File "C:\PlexPy\plexpy\plexwatch_import.py", line 408, in import_from_plexwatch 
        import_ignore_interval=import_ignore_interval) 
    File "C:\PlexPy\plexpy\activity_processor.py", line 301, in write_session_history 
        session['transcode_decision']] 
KeyError: 'transcode_decision' 

I installed then did the update it stated. I also tried removing my .db shm/wal files and having it make fresh ones with no luck.

**Version:**
1.4.10

**Branch:**
Unsure

**Commit hash:**

**Operating system:**
Windows Server 2012 R2

**Python version:**
2.7

**What you did?**
I installed a fresh install. I upgraded via the WebGUI to 1.4.10. I shutdown and removed my .db/wal/shm files. I've tried repeated attempts and tried some of my .bak revisions in case that particular one was having issue.

**What happened?**
I've been met witth the exact same error each time.

**What you expected?**
A database import of my PWatch data.

**How can we reproduce your issue?**

Import my DB

**What are your (relevant) settings?**

**Link to logs:**
https://dl.dropboxusercontent.com/u/39724/plexpy.log
https://dl.dropboxusercontent.com/u/39724/pwatch.db

**Comment by JonnyWong16** [comment]
[I don't like people that don't search first.](https://github.com/drzoidberg33/plexpy/issues/815)

**Comment by Denverboarder** [comment]
I appreciate the link but definitely searched for the last 1.5 hours for similar instances. Sorry I didn't find it with what my query was.

**Comment by JonnyWong16** [comment]
It is the second one listed on the Issues page...

**Comment by Denverboarder** [comment]
As a note I started from 1.4.8 I thought and only after it wasn't importing did the update. I will try it. It didn't appear the same issue.

**Comment by JonnyWong16** [comment]
It is the same issue. I know what the bug is, but I just haven't had time to fix it.

**Comment by Denverboarder** [comment]
I'm not trying to be upset about anything I just apparently sucked at understanding the situation. I'm reverting to 1.4.8 now, thank you for linking me to the issue.
