### ISSUE TITLE
PlexPy no longer launching / Database error

### ISSUE THREAD

**Issue by alternativesurfer** [Tautulli/Tautulli#824]
**Version:**

**Branch:**
Master
**Commit hash:**

**Operating system:**
Win Server 2012 R2
**Python version:**
2.7
**What you did?**
Updated PlexPy on 8/17/2016 to the most recent commits
**What happened?**
Stopped running, Logs state: DatabaseError: file is encrypted or is not a database
**What you expected?**
PlexPy to launch
**How can we reproduce your issue?**

All I usually do is launch PlexPy from the py file.
**What are your (relevant) settings?**
n/a
**Link to logs:**
Truncated to the last 30 lines [plexpy.log.txt](https://github.com/drzoidberg33/plexpy/files/433576/plexpy.log.txt)

Full log
[plexpy.log_full.txt](https://github.com/drzoidberg33/plexpy/files/433579/plexpy.log_full.txt)

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#windows-q4

**Comment by alternativesurfer** [comment]
That appears to have made things worse....   =(

C:\PlexPy>plexpy.py
Traceback (most recent call last):
  File "C:\PlexPy\PlexPy.py", line 35, in <module>
    import plexpy
  File "C:\PlexPy\plexpy__init__.py", line 17, in <module>
    import sqlite3
  File "C:\Python27\lib\sqlite3__init__.py", line 24, in <module>
    from dbapi2 import *
  File "C:\Python27\lib\sqlite3\dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by JonnyWong16** [comment]
You got the wrong dll file.

**Comment by alternativesurfer** [comment]
Yep...I did
