### ISSUE TITLE
Pushbullet to all devices causes error

### ISSUE THREAD

**Issue by obsess** [Tautulli/Tautulli#826]
**Version:**
1.4.10
**Branch:**
master
**Commit hash:**
2a701a6dfea6ef4abda0c6db5f23f59d2a251a35
**Operating system:**
MacOSX 11 (plex & plexpy server) + Windows 10 (web user)
**Python version:**
2.7.12
**What you did?**
Tried to setup pushbullet notification to all devices (leave blank as stated on option screen)
**What happened?**
Notification error and no notifications were produced
**What you expected?**
Works as intended with one device selected.
http://imgur.com/67UcbVF
**How can we reproduce your issue?**

Setup pushbullet and select blank for no devices
http://imgur.com/DWz59G4
**What are your (relevant) settings?**
api key and blank device selection (tested on all 3 individually and works fine)
**Link to logs:**
https://gist.github.com/obsess/e5e532d75d80fd5e24d30f224729cf4b

**Comment by JonnyWong16** [comment]
Your Pushbullet channel is incorrect.

Blank device + channel name = send notification to channel.
Blank device + no channel name = send notification to all devices.
