### ISSUE TITLE
Proxy by nginx.

### ISSUE THREAD

**Issue by yukunyi** [Tautulli/Tautulli#827]
my nginx url is : https://xxx.xx.xx/
plexpy url is http://xxx.xx.xx:8182/
my nginx  proxy_pass set http header is : 
    proxy_set_header Host $http_host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto "https";
    proxy_set_header HTTP_X_FORWARDED_SSL on;
    proxy_set_header HTTPS on;
    proxy_set_header HTTP_X_FORWARDED_PROTO https;

but https://xxx.xx.xx/ redirect to https://xxx.xx.xx:443:8182/ , please support this .thanks.

**Comment by JonnyWong16** [comment]
> please support this

What? Your Nginx setup is wrong. Read the FAQ.

**Comment by yukunyi** [comment]
Sorry,I use the robot translated into English.
Found in the FAQ, have been solved, thank you.
