### ISSUE TITLE
There was an error communicating with your Plex Server. After turning off disableremotesecurity

### ISSUE THREAD

**Issue by Gunrunner101** [Tautulli/Tautulli#830]
Hello team,

First let me say I am a big fan of plexpy, thank you!

So i recently leaned that I had disableremotesecurity to on in my preferences.xml. After turning it off I am getting "There was an error communicating with your Plex Server' under Activity. to test if the change in the preferences.xml I turned on disableremotesecurity again and plexpy was working again. I have looked too see if anyone else has the same issues.

I am running the latest version of plexpy.
Running Plex version 1.1.2.2680.

Freenas 9.3.

Please let me know if you need any more info. Thank you in advance.

A

**Comment by JonnyWong16** [comment]
Verify your server again. Remove PlexPy from your server devices (Plex Settings > Devices) and fetch a new token in the PlexPy settings > Plex.tv account.

**Comment by Gunrunner101** [comment]
That did it thank you very much.
