### ISSUE TITLE
Notifications for recently added stopped working 

### ISSUE THREAD

**Issue by yeyeoke** [Tautulli/Tautulli#832]
Since last update recently added notifications stopped working, I have made no changes what do ever and testing the notifications works fine and I have checked that all the right settings are enabled, the log shows nothing as well, not trying to send and failing or anything like that. Just quiet. 

Running Ubuntu 14.04 and using slack and pushover. 

Plexpy: 1.4.11
Python: 2.7.6

**Comment by JonnyWong16** [comment]
Template not filled in.
