### ISSUE TITLE
Recently added notifications stopped working

### ISSUE THREAD

**Issue by yeyeoke** [Tautulli/Tautulli#833]
**Version: 1.4.11

**Branch: master

**Commit hash: a07f54ca33ed2ce1c8ce7adbe31e7cbfaeb18e98

**Operating system: Ubuntu 14.04

**Python version: 2.7.6

**What you did? I updated to latest version. 

**What happened? Slack and Pushover notifications stopped working for recently added media, they're still working for played/paused notifications. 

**What you expected? To get notifications :)

**How can we reproduce your issue?**
Update to 1.4.11, enable slack and pushover, add some media to plex, wait for the notifications to arrive. 

**What are your (relevant) settings?**
I have enabled everything having to do with notifications, the bell is yellow, the global notifications is selected aswell. I've even tried doing a fresh install without importing any database or any settings and tried to manually configure everything instead, but I still have the same problem. 

**Link to logs: https://drive.google.com/file/d/0B7lVjlJCj132WnpOM1VCZ2tDV0k/view?usp=sharing

**Comment by JonnyWong16** [comment]
I don't see anything wrong in your logs, so it's most likely a missing setting somewhere:
- Settings > Notifications > Global Notification Settings > Enable Recently Added Notifications
- Settings > Notification Agents > Bell Icon > Notify on recently added
- Libraries > Edit mode > Toggle Recently Added

Other things:
- Make sure your system clock is correct
- Make sure the new items show up on your Plex dashboard (homepage)

**Comment by yeyeoke** [comment]
You sir, is nothing short of a genius. 

I run everything except Plex in a VM on a Windows host and it turns out the host had screwed up the time. Thank you!
