### ISSUE TITLE
Home page statistics showing incorrect duration

### ISSUE THREAD

**Issue by F13** [Tautulli/Tautulli#834]
Version: 1.4.11
Branch: master
Commit hash: a07f54ca33ed2ce1c8ce7adbe31e7cbfaeb18e98
Operating system: Ubuntu
Python version: 2.7.12

If using play duration to track statistics on the main page, it shows an incorrect time versus the duration of all plays in the same time period according to the history database.

![image](https://cloud.githubusercontent.com/assets/1860089/18227638/a1c1378a-71f9-11e6-9b6c-8a39deef881b.png)
![image](https://cloud.githubusercontent.com/assets/1860089/18227644/b0112cb4-71f9-11e6-98d8-bade7d9bae75.png)

**Comment by JonnyWong16** [comment]
I can't reproduce this issue. Can you PM me your `plexpy.db` file either on Gitter or Discord?

**Comment by JonnyWong16** [comment]
No response.

**Comment by F13** [comment]
Sent over Discord just now.

**Comment by JonnyWong16** [comment]
You moved the movie at some point which re-added it to your Plex library with a different ID.

You have "Star Wars: Episode I - The Phantom Menace" with rating key `2470` and `2476`. On the movie's page in PlexPy, you can change the `rating_key` in the URL to see it. 

```
http://localhost:8181/info?rating_key=2470&source=history
http://localhost:8181/info?rating_key=2476&source=history
```

To join them back together, go to the movie page for the older entry (`2470`) and click the "Fix Metadata" button.

**Comment by F13** [comment]
Oh wow, I'd never have thought of that. So the discrepancy is because the home page statistics is showing the play duration of both entries, but the entry specific page is only listing its own plays. That's not a problem I'd have been able to find! Thanks!
