### ISSUE TITLE
Can't connect to plex after updating the server to 1.1.3

### ISSUE THREAD

**Issue by RacerBas** [Tautulli/Tautulli#835]
**Version:**
Plex 1.1.3
Plexpy 1.4.11

**Branch:**

**Commit hash:**

**Operating system:**
Ubuntu Server 14.04.5

**Python version:**
2.7.6

**What you did?**
Updated plex to 1.1.3

**What happened?**
Plexpy stopped being able to connect to plex. I suspect this is because every app now needs to authenticate first. Adding the IP address to the exclusion list in plexmediaserver does not seem to solve it. Trying to refetch the token does not fix the issue.

**What you expected?**

**How can we reproduce your issue?**
Update plexmediaserver to 1.1.3 and try connecting it to plexpy

**What are your (relevant) settings?**

**Link to logs:**
https://cloud.langevelde.com/index.php/s/1GUo7I0Ae01mxvU

**Comment by mapleleafs89** [comment]
I had a similar problem, my plexpy randomly stopped functioning a couple days ago and wouldn't connect to PMS. The path to my plex logs in the settings of plexpy was empty, and my token was blank. I refetched the token and filled in the path to the plexlogs and saved, it restarted plexpy and made me go through the initial wizard as if it was a new install. Luckily my database was still intact, and after I completed the steps I was back to normal :+1:

**Comment by drzoidberg33** [comment]
There is nothing wrong with PlexPy here, it already uses an app token to authenticate. From your log it shows that PlexPy cannot communicate at all with PMS. I'd recheck the server IP/hostname in your PlexPy settings.

**Comment by RacerBas** [comment]
Downgrading it from 1.1.3 to 1.1.2 makes it work instantly so it's something Plex related I think. Upgrading it back to 1.1.3 gives the same connection issues.

**Comment by drzoidberg33** [comment]
Are you using your hostname by any chance? If so, put the IP in and see if that works.

**Comment by RacerBas** [comment]
I'm using 127.0.0.1 (plex and plexpy are on the same server)

**Comment by nojohnny101** [comment]
I am also having a problem of plexpy not being able to communicate with my plex server right after plex server update to version 1.1.3.2700

EDIT: I am using internal IP addresses and no hostnames.

**Comment by drzoidberg33** [comment]
If you can provide a Plex Media Server log it may be helpful to see why the requests aren't getting through.

**Comment by nojohnny101** [comment]
sure. here it is attached.
[nojohnny101 plexpy logs.pdf](https://github.com/drzoidberg33/plexpy/files/455329/nojohnny101.plexpy.logs.pdf)

EDIT: also here is my plex server logs:
[nojohnny101 plex server logs.pdf](https://github.com/drzoidberg33/plexpy/files/455334/nojohnny101.plex.server.logs.pdf)

Thanks for looking into this, love plexpy!

**Comment by drzoidberg33** [comment]
@nojohnny101 Are you using the same user for PlexPy that you use for your server?

```
Sep 05, 2016 11:40:47.442 [0x80972fc00] DEBUG - Request: [10.0.1.32:62825
(Subnet)] GET /status/sessions (2 live) Signed-in
Sep 05, 2016 11:40:47.442 [0x80972fc00] DEBUG - Auth: We found auth token
(xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
Sep 05, 2016 11:40:47.442 [0x80972fc00] DEBUG - Auth: authenticating user as guest
Sep 05, 2016 11:40:47.442 [0x80972fc00] DEBUG - Completed: [10.0.1.32:62825] 401
GET /status/sessions (2 live) 0ms 212 bytes
```

According to this it looks like PlexPy may be trying to access it with a guest user account, although I don't really know if that request is coming from PlexPy.

**Comment by nojohnny101** [comment]
> @nojohnny101 Are you using the same user for PlexPy that you use for your server?

yes. the GUI login I use for plexpy is the same as the username for PMS. but nothing has changed except updating PMS.

I never understood for that to be a requirement (for PMS to share login name with the name used to login to plexpy)? Are you saying that I'm logging into Plex as guest?

**Comment by JonnyWong16** [comment]
Likely something to do with the new authentication requirements in PMS 1.1.3. Have you tried removing the PlexPy device from your Plex server settings, then fetching a new token?

**Comment by nojohnny101** [comment]
> Likely something to do with the new authentication requirements in PMS 1.1.3. Have you tried removing the PlexPy device from your Plex server settings, then fetching a new token?

Ok I removed it from "devices" on plex but how do I fetch a new token?

**Comment by JonnyWong16** [comment]
PlexPy settings > Plex.tv account > fetch token.

**Comment by nojohnny101** [comment]
it is saying invalid username and/or password. Is plexpy having trouble with network settings? what can I check, maybe something changed with the update.

Seems to instantly reject it like it can't reach the internet to verify.

**Comment by JonnyWong16** [comment]
If it says "Invalid username or password" then it connected to Plex.tv. Can you get to Plex.tv on the machine running PlexPy? 

Again, are you sure you are using the exact same account at the one signed into the settings page of your Plex server? Maybe sign out of the server and sign in again.

**Comment by nojohnny101** [comment]
> Can you get to Plex.tv on the machine running PlexPy?
> yes I can ping it from terminal
> 
> Again, are you sure you are using the exact same account at the one signed into the settings page of your Plex server? Maybe sign out of the server and sign in again.

I just did that. The password for plex.tv and my password for plexpy are not the same but I know that doesn't matter.
I just deleted the config.ini file and am going through the wizard and when I enter my login credentials it says the same thing "invalid username and password"

**Comment by nojohnny101** [comment]
well I ended up just backing up my database and then reinstalling from scratch. seems to be working now and it got the new token.

when I click "verify server" in the settings of plexpy it gives a check and "success" however on the homepage it still says "There was an error communicating with your Plex Server."

**Comment by JonnyWong16** [comment]
Grab your logs again. Please use [Pastebin](http://pastebin.com) or [Gist](https://gist.github.com).

**Comment by nojohnny101** [comment]
sorry for all the trouble. here are the logs:
http://pastebin.com/yc5d89XA

It is saying that it can't ping the server internally yet it gives "success" on verifying server and the token is successfully fetched? strange.

**Comment by nojohnny101** [comment]
little bit of an update. once I checked the option on PMS
"List of IP addresses and networks that are allowed without auth" and input the plexpy IP address. It works.

This is something I do not want to keep checked though because of security concerns. It was working before without this option (I believe). This isn't required is it?

**Comment by JonnyWong16** [comment]
You're still getting authentication errors with your token. 

```
2016-09-05 22:18:27 - WARNING :: Thread-13 : Failed to access uri endpoint /status/sessions. Status code 401
```

Try to find your token manually following this support page: https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token

Then enter it manually in the PlexPy settings.

**Comment by nojohnny101** [comment]
that was it!

thanks! I hope this isn't a widespread problem that is triggered by the PMS 1.1.3.2700 update.

Thank you thank you thank you. I think it actually would be appropriate to mention that this project has inspired me to learn python and i'm currently taking course to do so!
