### ISSUE TITLE
Suggestion, History page to show 'Currently Watching'

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli#836]
Just moved over from PlexWatch this morning, and loving what you have done with PlexPy

Just wondering, if its possible, to add the feature from PlexWatcWeb where shows that are currently being watched are also shown on the History tab - this was my default web page to load on my PC and iPhone to get a quick overview of what has happened (and is happening) on my server.

Screenshot of PlexWatch attached for info
![plexwatch](https://cloud.githubusercontent.com/assets/14026913/18241998/1243e43c-734c-11e6-999b-32818fd28d90.JPG)

**Comment by drzoidberg33** [comment]
This option was recently added, make sure you're on the latest release.

![capture](https://cloud.githubusercontent.com/assets/1313205/18245982/af2bb6a0-7368-11e6-9a6b-55c328ac410c.PNG)

**Comment by ghost** [comment]
Oops, thanks must have missed this option when reading through the settings (more coffee required)
