### ISSUE TITLE
installed version`?

### ISSUE THREAD

**Issue by zobe123** [Tautulli/Tautulli#84]
where can i see my installed Version? there should be a footer with some credentials

**Comment by drzoidberg33** [comment]
It's currently in the Settings menu under the General tab if you have a git cloned copy. That version is however not very useful yet and a new versioning system will be pushed in very soon (most of this is already pushed to the dev branch).

**Comment by zobe123** [comment]
ok, now i switched to dev branch and there is exact what i mean, thank you man. great work!

**Comment by drzoidberg33** [comment]
Pushed in 1.1.3
