### ISSUE TITLE
Sorting Media Info shows items in the wrong order.

### ISSUE THREAD

**Issue by zelestcarlyone** [Tautulli/Tautulli#840]
**Version:**  1.4.11 

**Branch:** Main

**Commit hash:** a07f54ca33ed2ce1c8ce7adbe31e7cbfaeb18e98

**Operating system:** Ubuntu Server / Viewed in Win10

**Python version:** 2.7.12

**What you did?** Went into Libraries > Movies > Media Info and sorted by bitrate, channels, size, plays etc.

**What happened?** The list sorts in the completely wrong order. Always the same order but always wrong.

![8b8634564213e9d6706d3b3193d75045](https://cloud.githubusercontent.com/assets/13156143/18576735/8772bde6-7be4-11e6-866c-6869136b4122.png)

**What you expected?** To it to be sorted in the correct order.

**How can we reproduce your issue?** Hopefully by going in the same way I did (Log in, Libraries > Your media folder of choice > Media info > Click the lil' sort buttons)

**What are your (relevant) settings?** All settings are default

**Link to logs:** No logs of importance to be shown here

**Comment by JonnyWong16** [comment]
Try clearing the PlexPy cache.

**Comment by zelestcarlyone** [comment]
A cache cleanout coupled with a PlexPy restart fixed the problem.
