### ISSUE TITLE
There was an error communicating with your Plex Server

### ISSUE THREAD

**Issue by KingSizedKilla** [Tautulli/Tautulli#841]
**Version: 1.4.11

**Branch: master

**Commit hash: a07f54ca33ed2ce1c8ce7adbe31e7cbfaeb18e98

**Operating system: Windows 10

**Python version:   2.7.11

**What you did? Removed device from Plex, retrieved new token, restarted PlexPy, issue still exists.  Removed device from Plex, made a backup of the PlexPy db, deleted PlexPy folder, cloned existing repo in Git, ran setup wizard, issue still exists

**What happened? Not sure, when I checked PlexPy this morning it was fine.  Checked it again an hour or so later and the error message appeared

**What you expected? 

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
PlexPy Logs http://pastebin.com/90MsEd8t

**Comment by JonnyWong16** [comment]
Have you checked #835?

**Comment by KingSizedKilla** [comment]
I'm sorry, I did try that as well but it did not help.

**Comment by JonnyWong16** [comment]
- Clicked verify server in the settings?
- Plex and PlexPy on the same machine or different machines?
- SSL enabled in Plex and/or "Use SSL" checked in PlexPy?
- Can you visit the `pms_url/web` in your config.ini file?

**Comment by KingSizedKilla** [comment]
The url is
https://192-168-1-12.61354ab07fee41ce838d98407a818a0b.plex.direct:32400.
If I change 192-168-1-12 to 127-0-0-1 it works

**Comment by JonnyWong16** [comment]
You only answered 1 out of 4 questions.

**Comment by KingSizedKilla** [comment]
Weird, I can see my inline replies.  I'll paste them below, as well as my
follow-up email
- Clicked verify server in the settings?  Yes
- Plex and PlexPy on the same machine or different machines?  Same
  machine
- SSL enabled in Plex and/or "Use SSL" checked in PlexPy?  Enabled in
  Plex and checked in PlexPy
- Can you visit the pms_url/web in your config.ini file?  When I try to
  open the url in Chrome, it indicates it cannot be reached
- The url is https://192-168-1-12.61354ab07fee41ce838d98407a818a
  0b.plex.direct:32400.  If I change 192-168-1-12 to 127-0-0-1 it works

**Comment by JonnyWong16** [comment]
Use 127.0.0.1 as the IP address if it's on the same machine.

**Comment by KingSizedKilla** [comment]
This is what I have configured in the settings

​
Can I make the change in the config.ini?

**Comment by JonnyWong16** [comment]
Also uncheck "Use SSL" if Plex is only set to "Preferred".

You can't manually change the config file. It will get overwritten.

**Comment by KingSizedKilla** [comment]
Unchecking Use SSL and restarting seems to have fixed the issue.  Thanks
for your assistance and thanks for the great app!
