### ISSUE TITLE
Plexwatch db wont import

### ISSUE THREAD

**Issue by bashers222** [Tautulli/Tautulli#845]
I've just installed the plexpy on my web server and im very impressed.
I'm trying to import my last two years of sats from plexwatch db but its not accepted.

plexwatch is running 3.2 as required.
I've the logs ready to send over if required via PM as im not sure if they contain senstive info

Are you able to help out:???

Thanks in advance
Ashley

`Configuration File:    /opt/plexpy/config.ini
Database File:  /opt/plexpy/plexpy.db
Log File:   /opt/plexpy/logs/plexpy.log
Backup Directory:   /opt/plexpy/backups
Cache Directory:    /opt/plexpy/cache
GeoLite2 Database:  Click here to install the GeoLite2 database.
Arguments:  ['--quiet', '--daemon', '--nolaunch', '--pidfile=/var/run/plexpy/plexpy.pid', '--datadir=/opt/plexpy']
Platform:   Linux 3.16.0-4-amd64
Python Version:     2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]`

**Comment by JonnyWong16** [comment]
Please post your logs to [pastebin.com](http://pastebin.com).

**Comment by bashers222** [comment]
I've uploaded here; http://pastebin.com/vGwahehw
at line 193 you can see its not happy importing, and at the last two lines where i've tried it again this morning importing both grouped and procesed tables from the plexwatch db.

i can PM you the db if that helps

**Comment by JonnyWong16** [comment]
Are you specifying the right database? What are you entering into the "Database Location"?

**Comment by bashers222** [comment]
/opt/plexWatch/plexWatch.db

**Comment by JonnyWong16** [comment]
Does PlexPy have access/permission to access that folder?

**Comment by bashers222** [comment]
your right. i forgot plexpy runs as another user who needed access to this file
