### ISSUE TITLE
[Feature Request] Add notifications about concurrent number of streams / transcoding

### ISSUE THREAD

**Issue by edddeduck** [Tautulli/Tautulli#847]
Could we expand the code used for current notification about concurrent streams for a single user and provide the ability to warn when a set number of concurrent streams for all users (not a single user) is hit? 

Having a similar ability to warn when a set number of concurrent streams are bring transcoded (for all users in total) would also be very useful.

These warnings would help warn people when network upload and server CPU might be under high load.

**Comment by JonnyWong16** [comment]
~~https://github.com/JonnyWong16/plexpy#feature-requests~~

https://github.com/JonnyWong16/plexpy/tree/dev#feature-requests

FeatHub link is fixed on the dev branch.

**Comment by edddeduck** [comment]
UPDATE: Thanks for providing details on where a correct url could be found.

Request refiled as requested - http://feathub.com/JonnyWong16/plexpy/+135
