### ISSUE TITLE
No Plex Cloud support

### ISSUE THREAD

**Issue by endiz** [Tautulli/Tautulli#849]
This is more of a request then an issue, but it would be great if plexpy supported the new Plex Cloud server. I'm on the beta if you need me to test anything out.

**Comment by paavo** [comment]
same here =)

**Comment by Hellowlol** [comment]
@JonnyWong16 Are you in the beta?

**Comment by JonnyWong16** [comment]
~~I am not, but~~ someone let me connect PlexPy to their cloud server. It works.

**Comment by paavo** [comment]
and how do i connect PlexCloud to PlexPy?

**Comment by JonnyWong16** [comment]
You can't right now. I'm just saying it should work in the future. There are still some things to work out.

**Comment by paavo** [comment]
perfect...
monitoring my Server and PlexCloud would be awesome =)

**Comment by PremiumizeNZB** [comment]
You can actually use Plexpy with Plex Cloud already. See here:
https://github.com/JonnyWong16/plexpy/issues/113#issuecomment-252004272

**Comment by francesco2013** [comment]
@JonnyWong16 thank you so much for your great app I love it. 

One question as per today 20/04/2017 is the support for Plex Cloud available ? I guess after 6 months it should be there since you were saying you were working with the Plex people for it. 

Thanks a lot again :)

**Comment by JonnyWong16** [comment]
Nope, not yet.

**Comment by francesco2013** [comment]
ok no problem thanks a lot again for your great work :)

**Comment by carlosrovira** [comment]
Hope you could give more info on this so we could know what's happening. Thanks in advance

**Comment by ChrisColotti** [comment]
This will be great when added....if it is will you be able to use ONE setup of PLexPY with multiple servers (local and cloud)?  I know both Plex Cloud and having multiple servers are both requests I've read here. :)

LOVE this app.  Running it as the Native QNAP App.

**Comment by PhillyUrbs** [comment]
I'd love to see Plex Cloud support.  Any news on it?

**Comment by JonnyWong16** [comment]
Added in v2.

**Comment by ChrisColotti** [comment]
WOOT!!  Was this also part of multi-server support as well on one install?  Love to be able to stop running 3 instances of the tool :)

**Comment by TheMeanCanEHdian** [comment]
No mutli-server support
