### ISSUE TITLE
Different tack

### ISSUE THREAD

**Issue by Elrique64** [Tautulli/Tautulli#85]
I know that what you are trying to do with PlexPy is make an alternative to PlexWatch/Web.  What you have is GREAT!

But, the thought I just had was incorporating the Transmogrify extension into PlexPy.  I know this is counter to the original designs, but the added functionality combining the two together would be AWESOME!

One place to see the stats on media and on usage.  What formats/resolutions have been streamed vs what is available on the server for that same media.  I know some people, like Cayars and myself keep at least a couple of different bitrates/reso's for most of the heavier traffic seasons/movies.  

You probably don't want to take something like this on, but give it some thought before you kill the request...  :)

**Comment by drzoidberg33** [comment]
Not sure exactly how this works.

Shouldn't this be implemented the other way around (e.g. Transmogrify implements PlexPy features into itself)?

PlexPy has an API which allows 3rd party apps to pull info - however nothing has been really implemented here yet as there have been other priorities more important. Once this gets done I will write API documentation so other apps can interface with it.

**Comment by Elrique64** [comment]
Not sure who would do that, though.  The guy that did Transmogrify stopped working on it.  As it's a browser extension, it only worked on a couple of browsers, so not every one could use it.

Anyway, I just threw this out there for thought.  It's probably a stupid idea.

**Comment by drzoidberg33** [comment]
Ye I'm just closing this. Not going to happen. Sorry.
