### ISSUE TITLE
[Feature Request] Media Info Graphs

### ISSUE THREAD

**Issue by dannyhanes** [Tautulli/Tautulli#850]
I would love to see some pie charts showing what percentage of my movies / tv shows were 1080p versus 720p versus all the rest. This would be helpful is performing an audit on some of my back catalog. 

Ideally I would like graphs / percentages for all of the information tracked in the "Media Info" section. (Frame rate, audio codec etc)

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/tree/dev#feature-requests
