### ISSUE TITLE
Most Listened to Artist / Most Popular Artist = Various Artists 

### ISSUE THREAD

**Issue by bagobones** [Tautulli/Tautulli#854]
**Version:**
Version 1.4.12

**Branch:**
master

**Commit hash:**
e029f329eb74f8d1f23beb284251c7382b2a4e1f

**Operating system:**
Linux 4.4.0-38-generic

**Python version:**
    2.7.12 (default, Jul 1 2016, 15:12:24) [GCC 5.4.0 20160609]

**What you did?**
Listed to several soundtrack albums, and several songs from those albums repeatedly

**What happened?**
 Various Artists became Most Listened to Artist and Most Popular Artist

**What you expected?**
Each song has a specific artist, since I played specific songs more than others I would have suspected the SONGS artist would have become both Most Listened to Artist and Most Popular Artist.

PlexPy seems to be using the Album artist which appears to be problematic on multi artist albums

**Comment by JonnyWong16** [comment]
#600
