### ISSUE TITLE
Enlarge table width to 100%

### ISSUE THREAD

**Issue by ecleese** [Tautulli/Tautulli#857]
This is a minor request but I see no benefit in keeping the libraries, users, history graphs, synced items and log tables at 90% width. Increasing the width to 100% would be especially helpful on mobile platforms.

**Comment by XusBadia** [comment]
I agree, although I would add a max-width so it isn't too wide in large monitors.

See #870 

A media query so it only applies to smaller screens would also work. What do you think would be the best solution?

**Comment by JonnyWong16** [comment]
I think using `max-width` is a good idea so it's not crazy.

**Comment by JonnyWong16** [comment]
Changed in v1.4.15.
