### ISSUE TITLE
[Feature Request] Add Stream-Type column to history

### ISSUE THREAD

**Issue by xorinzor** [Tautulli/Tautulli#858]
It would be great if another column could be added to the history list showing what type of streaming was used, this way it would be possible to see what files could use optimization later on.

Ie:
- Direct Play
- Direct Stream
- Transcode
- Etc

**Comment by JonnyWong16** [comment]
Hover your mouse over the [three different icons](https://cloud.githubusercontent.com/assets/9099342/19024547/9a5e4b2c-88ba-11e6-9a1c-750f31e5bd2b.png) in the "Player" column.

**Comment by xorinzor** [comment]
Sorry to say, but when it comes to UI design that should have its own column, you wouldn't expect to find that in the "player" column.

Glad it's there at least though

**Comment by JonnyWong16** [comment]
An icon tells you the exact same info as the words "Transcode", "Direct Play", "Direct Stream", but with less space. Click on the player for more info.

You don't want me to add the words "Movie", "TV Show", or "Music" to replace the media type icons in the "Title" column.

**Comment by xorinzor** [comment]
Agreed, however in it's current state these icons, as well as the
expand/collapse icons, are easily overlooked and there's not really
anything to indicate the functionality is there.

helpful would be a text bubble for first-time use, when visiting a page
with such an icon pointing out that icon is there with a certain goal in
mind, ie: "click here to show the episodes".

It's just a bit of feedback which I think users would benefit from, of
course you're free to do with that what you want.
