### ISSUE TITLE
FR: Option to ignore a user from the overviews

### ISSUE THREAD

**Issue by joswart** [Tautulli/Tautulli#86]
I am only interested in what my friends view on my system. I already have a pretty good feeling of what I am viewing myself. It would be nice if one could selectively remove accounts from the display, so one could just see how many resources those others are claiming.

**Comment by drzoidberg33** [comment]
Do you still want to keep history for the user but just not display the data?

**Comment by joswart** [comment]
Yeah, would like to be able to dingle out groups of users. 

Jord Swart
Engerstraße 21a
D-40235 Düsseldorf

e: jord.swart@jordswart.org
t: +49 211 - 468 768 85
m: +49 162 - 214 74 85

**Comment by drzoidberg33** [comment]
Dingle out? :laughing: I hope not.

Okay, so it must continue to log history for these users but you should be able to toggle whether the user shows up in any report.

There is already a per-user option to disable logging completely but then obviously you cannot re-enable it later and see old history for that user.

**Comment by joswart** [comment]
I meant single out, but I guess you understood ;-)

Yes, basically the way you describe it, show me the history for group a and then show me the history for group b.

I wasn’t aware there is an option to disable certain users, where is it hidden? Or is there a fine manual somewhere I haven’t read?

Thanks for the quick responses!

**Comment by drzoidberg33** [comment]
If you go to the Users page and select the user you want, on their profile page there is an edit icon (the pencil) next to their username. This will bring up options for that user.
