### ISSUE TITLE
[Feature Request] Custom Notification when manually marking an item as watched

### ISSUE THREAD

**Issue by srob650** [Tautulli/Tautulli#863]
Title says it all, would love custom notifications when manually marking as watched.  Any plans to do this?

PS I did read the note about feature requests being handled on FeatHub but the link seems to be dead so I posted here.

**Comment by JonnyWong16** [comment]
The link is fixed on the dev branch. https://github.com/JonnyWong16/plexpy/tree/dev#feature-requests
