### ISSUE TITLE
Enhancement request: Notifications only for selected libraries

### ISSUE THREAD

**Issue by nibble4bits** [Tautulli/Tautulli#865]
Since Plex DVR started, my notifications have been inundated with what I'm recording on Plex DVR. I really just want the notifications for my end users to see what I've added, rather than what I'm recording, since I put all my DVR recordings in one particular library so I can edit out the commercials.

There doesn't seem to be a way to select particular libraries among my TV libraries for the notifications. Could we have a way to pick & choose which libraries to use for notifications?

**Comment by JonnyWong16** [comment]
Have you read the FAQ?
