### ISSUE TITLE
No such file or directory (.log) after reinstalling and adding database

### ISSUE THREAD

**Issue by Sander-96** [Tautulli/Tautulli#866]
http://imgur.com/a/7UjQ6

Error that I'm getting in the screenshot. It closes before I could actually read it so had to time my screenshot.

Changed my PleX server to another PC (both Windows 10) and wanted to take PlexPy with me. Not working out so well so far.

**Comment by JonnyWong16** [comment]
Did you follow the reinstall instructions in the FAQ?

**Comment by Sander-96** [comment]
I added the PlexPy database file after the reinstall yes.

**Comment by JonnyWong16** [comment]
PlexPy can't create the logs folder. Either it doesn't have permission or there is already one specified in the config.ini file which it can't find. Try deleting the config.ini file and trying again or installing PlexPy somewhere else.

**Comment by Sander-96** [comment]
Installing PlexPy somewhere else worked, somehow it didn't like my C drive. Thanks for the help Jonny!
