### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by unixjeff** [Tautulli/Tautulli#868]
**Version:**
v1.4.13
**Branch:**
Master
**Commit hash:**
1a2e205c1f0ab91582ce498a8828ee07f573cd4f
**Operating system:**
ubuntu 15
**Python version:**
Python 2.7.10
**What you did?**
click update in webui then crashed and wont start back up
**What happened?**
disk malformed
**What you expected?**
start up
**How can we reproduce your issue?**
fails on start up

**What are your (relevant) settings?**

**Link to logs:**
https://zerobin.net/?43f1f760acb48705#997VsxRdSFrH7F5OmCDe8rzSpppfpJZDLLO/wU3Aj8k=

**Comment by JonnyWong16** [comment]
Search the issues, this has been solved many times.
