### ISSUE TITLE
Last Watched not updating even though History correct

### ISSUE THREAD

**Issue by jedimstr** [Tautulli/Tautulli#874]
Last Watched on Homepage stops updating while History correctly shows up to date usage.  
I have to delete history entries to get Last Watched working again, which I'd rather not do.
I've had to clear out history a few times in the last month already.

PlexPy ver 1.4.14 in an unRAID Docker Container.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#history-q6

**Comment by jedimstr** [comment]
Yes, I know about the percentage setting.
The missing Last Watched items were all greater than 80% watched.  We're talking about 5 100% viewings and 3 90+% viewings over the course of 2 days that showed up in History, but not Last Watched.
My setting is at the minimum 50%.

Only a purge of History going back to, and including the last item shown in Last Watched fixes the issue (temporarily).

**Comment by JonnyWong16** [comment]
Screenshot, logs, and database please. You can PM the database to me on Discord (link is in PlexPy Settings > Support).

**Comment by jedimstr** [comment]
I'll have to accumulate enough history again to recreate the issue and gather the relevant logs/shots/db that would reflect the issue.  Shouldn't take too long though since I had to purge once this week and once a week and a half ago.

**Comment by JonnyWong16** [comment]
The current logs and db with the mismatch should be enough if it's still at the top of your history list.

**Comment by jedimstr** [comment]
History purged. So no, it's not at the top of the history list anymore.  I'll get you logs and db once I recreate the issue again.
