### ISSUE TITLE
PlexPy showing every stream as done by local user.

### ISSUE THREAD

**Issue by darkcloud784** [Tautulli/Tautulli#875]
Every single stream is being shown as the local user. I have confirmed my server is secured and I have multiple users that access it from both the local network and from external. Plexpy is installed on the same VM I have plex installed on.

Plexpy version: 1.4.14

Commit Hash:    86a9230da8a9ab1af18eacb07a9fd7086437305c

Branch: master

Operating system: Ubuntu 16.04

Python Version: 2.7.12

What I did: Unsure what I'm supposed to do in this situation.

What Happened: See above

What you expected: Individual users being logged for what they are streaming. Plexpy did this before I re-installed it a few revisions ago.

How can we reproduce your issue? Install it?

Log is too large for pastebin in full. Here is the last 24 hours: http://pastebin.com/QWADP5Xd

**Comment by JonnyWong16** [comment]
Please follow the issue guidelines: https://github.com/JonnyWong16/plexpy#if-nothing-has-worked

**Comment by darkcloud784** [comment]
Updated post to list the information requested.

**Comment by JonnyWong16** [comment]
Can you access https://plex.tv/api/users? Can PlexPy access https://plex.tv/api/users?

**Comment by darkcloud784** [comment]
The server is web connected, and access any website available so there should be no reason why it cant. I can even access the information using wget from commandline.

**Comment by JonnyWong16** [comment]
Well, your logs are saying otherwise. 

```
Failed to access uri endpoint /api/users with error [Errno 2] No such file or directory
```

**Comment by darkcloud784** [comment]
I've checked my firewall settings and everything network related and confirmed that is not he problem. Afterwards, I re-installed plexpy and now its showing all the users though I have no idea why as nothing changed configuration wise.

**Comment by darkcloud784** [comment]
Re-opening as I restarted the service and now have the same problem. This is a fresh install of plexpy from the installation instructions on the wiki. Please note, I have resolve the perms issue on /opt/plexpy/config.ini and I can no longer authenticate using plexpy with plex.tv using my usr/password. I have even gone the length of changing my plex.tv password to something extremely simple for testing.

http://pastebin.com/AB31DjrN

**Comment by pychopaul** [comment]
Had the same problem.  you need a new pms token.  go to plexpy settings, plex.tv accout, and click the button to fetch a pms token.(yes, even if you already have a token)
