### ISSUE TITLE
Wrong images shown after Plex reinstall

### ISSUE THREAD

**Issue by JoooostB** [Tautulli/Tautulli#877]
Dear Developers,

I have been using PlexPy for a while now, and I love it! But since I rebuilded my Plex server last weekend, I noticed that wrong imaged are shown at some movies/series. Is there some way to completely rebuild the database? Or redownload all the images only?
See attachment for details. (Some images are right, some aren't)

Best regards,

JoooostB

![image](https://cloud.githubusercontent.com/assets/8641236/19441819/65ed2542-9487-11e6-9a6d-c0000c530c30.png)

**Comment by JonnyWong16** [comment]
PlexPy caches images from your Plex server. You can delete the cache in the Settings > General > Clear image cache.

**Comment by JoooostB** [comment]
But Plex shows the covers without any issues, looks like a PlexPy problem to me

**Comment by JonnyWong16** [comment]
I just told you how to fix it....with an explanation of why.

**Comment by JoooostB** [comment]
I don't have that option... So it's not fixed actually. Am I overlooking anything?
![image](https://cloud.githubusercontent.com/assets/8641236/19472479/c58fcf68-9527-11e6-86f0-3872bda564f5.png)

**Comment by Hellowlol** [comment]
You need to clear **PlexPy** cache. Plexpy caches the images based on the "uri" since plex is rebuild the mediaids are changed. Thats why you get a poster of games thrones up when you really browsing Kevin can wait. 

JonnyWong16 said how to clear it in plexpy..

**Comment by JonnyWong16** [comment]
![image](https://cloud.githubusercontent.com/assets/9099342/19491855/4e57fe8c-9529-11e6-986e-cad4dea0063f.png)

**Comment by JoooostB** [comment]
I really appreciate your answers, but I don't have that option....
![image](https://cloud.githubusercontent.com/assets/8641236/19497145/3a4bf8b4-958b-11e6-96be-f38bf7afde7b.png)

**Comment by JonnyWong16** [comment]
![image](https://cloud.githubusercontent.com/assets/9099342/19497258/5b427b6a-9540-11e6-96f7-7daf0a464447.png)

![image](https://cloud.githubusercontent.com/assets/9099342/19497335/b3dc3f0e-9540-11e6-8db8-b4b8791836fa.png)

![image](https://cloud.githubusercontent.com/assets/9099342/19497361/d63c4026-9540-11e6-88ef-7831d9c5d3fd.png)

**Comment by JoooostB** [comment]
I really appreciate your instructions, amazing how willing you are to help me. But it's not there. Seriously. Running on CentOS btw, latest rpm from there website

**Comment by JoooostB** [comment]
OMG delete this issue, I feel so stupid. I was looking in Plex instead of PlexPy. Sorry to waste your time!
