### ISSUE TITLE
Bad data bug - how to remove?

### ISSUE THREAD

**Issue by RichyRich1970** [Tautulli/Tautulli#878]
**Amazing app - so easy to use, data is relevant, useful and just plain cool!
As a previous Python developers, I can appreciate what you have done here!
Thank you!**

**Version:**
v1.4.14

**Branch:**
master

**Commit hash:**
"86a9230da8a9ab1af18eacb07a9fd7086437305c"

**Operating system:**
Server 2012 - showing as Windows 8.1 in PlexPY Config window

**Python version:**
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

**What you did?**
Looking at data, there is a single day with massively wrong data points.
Oct 8th, 2016 shows over 7400 simultaneous streams, which then flows into the graphs (which are awesome!) being useless as it scales to the 7400 and all other charts appear to be 0 as they are just a few counts.
I've narrowed it down to one date (10/8/16) and one user.

**What happened?**
I don't know how it happened, I went to look and found it while trying to look at the Plex server usage a few days ago

**What you expected?**
I would like to delete the bad data, maybe just delete all of Oct 8th data, which would at least make all the other data counts, graphs, etc. not be so skewed.

**How can we reproduce your issue?**

I can pull any logs needed, let me know what would help?

**What are your (relevant) settings?**

**Link to logs:**

![image](https://cloud.githubusercontent.com/assets/22891498/19444194/736e9edc-945d-11e6-94c4-bc20bd5c0a02.png)

![image](https://cloud.githubusercontent.com/assets/22891498/19444133/34e67324-945d-11e6-99cc-4697a521157a.png)

**Comment by JonnyWong16** [comment]
#867
