### ISSUE TITLE
Pushover notifications stopped working

### ISSUE THREAD

**Issue by dashbad** [Tautulli/Tautulli#879]
**Version:**
1.4.14

**Branch:**
master

**Commit hash:**
86a9230da8a9ab1af18eacb07a9fd7086437305c

**Operating system:**
Debian 8.6, linux kernel 3.16

**Python version:**
2.7.9

**What you did?**
pushover notifications simply stopped working a couple of days ago.

To test I have:
1. restarted plexpy
2. cleared logs
3. opened notification settings
4. re-entered pushover API token and user key
5. clicked save
4. sent a test pushover notification
5. received "success" toast

I have also verified that pushover is working by issuing notifications directly from the command line on the same machine

**What happened?**
No pushover notification received and no log message

**What you expected?**
A notification and a log message

**How can we reproduce your issue?**
Steps above

[plexpy.txt](https://github.com/JonnyWong16/plexpy/files/538985/plexpy.txt)

any tips on how to debug appreciated

**Comment by JonnyWong16** [comment]
Did you just recently update to v1.4.14? Force refresh the page (Ctrl+F5). 

Also post your full logs to pastebin.com.

**Comment by dashbad** [comment]
Thanks, this was a browser issue
