### ISSUE TITLE
History stopped working, not writing data 

### ISSUE THREAD

**Issue by izeen** [Tautulli/Tautulli#88]
Had to do a hard reboot of my server this sunday due to the system being frozen up. After this PlexPy no longer records history data. User activity shows up fine on the first page and old data is displayed fine aswell in the history section, but no new data gets written. What can i do, some help would be appreciated.

**Comment by drzoidberg33** [comment]
Could be a corrupted database. Could you send me a copy of database (the plexpy.db file). You can just mail it to me: timvdwest (at) outlook (dot) com.

I still need to write an automated backup procedure that keeps recent backups.

The fact that the file is still readable though is good, which means it should be easy to fix.

**Comment by izeen** [comment]
Just sent it to you now. It's 17mb so tell me if the mail doesn't reach you.

**Comment by drzoidberg33** [comment]
Did you zip/compress it? That would make the size considerably smaller.

**Comment by izeen** [comment]
Resended with better compression :)

**Comment by drzoidberg33** [comment]
Thanks, got it. Will get back to you.

**Comment by izeen** [comment]
Thank you, really appreciate it.

**Comment by izeen** [comment]
i still have plexwatch running, technically could i just remote the plexpy.db and import the plexwatch database again to get everything working again? Maybe i´ll save you a headache by doing that instead :) ?

**Comment by drzoidberg33** [comment]
Yes, you can do that.

Just make sure you shut down PlexPy before removing the database files (there will probably be 3 files plexpy.db, plexpy.db-wal and plexpy.db-shm).

Then start it back up and run the PW import again.

If that doesn't solve your issue, then it's likely not a db issue but something else. A copy of your log file would be needed to see if something else is the matter.

**Comment by izeen** [comment]
Thanks, i´ll give that a try right away. I´ll keep you posted if it started working again :)

**Comment by izeen** [comment]
New data was imported and i can see it in the history tab fine, STILL however no new data is recorded :( I emailed you the logs.

**Comment by izeen** [comment]
never mind my last post, its there now. It just took a little while before it showed up. Thank you for your help Tim

**Comment by drzoidberg33** [comment]
I'm going to close this as it's resolved.
