### ISSUE TITLE
[Feature Request] Treat Players as Users

### ISSUE THREAD

**Issue by oskameDEV** [Tautulli/Tautulli#880]
First of all, great work on PlexPy!

One of my feature requests is to allow us to treat players as users.

How I use Plex is that my family living in different places use my account to stream media, because friend account access requires a Plex Pass.

It would help a lot to get more useful notifications and stats to see who (which player) has watched what.

Thanks!

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests
