### ISSUE TITLE
Notifcation Agent "Facebook" Include Link to Plex Web options has no HTTPS link on Facebook (to app.plex.tv/web)

### ISSUE THREAD

**Issue by alneven** [Tautulli/Tautulli#882]
Hello there,
I have a problem which I just recognized. I have a working Facebook notification with LINK to the app.plex.tv/web site, and this is not **HTTPS**.
How can I change the link which PlexPy posting to Facebook that it's https?
My Plex is reachable over HTTPS
http://imgur.com/a/yMOKa

Any idea? Thanks!

**Version: VERSION 1.4.14**

**Branch: master**

**Commit hash: 86a9230da8a9ab1af18eacb07a9fd7086437305c**

**Operating system: Debian Linux Linux 3.2.0-4-686-pae**

**Python version: 2.7.3 (default, Jun 20 2016, 16:18:47) [GCC 4.7.2]**

**Comment by JonnyWong16** [comment]
I messed up. It's a bug.

**Comment by alneven** [comment]
OK, then I guess it is on your list.
Thanks! ;-)

**Comment by JonnyWong16** [comment]
Fixed in v1.4.15.
