### ISSUE TITLE
History of movies in thousands after update. 

### ISSUE THREAD

**Issue by pabin1817** [Tautulli/Tautulli#883]
I updated from v1.4.12 to v1.4.14 and now my history shows 2 days of watching movies in the thousands. 
I downloaded the latests version and copy and pasted (replaced the original files) from the zip to the folder and launched PlexPy. 
![screen shot 2016-10-21 at 11 12 45 pm](https://cloud.githubusercontent.com/assets/22993434/19617388/32573a00-97e4-11e6-8889-1e58f9298c7c.png)
I don't know if I can fix this or just delete those two days from the logs but I don't know how to get to the logs for specific days. 
I am running PlexPy on a Mac. I know how to get to the files for PlexPy but don't know what file stores the logs or how to search for those days.

**Comment by JonnyWong16** [comment]
#867

**Comment by pabin1817** [comment]
I did what it asked to do in that forum but nothing has changed. Is there a way to just delete the history for those days?

**Comment by JonnyWong16** [comment]
You will need to edit the database manually with something like http://sqlitebrowser.org. 

Backup your database and make sure PlexPy is shutdown. Look in the three tables `session_history`,  `session_history_media_info`, and `session_history_metadata` and delete the same row from all three as necessary. Dates are stored in the `session_history` table in epoch format. Or if you know Sqlite then you can just run the query to delete for a certain date. I don't know it off the top of my head right now.
