### ISSUE TITLE
Request: Pushover notification per user per IP Address

### ISSUE THREAD

**Issue by LuisNunezC** [Tautulli/Tautulli#884]
Hello,
Have an enquiry about a custom script:
My PlexPy runs on a Synology NAS with Pushover notifications and everything runs smoothly. However, I would like to identify the location of the IP Address from where a playback is running and send this info the Pushover notification instead of the IP Address.
ie:

If user "A" has registered 3 different IP addresses and starts playback from:

IP A = location1
IP B = location2
IP C = location3 

The notification should then show IPX's value instead of the IP address for that user.

So at end the notification would give me the location of where the playback started based per user If user A or user B... else normal notification
How can I achieve that?
Or better yet, how could I use GeoLite2 Database to show country or city (instead of hardcoding values for IP Addresses)?

Thanks for your feedback!

L.

**Comment by JonnyWong16** [comment]
You can lookup GeoIP info through the PlexPy API: https://github.com/JonnyWong16/plexpy/blob/master/API.md#get_geoip_lookup

And send a notification through the API:
https://github.com/JonnyWong16/plexpy/blob/master/API.md#notify
1. Pass the IP address to your custom script.
2. Use the script to query the PlexPy API with that IP address to retrieve the geolocation.
3. Send the location (and other notification info) back through the API again to send a Pushover notification.

Join the [PlexPy Discord server](https://discord.gg/36ggawe) and I can help you out. GitHub should be used for bug reports.
