### ISSUE TITLE
[Feature Request] Graphical representation of transcode performance, throttling, etc

### ISSUE THREAD

**Issue by BuggeringHell** [Tautulli/Tautulli#885]
It would great to view a graph of single/concurrent transcodes (colour coded) with time on the X axis and speed/throttled on the Y axis. Unless I am missing something, at the moment it is only possible to know the speed of a transcode live. This would be very useful for diagnosis and performance benchmarking during concurrent transcodes, determining limitations and comparing types of codecs/bitrates etc.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/blob/master/README.md#feature-requests
