### ISSUE TITLE
Group Table and Watch Statistics History Question

### ISSUE THREAD

**Issue by montizzl3** [Tautulli/Tautulli#886]
**Version:**
1.4.14
**Branch:**
master
**Commit hash:**
86a9230da8a9ab1af18eacb07a9fd7086437305c
**Operating system:**
Windows Server 2012
**Python version:**
2.7

**Question**
When the setting to "Group Table and Watch Statistics History" is checked, what is considered a successive play?  Is it anything resumed within the same date or within 4 hours or 60 minutes or x seconds or what amount of time?

Is there any way for me to alter the amount of time that constitutes a successive play?

**Comment by JonnyWong16** [comment]
Questions should be asked on the support channels: https://github.com/JonnyWong16/plexpy#plexpy
GitHub issues are for bug reports.

History is grouped together if it is the same person, playing the same item successively, and forward progress has been made.

```
if user_id == user_id and rating_key == rating_key and view_offset > view_offset
```

If you play a different item in between, it won't group.
If you rewind to a previous point and stop, it won't group.

It is not time based. You can watch start something today, and continue next week and it will be grouped as long as the conditions above are met.

**Comment by montizzl3** [comment]
OK, sorry for posting in the wrong section.  Thanks for the clarification!!
