### ISSUE TITLE
Cannot set script notifications settings, crashes

### ISSUE THREAD

**Issue by MysticRyuujin** [Tautulli/Tautulli#888]
**Version:**
1.4.14

**Branch:**
Master

**Commit hash:**
86a9230da8a9ab1af18eacb07a9fd7086437305c

**Operating system:**
Ubuntu 16.04 LTS x64

**Python version:**
Python 2.7.12

**What you did?**
Trying to configure script notifications

**What happened?**
[YouTube Video](https://youtu.be/ds1LoJEELAA)
PlexPy stops responding completely after I try to set/configure the Scripts notifications. Also when I click Scripts settings I'm presented with a different settings page. It varies depending on what I click on beforehand. If I just click Scripts settings first, nothing appears. I have to restart the service via "service plexpy restart"

**What you expected?**
To be able to configure script notifications settings.

**How can we reproduce your issue?**
I can personally reproduce it every single time I try to configure the settings.

**What are your (relevant) settings?**
Setup is pretty basic and have gust login enabled.

**Link to logs:**
[Pastebin](http://pastebin.com/s94gEFHb)

**Comment by JonnyWong16** [comment]
Shut down PlexPy and try removing the entire `[scripts]` section in your `config.ini` file, then restarting.

Also try force refreshing the page (Ctrl+F5).

**Comment by MysticRyuujin** [comment]
Removing it from the config and re-configuring solved it.
