### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by hannibal1986** [Tautulli/Tautulli#890]
What changes need to add bot in multiple groups and work alone allin1 ?

**Comment by JonnyWong16** [comment]
http://feathub.com/JonnyWong16/plexpy/+40

**Comment by hannibal1986** [comment]
Not posible work bot alone and all groups?

**Comment by Electronickss** [comment]
> alone and all groups

Are you asking if one bot can send to multiple groups?

**Comment by hannibal1986** [comment]
Yes, use bot in multiple groups, only add bot in group and work <--- this, sorry for my bad english

**Comment by Electronickss** [comment]
Then yes I believe you will need to wait till that feature request that @JonnyWong16 referenced hits the main branch

**Comment by hannibal1986** [comment]
Ok, thnks
