### ISSUE TITLE
Web Interface Setting change results in the user taken to a connection error page

### ISSUE THREAD

**Issue by xortim** [Tautulli/Tautulli#891]
**Version:** 1.4.14

**Branch:** master

**Commit hash:**    86a9230da8a9ab1af18eacb07a9fd7086437305c

**Operating system:** CentOS 7 (Linux 3.10.0-327.22.2.el7.x86_64)

**Python version:** 2.7.5

**What you did?** Changed HTTP Root setting

**What happened?** Modal prompt about restarting. Agreed to restart. After restart timeout, browser was refreshed to the original location.

**What you expected?** After the restart timer, the application should take the user to the new/correct HOST, Port, and HTTP Root values.

**How can we reproduce your issue?** Change HTTP Root setting. Issue restart via the prompt. Let the timer countdown. Browser will refresh to the original context root, an error page is shown.

**What are your (relevant) settings?** Complete OOTB/default settings. Change only the HTTP Root setting.

**Link to logs:** No error was produced by the application. Simply a UX issue.

**Comment by JonnyWong16** [comment]
Thanks for catching this.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.15.
