### ISSUE TITLE
Suddenly not updating anymore

### ISSUE THREAD

**Issue by ofurpesi** [Tautulli/Tautulli#892]
Hi there

![image](https://cloud.githubusercontent.com/assets/8067418/19828906/be56e27e-9dc2-11e6-98a8-0c6ae1f2d86b.png)

This is the error i am getting when i try to update Plexpy.

Any ideas?

**Comment by JonnyWong16** [comment]
Please read the FAQ.

**Comment by ofurpesi** [comment]
All fixed by deleting the folders in the Update folder and running the update process again
