### ISSUE TITLE
GeoLite2 Database failing to install

### ISSUE THREAD

**Issue by heartisall** [Tautulli/Tautulli#894]
**Version:** 1.4.14

**Branch:**

**Commit hash:**

**Operating system:** Windows Server 2012R2

**Python version:**	2.7.12

**What you did?** Tried to install GeoLite2 Database from the Help/Info page, I did already search and tried the **hard refresh of the browser/cache removal**. It didn't fix the problem.

**What happened?**
I received a red Toast notication stating that it failed to install. I then receive this in in the Log

2016-10-31 15:18:05 - ERROR   :: CP Server Thread-7 : PlexPy Helpers :: Failed to download GeoLite2 gzip file from MaxMind: ('http error', 403, 'Forbidden', <httplib.HTTPMessage instance at 0x045EC148>)

**What are your (relevant) settings?**
This install is on a separate VM on a different host then my plex server. It is on the same network however. Everything else is running fine. I am running my own certificate so that this is accessible via HTTPS if it makes any difference. Other than that the install is pretty straightforward.
Plex is also on Server 2012 R2, Plex version - 1.2.4.2949 
**Link to logs:**

[plexpy.docx](https://github.com/JonnyWong16/plexpy/files/564151/plexpy.docx)

**Comment by JonnyWong16** [comment]
Can you download the database manually from inside the VM? 

http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz

**Comment by heartisall** [comment]
Yes, Is there a certain place I can put it manually so that Plex.py will see it?

**Comment by JonnyWong16** [comment]
Shutdown PlexPy and edit the config.ini file. Set `geoip_db` to the full path to the file. 

E.g. `geoip_db = C:\PlexPy\GeoLite2-City.mmdb`

**Comment by heartisall** [comment]
Worked like a charm, thanks for your help. Great job on this, it's incredibly useful.
