### ISSUE TITLE
SQLite error in Plex Media Server Logs

### ISSUE THREAD

**Issue by xorinzor** [Tautulli/Tautulli#896]
**Version:**
1.4.14 
**Branch:**
master
**Commit hash:**
86a9230da8a9ab1af18eacb07a9fd7086437305c

**Operating system:**
Ubuntu Server 14.04

**Python version:**
2.7.12

**Problem:**
In the Logs section at `Plex Media Server Logs` I have a bunch of these errors:
SQLITE3:0x10, 17, statement aborts at 58: [select * from metadata_items limit 1] database schema has changed

Is this from PlexPy or Plex?

**Comment by JonnyWong16** [comment]
This isn't a PlexPy issue. Those are your Plex logs.
