### ISSUE TITLE
API reporting incorrect result and message for restart command

### ISSUE THREAD

**Issue by jxer** [Tautulli/Tautulli#897]
can you provide an example of how to restart  or shutdown plexpy from cli via apikey

curl -k "https://ip:port/api/v2?apikey=c8af1838a139355437da9f5e254f83d4&cmd=restart"
{"response": {"message": null, "data": {}, "result": "error"}}

**Comment by JonnyWong16** [comment]
I think the `message` and `result` are just reporting the wrong info. PlexPy should still restart.

There is no shutdown command.

**Comment by jxer** [comment]
how can i shut it down gracefully from command line?
this is my start command
/opt/plexpy/PlexPy.py --quiet --daemon --nolaunch --config /opt/plexpy/config.ini --datadir /opt/plexpy --pidfile="/opt/plexpy/plexpy.pid

**Comment by jxer** [comment]
yes restart is actually working, can you please provide shutdown via api?

**Comment by JonnyWong16** [comment]
No, I don't want people accidentally shutting down PlexPy _and not being able to start it back up_.

You can shutdown gracefully from the command line with 

```
kill {pid}
```

You can get the `pid` from the `pidfile` automatically with

```
kill `cat /opt/plexpy/plexpy.pid`
```

**Comment by jxer** [comment]
no offense but how do you accidentally send a api call?

**Comment by JonnyWong16** [comment]
It's not so much accidentally sending a shutdown command, it's more that you wouldn't be able to start PlexPy after shutting down with the API because PlexPy isn't running.

On the other hand, if you can shutdown with the command line, then you can also start with the command line.

**Comment by Hellowlol** [comment]
It's a bug in the API. I forgot to change the result type in to a private variable. I'll send a pr to fix this

**Comment by JonnyWong16** [comment]
^ Yep. I realized the same thing.

I fixed the message but not the result type https://github.com/JonnyWong16/plexpy/commit/8b0959aa699a3d82f17aa422c191598e05bbe56a

**Comment by Hellowlol** [comment]
Fixed it https://github.com/JonnyWong16/plexpy/pull/898

**Comment by JonnyWong16** [comment]
Fixed in v1.4.15.
