### ISSUE TITLE
Update to Imgur's API

### ISSUE THREAD

**Issue by alneven** [Tautulli/Tautulli#899]
> We’re contacting you with an important update to the Imgur API. Starting on December 1, 2016, Imgur messaging will no longer be available in the API. Your client will be able to access older archived messages in read-only mode for a short time, but no new messages will be sent or received.

hi guys,
how this affect the posters?
I guess we have to look for another image share services, am I right?

Thanks!

**Comment by JonnyWong16** [comment]
It doesn't affect anything.
