### ISSUE TITLE
PlexPy Graphs Play Totals showing Invalid Dates

### ISSUE THREAD

**Issue by izeen** [Tautulli/Tautulli#90]
![capture](https://cloud.githubusercontent.com/assets/13767120/9328615/7920e428-45aa-11e5-9076-74027d216022.PNG)

This worked fine previously and showed correct months, think it happend after the commit where you fixed the graphs for Safari/iOS.

**Comment by drzoidberg33** [comment]
Seems to be a Safari specific bug. I'll look into it.

**Comment by drzoidberg33** [comment]
This was fixed in last release. Closing.
