### ISSUE TITLE
Authentication does not work with special chars

### ISSUE THREAD

**Issue by jwillmer** [Tautulli/Tautulli#900]
I used a password that had a `ü` as character for my plex account and plexpy was not able to fetch the auth token. After changing the password and removing special chars it works.

**Comment by Hellowlol** [comment]
Should be fixed in https://github.com/JonnyWong16/plexpy/commit/59ce3404c9deca625013a535aec738c7a969124b

**Comment by JonnyWong16** [comment]
Fixed in v1.4.15.
