### ISSUE TITLE
Facebook notifications not working, no errors in log

### ISSUE THREAD

**Issue by astrodad** [Tautulli/Tautulli#901]
**Version:**
VERSION 1.4.14

**Branch:**
master

**Commit hash:**
86a9230da8a9ab1af18eacb07a9fd7086437305c

**Operating system:**
macOS Sierra

**Python version:**
2.7.10 (default, Jul 30 2016, 18:31:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

**What you did?**
Used the instructions to set up a Facebook app and a Facebook group. Authorized and when I issue the test, it indicates that it's successful, but nothing posts to Facebook. I added a trigger for Recently Added and the logs indicates that the notification was sent, but nothing is posted.

2016-11-07 18:56:01	INFO	PlexPy Notifiers :: Facebook notification sent.
2016-11-07 18:56:00	DEBUG	Sending test Facebook notification.

**Comment by astrodad** [comment]
I also just tried re-creating the app, and creating a new group, with the same results.

**Comment by JonnyWong16** [comment]
Somewhere along the line a setting is wrong.

Did you get the "Key verification successful" message?

Did you make sure you have the correct permissions?

> When allowing PlexPy to access your Facebook account, you must select **Public** or **Friends** for the app visibility permissions. Selecting **Only Me** will not work.

Did you make sure you have the correct group ID?

> The Facebook Group ID you've used is incorrect. If your group has a named URL, you'll need to find the ID number using a tool like lookup-id.com. You'll need to make your group open in order for that tool to work. You can change the group back to closed/secret once you have the ID number.

**Comment by astrodad** [comment]
Yes, I got the "Key Verification Successful" message.  I selected Friends for app visibility settings. For the group ID, when I went through the set up the first time and copy and pasted the ID in the group URL, it didn't take. I read somewhere else that it required the URL, not the ID. 

But just now I updated the settings to include just the ID, and it works. Thanks!
