### ISSUE TITLE
Change Plex Update Check Interval

### ISSUE THREAD

**Issue by hcuk94** [Tautulli/Tautulli#903]
Is it possible to change the interval that PlexPy checks for new Plex updates?

For example today I was notified of an update first by the banner in Plex rather than by PlexPy notifying me which is what I'd rather.

Would appreciate if you could let me know how I do this if possible.

Thanks and, keep up the great work, love PlexPy.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy#feature-requests
