### ISSUE TITLE
Facebook notifications wont work

### ISSUE THREAD

**Issue by ufo56** [Tautulli/Tautulli#907]
Created app like said in instructions.

When i try to authorize app i get http://i.imgur.com/0iAPEjo.png
Seems to be some permissions are missing from FB app...
Even if i press "continue as Name" then only test message gets posted to group. If i add something to library then no post

http://i.imgur.com/N7zJ6rn.png

2016-11-18 11:04:40	INFO	PlexPy Notifiers :: Facebook notification sent.
2016-11-18 11:04:39	DEBUG	Sending test Facebook notification.
2016-11-18 11:04:39	INFO	PlexPy Config :: Writing configuration to file
2016-11-18 11:04:34	INFO	PlexPy Config :: Writing configuration to file
2016-11-18 11:04:33	INFO	PlexPy Notifiers :: Requesting access token from Facebook

**Comment by JonnyWong16** [comment]
The "Submit for Login Review" message is fine. Just ignore it.

Do you have "Enable Recently Added Notifications" checked under Settings > Notifications?

**Comment by ufo56** [comment]
Yes, i added even screenshot :)

**Comment by JonnyWong16** [comment]
No you didn't. Settings > Notifications.

**Comment by ufo56** [comment]
http://i.imgur.com/j5u8tdP.png

**Comment by manincubicle** [comment]
Love this app, great work! I have Facebook notifications setup including posters and seems to be working great for me specifically! However, I am the only one who sees the posts on the group wall. No one else in my Facebook group is able to see the "recently added" notification posts. I have my 'App visibility and post audience' set to "Friends" and everyone in the group is my friend. 

Do you have any suggestions as to how to give them viability to the notifications within the group wall? I must be missing a setting somewhere.

Thank you!
