### ISSUE TITLE
TopLevelLookupException

### ISSUE THREAD

**Issue by crack00r** [Tautulli/Tautulli#908]
latest version
WIndows 2012 Server

Works for 2 days, then this

Error !

TopLevelLookupException: Cant locate template for uri 'welcome.html'

return self._load(srcfile, uri) else: raise exceptions.TopLevelLookupException( "Cant locate template for uri %r" % uri) def adjust_uri(self, uri, relativeto): """Adjust the given ``uri`` based on the given relative URI.""" key = (uri, relativeto)
C:\Users\Administrator\Desktop\JonnyWong16-plexpy-v1.4.15-0-gef85fba\JonnyWong16-plexpy-ef85fba\lib/mako\lookup.py, line 248:
"Cant locate template for uri %r" % uri)
C:\Users\Administrator\Desktop\JonnyWong16-plexpy-v1.4.15-0-gef85fba\JonnyWong16-plexpy-ef85fba\plexpy\webserve.py, line 68:
template = _hplookup.get_template(templatename)

**Comment by JonnyWong16** [comment]
Make sure you don't have files missing in the `data/interfaces/default` directory.

**Comment by crack00r** [comment]
i dont change anything, it just stop working :D

**Comment by crack00r** [comment]
i extract now the zip over the folder again, and now its back again... curios

**Comment by crack00r** [comment]
same again, after 1-2h

Error !
TOPLEVELLOOKUPEXCEPTION: CANT LOCATE TEMPLATE FOR URI 'CURRENT_ACTIVITY_HEADER.HTML'

return self._load(srcfile, uri) else: raise exceptions.TopLevelLookupException( "Cant locate template for uri %r" % uri) def adjust_uri(self, uri, relativeto): """Adjust the given `uri` based on the given relative URI.""" key = (uri, relativeto)
C:\Users\Administrator\Desktop\JonnyWong16-plexpy-v1.4.15-0-gef85fba\JonnyWong16-plexpy-ef85fba\lib/mako\lookup.py, line 248:
"Cant locate template for uri %r" % uri)
C:\Users\Administrator\Desktop\JonnyWong16-plexpy-v1.4.15-0-gef85fba\JonnyWong16-plexpy-ef85fba\plexpy\webserve.py, line 68:
template = _hplookup.get_template(templatename)
Nothing is currently being played.
WATCH STATISTICS   Last 30 days

No stats to show for the selected period.

**Comment by crack00r** [comment]
Error !

TopLevelLookupException: Cant locate template for uri 'index.html'

return self._load(srcfile, uri) else: raise exceptions.TopLevelLookupException( "Cant locate template for uri %r" % uri) def adjust_uri(self, uri, relativeto): """Adjust the given `uri` based on the given relative URI.""" key = (uri, relativeto)
C:\Users\Administrator\Desktop\JonnyWong16-plexpy-v1.4.15-0-gef85fba\JonnyWong16-plexpy-ef85fba\lib/mako\lookup.py, line 248:
"Cant locate template for uri %r" % uri)
C:\Users\Administrator\Desktop\JonnyWong16-plexpy-v1.4.15-0-gef85fba\JonnyWong16-plexpy-ef85fba\plexpy\webserve.py, line 68:
template = _hplookup.get_template(templatename)

**Comment by JonnyWong16** [comment]
Install to a different location. Check your disk for errors.

I don't think this is an issue with PlexPy. Your server keeps losing the files. Bad disk, errors, permissions, etc.
