### ISSUE TITLE
401 Unauthorized Connection To Plex

### ISSUE THREAD

**Issue by dcplaya** [Tautulli/Tautulli#91]
I have PlexPy running on a seperate server than my Plex server. I have entered in the IP address and the test connection reports successful. I can get a valid authentication token as well. 

The PlexPy logs are reporting 

> > 2015-08-18 09:04:12   WARNING Unable to parse XML for get_recently_added.
> > 2015-08-18 09:04:12 WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=7 with error [Errno 111] Connection refused
> > 2015-08-18 09:04:12 WARNING Unable to retrieve data.
> > 2015-08-18 09:04:12 WARNING Unable to parse XML for get_sessions.
> > 2015-08-18 09:04:12 WARNING Failed to access uri endpoint /status/sessions with error [Errno 111] Connection refused
> > 2015-08-18 09:04:12 WARNING Unable to retrieve data.
> > 2015-08-18 09:04:12 WARNING Unable to parse XML for get_sessions.
> > 2015-08-18 09:04:12 WARNING Failed to access uri endpoint /status/sessions with error [Errno 111] Connection refused

Both server are running CentOS7 and both servers have the firewalld disabled with no different results. 

If I try going to 

> > http://192.168.1.180:32400/library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=7

I get a "401 unauthorized" response

**Comment by drzoidberg33** [comment]
The 401 error is correct when you open it in your browser as I don't include your Plex token in the logs, so without that it wouldn't allow you to do access the page unauthorised.

Are you using the Force SSL option by any chance? If so try and disable this - it doesn't quite work well with local connections yet.

**Comment by dcplaya** [comment]
I may have inadvertently fixed it.  I was trying to update to the dev branch of git. My normal routine didnt seem to work so I deleted my PlexPy folder and did a 

> git clone -b dev http://your.github.link

Now my version is showing v1.1.2 and it is now connecting to Plex correctly. Before my version was commit ID number. Not really sure what happened.

**Comment by drzoidberg33** [comment]
The version numbering is a new addition that's not yet released to the master versions.

Did you have Force SSL enabled though? If so that could have been the issue.

Just be aware that using the dev branch means you get all the latest stuff but also means that what you get is largely untested and can break things.

**Comment by dcplaya** [comment]
Force SSL works either way (SSL is a lot slower to load recently added images though).  I figured out the problem.  The option 

> Remote Server
> was checked. I understood it as a server that is not the same as what PlexPy is running on. Not external to my LAN.

**Comment by drzoidberg33** [comment]
Thanks.

Yes remote means not on your network. It does mention this under the checkbox option.

I also noticed that using SSL with local connections is really slow, if you use it on a remote server it's fine however. Not sure what's going on there, looks like it's the name resolution taking long.

**Comment by drzoidberg33** [comment]
I'm closing this issue as it's been resolved.
