### ISSUE TITLE
Hellowlol Script - Throttle NZB Client - AttributeError

### ISSUE THREAD

**Issue by sugarfunk** [Tautulli/Tautulli#911]
I couldn't determine how to contact @Hellowlol on this, but using the Throttle NZB Client, Python is throwing an attributeerror. Any guidance? 

	PlexPy Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "G:\PlexPy Scripts\throttle_nzbclient.py", line 202, in 
            if p.streamcount: 
    AttributeError: 'Namespace' object has no attribute 'streamcount'

**Comment by JonnyWong16** [comment]
You can comment at the bottom of the script's page: https://gist.github.com/Hellowlol/a5d0cab4bde185b38404
