### ISSUE TITLE
Error when enabling HTTPS in Plex (not HTTPS in plex.py)

### ISSUE THREAD

**Issue by xAhlen** [Tautulli/Tautulli#917]
Hey.

I'm trying to activate HTTPS "Required" in plex and not "Preferred" but when i do plex.py refuses to start, here's my log.

http://pastebin.com/HVTMmzm2

 
**Version:**
1.4.16

**Branch:**
master

**Commit hash:**
	3742f33d08feb6fb15e74af6318185230205006f

**Operating system:**
Windows 10 x64

**Python version:**
2.7

**What you did?**
Choose HTTPS Required instead of Preferred in the Plex settings.

**What happened?**
It will not start

**What you expected?**
That it would work.

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
http://pastebin.com/HVTMmzm2

**Comment by JonnyWong16** [comment]
Are you sure it's the HTTPS setting that's causing it?

It's failing on retrieving the name of your server:
```
2016-12-06 00:14:27 - INFO :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
```
Do you have a special character in your server name?

**Comment by xAhlen** [comment]
Thx for the quick response. Yes because if i switch back to preferred it starts right away. the server name is andromeda, All lower-case and no special characters

**Comment by JonnyWong16** [comment]
Did you also enable "Use SSL" in the PlexPy settings?

**Comment by xAhlen** [comment]
Wow... i can't believe i missed that, thx for the help and sorry for wasting your time xD.

BTW love your work :) 👍
