### ISSUE TITLE
Does PlexPy show stats for photos viewed?

### ISSUE THREAD

**Issue by tripaphonic** [Tautulli/Tautulli#918]
Hey there.  Great app.  I installed PlexPy a few days ago and just not got the time to dig into the settings and configuration.  PlexPy is a very robust and powerful tool.  Thanks for developing it and continuing to support it.

My question is fairly straight forward and may be answered somewhere already, I couldn't find it if it is. 

I am an amature+ photographer & as such I have numerous photo libraries in Plex, some of which I share with friends, family, and clients in order to provide a safe environment to control my copyrighted material.  I have not been able to verify whether or not PlexPy harvests statistics on when photo folder or the photos themselves are opened.  This would be very valuable to me ( and probably others ) because I often have people ask me about photos I've taken or video I've edited.  If there is a way to see when a photo folder is accessed as well as which photos were opened I would feel much more aware.  Also, having the ability to 'flag' a specific folder or maybe photos themselves to fire off an SMS or email letting me or the 'owner' know when it was accessed and by whom it would provide so much more insight into what specific photos people were drawn towards, opened first, opened twice, downloaded, shared, etc.  LOL.  

I hope this feature already exists.  Thanks again.

**Comment by JonnyWong16** [comment]
No, photo viewing is not logged. 

Photo viewing will show up on the homepage under current activity though.

**Comment by tripaphonic** [comment]
Thanks for the prompt respond Jonny.  I noticed how when I was viewing a photo it was under current activity.  So it's being reported on but not logged?  How difficult would it be to write that current activity to a log so historical data could be pulled up?  I assume photos as a category is excluded from logging but does the data exist already somewhere?

Thanks.

**Comment by JonnyWong16** [comment]
Photos are excluded from logging. It can be done, with a lot of work, but I don't think it would be worth the time spent to implement this.

**Comment by tripaphonic** [comment]
Thanks again for the reply.

I'm not the best programmer by far but would the photos not be identical to how the videos were handled as far as logging, only less work due to the fact that there is only one static image rather than a random length video, different codec as well as different containers to consider?  

I guess I'm looking at it from the standpoint of being able to pull up historical data or an audit trail that could be used in more of a professional or business capacity.  I would much rather use Plex with PlexPy on my own storage to share my photos than the commercialized social media apps strewn across the net.  

Do you know of any other solutions or is there a possibility you may look into expanding PlexPy to include this functionality?

Thanks again.

**Comment by JonnyWong16** [comment]
I don't know of any other tools that would satisfy what you are looking for.

It's possible that I can add this in the future, but there are other things that I am working on. It would be many, many, months before this will make it in.

**Comment by tripaphonic** [comment]
Thanks again for the reply Jonny. 

I had a thought last night while looking for a solution to do what I need ... do you think by changing the photos to have a video extension rather than a photo extention would "trick" PlexPy into thinking it was a video and thereby report it as it does other video files?  By changing the container it may force the result I'm looking for.  I may have to convert the photo files to video files so the container is an actual video container but do you think that could work?  Thought I'd throw that out there.

**Comment by JonnyWong16** [comment]
That sounds like a bad idea...

**Comment by tripaphonic** [comment]
How so?

**Comment by JonnyWong16** [comment]
Sure you can try it, but it has to be a "video" library in Plex. Media type isn't determined by file extensions.
