### ISSUE TITLE
Plex Server IP Address Doesn't Accept Hostnames

### ISSUE THREAD

**Issue by dcplaya** [Tautulli/Tautulli#92]
I have a working DNS server for my internal servers. I am able to ping my Plex server using its hostname. But if I enter the hostname into PlexPy it does not pass the connection test.

**Comment by drzoidberg33** [comment]
It does support hostnames, so your problem probably lies somewhere else.

What OS is PlexPy running on?

**Comment by dcplaya** [comment]
CentOS7

But you are correct. This 1 server is having DNS issues. All the rest are working as expected and I tested ping from a different server.
