### ISSUE TITLE
Set proctitle

### ISSUE THREAD

**Issue by depraved22** [Tautulli/Tautulli#920]
I was trying to get the proctitle to work so I can do some monitoring off the process name that is setup.

Based on the way it starts up now, it has the process name as "python" so I made one change to the startup with python installed with the setproctitle package:

felix    29552     1  0 09:34 ?        00:00:00 /usr/bin/python /opt/plexpy/PlexPy.py --quiet --daemon --nolaunch --config /opt/plexpy/config.ini --datadir /opt/plexpy
root     32258 29005  0 09:38 pts/2    00:00:00 grep plexpy
root@plex: plexpy# cd /proc
root@plex: proc# cd 29552
root@plex: 29552# cat status
Name:	PlexPy.py
State:	S (sleeping)
Tgid:	29552

That changes the name from "python" to PlexPy.py.

So I changed the startup to just "#!/usr/bin/python" at the top of the script and it honors the title then. Is there a better way to do that that you can include?

**Comment by JonnyWong16** [comment]
I honestly have no idea what you are doing.

**Comment by depraved22** [comment]
I'm trying to get the process name to not show as python but as PlexPy.py.

```
# ps -e | grep Plex.y
29552 ?        00:00:05 PlexPy.py
```

I changed it so you can use such commands to monitor, pkill, etc by process name instead of just having python.

The code you have to start up it up does an 'exec python':

```
#!/bin/sh
''''which python    >/dev/null 2>&1 && exec python    "$0" "$@" # '''
''''which python2   >/dev/null 2>&1 && exec python2   "$0" "$@" # '''
''''which python2.7 >/dev/null 2>&1 && exec python2.7 "$0" "$@" # '''
''''exec echo "Error: Python not found!" # '''
```

I changed the exec part to just launch /usr/bin/python:


```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```


So if I run a ps -e command, I get the name of the python running:

```
# ps -e | grep Plex.y
29552 ?        00:00:05 PlexPy.py
```

instead of something like:
```
 ps -e | grep python
13319 ?        00:00:12 python
```

That way, I can monitor / alarm/ etc on the specific thing running python of just monitoring python? Does that explain it a little better?
