### ISSUE TITLE
ChangeTip DIscontinuation

### ISSUE THREAD

**Issue by praeluceo** [Tautulli/Tautulli#921]
**Software Configuration:**
VERSION 1.4.16  Changelog

PLEXPY CONFIGURATION

Git Branch:	master
Git Commit Hash:	3742f33d08feb6fb15e74af6318185230205006f
Configuration File:	/opt/plexpy/config.ini
Database File:	/opt/plexpy/plexpy.db
Log File:	/opt/plexpy/logs/plexpy.log
Backup Directory:	/opt/plexpy/backups
Cache Directory:	/opt/plexpy/cache
GeoLite2 Database:	/opt/plexpy/GeoLite2-City.mmdb | Reinstall / Update | Uninstall
Arguments:	['--quiet', '--daemon', '--nolaunch', '--pidfile=/var/run/plexpy/plexpy.pid', '--datadir=/opt/plexpy']
Platform:	Linux 3.19.0-75-generic
Python Version:	2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

**Issue Description:**
As of the above release of plexpy, there is a PayPal donate link, and a Bitcoin donate link. The Bitcoin donate link goes to https://swiftpanda16.tip.me.

However, as of last month, ChangeTip has discontinued their service, and will be closing/cashing out accounts over the next couple of months: https://www.reddit.com/r/changetip/comments/5dn3rc/changetip_shutting_down/

You may want to convert that link to a Bitcoin wallet you control directly, or to something managed externally. Unfortunately, there aren't many good alternatives to ChangeTip, but Coinbase previously had a tipping infrastructure and may add it again, but in the meantime you could create a Coinbase account, and link to that via plexpy (as an example: https://www.coinbase.com/praeluceo). Please don't just remove the Bitcoin tipping function however! That would make me a SadPanda16!

**Comment by JonnyWong16** [comment]
Thanks. I'm already aware of this and I have already set up a [coinbase link](https://www.coinbase.com/JonnyWong16). I just haven't updated the link in PlexPy yet.

**Comment by praeluceo** [comment]
Awesome, I'm glad to hear you hadn't decided to remove the Bitcoin donation option! And thanks for the quick response to issues!
