### ISSUE TITLE
2 Concurrent Streams?????

### ISSUE THREAD

**Issue by apperrault** [Tautulli/Tautulli#922]
I am not sure what is going on.  For some reason, when one of my local users (my daughters account) starts a stream, I get a notification that they have 2 concurrent streams.  I have 5 other local users, and I never get this notification for any of those users.  It isn't a major issue, but it kind of drives me nuts.

I am not sure what logs I can provide or honestly where to find them, but I can provide them if necessary.

System: Windows 2012R2
Version of PlexPY: Most recent version in the releases area

What else do you need

thanks everyone

app

**Comment by JonnyWong16** [comment]
Settings > Extra Settings > Flush Temporary Sessions.
