### ISSUE TITLE
Notifications Stopped - IFTTT and PushBullet

### ISSUE THREAD

**Issue by BadBadger76** [Tautulli/Tautulli#923]
At some point in the last few days notifications have stopped. I use both IFTTT and PushBullet.

I can go into IFTTT notification settings and send a test notification with works and comes up on iphone as planned. However when a prescribed Plexpy event happens no notification is sent.

When I went into PushBullet to check the settings it just says:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Powered by CherryPy 5.1.0

As a test I did a complete reinstall of Plexpy and all looked good when I opened the PushBullet settings, but when I tried to enter a data I got the 500 internal server error again and the settings window disappeared again. Back to the same problem.

I tried updating all libraries, users, flushing temp sessions.

It seems I am not the only person with the same issue
https://www.reddit.com/r/PleX/comments/5h80s0/plexpypushbullet_issue/

Any thoughts on this.

Thanks

Git Branch:	master
Git Commit Hash:	3742f33d08feb6fb15e74af6318185230205006f
Configuration File:	D:\Plex\PlexPy\config.ini
Database File:	D:\Plex\PlexPy\plexpy.db
Log File:	D:\Plex\PlexPy\logs\plexpy.log
Backup Directory:	D:\Plex\PlexPy\backups
Cache Directory:	D:\Plex\PlexPy\cache
Platform:	Windows 8
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by JonnyWong16** [comment]
Post your full logs please.

Also, can you start PlexPy in dev mode to catch the error in the settings?

`python PlexPy.py --dev`

**Comment by theCheek** [comment]
I've got the same issue since Tuesday also. 
is --dev the same as running it with -d? I ask because I'm on a seedbox and manually running plexpy is a bit tricky, but i noticed the process running with -d

If so, I attach the logs, but as @BadBadger76 points out there doesn't seem to be any reference to the error
[plexpy.txt](https://github.com/JonnyWong16/plexpy/files/642245/plexpy.txt)

The logs were pulled after restarting plexpy, then trying to select the configuration of Pushbullet. The error in browser was:
```500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.````

**Comment by JonnyWong16** [comment]
No, `-d` is not the same as `--dev`.

**Comment by BadBadger76** [comment]
This is the output I get then going into PushBullet settings using Dev mode.

Traceback (most recent call last):
  File "d:\Plex\PlexPy\lib/cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "d:\Plex\PlexPy\lib/cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "d:\Plex\PlexPy\lib/cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "d:\Plex\PlexPy\plexpy\webserve.py", line 2848, in get_notification_agent_config
    config = notifiers.get_notification_agent_config(agent_id=agent_id)
  File "d:\Plex\PlexPy\plexpy\notifiers.py", line 505, in get_notification_agent_config
    return pushbullet.return_config_options()
  File "d:\Plex\PlexPy\plexpy\notifiers.py", line 1192, in return_config_options
    'select_options': self.get_devices()
  File "d:\Plex\PlexPy\plexpy\notifiers.py", line 1158, in get_devices
    'Authorization': 'Basic %s' % base64.b64encode(self.apikey + ":")})
  File "C:\Python27\lib\httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 844, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 806, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1198, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "C:\Python27\lib\ssl.py", line 392, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\ssl.py", line 148, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 310, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by BadBadger76** [comment]
As @theCheek said, nothing is showing up in the log file

**Comment by theCheek** [comment]
so I have a Plex Channel running called PlexRequests.bundle (https://github.com/ngovil21/PlexRequestChannel.bundle) which seems to be getting the same issue. It must be something to do with the implementation of httplib, but this is beyond my scope of understanding.
The logs from plexrequests do give a bit more info on the error if it helps:

```
2016-12-10 09:08:50,151 (7f49eeb6c700) :  DEBUG (networking:166) - Requesting 'https://api.pushbullet.com/v2/pushes'
2016-12-10 09:08:50,165 (7f49eeb6c700) :  ERROR (Session:2460) - Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PlexRequestChannel.bundle/Contents/Code/Session.py", line 2452, in notifyRequest
    summary = tv['summary'] + "<br>\n"
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PlexRequestChannel.bundle/Contents/Code/Session.py", line 2513, in sendPushBullet
    return HTTP.Request(PUSHBULLET_API_URL + "pushes", data=values, headers=api_header)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 194, in Request
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] _ssl.c:504: EOF occurred in violation of protocol>
```

**Comment by jasonlyle88** [comment]
I get more or less the same error in dev mode.  The main differences are line numbers.  I am running PlexPy 1.4.16 with Python 2.7.6 on Ubuntu 14.04

```
Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/plexpy/plexpy/webserve.py", line 2848, in get_notification_agent_config
    config = notifiers.get_notification_agent_config(agent_id=agent_id)
  File "/opt/plexpy/plexpy/notifiers.py", line 505, in get_notification_agent_config
    return pushbullet.return_config_options()
  File "/opt/plexpy/plexpy/notifiers.py", line 1192, in return_config_options
    'select_options': self.get_devices()
  File "/opt/plexpy/plexpy/notifiers.py", line 1158, in get_devices
    'Authorization': 'Basic %s' % base64.b64encode(self.apikey + ":")})
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
```

**Comment by JonnyWong16** [comment]
Can you guys update python to 2.7.12?

**Comment by jasonlyle88** [comment]
I'm not sure how to do that properly as Ubuntu 14.04 needs python 2.7.6 for the system.  If I were to install a separate python version, is it enough to simply run PlexPy.py with the new executable? Or does a VirtualEnv need to be set up?  I have very little experience with Python and VirtualEnv, so I am not quite sure the best way to do this.

**Comment by AngryNoodlez** [comment]
Hi,

I can confirm I also have this issue, started around the same time as the poster but not sure what's changed. I'm running it on Windows Server 2012 R2 though. I've updated to Python 2.7.12 but unfortunately this hasn't cured the issue.

Anything further I could collect for diagnostics?

**Comment by JonnyWong16** [comment]
Are you sure PlexPy is running with Python 2.7.12?

There are 3 people here that have confirmed that updating Python fixed the problem. https://forums.plex.tv/discussion/comment/1319527/#Comment_1319527

**Comment by AngryNoodlez** [comment]
Hi,

Definitely sure!

Here's the version listed on the Help & Info page on PlexPy (v1.4.16).

Git Branch:  master
Git Commit Hash:  69c94eb3155a5d110fdd7ade34c472117bd0211d
Python Version:  2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]


I've had a look and the error in the logs appears to be certificate related, though I'm not sure where it's connecting to test the SSL is trusted. Does Python use the local SSL Store for checking certificate chains?


```
Uncaught exception: Traceback (most recent call last):
    File "C:\Apps\PlexPy\plexpy\logger.py", line 270, in new_run
        old_run(*args, **kwargs)
    File "C:\Python27\lib\threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
    File "C:\Apps\PlexPy\plexpy\notification_handler.py", line 391, in notify_timeline
        metadata=metadata)
    File "C:\Apps\PlexPy\plexpy\notifiers.py", line 575, in send_notification
        return pushbullet.notify(message=body, subject=subject)
    File "C:\Apps\PlexPy\plexpy\notifiers.py", line 1127, in notify
        body=json.dumps(data))
    File "C:\Python27\lib\httplib.py", line 1057, in request
        self._send_request(method, url, body, headers)
    File "C:\Python27\lib\httplib.py", line 1097, in _send_request
        self.endheaders(body)
    File "C:\Python27\lib\httplib.py", line 1053, in endheaders
        self._send_output(message_body)
    File "C:\Python27\lib\httplib.py", line 897, in _send_output
        self.send(msg)
    File "C:\Python27\lib\httplib.py", line 859, in send
        self.connect()
    File "C:\Python27\lib\httplib.py", line 1278, in connect
        server_hostname=server_hostname)
    File "C:\Python27\lib\ssl.py", line 353, in wrap_socket
        _context=self)
    File "C:\Python27\lib\ssl.py", line 601, in __init__
        self.do_handshake()
    File "C:\Python27\lib\ssl.py", line 830, in do_handshake
        self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by AngryNoodlez** [comment]
Hi,

Not entirely sure what changed, but the errors appear to have subsided and everything is working OK again.

Thanks again, let's hope it doesn't stop!

**Comment by theCheek** [comment]
@AngryNoodlez can you check your python version again? Maybe something changed between when you had the error and when it stopped being a problem.

@JonnyWong16 If the python version really is the issue then I guess I'm stuck. I've asked my seedbox owners to downgrade Python but they said they can't as they upgraded it to 2.7.6 as part of a security upgrade and said they don't do custom compiles to previous versions.

**Comment by JonnyWong16** [comment]
2.7.12 is an **_upgrade_** not a *downgrade*.

**Comment by theCheek** [comment]
Sorry for my ignorance, but isn't 2.7.6 a higher number than 2.7.12? !!

**Comment by JonnyWong16** [comment]
http://semver.org/

`.6` is *6* not *60*. 12 > 6

**Comment by mjlehrke** [comment]
Also encountered this bug.  I upgraded to Python 2.7.12 and also deleted the Pushbullet section from the config file.

It allowed me to then open the Pushbullet settings, however, the moment I pasted in the access token from Pushbullet it gave the 500 error again.

**Comment by theCheek** [comment]
@JonnyWong16 ok thanks for the clarification and patience! 
I guess I'm stuck for now then, hopefully my seedbox will eventually upgrade to the latest version, and that this is indeed the root cause. @mjlehrke addition makes me worried that there is more to this issue than meets the eye though!

**Comment by BadBadger76** [comment]
OK, so I updated to 2.7.12 and it fixed the 500 error. I can now send test notifications and it also sends the correct notifications from Plexpy. As part of this error finding I also did a reinstall of Plexpy so this may help solve other people who continue to still have this error. Thanks for your support on this @JonnyWong16 and for the great tool that is Plexpy.

**Comment by jasonlyle88** [comment]
Upgrading python fixed this for me as well

**Comment by a5m0** [comment]
still broken for me - ubuntu lts 14.04 python 2.7.6

**Comment by JonnyWong16** [comment]
@a5m0 Please read above.

**Comment by winbergoscar0** [comment]
Just installed with python 2.7.13, and got the "500 internal error" when trying to open pushbullet notification settings :(

**Comment by mjlehrke** [comment]
Upgraded to python 2.7.13 and subsequently re-installed PlexPy.  Once a Pushbullet API key is entered into the field it throws the 500 error.  Upgrading or re-installing did not help.

**Comment by citizen0100** [comment]
I've got the same issue, updated to 2.7.13 which didn't help so downgraded to 2.7.12 which also didn't work. I've posted some info here: https://www.reddit.com/r/PleX/comments/5l9y5e/plexpy_and_pushbullet_500_internal_server_error?sort=confidence

**Comment by pvanhouten** [comment]
This probably isn't the right solution, but you can fix the pushbullet issue by doing a couple things.  First, it looks like the notifiers in plexpy is setup to use basic auth with pushbullet which their API doesn't document supporting.  They want an "Access-Token" header instead (https://docs.pushbullet.com/#api-quick-start) (though basic auth could very well still work).  It also seems like the SSL cert they're using either isn't in the python default ssl cert bundle or something so it's failing validation.  I'm no SSL expert, but that's my closest guess.  I did update my plexpy/notifiers.py file with some tweaks that should fix the issue if you're using API access tokens.  It also ignores bad SSL certs.  The tweaks are in this gist:

https://gist.github.com/pvanhouten/bc706a10d8346492fe58c44759c1e53c

I didn't do a PR for this because I don't think ignoring bad certs is the _right_ solution, so use at your own risk.

**Comment by x-radeon** [comment]
I'm getting an HTTP 500 error when trying to edit my Pushbullet config as well. I'm on PlexPy 1.4.22 and Python 2.7.14 on Windows Server 2016. It also doesn't send notifications, even with the correct API key.

For the notification issue I think Pushbullet needs to be changed from Basic auth:

'Authorization': 'Basic %s' % base64.b64encode(self.apikey + ":")

To Access-Token in the header:

'Access-Token': "%s" % self.apikey

Not sure why I'm getting a 500 when trying to edit it. I noticed in the config.ini file that the API key is not wrapped in quotes. If I shutdown PlexPy add the quotes, PlexPy removes them when I start it again. I'm not sure if that has anything to do with that 500.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.23.

**Comment by Cubby1313** [comment]
And apparently broken in v1.4.24 because I updated and now Pushbullet and IFTTT can't work together anymore...

**Comment by kylemart** [comment]
I'm also getting this issue on v1.4.25.

**Comment by x-radeon** [comment]
So for me, I found it was actually Python that was the issue since it was actually failing the cert validation which is now done by default on newer versions of Python. I tested this by just writing a small Python app that tried to hit Pushbullet using the same method PlexPy uses and I found it was throwing an error when trying to connect. To fix it, I had to manually insert the root CA and intermediary CA that Pushbullet uses for their cert into my Windows server trusted root cert store. When I did that, it works just fine now. Pushes works, and I can edit the Pushbullet config page. I suspect the 500 we get when you try to edit the Pushbullet config is actually the GetDevice method failing the cert validation as well.

So the workaround is installing the CA into your cert store, however, this is a bad idea in general, I wonder if we can have an option in PlexPy to use the IgnoreSSL httplib function to fix this issue.

Thanks for your work on this project guys!

**Comment by JonnyWong16** [comment]
Try

```
pip install pyopenssl
```

**Comment by Cubby1313** [comment]
I have no idea what that means and what I should do with that information... lol

Sorry for not being a pro :P

**Comment by kylemart** [comment]
@Cubby1313 It's a command for installing PyOpenSSL (via the terminal or command-line). @JonnyWong16 Will do!

**Comment by dejected1** [comment]
ok so ive been following. I was on python 2.7.8. Installed pyopenssl, no change still 500 error. I then updated to python 2.7.14, restarted service and bravo that worked. windows 10 x64 plexpy 1.4.25

**Comment by Cubby1313** [comment]
![image](https://user-images.githubusercontent.com/13462305/31329613-fb895082-aca8-11e7-9c3f-76ab9b21d3e2.png)


Yeah... still lost...

**Comment by Cubby1313** [comment]
![image](https://user-images.githubusercontent.com/13462305/31329670-32d7f32c-aca9-11e7-91f8-9bfbdc920925.png)

Yeah... still lost...

**Comment by JonnyWong16** [comment]
Normal windows command line. Not python.

**Comment by Cubby1313** [comment]
ahuh...

![image](https://user-images.githubusercontent.com/13462305/31329882-13090c2e-acaa-11e7-97ff-77ca5fcbd6a3.png)

**Comment by Cubby1313** [comment]
I obviously am completely lost so if someone would to be so kind as to treat me like a 5 year old then I would appreciate it.

**Comment by JonnyWong16** [comment]
C:\Python27\scripts\pip install pyopenssl

**Comment by dejected1** [comment]
@Cubby1313 i just had to figure all this out myself recently so i have some handy articles on tap. You will more then likely have to install pip. If you want to use it from any command line you'll have to setup the PATH variables in windows. Here is a really good article to get you going.

http://docs.python-guide.org/en/latest/starting/install/win/#install-windows

Once done with the article you should be able to run jonnywong16's pip install pyopenssl from any cmd windows.

**Comment by kylemart** [comment]
Installed pip, ran `pip install pyopenssl`, rebooted my machine, then attempted to use my PushBullet API token... Same issue... 500 Internal Service error... I have version 17.3 of pyOpenSSL. @JonnyWong16 

**--- EDIT ---**

Also, I found some instructions here: http://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2. In other words, I also did `pip install urllib3` then in the Python interpreter wrote: 
```Python
>>> import urllib3.contrib.pyopenssl
>>> urllib3.contrib.pyopenssl.inject_into_urllib3()
```
This didn't seem to help either. Not sure if it was even necessary, tbh. Can anyone confirm if I needed to perform that last step? I was getting a number of SNIMissingWarning and InsecurePlatformWarning messages while installing pyOpenSSL.

For reference:

Installing pip...

```
root@nas:~/Downloads# python get-pip.py 
Collecting pip
/tmp/tmpcg2Plh/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
/tmp/tmpcg2Plh/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 541kB/s 
Collecting setuptools
  Downloading setuptools-36.6.0-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 1.6MB/s 
Collecting wheel
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 5.1MB/s 
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.1 setuptools-36.6.0 wheel-0.30.0
/tmp/tmpcg2Plh/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
```

Installing pyopenssl...

```
root@nas:~/Downloads# pip install pyopenssl
Collecting pyopenssl
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pyOpenSSL-17.3.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 51kB 1.2MB/s 
Collecting cryptography>=1.9 (from pyopenssl)
  Downloading cryptography-2.1.1-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 318kB/s 
Collecting six>=1.5.2 (from pyopenssl)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->pyopenssl)
  Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 5.6MB/s 
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.9->pyopenssl)
  Downloading cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl (405kB)
    100% |████████████████████████████████| 409kB 2.0MB/s 
Collecting enum34; python_version < "3" (from cryptography>=1.9->pyopenssl)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.1 (from cryptography>=1.9->pyopenssl)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 5.5MB/s 
Collecting ipaddress; python_version < "3" (from cryptography>=1.9->pyopenssl)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.9->pyopenssl)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 2.8MB/s 
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built pycparser
Installing collected packages: asn1crypto, pycparser, cffi, enum34, six, idna, ipaddress, cryptography, pyopenssl
Successfully installed asn1crypto-0.23.0 cffi-1.11.2 cryptography-2.1.1 enum34-1.1.6 idna-2.6 ipaddress-1.0.18 pycparser-2.18 pyopenssl-17.3.0 six-1.11.0
```
Installing urllib3...

```
root@nas:~# pip install urllib3[secure]
Collecting urllib3[secure]
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 1.3MB/s 
Requirement already satisfied: idna>=2.0.0; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Requirement already satisfied: pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Requirement already satisfied: cryptography>=1.3.4; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Collecting certifi; extra == "secure" (from urllib3[secure])
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 1.2MB/s 
Requirement already satisfied: ipaddress; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Installing collected packages: certifi, urllib3
Successfully installed certifi-2017.7.27.1 urllib3-1.22
```

**Comment by Cubby1313** [comment]
Sorry guys, work got in the way of being able to follow through on this. I was able to run the pip command but it doesn't appear to have fixed the issue... I don't actually need Pushbullet and just wish I could get IFTTT functionality back. Should I just do a clean install of Plexpy since IFTTT actually worked before trying at add pushbullet?

**Comment by 7eptem** [comment]
same problem here but with more of the services and i use most IFTTT, still not working

**Comment by arabesc** [comment]
Don't know about IFTTT and PushBullet but Telegram notifications don't work for me.
[PlexPy-1.4.22](https://www.freshports.org/multimedia/plexpy/)
[python27-2.7.14_1](https://www.freshports.org/lang/python27/)
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/plexpy/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/plexpy/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/plexpy/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/plexpy/plexpy/helpers.py", line 59, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/plexpy/plexpy/webserve.py", line 2939, in send_notification
    if notifiers.send_notification(this_agent['id'], subject, body, notify_action, **kwargs):
  File "/usr/local/plexpy/plexpy/notifiers.py", line 596, in send_notification
    return telegramClient.notify(message=body, event=subject, **kwargs)
  File "/usr/local/plexpy/plexpy/notifiers.py", line 1926, in notify
    body=urlencode(data))
  File "/usr/local/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

**Comment by JonnyWong16** [comment]
The SSL Error means your machine cannot connect to IFTTT (not just PlexPy/Tautull specifically).

**Comment by arabesc** [comment]
How can I check that IFTTT? I've never heard about it.
I've tested Telegram bot from command line with cURL on the same machine, and it works, there are no connection issues.

**Comment by JonnyWong16** [comment]
Sorry, I meant Telegram. cURL probably has its own certificate store. 

Also 1.4.22 is and old version. Version 1.4.25 is the latest.

**Comment by arabesc** [comment]
So, there is some component that has outdated certificate storage? Is it possible to switch to some generic or system-wide certificate storage instead of the local one?

**Comment by JonnyWong16** [comment]
Sorry, that is outside my sphere of knowledge. Google is your friend here.

**Comment by slimshizn** [comment]
I know this hasn't been discussed in a while but just wanted to confirm that updating to 2.7.12 fixed the 500 error with notifications on pushbullet. Thank you.

**Comment by skippa** [comment]
Can Ubuntu 14.04 LTS be easily upgraded to Python 2.7.12?  I've heard its bad.  Like crossing the streams bad.  Nor do I know how to do it...
