### ISSUE TITLE
PlexPy fails to launch if /Etc/Timezone directory exists on QNAP 

### ISSUE THREAD

**Issue by MwC-Trexx** [Tautulli/Tautulli#924]
PLEXPY CONFIGURATION

Git Branch:	master
Git Commit Hash:	3742f33d08feb6fb15e74af6318185230205006f
Configuration File:	/share/CACHEDEV1_DATA/.qpkg/PlexPy/CONFIG/plexpy.conf
Database File:	/share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR/plexpy.db
Log File:	/share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR/logs/plexpy.log
Backup Directory:	/share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR/backups
Cache Directory:	/share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR/cache
GeoLite2 Database:	Click here to install the GeoLite2 database.
Arguments:	['--daemon', '--port=8659', '--datadir=/share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR', '--config=/share/CACHEDEV1_DATA/.qpkg/PlexPy/CONFIG/plexpy.conf']
Platform:	Linux 4.2.8
Python Version:	2.7.12 (default, Aug 21 2016, 01:11:52) [GCC 5.2.0]
Resources:	GitHub Source | GitHub Issues | FeatHub Feature Requests | PlexPy Wiki | PlexPy FAQ
Support:	Plex Forums | PlexPy Gitter Chat | /r/Plex Discord Server | PlexPy Discord Server

**How can we reproduce your issue?**
1) Create /etc/timezone directory
2) Launch PlexPy.py

**Error Log**
Traceback (most recent call last):
  File "PlexPy.py", line 35, in <module>
    import plexpy
  File "/share/CACHEDEV1_DATA/.qpkg/PlexPy/plexpy-master/plexpy/__init__.py", line 58, in <module>
    SCHED = BackgroundScheduler()
  File "lib/apscheduler/schedulers/base.py", line 61, in __init__
    self.configure(gconfig, **options)
  File "lib/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "lib/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "lib/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "lib/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "lib/tzlocal/unix.py", line 49, in _get_localzone
    with open(tzpath, 'rb') as tzfile:
IOError: [Errno 21] Is a directory: '/etc/timezone'

**Work Around**
Delete /etc/timezone directory and restart PlexPy

**Comment by JonnyWong16** [comment]
Not a PlexPy issue.
