### ISSUE TITLE
Plexpy is not noticing the playback session ending, which leads to a high duration.

### ISSUE THREAD

**Issue by louis-lau** [Tautulli/Tautulli#925]
**Version:** 1.4.16

**Branch:** v2

**Commit hash:** 01ec812e1c3b5e3108631ce67329bc1d5ecbd60e

**Operating system:** Ubuntu 16.04.1 LTS

**Python version:** 2.7.12

**What you did?**
Started playpack.

**What happened?**
It looks like plexpy didn't notice the item had stopped playing, it only ended that session after restarting plexpy. Now this session has a duration of 5365 mins.

**What you expected?**
I kinda expected plexpy to see the item had stopped playing 😆 

**How can we reproduce your issue?**
It looks like some "[Errno 111] Connection refused" errors might have caused this, as before that error the session id is 450. After the error the session id is 1. Maybe the logs are more helpful to you than to me.

**Screenshot:**
http://i.imgur.com/kz8g6OJ.png

**Link to logs:**
Logs of  09-12-2016 (when playback started): http://pastebin.com/7J8ffUWf
Logs of  13-12-2016 (when plexpy restarted): http://pastebin.com/LFVrWJVt

**Comment by JonnyWong16** [comment]
I have already reported this websocket issue to Plex.

I'm not going to provide support for v2 at the moment because I know it is buggy. The only way to avoid this is to use v1 and disable websockets.

**Comment by louis-lau** [comment]
Alright, thanks for the update and the effort!
