### ISSUE TITLE
Access control not working

### ISSUE THREAD

**Issue by Rockapela** [Tautulli/Tautulli#926]
I am trying to be able to access PlexPy from outside my house. I originally forwarded port 8181 on my router and setup PlexPy. I checked the port online with a port checker and it says that it is not open. I ran PlexPy as an administrator and this still didn't fix the issue. I have changed the port to 38084 and this still doesnt work. I'm so confused at this point.

 I have multiple ports forwarded on my router for different application and they all work perfectly, so I don't understand why PlexPy wouldnt be working. The only thing I haven't tried is reinstalling PlexPy and I would like to get some input on this before I do so. Ill attach a photo of my "Access Control" and "Web Interface" settings.

<img width="578" alt="screen shot 2016-12-17 at 4 12 49 pm" src="https://cloud.githubusercontent.com/assets/10479452/21290101/ec852976-c473-11e6-89d3-e0afb6d50569.png">

<img width="359" alt="screen shot 2016-12-17 at 4 12 58 pm" src="https://cloud.githubusercontent.com/assets/10479452/21290103/f1c45560-c473-11e6-8e33-7286a7f82706.png">

**Comment by JonnyWong16** [comment]
Try it with `0.0.0.0` instead of `localhost`.

**Comment by Rockapela** [comment]
Worked, thank you!
