### ISSUE TITLE
How to deal with Plex Web using new sessionKey to issue stop state?

### ISSUE THREAD

**Issue by Swiftnesses** [Tautulli/Tautulli#927]
I've noticed that in some circumstances Plex Web (and possibly other players) issue the stopped state under a new sessionKey.

This is easy to reproduce. Start a movie via Plex Web, immediately after seek to the end and let it finish.The result is a pause state send via the original sessionKey and a stopped state sent under a new sessionKey. 

I see evidence of this in my DB as the sessions table is filling up with orphan sessions.

**Comment by JonnyWong16** [comment]
I have been noticing this too.

I couldn't figure out why. Now I do. Thanks. 

Unfortunately, I'm on vacation right now so I won't be able to fix it for a while.
