### ISSUE TITLE
PlexPy assigning Last Played and Last Device to wrong user

### ISSUE THREAD

**Issue by gers1978** [Tautulli/Tautulli#928]
My boss Louise logs in to my Plex using her iPad.  PlexPy reports her device name as "Louise's iPad".  This is the only device she uses.

I noticed last week that PlexPy reported two of my other users, Paul and David, as having "Louise's iPad" as their last device.

I assumed she had logged in as Paul or David (only explanation I could think of), but she said she didn't (she doesn't even know Paul or David and wouldn't know their PINs)

When I check today, a similar thing is showing on other users - my user Andy's last device shows as "Tom's iPad'.  Again, Andy doesn't know Tom or his PIN.

Is this a Plex or PlexPy bug?

UPDATE: just for further info, I think the device name is correct, but showing under wrong user.  For example I know my boss Louise religiously watches the show Empire on my Plex.  I know for a fact my user Kirsty doesn't watch Empire.  But under Users in PlexPy, Kirsty's Last Device is showing as "Louise's iPad" and Last Played is Empire season 3 episode 8.  The date and device match up to when Louise actually watched this episode (I asked her), but PlexPy is reporting it under user Kirsty.  Again, Louise does not know Kirsty or her Plex PIN, so looks like a bug.

**Comment by livefeed** [comment]
How did you fix this?
