### ISSUE TITLE
1 million pulls from the docker hub

### ISSUE THREAD

**Issue by sparklyballs** [Tautulli/Tautulli#929]
**Version:**
This one.
**Branch:**
This one.
**Commit hash:**
This one too, there's a pattern here, lol.
**Operating system:**
Computer thing.
**Python version:**
Big slithery one.
**What you did?**
Lots of things, some of which probably can't admit to in public.
**What happened?**
the docker image was pulled 1 million times
**What you expected?**
beer and snacks
**How can we reproduce your issue?**

sticky back plastic and an old toilet roll.
**What are your (relevant) settings?**
Steer a straight course 
**Link to logs:**

http://www.arieltreecare.com/wp-content/uploads/2015/02/logs.jpg

The [linuxserver.io plexpy](https://hub.docker.com/r/linuxserver/plexpy/) docker image has just reached 1 million pulls from the dockerhub.

**Comment by Hellowlol** [comment]
Awesome stuff!

**Comment by sparklyballs** [comment]
hey @Hellowlol 

long time no see.
