### ISSUE TITLE
Plexpy is crashing and wont start

### ISSUE THREAD

**Issue by wiscokidd** [Tautulli/Tautulli#930]
**Version:**
v1.4.16
**Branch:**
master
**Commit hash:**
3742f33d08feb6fb15e74af6318185230205006f
**Operating system:**
Windows 10 Pro
**Python version:**
2.7
**What you did?**
I backed up data base and reinstalled Plexpy
**What happened?**
Plexpy was working great for about a year. I have never had an issue. 
Starting yesterday Plexpy webinterface was unavailable. I used remote desktop to check if it was running and it appeared to have crashed. So I double clicked plexpy.py The command prompt window opened and 5-10 seconds later it closed. I tried everything I could think of. I ended up backing up the database and I reinstalled Plexpy. It worked great, until I got home from work today and realized it had crashed again. Same issue when I try to launch it the command prompt window opens and closes after about 5-10 seconds.
**What you expected?**
I expected it to work like it has for the past year.
**How can we reproduce your issue?**

I don't know
**What are your (relevant) settings?**

**Link to logs:**
https://gist.github.com/wiscokidd/642a3cc0ab6cbb0bf7734d9c4d87e687

**Comment by JonnyWong16** [comment]
Your database got corrupted, possibly from the crashing.

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q18

**Comment by wiscokidd** [comment]
thank you for the quick reply. I checked the DB integrity and was not ok. I repaired it got the integrity ok. Copied the DB over but I'm still having the same issue.

**Comment by wiscokidd** [comment]
I figured it out. I had changed the port because there was something already running on the default port. When I reinstalled plexpy I forgot to change the port. After changing the port and fixing the DB everything i working again. Thanks for the help!
