### ISSUE TITLE
Pushover Notification Agent Failing

### ISSUE THREAD

**Issue by JonLaliberte** [Tautulli/Tautulli#933]
**Version:**
1.4.16

**Branch:**
master

**Commit hash:**
3742f33d08feb6fb15e74af6318185230205006f

**Operating system:**
Ubuntu/Linux 3.19.0-59-generic

**Python version:**
2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

**What you did?**
Entered my API token, saved. Pressed the "Test Pushover" button.
Also tried restarting PlexPy, and restarted the machine.
I also tried removing my API key and saving a new one.

**What happened?**
It gives me an error: Notification Failed.
In logs it's 400 Bad Request.

**What you expected?**
A test notification to be sent.

**How can we reproduce your issue?**
I don't know. As far as I can tell it simply does not work.

**What are your (relevant) settings?**

**Link to logs:**
http://pastebin.com/B5px4x3h

**Comment by JonnyWong16** [comment]
400 bad request usually means you entered something wrong. Do you have the API key and the user key? Did you have them backwards?

**Comment by JonLaliberte** [comment]
Very sorry about that, was rushing and didn't enter in the correct user key.
