### ISSUE TITLE
Massively Incorrect "Most Concurrent Streams" Statistics

### ISSUE THREAD

**Issue by slunat** [Tautulli/Tautulli#935]
Hi,
I have a strange issue with my Most Concurrent Streams data. It seems to be showing that I had over 9000 (literally, not a reference) concurrent streams on a single day. 

![image](https://cloud.githubusercontent.com/assets/24834294/21558073/8e07ebe6-ce2c-11e6-97de-20f9c09b8271.png)

This is impossible as I have not even got 9000 media files and only two users who use my Plex. Also, when selecting to view the concurrent streams, it shows only a single play for a tv show (which is the correct data).

![image](https://cloud.githubusercontent.com/assets/24834294/21558085/c35175b0-ce2c-11e6-95cb-d05e93742952.png)

I wasnt bothered by this at first but I just realised this is now skewing all of my other data as I have over 9000 plays added to my watch history.
Is there any way I can manually change this data so I can have all my statistics correct again? Please note I am basically illiterate when it comes to stuff like this so step by step instructions of which file and what data to change would be appreciated.

Please let me know if any logs are required (and how to aquire them :) )

Thanks in advance.

**Comment by JonnyWong16** [comment]
Please use the search feature:

https://github.com/JonnyWong16/plexpy/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20concurrent

Specifically #910
