### ISSUE TITLE
Windows Fail to Launch

### ISSUE THREAD

**Issue by kfulgham** [Tautulli/Tautulli#936]
I'm switching from OS X to Windows thanks to my Mac Mini boot drive dying. Trying to get PlexPy setup on this windows device has me losing hair. I have Python 2.7 installed and .py is set to run Pythonw.exe 

When I try Plexpy.py nothing visibly occurs. When I run CMD and launch using the python command I get the following error. Looks like it's escaping folders for some reason?

> 
> C:\Program Files\Plexpy>python Plexpy.py
> Unable to create the log directory. Logging to screen only.
> Traceback (most recent call last):
>   File "Plexpy.py", line 260, in <module>
>     main()
>   File "Plexpy.py", line 186, in main
>     plexpy.initialize(config_file)
>   File "C:\Program Files\Plexpy\plexpy\__init__.py", line 129, in initialize
>     verbose=VERBOSE)
>   File "C:\Program Files\Plexpy\plexpy\logger.py", line 205, in initLogger
>     file_handler = handlers.RotatingFileHandler(filename, maxBytes=MAX_SIZE, backupCount=MAX_FILES)
>   File "C:\Python27\lib\logging\handlers.py", line 117, in __init__
>     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
>   File "C:\Python27\lib\logging\handlers.py", line 64, in __init__
>     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
>   File "C:\Python27\lib\logging\__init__.py", line 913, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "C:\Python27\lib\logging\__init__.py", line 943, in _open
>     stream = open(self.baseFilename, self.mode)
> IOError: [Errno 2] No such file or directory: 'C:\\Program Files\\Plexpy\\None\\plexpy.log'

**Comment by JonnyWong16** [comment]
Delete your `config.ini` file and try again.

**Comment by kfulgham** [comment]
No config.ini file?

**Comment by JonnyWong16** [comment]
It should be in the folder `C:\Program Files\Plexpy\`

**Comment by kfulgham** [comment]
Thanks, That file isn't there.

**Comment by JonnyWong16** [comment]
Reinstall in a different folder where PlexPy will have write permissions.

**Comment by kfulgham** [comment]
Thanks I'll try again.

**Comment by kfulgham** [comment]
I'm an idiot. It just couldn't write to that file. Thanks
