### ISSUE TITLE
pms_image_proxy API call only returns an image on the first couple calls

### ISSUE THREAD

**Issue by JayyyR** [Tautulli/Tautulli#938]
I'm using the api to get image art, but it only seems to work on the first few calls. Then subsequent calls return no image.

API call looks like this:

ip:port/api/v2/?apikey=$apikey&cmd=pms_image_proxy&img=$imgpath&fallback=art

**Comment by JayyyR** [comment]
thanks for the quick response. deleting the image cache works, however it appears I need to do it after every call. Is this expected?

**Comment by JonnyWong16** [comment]
No. I think you may be doing something wrong, or it is being cached elsewhere like your browser. 

`pms_image_proxy` works fine in our Android app and returns hundreds of images.

**Comment by wptex** [comment]
I encountered this issue providing background images from plexpy to a separate service. You can add a current timestamp (or random number, guid, etc.) after $imgpath to avoid returning a blank image. e.g., $imgpath/1492127210. I guess that regenerates it to cache, fixing the subsequent load issue.
