### ISSUE TITLE
Unable to access webpage of Plexpy :(

### ISSUE THREAD

**Issue by vincegre** [Tautulli/Tautulli#939]
Hi

Moved my Plex server from FreeNAS to Linux Ubuntu and Plexpy with it. I did a clean install of Plexpy on the Ubuntu server following instructions here and everything went fine. I copied my db file from my old system to the new one. I deleted also in the config.ini the two http lines as stated in FAQ when problem arises to access webpages of Plexpy but mot much success till now :( Startup of Plexpy looks fine !

`root@serveur:/opt/plexpy# service plexpy status
● plexpy.service - PlexPy - Stats for Plex Media Server usage
   Loaded: loaded (/lib/systemd/system/plexpy.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since dim. 2017-01-01 12:10:20 CET; 1h 3min ago
  Process: 28522 ExecStart=/opt/plexpy/PlexPy.py --quiet --daemon --nolaunch --config /opt/plexpy/config.ini --datadir /opt/plexpy (code=exited, status=0/SUCCESS)

janv. 01 12:10:19 serveur systemd[1]: Starting PlexPy - Stats for Plex Media Server usage...
janv. 01 12:10:20 serveur systemd[1]: Started PlexPy - Stats for Plex Media Server usage.
root@serveur:/opt/plexpy#`

The logs directory keeps being empty :(

Version of Plexpy: the one pulled from Github two days ago
Operating system: Ubuntu Server 16.04.1 LTS
Python version: not sure looks like system hav Python 2.7, 3 and 3.5 but not sure which one used by plexpy....
What you did? brand new install of Plexpy plus import of existing db file from a previous setup
What happened? Web interface not avalaible

Any ideas what to look for ? to resolve the issue !

Happy new year everyone ;)

Vincèn

**Comment by vincegre** [comment]
Hum have done a python -V and it states 2.7.12 so I guess it's one used by plexpy no ?

**Comment by JonnyWong16** [comment]
No, not necessarily. Can you start it manually?

**Comment by JonnyWong16** [comment]
That would be my guess. I don't have enough experience with Ubuntu enough to know how to fix it.

**Comment by vincegre** [comment]
Oki after going in wrong direction (thinking it was wrong version of Python that was used), the issue was just the user declared in script to run app that was wrong ! As soon as corrected, pfiu it works like a charm :+1: 
Thanks for help and for such a great tool ;)

**Comment by kanebrands** [comment]
I'm having this same issue, can you give details as to how you corrected yours vincegre? I'm also on Ubuntu 16.04 and Python 2.7.12.

**Comment by vincegre** [comment]
In the init script used to start Plexpy the declared user for the script was wrong so I just edited that to be correct with my system !
