### ISSUE TITLE
Facebook group notifications not reliable

### ISSUE THREAD

**Issue by ScouseTS** [Tautulli/Tautulli#940]
**Version:** 1.4.16

**Branch:**

**Commit hash:**

**Operating system:** MS Server 2012 R2

**Python version:** 3.7

**What you did?** Enabled Facebook group notifications, setup an app, test notifications works and so far it's notified on some stuff added, but not all. I have notifications setup on all libraries.

**What happened?** It has posted a few new movies added and a few new tv shows added but not all, for example I've added Sherlock season to Plex and PlexPy can see it added but didn't fire a notification, however when I added a different show earlier it did.

**What you expected?** Notifications on every movie or tv show added.

Notification log: http://prntscr.com/dqncwg
Recently added: http://prntscr.com/dqnd71

I've looked over FAQ but cannot find anything that I have missed, recently added notifications are enabled and selected within the Facebook notifications. It doesn't make a whole lot of sense why it is randomly firing the notifications.

**Link to logs:**

**Comment by ScouseTS** [comment]
I've just added Sing and Mariah's world to the server. It's fired a notification off for Sing but not for the TV Show. Notifications are enabled on TV Shows library definitely as it's fired them for TV shows already.

http://prntscr.com/dqnode
http://prntscr.com/dqnol4

**Comment by JonnyWong16** [comment]
Please post your logs. https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#q-where-can-i-find-my-plexpy-logs

Also Python 3.7 doesn't work with PlexPy.  https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#q-i-have-some-weird-python-errors

**Comment by ScouseTS** [comment]
Uploaded the log to my server: http://patto.co.uk/plexpy.zip


Apologies Python 2.7 :)

**Comment by JonnyWong16** [comment]
Please use pastebin or gist as stated in the FAQ. I'm not downloading a file.

**Comment by ScouseTS** [comment]
No problem, they both tell me file is too large. 

I've uploaded the .log file instead so you can read it via your browser, no need to download anything.

http://patto.co.uk/plexpy.log

**Comment by ScouseTS** [comment]
Just noticed also it appears the custom notification body isn't working, I've changed it and restarted Plexpy but it's still posting as the default notification text.
