### ISSUE TITLE
Bottom text not wrapping on history page

### ISSUE THREAD

**Issue by OmgImAlexis** [Tautulli/Tautulli#943]
![screen shot 2017-01-08 at 2 52 54 am](https://cloud.githubusercontent.com/assets/6525926/21743230/ddc98446-d54d-11e6-801c-344b3d37ac07.png)

**What you did?**
Opened history page.
**What happened?**
Bottom text didn't wrap.
**What you expected?**
Bottom text to wrap.
**How can we reproduce your issue?**
Open history page on screen with width around 1440px.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.18.
