### ISSUE TITLE
Multiple 404 not found with reverse proxy with SSL

### ISSUE THREAD

**Issue by tijmenvn** [Tautulli/Tautulli#944]
**Version:**
1.4.16

**Branch:**
Master

**Commit hash:**
None?

**Operating system:**
Ubuntu 16.04

**Python version:**
2.7.12

**What you did?**
Used Nginx to reverse proxy with SSL (and only with SSL),

**What happened?**
First refresh works, but after few minutes I get multiple 404's and "Nothing matches the give URI"

**What you expected?**
A working Plexpy page

**How can we reproduce your issue?**
Very hard to reproduce, even I can't find a consistent way to get the bug. Sometimes it keeps working for an hour, sometimes for 15 minutes. Locally it keeps running, just over proxy it doesn't

**What are your (relevant) settings?**
I have included all the needed proxy lines that are in the FAQ, Nginx is run from another container, not the same

**Link to logs:**

[tijmenvn_log.zip](https://github.com/JonnyWong16/plexpy/files/692039/tijmenvn_log.zip)
![capture](https://cloud.githubusercontent.com/assets/9320891/21749089/d4116a7e-d596-11e6-811a-78c149e3a22a.PNG)

**Comment by Hellowlol** [comment]
If you want help. Dont zip the log. Since this is related to the reverse proxy you might wanna post your config. (maybe its included in zip, who knows..)

**Comment by tijmenvn** [comment]
server {
			listen 443 ssl;
			include snippets/ssl-MYSITE.conf;

			# Standard proxying headers
			proxy_set_header    Host                $host;
			proxy_set_header    X-Real-IP           $remote_addr;
			proxy_set_header    X-Forwarded-Host    $server_name;
			proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

			# SSL proxying headers
			proxy_set_header    X-Forwarded-Proto   $scheme;
			proxy_set_header    X-Forwarded-Ssl     on;

			server_name plexpy.MYSITE.nl;
			location / {
					proxy_pass http://192.168.1.8:8181/;
			}
	}
Here you can see my reverse proxy setup for PlexPy.

**Comment by tijmenvn** [comment]
Does anyone have a clue? I have no idea what I'm doing wrong here, or if this is a bug.

**Comment by JonnyWong16** [comment]
Start PlexPy in dev mode please.

`python PlexPy.py --dev`

**Comment by tijmenvn** [comment]
Done, only warnings I get are:

2017-01-10 16:48:36 - WARNING :: MainThread : Failed to access uri endpoint /library/sections. Status code 401
2017-01-10 16:48:36 - WARNING :: MainThread : PlexPy Pmsconnect :: Unable to parse XML for get_libraries_list: 'NoneType' object has no attribute 'getElementsByTagName'.

In the web interface in those white fields, I now get:
Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 66, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, None)
![capture](https://cloud.githubusercontent.com/assets/9320891/21815583/8932a2a2-d75d-11e6-838b-92bf4a406d1b.PNG)

And BTW: to replicate this problem. 90% out of the times I open a second instance, so plexpy in a new tab. I get this problem, the other tab keeps working

**Comment by tijmenvn** [comment]
Could it be the fact that Nginx is running of a different container than PlexPy?

**Comment by tijmenvn** [comment]
Yeah, I definetely found the consistency in the error, I only get the error in a entirely different session, so F5 the page with the first session and it will still work, closing the session and reopening it and you'll get the error.

**Comment by JonnyWong16** [comment]
I think the error is in your nginx config somewhere.

**Comment by tijmenvn** [comment]
For some reason my plexpy was saved as https://plexpy.MYSITE.nl/home/ The last slash was only adjusted for the first session, afterwards I would get this error. And my bookmarks are nicely saved accros machines, so the problem occured everywhere....
