### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Supersimo88** [Tautulli/Tautulli#946]
I can not set the telegram client for notifications, I tried guides around but none of them seems to explain step by step, and I'm clearly doing something wrong but I do not understand what

**Comment by roelbeun** [comment]
Did you enable it with the bell icon in front of the notification agent?

**Comment by Supersimo88** [comment]
Yes, but the problem is in the configuration side, seams that i'm not understanding how to get Telegram Bot Token and Telegram Chat ID, Group ID, or Channel Username.
Don't know if i'm doing right in telegram
