### ISSUE TITLE
Unable to configure HTTPS. The pyOpenSSL module is missing [Synology]

### ISSUE THREAD

**Issue by irishj** [Tautulli/Tautulli#947]
Hi,

Attempting to enabled HTTPS on the backend and after a restart, it's disabled.

Logs show "2017-01-18 19:02:39 - WARNING :: MainThread : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled"

Python is installed correctly (Python 2.7) and attempting to install PyOpenSSL via PIP shows it's already installed. 

root@DS1815:/volume1/@appstore/python/lib/python2.7/site-packages# python pip install pyopenssl

Requirement already satisfied: pyopenssl in /volume1/@appstore/python/lib/python2.7/site-packages
Requirement already satisfied: six>=1.5.2 in /volume1/@appstore/python/lib/python2.7/site-packages (from pyopenssl)
Requirement already satisfied: cryptography>=1.3.4 in /volume1/@appstore/python/lib/python2.7/site-packages (from pyopenssl)
Requirement already satisfied: idna>=2.0 in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already satisfied: pyasn1>=0.1.8 in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already satisfied: setuptools>=11.3 in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already satisfied: enum34 in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already satisfied: ipaddress in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already satisfied: cffi>=1.4.1 in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=1.3.4->pyopenssl)
Requirement already satisfied: pycparser in /volume1/@appstore/python/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.3.4->pyopenssl)

Running the latest version of plexpy...

2017-01-18 19:02:36 - DEBUG   :: MainThread : Latest version is 3742f33d08feb6fb15e74af6318185230205006f
2017-01-18 19:02:36 - INFO    :: MainThread : PlexPy is up to date

Synology DS1815+ / DSM 6.0.2-8451 Update 8

Any idea how to fix this issue and enable HTTPS support ?

Thanks

**Comment by JonnyWong16** [comment]
This looks relevant http://stackoverflow.com/a/25907213

**Comment by irishj** [comment]
Thanks - I think it's related to how the Synology system setup python and not an issue with PlexPy.

I've posted on the Plex forums as another user asked the same question.  It can be found here if anyone has a similar problem -https://forums.plex.tv/discussion/178104/help-installing-plexpy/p4

Thanks
