### ISSUE TITLE
Telegram notification returning "notification failed"

### ISSUE THREAD

**Issue by jasperrooduijn** [Tautulli/Tautulli#949]
I'm running plexpy in a docker container (from LInux Server) https://github.com/linuxserver/docker-plexpy. All is working perfext. Except from the Telgram notification server. I created and tries several new bots and group id's (which i requested with @myidbot). Every time i test the telegram notification i get the message notification failed. Ik also check the output of the request made by plexpy but the only message i get is "Notification failed.". This is the URL -> <my-ip-here>:8181/plexpy/send_notification?agent_id=13&subject=PlexPy&body=Test+notification&notify_action=test&_=1484937034757

Am i missing something or doing something wrong?

**Comment by JonnyWong16** [comment]
What do the logs say? Has the bot been added to the group chat?

**Comment by jasperrooduijn** [comment]
PlexPy Notifiers :: Telegram notification failed: [404] Not Found

This is the only thing i can find in the log regarding telegram

**Comment by jasperrooduijn** [comment]
Just to be sure the chat ID and API key are matching and working i also send some test messages with curl and that works fine.

**Comment by JonnyWong16** [comment]
I just tested mine and it works. One of your settings is still wrong.

**Comment by jasperrooduijn** [comment]
Found it! I included the 'bot' part from the curl test and saved that in plexpy. After testing with curl i tried without the 'bot' part and it worked. Thanks for the fast support and the great work on the app!
