### ISSUE TITLE
Can 'Group Table and Watch Statistics History' option affect graphs as well?

### ISSUE THREAD

**Issue by mattman86** [Tautulli/Tautulli#950]
When I have the 'Group Table and Watch Statistics History' box checked, the tables look very nice. However, I notice that when I go to the graphs, they don't really match up with the tables. Is it possible to make them more congruent with each other when that box is checked?

**Comment by JonnyWong16** [comment]
Graphs don't group just like the check box says.

Grouping across days would not be accurate at all.
