### ISSUE TITLE
End of movie reporting (bug or feature ?)

### ISSUE THREAD

**Issue by fredguy** [Tautulli/Tautulli#954]
Hi, 
It would seem that plexpy does not see the end of a play as "stopped" or not as an event. play pause resume stop works fine, but if one goes to the end of movie, nothing happens. Anyone has the same behaviour ? I would have expected that reaching the end of a content would trigger a "stop" event.

**Comment by fredguy** [comment]
Except that would be a bugger because a movie is considered as watched at 95% max (85%default),  therefore triggered before the movie is actually ended. That's 6 mins before the actual end of a 2 hours movie.... witch could be ok i guess , but that's 2 min for a 40 mn TV show, and that's rough if the event triggers lights on on home automation.  If that's the case, so be it, i'll add a delay to the script execution but just wanted to make sure.

**Comment by JonnyWong16** [comment]
![image](https://cloud.githubusercontent.com/assets/9099342/22431217/a1ea08fe-e6c5-11e6-9d45-62e09bf1f299.png)

**Comment by fredguy** [comment]
Oh... feel dumb now. I read that option the other way around. 
Tested and approved ! It sent a stop notification indeed.
