### ISSUE TITLE
Can't save any settings

### ISSUE THREAD

**Issue by MaartenMol** [Tautulli/Tautulli#959]
**Version:** Latest from master

**Branch:** master

**Operating system:** Windows Server 2016 64-bit

**Python version:** 2.7

**What you did?** Tried to change a setting under any settings tab and save it

**What happened?** Nothing, an error showed up in the log

**What you expected?** To save the settings

**How can we reproduce your issue?** No idea. I have downloaded a fresh zip and copied the settings and db file. But same problem...

WebUI :: /settings#tab_tabs-2 : Uncaught TypeError: configForm.parsley is not a function. (settings:3289)

**Comment by JonnyWong16** [comment]
Ctrl+F5 and/or clear your browser cache.
