### ISSUE TITLE
User activity history not recorded for users other than plex server's account

### ISSUE THREAD

**Issue by duramato** [Tautulli/Tautulli#962]
**Version:** 1.4.16

**Branch:** dev

**Commit hash:**	3742f33d08feb6fb15e74af6318185230205006f

**Operating system:** Raspbian

**Python version:** 2.7.9

**What you did?** A user (other than me) watched a show on plex

**What happened?** It showed while he was streaming but didn't show any info on his history, the only user with history is mine.
See pictures below,
![img](https://pls.gtfo.accountant/Sej0f.png)
![img](https://pls.gtfo.accountant/9Uaow.png) 

**What you expected?** For all users to have their history logged

**Link to logs:** https://gist.github.com/duramato/8c78721bf0714f93df03d7c0adb6bb79

**Comment by JonnyWong16** [comment]
Please read the FAQ.

You also have TV logging disabled.

**Comment by duramato** [comment]
I had read the FAQ, it was no help to me.
The issue was i had TV logging disabled.
