### ISSUE TITLE
[Feature Request] Notification on Number of Watches

### ISSUE THREAD

**Issue by InfinitNumbrs** [Tautulli/Tautulli#964]
Would it be possible to receive a notification through pushover (any notification client) indicating when a user hits a certain amount of watches within a specific time frame?  Or even get a report on how many plays/ watches each user has accumulated at the end of each week or month?  This would help to know who is using the server too much without having to go through PlexPy history.

**Comment by JonnyWong16** [comment]
No, setup your own custom script.

And not the right place for feature requests.
