### ISSUE TITLE
Fixing malformed data in "Graphs" view

### ISSUE THREAD

**Issue by phobiac** [Tautulli/Tautulli#965]
**Version:** 1.4.16

**Branch:** master

**Commit hash:** 3742f33d08feb6fb15e74af6318185230205006f

**Operating system:** Windows 10 (Shows up as Windows 8 in plexpy interface)

**Python version:** 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**What you did?** Fixed corruption in the PlexPy database, per resolution of issue #556 

**What happened?** It worked! Unfortunately there were some active sessions whenever the issue that caused the corruption occurred and PlexPy had some active sessions with almost month long playtimes. I then went in and manually deleted them. Now my Graphs tab has a huge spike, as you can see below.

![plexpy](https://cloud.githubusercontent.com/assets/1310082/22829796/3fd1b17a-ef72-11e6-8c9a-743b3c7a62e5.png)

There's also no data associated with that day if I click on the spike.

![plexpy2](https://cloud.githubusercontent.com/assets/1310082/22829843/6dcc33c0-ef72-11e6-8c38-5762c04efad5.png)

And this persists even after restart of PlexPy.

**What you expected?** The incorrect data to not be there. I'm sure it's an issue I'll have to manually manipulate the database to fix. I just don't know what exactly needs to be done. I'm comfortable and able to use sqlite to fix it if someone can point me where to go.

**Comment by JonnyWong16** [comment]
#878
