### ISSUE TITLE
Slack channel only gets notifications of TV, not movies

### ISSUE THREAD

**Issue by LwsBtlr** [Tautulli/Tautulli#966]
Running Plexpy and keeping it up to date and it works very well, tracking all the things watched, but when notifications were setup for Slack, both new movies and new TV were added. Now only TV shows are getting published.

Under Global Notification settings both Movie and TV are checked as well as recently added, as well as "allow consecutive notifications" and "Enable Posters"

In the Slack settings there doesn't seem to be any setting that would change which notifications show up.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#notifications-q3

**Comment by daymanbpi** [comment]
Is there way to limit the notification to: Include Subject Line/ Include Link to Plex Web ->without Include Poster Image...
1. http://imgur.com/a/dxe7j
2. Without Include Poster Image checked.. http://imgur.com/a/zs1CJ ->Include Link to Plex does not show.
3. With include Poster Image checked...-> http://imgur.com/a/09nIE

Just looking to not include Poster Image but allow the other two.

**Comment by LwsBtlr** [comment]
Plexpy seems to get confused if there are multiple libraries with the same name. For example, I have three different plex servers and all have a "Movies" category. This seems to break notifications, somehow. At least notifications are "on" for all of them, but no notifications get posted to any notification agent.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/blob/master/README.md#issues
