### ISSUE TITLE
HTTPS keeps rewriting to HTTP

### ISSUE THREAD

**Issue by saltypoison** [Tautulli/Tautulli#971]
Hello,

I'm running my Plex server, PlexPy, and apache on Ubuntu server 14.04.  I've set up the reverse proxy in apache and can connect securely.  However, when I try and add a password, the url is rewritten to http and I lose access to the site until I manually remove the password from the config.  Any attempt to modify the URL back the https just results in another rewrite.

Apache Settings
```
ProxyPass /plexpy http://localhost:8181/plexpy/
ProxyPassReverse /plexpy http://localhost:8181/plexpy/
```

![image](https://cloud.githubusercontent.com/assets/7386461/22943138/a30655a4-f2a9-11e6-937b-33e4844f813b.png)

Any guidance would be appreciated.  

Thanks

**Comment by JonnyWong16** [comment]
Check the FAQ.

**Comment by saltypoison** [comment]
Perhaps you can be a bit more specific?  I don't see anything in there pertaining to my situation.  The reverse proxy works, but enabling the password feature (both basic and webform) causes the URL to be rewritten to http rather than https.

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q10

**Comment by frebib** [comment]
Had the same issue, I can confirm that all weirdness is solved by this specific configuration (as the docs describe) for me:

    location /plexpy {
        set $plexpy_upstream plexpy:8181;
        proxy_pass       http://$plexpy_upstream;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Remote-Port      $remote_port;
        proxy_set_header X-Forwarded-Host   $server_name;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-Ssl    on;
    }

*The variable for the upstream name isn't required, it is something specific to make nginx behave in docker correctly*

**Comment by saltypoison** [comment]
THANK YOU!  Those settings did the trick.  Much appreciated frebib.
