### ISSUE TITLE
SSL error when connecting via PlexPY Remote App

### ISSUE THREAD

**Issue by seanvree** [Tautulli/Tautulli#973]
**Version:**

VERSION 1.4.16  Changelog

PLEXPY CONFIGURATION

Git Branch:	master
Git Commit Hash:	3742f33d08feb6fb15e74af6318185230205006f
**Branch:**

Master

**Commit hash:**

3742f33d08feb6fb15e74af6318185230205006f

**Operating system:**

Windows 10E

**Python version:**

Python Version:	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

**What you did?**

Trying to connect via PlexPY Remote Android App

**What happened?**

Error from PlexPY remote app:

Error:  Unexpected error, Javax.net.ssl.peerunverfiedexception: Hostname:  MYHOSTNAME
not verified cert:  HASH

**What you expected?**

Always worked until this morning

I can access the PlexPY webUI from a a HTTPs webfront.

**How can we reproduce your issue?**

N/A

**What are your (relevant) settings?**

Using PlexyPY with signed and valid certs

Trying to connect via PlexPY remote app on HTTPS://mydomainname:32500

**Link to logs:**

There is nothing in the logs when I try to connect via the app.

**Comment by JonnyWong16** [comment]
Please submit to the PlexPy Remote app GItHub page. 

https://github.com/wcomartin/PlexPy-Remote
