### ISSUE TITLE
IP logging reports router's IP address

### ISSUE THREAD

**Issue by Enf0** [Tautulli/Tautulli#981]
I've installed PlexPy on the same machine as my Plex Media Server. I have enabled IP logging, but PlexPy reports the same IP address for all plays, "192.168.20.1" (my firewalls IP address).

What could cause this to happen?

**Version:**
PlexPy 1.4.16
Plex Media Server 1.3.4.3285

**Branch:**
origin/master

**Operating system:**
Debian 8 Jessie

**Python version:**
2.7.9

**Comment by JonnyWong16** [comment]
This is not an issue with PlexPy, but an issue with your *Plex* networking. PlexPy only records whichever IP address Plex tells it. Sorry, I can't help you with that.
