### ISSUE TITLE
issues with links directly to plex created from facebook notifications

### ISSUE THREAD

**Issue by GitHub010931** [Tautulli/Tautulli#983]
Just wondering if anyone else has had this, but I have plexpy setup to post automated notifications to a facebook group when new content is added, and I use custom text wrappers to show different pieces of info like the actors, rating, description etc.

It usually also posts a clickable attachment showing the poster and that link leads directly to Plex web app. I just noticed that after the new plex web app update, all the links are broken, and now none of the links correctly go to the respective movie/tv show when posted.

Is this something that can potentially be addressed and fixed from my side or is it up to developer to fix?

Really love this add on, its truly amazing utility wise.

Pictures of the issue:
![image](https://cloud.githubusercontent.com/assets/26070827/23376479/3bbc3840-fcfa-11e6-928f-4d10df6c8174.png)
![image](https://cloud.githubusercontent.com/assets/26070827/23376495/50851e4a-fcfa-11e6-8989-28c1b7464486.png)

**Comment by JonnyWong16** [comment]
I'm aware of it. Plex Web 3.0 changed the links. I need to fix it.

**Comment by GitHub010931** [comment]
Great, thanks. Any idea of eta of update? Appreciate this application, it's absolutely amazing!

On Feb 27, 2017, at 3:01 PM, JonnyWong16 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm aware of it. Plex Web 3.0 changed the links. I need to fix it.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.17.
