### ISSUE TITLE
Failed to run script: [Error 193] %1 is not a valid Win32 application 

### ISSUE THREAD

**Issue by 1liminal1** [Tautulli/Tautulli#987]
Hi guys, 

Running .sh though though the windows shell using, GIT for windows, as the default program works no problem. But PlexPy is using a different method to execute the script. Is there a way to force PlexPy to use a certain program?

**Comment by JonnyWong16** [comment]
What?

**Comment by 1liminal1** [comment]
HAHA, yeah I'm trying to smash this out @ work, wasn't very clear sorry

So Im trying to use the Notification Agent to execute a script, but it fails with "Failed to run script: [Error 193] %1 is not a valid Win32 application" Which is fine, Im trying to run a Bash script from a windows server. Thing is though, I have GIT for windows as the associated program to run any .sh files. But PlexPy does not seem to see that. Is there a way to force it to use the GIT Bash to run the script?

**Comment by JonnyWong16** [comment]
No.

You could use an intermediary script, like a .bat file to run the .sh script.

**Comment by 1liminal1** [comment]
Dam ok, or convert it i guess. 

Thanks for that!!!
