### ISSUE TITLE
Metadata in Plex not available in PlexPy | Movies | Media Info

### ISSUE THREAD

**Issue by iamnotdunningkruger** [Tautulli/Tautulli#989]
**Version:** 1.4.16
**Branch:** Master
**Commit hash:** 	3742f33d08feb6fb15e74af6318185230205006f
**Operating system:** Ubuntu 14.04.5 LTS Server
**Python version:** 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
**What you did?** Tried to get metadata in PlexPy | Movies | Media Info
**What happened?** Poster not available (see screenshot)
**What you expected?** Poster to be available.

The screenshot PlexPy doesn't show it but the container is asf.

Plex metadata
![screenshot from 2017-03-03 19-15-54](https://cloud.githubusercontent.com/assets/26175858/23573793/adeb8002-0046-11e7-83f0-0c7ecc318961.png)

PlexPy metadata
![screenshot from 2017-03-03 19-17-13](https://cloud.githubusercontent.com/assets/26175858/23573805/c44674c4-0046-11e7-9daf-d9163bddab7b.png)

**Comment by JonnyWong16** [comment]
PlexPy probably failed to grab the poster the first time and already cached the blank poster for that movie.

Clear you image cache in the settings.

**Comment by iamnotdunningkruger** [comment]
Did so, no difference.  After:

![screenshot from 2017-03-03 20-44-49](https://cloud.githubusercontent.com/assets/26175858/23574915/b6aec8dc-0052-11e7-9603-1dd4d2dd86c0.png)

Could it be that I made a crappy copy, since the framerate, codec, & audio channel data is missing?  Though the metadata in Plex (screencap above: 720p/H264) is I believe correct.

Log showing I cleared image cache twice a couple of minutes apart
![screenshot from 2017-03-03 20-56-23](https://cloud.githubusercontent.com/assets/26175858/23575002/fb878eb6-0053-11e7-8e1e-60a19e851dc5.png)

**Comment by JonnyWong16** [comment]
Force refresh the page (Ctrl + F5) and post your complete logs.

**Comment by iamnotdunningkruger** [comment]
Done.  No difference.

![screenshot from 2017-03-04 09-00-19](https://cloud.githubusercontent.com/assets/26175858/23579328/30ba4622-00b9-11e7-9b0c-6a652b31562d.png)

Complete logs: 
[plexpy-log.txt](https://github.com/JonnyWong16/plexpy/files/818658/plexpy-log.txt)

**Comment by JonnyWong16** [comment]
Have you refreshed the media info table yet?

**Comment by iamnotdunningkruger** [comment]
After refreshing the media info with the button on the page, clicking the refresh icon at the top right, and reloading the page now it works.  Thanks!  Guess this wasn't a bug and I just had to update the table.  Will mark as closed.  Thanks!!

![screenshot from 2017-03-09 12-16-18](https://cloud.githubusercontent.com/assets/26175858/23761896/71fc258a-04c2-11e7-8f93-f354ed0d2776.png)
