### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by sirmax1** [Tautulli/Tautulli#99]
1: Error parsing XML for Plex sync lists: must be string or read-only buffer, not None
2: Failed to access uri endpoint /servers/*/sync_lists. Status code 401

**Comment by drzoidberg33** [comment]
Not sure exactly what the question is, could you elaborate?

Are you sync lists not working? Is that the only thing not working? Can you access your synced items from Plex Web?

**Comment by ooii** [comment]
Hi,

I have no more history. When I go to History tab, I have the following error message.
![image](http://snag.gy/DAxHn.jpg)
The history page looks like this:
![image](http://snag.gy/kQH5P.jpg)
I got another error message before the previous one, about a number `10` and a number of rows, but I didn't make a copy of it.

Restarted plexpy but issue still there. Any idea what's the issue and how to fix it?
Thanks.

**Comment by JonnyWong16** [comment]
@ooii See #109.

**Comment by ooii** [comment]
Thanks.
PS: I don't know why I posted my issue in this one. Sorry for not paying attention.

**Comment by drzoidberg33** [comment]
Closing.
