### ISSUE TITLE
Websocket Monitoring not marking item as finished watched in real time

### ISSUE THREAD

**Issue by phoniclynx** [Tautulli/Tautulli#992]
**Version:**
1.4.17

**Branch:**
Master

**Commit hash:**
Don't know

**Operating system:**
Synology NAS

**Python version:**
2 and 3

**What you did?**
I turned on the Web Monitoring by WebSocket so I could get a faster response to run some scripts as per a walk through I found. Restarted the service fine. Watched a TV episode and left it as it was.

**What happened?**
PLEX played the movie as per expected and everything showed up in PLEX.py's web interface during the TV show. However when the show finished the show didn't stop being showed as 'still running' Even after an hour it was still being shown as run. I turned off WebSocket monitoring and restarted the service, then PLEXpy decided to mark it as stopped. In the activity logs, it shows the TV episode that was only 42 mins long was running for 174 mins instead. This is throwing out all the graphs. (as a side point can you tell me how to edit the database to give it the correct times?)

**What you expected?**
It to mark the end of the show when the end of the show appeared.

**How can we reproduce your issue?**
Turn on WebSocket.
Watch a TV Episode
Wait for a while after the show has stopped
Turn off WebSocket
Monitor Result

**What are your (relevant) settings?**
Default Install

**Link to logs:**
Sorry, this happened too long ago and I have removed the logs since.

**Comment by JonnyWong16** [comment]
There's a websocket bug (on Plex's side) where it doesn't report the stop events, so it just keeps on going. Sessions are cleared out on restart, so that triggered the stop event and the time was calculated.

Just delete that one history entry from the History tab.

*This is one of the major bugs holding back v2.*

**Comment by phoniclynx** [comment]
Is there a way of modifying it rather than deleting the event?

**Comment by JonnyWong16** [comment]
If you know SQLite commands, then you can modify it through the API.

**Comment by phoniclynx** [comment]
I know some MySQL stuff.. shouldn't be too hard I guess. Where is the
database? What am I looking for? Is there any docco on the API?

**Comment by JonnyWong16** [comment]
https://github.com/JonnyWong16/plexpy/blob/master/API.md#sql

**Comment by rochdev** [comment]
Is this still an issue?

**Comment by phoniclynx** [comment]
This seems to be working as far as I can see.
