### ISSUE TITLE
Resolution types on Graphs not consolidated.

### ISSUE THREAD

**Issue by skunkworker** [Tautulli/Tautulli#993]
The different types of resoloutions on the Graphs are not being consolidated properly, `1080p` is showing up as different than `1080` etc.

**Version:**
1.4.17
**Branch:**
master
**Commit hash:**
e85cdd5609c3f5795baaf2d45c484eb652497ec2
**Operating system:**
Freenas 9.10
**Python version:**
2.7.10 (default, Aug 20 2015, 17:58:19) [GCC 4.2.1 20070831 patched [FreeBSD]]
**What you did?**
Went to the /graphs path
**What happened?**
The graphs are not consolidating the different resoloutions, ex `1080p` and `1080` are separate, `720` and `720p`, `sd` and `SD` etc.
**What you expected?**
That they would be homogenous, only: [`1080p`,`720p`,`SD`] etc.
**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
None relevant
![screenshot 2017-03-12 01 22 08](https://cloud.githubusercontent.com/assets/2637951/23830215/d61a6fb6-06c2-11e7-98dd-29706e602c6b.PNG)
![screenshot 2017-03-12 01 22 06](https://cloud.githubusercontent.com/assets/2637951/23830216/d61d2d50-06c2-11e7-955c-c08a2324edbf.PNG)

**Comment by Hellowlol** [comment]
I think this is because that's how plex reports them.

**Comment by JonnyWong16** [comment]
Yeah there's a change in the Plex API. I will fix it in the future. This is not a priority bug.

**Comment by JonnyWong16** [comment]
Fixed in v2-beta.
