### ISSUE TITLE
Recently added not notifying on all new episodes (Telegram)

### ISSUE THREAD

**Issue by matmuilwijk** [Tautulli/Tautulli#994]
**Version:**
1.4.17
**Branch:**
Master
**Commit hash:**

**Operating system:**
Ubuntu 16.04 (Server edition)
**Python version:**
2.7.12
**What you did?**
Set up runs with Filebot. Torrent client drops series and films in different folders, and filebot sorts these out and puts them in the right directory. Plexpy is set-up with Telegram notifications, and a script notification (Only in case the network-connection goes down)
**What happened?**
After the last PlexPy update some new TV episodes aren't triggering the Newly Added notification. They also don't show up in the logs, but they do show in recently added on Plex and PlexPy.
**What you expected?**
The notification to be triggered, like before.
**How can we reproduce your issue?**

Update PlexPy to current version, add episodes.
**What are your (relevant) settings?**
Localhost PlexPy install, using WebSocket

**Comment by JonnyWong16** [comment]
No logs.

**Comment by matmuilwijk** [comment]
There's nothing to find about them in the logs, that's why I didn't add them... Added are the plexpy log and the PMS log... (Note: in the notification logs, there also wasn't a trigger.)

[plexpy.txt](https://github.com/JonnyWong16/plexpy/files/838765/plexpy.txt)

**Comment by JonnyWong16** [comment]
PlexPy probably just missed them. It's not a perfect system.

**Comment by Kedryn** [comment]
Same problem here. Of few episodes of 5 shows, only one show got notified, for 2 episodes, on telegram. Nothing about the others. And they all are in recently added in PlexPy
