### ISSUE TITLE
Rights errors all the time !

### ISSUE THREAD

**Issue by vincegre** [Tautulli/Tautulli#995]
Hi

I'm running Plexpy 1.4.16 with success on my PMS 1.4.3 but I have an issue. I receive regularly an email from my system about some right issues:
```
/etc/cron.daily/plexupdate:
ERROR: Permissions on some files are too lax for running as root. Files must be owned by root:root and not world-writeable.
Unsafe files found:
/opt/plexpy/lib/dns/rdtypes/nsbase.pyc
/opt/plexpy/lib/dns/rdtypes/IN/A.pyc
/opt/plexpy/lib/dns/rdtypes/ANY/NS.pyc
/opt/plexpy/cache/media_info_5.json
/opt/plexpy/cache/images/c15c2ad71e8659d5dd945441275d3cc1.jpg
/opt/plexpy/cache/images/65bb4ec0384c4ee5a443c3bee65cae68.jpg
/opt/plexpy/cache/images/22b490c53113de84de8ddc54a3cf6393.jpg
/opt/plexpy/cache/images/2e5d6312240df0b4dfc34447ed6213ef.jpg
/opt/plexpy/cache/images/e39092d832b6ace959dc6bfdcd31e04c.jpg
/opt/plexpy/cache/images/6dacd38689ad3dc0a03bd9f321b592c3.jpg
```
And also now when I want to upgrade Plexpy from Webinterface, it looks to do so but when it restarts it's still the same version :(

Plexpy has been installed on Ubuntu 16.04 LTS as deamon (using procedure described here).

Thanks for help

Vincèn

**Comment by Hellowlol** [comment]
Why is you plex update script messing with plexpy folders/files?

**Comment by vincegre** [comment]
Looks like there was a wrong setting in the update script of Plex ! Corrected that part and thanks for it !

Now how to correct my problem of update of Plexpy ? that is no more working (the update process) in web interface :(

**Comment by JonnyWong16** [comment]
Please follow the guidelines: https://github.com/JonnyWong16/plexpy#issues

**Comment by vincegre** [comment]
Sure but I have seen nothing in FAQ and Wiki about that error I get in logs when I try to update :(
`2017-03-14 16:20:20 - INFO    :: MainThread : PlexPy is updating...
2017-03-14 16:20:20 - DEBUG   :: MainThread : Trying to execute: "git pull origin master" with shell in /opt/plexpy
2017-03-14 16:20:21 - DEBUG   :: MainThread : Git output: Depuis https://github.com/JonnyWong16/plexpy
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	CHANGELOG.md
	data/interfaces/default/base.html
	data/interfaces/default/css/plexpy.css
	data/interfaces/default/graphs.html
	data/interfaces/default/images/res/ios/Default-portrait@2x~iphone5.jpg
	data/interfaces/default/images/res/ios/Icon-60.png
	data/interfaces/default/images/res/ios/Icon-60@2x.png
	data/interfaces/default/images/res/ios/Icon-Small-40.png
	data/interfaces/default/images/res/ios/Icon-Small-40@2x.png
	data/interfaces/default/images/res/ios/Icon-Small-50.png
	data/interfaces/default/images/res/ios/Icon-Small-50@2x.png
	data/interfaces/default/info.html
	data/interfaces/default/settings.html
	init-scripts/init.opensuse.systemd
	init-scripts/init.ubuntu.systemd
	plexpy/config.py
	plexpy/graphs.py
	plexpy/notification_handler.py
	plexpy/version.py
	plexpy/webserve.py
Please, commit your changes or stash them before you can merge.
Aborting
Mise à jour 3742f33..e85cdd5
2017-03-14 16:20:21 - INFO    :: MainThread : PlexPy is restarting...`

**Comment by JonnyWong16** [comment]
You're not even trying.

https://i.imgur.com/VKozrwq.png
https://i.imgur.com/FqyFdbt.png
