### ISSUE TITLE
PlexPY API - get_apikey

### ISSUE THREAD

**Issue by royhid** [Tautulli/Tautulli#997]
Hi,
  I am using the API and so far so good. Thanks! 
Just one issue is with the get_apikey. I was hoping with the username and password as paramters I could get the user's apikey but i get an error regarding missing HTTP_USERNAME.

I use: parameters username=<myusername>&password=<mypassowrd>&cmd=get_apikey

I have passed toe apikey as a parameter also (although this defeats the purpose of getting the key) but I get the following error in the log:

	PlexPy APIv2 :: Failed to run get_apikey with {}: 'module' object has no attribute 'HTTP_USERNAME'

I am doing something wrong?

Thanks,
Royhid

**Comment by JonnyWong16** [comment]
There's a bug in the code. Thanks for finding it.

**Comment by Hellowlol** [comment]
My bad :P

**Comment by royhid** [comment]
Thanks! At least i know its not me.
In the mean time i'll get the users to manually put in their key.

**Comment by JonnyWong16** [comment]
I'm not sure what you are doing, but this to to retrieve the PlexPy API key (the same one that you can generate under Settings > Access Control > API). This has nothing to do with your users.

**Comment by royhid** [comment]
I'm using the api to make an app to get some info from PlexPy. The apikey is one of the settings and its a pain to put it in manually. I mean users of my app, not users of Plex.

**Comment by JonnyWong16** [comment]
Ok, but that username and password is your PlexPy *admin* username and password. It's pretty much as good as giving out admin access to your Plex server.

PlexPy login > API key > Plex.tv token > Admin access to your Plex server.

**Comment by royhid** [comment]
Fair point. i'll get them to tyoe it in, also looking at using the camera to read in the key from your screen.

**Comment by JonnyWong16** [comment]
Doesn't matter if they type it in themselves. You just cut down on a step. 

API key > Plex.tv token > Admin access to your Plex server.

**Comment by Hellowlol** [comment]
this was fixed in https://github.com/JonnyWong16/plexpy/commit/a5eb0e7faad7a4b33537c253302ba70621795edb
